-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- NEWS RECORDS 
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION DROP CONSTRAINT FK_PERSON_ID;
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION DROP CONSTRAINT FK_SOURCE_ID;
DROP INDEX  NR_SUBSCRIPTION_IX_UNIQUE ON HOMEPAGE.NR_SUBSCRIPTION;
--DROP INDEX  NR_SOURCE_IX_UNIQUE ON HOMEPAGE.NR_SOURCE ;

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP CONSTRAINT FK_C_COMMENT_ID;

ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT FK_RES_RES_TYPE;
ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT FK_RES_CAT_TYPE;
ALTER TABLE HOMEPAGE.NR_RESOURCE_TYPE DROP RES_TYPE_UNIQUE;
ALTER TABLE HOMEPAGE.NR_FOLLOWS  DROP CONSTRAINT FK_FS_PERSON_ID;
ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP CONSTRAINT FK_FS_RESOURCE_ID;
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW DROP CONSTRAINT FK_COMM_PERSON_ID;

ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW DROP CONSTRAINT FK_COMM_PER_PER_ID;

ALTER TABLE HOMEPAGE.NR_NETWORK DROP CONSTRAINT FK_NTW_PERS_ID;
ALTER TABLE HOMEPAGE.NR_NETWORK DROP CONSTRAINT FK_NTW_COLL_ID;

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP CONSTRAINT FK_RES_PERSON_ID; 
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP CONSTRAINT FK_RES_FRQ_TYPE;
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS DROP CONSTRAINT FK_EMD_PERSON_ID;
ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE DROP CONSTRAINT FRQ_TYPE_UNIQUE;
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO DROP CONSTRAINT FK_TRANCHE_ID;

ALTER TABLE HOMEPAGE.NR_RECOMMENDATION DROP CONSTRAINT FK_RECOMMENDER_ID;

-- BOARDS
ALTER TABLE HOMEPAGE.BOARD_COMMENTS DROP CONSTRAINT FK_BRD_COM_ENTRY;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_OBJ_ENTRY;
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_AUTHOR_ID;

ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP CONSTRAINT FK_CUR_ST_ACTOR_ID;
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP CONSTRAINT FK_CUR_ST_ENTRY_ID;

ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_OWNER;
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_CREATED;
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_LASTUPDATE;

ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT FK_CONTAINER_ID;

ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS 	DROP CONSTRAINT FK_BRD_RECOMMENDER;
ALTER TABLE HOMEPAGE.BOARD_MENTIONS 	DROP CONSTRAINT FK_BRD_MEN_PER_ID;

ALTER TABLE HOMEPAGE.NR_STORIES DROP CONSTRAINT FK_ENTRY_ID;
GO

-----------------------------------------------------------------------------------
-- [START] FK KEY FROM READERS TO STORIES TABLE
-----------------------------------------------------------------------------------
-- DROPing the fk
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS DROP CONSTRAINT FK_RES_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS DROP CONSTRAINT FK_PRF_READERS_STR;
GO		
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS DROP CONSTRAINT FK_COM_READERS_STR;
GO	 
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS DROP CONSTRAINT FK_ACI_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS DROP CONSTRAINT FK_BLG_READERS_STR;
GO	 
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS DROP CONSTRAINT FK_BKM_READERS_STR;
GO	 
ALTER TABLE HOMEPAGE.NR_FILES_READERS DROP CONSTRAINT FK_FIL_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS DROP CONSTRAINT FK_FRM_READERS_STR;
GO	 
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS DROP CONSTRAINT FK_WIK_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_TAGS_READERS DROP CONSTRAINT FK_TAG_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT FK_STA_READERS_STR;
GO	 
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT FK_EXT_READERS_STR;
GO	
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT FK_ACT_READERS_STR;
GO		
ALTER TABLE HOMEPAGE.NR_SAVED_READERS DROP CONSTRAINT FK_SAV_READERS_STR;
GO	 
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW DROP CONSTRAINT FK_DIS_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW DROP CONSTRAINT FK_PRO_READERS_STR;
GO	 
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS DROP CONSTRAINT FK_NOT_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS DROP CONSTRAINT FK_REC_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS DROP CONSTRAINT  FK_TOP_READERS_STR;
GO


ALTER TABLE HOMEPAGE.OAUTH2_CLIENT DROP CONSTRAINT FK_CLIENT_PRO_NAME;
ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING DROP CONSTRAINT FK_BINDING_CLIENT;
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT  DROP CONSTRAINT CLNT_FK;
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT DROP CONSTRAINT CLNT_TOKEN_FK;
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT CONTEXT_CLNT_FK;
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT AUTH_TOKEN_FK;

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT FK_OA1C_PERSON_ID;
ALTER TABLE HOMEPAGE.OAUTH2_TOKEN DROP CONSTRAINT FK_OA2T_PERSON_ID;

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING DROP CONSTRAINT FK_BINDING_WIDGET;
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT DROP CONSTRAINT FK_OA1CL_PERSON_ID;
GO

-----------------------------------------------------------------------------------
-- [END] FK KEY FROM READERS TO STORIES TABLE
-----------------------------------------------------------------------------------

DELETE FROM HOMEPAGE.NR_STORIES;
DELETE FROM HOMEPAGE.NR_ENTRIES;
DELETE FROM HOMEPAGE.NR_ENTRIES_ARCHIVE;

DELETE FROM HOMEPAGE.NR_COMM_SETTINGS;

DELETE FROM HOMEPAGE.DELETED_STORIES_QUEUE;

-- News delete board tables
DELETE FROM HOMEPAGE.BOARD_CURRENT_STATUS;
DELETE FROM HOMEPAGE.BOARD_RECOMMENDATIONS;
DELETE FROM HOMEPAGE.BOARD_OBJECT_REFERENCE;
DELETE FROM HOMEPAGE.BOARD_COMMENTS;
DELETE FROM HOMEPAGE.BOARD_ENTRIES;

-- New delete categories stories
DELETE FROM HOMEPAGE.NR_RESPONSES_READERS;
DELETE FROM HOMEPAGE.NR_PROFILES_READERS;
DELETE FROM HOMEPAGE.NR_COMMUNITIES_READERS;
DELETE FROM HOMEPAGE.NR_ACTIVITIES_READERS;
DELETE FROM HOMEPAGE.NR_BLOGS_READERS;
DELETE FROM HOMEPAGE.NR_BOOKMARKS_READERS;
DELETE FROM HOMEPAGE.NR_FILES_READERS;
DELETE FROM HOMEPAGE.NR_FORUMS_READERS;
DELETE FROM HOMEPAGE.NR_WIKIS_READERS;
DELETE FROM HOMEPAGE.NR_TAGS_READERS;
DELETE FROM HOMEPAGE.NR_STATUS_UPDATE_READERS;
DELETE FROM HOMEPAGE.NR_DISCOVERY_VIEW;
DELETE FROM HOMEPAGE.NR_PROFILES_VIEW;
DELETE FROM HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
DELETE FROM HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
DELETE FROM HOMEPAGE.NR_TOPICS_READERS;
 
DELETE FROM HOMEPAGE.NR_AS_SEEDLIST; 
DELETE FROM HOMEPAGE.NR_AS_COLLECTION_CONFIG; 
DELETE FROM HOMEPAGE.NR_AS_CRAWLER_STATUS; 

-- NEWS deletion
DELETE FROM HOMEPAGE.NR_NEWS_RECORDS;
DELETE FROM HOMEPAGE.NR_SUBSCRIPTION;
DELETE FROM HOMEPAGE.NR_SOURCE;
DELETE FROM HOMEPAGE.NR_TEMPLATE;

DELETE FROM HOMEPAGE.NR_CATEGORY_TYPE;
DELETE FROM HOMEPAGE.NR_NEWS_SAVED;
DELETE FROM HOMEPAGE.NR_NEWS_DISCOVERY;

DELETE FROM HOMEPAGE.NR_NEWS_COMMENT_CONTENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_CONTENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_COMMENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_NETWORK;

DELETE FROM HOMEPAGE.NR_AGGREGATED_READERS;
DELETE FROM HOMEPAGE.NR_COMM_PERSON_FOLLOW;
DELETE FROM HOMEPAGE.NR_NETWORK;
DELETE FROM HOMEPAGE.NR_STORIES_CONTENT;

DELETE FROM HOMEPAGE.NR_COMM_FOLLOW;
DELETE FROM HOMEPAGE.NR_FOLLOWS;	
DELETE FROM HOMEPAGE.NR_RESOURCE;
DELETE FROM HOMEPAGE.NR_RESOURCE_TYPE;

-- EMail Digest deletion
DELETE FROM HOMEPAGE.EMD_EMAIL_PREFS;
DELETE FROM HOMEPAGE.EMD_TRANCHE_INFO;
DELETE FROM HOMEPAGE.EMD_TRANCHE;
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF;
DELETE FROM HOMEPAGE.EMD_FREQUENCY_TYPE;

-- Delete notifications NT_NOTIFICATIONs
DELETE FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT;
DELETE FROM HOMEPAGE.NT_NOTIFICATION;

DELETE FROM HOMEPAGE.NR_SOURCE_TYPE;

DELETE FROM HOMEPAGE.NR_RECOMMENDATION;
DELETE FROM HOMEPAGE.NR_ATTACHMENT;    

-- Delete actionable stories
DELETE FROM HOMEPAGE.NR_ACTIONABLE_READERS;
DELETE FROM HOMEPAGE.NR_SAVED_READERS;

DELETE FROM HOMEPAGE.OAUTH2_TOKEN;
DELETE FROM HOMEPAGE.OAUTH2_GADGET_BINDING;
DELETE FROM HOMEPAGE.OAUTH2_CLIENT;
DELETE FROM HOMEPAGE.OAUTH2_PROVIDER;
DELETE FROM HOMEPAGE.OAUTH1_CONTEXT;
DELETE FROM HOMEPAGE.OAUTH1_CLIENT;
DELETE FROM HOMEPAGE.OAUTH1_PROVIDER;
DELETE FROM HOMEPAGE.OAUTH1_TOKEN;

----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
-- REMOVE indexes
 ---------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------


--  [start indexes] NR_AGGREGATED_READERS
DROP  INDEX AGGREGATED_READERS_STR_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_ITM_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_CD_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_SRC_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_RLL_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_RDR_STR 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_RIR_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO



--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
DROP  INDEX RESPONSES_READERS_STR_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_CD_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_RDR_STR 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_RIR_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO



--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
DROP  INDEX PROFILES_READERS_STR_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_CD_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_RDR_STR 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_RIR_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO



--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
DROP  INDEX COMM_READERS_STR_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_ITM_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_CD_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_SRC_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_RLL_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_RDR_STR 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_RIR_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO



--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
DROP  INDEX ACTIVITIES_READERS_STR_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_CD_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_RDR_STR 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_RIR_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO



--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
DROP  INDEX BLOGS_READERS_STR_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_CD_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO



--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
DROP  INDEX BOOKMARKS_READERS_STR_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_CD_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO



--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
DROP  INDEX FILES_READERS_STR_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_CD_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_RDR_STR 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_RIR_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FILES_READERS;
GO



--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
DROP  INDEX FORUMS_READERS_STR_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_CD_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO



--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
DROP  INDEX WIKIS_READERS_STR_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_CD_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO



--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
DROP  INDEX TAGS_READERS_STR_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_CD_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO



--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX STATUS_READERS_STR_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_CD_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO



--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX EXTERNAL_READERS_STR_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_ITM_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_CD_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_SRC_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_RLL_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_RDR_STR 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_RIR_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO



--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_SAVED_READERS
DROP  INDEX SAVED_READERS_STR_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_ITM_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_CD_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_SRC_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_RLL_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_RDR_STR 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_RIR_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_SR_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO


--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX ACTIONABLE_READERS_STR_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_ITM_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_CD_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_SRC_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_RLL_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_RDR_STR 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_RIR_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO



--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
DROP  INDEX DISCOVERY_VIEW_STR_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_CD_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO


DROP  INDEX DISCOVERY_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_ROLLUP_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_RIR_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO


DROP  INDEX DISCOVERY_VIEW_ACT_CD_VIS_IDX  
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX PROFILES_VIEW_STR_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_CD_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_RDR_STR 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_ROLLUP_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_RIR_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO



--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX NOTIFICA_READERS_STR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_ITM_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_CD_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_RDR_STR 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_RIR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO



--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP  INDEX NOT_REC_READERS_STR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_ITM_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_CD_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_RDR_STR 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_RIR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO



--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_TOPICS_READERS
DROP  INDEX TOPICS_READERS_STR_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_CD_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO



--  [end indexes] NR_TOPICS_READERS




----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
-- REMOVE indexes
 ---------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
