-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- NEWS RECORDS 
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);
	
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT FK_SOURCE_ID FOREIGN KEY (SOURCE_ID)
	REFERENCES HOMEPAGE.NR_SOURCE (SOURCE_ID);

CREATE UNIQUE INDEX NR_SUBSCRIPTION_IX_UNIQUE
	ON HOMEPAGE.NR_SUBSCRIPTION(PERSON_ID ASC, SOURCE_ID ASC);

--CREATE UNIQUE INDEX NR_SOURCE_IX_UNIQUE
--	ON HOMEPAGE.NR_SOURCE(SOURCE ASC, CONTAINER_ID ASC, ENTRY_ID ASC);

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT
  	ADD CONSTRAINT FK_C_COMMENT_ID FOREIGN KEY (NEWS_STATUS_COMMENT_ID)
	REFERENCES HOMEPAGE.NR_NEWS_STATUS_COMMENT(NEWS_STATUS_COMMENT_ID);
	
ALTER TABLE HOMEPAGE.NR_RESOURCE_TYPE 
	ADD CONSTRAINT RES_TYPE_UNIQUE UNIQUE (RESOURCE_TYPE);

ALTER TABLE HOMEPAGE.NR_RESOURCE
    ADD CONSTRAINT FK_RES_RES_TYPE FOREIGN KEY (RESOURCE_TYPE)
	REFERENCES HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE);
	
ALTER TABLE HOMEPAGE.NR_RESOURCE
    ADD CONSTRAINT FK_RES_CAT_TYPE FOREIGN KEY (CATEGORY_TYPE)
	REFERENCES HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE);
	
ALTER TABLE HOMEPAGE.NR_FOLLOWS
    ADD CONSTRAINT FK_FS_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_FOLLOWS
    ADD CONSTRAINT FK_FS_RESOURCE_ID FOREIGN KEY (RESOURCE_ID)
	REFERENCES HOMEPAGE.NR_RESOURCE (RESOURCE_ID);

ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW
    ADD CONSTRAINT FK_COMM_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD CONSTRAINT FK_NTW_PERS_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD CONSTRAINT FK_NTW_COLL_ID FOREIGN KEY (COLLEAGUE_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW
    ADD CONSTRAINT FK_COMM_PER_PER_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE
	ADD CONSTRAINT FRQ_TYPE_UNIQUE UNIQUE (FREQUENCY_TYPE);
	
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF
    ADD CONSTRAINT FK_RES_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF
    ADD CONSTRAINT FK_RES_FRQ_TYPE FOREIGN KEY (FREQUENCY_TYPE)
	REFERENCES HOMEPAGE.EMD_FREQUENCY_TYPE (FREQUENCY_TYPE);
	
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS
    ADD CONSTRAINT FK_EMD_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
    ADD CONSTRAINT FK_TRANCHE_ID FOREIGN KEY (TRANCHE_ID)
	REFERENCES HOMEPAGE.EMD_TRANCHE (TRANCHE_ID);

ALTER TABLE HOMEPAGE.NR_RECOMMENDATION
  	ADD CONSTRAINT FK_RECOMMENDER_ID FOREIGN KEY (RECOMMENDER_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

-- BOARDS
ALTER TABLE HOMEPAGE.BOARD_COMMENTS
	ADD CONSTRAINT FK_BRD_COM_ENTRY FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT FK_BRD_OBJ_ENTRY FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT FK_BRD_AUTHOR_ID FOREIGN KEY (AUTHOR_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS
	ADD CONSTRAINT FK_CUR_ST_ACTOR_ID FOREIGN KEY (ACTOR_UUID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);

ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS
	ADD CONSTRAINT FK_CUR_ST_ENTRY_ID FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES(ENTRY_ID);

ALTER TABLE HOMEPAGE.BOARD 
	ADD CONSTRAINT FK_BRD_OWNER FOREIGN KEY (BOARD_OWNER_ASSOC_ID) 
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.BOARD 
	ADD CONSTRAINT FK_BRD_CREATED FOREIGN KEY (CREATED_BY) 
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);	

ALTER TABLE HOMEPAGE.BOARD 
	ADD CONSTRAINT FK_BRD_LASTUPDATE FOREIGN KEY (LASTUPDATE_BY) 
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);


ALTER TABLE HOMEPAGE.BOARD_ENTRIES
	ADD CONSTRAINT FK_CONTAINER_ID FOREIGN KEY (CONTAINER_ID) 
	REFERENCES HOMEPAGE.BOARD (BOARD_CONTAINER_ID);	

-- BOARD_RECOMMENDATIONS
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS
	ADD CONSTRAINT FK_BRD_RECOMMENDER FOREIGN KEY (RECOMMENDER_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.BOARD_MENTIONS
	ADD CONSTRAINT FK_BRD_MEN_PER_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);
	
--GO	

ALTER TABLE HOMEPAGE.NR_STORIES
  	ADD CONSTRAINT FK_ENTRY_ID FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES (ENTRY_ID);  

GO

-----------------------------------------------------------------------------------
-- [START] FK KEY FROM READERS TO STORIES TABLE
-----------------------------------------------------------------------------------
-- adding the fk
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS 
	ADD CONSTRAINT FK_AGG_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS 
	ADD CONSTRAINT FK_RES_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS 
	ADD CONSTRAINT FK_PRF_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO	
	
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ADD CONSTRAINT FK_COM_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO
	 
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ADD CONSTRAINT FK_ACI_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO
	 
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ADD CONSTRAINT FK_BLG_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO
	 
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ADD CONSTRAINT FK_BKM_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO
	 
ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ADD CONSTRAINT FK_FIL_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ADD CONSTRAINT FK_FRM_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO
	 
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ADD CONSTRAINT FK_WIK_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ADD CONSTRAINT FK_TAG_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS
	ADD CONSTRAINT FK_STA_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO	
	 
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS
	ADD CONSTRAINT FK_EXT_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO	
	
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS
	ADD CONSTRAINT FK_ACT_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO	
	
ALTER TABLE HOMEPAGE.NR_SAVED_READERS
	ADD CONSTRAINT FK_SAV_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO
	 
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW
	ADD CONSTRAINT FK_DIS_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW
	ADD CONSTRAINT FK_PRO_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO
	 
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS
	ADD CONSTRAINT FK_NOT_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
	ADD CONSTRAINT FK_REC_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);    
GO

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS
	ADD CONSTRAINT FK_TOP_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID); 

GO
-----------------------------------------------------------------------------------
-- [END] FK KEY FROM READERS TO STORIES TABLE
-----------------------------------------------------------------------------------

-----------------------------------------------------------
ALTER TABLE HOMEPAGE.OAUTH2_CLIENT
  ADD CONSTRAINT FK_CLIENT_PRO_NAME FOREIGN KEY(PROVIDER_NAME)
  REFERENCES HOMEPAGE.OAUTH2_PROVIDER(NAME)
    
ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING
  ADD CONSTRAINT FK_BINDING_CLIENT FOREIGN KEY(CLIENT_NAME)
  REFERENCES HOMEPAGE.OAUTH2_CLIENT(NAME);


-- OAUTH1 CLIENT TABLE
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT 
	ADD CONSTRAINT CLNT_FK FOREIGN KEY (PROVIDERID) 
	REFERENCES HOMEPAGE.OAUTH1_PROVIDER(ID);
	
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT 
	ADD CONSTRAINT CLNT_TOKEN_FK FOREIGN KEY (TOKENID) 
	REFERENCES HOMEPAGE.OAUTH1_TOKEN(ID);

-- OAUTH1 CONTEXT
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT CONTEXT_CLNT_FK FOREIGN KEY (CLIENTID) 
	REFERENCES HOMEPAGE.OAUTH1_CLIENT(ID);

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT AUTH_TOKEN_FK FOREIGN KEY (TOKENID) 
	REFERENCES HOMEPAGE.OAUTH1_TOKEN(ID);
	
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT FK_OA1C_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);	

ALTER TABLE HOMEPAGE.OAUTH2_TOKEN
	ADD CONSTRAINT FK_OA2T_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);
	
GO

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING
  ADD CONSTRAINT FK_BINDING_WIDGET FOREIGN KEY(WIDGET_ID) REFERENCES HOMEPAGE.WIDGET(WIDGET_ID);

ALTER TABLE HOMEPAGE.OAUTH1_CLIENT
  ADD CONSTRAINT FK_OA1CL_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON(PERSON_ID);	
  
GO 	
-----------------------------------------------------------  
  

-- Delete content from news scheduler tables
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMPR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMGR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TREG;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TASK;		

-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- ADD INDEXES
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------


--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX AGGREGATED_READERS_STR_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID); 
GO

CREATE  INDEX AGGREGATED_READERS_ITM_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ITEM_ID); 
GO

CREATE  INDEX AGGREGATED_READERS_CD_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX AGGREGATED_READERS_SRC_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX AGGREGATED_READERS_RLL_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX AGGREGATED_READERS_RDR_STR 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX AGGREGATED_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX AGGREGATED_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX AGGREGATED_READERS_RIR_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX AGGREGATED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX RESPONSES_READERS_STR_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (STORY_ID); 
GO

CREATE  INDEX RESPONSES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ITEM_ID); 
GO

CREATE  INDEX RESPONSES_READERS_CD_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX RESPONSES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX RESPONSES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX RESPONSES_READERS_RDR_STR 
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX RESPONSES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX RESPONSES_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX RESPONSES_READERS_RIR_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX RESPONSES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX PROFILES_READERS_STR_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (STORY_ID); 
GO

CREATE  INDEX PROFILES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (ITEM_ID); 
GO

CREATE  INDEX PROFILES_READERS_CD_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX PROFILES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX PROFILES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX PROFILES_READERS_RDR_STR 
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX PROFILES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX PROFILES_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX PROFILES_READERS_RIR_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX PROFILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX COMM_READERS_STR_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (STORY_ID); 
GO

CREATE  INDEX COMM_READERS_ITM_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ITEM_ID); 
GO

CREATE  INDEX COMM_READERS_CD_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX COMM_READERS_SRC_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX COMM_READERS_RLL_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX COMM_READERS_RDR_STR 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX COMM_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (CREATION_DATE DESC, IS_BROADCAST); 
GO

CREATE  INDEX COMM_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX COMM_READERS_RIR_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX COMM_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX ACTIVITIES_READERS_STR_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (STORY_ID); 
GO

CREATE  INDEX ACTIVITIES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ITEM_ID); 
GO

CREATE  INDEX ACTIVITIES_READERS_CD_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX ACTIVITIES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX ACTIVITIES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX ACTIVITIES_READERS_RDR_STR 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX ACTIVITIES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX ACTIVITIES_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX ACTIVITIES_READERS_RIR_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX ACTIVITIES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX BLOGS_READERS_STR_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (STORY_ID); 
GO

CREATE  INDEX BLOGS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (ITEM_ID); 
GO

CREATE  INDEX BLOGS_READERS_CD_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX BLOGS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX BLOGS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX BLOGS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX BLOGS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX BLOGS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX BLOGS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX BLOGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX BOOKMARKS_READERS_STR_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (STORY_ID); 
GO

CREATE  INDEX BOOKMARKS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ITEM_ID); 
GO

CREATE  INDEX BOOKMARKS_READERS_CD_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX BOOKMARKS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX BOOKMARKS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX BOOKMARKS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX BOOKMARKS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX BOOKMARKS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX BOOKMARKS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX BOOKMARKS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX FILES_READERS_STR_IX 
 	ON HOMEPAGE.NR_FILES_READERS (STORY_ID); 
GO

CREATE  INDEX FILES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_FILES_READERS (ITEM_ID); 
GO

CREATE  INDEX FILES_READERS_CD_IX 
 	ON HOMEPAGE.NR_FILES_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX FILES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX FILES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX FILES_READERS_RDR_STR 
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX FILES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_FILES_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX FILES_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX FILES_READERS_RIR_IX 
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX FILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX FORUMS_READERS_STR_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (STORY_ID); 
GO

CREATE  INDEX FORUMS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (ITEM_ID); 
GO

CREATE  INDEX FORUMS_READERS_CD_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX FORUMS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX FORUMS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX FORUMS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX FORUMS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX FORUMS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX FORUMS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX FORUMS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX WIKIS_READERS_STR_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (STORY_ID); 
GO

CREATE  INDEX WIKIS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (ITEM_ID); 
GO

CREATE  INDEX WIKIS_READERS_CD_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX WIKIS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX WIKIS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX WIKIS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX WIKIS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX WIKIS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX WIKIS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX WIKIS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX TAGS_READERS_STR_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (STORY_ID); 
GO

CREATE  INDEX TAGS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (ITEM_ID); 
GO

CREATE  INDEX TAGS_READERS_CD_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX TAGS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX TAGS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX TAGS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX TAGS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX TAGS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX TAGS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX TAGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX STATUS_READERS_STR_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID); 
GO

CREATE  INDEX STATUS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ITEM_ID); 
GO

CREATE  INDEX STATUS_READERS_CD_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX STATUS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX STATUS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX STATUS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX STATUS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX STATUS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX STATUS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX STATUS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX EXTERNAL_READERS_STR_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID); 
GO

CREATE  INDEX EXTERNAL_READERS_ITM_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ITEM_ID); 
GO

CREATE  INDEX EXTERNAL_READERS_CD_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX EXTERNAL_READERS_SRC_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX EXTERNAL_READERS_RLL_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX EXTERNAL_READERS_RDR_STR 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX EXTERNAL_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX EXTERNAL_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX EXTERNAL_READERS_RIR_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX EXTERNAL_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX SAVED_READERS_STR_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID); 
GO

CREATE  INDEX SAVED_READERS_ITM_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (ITEM_ID); 
GO

CREATE  INDEX SAVED_READERS_CD_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX SAVED_READERS_SRC_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX SAVED_READERS_RLL_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX SAVED_READERS_RDR_STR 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX SAVED_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX SAVED_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX SAVED_READERS_RIR_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX SAVED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

CREATE  INDEX SAVED_READERS_SR_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, READER_ID); 
GO


--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX ACTIONABLE_READERS_STR_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID); 
GO

CREATE  INDEX ACTIONABLE_READERS_ITM_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ITEM_ID); 
GO

CREATE  INDEX ACTIONABLE_READERS_CD_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX ACTIONABLE_READERS_SRC_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX ACTIONABLE_READERS_RLL_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX ACTIONABLE_READERS_RDR_STR 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX ACTIONABLE_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX ACTIONABLE_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX ACTIONABLE_READERS_RIR_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX ACTIONABLE_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX DISCOVERY_VIEW_STR_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID); 
GO

CREATE  INDEX DISCOVERY_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ITEM_ID); 
GO

CREATE  INDEX DISCOVERY_VIEW_CD_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX DISCOVERY_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX DISCOVERY_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_VISIBLE, USE_IN_ROLLUP); 
GO


CREATE  INDEX DISCOVERY_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, IS_BROADCAST); 
GO

CREATE  INDEX DISCOVERY_VIEW_ROLLUP_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_ENTRY_ID); 
GO

CREATE  INDEX DISCOVERY_VIEW_RIR_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX DISCOVERY_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO


CREATE  INDEX DISCOVERY_VIEW_ACT_CD_VIS_IDX  
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ACTOR_UUID, CREATION_DATE DESC, IS_VISIBLE); 
GO

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX PROFILES_VIEW_STR_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID); 
GO

CREATE  INDEX PROFILES_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ITEM_ID); 
GO

CREATE  INDEX PROFILES_VIEW_CD_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX PROFILES_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX PROFILES_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX PROFILES_VIEW_RDR_STR 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, STORY_ID); 
GO

CREATE  INDEX PROFILES_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (CREATION_DATE DESC, IS_BROADCAST); 
GO

CREATE  INDEX PROFILES_VIEW_ROLLUP_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX PROFILES_VIEW_RIR_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX PROFILES_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX NOTIFICA_READERS_STR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID); 
GO

CREATE  INDEX NOTIFICA_READERS_ITM_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ITEM_ID); 
GO

CREATE  INDEX NOTIFICA_READERS_CD_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX NOTIFICA_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX NOTIFICA_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX NOTIFICA_READERS_RDR_STR 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX NOTIFICA_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX NOTIFICA_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX NOTIFICA_READERS_RIR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX NOTIFICA_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX NOT_REC_READERS_STR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID); 
GO

CREATE  INDEX NOT_REC_READERS_ITM_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ITEM_ID); 
GO

CREATE  INDEX NOT_REC_READERS_CD_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX NOT_REC_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX NOT_REC_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX NOT_REC_READERS_RDR_STR 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX NOT_REC_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX NOT_REC_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX NOT_REC_READERS_RIR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX NOT_REC_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX TOPICS_READERS_STR_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID); 
GO

CREATE  INDEX TOPICS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ITEM_ID); 
GO

CREATE  INDEX TOPICS_READERS_CD_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, CREATION_DATE DESC); 
GO

CREATE  INDEX TOPICS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

CREATE  INDEX TOPICS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX TOPICS_READERS_RDR_STR 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, STORY_ID); 
GO

CREATE  INDEX TOPICS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (CREATION_DATE DESC); 
GO

CREATE  INDEX TOPICS_READERS_ROLLUP_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID); 
GO

CREATE  INDEX TOPICS_READERS_RIR_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC); 
GO

CREATE  INDEX TOPICS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO



--  [end indexes] NR_TOPICS_READERS



-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------
-- ADD INDEXES
-----------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------