-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- NEWS RECORDS 
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);
	
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT FK_SOURCE_ID FOREIGN KEY (SOURCE_ID)
	REFERENCES HOMEPAGE.NR_SOURCE (SOURCE_ID);

CREATE UNIQUE INDEX NR_SUBSCRIPTION_IX_UNIQUE
	ON HOMEPAGE.NR_SUBSCRIPTION(PERSON_ID ASC, SOURCE_ID ASC);

--CREATE UNIQUE INDEX NR_SOURCE_IX_UNIQUE
--	ON HOMEPAGE.NR_SOURCE(SOURCE ASC, CONTAINER_ID ASC, ENTRY_ID ASC);

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT
  	ADD CONSTRAINT FK_C_COMMENT_ID FOREIGN KEY (NEWS_STATUS_COMMENT_ID)
	REFERENCES HOMEPAGE.NR_NEWS_STATUS_COMMENT(NEWS_STATUS_COMMENT_ID);
	
ALTER TABLE HOMEPAGE.NR_RESOURCE_TYPE 
	ADD CONSTRAINT RES_TYPE_UNIQUE UNIQUE (RESOURCE_TYPE);

ALTER TABLE HOMEPAGE.NR_RESOURCE
    ADD CONSTRAINT FK_RES_RES_TYPE FOREIGN KEY (RESOURCE_TYPE)
	REFERENCES HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE);
	
ALTER TABLE HOMEPAGE.NR_RESOURCE
    ADD CONSTRAINT FK_RES_CAT_TYPE FOREIGN KEY (CATEGORY_TYPE)
	REFERENCES HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE);
	
ALTER TABLE HOMEPAGE.NR_FOLLOWS
    ADD CONSTRAINT FK_FS_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_FOLLOWS
    ADD CONSTRAINT FK_FS_RESOURCE_ID FOREIGN KEY (RESOURCE_ID)
	REFERENCES HOMEPAGE.NR_RESOURCE (RESOURCE_ID);

ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW
    ADD CONSTRAINT FK_COMM_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_ORGPERSON_FOLLOW
    ADD CONSTRAINT FK_ORGP_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_COMM_STORIES
    ADD CONSTRAINT FK_COMM_STORY_ID FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_ORGPERSON_STORIES
    ADD CONSTRAINT FK_ORGP_STORY_ID FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD CONSTRAINT FK_NTW_PERS_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD CONSTRAINT FK_NTW_COLL_ID FOREIGN KEY (COLLEAGUE_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW
    ADD CONSTRAINT FK_COMM_PER_PER_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_COMM_PERSON_STORIES
    ADD CONSTRAINT FK_FCP_STORY_ID FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);	

ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE
	ADD CONSTRAINT FRQ_TYPE_UNIQUE UNIQUE (FREQUENCY_TYPE);
	
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF
    ADD CONSTRAINT FK_RES_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF
    ADD CONSTRAINT FK_RES_FRQ_TYPE FOREIGN KEY (FREQUENCY_TYPE)
	REFERENCES HOMEPAGE.EMD_FREQUENCY_TYPE (FREQUENCY_TYPE);
	
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS
    ADD CONSTRAINT FK_EMD_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
    ADD CONSTRAINT FK_TRANCHE_ID FOREIGN KEY (TRANCHE_ID)
	REFERENCES HOMEPAGE.EMD_TRANCHE (TRANCHE_ID);

ALTER TABLE HOMEPAGE.NR_RESPONSES_STORIES
    ADD CONSTRAINT FK_RESP_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_PROFILES_STORIES 
    ADD CONSTRAINT FK_PROF_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_STORIES
    ADD CONSTRAINT FK_COM_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_STORIES
    ADD CONSTRAINT FK_ACT_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_BLOGS_STORIES
    ADD CONSTRAINT FK_BLOGS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_STORIES
    ADD CONSTRAINT FK_BOOKS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_FILES_STORIES
    ADD CONSTRAINT FK_FILES_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_FORUMS_STORIES
    ADD CONSTRAINT FK_FORUMS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_WIKIS_STORIES
    ADD CONSTRAINT FK_WIKIS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_TAGS_STORIES
    ADD CONSTRAINT FK_TAGS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);	
	
-- Delete content from news scheduler tables
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMPR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMGR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TREG;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TASK;		