-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

--NEWS

UPDATE STATISTICS HOMEPAGE.NR_SOURCE;
GO

UPDATE STATISTICS HOMEPAGE.NR_SUBSCRIPTION;
GO

UPDATE STATISTICS HOMEPAGE.NR_NEWS_RECORDS;
GO

UPDATE STATISTICS HOMEPAGE.NR_TEMPLATE;
GO

UPDATE STATISTICS  HOMEPAGE.NR_SCHEDULER_LMGR;
GO

UPDATE STATISTICS  HOMEPAGE.NR_SCHEDULER_LMPR;
GO

UPDATE STATISTICS  HOMEPAGE.NR_SCHEDULER_TASK;
GO

UPDATE STATISTICS  HOMEPAGE.NR_SCHEDULER_TREG;
GO

UPDATE STATISTICS  HOMEPAGE.NR_CATEGORY_TYPE;
GO

UPDATE STATISTICS  HOMEPAGE.NR_NEWS_SAVED;
GO

UPDATE STATISTICS  HOMEPAGE.NR_NEWS_DISCOVERY;
GO

UPDATE STATISTICS  HOMEPAGE.NR_NEWS_COMMENT_CONTENT;
GO

UPDATE STATISTICS  HOMEPAGE.NR_NEWS_STATUS_CONTENT;
GO

UPDATE STATISTICS  HOMEPAGE.NR_NEWS_STATUS_COMMENT;
GO

UPDATE STATISTICS  HOMEPAGE.NR_NEWS_STATUS_NETWORK;
GO

UPDATE STATISTICS  HOMEPAGE.NR_NETWORK;	
GO
UPDATE STATISTICS  HOMEPAGE.NR_STORIES_CONTENT;
GO

UPDATE STATISTICS  HOMEPAGE.NR_COMM_FOLLOW;
GO
UPDATE STATISTICS  HOMEPAGE.NR_FOLLOWS;	
GO
UPDATE STATISTICS  HOMEPAGE.NR_RESOURCE;
GO
UPDATE STATISTICS  HOMEPAGE.NR_RESOURCE_TYPE;	
GO
UPDATE STATISTICS  HOMEPAGE.NR_COMM_PERSON_FOLLOW;
GO
UPDATE STATISTICS  HOMEPAGE.NR_AGGREGATED_READERS;	
GO

UPDATE STATISTICS HOMEPAGE.EMD_FREQUENCY_TYPE;
GO
UPDATE STATISTICS HOMEPAGE.EMD_RESOURCE_PREF;
GO
UPDATE STATISTICS HOMEPAGE.EMD_TRANCHE;
GO
UPDATE STATISTICS HOMEPAGE.EMD_TRANCHE_INFO;
GO
UPDATE STATISTICS HOMEPAGE.EMD_EMAIL_PREFS;
GO

UPDATE STATISTICS HOMEPAGE.NR_RESPONSES_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_PROFILES_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_COMMUNITIES_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_ACTIVITIES_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_BLOGS_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_BOOKMARKS_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_FILES_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_FORUMS_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_WIKIS_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_TAGS_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_TAGS_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO



UPDATE STATISTICS HOMEPAGE.NR_RECOMMENDATION;
GO
UPDATE STATISTICS HOMEPAGE.NR_ATTACHMENT;    
GO

-- BOARD USE CASE
UPDATE STATISTICS HOMEPAGE.BOARD_ENTRIES;
GO
UPDATE STATISTICS HOMEPAGE.BOARD_COMMENTS;   
GO
UPDATE STATISTICS HOMEPAGE.BOARD_OBJECT_REFERENCE;  
GO
UPDATE STATISTICS HOMEPAGE.BOARD_RECOMMENDATIONS;
GO
UPDATE STATISTICS HOMEPAGE.BOARD;
GO

UPDATE STATISTICS HOMEPAGE.NR_ACTIONABLE_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_SAVED_READERS;
GO

UPDATE STATISTICS HOMEPAGE.NR_DISCOVERY_VIEW;
GO
UPDATE STATISTICS HOMEPAGE.NR_PROFILES_VIEW;
GO
UPDATE STATISTICS HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO
UPDATE STATISTICS HOMEPAGE.NR_TOPICS_READERS;
GO

UPDATE STATISTICS HOMEPAGE.NR_COMM_SETTINGS;
GO

UPDATE STATISTICS HOMEPAGE.NR_ENTRIES;
GO

UPDATE STATISTICS HOMEPAGE.NR_ENTRIES_ARCHIVE;
GO

UPDATE STATISTICS HOMEPAGE.NR_STORIES;
GO

UPDATE STATISTICS HOMEPAGE.OAUTH2_CLIENT;
UPDATE STATISTICS HOMEPAGE.OAUTH2_GADGET_BINDING;
UPDATE STATISTICS HOMEPAGE.OAUTH1_CLIENT;
UPDATE STATISTICS HOMEPAGE.OAUTH1_CLIENT;
UPDATE STATISTICS HOMEPAGE.OAUTH1_CONTEXT;
UPDATE STATISTICS HOMEPAGE.OAUTH1_CONTEXT;
GO

UPDATE STATISTICS HOMEPAGE.NR_AS_SEEDLIST;
UPDATE STATISTICS HOMEPAGE.NR_AS_COLLECTION_CONFIG;
UPDATE STATISTICS HOMEPAGE.NR_AS_CRAWLER_STATUS;


