-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- NEWS REPOSITORY
{SQL_GRANT_START} HOMEPAGE.NR_SOURCE {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_TEMPLATE {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMGR {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMPR {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_SCHEDULER_TASK {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_SCHEDULER_TREG {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.NR_CATEGORY_TYPE {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_NETWORK {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_COMMENT {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_CONTENT {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_COMMENT_CONTENT {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.NR_RESOURCE_TYPE  {SQL_GRANT_STOP}	
{SQL_GRANT_START} HOMEPAGE.NR_RESOURCE  {SQL_GRANT_STOP}  
{SQL_GRANT_START} HOMEPAGE.NR_FOLLOWS  {SQL_GRANT_STOP}	
{SQL_GRANT_START} HOMEPAGE.NR_COMM_FOLLOW  {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.NR_STORIES_CONTENT  {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_NETWORK  {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_COMM_PERSON_FOLLOW {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_AGGREGATED_READERS {SQL_GRANT_STOP}	

{SQL_GRANT_START} HOMEPAGE.EMD_FREQUENCY_TYPE {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.EMD_RESOURCE_PREF {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.EMD_TRANCHE {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.EMD_TRANCHE_INFO {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.EMD_EMAIL_PREFS {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.NR_RESPONSES_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_PROFILES_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_COMMUNITIES_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_ACTIVITIES_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_BLOGS_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_BOOKMARKS_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_FILES_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_FORUMS_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_WIKIS_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_TAGS_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_STATUS_UPDATE_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_EXTERNAL_READERS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_MENTIONS_READERS {SQL_GRANT_STOP} 

{SQL_GRANT_START} HOMEPAGE.NR_CATEGORIES_READERS {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.NR_SOURCE_TYPE {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.NR_SOURCE_TYPE_DEFAULT {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.BOARD {SQL_GRANT_STOP}

-- BOARD USE CASE
{SQL_GRANT_START} HOMEPAGE.BOARD_ENTRIES {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.BOARD_COMMENTS {SQL_GRANT_STOP}   
{SQL_GRANT_START} HOMEPAGE.BOARD_OBJECT_REFERENCE {SQL_GRANT_STOP}   
{SQL_GRANT_START} HOMEPAGE.BOARD_RECOMMENDATIONS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.BOARD_CURRENT_STATUS {SQL_GRANT_STOP}
{SQL_GRANT_START} HOMEPAGE.BOARD_MENTIONS {SQL_GRANT_STOP}

{SQL_GRANT_START} HOMEPAGE.DELETED_STORIES_QUEUE {SQL_GRANT_STOP}  

{SQL_GRANT_START} HOMEPAGE.NR_ACTIONABLE_READERS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_SAVED_READERS {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.NR_COMM_SETTINGS {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.NR_DISCOVERY_VIEW {SQL_GRANT_STOP}   
GO
{SQL_GRANT_START} HOMEPAGE.NR_PROFILES_VIEW {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NOTIFICATION_SENT_READERS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_TOPICS_READERS {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.NR_ENTRIES {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_ENTRIES_ARCHIVE {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_STORIES {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.NR_AS_SEEDLIST {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_AS_COLLECTION_CONFIG {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_AS_CRAWLER_STATUS  {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_AS_CONTENT_INDEX_STATS {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.OAUTH1_TOKEN {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.OAUTH1_PROVIDER {SQL_GRANT_STOP} 
GO
{SQL_GRANT_START} HOMEPAGE.OAUTH1_CLIENT {SQL_GRANT_STOP} 
GO
{SQL_GRANT_START} HOMEPAGE.OAUTH1_CONTEXT {SQL_GRANT_STOP} 
GO
{SQL_GRANT_START} HOMEPAGE.OAUTH2_PROVIDER {SQL_GRANT_STOP} 
GO
{SQL_GRANT_START} HOMEPAGE.OAUTH2_CLIENT {SQL_GRANT_STOP} 
GO
{SQL_GRANT_START} HOMEPAGE.OAUTH2_GADGET_BINDING {SQL_GRANT_STOP} 
GO
{SQL_GRANT_START} HOMEPAGE.OAUTH2_TOKEN {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_AS_CONTENT_INDEX_STATS {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.IMG_CACHE {SQL_GRANT_STOP}
GO