-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2017                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-----------------------------------------------------------------------
-- ADDING new HOMEPAGE.MT_ORGANIZATION table
-----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.MT_ORGANIZATION (
    ORGANIZATION_ID VARCHAR2(36) NOT NULL,
    ORGANIZATION_EXID VARCHAR2(36) -- note is nullable for premises IC deployment
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.MT_ORGANIZATION
    ADD (CONSTRAINT PK_ORGANIZATION_ID PRIMARY KEY(ORGANIZATION_ID)  USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
CREATE UNIQUE INDEX HOMEPAGE.UNQ_ORG_EXID
	ON HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_EXID) TABLESPACE "HPNTINDEXTABSPACE";    
    
ALTER TABLE HOMEPAGE.MT_ORGANIZATION ENABLE ROW MOVEMENT;

------------------------------------------------
-- PERSON
------------------------------------------------  
CREATE TABLE HOMEPAGE.PERSON  (
	PERSON_ID VARCHAR2(36) NOT NULL,
	DISPLAYNAME VARCHAR2(256) NOT NULL,
	EXID VARCHAR2(256) NOT NULL,
	USER_MAIL VARCHAR2(256),
	USER_MAIL_LOWER VARCHAR2(256),
	DISPLAYNAME_LOWER VARCHAR2(256),
	STATE NUMBER(5,0) DEFAULT 0 NOT NULL,
	LAST_UPDATE TIMESTAMP,
	SAND_OPT NUMBER(5,0) DEFAULT 1,
	SAND_LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PROF_TYPE VARCHAR2(128),
	CREATION_DATE TIMESTAMP,
	THEME_ID VARCHAR2(36),
	COMM_VISIBILITY NUMBER(5 ,0),
	MEMBER_TYPE NUMBER(5 ,0) DEFAULT 0 NOT NULL,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000',
	COMMUNITY_INTERNAL_ONLY NUMBER(5 ,0) DEFAULT 1,
	LAST_CONN_VISIT TIMESTAMP,
	PREF_LANG VARCHAR2(5),
	IS_EXTERNAL NUMBER(5,0) DEFAULT 0 NOT NULL,
	HOME_ORG_ID VARCHAR2(36)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.PERSON PCTFREE 30;

ALTER TABLE HOMEPAGE.PERSON 
    ADD (CONSTRAINT "PK_PERSON_ID" PRIMARY KEY ("PERSON_ID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.PERSON ADD CONSTRAINT FK_PERSON_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
    
CREATE UNIQUE INDEX HOMEPAGE.PERSON_EXID_ORG
    ON "HOMEPAGE"."PERSON"("EXID", "ORGANIZATION_ID") TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX HOMEPAGE.PERSON_EMD_CHECK 
	ON HOMEPAGE.PERSON (MEMBER_TYPE, CREATION_DATE ASC, STATE, USER_MAIL_LOWER, PERSON_ID, ORGANIZATION_ID) TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX HOMEPAGE.PERSON_USER_MAIL_LWR
    ON HOMEPAGE.PERSON(USER_MAIL_LOWER ASC) TABLESPACE "HOMEPAGEINDEXTABSPACE";

CREATE INDEX HOMEPAGE.PERSON_DISPLAYNAME_LWR
    ON HOMEPAGE.PERSON(DISPLAYNAME_LOWER ASC) TABLESPACE "HOMEPAGEINDEXTABSPACE";

CREATE INDEX HOMEPAGE.PERSON_LAST_UPDATE
    ON HOMEPAGE.PERSON (LAST_UPDATE DESC) TABLESPACE "HOMEPAGEINDEXTABSPACE";    

CREATE INDEX HOMEPAGE.PERSON_SAND_LAST_UPDATE
    ON HOMEPAGE.PERSON (SAND_LAST_UPDATE ASC) TABLESPACE "HOMEPAGEINDEXTABSPACE";
    
CREATE INDEX HOMEPAGE.DISPLAYNAME_LOWER_MEM
	ON HOMEPAGE.PERSON (DISPLAYNAME_LOWER, MEMBER_TYPE) TABLESPACE "HOMEPAGEINDEXTABSPACE";    

CREATE INDEX HOMEPAGE.PERSON_EXID_PER_ID_IX
	ON HOMEPAGE.PERSON  (EXID, PERSON_ID) TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX HOMEPAGE.PERSON_STATE_MEM_LU_IX
	ON HOMEPAGE.PERSON  (STATE, MEMBER_TYPE,LAST_UPDATE) TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX HOMEPAGE.PERSON_MEM_STATE_IX
	ON HOMEPAGE.PERSON  (MEMBER_TYPE,STATE) TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX HOMEPAGE.PERSON_MEM_SAND_IX
	ON HOMEPAGE.PERSON  (MEMBER_TYPE,SAND_OPT) TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE INDEX HOMEPAGE.PERSON_SND_SR 
	ON HOMEPAGE.PERSON (MEMBER_TYPE, SAND_OPT, SAND_LAST_UPDATE ASC) TABLESPACE "HPNTINDEXTABSPACE";	
	
CREATE INDEX HOMEPAGE.PERSON_SAND_OPT_IDX
    ON HOMEPAGE.PERSON(SAND_OPT, SAND_LAST_UPDATE ASC) TABLESPACE "HOMEPAGEINDEXTABSPACE";  
COMMIT;
    
CREATE INDEX HOMEPAGE.PERSON_STATE_OPT_IDX  
  ON HOMEPAGE.PERSON(MEMBER_TYPE, LAST_UPDATE ASC, STATE, PERSON_ID) TABLESPACE "HOMEPAGEINDEXTABSPACE";
COMMIT;	
   
CREATE INDEX HOMEPAGE.PERSON_LAST_CONN_VISIT
    ON HOMEPAGE.PERSON(LAST_CONN_VISIT DESC) TABLESPACE "HOMEPAGEINDEXTABSPACE";
COMMIT;

CREATE INDEX HOMEPAGE.PERSON_EXID_STATE
	ON HOMEPAGE.PERSON(EXID,STATE) TABLESPACE "HPNTINDEXTABSPACE";
COMMIT;

ALTER TABLE "HOMEPAGE"."PERSON" ENABLE ROW MOVEMENT;

-----------------------------------------------
-- PERSON_ROLE
-----------------------------------------------

CREATE TABLE HOMEPAGE.PERSON_ROLE  (
	PERSON_ROLE_ID VARCHAR2(36) NOT NULL,
	ROLE VARCHAR2(256) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.PERSON_ROLE 
    ADD CONSTRAINT PK_PERSON_ROLE_ID PRIMARY KEY(PERSON_ROLE_ID) USING INDEX TABLESPACE "NEWSINDEXTABSPACE";
    
ALTER TABLE HOMEPAGE.PERSON_ROLE ADD CONSTRAINT FK_PERSON_ROLE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

ALTER TABLE HOMEPAGE.PERSON_ROLE ADD CONSTRAINT FK_PERSON_ROLE_PER_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID);

CREATE INDEX HOMEPAGE.PERSON_ROLE_PER_IDX
    ON HOMEPAGE.PERSON_ROLE (PERSON_ID) TABLESPACE "NEWSINDEXTABSPACE";
    
CREATE INDEX HOMEPAGE.PERSON_ROLE_PER_R_IDX
    ON HOMEPAGE.PERSON_ROLE (PERSON_ID, PERSON_ROLE_ID) TABLESPACE "NEWSINDEXTABSPACE";
    
CREATE UNIQUE INDEX HOMEPAGE.PERSON_ROLE_ROLE_IDX
    ON HOMEPAGE.PERSON_ROLE (PERSON_ID, ROLE) TABLESPACE "NEWSINDEXTABSPACE";



-- LL requirement
------------------------------------------------
-- SNCORE_PERSON
------------------------------------------------  
CREATE VIEW HOMEPAGE.SNCORE_PERSON (SNC_INTERNAL_ID, SNC_IDKEY, SNC_EMAIL_LOWER, SNC_DISPLAY_NAME) 
    AS SELECT PERSON_ID, EXID, USER_MAIL_LOWER, DISPLAYNAME FROM HOMEPAGE.PERSON;	

-----------------------------------------
-- HOMEPAGE.USER_PREFS
-----------------------------------------
CREATE TABLE HOMEPAGE.HP_USER_PREFS (
	USER_PREFS_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	PREF_NAME VARCHAR2(400),
	PREF_VALUE VARCHAR2(1536),
	LAST_UPDATE TIMESTAMP,
	CREATE_DATE TIMESTAMP,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.HP_USER_PREFS
    ADD (CONSTRAINT PK_USER_PREFS_ID PRIMARY KEY(USER_PREFS_ID)  USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.HP_USER_PREFS 
	ADD CONSTRAINT FK_USER_PREFS_PERS_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID);
	
ALTER TABLE HOMEPAGE.HP_USER_PREFS 
	ADD CONSTRAINT FK_USER_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE INDEX HOMEPAGE.USER_PREF_NAME_IDX
	ON HOMEPAGE.HP_USER_PREFS (PREF_NAME) TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX HOMEPAGE.USER_PREF_PER_IDX
	ON  HOMEPAGE.HP_USER_PREFS (PERSON_ID) TABLESPACE "HPNTINDEXTABSPACE";

CREATE UNIQUE INDEX HOMEPAGE.USER_PREF_PER_NAME_UNQ
	ON  HOMEPAGE.HP_USER_PREFS (PERSON_ID, PREF_NAME) TABLESPACE "HPNTINDEXTABSPACE";

COMMIT;

ALTER TABLE HOMEPAGE.HP_USER_PREFS ENABLE ROW MOVEMENT;
COMMIT;

------------------------------------------------
-- LOGINAME
------------------------------------------------
CREATE TABLE HOMEPAGE.LOGINNAME (
	PERSON_ID VARCHAR2(36) NOT NULL,
	LOGINNAME VARCHAR2(256) NOT NULL,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";  

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD (CONSTRAINT "PK_LOGINNAME_ID" PRIMARY KEY ("PERSON_ID","LOGINNAME") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT "FK_LN_PERSON_ID" FOREIGN KEY ("PERSON_ID")	
	REFERENCES "HOMEPAGE"."PERSON" ("PERSON_ID");
	
ALTER TABLE HOMEPAGE.LOGINNAME ADD CONSTRAINT FK_LN_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE UNIQUE INDEX HOMEPAGE.LOGINNAME_UNIQUE
    ON HOMEPAGE.LOGINNAME (LOGINNAME, ORGANIZATION_ID) TABLESPACE "HPNTINDEXTABSPACE";

ALTER TABLE HOMEPAGE.LOGINNAME ENABLE ROW MOVEMENT;

------------------------------------------------
-- HP_UI
------------------------------------------------  
CREATE TABLE HOMEPAGE.HP_UI  (
	UI_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	PERSON_LANG VARCHAR2(5) NOT NULL,
	LAST_VISIT TIMESTAMP NOT NULL,
	WELCOME_MODE NUMBER(5,0) DEFAULT 1 NOT NULL,
	SHOW_DISABLED_WIDGETS NUMBER(5,0) DEFAULT 0 NOT NULL,
	LAST_NOTIFY_VISIT TIMESTAMP,
	LAST_ACTIONABLE_VISIT TIMESTAMP,
	WELCOME_NOTE NUMBER(5,0) DEFAULT 1,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.HP_UI PCTFREE 30;

ALTER TABLE HOMEPAGE.HP_UI
    ADD (CONSTRAINT "PK_HP_UI" PRIMARY KEY ("UI_ID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");   

ALTER TABLE HOMEPAGE.HP_UI
    ADD CONSTRAINT "FK_UI_PERSON_ID" FOREIGN KEY ("PERSON_ID") 
	REFERENCES "HOMEPAGE"."PERSON" ("PERSON_ID");
	
ALTER TABLE HOMEPAGE.HP_UI ADD CONSTRAINT FK_UI_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE UNIQUE INDEX HOMEPAGE.HP_UI_PERSONID
	ON HOMEPAGE.HP_UI (PERSON_ID) TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE INDEX HOMEPAGE.HP_UI_R
	ON HOMEPAGE.HP_UI (LAST_VISIT) REVERSE TABLESPACE "NEWSINDEXTABSPACE";	

CREATE UNIQUE INDEX HOMEPAGE.HP_UI_PERSONID_LANG
   ON HOMEPAGE.HP_UI (PERSON_ID,PERSON_LANG) TABLESPACE "HPNTINDEXTABSPACE";

ALTER TABLE HOMEPAGE.HP_UI ENABLE ROW MOVEMENT;

------------------------------------------------
-- HP_TAB
------------------------------------------------  
CREATE TABLE HOMEPAGE.HP_TAB  (
	TAB_ID VARCHAR2(36) NOT NULL,
	DEFAULT_NAME VARCHAR2(36) NOT NULL,
	DEFAULT_N_COLUMNS NUMBER(5,0),
	IS_NAME_CHANGEABLE NUMBER(5,0),
	ENABLED NUMBER(5,0) DEFAULT 1,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.HP_TAB
    ADD (CONSTRAINT "PK_HP_TAB" PRIMARY KEY("TAB_ID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.HP_TAB ADD CONSTRAINT FK_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
    
ALTER TABLE HOMEPAGE.HP_TAB ENABLE ROW MOVEMENT;

------------------------------------------------
-- HP_TAB_INST
------------------------------------------------  
CREATE TABLE HOMEPAGE.HP_TAB_INST  (
	TAB_INST_ID VARCHAR2(36) NOT NULL,
	TAB_ID VARCHAR2(36) NOT NULL,
	UI_ID VARCHAR2(36) NOT NULL,
	TAB_NAME VARCHAR2(36),
	N_COLUMNS NUMBER(5,0),
	LAST_MODIFIED TIMESTAMP NOT NULL,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.HP_TAB_INST
    ADD (CONSTRAINT "PK_HP_TAB_INST" PRIMARY KEY("TAB_INST_ID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.HP_TAB_INST
    ADD CONSTRAINT "FK_UI_ID" FOREIGN KEY ("UI_ID")
	REFERENCES "HOMEPAGE"."HP_UI" ("UI_ID");

ALTER TABLE HOMEPAGE.HP_TAB_INST
    ADD CONSTRAINT "FK_TAB_INST_TAB_ID" FOREIGN KEY ("TAB_ID")
	REFERENCES "HOMEPAGE"."HP_TAB" ("TAB_ID");
	
ALTER TABLE HOMEPAGE.HP_TAB_INST ADD CONSTRAINT FK_TAB_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE INDEX HOMEPAGE.TAB_INST_UI_ID_IDX 
	ON "HOMEPAGE"."HP_TAB_INST"("UI_ID") TABLESPACE "HPNTINDEXTABSPACE";	

CREATE INDEX HOMEPAGE.TAB_INST_TAB_ID 
	ON HOMEPAGE.HP_TAB_INST (TAB_ID) TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE UNIQUE INDEX HOMEPAGE.HP_TAB_INST_UNQ 
	ON HOMEPAGE.HP_TAB_INST (TAB_ID, UI_ID) TABLESPACE "HPNTINDEXTABSPACE";	
	
ALTER TABLE HOMEPAGE.HP_TAB_INST ENABLE ROW MOVEMENT;

------------------------------------------------
-- WIDGET
------------------------------------------------  
CREATE TABLE HOMEPAGE.WIDGET (
	WIDGET_ID VARCHAR2(36) NOT NULL,
	WIDGET_TITLE VARCHAR2(256) NOT NULL,
	WIDGET_TEXT VARCHAR2(256),
	WIDGET_URL VARCHAR2(256) NOT NULL,
	WIDGET_ICON VARCHAR2(256),
	WIDGET_ENABLED NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_SYSTEM NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_HOMEPAGE_SPECIFIC NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_PREVIEW_IMAGE VARCHAR2(256),
	WIDGET_CATEGORY VARCHAR2(36) DEFAULT ' ' NOT NULL,
	WIDGET_IS_DEFAULT_OPENED NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_MULTIPLE_INSTANCES NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_MARKED_CACHABLE NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_SECURE_URL VARCHAR2(256) DEFAULT '',
	WIDGET_SECURE_ICON VARCHAR2(256) DEFAULT '',
	IS_GADGET NUMBER(5,0) DEFAULT 0,
	WIDGET_POLICY_FLAGS NUMBER(9,0) DEFAULT 1 NOT NULL,
	WIDGET_EXT_PROPERTIES VARCHAR2(2048),
	PROXY_POLICY VARCHAR2(64) DEFAULT 'custom' NOT NULL,
	SHARE_ORDER NUMBER(9,0) DEFAULT -1 NOT NULL,
	SERVER_ACCESS 			CLOB, 
	ADDITIONAL_FEATURES 	CLOB,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
LOB (SERVER_ACCESS) STORE AS (TABLESPACE NEWSLOBTABSPACE STORAGE (INITIAL 1M) CHUNK 4000 NOCACHE NOLOGGING),
LOB (ADDITIONAL_FEATURES) STORE AS (TABLESPACE NEWSLOBTABSPACE STORAGE (INITIAL 1M) CHUNK 4000 NOCACHE NOLOGGING)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.WIDGET
	ADD (CONSTRAINT "PK_WIDGET" PRIMARY KEY ("WIDGET_ID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.WIDGET ADD CONSTRAINT FK_WIDGET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

ALTER TABLE HOMEPAGE.WIDGET ENABLE ROW MOVEMENT;

------------------------------------------------
-- HP_WIDGET_TAB
------------------------------------------------  
CREATE TABLE HOMEPAGE.HP_WIDGET_TAB (
	WIDGET_TAB_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL,
	TAB_ID VARCHAR2(36) NOT NULL,
	TYPE VARCHAR2(36) NOT NULL,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)	
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB
	ADD (CONSTRAINT "PK_WIDGET_TAB" PRIMARY KEY ("WIDGET_TAB_ID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB	
    ADD CONSTRAINT "FK_WID_TAB_WID_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID");
	
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB	
    ADD CONSTRAINT "FK_WID_TAB_TAB_ID" FOREIGN KEY ("TAB_ID")
	REFERENCES "HOMEPAGE"."HP_TAB" ("TAB_ID");

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ADD CONSTRAINT FK_WIDGET_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
	
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ENABLE ROW MOVEMENT;

------------------------------------------------
-- HP_WIDGET_INST
------------------------------------------------  
CREATE TABLE HOMEPAGE.HP_WIDGET_INST  (
	WIDGET_INST_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL,
	TAB_INST_ID VARCHAR2(36) NOT NULL,
	WIDGET_SETTING VARCHAR2(2048),
	CONTAINER VARCHAR2(36),
	ORDER_SEQUENCE NUMBER(5,0),
	IS_FIXED NUMBER(5,0),
	IS_TOGGLED NUMBER(5,0),
	LAST_MODIFIED TIMESTAMP NOT NULL,
	LAST_UPDATED TIMESTAMP,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
	ADD (CONSTRAINT "PK_HP_WIDGET_INST" PRIMARY KEY ("WIDGET_INST_ID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
    ADD CONSTRAINT "FK_WIDGET_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID");
		
ALTER TABLE HOMEPAGE.HP_WIDGET_INST
    ADD CONSTRAINT "FK_TAB_INST_ID" FOREIGN KEY ("TAB_INST_ID") 
	REFERENCES "HOMEPAGE"."HP_TAB_INST" ("TAB_INST_ID");

ALTER TABLE HOMEPAGE.HP_WIDGET_INST ADD CONSTRAINT FK_WIDGET_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
	
CREATE INDEX HOMEPAGE.WIDGET_INST
	ON "HOMEPAGE"."HP_WIDGET_INST"("TAB_INST_ID" ASC, "WIDGET_ID" ASC) TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX HOMEPAGE.HP_WIDGET_INST_TAB_INST_ID_IDX
	ON "HOMEPAGE"."HP_WIDGET_INST"("TAB_INST_ID") TABLESPACE "HPNTINDEXTABSPACE";	
	
CREATE INDEX HOMEPAGE.HP_WIDGET_IDX 
	ON HOMEPAGE.HP_WIDGET_INST (WIDGET_ID)  TABLESPACE "HPNTINDEXTABSPACE";	

ALTER TABLE HOMEPAGE.HP_WIDGET_INST ENABLE ROW MOVEMENT;

------------------------------------------------
-- PREREQ
------------------------------------------------  
CREATE TABLE HOMEPAGE.PREREQ (
	PREREQ_ID VARCHAR2(36) NOT NULL,
	APP_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";	

ALTER TABLE HOMEPAGE.PREREQ 
	ADD (CONSTRAINT "PK_PREREQ" PRIMARY KEY ("PREREQ_ID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.PREREQ
	ADD CONSTRAINT "FK_PREREQ_WIDGET" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID")
	ON DELETE CASCADE;
	
ALTER TABLE HOMEPAGE.PREREQ ADD CONSTRAINT FK_PREREQ_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

ALTER TABLE HOMEPAGE.PREREQ ENABLE ROW MOVEMENT;


----------------------------------------------------------------------
-- HOMEPAGE.NT_REPLYTO
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NT_REPLYTO (
	REPLYTO_NOTIFICATION_ID VARCHAR2(36) NOT NULL,
	SOURCE VARCHAR2(36),
	EVENT_NAME VARCHAR2(256) NOT NULL,
	CONTAINER_ID VARCHAR2(256),	
	ITEM_ID VARCHAR2(36),
	ITEM_CORRELATION_ID VARCHAR2(256),	
	CREATION_DATE TIMESTAMP NOT NULL,
	ACTOR_UUID VARCHAR2(36),
	EVENT_RECORD_UUID VARCHAR2(36) NOT NULL,
	CATEGORY_TYPE NUMBER(5,0),
	SOURCE_TYPE NUMBER(5,0),
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.NT_REPLYTO
    ADD (CONSTRAINT PK_REPLYTO PRIMARY KEY(REPLYTO_NOTIFICATION_ID) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NT_REPLYTO ADD CONSTRAINT FK_REPLYTO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
    
ALTER TABLE HOMEPAGE.NT_REPLYTO ENABLE ROW MOVEMENT;

----------------------------------------------------------------------
-- HOMEPAGE.NT_REPLYTO_RECIPIENT
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT (
	REPLYTO_RECIPIENT_ID VARCHAR2(36) NOT NULL,
	REPLYTO_NOTIFICATION_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,	
	REPLYTO_ID VARCHAR2(36) NOT NULL,
	LAST_UPDATE TIMESTAMP,
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD (CONSTRAINT REPLYTO_RECIP_ID PRIMARY KEY(REPLYTO_RECIPIENT_ID) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD CONSTRAINT FK_REPLYTO_NOT_ID FOREIGN KEY (REPLYTO_NOTIFICATION_ID)
	REFERENCES HOMEPAGE.NT_REPLYTO (REPLYTO_NOTIFICATION_ID);

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD CONSTRAINT FK_REPLYTO_PER_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ADD CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
	
CREATE UNIQUE INDEX HOMEPAGE.REPLYTO_IDX
    ON HOMEPAGE.NT_REPLYTO_RECIPIENT (REPLYTO_ID) TABLESPACE "HPNTINDEXTABSPACE";

    
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ENABLE ROW MOVEMENT;
    
----------------------------------------------------------------------
-- HOMEPAGE.MT_METRICS 
----------------------------------------------------------------------

CREATE TABLE HOMEPAGE.METRIC_STAT  (
      METRIC_STAT_ID VARCHAR2(36) NOT NULL,
      RECORDED_ON TIMESTAMP NOT NULL,
      METRIC_TYPE NUMBER(5,0) NOT NULL,
      METRIC_DESC VARCHAR2(36) NOT NULL,
      RES_BUNDLE_KEY VARCHAR2(144) NOT NULL,
      COUNT_LAST_24_H NUMBER(19 ,0),
      COUNT_LAST_7_D NUMBER(19 ,0),
      COUNT_LAST_1_M NUMBER(19 ,0),
      TOP_STATS VARCHAR2(512),
      TOT_STAT NUMBER(19 ,0),
      AVG_TOT_STAT NUMBER(19 ,0),
      ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000'
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.METRIC_STAT 
    ADD (CONSTRAINT PK_METRIC_STAT_ID PRIMARY KEY(METRIC_STAT_ID) USING INDEX TABLESPACE "HPNTINDEXTABSPACE");

CREATE INDEX HOMEPAGE.METRIC_IDX
    ON HOMEPAGE.METRIC_STAT (RECORDED_ON ASC, METRIC_TYPE) TABLESPACE "HPNTINDEXTABSPACE";
    
ALTER TABLE HOMEPAGE.METRIC_STAT 
	ADD CONSTRAINT FK_METRIC_ORG_ID FOREIGN KEY (ORGANIZATION_ID) 
	REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: OAuth Consumer Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
--
-- Replace							Example
--  HOMEPAGE					HOMEPAGE
--	 		HOMEPAGE.
-- 	IN USERSPACE8K INDEX IN USERSPACE8K
--  LCUSER
--  STMT == End statement
--
-- Types - You will need to substitue these tokens
--  VARCHAR
--  TIMESTAMP



-------------------------------------------
-- HOMEPAGE.OAUTH1_TOKEN
-------------------------------------------	 
CREATE TABLE HOMEPAGE.OAUTH1_TOKEN (
	ID VARCHAR2(256) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
	TOKEN VARCHAR2(1024) NOT NULL,
	SECRET VARCHAR2(1024) NOT NULL,
	EXPIRATION TIMESTAMP,
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH1_TOKEN ENABLE ROW MOVEMENT;

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH1_PROVIDER
-------------------------------------------	 
CREATE TABLE HOMEPAGE.OAUTH1_PROVIDER (
	ID VARCHAR2(256) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
	NAME VARCHAR2(254) NOT NULL,
	DESCRIPTION VARCHAR2(1024),
	REQUESTTOKENURL VARCHAR2(512) NOT NULL,
	AUTHORIZEURL VARCHAR2(512) NOT NULL,
	ACCESSTOKENURL VARCHAR2(512) NOT NULL,
	BASEURL VARCHAR2(512),
	MANAGEURL VARCHAR2(512),
	REGISTERURL VARCHAR2(512),
	SIGNMETHOD VARCHAR2(32),
	VERSION VARCHAR2(8),
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	CONSTRAINT PRVD_NAME_UK UNIQUE (NAME) USING INDEX  TABLESPACE "NEWSINDEXTABSPACE"
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH1_PROVIDER ENABLE ROW MOVEMENT; 

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH1_CLIENT
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH1_CLIENT (
	ID VARCHAR2(256) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
	PERSON_ID VARCHAR2(36) NOT NULL,
	NAME VARCHAR2(254) NOT NULL,
	TOKENID VARCHAR2(256) NOT NULL,
	PROVIDERID VARCHAR2(256) NOT NULL,
	DESCRIPTION VARCHAR2(1024),
	CALLBACKURL VARCHAR2(512),
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	CONSTRAINT CLNT_NAME_UK UNIQUE (NAME) USING INDEX  TABLESPACE "NEWSINDEXTABSPACE"
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH1_CLIENT 
	ADD CONSTRAINT CLNT_FK FOREIGN KEY (PROVIDERID) 
	REFERENCES HOMEPAGE.OAUTH1_PROVIDER(ID);

ALTER TABLE HOMEPAGE.OAUTH1_CLIENT 
	ADD CONSTRAINT CLNT_TOKEN_FK FOREIGN KEY (TOKENID) 
	REFERENCES HOMEPAGE.OAUTH1_TOKEN(ID);
	
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT
	ADD CONSTRAINT FK_OA1CL_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);	
	
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT ENABLE ROW MOVEMENT; 

COMMIT;

------------------------------------------
-- HOMEPAGE.OAUTH1_CONTEXT
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH1_CONTEXT (
	ID VARCHAR2(256) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
	CLIENTID VARCHAR2(256) NOT NULL,
	PERSON_ID VARCHAR2(36),
	TOKENID VARCHAR2(256) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	NONCE VARCHAR2(256),
	EXPIRATION TIMESTAMP,
	AUTHORIZED NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT CONTEXT_CLNT_FK FOREIGN KEY (CLIENTID) 
	REFERENCES HOMEPAGE.OAUTH1_CLIENT(ID);

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT AUTH_TOKEN_FK FOREIGN KEY (TOKENID) 
	REFERENCES HOMEPAGE.OAUTH1_TOKEN(ID);
	
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT FK_OA1C_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);		

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT ENABLE ROW MOVEMENT;

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH2_PROVIDER
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_PROVIDER (
  NAME VARCHAR2(254) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
  CLIENT_AUTH VARCHAR2(254),
  AUTH_HEADER NUMBER(5,0),
  URL_PARAM NUMBER(5,0),
  AUTH_URL VARCHAR2(1024),
  TOKEN_URL VARCHAR2(1024)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH2_PROVIDER ENABLE ROW MOVEMENT;  

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH2_CLIENT
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_CLIENT (
  NAME VARCHAR2(254) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
  PROVIDER_NAME VARCHAR2(254) NOT NULL,
  REDIRECT_URI VARCHAR2(1024),
  CTYPE VARCHAR2(254) NOT NULL,
  GRANT_TYPE VARCHAR2(254) NOT NULL,
  CLIENT_ID VARCHAR2(1024) NOT NULL,
  CLIENT_SECRET VARCHAR2(1024) NOT NULL,
  ALLOWED_DOMAINS VARCHAR2(1024)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH2_CLIENT
  ADD CONSTRAINT FK_CLIENT_PRO_NAME FOREIGN KEY(PROVIDER_NAME)
  REFERENCES HOMEPAGE.OAUTH2_PROVIDER(NAME);
  
ALTER TABLE HOMEPAGE.OAUTH2_CLIENT ENABLE ROW MOVEMENT;   

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH2_GADGET_BINDING
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_GADGET_BINDING (
  ID VARCHAR2(36) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
  WIDGET_ID VARCHAR2(36) NOT NULL,
  URI_SHA1 CHAR(40) NOT NULL, 
  SERVICE_NAME VARCHAR2(254)  NOT NULL,
  URI VARCHAR2(1024) NOT NULL,
  CLIENT_NAME VARCHAR2(254) NOT NULL,
  OVERRIDES NUMBER(5,0) NOT NULL,
  SECURE_URI_SHA1 CHAR(40),
  SECURE_URI VARCHAR2(1024),
  CONSTRAINT WIDGET_GADGET_UK UNIQUE (WIDGET_ID, SERVICE_NAME) USING INDEX  TABLESPACE "NEWSINDEXTABSPACE"
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING
  ADD CONSTRAINT FK_BINDING_CLIENT FOREIGN KEY(CLIENT_NAME)
  REFERENCES HOMEPAGE.OAUTH2_CLIENT(NAME);

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING
  ADD CONSTRAINT FK_BINDING_WIDGET FOREIGN KEY(WIDGET_ID)
  REFERENCES HOMEPAGE.WIDGET(WIDGET_ID);
  
CREATE INDEX OA2T_GBINDING_WID
	ON HOMEPAGE.OAUTH2_GADGET_BINDING (WIDGET_ID) TABLESPACE "HOMEPAGEINDEXTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING ENABLE ROW MOVEMENT;

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH2_TOKEN
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_TOKEN (
  ID VARCHAR2(254) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
  URI VARCHAR2(1024) NOT NULL,
  SERVICE_NAME VARCHAR2(254) NOT NULL,
  PERSON_ID VARCHAR2(36) NOT NULL,
  SCOPE VARCHAR2(1024) NOT NULL,
  TTYPE NUMBER(5,0) NOT NULL,
  SECRET VARCHAR2(1024),
  EXPIRES TIMESTAMP,
  ISSUED TIMESTAMP NOT NULL,
  TOKEN_TYPE VARCHAR2(254),
  MAC_SECRET VARCHAR2(1024),
  MAC_ALG VARCHAR2(254),
  MAC_EXT VARCHAR2(254),
  PROPS VARCHAR2(1024),
  TOKEN_SHA1 CHAR(40)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH2_TOKEN
	ADD CONSTRAINT FK_OA2T_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);	

CREATE INDEX HOMEPAGE.OA2T_PERSON_SERVICE
	ON HOMEPAGE.OAUTH2_TOKEN (PERSON_ID, SERVICE_NAME) TABLESPACE "NEWSINDEXTABSPACE";
	
CREATE UNIQUE INDEX HOMEPAGE.OA2_TOKEN_SHA1_UNQ 
	ON HOMEPAGE.OAUTH2_TOKEN (TOKEN_SHA1) TABLESPACE "NEWSINDEXTABSPACE";
	
ALTER TABLE HOMEPAGE.OAUTH2_TOKEN ENABLE ROW MOVEMENT;

COMMIT;

CREATE TABLE HOMEPAGE.OH2P_CACHE (
	LOOKUPKEY VARCHAR2(256) NOT NULL, 
	UNIQUEID VARCHAR2(128) NOT NULL, 
	COMPONENTID VARCHAR2(256) NOT NULL, 
	TYPE VARCHAR2(64) NOT NULL, 
	SUBTYPE VARCHAR2(64), 
	CREATEDAT NUMBER(19), 
	LIFETIME NUMBER(10), 
	EXPIRES NUMBER(19), 
	TOKENSTRING VARCHAR2(2048) NOT NULL, 
	CLIENTID VARCHAR2(64) NOT NULL, 
	USERNAME VARCHAR2(256) NOT NULL, 
	SCOPE VARCHAR2(512) NOT NULL, 
	REDIRECTURI VARCHAR2(2048), 
	STATEID VARCHAR2(64) NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OH2P_CACHE 
	ADD CONSTRAINT PK_LOOKUPKEY PRIMARY KEY (LOOKUPKEY) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE";

CREATE INDEX HOMEPAGE.OH2P_CACHE_EXPIRES ON HOMEPAGE.OH2P_CACHE (EXPIRES ASC) TABLESPACE "HOMEPAGEINDEXTABSPACE";
COMMIT;

CREATE INDEX HOMEPAGE.OH2P_CACHE_CNT 
	ON HOMEPAGE.OH2P_CACHE (USERNAME, CLIENTID, COMPONENTID) TABLESPACE "NEWSINDEXTABSPACE";
COMMIT;

CREATE INDEX HOMEPAGE.OH2P_CACHE_DUP 
	ON HOMEPAGE.OH2P_CACHE (USERNAME ASC, EXPIRES DESC, CLIENTID ASC, TYPE ASC) TABLESPACE "NEWSINDEXTABSPACE";
COMMIT;

ALTER TABLE HOMEPAGE.OH2P_CACHE ENABLE ROW MOVEMENT;

COMMIT;


CREATE TABLE HOMEPAGE.OH2P_CLIENTCFG (
	COMPONENTID VARCHAR2(128) NOT NULL, 
	CLIENTID VARCHAR2(256) NOT NULL, 
	CLIENTSECRET VARCHAR2(256), 
	DISPLAYNAME VARCHAR2(256) NOT NULL, 
	REDIRECTURI VARCHAR2(2048), 
	ENABLED NUMBER(5)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OH2P_CLIENTCFG 
	ADD CONSTRAINT PK_COMPIDCLIENTID PRIMARY KEY (COMPONENTID,CLIENTID) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE";

ALTER TABLE HOMEPAGE.OH2P_CLIENTCFG ENABLE ROW MOVEMENT;

COMMIT;

-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END OAuth Consumer Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

CREATE TABLE HOMEPAGE.MTCONFIG (
	UUID			VARCHAR2(36) NOT NULL,
	SCOPE 			VARCHAR2(36) NOT NULL,
	ID 				VARCHAR2(128) NOT NULL,
	CONFIG_VALUE 	VARCHAR2(1024),
	SERVICE 		VARCHAR2(256),
	NAME	 		VARCHAR2(64),
	DESCRIPTION		VARCHAR2(64),
	OVERRIDABLE 	NUMBER(5,0) DEFAULT 1 NOT NULL,
	ISPOLICY		NUMBER(5,0) DEFAULT 0 NOT NULL,
	ADMIN_VIS		NUMBER(5,0) DEFAULT 1 NOT NULL
) TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.MTCONFIG
	 ADD (CONSTRAINT "PK_ID" PRIMARY KEY ("UUID") USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

CREATE UNIQUE INDEX HOMEPAGE.SCOPE_AND_ID
	ON HOMEPAGE.MTCONFIG (SCOPE, ID) TABLESPACE "HOMEPAGEINDEXTABSPACE";

CREATE INDEX HOMEPAGE.SETTINGS_BY_ID
    ON HOMEPAGE.MTCONFIG (ID) TABLESPACE "HOMEPAGEINDEXTABSPACE";
    
ALTER TABLE HOMEPAGE.MTCONFIG ENABLE ROW MOVEMENT;

COMMIT;    


-----------------------------------------------------
--  HOMEPAGE.MT_CFG_DEFINITIONS
-----------------------------------------------------
CREATE TABLE HOMEPAGE.MT_CFG_DEFINITIONS (
	DEFINITION_ID	VARCHAR2(36) NOT NULL,
	NAME			VARCHAR2(128) NOT NULL,
	TITLE			VARCHAR2(128),
	DESCRIPTION		VARCHAR2(256),
	TYPE			VARCHAR2(256),
	EDITOR			VARCHAR2(128),
	CAN_MODIFY		NUMBER(5,0) DEFAULT 0 NOT NULL,
	DISPLAY			NUMBER(5,0) DEFAULT 0 NOT NULL,
	REQUIRES		VARCHAR2(128),
	VALIDATOR		VARCHAR2(256),
	CATEGORY 		VARCHAR2(128),
	ALLOW_ROLE 		NUMBER(5, 0)
)
TABLESPACE "HOMEPAGEREGTABSPACE";
    
ALTER TABLE HOMEPAGE.MT_CFG_DEFINITIONS
	ADD (CONSTRAINT PK_MT_CFG_DEFINITION PRIMARY KEY (DEFINITION_ID) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
	

CREATE UNIQUE INDEX HOMEPAGE.UNQ_NAME
	ON HOMEPAGE.MT_CFG_DEFINITIONS (NAME) TABLESPACE "HPNTINDEXTABSPACE";

	
ALTER TABLE HOMEPAGE.MT_CFG_DEFINITIONS ENABLE ROW MOVEMENT;	

-----------------------------------------------------
--  HOMEPAGE.MT_CFG_SETTINGS
-----------------------------------------------------
CREATE TABLE HOMEPAGE.MT_CFG_SETTINGS (
	SETTING_ID		VARCHAR2(36) NOT NULL,
	ORGANIZATION_ID	VARCHAR2(36) NOT NULL,
	NAME			VARCHAR2(128) NOT NULL,
	VALUE			VARCHAR2(256),
	CAN_MODIFY		NUMBER(5,0) DEFAULT 0 NOT NULL,
	ROLE 			VARCHAR2(36)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS
	ADD (CONSTRAINT PK_MT_CFG_SETTINGS PRIMARY KEY (SETTING_ID) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS 
	ADD CONSTRAINT FK_CFG_SET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) 
	REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID); 	
	
CREATE UNIQUE INDEX HOMEPAGE.UNQ_ORG_NAME
	ON HOMEPAGE.MT_CFG_SETTINGS (NAME, ORGANIZATION_ID, ROLE) TABLESPACE "HPNTINDEXTABSPACE";
	
	
	
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS ENABLE ROW MOVEMENT;

-----------------------------------------------------
--  HOMEPAGE.MT_CFG_FILES
-- 	TYPE: 0: BINARY FILE, 1: TXT FILE, 2: CONFIGURATION FILE
-----------------------------------------------------
CREATE TABLE HOMEPAGE.MT_CFG_FILES (
	FILE_ID			VARCHAR2(36) NOT NULL,
	SETTING_ID		VARCHAR2(36) NOT NULL,
	TYPE			NUMBER(5,0) NOT NULL, 
	FILENAME		VARCHAR2(256),		
	CACHE			NUMBER(5,0) DEFAULT 0 NOT NULL,
	C_CONTENT		CLOB,
	B_CONTENT		BLOB,
	ORGANIZATION_ID	VARCHAR2(36) NOT NULL
)
LOB (C_CONTENT) STORE AS (TABLESPACE NEWSLOBTABSPACE STORAGE (INITIAL 1M) CHUNK 4000 NOCACHE NOLOGGING),
LOB (B_CONTENT) STORE AS (TABLESPACE NEWSLOBTABSPACE STORAGE (INITIAL 1M) CHUNK 4000 NOCACHE NOLOGGING)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.MT_CFG_FILES
	ADD (CONSTRAINT PK_MT_CFG_FILE PRIMARY KEY (FILE_ID) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.MT_CFG_FILES 
	ADD CONSTRAINT FK_SETTING_ID FOREIGN KEY (SETTING_ID) REFERENCES HOMEPAGE.MT_CFG_SETTINGS (SETTING_ID);

CREATE UNIQUE INDEX HOMEPAGE.UNQ_SETTING
	ON HOMEPAGE.MT_CFG_FILES (SETTING_ID) TABLESPACE "HPNTINDEXTABSPACE";
	
ALTER TABLE HOMEPAGE.MT_CFG_FILES 
	ADD CONSTRAINT FK_CFG_FILE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) 
	REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);	

ALTER TABLE HOMEPAGE.MT_CFG_FILES ENABLE ROW MOVEMENT;

----------------------------------------------------
------------------------ END   HP FIXUP 451 -------
----------------------------------------------------
