-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

DELETE FROM HOMEPAGE.NR_STORIES;
commit;

DELETE FROM HOMEPAGE.NR_ENTRIES;
commit;

DELETE FROM HOMEPAGE.NR_ENTRIES_ARCHIVE;
commit;

DELETE FROM HOMEPAGE.NR_COMM_SETTINGS;
commit;

DELETE FROM HOMEPAGE.DELETED_STORIES_QUEUE;
commit;

-- News delete board tables
DELETE FROM HOMEPAGE.BOARD_MENTIONS;
commit;

DELETE FROM HOMEPAGE.BOARD_CURRENT_STATUS;
commit;

DELETE FROM HOMEPAGE.BOARD_RECOMMENDATIONS;
commit;

DELETE FROM HOMEPAGE.BOARD_OBJECT_REFERENCE;
commit;

DELETE FROM HOMEPAGE.BOARD_COMMENTS;
commit;

DELETE FROM HOMEPAGE.BOARD_ENTRIES;
commit;

DELETE FROM HOMEPAGE.BOARD;

commit;

-- New delete categories stories
DELETE FROM HOMEPAGE.NR_RESPONSES_READERS;
commit;

DELETE FROM HOMEPAGE.NR_PROFILES_READERS;
commit;

DELETE FROM HOMEPAGE.NR_COMMUNITIES_READERS;
commit;

DELETE FROM HOMEPAGE.NR_ACTIVITIES_READERS;
commit;

DELETE FROM HOMEPAGE.NR_BLOGS_READERS;
commit;

DELETE FROM HOMEPAGE.NR_BOOKMARKS_READERS;
commit;

DELETE FROM HOMEPAGE.NR_FILES_READERS;
commit;

DELETE FROM HOMEPAGE.NR_FORUMS_READERS;
commit;

DELETE FROM HOMEPAGE.NR_WIKIS_READERS;
commit;

DELETE FROM HOMEPAGE.NR_TAGS_READERS;
commit;

DELETE FROM HOMEPAGE.NR_STATUS_UPDATE_READERS;
commit;

DELETE FROM HOMEPAGE.NR_DISCOVERY_VIEW;
commit;

DELETE FROM HOMEPAGE.NR_PROFILES_VIEW;
commit;

DELETE FROM HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
commit;

DELETE FROM HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
commit;

DELETE FROM HOMEPAGE.NR_TOPICS_READERS;
commit;

DELETE FROM HOMEPAGE.NR_MENTIONS_READERS;
commit;

DELETE FROM HOMEPAGE.NR_AS_SEEDLIST;
commit;

DELETE FROM HOMEPAGE.NR_AS_COLLECTION_CONFIG; 
commit;

DELETE FROM HOMEPAGE.NR_AS_CRAWLER_STATUS; 
commit;

-- NEWS deletion
DELETE FROM HOMEPAGE.NR_NEWS_RECORDS;
commit;

DELETE FROM HOMEPAGE.NR_SUBSCRIPTION;
commit;

DELETE FROM HOMEPAGE.NR_SOURCE;
commit;

DELETE FROM HOMEPAGE.NR_TEMPLATE;
commit;

DELETE FROM HOMEPAGE.NR_CATEGORY_TYPE;
commit;

DELETE FROM HOMEPAGE.NR_NEWS_SAVED;
commit;

DELETE FROM HOMEPAGE.NR_NEWS_DISCOVERY;
commit;

DELETE FROM HOMEPAGE.NR_NEWS_COMMENT_CONTENT;
commit;

DELETE FROM HOMEPAGE.NR_NEWS_STATUS_CONTENT;
commit;

DELETE FROM HOMEPAGE.NR_NEWS_STATUS_COMMENT;
commit;

DELETE FROM HOMEPAGE.NR_NEWS_STATUS_NETWORK;
commit;

DELETE FROM HOMEPAGE.NR_AGGREGATED_READERS;
commit;

DELETE FROM HOMEPAGE.NR_COMM_PERSON_FOLLOW;
commit;

DELETE FROM HOMEPAGE.NR_NETWORK;
commit;

DELETE FROM HOMEPAGE.NR_STORIES_CONTENT;
commit;

DELETE FROM HOMEPAGE.NR_COMM_FOLLOW;
commit;

DELETE FROM HOMEPAGE.NR_FOLLOWS;	
commit;

DELETE FROM HOMEPAGE.NR_RESOURCE;
commit;

DELETE FROM HOMEPAGE.NR_RESOURCE_TYPE;
commit;

-- EMail Digest deletion
DELETE FROM HOMEPAGE.EMD_EMAIL_PREFS;
commit;

DELETE FROM HOMEPAGE.EMD_TRANCHE_INFO;
commit;

DELETE FROM HOMEPAGE.EMD_TRANCHE;
commit;

DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF;
commit;

DELETE FROM HOMEPAGE.EMD_FREQUENCY_TYPE;
commit;

-- Delete notifications NT_NOTIFICATIONs
DELETE FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT;
commit;

DELETE FROM HOMEPAGE.NT_NOTIFICATION;
commit;

DELETE FROM HOMEPAGE.NR_SOURCE_TYPE;
commit;

DELETE FROM HOMEPAGE.NR_SOURCE_TYPE_DEFAULT;
commit;

DELETE FROM HOMEPAGE.NR_RECOMMENDATION;
commit;

DELETE FROM HOMEPAGE.NR_ATTACHMENT;    
commit;

-- Delete actionable stories
DELETE FROM HOMEPAGE.NR_ACTIONABLE_READERS;
commit;

DELETE FROM HOMEPAGE.NR_SAVED_READERS;
commit;

DELETE FROM HOMEPAGE.NR_DISCOVERY_VIEW;
commit;

DELETE FROM HOMEPAGE.NR_AS_CONTENT_INDEX_STATS;
commit;

DELETE FROM HOMEPAGE.OH2P_CLIENTCFG;
commit;

DELETE FROM HOMEPAGE.OH2P_CACHE;
commit;

DELETE FROM HOMEPAGE.OAUTH2_TOKEN;
commit;

DELETE FROM HOMEPAGE.OAUTH2_GADGET_BINDING;
commit;

DELETE FROM HOMEPAGE.OAUTH2_CLIENT;
commit;

DELETE FROM HOMEPAGE.OAUTH2_PROVIDER;
commit;

DELETE FROM HOMEPAGE.OAUTH1_CONTEXT;
commit;

DELETE FROM HOMEPAGE.OAUTH1_CLIENT;
commit;

DELETE FROM HOMEPAGE.OAUTH1_PROVIDER;
commit;

DELETE FROM HOMEPAGE.OAUTH1_TOKEN;
commit;



