-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- NEWS REPOSITORY
{ORA_GRANT_START} HOMEPAGE.NR_SOURCE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_TEMPLATE {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMGR {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMPR {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SCHEDULER_TASK {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SCHEDULER_TREG {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_CATEGORY_TYPE {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_NETWORK {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_COMMENT {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_CONTENT {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_COMMENT_CONTENT {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_RESOURCE_TYPE  {ORA_GRANT_STOP}	
{ORA_GRANT_START} HOMEPAGE.NR_RESOURCE  {ORA_GRANT_STOP}  
{ORA_GRANT_START} HOMEPAGE.NR_FOLLOWS  {ORA_GRANT_STOP}	
{ORA_GRANT_START} HOMEPAGE.NR_COMM_FOLLOW  {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_STORIES_CONTENT  {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NETWORK  {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_COMM_PERSON_FOLLOW {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_AGGREGATED_READERS {ORA_GRANT_STOP}	

{ORA_GRANT_START} HOMEPAGE.EMD_FREQUENCY_TYPE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.EMD_RESOURCE_PREF {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.EMD_TRANCHE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.EMD_TRANCHE_INFO {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.EMD_EMAIL_PREFS {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_RESPONSES_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_PROFILES_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_COMMUNITIES_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_ACTIVITIES_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_BLOGS_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_BOOKMARKS_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_FILES_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_FORUMS_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_WIKIS_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_TAGS_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_STATUS_UPDATE_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_EXTERNAL_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_MENTIONS_READERS {ORA_GRANT_STOP} 

{ORA_GRANT_START} HOMEPAGE.NR_CATEGORIES_READERS {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_SOURCE_TYPE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SOURCE_TYPE_DEFAULT {ORA_GRANT_STOP}


--{ORA_GRANT_START} HOMEPAGE.NR_STORIES {ORA_GRANT_STOP}

-- BOARD USE CASE
{ORA_GRANT_START} HOMEPAGE.BOARD_ENTRIES {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.BOARD_COMMENTS {ORA_GRANT_STOP}   
{ORA_GRANT_START} HOMEPAGE.BOARD_OBJECT_REFERENCE {ORA_GRANT_STOP}   
{ORA_GRANT_START} HOMEPAGE.BOARD_RECOMMENDATIONS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.BOARD_CURRENT_STATUS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.BOARD_MENTIONS {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.DELETED_STORIES_QUEUE {ORA_GRANT_STOP}  

{ORA_GRANT_START} HOMEPAGE.NR_ACTIONABLE_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SAVED_READERS {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_COMM_SETTINGS {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_DISCOVERY_VIEW {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_PROFILES_VIEW {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NOTIFICATION_SENT_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_TOPICS_READERS {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.BOARD {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_ENTRIES {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_ENTRIES_ARCHIVE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_STORIES {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.OAUTH1_TOKEN {ORA_GRANT_STOP} 
{ORA_GRANT_START} HOMEPAGE.OAUTH1_PROVIDER {ORA_GRANT_STOP} 
{ORA_GRANT_START} HOMEPAGE.OAUTH1_CLIENT {ORA_GRANT_STOP} 
{ORA_GRANT_START} HOMEPAGE.OAUTH1_CONTEXT {ORA_GRANT_STOP} 
{ORA_GRANT_START} HOMEPAGE.OAUTH2_PROVIDER {ORA_GRANT_STOP} 
{ORA_GRANT_START} HOMEPAGE.OAUTH2_CLIENT {ORA_GRANT_STOP} 
{ORA_GRANT_START} HOMEPAGE.OAUTH2_GADGET_BINDING {ORA_GRANT_STOP} 
{ORA_GRANT_START} HOMEPAGE.OAUTH2_TOKEN {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_AS_SEEDLIST {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_AS_COLLECTION_CONFIG {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_AS_CRAWLER_STATUS  {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_AS_CONTENT_INDEX_STATS {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.IMG_CACHE {ORA_GRANT_STOP}

