-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2008, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- DB2   	ORACLE 
-- CHAR 	-> CHAR   
-- VARCHAR	-> VARCHAR2 
-- SMALLINT	-> NUMBER(5,0)
-- INTEGER	-> NUMBER(10 ,0)
-- BIGINT	-> NUMBER(19 ,0)
-- CLOB(max)	-> CLOB
-- BLOB(max)	-> BLOB
-- TIMESTAMP	-> TIMESTAMP   
  
--------------------------------------
-- CREATE THE TABLESPACE  
--------------------------------------   
 
-- HOMEPAGE TABLESPACE 
CREATE SMALLFILE TABLESPACE "HOMEPAGEREGTABSPACE" 
	DATAFILE 'HOMEPAGEREGTABSPACE' 
	SIZE 100M REUSE AUTOEXTEND ON 
	NEXT 20M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;
	
CREATE SMALLFILE TABLESPACE "HOMEPAGEINDEXTABSPACE" 
	DATAFILE 'HOMEPAGEINDEXTABSPACE' 
	SIZE 100M REUSE AUTOEXTEND ON 
	NEXT 20M MAXSIZE UNLIMITED 
	LOGGING EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;

-- HOMEPAGE NOTIFICATION TABLETABLESPACE
CREATE TEMPORARY TABLESPACE "HPNTTMPTABSPACE"
	TEMPFILE 'HPNTTMPTABSPACE'
	SIZE 100M REUSE AUTOEXTEND ON;
	
CREATE SMALLFILE TABLESPACE "HPNTREGTABSPACE"
	DATAFILE 'HPNTREGTABSPACE'
	SIZE 100M REUSE AUTOEXTEND ON 
	NEXT 20M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HPNTINDEXTABSPACE"
	DATAFILE 'HPNTINDEXTABSPACE'
	SIZE 100M REUSE AUTOEXTEND ON 
	NEXT 20M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;

-- HOMEPAGE NEWS TABLETABLESPACE
CREATE TEMPORARY TABLESPACE "NEWSTMPTABSPACE"
	TEMPFILE 'NEWSTMPTABSPACE'
	SIZE 200M REUSE AUTOEXTEND ON;
	
CREATE SMALLFILE TABLESPACE "NEWSREGTABSPACE"
	DATAFILE 'NEWSREGTABSPACE'
	SIZE 200M REUSE AUTOEXTEND ON 
	NEXT 40M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;
	
CREATE SMALLFILE TABLESPACE "NEWSINDEXTABSPACE"
	DATAFILE 'NEWSINDEXTABSPACE'
	SIZE 200M REUSE AUTOEXTEND ON 
	NEXT 40M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;	

--------------------------------------
-- CREATE THE USER\SCHEMA
--------------------------------------
CREATE ROLE HOMEPAGEUSER_ROLE;
CREATE USER "HOMEPAGEUSER" PROFILE "DEFAULT" IDENTIFIED BY "&1" DEFAULT TABLESPACE "HOMEPAGEREGTABSPACE" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
CREATE USER "HOMEPAGE" PROFILE "DEFAULT" IDENTIFIED BY "&1" DEFAULT TABLESPACE "HOMEPAGEREGTABSPACE" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
COMMIT;

-------------------------------------
-- ALTER HOMEPAGE USER, assumes already created
-------------------------------------
GRANT "CONNECT" TO "HOMEPAGE";
ALTER USER "HOMEPAGE" DEFAULT ROLE ALL;
GRANT ALTER TABLESPACE TO "HOMEPAGE";
GRANT UNLIMITED TABLESPACE TO "HOMEPAGE";

--------------------------------------
-- CREATE THE TABLES
--------------------------------------
CREATE TABLE "HOMEPAGE"."HOMEPAGE_SCHEMA" ( 
	COMPKEY VARCHAR2(36) NOT NULL,
	DBSCHEMAVER NUMBER(5, 0) NOT NULL,
	RELEASEVER VARCHAR2(32) DEFAULT ' ' NOT NULL
) 
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."PERSON"  (
	PERSON_ID VARCHAR2(36) NOT NULL,
	DISPLAYNAME VARCHAR2(256) NOT NULL,
	EXID VARCHAR2(256) NOT NULL,
	USER_MAIL VARCHAR2(256)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."LOGINNAME" (
	PERSON_ID VARCHAR2(36) NOT NULL,
	LOGINNAME VARCHAR2(256) NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";  

CREATE TABLE "HOMEPAGE"."HP_UI"  (
	UI_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	PERSON_LANG VARCHAR2(5) NOT NULL,
	LAST_VISIT TIMESTAMP NOT NULL,
	WELCOME_MODE NUMBER(5,0) DEFAULT 1 NOT NULL,
	SHOW_DISABLED_WIDGETS NUMBER(5,0) DEFAULT 0 NOT NULL		
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."HP_TAB"  (
	TAB_ID VARCHAR2(36) NOT NULL,
	DEFAULT_NAME VARCHAR2(36) NOT NULL,
	DEFAULT_N_COLUMNS NUMBER(5,0),
	IS_NAME_CHANGEABLE NUMBER(5,0)	
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."HP_TAB_INST"  (
	TAB_INST_ID VARCHAR2(36) NOT NULL,
	TAB_ID VARCHAR2(36) NOT NULL,
	UI_ID VARCHAR2(36) NOT NULL,
	TAB_NAME VARCHAR2(36),
	N_COLUMNS NUMBER(5,0),
	LAST_MODIFIED TIMESTAMP NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."HP_WIDGET_INST"  (
	WIDGET_INST_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL,
	TAB_INST_ID VARCHAR2(36) NOT NULL,
	WIDGET_SETTING VARCHAR2(2048),
	CONTAINER VARCHAR2(36),
	ORDER_SEQUENCE NUMBER(5,0),
	IS_FIXED NUMBER(5,0),
	IS_TOGGLED NUMBER(5,0),
	LAST_MODIFIED TIMESTAMP NOT NULL,
	LAST_UPDATED TIMESTAMP
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."WIDGET" (
	WIDGET_ID VARCHAR2(36) NOT NULL,
	WIDGET_TITLE VARCHAR2(256) NOT NULL,
	WIDGET_TEXT VARCHAR2(256),
	WIDGET_URL VARCHAR2(256) NOT NULL,
	WIDGET_ICON VARCHAR2(256),
	WIDGET_ENABLED NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_SYSTEM NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_HOMEPAGE_SPECIFIC NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_PREVIEW_IMAGE VARCHAR2(256),
	WIDGET_CATEGORY VARCHAR2(36) DEFAULT ' ' NOT NULL,
	WIDGET_IS_DEFAULT_OPENED NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_MULTIPLE_INSTANCES NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_MARKED_CACHABLE NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_SECURE_URL VARCHAR2(256) DEFAULT '',
	WIDGET_SECURE_ICON VARCHAR2(256) DEFAULT ''	
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."HP_WIDGET_TAB" (
	WIDGET_TAB_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL,
	TAB_ID VARCHAR2(36) NOT NULL,
	TYPE VARCHAR2(36) NOT NULL
)	
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."PREREQ" (
	PREREQ_ID VARCHAR2(36) NOT NULL,
	APP_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";	

CREATE TABLE "HOMEPAGE"."NT_NOTIFICATION"  (
	  NOTIFICATION_ID VARCHAR2(36) NOT NULL,
	  NOTIFICATION_SOURCE VARCHAR2(36) NOT NULL,
	  NOTIFICATION_TYPE VARCHAR2(256) NOT NULL,
	  DATETIME_STAMP TIMESTAMP NOT NULL,
	  SENDER_EXID VARCHAR2(36) NOT NULL,
	  SUBJECT VARCHAR2(256),
	  MESSAGE VARCHAR2(2048),
	  CONTAINER_NAME VARCHAR2(256),
	  CONTAINER_URL VARCHAR2(2048),
	  ITEM_NAME VARCHAR2(256),
	  ITEM_URL VARCHAR2(2048)
)
TABLESPACE "HPNTREGTABSPACE";

CREATE TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT" (
		  ID VARCHAR2(36) NOT NULL,
		  NOTIFICATION_ID VARCHAR2(36) NOT NULL,
		  RECIPIENT_EXID VARCHAR2(36) NOT NULL		  
)
TABLESPACE "HPNTREGTABSPACE";
--------------------------------------
-- CREATE THE CONSTRAINTS
--------------------------------------

ALTER TABLE "HOMEPAGE"."PERSON" 
    ADD (CONSTRAINT "PK_PERSON_ID" PRIMARY KEY ("PERSON_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."HP_UI"
    ADD (CONSTRAINT "PK_HP_UI" PRIMARY KEY ("UI_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");   

ALTER TABLE "HOMEPAGE"."HP_TAB"
    ADD (CONSTRAINT "PK_HP_TAB" PRIMARY KEY("TAB_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."HP_TAB_INST"
    ADD (CONSTRAINT "PK_HP_TAB_INST" PRIMARY KEY("TAB_INST_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
        
ALTER TABLE "HOMEPAGE"."WIDGET"
	ADD (CONSTRAINT "PK_WIDGET" PRIMARY KEY ("WIDGET_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB"
	ADD (CONSTRAINT "PK_WIDGET_TAB" PRIMARY KEY ("WIDGET_TAB_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."PREREQ" 
	ADD (CONSTRAINT "PK_PREREQ" PRIMARY KEY ("PREREQ_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST"
	ADD (CONSTRAINT "PK_HP_WIDGET_INST" PRIMARY KEY ("WIDGET_INST_ID")
	USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE "HOMEPAGE"."LOGINNAME"
	ADD (CONSTRAINT "PK_LOGINNAME_ID" PRIMARY KEY ("PERSON_ID","LOGINNAME")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION"
	ADD (CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NOTIFICATION_ID")
	USING INDEX TABLESPACE "HPNTINDEXTABSPACE");
	
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT"
	ADD (CONSTRAINT "PK_NOTIF_RECIP" PRIMARY KEY ("ID")
	USING INDEX TABLESPACE "HPNTINDEXTABSPACE");

ALTER TABLE "HOMEPAGE"."LOGINNAME"
	ADD CONSTRAINT "FK_LN_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES "HOMEPAGE"."PERSON" ("PERSON_ID");

ALTER TABLE "HOMEPAGE"."HP_UI"
    ADD CONSTRAINT "FK_UI_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES "HOMEPAGE"."PERSON" ("PERSON_ID");
		
ALTER TABLE "HOMEPAGE"."HP_TAB_INST"
    ADD CONSTRAINT "FK_UI_ID" FOREIGN KEY ("UI_ID")
	REFERENCES "HOMEPAGE"."HP_UI" ("UI_ID");

ALTER TABLE "HOMEPAGE"."HP_TAB_INST"
    ADD CONSTRAINT "FK_TAB_INST_TAB_ID" FOREIGN KEY ("TAB_ID")
	REFERENCES "HOMEPAGE"."HP_TAB" ("TAB_ID");
	
ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST"
    ADD CONSTRAINT "FK_WIDGET_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID");
		
ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST"
    ADD CONSTRAINT "FK_TAB_INST_ID" FOREIGN KEY ("TAB_INST_ID")
	REFERENCES "HOMEPAGE"."HP_TAB_INST" ("TAB_INST_ID");
	
ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB"	
    ADD CONSTRAINT "FK_WID_TAB_WID_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID");
	
ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB"	
    ADD CONSTRAINT "FK_WID_TAB_TAB_ID" FOREIGN KEY ("TAB_ID")
	REFERENCES "HOMEPAGE"."HP_TAB" ("TAB_ID");
	
ALTER TABLE "HOMEPAGE"."PREREQ"
	ADD CONSTRAINT "FK_PREREQ_WIDGET" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID")
	ON DELETE CASCADE;
	
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT"
	ADD CONSTRAINT "FK_RECIP_NOTIF" FOREIGN KEY ("NOTIFICATION_ID")
	REFERENCES "HOMEPAGE"."NT_NOTIFICATION" ("NOTIFICATION_ID")
	ON DELETE CASCADE;
	
ALTER TABLE "HOMEPAGE"."LOGINNAME"
	ADD CONSTRAINT LOGINNAME_UNIQUE UNIQUE(LOGINNAME);
	
--------------------------------------
-- CREATE THE INDEXES
--------------------------------------

CREATE INDEX "HOMEPAGE"."WIDGET_INST"
	ON "HOMEPAGE"."HP_WIDGET_INST"("TAB_INST_ID" ASC, "WIDGET_ID" ASC) TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE UNIQUE INDEX "HOMEPAGE"."PERSON_EXID"
    ON "HOMEPAGE"."PERSON"("EXID") TABLESPACE "HPNTINDEXTABSPACE";
    
CREATE INDEX "HOMEPAGE"."PERSON_USER_MAIL"
	ON "HOMEPAGE"."PERSON"("USER_MAIL") TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE INDEX "HOMEPAGE"."HP_UI_PERSON_ID_INDEX"
	ON "HOMEPAGE"."HP_UI"("PERSON_ID") TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NT_NOTIFICATION_EXID_INDEX"
	ON "HOMEPAGE"."NT_NOTIFICATION"("SENDER_EXID") TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NT_NOTIF_RECT_EXID_INDEX"
	ON "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT" ("RECIPIENT_EXID") TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE INDEX "HOMEPAGE"."NT_NOTIF_RECT_NID_INDEX"
	ON "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT"("NOTIFICATION_ID") TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."TAB_INST_UI_ID_IDX" 
	ON "HOMEPAGE"."HP_TAB_INST"("UI_ID") TABLESPACE "HPNTINDEXTABSPACE";	

CREATE INDEX "HOMEPAGE"."HP_WIDGET_INST_TAB_INST_ID_IDX"
	ON "HOMEPAGE"."HP_WIDGET_INST"("TAB_INST_ID") TABLESPACE "HPNTINDEXTABSPACE";	

	
--------------------------------------
-- CREATE THE VIEWS
--------------------------------------

-- TBD

--------------------------------------
-- ENABLE ROW MOVEMENT (for backup, epxort/import)
--------------------------------------
ALTER TABLE "HOMEPAGE"."HOMEPAGE_SCHEMA" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."PERSON" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."LOGINNAME" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_UI" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_TAB" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_TAB_INST" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."WIDGET" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."PREREQ" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT" ENABLE ROW MOVEMENT;

COMMIT;

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- STARTING OF THE DEFINITION FOR THE NEWS REPOSITORY DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------
-- NEWS REPOSITORY - CREATE THE TABLES
----------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_SOURCE (
	SOURCE_ID VARCHAR2(36) NOT NULL,
	SOURCE VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(36) NOT NULL,
	CONTAINER_NAME VARCHAR2(256),
	CONTAINER_URL VARCHAR2(2048),
	ENTRY_ID  VARCHAR2(36),
	ENTRY_NAME VARCHAR2(256),
	ENTRY_URL VARCHAR2(2048),
	ENTRY_ATOM_URL VARCHAR2(2048),
	IS_ACL NUMBER(5,0) DEFAULT 0 NOT NULL,
	IS_PRIVATE NUMBER(5,0),
	LAST_UPDATE TIMESTAMP,
	IS_CNAME_RTL NUMBER(5,0) DEFAULT 0 NOT NULL,
	IS_ENAME_RTL NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";


CREATE TABLE HOMEPAGE.NR_SUBSCRIPTION  (
	SUBSCRIPTION_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	SOURCE_ID VARCHAR2(36) NOT NULL,
	IS_EXPLICIT NUMBER(5,0) DEFAULT 0 NOT NULL,
	IS_ACTIVE NUMBER(5,0) DEFAULT 1 NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";


CREATE TABLE HOMEPAGE.NR_NEWS_RECORDS (
	NEWS_RECORDS_ID VARCHAR2(36) NOT NULL,
	EVENT_NAME VARCHAR2(256) NOT NULL,
    READER_ID VARCHAR2(36),
    SOURCE VARCHAR2(36),
    CONTAINER_ID VARCHAR2(36),
    CONTAINER_NAME VARCHAR2(256),
    CONTAINER_URL VARCHAR2(2048),
    ENTRY_ID VARCHAR2(36),
    ENTRY_NAME VARCHAR2(256),
    ENTRY_URL VARCHAR2(2048),
    ENTRY_ATOM_URL VARCHAR2(2048),
    CREATION_DATE TIMESTAMP NOT NULL,
    IS_INBOX NUMBER(5,0) DEFAULT 0 NOT NULL,
    IS_SAVED NUMBER(5,0) DEFAULT 0 NOT NULL,
    IS_TOP_STORY NUMBER(5,0) DEFAULT 0 NOT NULL,
    IS_PUBLIC NUMBER(5,0) NOT NULL,
    IS_MAILED NUMBER(5,0) NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    BRIEF_DESC VARCHAR2(512),
    IS_BRIEF_DESC_RTL NUMBER(5,0) DEFAULT 0 NOT NULL,
    ACTOR_UUID VARCHAR2(36),
    EVENT_RECORD_UUID VARCHAR2(36) NOT NULL,
    RELATED_COMM_UUID VARCHAR2(36),
    RELATED_COMM_NAME VARCHAR2(256),
    TAGS VARCHAR2(1024),
    META_TEMPLATE VARCHAR2(4000) DEFAULT ' ' NOT NULL,
    TEXT_META_TEMPLATE VARCHAR2(1024),
    IS_CONTAINER NUMBER(5,0) DEFAULT 0 NOT NULL,
    ITEM_ID VARCHAR2(36),
    ITEM_CORRELATION_ID VARCHAR2(36)
) 
TABLESPACE "NEWSREGTABSPACE";



CREATE TABLE HOMEPAGE.NR_TEMPLATE (
	TEMPLATE_ID VARCHAR2(36) NOT NULL,
 	NAME VARCHAR2(256) NOT NULL,
 	FORMAT VARCHAR2(256) NOT NULL,
 	DATA_SOURCE_STRING VARCHAR2(256) NOT NULL,
 	NO_VALUES NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.NR_EVENT_RECORDS  (
	EVENT_RECORD_ID VARCHAR2(36) NOT NULL,
	EVENT_RECORD_CONTENT BLOB,
	IS_ACL NUMBER(5,0) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

-- EMAIL DIGEST
CREATE TABLE HOMEPAGE.EMD_RECIPIENTS (
	RECIPIENT_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	FREQUENCY_UPDATE NUMBER(5,0) NOT NULL,
	LAST_SENT_UPDATE TIMESTAMP NOT NULL,
	MAIL_DOMAIN VARCHAR2(256) NOT NULL,
	MAIL_ADDRESS  VARCHAR2(256) NOT NULL,
	LOCALE VARCHAR2(5),
	DISPLAYNAME VARCHAR2(256)
)
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.EMD_JOBS  (
	JOB_ID VARCHAR2(36) NOT NULL,
	JOB_FREQUENCY NUMBER(5,0) NOT NULL,
	NEXT_EXEC_TIME TIMESTAMP,
	DUE_DATE_EXEC_TIME TIMESTAMP,
	START_JOB TIMESTAMP,
	END_JOB TIMESTAMP,
	STATUS VARCHAR2(36),
	N_PERSONS_TO_UPDATE NUMBER(10,0),
	AVG_EXEC_TIME_SECONDS NUMBER(10,0),
	JOB_FREQUENCY_SCALE VARCHAR2(36) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.EMD_JOBS_STATS (
	STAT_ID VARCHAR2(36) NOT NULL,
	JOB_ID VARCHAR2(36) NOT NULL,
	START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    EXEC_TIME_SECONDS NUMBER(10,0),
    N_PERSONS_UPDATED NUMBER(10,0),
    STATUS VARCHAR2(36) DEFAULT 'COMPLETED' NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";



----------------------------------------------------------------------------
-- NEWS REPOSITORY -  CREATE THE CONSTRAINTS
----------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_SOURCE
    ADD (CONSTRAINT "PK_SOURCE_ID" PRIMARY KEY ("SOURCE_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");    

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD (CONSTRAINT "PK_SUBSCRIPTION_ID" PRIMARY KEY ("SUBSCRIPTION_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_NEWS_RECORDS
    ADD (CONSTRAINT "PK_NR_NEWS_RECORDS" PRIMARY KEY ("NEWS_RECORDS_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_TEMPLATE 
    ADD (CONSTRAINT "PK_TEMPLATE_ID" PRIMARY KEY ("TEMPLATE_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");    

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT "FK_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT "FK_SOURCE_ID" FOREIGN KEY ("SOURCE_ID")
	REFERENCES HOMEPAGE.NR_SOURCE ("SOURCE_ID");
	
ALTER TABLE "HOMEPAGE"."NR_EVENT_RECORDS"
    ADD (CONSTRAINT "PK_EVENT_RECORD_ID" PRIMARY KEY("EVENT_RECORD_ID")
	USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

-- EMAIL DIGEST CONSTRAINTS
ALTER TABLE "HOMEPAGE"."EMD_RECIPIENTS"
    ADD (CONSTRAINT "PK_RECIPIENT_ID" PRIMARY KEY("RECIPIENT_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");   

ALTER TABLE "HOMEPAGE"."EMD_JOBS"
    ADD (CONSTRAINT "PK_JOB_ID" PRIMARY KEY("JOB_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE "HOMEPAGE"."EMD_JOBS_STATS"
    ADD (CONSTRAINT "PK_STAT_ID" PRIMARY KEY("STAT_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE "HOMEPAGE"."EMD_RECIPIENTS"
    ADD CONSTRAINT "FK_REC_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");
	
ALTER TABLE "HOMEPAGE"."EMD_JOBS_STATS"
    ADD CONSTRAINT "FK_JOB_ID" FOREIGN KEY ("JOB_ID")
	REFERENCES HOMEPAGE.EMD_JOBS ("JOB_ID");

ALTER TABLE "HOMEPAGE"."EMD_JOBS"
	ADD CONSTRAINT UNIQUE_JOB_FREQ UNIQUE("JOB_FREQUENCY");	

----------------------------------------------------------------------------
-- NEWS REPOSITORY -  CREATE THE INDEXES
----------------------------------------------------------------------------
CREATE UNIQUE INDEX HOMEPAGE.NR_SUBSCRIPTION_IX_UNIQUE
	ON HOMEPAGE.NR_SUBSCRIPTION("PERSON_ID" ASC, "SOURCE_ID" ASC) TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX HOMEPAGE.NR_SUBSCRIPTION_SOURCE_IDX  
    ON HOMEPAGE.NR_SUBSCRIPTION("SOURCE_ID") TABLESPACE "NEWSINDEXTABSPACE";

CREATE UNIQUE INDEX HOMEPAGE.NR_SOURCE_IX_UNIQUE
	ON HOMEPAGE.NR_SOURCE("SOURCE" ASC, "CONTAINER_ID" ASC, "ENTRY_ID" ASC, "IS_ACL" ASC) TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX HOMEPAGE.NR_SOURCE_CONTAINER_NAME_IDX
    ON HOMEPAGE.NR_SOURCE("SOURCE" ASC, "CONTAINER_NAME" ASC, "ENTRY_ID" ASC, "IS_ACL" ASC) TABLESPACE "NEWSINDEXTABSPACE";
    
CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_READER_IDX"
	ON HOMEPAGE.NR_NEWS_RECORDS("READER_ID") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_ACTOR_IDX"
	ON HOMEPAGE.NR_NEWS_RECORDS("ACTOR_UUID") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_SOURCE_IDX" 
	ON "HOMEPAGE"."NR_NEWS_RECORDS" ("CREATION_DATE" DESC, "NEWS_RECORDS_ID", "READER_ID", "IS_CONTAINER", "IS_PUBLIC", "SOURCE") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_CONTAINER_IDX"
	ON HOMEPAGE.NR_NEWS_RECORDS("CONTAINER_ID") TABLESPACE "NEWSINDEXTABSPACE";
	
CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_DATE_IDX"
	ON HOMEPAGE.NR_NEWS_RECORDS("CREATION_DATE" DESC) TABLESPACE "NEWSINDEXTABSPACE";
	
CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_EVENT_IDX"
	ON HOMEPAGE.NR_NEWS_RECORDS("EVENT_RECORD_UUID") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_IX1" 
	ON HOMEPAGE.NR_NEWS_RECORDS ("CREATION_DATE" DESC, "NEWS_RECORDS_ID", "READER_ID", "IS_CONTAINER", "IS_PUBLIC") TABLESPACE "NEWSINDEXTABSPACE";
	
CREATE INDEX "HOMEPAGE"."NR_READ_SOUR_ACTR_IS_PUB_IDX"
	ON HOMEPAGE.NR_NEWS_RECORDS ("READER_ID", "SOURCE", "ACTOR_UUID", "IS_PUBLIC") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_READER_ER_UUID_IDX"
	ON HOMEPAGE.NR_NEWS_RECORDS ("READER_ID", "EVENT_RECORD_UUID") TABLESPACE "NEWSINDEXTABSPACE";
	
CREATE INDEX "HOMEPAGE"."NR_READER_IS_TOP_STORY_IDX" 
	ON "HOMEPAGE"."NR_NEWS_RECORDS" ("CREATION_DATE" DESC, "NEWS_RECORDS_ID", "READER_ID", "IS_TOP_STORY") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_READER_IS_SAVED_IDX" 
	ON "HOMEPAGE"."NR_NEWS_RECORDS" ("CREATION_DATE" DESC, "READER_ID", "IS_SAVED") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_READER_TOPSTORY_SRC_IDX" 
	ON "HOMEPAGE"."NR_NEWS_RECORDS" ("CREATION_DATE" DESC, "NEWS_RECORDS_ID", "READER_ID", "IS_TOP_STORY", "SOURCE") TABLESPACE "NEWSINDEXTABSPACE";		

CREATE UNIQUE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_COMM_UUID_IDX"
    ON HOMEPAGE.NR_NEWS_RECORDS("CREATION_DATE" DESC, "NEWS_RECORDS_ID", "SOURCE", "RELATED_COMM_UUID", "READER_ID", "IS_PUBLIC", "IS_CONTAINER") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_NEWS_WATCHLIST_IDX"
	ON HOMEPAGE.NR_NEWS_RECORDS(CONTAINER_ID,SOURCE,IS_CONTAINER,READER_ID) TABLESPACE "NEWSINDEXTABSPACE";
	
-- EMAIL DIGEST INDEXES
CREATE INDEX "HOMEPAGE"."EMD_RECIPIENTS_SENT_UPDATE_IDX"
	ON HOMEPAGE.EMD_RECIPIENTS("LAST_SENT_UPDATE" DESC) TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."EMD_RECIPIENTS_MAIL_DOMAIN_IDX"
	ON HOMEPAGE.EMD_RECIPIENTS("MAIL_DOMAIN" DESC) TABLESPACE "NEWSINDEXTABSPACE";

-------------------------------------------------------------------
-- START ADDING SCHEDULER TABLES
-------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_SCHEDULER_TASK (
	TASKID NUMBER(19) NOT NULL,
	VERSION VARCHAR2(5) NOT NULL,
   	ROW_VERSION NUMBER(10) NOT NULL,
   	TASKTYPE NUMBER(10) NOT NULL,
   	TASKSUSPENDED NUMBER(1) NOT NULL,
   	CANCELLED NUMBER(1) NOT NULL,
   	NEXTFIRETIME NUMBER(19) NOT NULL,
   	STARTBYINTERVAL VARCHAR2(254),
   	STARTBYTIME NUMBER(19),
   	VALIDFROMTIME NUMBER(19),
   	VALIDTOTIME NUMBER(19),
   	REPEATINTERVAL VARCHAR2(254),
   	MAXREPEATS NUMBER(10) NOT NULL,
   	REPEATSLEFT NUMBER(10) NOT NULL,
   	TASKINFO BLOB,
   	NAME VARCHAR2(254),
   	AUTOPURGE NUMBER(10) NOT NULL,
   	FAILUREACTION NUMBER(10),
   	MAXATTEMPTS NUMBER(10),
   	QOS NUMBER(10),
   	PARTITIONID NUMBER(10),
   	OWNERTOKEN VARCHAR2(200) NOT NULL,
   	CREATETIME NUMBER(19) NOT NULL,
   	PRIMARY KEY (TASKID)
)
TABLESPACE "NEWSREGTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_SCHEDULER_TASK_IDX1 "
	ON "HOMEPAGE"."NR_SCHEDULER_TASK" ("TASKID", "OWNERTOKEN") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_SCHEDULER_TASK_IDX2" 
	ON "HOMEPAGE"."NR_SCHEDULER_TASK" ("NEXTFIRETIME" ASC, "REPEATSLEFT", "PARTITIONID") TABLESPACE "NEWSINDEXTABSPACE";

CREATE TABLE HOMEPAGE.NR_SCHEDULER_TREG (
	REGKEY VARCHAR2(254) NOT NULL,
	REGVALUE VARCHAR2(254),
	PRIMARY KEY (REGKEY)
) 
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.NR_SCHEDULER_LMGR (
	LEASENAME VARCHAR2(254) NOT NULL,
	LEASEOWNER VARCHAR2(254),
	LEASE_EXPIRE_TIME NUMBER(19),
	DISABLED VARCHAR2(254),
	PRIMARY KEY (LEASENAME)
)
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.NR_SCHEDULER_LMPR (
	LEASENAME VARCHAR2(254) NOT NULL,
	NAME VARCHAR2(254) NOT NULL,
	VALUE VARCHAR2(254) NOT NULL 
)
TABLESPACE "NEWSREGTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_SCHEDULER_LMPR_IDX1"
	ON "HOMEPAGE"."NR_SCHEDULER_LMPR" ("LEASENAME", "NAME") TABLESPACE "NEWSINDEXTABSPACE";


	
-------------------------------------------------------------------
-- END ADDING SCHEDULER TABLES
-------------------------------------------------------------------	
 
--------------------------------------
-- ENABLE ROW MOVEMENT (for backup, epxort/import)
--------------------------------------
ALTER TABLE "HOMEPAGE"."NR_SOURCE" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_SUBSCRIPTION" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_NEWS_RECORDS" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_TEMPLATE" ENABLE ROW MOVEMENT;

-- News Repository
ALTER TABLE "HOMEPAGE"."NR_EVENT_RECORDS" ENABLE ROW MOVEMENT;

-- Email digest
ALTER TABLE "HOMEPAGE"."EMD_RECIPIENTS" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."EMD_JOBS" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."EMD_JOBS_STATS" ENABLE ROW MOVEMENT;

-- Scheduler
ALTER TABLE "HOMEPAGE"."NR_SCHEDULER_TASK" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_SCHEDULER_TREG" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_SCHEDULER_LMGR" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_SCHEDULER_LMPR" ENABLE ROW MOVEMENT;
	
-----------------------------------------------------------------------------
-- NEWS REPOSITORY -  RUN STATS
-----------------------------------------------------------------------------
-- TODO


COMMIT;
	


------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- END OF THE DEFINITION FOR THE NEWS REPOSITORY DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- START THE DEFINITION FOR THE SEARCH DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------
-- SEARCH -  CREATE THE TABLES
----------------------------------------------------------------------------

CREATE TABLE HOMEPAGE.SR_TASKDEF (
	TASK_ID VARCHAR2(36) NOT NULL,
	TASK_NAME VARCHAR2(256) NOT NULL,
	STARTBY VARCHAR2(256),
	INTERVAL VARCHAR2(256),
	TASK_TYPE VARCHAR2(36) NOT NULL,
	ENABLED NUMBER(5,0) DEFAULT 1 NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE HOMEPAGE.SR_INDEXINGTASKDEF (
	INDEXING_TASK_ID VARCHAR2(36) NOT NULL,
	TASK_ID VARCHAR2(36) NOT NULL,
	INDEXING_TASK_SERVICES VARCHAR2(256) NOT NULL,
	INDEXING_TASK_OPTIMIZE NUMBER(5,0) NOT NULL	
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE HOMEPAGE.SR_OPTIMIZETASKDEF (
	OPTIMIZE_TASK_ID VARCHAR2(36) NOT NULL,	
	TASK_ID VARCHAR2(36) NOT NULL	
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE HOMEPAGE.SR_FILESCONTENT (
	FILESCONTENT_ID VARCHAR2(36) NOT NULL,
	URL VARCHAR2(256) NOT NULL,
	COMPONENT_UUID VARCHAR2(36) NOT NULL,
	COMPONENT VARCHAR2(36) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
	LAST_ACCESSED_DATE TIMESTAMP NOT NULL,
	IS_CURRENT NUMBER(5,0) NOT NULL,
	CONTENT CLOB NOT NULL,
	FILE_SIZE NUMBER(19 ,0) NOT NULL,
	CONTENT_SIZE NUMBER(19 ,0) NOT NULL,
	INPUT_MIME_TYPE VARCHAR2(256) NOT NULL,
	CLAIMED NUMBER(5,0) DEFAULT 0 NOT NULL,
	CLAIMED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE HOMEPAGE.SR_MIGTASKDEFINFO (
	MIGTASKDEFINFO_ID VARCHAR2(36) NOT NULL,
	NUM_TASKS_MIG NUMBER(10,0) DEFAULT 1 NOT NULL  
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE HOMEPAGE.SR_FILECONTENTTASKDEF (
	FILECONTENT_TASK_ID VARCHAR(36) NOT NULL,	
	TASK_ID VARCHAR(36) NOT NULL,
	FILE_CONTENT_TASK_SERVICES VARCHAR(256) NOT NULL,
	CONTENT_FAILURES_ONLY NUMBER(5,0) NOT NULL	
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE VIEW HOMEPAGE.SR_ALLTASKSDEF 	AS
(
	SELECT 	T1.TASK_ID  			AS	PARENT_TASK_ID,
	T1.TASK_NAME 					AS	PARENT_TASK_NAME,
	T1.INTERVAL 					AS	PARENT_TASK_INTERVAL,
	T1.STARTBY	 					AS	PARENT_TASK_STARTBY,
	T1.TASK_TYPE 					AS	PARENT_TASK_TYPE,
    T1.ENABLED 						AS  PARENT_TASK_ENABLED,
	T2.INDEXING_TASK_SERVICES		AS	INDEXING_TASK_SERVICES,
	T2.INDEXING_TASK_OPTIMIZE		AS	INDEXING_TASK_OPTIMIZE,
	T2.INDEXING_TASK_ID				AS	INDEXING_TASK_ID,
	''								AS	OPTIMIZE_TASK_ID,
	'' 								AS 	FILECONTENT_TASK_ID,
	''								AS	FILE_CONTENT_TASK_SERVICES,
	0								AS 	CONTENT_FAILURES_ONLY,
	T2.INDEXING_TASK_ID				AS	CHILDTASK_PK
	FROM    HOMEPAGE.SR_TASKDEF T1,
			HOMEPAGE.SR_INDEXINGTASKDEF T2 
	WHERE T1.TASK_ID=T2.TASK_ID
) 
UNION 
(
	SELECT T3.TASK_ID				AS 	PARENT_TASK_ID,
	T3.TASK_NAME 					AS 	PARENT_TASK_NAME,
	T3.INTERVAL						AS 	PARENT_TASK_INTERVAL,
	T3.STARTBY 						AS	PARENT_TASK_STARTBY,
	T3.TASK_TYPE 					AS 	PARENT_TASK_TYPE,
 	T3.ENABLED 						AS  PARENT_TASK_ENABLED,
	''								AS 	INDEXING_TASK_SERVICES,
	0								AS	INDEXING_TASK_OPTIMIZE,
	''								AS	INDEXING_TASK_ID,
	T4.OPTIMIZE_TASK_ID 			AS	OPTIMIZE_TASK_ID,
	'' 								AS 	FILECONTENT_TASK_ID,
	''								AS	FILE_CONTENT_TASK_SERVICES,
	0								AS 	CONTENT_FAILURES_ONLY,
	T4.OPTIMIZE_TASK_ID				AS	CHILDTASK_PK
	FROM   	HOMEPAGE.SR_TASKDEF T3,
			HOMEPAGE.SR_OPTIMIZETASKDEF T4
	WHERE  T3.TASK_ID=T4.TASK_ID
)
UNION 
(
	SELECT T5.TASK_ID				AS 	PARENT_TASK_ID,
	T5.TASK_NAME 					AS 	PARENT_TASK_NAME,
	T5.INTERVAL						AS 	PARENT_TASK_INTERVAL,
	T5.STARTBY 						AS	PARENT_TASK_STARTBY,
	T5.TASK_TYPE 					AS 	PARENT_TASK_TYPE,
 	T5.ENABLED 						AS  PARENT_TASK_ENABLED,
	''								AS 	INDEXING_TASK_SERVICES,
	0								AS	INDEXING_TASK_OPTIMIZE,
	''								AS	INDEXING_TASK_ID,
	''								AS	OPTIMIZE_TASK_ID,
	T6.FILECONTENT_TASK_ID 			AS 	FILECONTENT_TASK_ID,
	T6.FILE_CONTENT_TASK_SERVICES	AS	FILE_CONTENT_TASK_SERVICES,
	T6.CONTENT_FAILURES_ONLY		AS 	CONTENT_FAILURES_ONLY,
	T6.FILECONTENT_TASK_ID			AS	CHILDTASK_PK
	FROM   	HOMEPAGE.SR_TASKDEF T5,
			HOMEPAGE.SR_FILECONTENTTASKDEF T6
	WHERE  T5.TASK_ID=T6.TASK_ID
);

----------------------------------------------------------------------------
-- SEARCH -  CREATE THE CONSTRAINTS
----------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.SR_TASKDEF
	 ADD (CONSTRAINT "PK_TASK_ID" PRIMARY KEY ("TASK_ID")
	 USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF
	ADD (CONSTRAINT "PK_INDEX_TASK_ID" PRIMARY KEY ("INDEXING_TASK_ID")
	USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF
	ADD (CONSTRAINT "PK_OPT_TASK_ID" PRIMARY KEY ("OPTIMIZE_TASK_ID")
	USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.SR_FILESCONTENT
	ADD (CONSTRAINT "PK_FILESCONTENT_ID" PRIMARY KEY ("FILESCONTENT_ID")
	USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");	

ALTER TABLE HOMEPAGE.SR_MIGTASKDEFINFO
	ADD (CONSTRAINT "PK_MIGTASKDEF_ID" PRIMARY KEY("MIGTASKDEFINFO_ID")
	USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF
	ADD (CONSTRAINT "PK_FC_TASK_ID" PRIMARY KEY ("FILECONTENT_TASK_ID")
	USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");	
	
ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF
	ADD CONSTRAINT "FK_INDEX_TASK_ID" FOREIGN KEY ("TASK_ID") 
	REFERENCES HOMEPAGE.SR_TASKDEF("TASK_ID") ON DELETE CASCADE;

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF
	ADD CONSTRAINT "FK_OPT_TASK_ID" FOREIGN KEY ("TASK_ID") 
	REFERENCES  HOMEPAGE.SR_TASKDEF("TASK_ID") ON DELETE CASCADE;

ALTER TABLE HOMEPAGE.SR_TASKDEF
    ADD CONSTRAINT UNIQUE_TASK_NAME UNIQUE ("TASK_NAME");
    
ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF
	ADD CONSTRAINT UNIQUE_TASK_ID_IND UNIQUE ("TASK_ID");

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF
	ADD CONSTRAINT UNIQUE_TASK_ID_OPT UNIQUE ("TASK_ID");

ALTER TABLE HOMEPAGE.SR_FILESCONTENT
	ADD CONSTRAINT UNIQUE_COMP_UUID UNIQUE ("COMPONENT_UUID","COMPONENT");

ALTER TABLE HOMEPAGE.SR_TASKDEF
    ADD CONSTRAINT CHECK_SR_TASKDEF
    CHECK ( (STARTBY IS NOT NULL AND INTERVAL IS NOT NULL) OR (STARTBY IS NULL AND INTERVAL IS NULL) );

ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF
	ADD CONSTRAINT "UNIQUE_TASK_ID_FC" UNIQUE ("TASK_ID");
	
ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF
	ADD CONSTRAINT "FK_FC_TASK_ID" FOREIGN KEY ("TASK_ID") 
	REFERENCES  HOMEPAGE.SR_TASKDEF("TASK_ID") ON DELETE CASCADE;

CREATE INDEX "HOMEPAGE"."SR_FILESCONTENT_IS_CURRENT_IDX" 
	ON HOMEPAGE.SR_FILESCONTENT(IS_CURRENT) TABLESPACE "HOMEPAGEINDEXTABSPACE";    
		

-------------------------------------------------------------------
-- START GRANT LCUSER FOR THE SEARCH TABLES
-------------------------------------------------------------------
ALTER TABLE "HOMEPAGE"."SR_TASKDEF" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."SR_OPTIMIZETASKDEF" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."SR_INDEXINGTASKDEF" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."SR_FILESCONTENT" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."SR_MIGTASKDEFINFO" ENABLE ROW MOVEMENT;

-------------------------------------------------------------------
-- START SEARCH SCHEDULER TABLES
-------------------------------------------------------------------

CREATE TABLE "HOMEPAGE"."LOTUSCONNECTIONSTASK"("TASKID" NUMBER(19) NOT NULL,
               "VERSION" VARCHAR2(5) NOT NULL,
               "ROW_VERSION" NUMBER(10) NOT NULL,
               "TASKTYPE" NUMBER(10) NOT NULL,
               "TASKSUSPENDED" NUMBER(1) NOT NULL,
               "CANCELLED" NUMBER(1) NOT NULL,
               "NEXTFIRETIME" NUMBER(19) NOT NULL,
               "STARTBYINTERVAL" VARCHAR2(254),
               "STARTBYTIME" NUMBER(19),
               "VALIDFROMTIME" NUMBER(19),
               "VALIDTOTIME" NUMBER(19),
               "REPEATINTERVAL" VARCHAR2(254),
               "MAXREPEATS" NUMBER(10) NOT NULL,
               "REPEATSLEFT" NUMBER(10) NOT NULL,
               "TASKINFO" BLOB,
               "NAME" VARCHAR2(254),
               "AUTOPURGE" NUMBER(10) NOT NULL,
               "FAILUREACTION" NUMBER(10),
               "MAXATTEMPTS" NUMBER(10),
               "QOS" NUMBER(10),
               "PARTITIONID" NUMBER(10),
               "OWNERTOKEN" VARCHAR2(200) NOT NULL,
               "CREATETIME" NUMBER(19) NOT NULL,
               PRIMARY KEY ("TASKID") ) TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE INDEX "HOMEPAGE"."LOTUSCONNECTIONSTASK_IDX1" ON "HOMEPAGE"."LOTUSCONNECTIONSTASK" ("TASKID",
              "OWNERTOKEN") ;

CREATE INDEX "HOMEPAGE"."LOTUSCONNECTIONSTASK_IDX2" ON "HOMEPAGE"."LOTUSCONNECTIONSTASK" ("NEXTFIRETIME" ASC,
               "REPEATSLEFT",
               "PARTITIONID") ;

CREATE TABLE "HOMEPAGE"."LOTUSCONNECTIONSTREG" ("REGKEY" VARCHAR2(254) NOT NULL ,
               "REGVALUE" VARCHAR2(254) ,
               PRIMARY KEY ( "REGKEY" )) TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."LOTUSCONNECTIONSLMGR" ("LEASENAME" VARCHAR2(254) NOT NULL,
               "LEASEOWNER" VARCHAR2(254),
               "LEASE_EXPIRE_TIME" NUMBER(19),
               "DISABLED" VARCHAR2(254),
               PRIMARY KEY ( "LEASENAME" )) TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."LOTUSCONNECTIONSLMPR" ("LEASENAME" VARCHAR2(254) NOT NULL,
               "NAME" VARCHAR2(254) NOT NULL,
               "VALUE" VARCHAR2(254) NOT NULL ) TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE INDEX "HOMEPAGE"."LOTUSCONNECTIONSLMPR_IDX1" ON "HOMEPAGE"."LOTUSCONNECTIONSLMPR" ("LEASENAME",
               "NAME") ;


ALTER TABLE "HOMEPAGE"."LOTUSCONNECTIONSTASK" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."LOTUSCONNECTIONSTREG" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."LOTUSCONNECTIONSLMGR" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."LOTUSCONNECTIONSLMPR" ENABLE ROW MOVEMENT;

COMMIT;

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- END THE DEFINITION FOR THE SEARCH DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

--------------------------------------
-- POPULATE VERSION TABLE 
--------------------------------------

INSERT INTO "HOMEPAGE"."HOMEPAGE_SCHEMA"
	( "COMPKEY", "DBSCHEMAVER", "RELEASEVER") 
VALUES 
	( 'HOMEPAGE', 23, '3.0.0');

COMMIT;

--------------------------------------
-- DISCONNECT
--------------------------------------
DISCONNECT ALL;

QUIT;
