-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-----------------------------------------------------------------------------------
-- Remove NR_NEWS_PRF_COMMENT
-----------------------------------------------------------------------------------
DROP TABLE HOMEPAGE.NR_NEWS_PRF_COMMENT;

GO


-----------------------------------------------------------------------------------
-- Rename all the PK in the reader tables to be CATEGORY_READER_ID;
-----------------------------------------------------------------------------------
-- 1
ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS DROP CONSTRAINT PK_RESP_STORIES;
ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_RESPONSES_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT PK_RESP_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS DROP COLUMN FOLLOWED_STORY_ID;	

ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_RESP_READER_STORY ON HOMEPAGE.NR_RESPONSES_READERS;
GO

CREATE UNIQUE INDEX NR_RESP_READER_STORY 		
	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID);
	
GO

-- 2
ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS DROP CONSTRAINT PK_PROF_STORIES;
ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_PROFILES_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT PK_PROF_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_PRO_READER_STORY ON HOMEPAGE.NR_PROFILES_READERS;
GO

CREATE UNIQUE INDEX NR_PRO_READER_STORY 		
	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID); 
	
GO

-- 3
ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS DROP CONSTRAINT PK_COMM_STORIES;
ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_COMMUNITIES_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT PK_COMM_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_COM_READER_STORY ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

CREATE UNIQUE INDEX NR_COM_READER_STORY 		
	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID);
	
GO

-- 4
ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS DROP CONSTRAINT PK_ACT_STORIES;
ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_ACTIVITIES_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT PK_ACT_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_ACT_READER_STORY ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

CREATE UNIQUE INDEX NR_ACT_READER_STORY 		
	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID);
	
GO

-- 5
ALTER TABLE		HOMEPAGE.NR_BLOGS_READERS DROP CONSTRAINT PK_BLOGS_STORIES;
ALTER TABLE 	HOMEPAGE.NR_BLOGS_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_BLOGS_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT PK_BLOGS_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_BLOGS_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_BLOGS_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_BLG_READER_STORY ON HOMEPAGE.NR_BLOGS_READERS;
GO

CREATE UNIQUE INDEX NR_BLG_READER_STORY 		
	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID);
	
GO

-- 6
ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS  DROP CONSTRAINT PK_BOOKS_STORIES;
ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_BOOKMARKS_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT PK_BOOKS_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_BOOK_READER_STORY ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

CREATE UNIQUE INDEX NR_BOOK_READER_STORY 		
	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID);

GO

-- 7
ALTER TABLE 	HOMEPAGE.NR_FILES_READERS DROP CONSTRAINT PK_FILES_STORIES;
ALTER TABLE 	HOMEPAGE.NR_FILES_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_FILES_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT PK_FILES_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_FILES_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_FILES_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_FILES_READER_STORY ON HOMEPAGE.NR_FILES_READERS;
GO

CREATE UNIQUE INDEX NR_FILES_READER_STORY 		
	ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID);
GO

-- 8
ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS DROP CONSTRAINT PK_FORUMS_STORIES;
ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_FORUMS_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT PK_FORUMS_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_FORUMS_READER_STORY ON HOMEPAGE.NR_FORUMS_READERS;
GO

CREATE UNIQUE INDEX NR_FORUMS_READER_STORY 	
	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID);
GO

-- 9
ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS DROP CONSTRAINT PK_WIKIS_STORIES;
ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_WIKIS_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT PK_WIKIS_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX NR_WIKIS_READER_STORY ON HOMEPAGE.NR_WIKIS_READERS;
GO

CREATE UNIQUE INDEX NR_WIKIS_READER_STORY 		
	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID);

GO

-- 10
ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS DROP CONSTRAINT PK_TAGS_STORIES;
ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_TAGS_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT PK_TAGS_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

--DROP INDEX NR_TAGS_READER_STORY ON HOMEPAGE.NR_TAGS_READERS;
--GO

--CREATE UNIQUE INDEX NR_TAGS_READER_STORY 		
--	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID);

--GO

-- 11 NR_STATUS_UPDATE_READERS
ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT PK_SU_READERS;
ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_STATUS_UPDATE_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT PK_SU_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX SU_STORIES_READER_STORY ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

CREATE UNIQUE INDEX SU_STORIES_READER_STORY
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID);

GO

-- 12 NR_EXTERNAL_READERS
ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT PK_EXT_STORIES;
ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_EXTERNAL_READERS SET CATEGORY_READER_ID = FOLLOWED_STORY_ID;
ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT PK_EXT_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS DROP COLUMN FOLLOWED_STORY_ID;

ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

DROP INDEX EXT_STORIES_READER_STORY ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

CREATE UNIQUE INDEX EXT_STORIES_READER_STORY
    ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID);

GO

-- 13-16 ACTIONABLE TABLES
ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT PK_ACTION_STORIES;
ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS ADD CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL;
GO
UPDATE 			HOMEPAGE.NR_ACTIONABLE_READERS SET CATEGORY_READER_ID = ACTIONABLE_READER_ID;
ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT PK_ACTION_READERS PRIMARY KEY(CATEGORY_READER_ID);
ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS DROP COLUMN ACTIONABLE_READER_ID;

ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS ADD IS_STORY_COMM NUMERIC(5 ,0);

GO

-------------------------------------------------------------------
-- Remove NR_ACTIONABLE_STORIES
-------------------------------------------------------------------
DROP TABLE HOMEPAGE.NR_ACTIONABLE_STORIES; 
GO

-------------------------------------------------------------------
-- TODO: Remove the 4 categories type, leave just one category (16)
-------------------------------------------------------------------

-------------------------------------------------------------------
-- TODO: Rename COMM_PERSON_STORIES to be HOMEPAGE.NR_AGGREGATED_READERS. Make it compatible withe other table
-------------------------------------------------------------------
-- Add a category type: aggregated_readers
CREATE TABLE HOMEPAGE.NR_AGGREGATED_READERS (
	CATEGORY_READER_ID nvarchar(36) DEFAULT ' ' NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5 ,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	ROLLUP_ENTRY_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5 ,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	SOURCE_TYPE NUMERIC(5 ,0),
	USE_IN_ROLLUP NUMERIC(5 ,0),
	IS_NETWORK	NUMERIC(5 ,0),
	IS_FOLLOWER	NUMERIC(5 ,0),
	EVENT_TIME 	DATETIME,
	IS_STORY_COMM NUMERIC(5 ,0)
) ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
    ADD CONSTRAINT PK_AGG_READERS PRIMARY KEY(CATEGORY_READER_ID);

CREATE INDEX NR_AGGREGATED_READERS_IDX
    ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE ASC, READER_ID);

CREATE INDEX NR_AGGREGATED_READERS_STORY_ID
    ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID);

CREATE INDEX NR_AGGREGATED_READERS_ITEM_ID
    ON HOMEPAGE.NR_AGGREGATED_READERS (ITEM_ID);

CREATE INDEX NR_AGGREGATED_READERS_DATE
    ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE ASC);

CREATE UNIQUE INDEX NR_AGG_READERS_UNQ
    ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, STORY_ID); 



-------------------------------------------------------------------    
-- MIGRATION FROM: NR_COMM_PERSON_STORIES -> NR_AGGREGATED_READERS
-------------------------------------------------------------------
INSERT INTO HOMEPAGE.NR_AGGREGATED_READERS
	SELECT 	COMM_PER_STORY_ID,
			COMM_PER_READER_ID,
			CATEGORY_TYPE,
			SOURCE,
			CONTAINER_ID,
			ITEM_ID,
			' ' ROLLUP_ENTRY_ID,
			RESOURCE_TYPE,
			CREATION_DATE,
			STORY_ID,
			SOURCE_TYPE,
			USE_IN_ROLLUP,
			IS_NETWORK,
			IS_FOLLOWER,
			EVENT_TIME,
			IS_STORY_COMM
	FROM 	HOMEPAGE.NR_COMM_PERSON_STORIES;

GO

-- DROPPING PREV. TABLE
DROP TABLE HOMEPAGE.NR_COMM_PERSON_STORIES;
GO
-------------------------------------------------------------------
-- Remove N_COMMENTS and N_RECOMMANDATIONS from BOARD_ENTRIES
-------------------------------------------------------------------

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.HOMEPAGE.BOARD_ENTRIES') and name like '%DF__BOARD_ENT__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.HOMEPAGE.BOARD_ENTRIES') and name like '%DF__BOARD_ENT__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE 	HOMEPAGE.BOARD_ENTRIES DROP COLUMN N_COMMENTS;
GO
ALTER TABLE 	HOMEPAGE.BOARD_ENTRIES DROP COLUMN N_RECOMMANDATIONS;
GO

-------------------------------------------------------------------
-- BOARD_OBJECT_REFERENCE 
-------------------------------------------------------------------
DROP TABLE HOMEPAGE.BOARD_ATTACHMENTS;

CREATE TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE (
	OBJECT_ID nvarchar(47) NOT NULL,
	ENTRY_ID nvarchar(47) NOT NULL,
	DISPLAY_NAME nvarchar(2048),
	IMAGE_NAME   nvarchar(2048),
	NAME nvarchar(1024),
	URL nvarchar(2048),
	CONTENT nvarchar(4000),
	IMAGE_URL nvarchar(2048),
	SOURCE  nvarchar(36),
	SOURCE_TYPE  NUMERIC(5 ,0),
	CREATION_DATE DATETIME,
	MIME_TYPE nvarchar(36),
	AUTHOR_ID nvarchar(36),
	AUTHOR_DISPLAY_NAME nvarchar(256)
) ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE 
    ADD CONSTRAINT PK_BRD_OBJ_ID PRIMARY KEY(OBJECT_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT FK_BRD_OBJ_ENTRY FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT FK_BRD_AUTHOR_ID FOREIGN KEY (AUTHOR_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

CREATE INDEX BRD_ENTRY_IDX
    ON HOMEPAGE.BOARD_OBJECT_REFERENCE (ENTRY_ID);

CREATE INDEX BRD_AUTHOR_IDX
    ON HOMEPAGE.BOARD_OBJECT_REFERENCE (AUTHOR_ID);

GO


-----------------------------------------------
-- HOMEPAGE.NR_COMM_SETTINGS
-----------------------------------------------

CREATE TABLE HOMEPAGE.NR_COMM_SETTINGS (
	COMM_ID nvarchar(36) NOT NULL,
	MICROBLOGGING_ENABLED NUMERIC(5 ,0),
	FLAGS nvarchar(36)
) ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS
    ADD CONSTRAINT PK_COMM_ID PRIMARY KEY(COMM_ID);


--------------------------------------------------------------------------
-- 17 HOMEPAGE.NR_DISCOVERY_VIEW
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_DISCOVERY_VIEW (
	CATEGORY_READER_ID nvarchar(36)  DEFAULT ' ' NOT NULL,
	READER_ID nvarchar(36),
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	ROLLUP_ENTRY_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	SOURCE_TYPE NUMERIC(5,0),
	USE_IN_ROLLUP NUMERIC(5,0),
	IS_NETWORK	NUMERIC(5,0),
	IS_FOLLOWER	NUMERIC(5,0),
	EVENT_TIME 	DATETIME,
	IS_STORY_COMM NUMERIC(5 ,0),
	CONSTRAINT   	CK_CAT17_TYPE
					CHECK
					(CATEGORY_TYPE = 17)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW 
    ADD CONSTRAINT PK_DISCOVERY_VIEW PRIMARY KEY(CATEGORY_READER_ID);

CREATE INDEX DISCOVERY_STORIES_IDX
    ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, CREATION_DATE ASC);

CREATE INDEX DISCOVERY_SIDX
    ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID);

CREATE INDEX DISCOVERY_ITEM
    ON HOMEPAGE.NR_DISCOVERY_VIEW (ITEM_ID);

CREATE INDEX DISCOVERY_STORIES_DATE
    ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE ASC);

CREATE UNIQUE INDEX DISCOVERY_READER_STORY 		
	ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, STORY_ID);   



INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('discovery-view', 17, '%discovery', 'discovery');

