-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------
-- 111057: Remove table references from SQL init code in sn.homepage
---------------------------------------------------
ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT FK_RES_RES_TYPE;
GO	
ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT FK_RES_CAT_TYPE;
GO
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP CONSTRAINT FK_RES_FRQ_TYPE;
GO

DROP TABLE HOMEPAGE.NR_RESOURCE_TYPE;
GO
DROP TABLE HOMEPAGE.NR_CATEGORY_TYPE;
GO
DROP TABLE HOMEPAGE.EMD_FREQUENCY_TYPE;
GO



--112212: [fixup468] Remove OLD_CONTENT BLOB field
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT DROP COLUMN OLD_CONTENT;
GO

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP COLUMN OLD_CONTENT;
GO

ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT DROP COLUMN OLD_CONTENT;
GO

ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP COLUMN OLD_CONTENT;
GO

ALTER TABLE HOMEPAGE.BOARD_COMMENTS DROP COLUMN OLD_CONTENT;
GO



CREATE  INDEX AGGREGATED_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX RESPONSES_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX PROFILES_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_PROFILES_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX COMM_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX ACTIVITIES_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX BLOGS_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_BLOGS_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX BOOKMARKS_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX FILES_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_FILES_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX FORUMS_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_FORUMS_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX WIKIS_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_WIKIS_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX TAGS_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_TAGS_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX STATUS_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX EXTERNAL_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX ACTIONABLE_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (CONTAINER_ID); 
GO
--
GO

CREATE  INDEX DISCOVERY_VIEW_CONT_IDX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (CONTAINER_ID); 
GO
--
GO

CREATE  INDEX PROFILES_VIEW_CONT_IDX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (CONTAINER_ID); 
GO
--


CREATE  INDEX NOTIFICA_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX NOT_REC_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX SAVED_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_SAVED_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX TOPICS_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_TOPICS_READERS (CONTAINER_ID); 
GO
--


CREATE  INDEX MENTIONS_READERS_CONT_IDX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (CONTAINER_ID); 
GO



--------------------------------------------------------------------------------------------
-- 113510: [fixup468] Add COMMUNITY_ID in READER|VIEW tables
--------------------------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_FILES_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_TAGS_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_SAVED_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW ADD  COMMUNITY_ID nvarchar(36);
GO

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW ADD  COMMUNITY_ID nvarchar(36);
GO
