-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}
---------------------------------------------------------------------------------------------------
-- 135559: Homepage_Check-SC-DB-Fixup IC10.0_Homepage_20140922-1157 - UNIQUE INDEX issues
---------------------------------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.TMP (
	CATEGORY_READER_ID nvarchar(36) NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL
);
GO


ALTER TABLE HOMEPAGE.TMP
    ADD CONSTRAINT PK_TMP PRIMARY KEY (CATEGORY_READER_ID);
GO

-- 148073: Homepage database fixup510 hangs
CREATE INDEX IDX1 ON HOMEPAGE.TMP (STORY_ID, READER_ID);
GO

--------------------------------------------------------------------------------------------------------
-- FIX NR_AGGREGATED_READERS TABLE
--------------------------------------------------------------------------------------------------------
-- I) SEARCH FOR DUPS
INSERT INTO HOMEPAGE.TMP (CATEGORY_READER_ID, STORY_ID, READER_ID, CATEGORY_TYPE) (
	SELECT READERS.CATEGORY_READER_ID, READERS.STORY_ID, READERS.READER_ID, READERS.CATEGORY_TYPE
	FROM
		(
		SELECT 	STORY_ID, READER_ID, CATEGORY_TYPE 
		FROM 	HOMEPAGE.NR_AGGREGATED_READERS    
		GROUP 	BY STORY_ID, READER_ID, CATEGORY_TYPE HAVING COUNT(*) > 1
		) TMP,
		HOMEPAGE.NR_AGGREGATED_READERS    READERS
	WHERE  	TMP.STORY_ID = READERS.STORY_ID AND 
			TMP.READER_ID = READERS.READER_ID AND
			TMP.CATEGORY_TYPE = READERS.CATEGORY_TYPE
);
GO

-- DELETE DUPS
DELETE FROM HOMEPAGE.NR_AGGREGATED_READERS WHERE CATEGORY_READER_ID IN (
	SELECT CATEGORY_READER_ID FROM HOMEPAGE.TMP WHERE CATEGORY_READER_ID < ( 
		SELECT 	MAX(CATEGORY_READER_ID) 
		FROM 	HOMEPAGE.TMP TMP
		WHERE 	TMP.STORY_ID = HOMEPAGE.NR_AGGREGATED_READERS.STORY_ID AND HOMEPAGE.NR_AGGREGATED_READERS.READER_ID = HOMEPAGE.NR_AGGREGATED_READERS.READER_ID AND TMP.CATEGORY_TYPE = HOMEPAGE.NR_AGGREGATED_READERS.CATEGORY_TYPE
		GROUP BY STORY_ID, READER_ID, CATEGORY_TYPE)
);
GO

-- CLEAN TMP TABLE
TRUNCATE TABLE HOMEPAGE.TMP;
GO
--------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------
-- FIX NR_STATUS_UPDATE_READERS TABLE
--------------------------------------------------------------------------------------------------------
-- I) SEARCH FOR DUPS
INSERT INTO HOMEPAGE.TMP (CATEGORY_READER_ID, STORY_ID, READER_ID, CATEGORY_TYPE) (
	SELECT READERS.CATEGORY_READER_ID, READERS.STORY_ID, READERS.READER_ID, READERS.CATEGORY_TYPE
	FROM
		(
		SELECT 	STORY_ID, READER_ID, CATEGORY_TYPE 
		FROM 	HOMEPAGE.NR_STATUS_UPDATE_READERS    
		GROUP 	BY STORY_ID, READER_ID, CATEGORY_TYPE HAVING COUNT(*) > 1
		) TMP,
		HOMEPAGE.NR_STATUS_UPDATE_READERS    READERS
	WHERE  	TMP.STORY_ID = READERS.STORY_ID AND 
			TMP.READER_ID = READERS.READER_ID AND
			TMP.CATEGORY_TYPE = READERS.CATEGORY_TYPE
);
GO

-- DELETE DUPS
DELETE FROM HOMEPAGE.NR_STATUS_UPDATE_READERS  WHERE CATEGORY_READER_ID IN (
	SELECT CATEGORY_READER_ID FROM HOMEPAGE.TMP WHERE CATEGORY_READER_ID < ( 
		SELECT 	MAX(CATEGORY_READER_ID) 
		FROM 	HOMEPAGE.TMP TMP
		WHERE 	TMP.STORY_ID = HOMEPAGE.NR_STATUS_UPDATE_READERS.STORY_ID AND TMP.READER_ID = HOMEPAGE.NR_STATUS_UPDATE_READERS.READER_ID AND TMP.CATEGORY_TYPE = HOMEPAGE.NR_STATUS_UPDATE_READERS.CATEGORY_TYPE
		GROUP BY STORY_ID, READER_ID, CATEGORY_TYPE)
);
GO

-- CLEAN TMP TABLE
TRUNCATE TABLE HOMEPAGE.TMP;
GO

--------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
-- FIX NR_SAVED_READERS TABLE
--------------------------------------------------------------------------------------------------------
-- I) SEARCH FOR DUPS
INSERT INTO HOMEPAGE.TMP (CATEGORY_READER_ID, STORY_ID, READER_ID, CATEGORY_TYPE) (
	SELECT READERS.CATEGORY_READER_ID, READERS.STORY_ID, READERS.READER_ID, READERS.CATEGORY_TYPE
	FROM
		(
		SELECT 	STORY_ID, READER_ID, CATEGORY_TYPE 
		FROM 	HOMEPAGE.NR_SAVED_READERS    
		GROUP 	BY STORY_ID, READER_ID, CATEGORY_TYPE HAVING COUNT(*) > 1
		) TMP,
		HOMEPAGE.NR_SAVED_READERS    READERS
	WHERE  	TMP.STORY_ID = READERS.STORY_ID AND 
			TMP.READER_ID = READERS.READER_ID AND
			TMP.CATEGORY_TYPE = READERS.CATEGORY_TYPE
);
GO

-- DELETE DUPS
DELETE FROM HOMEPAGE.NR_SAVED_READERS WHERE CATEGORY_READER_ID IN (
	SELECT CATEGORY_READER_ID FROM HOMEPAGE.TMP WHERE CATEGORY_READER_ID < ( 
		SELECT 	MAX(CATEGORY_READER_ID) 
		FROM 	HOMEPAGE.TMP TMP
		WHERE 	TMP.STORY_ID = HOMEPAGE.NR_SAVED_READERS.STORY_ID AND TMP.READER_ID = HOMEPAGE.NR_SAVED_READERS.READER_ID AND TMP.CATEGORY_TYPE = HOMEPAGE.NR_SAVED_READERS.CATEGORY_TYPE
		GROUP BY STORY_ID, READER_ID, CATEGORY_TYPE)
);
GO

-- CLEAN TMP TABLE
TRUNCATE TABLE HOMEPAGE.TMP;
GO

--------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
-- FIX NR_COMMUNITIES_VIEW TABLE
--------------------------------------------------------------------------------------------------------
-- I) SEARCH FOR DUPS
INSERT INTO HOMEPAGE.TMP (CATEGORY_READER_ID, STORY_ID, READER_ID, CATEGORY_TYPE) (
	SELECT READERS.CATEGORY_READER_ID, READERS.STORY_ID, READERS.READER_ID, READERS.CATEGORY_TYPE
	FROM
		(
		SELECT 	STORY_ID, READER_ID, CATEGORY_TYPE 
		FROM 	HOMEPAGE.NR_COMMUNITIES_VIEW    
		GROUP 	BY STORY_ID, READER_ID, CATEGORY_TYPE HAVING COUNT(*) > 1
		) TMP,
		HOMEPAGE.NR_COMMUNITIES_VIEW    READERS
	WHERE  	TMP.STORY_ID = READERS.STORY_ID AND 
			TMP.READER_ID = READERS.READER_ID AND
			TMP.CATEGORY_TYPE = READERS.CATEGORY_TYPE
);
GO

-- DELETE DUPS
DELETE FROM HOMEPAGE.NR_COMMUNITIES_VIEW  WHERE CATEGORY_READER_ID IN (
	SELECT CATEGORY_READER_ID FROM HOMEPAGE.TMP WHERE CATEGORY_READER_ID < ( 
		SELECT 	MAX(CATEGORY_READER_ID) 
		FROM 	HOMEPAGE.TMP TMP
		WHERE 	TMP.STORY_ID = HOMEPAGE.NR_COMMUNITIES_VIEW.STORY_ID AND TMP.READER_ID = HOMEPAGE.NR_COMMUNITIES_VIEW.READER_ID AND TMP.CATEGORY_TYPE = HOMEPAGE.NR_COMMUNITIES_VIEW.CATEGORY_TYPE
		GROUP BY STORY_ID, READER_ID, CATEGORY_TYPE)
);
GO

-- CLEAN TMP TABLE
TRUNCATE TABLE HOMEPAGE.TMP;
GO

--------------------------------------------------------------------------------------------------------------------------------

DROP TABLE HOMEPAGE.TMP;
GO

----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
-- 134379: [fixup505] Unique BOARD_RECOMMENDATIONS index needs to be changed

DROP INDEX BRD_REC_RECOM_ITEM_ID ON HOMEPAGE.BOARD_RECOMMENDATIONS;
GO	
    
CREATE UNIQUE INDEX BRD_REC_RECOM_D_ITEM_ID
	ON HOMEPAGE.BOARD_RECOMMENDATIONS (RECOMMENDER_ID_DISPLAY, ITEM_ID);
GO

-------------------------------------------------------------------------------------------------
--- Removing un-used tables
-------------------------------------------------------------------------------------------------

-- To speedup the merging process we remove indexes and FK from NR_AGGREGATED_READERS
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT PK_AGG_READERS;
GO

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_STR;
GO
	
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_ORG_ID;
GO

DROP  INDEX AGGREGATED_READERS_STR_IX ON  HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_ITM_IX ON  HOMEPAGE.NR_AGGREGATED_READERS; 
GO

DROP  INDEX AGGREGATED_READERS_CD_IX ON  HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_RLL_IIX ON  HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_STR_RDR ON  HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_DEL_SERV_IX ON  HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_ROLLUP_IIIX ON  HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_RLL_BRD_VVI ON  HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_COMM_IDX ON  HOMEPAGE.NR_AGGREGATED_READERS;
GO


-----------------------------------------------------------------------------------------------------
-- Merging just NR_DISCOVERY_VIEW
-----------------------------------------------------------------------------------------------------
-- warning c&p: just in sqlserver the order for the last three columns is: ROLLUP_AUTHOR_ID, IS_VISIBLE, COMMUNITY_ID
CREATE VIEW HOMEPAGE.NR_DISCOVEY_VIEW_IN AS (
	SELECT 
    	CATEGORY_READER_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID, ROLLUP_ENTRY_ID, 
		RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM, 
		IS_BROADCAST, ORGANIZATION_ID, ACTOR_UUID, ROLLUP_AUTHOR_ID, IS_VISIBLE, COMMUNITY_ID
    FROM HOMEPAGE.NR_DISCOVERY_VIEW
);
GO

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_DISCOVEY_VIEW_IN TO HOMEPAGEUSER;
GO

-- MUST COMMIT BEFORE ENABLING CMDSHELL --
COMMIT

-----------------------------------
-- Enable xp_cmdshell
----------------------------------

EXEC master.dbo.sp_configure 'show advanced options', 1
RECONFIGURE
EXEC master.dbo.sp_configure 'xp_cmdshell', 1
RECONFIGURE
----------------------------------

BEGIN TRANSACTION
GO

DECLARE 	@cmd varchar(255), 	@rc int, @tmpLocation varchar(255)
select 		@cmd='echo %TMP%'
create table #output (output varchar(255))
insert #output EXEC @rc = master..xp_cmdshell @cmd
select @tmpLocation=output from #output where output is not null
drop table #output 


declare @backup_command varchar(8000), @format_command varchar(8000), @bulk_insert_command varchar(8000) 
declare @format_file varchar(8000), @data_file varchar(8000)
set @format_file = @tmpLocation +'\format.fmt'
set @data_file = @tmpLocation + '\data510.dat'

declare @in_view varchar(8000), @out_table varchar(8000)
set @in_view = 'HOMEPAGE.HOMEPAGE.NR_DISCOVEY_VIEW_IN' -- The view name need also to be specified with the database name and the schema name
set @out_table = 'HOMEPAGE.NR_AGGREGATED_READERS' -- Schema name and table name

-- create the format file
set @format_command = 'bcp '+@in_view+' format nul -S '+@@servername+' -T -n -f "'+@format_file+'"'
EXEC master..xp_cmdshell @format_command

-- backup the data
set @backup_command = 'bcp '+@in_view+' out "'+@data_file+'" -n -S '+@@servername+' -T'
EXEC master..xp_cmdshell @backup_command

--insert back the record
set @bulk_insert_command = 'BULK INSERT '+@out_table+' FROM "'+@data_file+'" WITH (DATAFILETYPE="native", FORMATFILE="'+@format_file+'")'
EXEC (@bulk_insert_command) 
GO

COMMIT;
GO

-----------------------------------
-- Disable xp_cmdshell
----------------------------------

EXEC master.dbo.sp_configure 'show advanced options', 1
RECONFIGURE
EXEC master.dbo.sp_configure 'xp_cmdshell', 0
RECONFIGURE
----------------------------------

BEGIN TRANSACTION
GO

------------------------------------------------------------------------------------------------------------------------		
-- DROPPING TABLES (this will be done in a new fixup for debug purpose and in case something fail. This is to prevent data lost
-------------------------------------------------------------------------------------------------------------------------
--DROP TABLE HOMEPAGE.NR_RESPONSES_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_PROFILES_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_COMMUNITIES_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_ACTIVITIES_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_BLOGS_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_BOOKMARKS_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_FILES_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_FORUMS_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_WIKIS_READERS;
--GO

--DROP TABLE HOMEPAGE.NR_TAGS_READERS;
--GO												
		
--DROP TABLE HOMEPAGE.NR_DISCOVERY_VIEW; 
--GO

--DROP TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
--GO

-------------------------------------------------------------------------------------------------------------------------


-- We restore the constraints
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
    ADD CONSTRAINT PK_AGG_READERS PRIMARY KEY(CATEGORY_READER_ID);
    
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS 
	ADD CONSTRAINT FK_AGG_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);    
	
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX AGGREGATED_READERS_STR_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID); 
GO

CREATE  INDEX AGGREGATED_READERS_ITM_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ITEM_ID); 
GO

CREATE  INDEX AGGREGATED_READERS_CD_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, CREATION_DATE DESC); 
GO

--CREATE  INDEX AGGREGATED_READERS_RLL_IIX 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
--GO

--CREATE  INDEX AGGREGATED_READERS_STR_RDR 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, READER_ID); 
--GO

CREATE  INDEX AGGREGATED_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE DESC); 
GO

--CREATE  INDEX AGGREGATED_READERS_ROLLUP_IIIX 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC); 
--GO

CREATE  INDEX AGGREGATED_READERS_RLL_BRD_VVI
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE); 
GO


CREATE  INDEX AGGREGATED_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (COMMUNITY_ID); 
GO

--  [end indexes] NR_AGGREGATED_READERS

---------------------------------------------------------------------------------------------------------------
-- Dropping index
---------------------------------------------------------------------------------------------------------------


--  [start indexes] NR_AGGREGATED_READERS
--DROP  INDEX AGGREGATED_READERS_RLL_IIX 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS;
--GO

--DROP INDEX AGGREGATED_READERS_STR_RDR 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS;
--GO

--DROP  INDEX AGGREGATED_READERS_ROLLUP_IIIX 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS;
--GO

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX STATUS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP INDEX STATUS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX EXTERNAL_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP INDEX EXTERNAL_READERS_STR_RDR 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX ACTIONABLE_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP INDEX ACTIONABLE_READERS_STR_RDR 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX PROFILES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP INDEX PROFILES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX NOTIFICA_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP INDEX NOTIFICA_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_SAVED_READERS
DROP  INDEX SAVED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP INDEX SAVED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
DROP  INDEX TOPICS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP INDEX TOPICS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
DROP  INDEX MENTIONS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS;
GO

DROP INDEX MENTIONS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_MENTIONS_READERS;
GO

DROP  INDEX MENTIONS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS;
GO

--  [end indexes] NR_MENTIONS_READERS

--  [start indexes] NR_COMMUNITIES_VIEW
DROP  INDEX COMMUNITIES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW;
GO

DROP INDEX COMMUNITIES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW;
GO

DROP  INDEX COMMUNITIES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW;
GO

--  [end indexes] NR_COMMUNITIES_VIEW


-- CREATING INDEX



--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX AGGREGATED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX AGGREGATED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, READER_ID, CONTAINER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX AGGREGATED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX STATUS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX STATUS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX STATUS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX EXTERNAL_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX EXTERNAL_READERS_STR_RDR 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX EXTERNAL_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX ACTIONABLE_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX ACTIONABLE_READERS_STR_RDR 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX ACTIONABLE_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX PROFILES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX PROFILES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX PROFILES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX NOTIFICA_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX NOTIFICA_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX NOTIFICA_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX SAVED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX SAVED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX SAVED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX TOPICS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX TOPICS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX TOPICS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
CREATE  INDEX MENTIONS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX MENTIONS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_MENTIONS_READERS (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX MENTIONS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_MENTIONS_READERS

--  [start indexes] NR_COMMUNITIES_VIEW
CREATE  INDEX COMMUNITIES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC); 
GO

CREATE UNIQUE INDEX COMMUNITIES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, READER_ID, CATEGORY_TYPE); 
GO

CREATE  INDEX COMMUNITIES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC); 
GO

--  [end indexes] NR_COMMUNITIES_VIEW
