-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}




---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 104 -----------------------------------
---------------------------------------------------------------------------------

--69239: [fixup104] Accepting colleague invitation causes SQLServerException, ...bad grammer... use CONVERT
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST 
 ALTER COLUMN FULL_FOLLOWERS NVARCHAR(MAX);
GO

ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST 
 ALTER COLUMN FULL_DATA NVARCHAR(MAX);
GO 

-- 69579: cannot add more than 32767 comments to a status update
DROP INDEX BRD_COMM_ITEM_COR_PUB ON HOMEPAGE.BOARD_COMMENTS; 

ALTER TABLE HOMEPAGE.BOARD_COMMENTS ALTER COLUMN PUBLISHED_ORDER NUMERIC(10,0);
GO

CREATE UNIQUE INDEX BRD_COMM_ITEM_COR_PUB
    ON HOMEPAGE.BOARD_COMMENTS (ENTRY_ID, PUBLISHED_ORDER ASC); 
GO

--70007: [fixup104] HOMEPAGE slow response times while executing the following query on DB2 AIX 
-- SELECT HOMEPAGE.NR_NEWS_STATUS_NETWORK.NEWS_STATUS_NETWORK_ID, ..........
DROP INDEX  NR_NEWS_STATUS_NETWORK_READER ON HOMEPAGE.NR_NEWS_STATUS_NETWORK ;
GO

CREATE INDEX NEWS_STATUS_NET_R_U 
	ON HOMEPAGE.NR_NEWS_STATUS_NETWORK (READER_ID, UPDATE_DATE DESC);
GO

--70800: [fixup104] add an index on  RELATED_COMMUNITY_ID
CREATE INDEX NR_STORIES_REL_COMM
	ON HOMEPAGE.NR_STORIES (RELATED_COMMUNITY_ID);
GO	



------------------------------------------------------------------------------------------------------------------
-- [START] 70802: [fixup104] add the column MAX_UPDATE_FOR_READER to READERS and VIEW tables
------------------------------------------------------------------------------------------------------------------

ALTER TABLE  HOMEPAGE.NR_AGGREGATED_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_RESPONSES_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_PROFILES_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_COMMUNITIES_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_ACTIVITIES_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_BLOGS_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_BOOKMARKS_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_FILES_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_FORUMS_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_WIKIS_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_TAGS_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_STATUS_UPDATE_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_EXTERNAL_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_SAVED_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_ACTIONABLE_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_DISCOVERY_VIEW ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_PROFILES_VIEW ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

ALTER TABLE  HOMEPAGE.NR_TOPICS_READERS ADD MAX_UPDATE_FOR_READER DATETIME;
GO

------------------------------------------------------------------------------------------------------------------
-- [END] 70802: [fixup104] add the column MAX_UPDATE_FOR_READER to READERS and VIEW tables
------------------------------------------------------------------------------------------------------------------


-----------------------------------------------------------------------------------------------------
-- [START] 70821: [fixup104] After rally we see we can improve of 90% perf. on querying readers table.
-----------------------------------------------------------------------------------------------------

--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX AGGREGATED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX RESPONSES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX PROFILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX COMM_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX ACTIVITIES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX BLOGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX BOOKMARKS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX FILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX FORUMS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX WIKIS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX TAGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX STATUS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX EXTERNAL_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX SAVED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX ACTIONABLE_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX DISCOVERY_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX PROFILES_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX NOTIFICA_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX NOT_REC_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX TOPICS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_TOPICS_READERS

-- 70839: Found as part of defect 70701 - need to set IS_READER_COMM to 1 as part of upgrade scripts
UPDATE HOMEPAGE.NR_COMM_PERSON_FOLLOW  SET IS_READER_COMM = 1 WHERE NOT EXISTS (
	SELECT 	1
 	FROM  	HOMEPAGE.PERSON PERSON
 	WHERE 	HOMEPAGE.NR_COMM_PERSON_FOLLOW.PERSON_COMMUNITY_ID = PERSON.PERSON_ID 
);
GO

-----------------------------------------------------------------------------------------------------
-- [END] 70821: [fixup104] After rally we see we can improve of 90% perf. on querying readers table.
-----------------------------------------------------------------------------------------------------

-- 71352: SQL server - Comments are not appearing inline in Homepage Activity Stream
ALTER TABLE HOMEPAGE.NR_ENTRIES ALTER COLUMN ITEM_UPDATE_DATE DATETIME NULL;
GO

ALTER TABLE HOMEPAGE.NR_ENTRIES ALTER COLUMN ITEM_CREATION_DATE DATETIME NULL;
GO

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE ALTER COLUMN ITEM_UPDATE_DATE DATETIME NULL;
GO

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE ALTER COLUMN ITEM_CREATION_DATE DATETIME NULL;
GO

---------------------------------------------------------------------------------
------------------------ END NEWS FIXUP 104 -------------------------------------
---------------------------------------------------------------------------------
 

  
  
  
