-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2016                                   
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- -----------------------------------------------------------------
-- Visitor model event tracking table
-- -----------------------------------------------------------------

CREATE TABLE HOMEPAGE.VM_EVENT_TRACKER(
	SUBSCRIBER_ID nvarchar(36) NOT NULL,
	VISITING_ORG_ID nvarchar(36),
	HOME_ORG_ID nvarchar(36),
	LAST_MODIFIED DATETIME2(6) NOT NULL,
	MIGRATED NUMERIC(5,0) DEFAULT 0 NOT NULL,
	EVENT_NAME nvarchar(36) NOT NULL
)ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.VM_EVENT_TRACKER ADD CONSTRAINT PK_VM_SUBSCRIBER_ID PRIMARY KEY (SUBSCRIBER_ID);
CREATE INDEX VM_VISITING_ORG_IDX ON HOMEPAGE.VM_EVENT_TRACKER (VISITING_ORG_ID);
CREATE INDEX VM_HOME_ORG_IDX ON HOMEPAGE.VM_EVENT_TRACKER (HOME_ORG_ID);

GO

-- -----------------------------------------------------------------
-- IC Task 173439
-- -----------------------------------------------------------------

DROP INDEX AGGREGATED_READERS_ROLLUP_IIIX ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

CREATE INDEX AGGREGATED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX STATUS_READERS_ROLLUP_IIIX ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

CREATE INDEX STATUS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX EXTERNAL_READERS_ROLLUP_IIIX ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

CREATE INDEX EXTERNAL_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX ACTIONABLE_READERS_ROLLUP_IIIX ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

CREATE INDEX ACTIONABLE_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX PROFILES_VIEW_ROLLUP_IIIX ON HOMEPAGE.NR_PROFILES_VIEW;
GO

CREATE INDEX PROFILES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX NOTIFICA_READERS_ROLLUP_IIIX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

CREATE INDEX NOTIFICA_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX SAVED_READERS_ROLLUP_IIIX ON HOMEPAGE.NR_SAVED_READERS;
GO

CREATE INDEX SAVED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX TOPICS_READERS_ROLLUP_IIIX ON HOMEPAGE.NR_TOPICS_READERS;
GO

CREATE INDEX TOPICS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX MENTIONS_READERS_ROLLUP_IIIX ON HOMEPAGE.NR_MENTIONS_READERS;
GO

CREATE INDEX MENTIONS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 

DROP INDEX COMMUNITIES_VIEW_ROLLUP_IIIX ON HOMEPAGE.NR_COMMUNITIES_VIEW;
GO

CREATE INDEX COMMUNITIES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE); 
GO 
