-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

--------------------------------------------------
-- ADDING COLUMN ITEM_CORRELATION_NAME TO NR_STORIES
--------------------------------------------------
ALTER TABLE HOMEPAGE.NR_STORIES
    ADD ITEM_CORRELATION_NAME nvarchar(256);
     
--------------------------------------------------------------------------
-- 1 NR_RESPONSES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_RESPONSES_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT1_TYPE
					CHECK
					(CATEGORY_TYPE = 1)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_RESPONSES_STORIES 
    ADD CONSTRAINT PK_RESP_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_RESPONSES_STORIES
    ADD CONSTRAINT FK_RESP_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX RESPONSES_STORIES_IDX
    ON HOMEPAGE.NR_RESPONSES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX RESPONSES_STORIES_CIDX
    ON HOMEPAGE.NR_RESPONSES_STORIES (CATEGORY_TYPE);

CREATE INDEX RESPONSES_STORIES_SIDX
    ON HOMEPAGE.NR_RESPONSES_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_RESPONSES_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 2 NR_PROFILES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_PROFILES_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT2_TYPE
					CHECK
					(CATEGORY_TYPE = 2)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_PROFILES_STORIES 
    ADD CONSTRAINT PK_PROF_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_PROFILES_STORIES
    ADD CONSTRAINT FK_PROF_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX PROFILES_STORIES_IDX
    ON HOMEPAGE.NR_PROFILES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX PROFILES_STORIES_CIDX
    ON HOMEPAGE.NR_PROFILES_STORIES (CATEGORY_TYPE);

CREATE INDEX PROFILES_STORIES_SIDX
    ON HOMEPAGE.NR_PROFILES_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_PROFILES_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 3 NR_COMMUNITIES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_COMMUNITIES_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT3_TYPE
					CHECK
					(CATEGORY_TYPE = 3)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_STORIES 
    ADD CONSTRAINT PK_COMM_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_STORIES
    ADD CONSTRAINT FK_COM_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX COMMUNITIES_STORIES_IDX
    ON HOMEPAGE.NR_COMMUNITIES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX COMMUNITIES_STORIES_CIDX
    ON HOMEPAGE.NR_COMMUNITIES_STORIES (CATEGORY_TYPE);

CREATE INDEX COMMUNITIES_STORIES_SIDX
    ON HOMEPAGE.NR_COMMUNITIES_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_COMMUNITIES_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 4 NR_ACTIVITIES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ACTIVITIES_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT4_TYPE
					CHECK
					(CATEGORY_TYPE = 4)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_STORIES 
    ADD CONSTRAINT PK_ACT_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_STORIES
    ADD CONSTRAINT FK_ACT_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX ACTIVITIES_STORIES_IDX
    ON HOMEPAGE.NR_ACTIVITIES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX ACTIVITIES_STORIES_CIDX
    ON HOMEPAGE.NR_ACTIVITIES_STORIES (CATEGORY_TYPE);

CREATE INDEX ACTIVITIES_STORIES_SIDX
    ON HOMEPAGE.NR_ACTIVITIES_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_ACTIVITIES_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 5 NR_BLOGS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_BLOGS_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT5_TYPE
					CHECK
					(CATEGORY_TYPE = 5)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_BLOGS_STORIES 
    ADD CONSTRAINT PK_BLOGS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_BLOGS_STORIES
    ADD CONSTRAINT FK_BLOGS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX BLOGS_STORIES_IDX
    ON HOMEPAGE.NR_BLOGS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX BLOGS_STORIES_CIDX
    ON HOMEPAGE.NR_BLOGS_STORIES (CATEGORY_TYPE);

CREATE INDEX BLOGS_STORIES_SIDX
    ON HOMEPAGE.NR_BLOGS_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_BLOGS_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 6 NR_BOOKMARKS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_BOOKMARKS_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT6_TYPE
					CHECK
					(CATEGORY_TYPE = 6)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_STORIES 
    ADD CONSTRAINT PK_BOOKS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_STORIES
    ADD CONSTRAINT FK_BOOKS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX BOOKMARKS_STORIES_IDX
    ON HOMEPAGE.NR_BOOKMARKS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX BOOKMARKS_STORIES_CIDX
    ON HOMEPAGE.NR_BOOKMARKS_STORIES (CATEGORY_TYPE);

CREATE INDEX BOOKMARKS_STORIES_SIDX
    ON HOMEPAGE.NR_BOOKMARKS_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_BOOKMARKS_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 7 NR_FILES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_FILES_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT7_TYPE
					CHECK
					(CATEGORY_TYPE = 7)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_FILES_STORIES 
    ADD CONSTRAINT PK_FILES_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_FILES_STORIES
    ADD CONSTRAINT FK_FILES_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX FILES_STORIES_IDX
    ON HOMEPAGE.NR_FILES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX FILES_STORIES_CIDX
    ON HOMEPAGE.NR_FILES_STORIES (CATEGORY_TYPE);

CREATE INDEX FILES_STORIES_SIDX
    ON HOMEPAGE.NR_FILES_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_FILES_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 8 NR_FORUMS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_FORUMS_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT8_TYPE
					CHECK
					(CATEGORY_TYPE = 8)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_FORUMS_STORIES 
    ADD CONSTRAINT PK_FORUMS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_FORUMS_STORIES
    ADD CONSTRAINT FK_FORUMS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX FORUMS_STORIES_IDX
    ON HOMEPAGE.NR_FORUMS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX FORUMS_STORIES_CIDX
    ON HOMEPAGE.NR_FORUMS_STORIES (CATEGORY_TYPE);

CREATE INDEX FORUMS_STORIES_SIDX
    ON HOMEPAGE.NR_FORUMS_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_FORUMS_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 9 NR_WIKIS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_WIKIS_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT9_TYPE
					CHECK
					(CATEGORY_TYPE = 9)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_WIKIS_STORIES 
    ADD CONSTRAINT PK_WIKIS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_WIKIS_STORIES
    ADD CONSTRAINT FK_WIKIS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX WIKIS_STORIES_IDX
    ON HOMEPAGE.NR_WIKIS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX WIKIS_STORIES_CIDX
    ON HOMEPAGE.NR_WIKIS_STORIES (CATEGORY_TYPE);

CREATE INDEX WIKIS_STORIES_SIDX
    ON HOMEPAGE.NR_WIKIS_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_WIKIS_STORIES {SQL_GRANT_STOP}

GO

--------------------------------------------------------------------------
-- 10 NR_TAGS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_TAGS_STORIES (
	FOLLOWED_STORY_ID nvarchar(36) NOT NULL,
	READER_ID nvarchar(36) NOT NULL,
	CATEGORY_TYPE NUMERIC(5,0) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(256),
	ITEM_ID nvarchar(36),
	RESOURCE_TYPE NUMERIC(5,0) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	STORY_ID nvarchar(36) NOT NULL,
	CONSTRAINT   	CK_CAT10_TYPE
					CHECK
					(CATEGORY_TYPE = 10)
)
ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.NR_TAGS_STORIES 
    ADD CONSTRAINT PK_TAGS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_TAGS_STORIES
    ADD CONSTRAINT FK_TAGS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX TAGS_STORIES_IDX
    ON HOMEPAGE.NR_TAGS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX TAGS_STORIES_CIDX
    ON HOMEPAGE.NR_TAGS_STORIES (CATEGORY_TYPE);

CREATE INDEX TAGS_STORIES_SIDX
    ON HOMEPAGE.NR_TAGS_STORIES (STORY_ID);

{SQL_GRANT_START} HOMEPAGE.NR_TAGS_STORIES {SQL_GRANT_STOP}
GO

--------------------------------------------------------------------------------------------------------------
-- RENAME THE ORIGINAL TABLE SO WE CAN USE THE VIEW NAME TO REFERENCE FROM THE CODE THE NEW SET OF TABLES
--------------------------------------------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_FOLLOWED_STORIES DROP CONSTRAINT FK_F_STORY_ID;
GO

EXEC sp_rename 'HOMEPAGE.NR_FOLLOWED_STORIES', 'FOLLOWED_STORIES_ORIGINAL';
GO

{SQL_GRANT_START} HOMEPAGE.FOLLOWED_STORIES_ORIGINAL {SQL_GRANT_STOP} 
GO
--------------------------------------------------------------------------------------------------------------
-- CREATE THE VIEW FOR ALL THE STORIES
--------------------------------------------------------------------------------------------------------------
CREATE VIEW HOMEPAGE.NR_FOLLOWED_STORIES AS (
    SELECT * FROM HOMEPAGE.NR_RESPONSES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_PROFILES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_COMMUNITIES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ACTIVITIES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_BLOGS_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_BOOKMARKS_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_FILES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_FORUMS_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_WIKIS_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_TAGS_STORIES
);
GO

{SQL_GRANT_START} HOMEPAGE.NR_FOLLOWED_STORIES {SQL_GRANT_STOP}
GO

------------------------------------------------------------------------------------------------------
-- MOVING BACK DATA
------------------------------------------------------------------------------------------------------

----------------------------
-- 1 NR_RESPONSES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 1;

GO

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 1;

GO

----------------------------
-- 2 NR_PROFILES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 2;

GO

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 2;

GO

----------------------------
-- 3 NR_COMMUNITIES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 3;

GO

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 3;

GO

----------------------------
-- 4 NR_ACTIVITIES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 4;

GO

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 4;

GO

----------------------------
-- 5 NR_BLOGS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 5;

GO

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 5;

GO

----------------------------
-- 6 NR_BOOKMARKS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 6;

GO

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 6;

GO

----------------------------
-- 7 NR_FILES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 7;

GO

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 7;

GO

----------------------------
-- 8 NR_FORUMS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 8;

GO

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 8;

GO

----------------------------
-- 9 NR_WIKIS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 9;

GO

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 9;

GO

----------------------------
-- 10 NR_TAGS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 10;

GO

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 10;

GO

------------------------------------
-- DROP TEMP TABLE
------------------------------------
DROP TABLE HOMEPAGE.FOLLOWED_STORIES_ORIGINAL;

GO