-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 101 -----------------------------------
---------------------------------------------------------------------------------

ALTER TABLE HOMEPAGE.BOARD_COMMENTS 
	ADD TAGS nvarchar(1024);
GO 


ALTER TABLE HOMEPAGE.BOARD_ENTRIES
	DROP COLUMN CONTAINER_NAME;
GO 


ALTER TABLE HOMEPAGE.NR_ENTRIES
	DROP COLUMN TARGET_SUBJECT_ID;
GO

ALTER TABLE HOMEPAGE.NR_ENTRIES
	ADD LAST_UPDATE_RECORD DATETIME;
GO


ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	DROP COLUMN TARGET_SUBJECT_ID;
GO

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ADD LAST_UPDATE_RECORD DATETIME;
GO


ALTER TABLE HOMEPAGE.NR_STORIES
	ADD CONTAINER_ATOM_URL nvarchar(2048);
GO 


ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS 
	ADD STAT_UPDATE_DATE DATETIME;
GO

ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST 
	DROP COLUMN EVENT_RECORD_UUID;
GO

-------------------------------------------------------------------------
-- Insert repost author templates
-------------------------------------------------------------------------

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('itemAuthor-wPldKwZTaR7aAiPFw4L08CyRW','Author', 'asItemAuthor','profilePhoto', 1);

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('itemauthor-wPldKwZTaR7aAiPFw4L08CyRW','author', 'asItemAuthor','profilePhoto',  1);

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('itemCorrAuthorkla9034jl89vasgf3k5Wfd','correlationItemAuthor', 'correlationItemAuthor','profilePhoto',  1);

GO

-------------------------------------------------------------------------
-- Fix SOURCE TYPE data
-------------------------------------------------------------------------


UPDATE HOMEPAGE.NR_SOURCE_TYPE SET IMAGE_URL_SSL = IMAGE_URL;

GO


---------------------------------------------------------------------------------
-- 36 -> 256
---------------------------------------------------------------------------------


ALTER TABLE HOMEPAGE.NR_ENTRIES
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES
	ALTER COLUMN ITEM_CORRELATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES
	ALTER COLUMN LAST_COMMENT_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES
	ALTER COLUMN PREV_COMMENT_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES
	ALTER COLUMN ITEM_AUTHOR_UUID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES
	ALTER COLUMN ITEM_CORRELATION_AUTHOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ALTER COLUMN ITEM_CORRELATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ALTER COLUMN LAST_COMMENT_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ALTER COLUMN PREV_COMMENT_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ALTER COLUMN ITEM_AUTHOR_UUID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ALTER COLUMN ITEM_CORRELATION_AUTHOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_STORIES
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_STORIES
	ALTER COLUMN ITEM_CORRELATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_STORIES
	ALTER COLUMN ITEM_AUTHOR_UUID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_STORIES
	ALTER COLUMN ITEM_CORRELATION_AUTHOR_UUID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_STORIES
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_PROFILES_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_SAVED_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_SAVED_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_SAVED_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_SAVED_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_SAVED_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


ALTER TABLE HOMEPAGE.NR_TOPICS_READERS
	ALTER COLUMN ITEM_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS
	ALTER COLUMN ROLLUP_ENTRY_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS
	ALTER COLUMN ORGANIZATION_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS
	ALTER COLUMN ROLLUP_AUTHOR_ID nvarchar(256);

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS
	ALTER COLUMN ACTOR_UUID nvarchar(256);

GO


---------------------------------------------------------------------------------
-- READER TABLES: MAKE INDEX ON READER_ID,STORY_ID CLUSTER
---------------------------------------------------------------------------------

DROP INDEX AGGREGATED_READERS_RDR_STR ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP INDEX CL_AGGREGATED_READERS_IDX ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

CREATE CLUSTERED INDEX AGGREGATED_READERS_RDR_STR
ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_AGGREGATED_READERS_IDX
ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID);
GO


DROP INDEX RESPONSES_READERS_RDR_STR ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP INDEX CL_RESPONSES_READERS_IDX ON HOMEPAGE.NR_RESPONSES_READERS;
GO

CREATE CLUSTERED INDEX RESPONSES_READERS_RDR_STR
ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_RESPONSES_READERS_IDX
ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID);
GO


DROP INDEX PROFILES_READERS_RDR_STR ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP INDEX CL_PROFILES_READERS_IDX ON HOMEPAGE.NR_PROFILES_READERS;
GO

CREATE CLUSTERED INDEX PROFILES_READERS_RDR_STR
ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_PROFILES_READERS_IDX
ON HOMEPAGE.NR_PROFILES_READERS (READER_ID);
GO


DROP INDEX COMM_READERS_RDR_STR ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP INDEX CL_COMM_READERS_IDX ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

CREATE CLUSTERED INDEX COMM_READERS_RDR_STR
ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_COMM_READERS_IDX
ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID);
GO


DROP INDEX ACTIVITIES_READERS_RDR_STR ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP INDEX CL_ACTIVITIES_READERS_IDX ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

CREATE CLUSTERED INDEX ACTIVITIES_READERS_RDR_STR
ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_ACTIVITIES_READERS_IDX
ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID);
GO


DROP INDEX BLOGS_READERS_RDR_STR ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP INDEX CL_BLOGS_READERS_IDX ON HOMEPAGE.NR_BLOGS_READERS;
GO

CREATE CLUSTERED INDEX BLOGS_READERS_RDR_STR
ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_BLOGS_READERS_IDX
ON HOMEPAGE.NR_BLOGS_READERS (READER_ID);
GO


DROP INDEX BOOKMARKS_READERS_RDR_STR ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP INDEX CL_BOOKMARKS_READERS_IDX ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

CREATE CLUSTERED INDEX BOOKMARKS_READERS_RDR_STR
ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_BOOKMARKS_READERS_IDX
ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID);
GO


DROP INDEX FILES_READERS_RDR_STR ON HOMEPAGE.NR_FILES_READERS;
GO

DROP INDEX CL_FILES_READERS_IDX ON HOMEPAGE.NR_FILES_READERS;
GO

CREATE CLUSTERED INDEX FILES_READERS_RDR_STR
ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_FILES_READERS_IDX
ON HOMEPAGE.NR_FILES_READERS (READER_ID);
GO


DROP INDEX FORUMS_READERS_RDR_STR ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP INDEX CL_FORUMS_READERS_IDX ON HOMEPAGE.NR_FORUMS_READERS;
GO

CREATE CLUSTERED INDEX FORUMS_READERS_RDR_STR
ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_FORUMS_READERS_IDX
ON HOMEPAGE.NR_FORUMS_READERS (READER_ID);
GO


DROP INDEX WIKIS_READERS_RDR_STR ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP INDEX CL_WIKIS_READERS_IDX ON HOMEPAGE.NR_WIKIS_READERS;
GO

CREATE CLUSTERED INDEX WIKIS_READERS_RDR_STR
ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_WIKIS_READERS_IDX
ON HOMEPAGE.NR_WIKIS_READERS (READER_ID);
GO


DROP INDEX TAGS_READERS_RDR_STR ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP INDEX CL_TAGS_READERS_IDX ON HOMEPAGE.NR_TAGS_READERS;
GO

CREATE CLUSTERED INDEX TAGS_READERS_RDR_STR
ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_TAGS_READERS_IDX
ON HOMEPAGE.NR_TAGS_READERS (READER_ID);
GO


DROP INDEX STATUS_READERS_RDR_STR ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP INDEX CL_STATUS_READERS_IDX ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

CREATE CLUSTERED INDEX STATUS_READERS_RDR_STR
ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_STATUS_READERS_IDX
ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID);
GO


DROP INDEX EXTERNAL_READERS_RDR_STR ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP INDEX CL_EXTERNAL_READERS_IDX ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

CREATE CLUSTERED INDEX EXTERNAL_READERS_RDR_STR
ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_EXTERNAL_READERS_IDX
ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID);
GO


DROP INDEX ACTIONABLE_READERS_RDR_STR ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP INDEX CL_ACTIONABLE_READERS_IDX ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

CREATE CLUSTERED INDEX ACTIONABLE_READERS_RDR_STR
ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_ACTIONABLE_READERS_IDX
ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID);
GO


DROP INDEX DISCOVERY_VIEW_RDR_STR ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP INDEX CL_DISCOVERY_READERS_IDX ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

CREATE CLUSTERED INDEX DISCOVERY_VIEW_RDR_STR
ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, STORY_ID);
GO

CREATE INDEX CL_DISCOVERY_READERS_IDX
ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID);
GO


DROP INDEX PROFILES_VIEW_RDR_STR ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP INDEX CL_PROFILESV_READERS_IDX ON HOMEPAGE.NR_PROFILES_VIEW;
GO

CREATE CLUSTERED INDEX PROFILES_VIEW_RDR_STR
ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, STORY_ID);
GO

CREATE INDEX CL_PROFILESV_READERS_IDX
ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID);
GO


DROP INDEX NOTIFICA_READERS_RDR_STR ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP INDEX CL_NOTIFICA_READERS_IDX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

CREATE CLUSTERED INDEX NOTIFICA_READERS_RDR_STR
ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_NOTIFICA_READERS_IDX
ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID);
GO


DROP INDEX NOT_REC_READERS_RDR_STR ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP INDEX CL_REC_READERS_IDX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

CREATE CLUSTERED INDEX NOT_REC_READERS_RDR_STR
ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_REC_READERS_IDX
ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID);
GO


DROP INDEX SAVED_READERS_RDR_STR ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP INDEX CL_SAVED_READERS_IDX ON HOMEPAGE.NR_SAVED_READERS;
GO

CREATE CLUSTERED INDEX SAVED_READERS_RDR_STR
ON HOMEPAGE.NR_SAVED_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_SAVED_READERS_IDX
ON HOMEPAGE.NR_SAVED_READERS (READER_ID);
GO


DROP INDEX TOPICS_READERS_RDR_STR ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP INDEX CL_TOPICS_READERS_IDX ON HOMEPAGE.NR_TOPICS_READERS;
GO

CREATE CLUSTERED INDEX TOPICS_READERS_RDR_STR
ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, STORY_ID);
GO

CREATE INDEX CL_TOPICS_READERS_IDX
ON HOMEPAGE.NR_TOPICS_READERS (READER_ID);
GO

---------------------------------------------------------------------------------
-- READER TABLES: ADD NEW INDEX
---------------------------------------------------------------------------------

CREATE INDEX AGGREGATED_READERS_RIR_IX
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX RESPONSES_READERS_RIR_IX
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX PROFILES_READERS_RIR_IX
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX COMM_READERS_RIR_IX
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX ACTIVITIES_READERS_RIR_IX
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX BLOGS_READERS_RIR_IX
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX BOOKMARKS_READERS_RIR_IX
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX FILES_READERS_RIR_IX
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX FORUMS_READERS_RIR_IX
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX WIKIS_READERS_RIR_IX
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX TAGS_READERS_RIR_IX
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX STATUS_READERS_RIR_IX
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX EXTERNAL_READERS_RIR_IX
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX ACTIONABLE_READERS_RIR_IX
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX DISCOVERY_VIEW_RIR_IX
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX PROFILES_VIEW_RIR_IX
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX NOTIFICA_READERS_RIR_IX
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX NOT_REC_READERS_RIR_IX
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX SAVED_READERS_RIR_IX
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE INDEX TOPICS_READERS_RIR_IX
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO


---------------------------------------------------------------------------------
--Community Event Widget
---------------------------------------------------------------------------------

INSERT INTO HOMEPAGE.WIDGET
            (WIDGET_ID, WIDGET_TITLE, WIDGET_TEXT, WIDGET_URL, WIDGET_ICON, WIDGET_ENABLED, WIDGET_SYSTEM, WIDGET_HOMEPAGE_SPECIFIC, WIDGET_PREVIEW_IMAGE, WIDGET_CATEGORY, WIDGET_IS_DEFAULT_OPENED, WIDGET_MULTIPLE_INSTANCES, WIDGET_SECURE_URL, WIDGET_SECURE_ICON, IS_GADGET)
VALUES      ('commuevtxe7c4x4e08xab54x80e7a4eb8933', '%widget.communities.event.name', '%widget.communities.event.desc', '${COMMON_CONTEXT_ROOT}/web/lconn.calendar/CalendarGadget.xml', '${COMMON_CONTEXT_ROOT}/web/com.ibm.lconn.core.styles/images/iconCommunities16.png', 1, 1, 1, '${HOMEPAGE_CONTEXT_ROOT}/web/jsp/palette/images/profiles_my_colleagues.jpg', 'COMMUNITIES', 1,  0, '${COMMON_CONTEXT_ROOT}/web/lconn.calendar/CalendarGadget.xml', '${COMMON_CONTEXT_ROOT}/web/com.ibm.lconn.core.styles/images/iconCommunities16.png',1);

INSERT INTO HOMEPAGE.PREREQ
            (PREREQ_ID, APP_ID, WIDGET_ID)
VALUES      ('73de6654x9317x4195x90c0x696c1b6da4ff', 'communities', 'commuevtxe7c4x4e08xab54x80e7a4eb8933');

INSERT INTO HOMEPAGE.HP_WIDGET_TAB
        (WIDGET_TAB_ID, WIDGET_ID, TAB_ID, TYPE)
VALUES  ('UPDATES_communityevent-sidebar', 'commuevtxe7c4x4e08xab54x80e7a4eb8933', '_panel.updatex4a43x82aaxb00187218631', 'primary');

GO


-------------------------- fixing issue with is_prev is_last comment ------------------------

--  [start] NR_ENTRIES
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID < '0..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID < '0..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '0..f' AND ENTRY_ID < '1..f'  ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '0..f' AND ENTRY_ID < '1..f'  ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '1..f' AND ENTRY_ID < '2..f'  ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '1..f' AND ENTRY_ID < '2..f'  ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '2..f' AND ENTRY_ID < '3..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '2..f' AND ENTRY_ID < '3..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '3..f' AND ENTRY_ID < '4..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '3..f' AND ENTRY_ID < '4..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '4..f' AND ENTRY_ID < '5..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '4..f' AND ENTRY_ID < '5..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '5..f' AND ENTRY_ID < '6..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '5..f' AND ENTRY_ID < '6..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '6..f' AND ENTRY_ID < '7..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '6..f' AND ENTRY_ID < '7..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '7..f' AND ENTRY_ID < '8..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '7..f' AND ENTRY_ID < '8..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '8..f' AND ENTRY_ID < '9..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '8..f' AND ENTRY_ID < '9..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '9..f' AND ENTRY_ID < 'a..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '9..f' AND ENTRY_ID < 'a..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'a..f' AND ENTRY_ID < 'b..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'a..f' AND ENTRY_ID < 'b..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'b..f' AND ENTRY_ID < 'c..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'b..f' AND ENTRY_ID < 'c..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'c..f' AND ENTRY_ID < 'd..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'c..f' AND ENTRY_ID < 'd..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'd..f' AND ENTRY_ID < 'e..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'd..f' AND ENTRY_ID < 'e..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'e..f' AND ENTRY_ID < 'f..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'e..f' AND ENTRY_ID < 'f..f' ;
GO

UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'f..f' ;
GO
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'f..f' ;
GO

--  [end] NR_ENTRIES


---------------------------------------------------------------------------------
------------------------ END NEWS FIXUP 101 -------------------------------------
---------------------------------------------------------------------------------
