-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 456 -----------------------------------
---------------------------------------------------------------------------------

-- 96380: DAO and DB schema changes for local caching

--------------------------------------------------
-- HOMEPAGE.IMG_CACHE
--------------------------------------------------
CREATE TABLE HOMEPAGE.IMG_CACHE (
	IMG_CACHE_ID nvarchar(36) NOT NULL,
	ORIGINAL_URL nvarchar (1024) NOT NULL,
	FILE_PATH nvarchar (256) NOT NULL,
	NUM_REQUEST NUMERIC (10, 0),
	CREATION_DATE DATETIME,
	LAST_REQUEST_DATE DATETIME,
	MAX_HEIGHT NUMERIC(5,0),
	MAX_WIDTH NUMERIC(5,0),	
	TRANSFORMATION NUMERIC(5,0),
	ORGANIZATION_ID nvarchar (36) DEFAULT '00000000-0000-0000-0000-000000000000'
) ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.IMG_CACHE
  	ADD CONSTRAINT PK_IMG_CACHE_ID PRIMARY KEY(IMG_CACHE_ID);  

ALTER TABLE HOMEPAGE.IMG_CACHE ADD CONSTRAINT FK_IMG_CACHE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE UNIQUE INDEX IMG_CACHE_FILE_UNQ
	ON HOMEPAGE.IMG_CACHE (FILE_PATH);

	
-- 94134: Indexes to support strict MT for private views of the Activity Streams

--  [start indexes] NR_AGGREGATED_READERS
DROP  INDEX AGGREGATED_READERS_SRC_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
DROP  INDEX RESPONSES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
DROP  INDEX PROFILES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
DROP  INDEX COMM_READERS_SRC_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
DROP  INDEX ACTIVITIES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
DROP  INDEX BLOGS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
DROP  INDEX BOOKMARKS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
DROP  INDEX FILES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
DROP  INDEX FORUMS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
DROP  INDEX WIKIS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
DROP  INDEX TAGS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX STATUS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX EXTERNAL_READERS_SRC_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX ACTIONABLE_READERS_SRC_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
DROP  INDEX DISCOVERY_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX PROFILES_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX NOTIFICA_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP  INDEX NOT_REC_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
DROP  INDEX SAVED_READERS_SRC_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
DROP  INDEX TOPICS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
DROP  INDEX MENTIONS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_MENTIONS_READERS;
GO

--  [end indexes] NR_MENTIONS_READERS


--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX AGGREGATED_READERS_SRC_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX RESPONSES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX PROFILES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX COMM_READERS_SRC_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX ACTIVITIES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX BLOGS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX BOOKMARKS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX FILES_READERS_SRC_IX 
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX FORUMS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX WIKIS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX TAGS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX STATUS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX EXTERNAL_READERS_SRC_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX ACTIONABLE_READERS_SRC_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX DISCOVERY_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE); 
GO

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX PROFILES_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX NOTIFICA_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX NOT_REC_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX SAVED_READERS_SRC_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX TOPICS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
CREATE  INDEX MENTIONS_READERS_SRC_IX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (READER_ID, ORGANIZATION_ID,  USE_IN_ROLLUP,  IS_VISIBLE, IS_BROADCAST,  CREATION_DATE DESC,  ROLLUP_ENTRY_ID,  SOURCE_TYPE, STORY_ID); 
GO

--  [end indexes] NR_MENTIONS_READERS

	
---------------------------------------------------------------------------------
------------------------ END   NEWS FIXUP 456 -------------------------------------
---------------------------------------------------------------------------------
