-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

ALTER TABLE HOMEPAGE.NR_NEWS_RECORDS
    ALTER COLUMN CONTAINER_ID 
    nvarchar(256);

ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT UNIQUE_RES;
DROP INDEX NR_RESOURCE_TYPE_CONT ON HOMEPAGE.NR_RESOURCE;

ALTER TABLE HOMEPAGE.NR_RESOURCE
    ALTER COLUMN CONTAINER_ID 
    nvarchar(256) NOT NULL;

ALTER TABLE HOMEPAGE.NR_RESOURCE
	ADD CONSTRAINT UNIQUE_RES UNIQUE (CONTAINER_ID, RESOURCE_TYPE);

CREATE INDEX NR_RESOURCE_TYPE_CONT
    ON HOMEPAGE.NR_RESOURCE (RESOURCE_TYPE, CONTAINER_ID);

-- NEWS REPOSITORY
{SQL_GRANT_START} HOMEPAGE.NR_SOURCE {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_SUBSCRIPTION {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_RECORDS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_TEMPLATE {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMGR {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMPR {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_SCHEDULER_TASK {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_SCHEDULER_TREG {SQL_GRANT_STOP}
GO


{SQL_GRANT_START} HOMEPAGE.NR_CATEGORY_TYPE {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_SAVED {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_DISCOVERY {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_NETWORK {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_COMMENT {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_CONTENT {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NEWS_COMMENT_CONTENT {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.NR_RESOURCE_TYPE  {SQL_GRANT_STOP}
GO	
{SQL_GRANT_START} HOMEPAGE.NR_RESOURCE  {SQL_GRANT_STOP}  
GO
{SQL_GRANT_START} HOMEPAGE.NR_FOLLOWS  {SQL_GRANT_STOP}	
GO
{SQL_GRANT_START} HOMEPAGE.NR_COMM_FOLLOW  {SQL_GRANT_STOP}	  
GO
{SQL_GRANT_START} HOMEPAGE.NR_ORGPERSON_FOLLOW  {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_STORIES  {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_FOLLOWED_STORIES  {SQL_GRANT_STOP}    
GO
{SQL_GRANT_START} HOMEPAGE.NR_COMM_STORIES  {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_ORGPERSON_STORIES  {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_STORIES_CONTENT  {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.NR_NETWORK  {SQL_GRANT_STOP}
GO	

{SQL_GRANT_START} HOMEPAGE.EMD_FREQUENCY_TYPE {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.EMD_RESOURCE_PREF {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.EMD_TRANCHE {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.EMD_TRANCHE_INFO {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.EMD_EMAIL_PREFS {SQL_GRANT_STOP}
GO    

	   