-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}




---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 103 -----------------------------------
---------------------------------------------------------------------------------

-- 68544: Adding to AS table an unique column where the timestamp is auto generated 
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST
	ADD CONSTRAINT NR_AS_SEEDLIST_UPDATE_DATE_DEFAULT DEFAULT (getdate()) FOR UPDATE_DATE;
GO	
	
--68754: expensive comments query, tablescan on BOARD_COMMENTS
CREATE INDEX SEEDLIST_BRD_IDX 
	ON HOMEPAGE.BOARD_ENTRIES (SL_UPDATE_DATE ASC, ENTRY_ID);


ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT 
	ALTER COLUMN ACTIVITY_META_DATA NVARCHAR(MAX);

GO

ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT 
	ALTER COLUMN ITEM_CONTENT NVARCHAR(MAX);

GO

ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT 
	ALTER COLUMN ITEM_CORRELATION_CONTENT NVARCHAR(MAX);

GO

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
	ALTER COLUMN DOMAIN_AFFINITY NVARCHAR(MAX);

GO

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ALTER COLUMN FULL_OBJECT_META_DATA NVARCHAR(MAX);

GO

ALTER TABLE HOMEPAGE.NR_AS_COLLECTION_CONFIG 
	ALTER COLUMN XML_DATA NVARCHAR(MAX);

GO

ALTER TABLE HOMEPAGE.NR_AS_CRAWLER_STATUS 
	ALTER COLUMN XML_DATA  NVARCHAR(MAX);

GO

------------

-- 67826
DROP INDEX NR_STORIES_ER_UUID ON HOMEPAGE.NR_STORIES;
GO

CREATE INDEX  NR_STORIES_ER_UUID 
	ON HOMEPAGE.NR_STORIES (EVENT_RECORD_UUID, STORY_ID);
GO

-- 68050: Discovery view for communities is very slow. Index needed
CREATE INDEX DISCOVERY_VIEW_COM 
	ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_STORY_COMM, USE_IN_ROLLUP);
GO

--68097: Remove WIDGET_ID column from BOARD table in next fixup
ALTER TABLE HOMEPAGE.BOARD DROP COLUMN WIDGET_ID;
GO

--59735: Exception in the logs on News startup in SourceTypeSyncServiceImpl
UPDATE HOMEPAGE.NR_SOURCE_TYPE 	SET  	IMAGE_URL = '${connections}/resources/web/com.ibm.lconn.core.styles/images/iconCommunities16.png',
										IMAGE_URL_SSL = '${connections}/resources/web/com.ibm.lconn.core.styles/images/iconCommunities16.png'
								WHERE 	SOURCE = 'communities';
GO

--68088: [fixup 103] Add 2 columns in BOARD_ENTRIES and BOARD_COMMENTS
--57636: Issue with hashtags keeping the capitals characters when added
--TAGS_LOWER columns in BOARD_ENTRIES and BOARD_COMMENTS
ALTER TABLE HOMEPAGE.BOARD_ENTRIES
	ADD HTML_CONTENT 	NVARCHAR(MAX);

GO
	
ALTER TABLE HOMEPAGE.BOARD_COMMENTS
	ADD HTML_CONTENT 	NVARCHAR(MAX);


GO

-------------------------------------------------------------------------------------------------------------
-- Drop 2 indexes: AUT_IX, RLL_IX; Create a new index
-------------------------------------------------------------------------------------------------------------






--  [start indexes] NR_AGGREGATED_READERS
DROP  INDEX AGGREGATED_READERS_AUT_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP  INDEX AGGREGATED_READERS_RLL_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

--  [end indexes] NR_AGGREGATED_READERS






--  [start indexes] NR_RESPONSES_READERS
DROP  INDEX RESPONSES_READERS_AUT_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP  INDEX RESPONSES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS;
GO

--  [end indexes] NR_RESPONSES_READERS






--  [start indexes] NR_PROFILES_READERS
DROP  INDEX PROFILES_READERS_AUT_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP  INDEX PROFILES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS;
GO

--  [end indexes] NR_PROFILES_READERS






--  [start indexes] NR_COMMUNITIES_READERS
DROP  INDEX COMM_READERS_AUT_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP  INDEX COMM_READERS_RLL_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

--  [end indexes] NR_COMMUNITIES_READERS






--  [start indexes] NR_ACTIVITIES_READERS
DROP  INDEX ACTIVITIES_READERS_AUT_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP  INDEX ACTIVITIES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

--  [end indexes] NR_ACTIVITIES_READERS






--  [start indexes] NR_BLOGS_READERS
DROP  INDEX BLOGS_READERS_AUT_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP  INDEX BLOGS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS;
GO

--  [end indexes] NR_BLOGS_READERS






--  [start indexes] NR_BOOKMARKS_READERS
DROP  INDEX BOOKMARKS_READERS_AUT_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP  INDEX BOOKMARKS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

--  [end indexes] NR_BOOKMARKS_READERS






--  [start indexes] NR_FILES_READERS
DROP  INDEX FILES_READERS_AUT_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

DROP  INDEX FILES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_FILES_READERS;
GO

--  [end indexes] NR_FILES_READERS






--  [start indexes] NR_FORUMS_READERS
DROP  INDEX FORUMS_READERS_AUT_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP  INDEX FORUMS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS;
GO

--  [end indexes] NR_FORUMS_READERS






--  [start indexes] NR_WIKIS_READERS
DROP  INDEX WIKIS_READERS_AUT_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP  INDEX WIKIS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS;
GO

--  [end indexes] NR_WIKIS_READERS






--  [start indexes] NR_TAGS_READERS
DROP  INDEX TAGS_READERS_AUT_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP  INDEX TAGS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_TAGS_READERS;
GO

--  [end indexes] NR_TAGS_READERS






--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX STATUS_READERS_AUT_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP  INDEX STATUS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

--  [end indexes] NR_STATUS_UPDATE_READERS






--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX EXTERNAL_READERS_AUT_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP  INDEX EXTERNAL_READERS_RLL_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

--  [end indexes] NR_EXTERNAL_READERS






--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX ACTIONABLE_READERS_AUT_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP  INDEX ACTIONABLE_READERS_RLL_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

--  [end indexes] NR_ACTIONABLE_READERS






--  [start indexes] NR_DISCOVERY_VIEW
DROP  INDEX DISCOVERY_VIEW_AUT_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

--  [end indexes] NR_DISCOVERY_VIEW






--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX PROFILES_VIEW_AUT_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP  INDEX PROFILES_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW;
GO

--  [end indexes] NR_PROFILES_VIEW






--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX NOTIFICA_READERS_AUT_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP  INDEX NOTIFICA_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS






--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP  INDEX NOT_REC_READERS_AUT_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP  INDEX NOT_REC_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS






--  [start indexes] NR_SAVED_READERS
DROP  INDEX SAVED_READERS_AUT_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP  INDEX SAVED_READERS_RLL_IX 
 	ON HOMEPAGE.NR_SAVED_READERS;
GO

--  [end indexes] NR_SAVED_READERS






--  [start indexes] NR_TOPICS_READERS
DROP  INDEX TOPICS_READERS_AUT_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP  INDEX TOPICS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS;
GO

--  [end indexes] NR_TOPICS_READERS







--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX AGGREGATED_READERS_RLL_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_AGGREGATED_READERS





--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX RESPONSES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_RESPONSES_READERS





--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX PROFILES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_PROFILES_READERS





--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX COMM_READERS_RLL_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_COMMUNITIES_READERS





--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX ACTIVITIES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_ACTIVITIES_READERS





--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX BLOGS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_BLOGS_READERS





--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX BOOKMARKS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_BOOKMARKS_READERS





--  [start indexes] NR_FILES_READERS
CREATE  INDEX FILES_READERS_RLL_IX 
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_FILES_READERS





--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX FORUMS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_FORUMS_READERS





--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX WIKIS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_WIKIS_READERS





--  [start indexes] NR_TAGS_READERS
CREATE  INDEX TAGS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_TAGS_READERS





--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX STATUS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_STATUS_UPDATE_READERS





--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX EXTERNAL_READERS_RLL_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_EXTERNAL_READERS





--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX ACTIONABLE_READERS_RLL_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_ACTIONABLE_READERS





--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX DISCOVERY_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_DISCOVERY_VIEW





--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX PROFILES_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_PROFILES_VIEW





--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX NOTIFICA_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS





--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX NOT_REC_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS





--  [start indexes] NR_SAVED_READERS
CREATE  INDEX SAVED_READERS_RLL_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_SAVED_READERS





--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX TOPICS_READERS_RLL_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
GO

--  [end indexes] NR_TOPICS_READERS



---------------------------------------------------------------------------------
------------------------ END NEWS FIXUP 103 -------------------------------------
---------------------------------------------------------------------------------
 

  
  
  
