-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-----------------------------------------------------------------------------------------------
-- START [1\2] BUG: During fixup84.sql we lose data. We need to fix 84 as there is no way to recover the data after
-----------------------------------------------------------------------------------------------

-- Dropping the constraints
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT 	DROP CONSTRAINT FK_ENTRY_ID_ACT;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG 	DROP CONSTRAINT FK_ENTRY_ID_BLG;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM 	DROP CONSTRAINT FK_ENTRY_ID_COM;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK 	DROP CONSTRAINT FK_ENTRY_ID_WIK;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF 	DROP CONSTRAINT FK_ENTRY_ID_PRF;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP 		DROP CONSTRAINT FK_ENTRY_ID_HP;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR 	DROP CONSTRAINT FK_ENTRY_ID_DGR;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE 	DROP CONSTRAINT FK_ENTRY_ID_FILE;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM 	DROP CONSTRAINT FK_ENTRY_ID_FRM;

GO

UPDATE HOMEPAGE.NR_SRC_STORIES_ACT SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

UPDATE HOMEPAGE.NR_SRC_STORIES_BLG SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

UPDATE HOMEPAGE.NR_SRC_STORIES_COM SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

UPDATE HOMEPAGE.NR_SRC_STORIES_WIK SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

UPDATE HOMEPAGE.NR_SRC_STORIES_PRF SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

UPDATE HOMEPAGE.NR_SRC_STORIES_HP SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

UPDATE HOMEPAGE.NR_SRC_STORIES_DGR SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

UPDATE HOMEPAGE.NR_SRC_STORIES_FILE SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

UPDATE HOMEPAGE.NR_SRC_STORIES_FRM SET ENTRY_ID = ITEM_ID WHERE ITEM_ID IS NOT NULL;
GO

-----------------------------------------------------------------------------------------------
-- END [1\2] BUG: During fixup84.sql we lose data. We need to fix 84 as there is no way to recover the data after
-----------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
-- STARTING DATA MIGRATION FROM THE NR_STORIES TABLE TO THE NR_ENTRIES TABLE
-----------------------------------------------------------------------------------------------
-- 1 NR_ENTRIES_ACT
ALTER TABLE HOMEPAGE.NR_ENTRIES_ACT ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_ACT (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_ACT.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_ACT.SOURCE,
				NR_SRC_STORIES_ACT.SOURCE_TYPE,
				NR_SRC_STORIES_ACT.CONTAINER_ID,
				NR_SRC_STORIES_ACT.CONTAINER_NAME,
				NR_SRC_STORIES_ACT.CONTAINER_URL,
				NR_SRC_STORIES_ACT.ITEM_ID,
				NR_SRC_STORIES_ACT.ITEM_NAME,
				NR_SRC_STORIES_ACT.ITEM_URL,			
				NR_SRC_STORIES_ACT.CREATION_DATE,
				NR_SRC_STORIES_ACT.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_ACT.TAGS,
				NR_SRC_STORIES_ACT.N_COMMENTS,
				NR_SRC_STORIES_ACT.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_ACT.BRIEF_DESC,
				NR_SRC_STORIES_ACT.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_ACT NR_SRC_STORIES_ACT,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_ACT
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_ACT.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_ACT
								);
GO


-- 2 NR_ENTRIES_BLG
ALTER TABLE HOMEPAGE.NR_ENTRIES_BLG ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_BLG (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_BLG.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_BLG.SOURCE,
				NR_SRC_STORIES_BLG.SOURCE_TYPE,
				NR_SRC_STORIES_BLG.CONTAINER_ID,
				NR_SRC_STORIES_BLG.CONTAINER_NAME,
				NR_SRC_STORIES_BLG.CONTAINER_URL,
				NR_SRC_STORIES_BLG.ITEM_ID,
				NR_SRC_STORIES_BLG.ITEM_NAME,
				NR_SRC_STORIES_BLG.ITEM_URL,			
				NR_SRC_STORIES_BLG.CREATION_DATE,
				NR_SRC_STORIES_BLG.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_BLG.TAGS,
				NR_SRC_STORIES_BLG.N_COMMENTS,
				NR_SRC_STORIES_BLG.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_BLG.BRIEF_DESC,
				NR_SRC_STORIES_BLG.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_BLG NR_SRC_STORIES_BLG,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_BLG
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_BLG.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_BLG
								);
GO

-- 3 HOMEPAGE.NR_ENTRIES_COM
ALTER TABLE HOMEPAGE.NR_ENTRIES_COM ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_COM (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_COM.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_COM.SOURCE,
				NR_SRC_STORIES_COM.SOURCE_TYPE,
				NR_SRC_STORIES_COM.CONTAINER_ID,
				NR_SRC_STORIES_COM.CONTAINER_NAME,
				NR_SRC_STORIES_COM.CONTAINER_URL,
				NR_SRC_STORIES_COM.ITEM_ID,
				NR_SRC_STORIES_COM.ITEM_NAME,
				NR_SRC_STORIES_COM.ITEM_URL,			
				NR_SRC_STORIES_COM.CREATION_DATE,
				NR_SRC_STORIES_COM.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_COM.TAGS,
				NR_SRC_STORIES_COM.N_COMMENTS,
				NR_SRC_STORIES_COM.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_COM.BRIEF_DESC,
				NR_SRC_STORIES_COM.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_COM NR_SRC_STORIES_COM,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_COM
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_COM.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_COM
								);
GO

-- 4 NR_ENTRIES_WIK
ALTER TABLE HOMEPAGE.NR_ENTRIES_WIK ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_WIK (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_WIK.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_WIK.SOURCE,
				NR_SRC_STORIES_WIK.SOURCE_TYPE,
				NR_SRC_STORIES_WIK.CONTAINER_ID,
				NR_SRC_STORIES_WIK.CONTAINER_NAME,
				NR_SRC_STORIES_WIK.CONTAINER_URL,
				NR_SRC_STORIES_WIK.ITEM_ID,
				NR_SRC_STORIES_WIK.ITEM_NAME,
				NR_SRC_STORIES_WIK.ITEM_URL,			
				NR_SRC_STORIES_WIK.CREATION_DATE,
				NR_SRC_STORIES_WIK.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_WIK.TAGS,
				NR_SRC_STORIES_WIK.N_COMMENTS,
				NR_SRC_STORIES_WIK.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_WIK.BRIEF_DESC,
				NR_SRC_STORIES_WIK.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_WIK NR_SRC_STORIES_WIK,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_WIK
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_WIK.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_WIK
								);
GO

-- 5 NR_ENTRIES_PRF
ALTER TABLE HOMEPAGE.NR_ENTRIES_PRF ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_PRF (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_PRF.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_PRF.SOURCE,
				NR_SRC_STORIES_PRF.SOURCE_TYPE,
				NR_SRC_STORIES_PRF.CONTAINER_ID,
				NR_SRC_STORIES_PRF.CONTAINER_NAME,
				NR_SRC_STORIES_PRF.CONTAINER_URL,
				NR_SRC_STORIES_PRF.ITEM_ID,
				NR_SRC_STORIES_PRF.ITEM_NAME,
				NR_SRC_STORIES_PRF.ITEM_URL,			
				NR_SRC_STORIES_PRF.CREATION_DATE,
				NR_SRC_STORIES_PRF.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_PRF.TAGS,
				NR_SRC_STORIES_PRF.N_COMMENTS,
				NR_SRC_STORIES_PRF.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_PRF.BRIEF_DESC,
				NR_SRC_STORIES_PRF.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_PRF NR_SRC_STORIES_PRF,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_PRF
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_PRF.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_PRF
								);
GO

-- 6 NR_ENTRIES_HP
ALTER TABLE HOMEPAGE.NR_ENTRIES_HP ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_HP (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_HP.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_HP.SOURCE,
				NR_SRC_STORIES_HP.SOURCE_TYPE,
				NR_SRC_STORIES_HP.CONTAINER_ID,
				NR_SRC_STORIES_HP.CONTAINER_NAME,
				NR_SRC_STORIES_HP.CONTAINER_URL,
				NR_SRC_STORIES_HP.ITEM_ID,
				NR_SRC_STORIES_HP.ITEM_NAME,
				NR_SRC_STORIES_HP.ITEM_URL,			
				NR_SRC_STORIES_HP.CREATION_DATE,
				NR_SRC_STORIES_HP.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_HP.TAGS,
				NR_SRC_STORIES_HP.N_COMMENTS,
				NR_SRC_STORIES_HP.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_HP.BRIEF_DESC,
				NR_SRC_STORIES_HP.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_HP NR_SRC_STORIES_HP,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_HP
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_HP.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_HP
								);
GO

-- 7 NR_ENTRIES_DGR
ALTER TABLE HOMEPAGE.NR_ENTRIES_DGR ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_DGR (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_DGR.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_DGR.SOURCE,
				NR_SRC_STORIES_DGR.SOURCE_TYPE,
				NR_SRC_STORIES_DGR.CONTAINER_ID,
				NR_SRC_STORIES_DGR.CONTAINER_NAME,
				NR_SRC_STORIES_DGR.CONTAINER_URL,
				NR_SRC_STORIES_DGR.ITEM_ID,
				NR_SRC_STORIES_DGR.ITEM_NAME,
				NR_SRC_STORIES_DGR.ITEM_URL,			
				NR_SRC_STORIES_DGR.CREATION_DATE,
				NR_SRC_STORIES_DGR.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_DGR.TAGS,
				NR_SRC_STORIES_DGR.N_COMMENTS,
				NR_SRC_STORIES_DGR.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_DGR.BRIEF_DESC,
				NR_SRC_STORIES_DGR.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_DGR NR_SRC_STORIES_DGR,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_DGR
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_DGR.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_DGR
								);
GO

-- 8 NR_ENTRIES_FILE
ALTER TABLE HOMEPAGE.NR_ENTRIES_FILE ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_FILE (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_FILE.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_FILE.SOURCE,
				NR_SRC_STORIES_FILE.SOURCE_TYPE,
				NR_SRC_STORIES_FILE.CONTAINER_ID,
				NR_SRC_STORIES_FILE.CONTAINER_NAME,
				NR_SRC_STORIES_FILE.CONTAINER_URL,
				NR_SRC_STORIES_FILE.ITEM_ID,
				NR_SRC_STORIES_FILE.ITEM_NAME,
				NR_SRC_STORIES_FILE.ITEM_URL,			
				NR_SRC_STORIES_FILE.CREATION_DATE,
				NR_SRC_STORIES_FILE.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_FILE.TAGS,
				NR_SRC_STORIES_FILE.N_COMMENTS,
				NR_SRC_STORIES_FILE.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_FILE.BRIEF_DESC,
				NR_SRC_STORIES_FILE.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_FILE NR_SRC_STORIES_FILE,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_FILE
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_FILE.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_FILE
								);
GO

-- 9 NR_ENTRIES_FRM
ALTER TABLE HOMEPAGE.NR_ENTRIES_FRM ADD ITEM_ATOM_URL nvarchar(2048);
GO

INSERT INTO HOMEPAGE.NR_ENTRIES_FRM (
	ENTRY_ID,
	SOURCE,
	SOURCE_TYPE,
	CONTAINER_ID,
	CONTAINER_NAME,
	CONTAINER_URL,
	ITEM_ID,
	ITEM_NAME,
	ITEM_URL,
	CREATION_DATE,
	UPDATE_DATE,
	TAGS,
	N_COMMENTS,
	N_RECCOMANDATIONS,
	N_ATTACHMENTS,
	BRIEF_DESC,
	ITEM_ATOM_URL
)
	SELECT *
	FROM (
		SELECT 	NR_SRC_STORIES_FRM.ITEM_ID ENTRY_ID,
				NR_SRC_STORIES_FRM.SOURCE,
				NR_SRC_STORIES_FRM.SOURCE_TYPE,
				NR_SRC_STORIES_FRM.CONTAINER_ID,
				NR_SRC_STORIES_FRM.CONTAINER_NAME,
				NR_SRC_STORIES_FRM.CONTAINER_URL,
				NR_SRC_STORIES_FRM.ITEM_ID,
				NR_SRC_STORIES_FRM.ITEM_NAME,
				NR_SRC_STORIES_FRM.ITEM_URL,			
				NR_SRC_STORIES_FRM.CREATION_DATE,
				NR_SRC_STORIES_FRM.CREATION_DATE UPDATE_DATE,
				NR_SRC_STORIES_FRM.TAGS,
				NR_SRC_STORIES_FRM.N_COMMENTS,
				NR_SRC_STORIES_FRM.N_RECOMMANDATIONS,
				0 N_ATTACHMENTS, -- N_ATTACHMENTS
				NR_SRC_STORIES_FRM.BRIEF_DESC,
				NR_SRC_STORIES_FRM.ITEM_ATOM_URL
		FROM 	HOMEPAGE.NR_SRC_STORIES_FRM NR_SRC_STORIES_FRM,
			(
				SELECT 	ITEM_ID, MAX(STORY_ID) STORY_ID
				FROM 	HOMEPAGE.NR_SRC_STORIES_FRM
				WHERE 	ENTRY_ID IS NOT NULL
				GROUP	BY ITEM_ID
			) TEMP
		WHERE NR_SRC_STORIES_FRM.STORY_ID = TEMP.STORY_ID
		) TEMP_STORIES 
	WHERE TEMP_STORIES.ENTRY_ID NOT IN (	
									SELECT 	ENTRY_ID
									FROM 	HOMEPAGE.NR_ENTRIES_FRM
								);
GO

-----------------------------------------------------------------------------------------------
-- START [1\2] BUG: During fixup84.sql we lose data. We need to fix 84 as there is no way to recover the data after
-----------------------------------------------------------------------------------------------
-- Putting back the constraints
-- 1
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT
  	ADD CONSTRAINT FK_ENTRY_ID_ACT FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_ACT (ENTRY_ID);

GO	

-- 2
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG
  	ADD CONSTRAINT FK_ENTRY_ID_BLG FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_BLG (ENTRY_ID);

GO

-- 3
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM
  	ADD CONSTRAINT FK_ENTRY_ID_COM FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_COM (ENTRY_ID);

GO

-- 4
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK
  	ADD CONSTRAINT FK_ENTRY_ID_WIK FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_WIK (ENTRY_ID); 

GO

-- 5
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF
  	ADD CONSTRAINT FK_ENTRY_ID_PRF FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_PRF (ENTRY_ID); 

GO

-- 6
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP
  	ADD CONSTRAINT FK_ENTRY_ID_HP FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_HP (ENTRY_ID);

GO

-- 7
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR
  	ADD CONSTRAINT FK_ENTRY_ID_DGR FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_DGR (ENTRY_ID);

GO

-- 8
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE
  	ADD CONSTRAINT FK_ENTRY_ID_FILE FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_FILE (ENTRY_ID);

GO

-- 9
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM
  	ADD CONSTRAINT FK_ENTRY_ID_FRM FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_FRM (ENTRY_ID);

GO
-----------------------------------------------------------------------------------------------
-- END [1\2] BUG: During fixup84.sql we lose data. We need to fix 84 as there is no way to recover the data after
-----------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------
-- END DATA MIGRATION
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------

-- DROPPING VIEW NR_ENTRIES 
DROP VIEW HOMEPAGE.NR_ENTRIES;
GO

--  DROPPING VIEW NR_STORIES
DROP VIEW HOMEPAGE.NR_STORIES;
GO

-----------------------------------------------------------------------
-- REFACTORING STORIES TABLE
-----------------------------------------------------------------------
-- DROPPING OLD COLUNNS FOR STORY TABLE: ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS
-- 1 NR_SRC_STORIES_ACT
DROP INDEX SRC_ACT_STORIES_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_ACT
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_ACT') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_ACT') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--2 NR_SRC_STORIES_BLG
DROP INDEX SRC_BLG_STORIES_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_BLG
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_BLG') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_BLG') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--3 NR_SRC_STORIES_COM
DROP INDEX SRC_COM_STORIES_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_COM
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_COM') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_COM') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--4 NR_SRC_STORIES_WIK
DROP INDEX SRC_WIK_STORIES_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_WIK
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_WIK') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_WIK') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--5 NR_SRC_STORIES_PRF
DROP INDEX SRC_PRF_STORIES_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_PRF
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_PRF') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_PRF') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--6 NR_SRC_STORIES_HP
DROP INDEX SRC_HP_STORIES_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_HP
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_HP') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_HP') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--7 NR_SRC_STORIES_DGR
DROP INDEX SRC_DGR_STORIES_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_DGR
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_DGR') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_DGR') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--8 NR_SRC_STORIES_FILE
DROP INDEX SRC_FILE_STORIES_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_FILE
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_FILE') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_FILE') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--9 NR_SRC_STORIES_FRM
DROP INDEX SRC_FRM_ITEM_ID ON HOMEPAGE.NR_SRC_STORIES_FRM
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_FRM') and name like '%DF__NR_SRC_ST__N_COM%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

DECLARE @CONST_NAME as nvarchar(128), @DROP_STMT as nvarchar(2000)
SET @CONST_NAME = (select name from sys.default_constraints where parent_object_id=OBJECT_ID('HOMEPAGE.NR_SRC_STORIES_FRM') and name like '%DF__NR_SRC_ST__N_REC%')
SET @DROP_STMT = N'ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM DROP CONSTRAINT ' + @CONST_NAME
EXEC (@DROP_STMT)
GO

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM DROP COLUMN ITEM_ID, ITEM_NAME, ITEM_URL, N_COMMENTS, N_RECOMMANDATIONS;
GO

--------------------------------------------
--------------------------------------------
--------------------------------------------
--------------------------------------------
-- EMD FIX - ADDING UNIQUE CONSTRAINT
--------------------------------------------
--------------------------------------------
--------------------------------------------
--------------------------------------------
--------------------------------------------

---------------------------------------------------------------------------------------------------------------------------
-- TO REMOVE ALL DUPLICATED RECORDS - WE NEED TO EXECUTE THIS QUERY N_TIME IN A PARTITIONED WAY TO DON'T GET FULL THE LOG.
-- THIS IS THE NOT PARTITIONED QUERIES
---------------------------------------------------------------------------------------------------------------------------
-- Sanitize first the table:
--[old query]
--DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID NOT IN (
--	SELECT TEMP.RESOURCE_PREF_ID
--	FROM (
--		SELECT 	MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE  
--		FROM  	HOMEPAGE.EMD_RESOURCE_PREF
--		GROUP BY 	PERSON_ID, RESOURCE_TYPE
--	)  TEMP
--);
--[old query]

-- delete using 0
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '0..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '0..f'			
);

GO

-- delete using 1
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '1..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '1..f'			
);

GO

-- delete using 2
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '2..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '2..f'			
);

GO

-- delete using 3
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '3..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '3..f'			
);

GO

-- delete using 4
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '4..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '4..f'			
);

GO

-- delete using 5
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '5..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '5..f'			
);

GO

-- delete using 6
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '6..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '6..f'			
);

GO

-- delete using 7
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '7..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '7..f'			
);

GO

-- delete using 8
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '8..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '8..f'			
);

GO

-- delete using 9
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < '9..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < '9..f'			
);

GO

-- delete using a
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < 'a..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < 'a..f'			
);

GO

-- delete using b
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < 'b..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < 'b..f'			
);

GO

-- delete using c
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < 'c..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < 'c..f'			
);

GO

-- delete using d
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < 'd..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < 'd..f'			
);

GO

-- delete using e
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		WHERE RESOURCE_PREF_ID < 'e..f'
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE AND
			EMD_RESOURCE_PREF.RESOURCE_PREF_ID < 'e..f'			
);

GO

-- The last delete all
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE RESOURCE_PREF_ID IN (
	select EMD_RESOURCE_PREF.RESOURCE_PREF_ID
	from (
		SELECT MAX(RESOURCE_PREF_ID) RESOURCE_PREF_ID, PERSON_ID, RESOURCE_TYPE 
		FROM HOMEPAGE.EMD_RESOURCE_PREF
		GROUP BY 	PERSON_ID, RESOURCE_TYPE
		) T,
		 HOMEPAGE.EMD_RESOURCE_PREF EMD_RESOURCE_PREF
	where 	EMD_RESOURCE_PREF.RESOURCE_PREF_ID < T.RESOURCE_PREF_ID AND 
			EMD_RESOURCE_PREF.PERSON_ID = T.PERSON_ID AND
			EMD_RESOURCE_PREF.RESOURCE_TYPE = T.RESOURCE_TYPE		
);
GO

-- Add unique constraint:
CREATE UNIQUE INDEX EMD_RESOURCE_PREF_UNQ
	ON HOMEPAGE.EMD_RESOURCE_PREF (PERSON_ID, RESOURCE_TYPE);

GO

---------------------------------------------------------------------------------
-- ADDING QUARANTINE TABLE
---------------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.DELETED_STORIES_QUEUE (
	STORY_ID nvarchar(36) NOT NULL,
	SOURCE 	nvarchar(36) NOT NULL, -- this is externalized
	SOURCE_TYPE NUMERIC(5,0) NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE 
  	ADD CONSTRAINT PK_QUARANTINE PRIMARY KEY(STORY_ID);
  	

GO