-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2015                                   
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}


-------------------------------------------------------
-- Add ORGANIZATION_ID to STR_RDR indexes
-------------------------------------------------------
DROP INDEX AGGREGATED_READERS_STR_RDR ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

CREATE UNIQUE INDEX AGGREGATED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, READER_ID, CONTAINER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO 

DROP INDEX STATUS_READERS_STR_RDR ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

CREATE UNIQUE INDEX STATUS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO 

DROP INDEX EXTERNAL_READERS_STR_RDR ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

CREATE UNIQUE INDEX EXTERNAL_READERS_STR_RDR 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO

DROP INDEX ACTIONABLE_READERS_STR_RDR ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

CREATE UNIQUE INDEX ACTIONABLE_READERS_STR_RDR 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO 

DROP INDEX PROFILES_VIEW_STR_RDR ON HOMEPAGE.NR_PROFILES_VIEW;
GO

CREATE UNIQUE INDEX PROFILES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO 

DROP INDEX NOTIFICA_READERS_STR_RDR ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

CREATE UNIQUE INDEX NOTIFICA_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO  

DROP INDEX NOT_REC_READERS_STR_RDR ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

CREATE  INDEX NOT_REC_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO 

DROP INDEX SAVED_READERS_STR_RDR ON HOMEPAGE.NR_SAVED_READERS;
GO

CREATE UNIQUE INDEX SAVED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO  

DROP INDEX TOPICS_READERS_STR_RDR ON HOMEPAGE.NR_TOPICS_READERS;
GO

CREATE UNIQUE INDEX TOPICS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO

DROP INDEX MENTIONS_READERS_STR_RDR ON HOMEPAGE.NR_MENTIONS_READERS;
GO

CREATE UNIQUE INDEX MENTIONS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_MENTIONS_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO

DROP INDEX COMMUNITIES_VIEW_STR_RDR ON HOMEPAGE.NR_COMMUNITIES_VIEW;
GO

CREATE UNIQUE INDEX COMMUNITIES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
GO 



-------------------------------------------------
-- SCEE: Add new table HOMEPAGE.L3T_EXT_POINTS
-------------------------------------------------
CREATE TABLE HOMEPAGE.L3T_EXT_POINTS (
		EXT_POINT_ID VARCHAR(36) NOT NULL,
		NAME VARCHAR(256) NOT NULL,
		SERVICE VARCHAR(128) NOT NULL,
		EXT_TYPE VARCHAR(128) NOT NULL,
		DESCRIPTION VARCHAR(512)
) ON [PRIMARY]
GO

ALTER TABLE HOMEPAGE.L3T_EXT_POINTS ADD CONSTRAINT PK_EXT_POINT_ID PRIMARY KEY (EXT_POINT_ID);
GO
