-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 107 -----------------------------------
---------------------------------------------------------------------------------

--73896: [Performance|Server] News DB disk I/O 100% busy when posting stories


DROP INDEX AGGREGATED_READERS_RDR_STR ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

DROP INDEX CL_AGGREGATED_READERS_IDX ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

CREATE  INDEX AGGREGATED_READERS_RDR_STR
ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, STORY_ID);
GO


DROP INDEX RESPONSES_READERS_RDR_STR ON HOMEPAGE.NR_RESPONSES_READERS;
GO

DROP INDEX CL_RESPONSES_READERS_IDX ON HOMEPAGE.NR_RESPONSES_READERS;
GO

CREATE  INDEX RESPONSES_READERS_RDR_STR
ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID);
GO

DROP INDEX PROFILES_READERS_RDR_STR ON HOMEPAGE.NR_PROFILES_READERS;
GO

DROP INDEX CL_PROFILES_READERS_IDX ON HOMEPAGE.NR_PROFILES_READERS;
GO

CREATE  INDEX PROFILES_READERS_RDR_STR
ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID);
GO

DROP INDEX COMM_READERS_RDR_STR ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

DROP INDEX CL_COMM_READERS_IDX ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

CREATE  INDEX COMM_READERS_RDR_STR
ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID);
GO

DROP INDEX ACTIVITIES_READERS_RDR_STR ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

DROP INDEX CL_ACTIVITIES_READERS_IDX ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

CREATE  INDEX ACTIVITIES_READERS_RDR_STR
ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID);
GO

DROP INDEX BLOGS_READERS_RDR_STR ON HOMEPAGE.NR_BLOGS_READERS;
GO

DROP INDEX CL_BLOGS_READERS_IDX ON HOMEPAGE.NR_BLOGS_READERS;
GO

CREATE  INDEX BLOGS_READERS_RDR_STR
ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID);
GO

DROP INDEX BOOKMARKS_READERS_RDR_STR ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

DROP INDEX CL_BOOKMARKS_READERS_IDX ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

CREATE  INDEX BOOKMARKS_READERS_RDR_STR
ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID);
GO

DROP INDEX FILES_READERS_RDR_STR ON HOMEPAGE.NR_FILES_READERS;
GO

DROP INDEX CL_FILES_READERS_IDX ON HOMEPAGE.NR_FILES_READERS;
GO

CREATE  INDEX FILES_READERS_RDR_STR
ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID);
GO

DROP INDEX FORUMS_READERS_RDR_STR ON HOMEPAGE.NR_FORUMS_READERS;
GO

DROP INDEX CL_FORUMS_READERS_IDX ON HOMEPAGE.NR_FORUMS_READERS;
GO

CREATE  INDEX FORUMS_READERS_RDR_STR
ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID);
GO

DROP INDEX WIKIS_READERS_RDR_STR ON HOMEPAGE.NR_WIKIS_READERS;
GO

DROP INDEX CL_WIKIS_READERS_IDX ON HOMEPAGE.NR_WIKIS_READERS;
GO

CREATE  INDEX WIKIS_READERS_RDR_STR
ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID);
GO

DROP INDEX TAGS_READERS_RDR_STR ON HOMEPAGE.NR_TAGS_READERS;
GO

DROP INDEX CL_TAGS_READERS_IDX ON HOMEPAGE.NR_TAGS_READERS;
GO

CREATE  INDEX TAGS_READERS_RDR_STR
ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID);
GO

DROP INDEX STATUS_READERS_RDR_STR ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

DROP INDEX CL_STATUS_READERS_IDX ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

CREATE  INDEX STATUS_READERS_RDR_STR
ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID);
GO

DROP INDEX EXTERNAL_READERS_RDR_STR ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

DROP INDEX CL_EXTERNAL_READERS_IDX ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

CREATE  INDEX EXTERNAL_READERS_RDR_STR
ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID);
GO

DROP INDEX ACTIONABLE_READERS_RDR_STR ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

DROP INDEX CL_ACTIONABLE_READERS_IDX ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

CREATE  INDEX ACTIONABLE_READERS_RDR_STR
ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, STORY_ID);
GO

DROP INDEX DISCOVERY_VIEW_RDR_STR ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP INDEX CL_DISCOVERY_READERS_IDX ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

CREATE  INDEX DISCOVERY_VIEW_RDR_STR
ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, STORY_ID);
GO

DROP INDEX PROFILES_VIEW_RDR_STR ON HOMEPAGE.NR_PROFILES_VIEW;
GO

DROP INDEX CL_PROFILESV_READERS_IDX ON HOMEPAGE.NR_PROFILES_VIEW;
GO

CREATE  INDEX PROFILES_VIEW_RDR_STR
ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, STORY_ID);
GO

DROP INDEX NOTIFICA_READERS_RDR_STR ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

DROP INDEX CL_NOTIFICA_READERS_IDX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

CREATE  INDEX NOTIFICA_READERS_RDR_STR
ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, STORY_ID);
GO

DROP INDEX NOT_REC_READERS_RDR_STR ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

DROP INDEX CL_REC_READERS_IDX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

CREATE  INDEX NOT_REC_READERS_RDR_STR
ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, STORY_ID);
GO

DROP INDEX SAVED_READERS_RDR_STR ON HOMEPAGE.NR_SAVED_READERS;
GO

DROP INDEX CL_SAVED_READERS_IDX ON HOMEPAGE.NR_SAVED_READERS;
GO

CREATE  INDEX SAVED_READERS_RDR_STR
ON HOMEPAGE.NR_SAVED_READERS (READER_ID, STORY_ID);
GO

DROP INDEX TOPICS_READERS_RDR_STR ON HOMEPAGE.NR_TOPICS_READERS;
GO

DROP INDEX CL_TOPICS_READERS_IDX ON HOMEPAGE.NR_TOPICS_READERS;
GO

CREATE  INDEX TOPICS_READERS_RDR_STR
ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, STORY_ID);
GO


------------------------------------------------------------------------------------------
-- 74177: [Performance|Server|DB2] Inefficient SQL/Index for NR_DISCOVERY_VIEW
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------


DROP  INDEX DISCOVERY_VIEW_SRC_IX ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_RLL_IX ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_RDR_STR ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_ROLLUP_IX ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

DROP  INDEX DISCOVERY_VIEW_RIR_IX ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO


CREATE  INDEX DISCOVERY_VIEW_SRC_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
GO

CREATE  INDEX DISCOVERY_VIEW_RLL_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_VISIBLE, USE_IN_ROLLUP); 
GO

CREATE  INDEX DISCOVERY_VIEW_ROLLUP_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_ENTRY_ID); 
GO

CREATE  INDEX DISCOVERY_VIEW_RIR_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);  
GO

------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------
------------------------ END NEWS FIXUP 107 -------------------------------------
---------------------------------------------------------------------------------
 

  
  
  
