-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2008, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

connect to HOMEPAGE;

----------------------------------------------------
-- 1) START ADDING INDEXES FOR HOMEPAGE TABLES
----------------------------------------------------
--CREATE INDEX HOMEPAGE.TAB_INST_UI_ID_IDX 
--	ON HOMEPAGE.HP_TAB_INST(UI_ID);	


--CREATE INDEX HOMEPAGE.HP_WIDGET_INST_TAB_INST_ID_IDX
--	ON HOMEPAGE.HP_WIDGET_INST(TAB_INST_ID);

----------------------------------------------------
-- END ADDING INDEXES FOR HOMEPAGE TABLES
----------------------------------------------------



-------------------------------------------------------------------
-- 2) START ADDING NEW TABLES FOR NEWS REPOSITORY AND EMAIL DIGEST
-------------------------------------------------------------------

-- NEW REPOSITORY
CREATE TABLE HOMEPAGE.NR_EVENT_RECORDS  (
	EVENT_RECORD_ID VARCHAR(36) NOT NULL,
	EVENT_RECORD_CONTENT BLOB (2097152),
	IS_ACL SMALLINT NOT NULL
)
IN NEWSTABSPACE;

-- EMAIL DIGEST
CREATE TABLE HOMEPAGE.EMD_RECIPIENTS (
	RECIPIENT_ID VARCHAR(36) NOT NULL,
	PERSON_ID VARCHAR(36) NOT NULL,
	FREQUENCY_UPDATE SMALLINT NOT NULL,
	LAST_SENT_UPDATE TIMESTAMP NOT NULL,
	MAIL_DOMAIN VARCHAR(256) NOT NULL,
	MAIL_ADDRESS  VARCHAR(256) NOT NULL
)
IN NEWSTABSPACE;

CREATE TABLE HOMEPAGE.EMD_JOBS  (
	JOB_ID VARCHAR(36) NOT NULL,
	JOB_FREQUENCY SMALLINT NOT NULL,
	NEXT_EXEC_TIME TIMESTAMP NOT NULL,
	DUE_DATE_EXEC_TIME TIMESTAMP,
	START_JOB TIMESTAMP,
	END_JOB TIMESTAMP,
	STATUS VARCHAR(36),
	N_PERSONS_TO_UPDATE INTEGER,
	AVG_EXEC_JOB INTEGER
)
IN NEWSTABSPACE;

CREATE TABLE HOMEPAGE.EMD_JOBS_STATS (
	STAT_ID VARCHAR(36) NOT NULL,
	JOB_ID VARCHAR(36) NOT NULL,
	START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    EXEC_TIME INTEGER,
    N_PERSONS_UPDATED INTEGER
)
IN NEWSTABSPACE;


-- NEWS REPOSITORY CONSTRAINTS
ALTER TABLE HOMEPAGE.NR_EVENT_RECORDS
    ADD CONSTRAINT "PK_EVENT_RECORD_ID" PRIMARY KEY("EVENT_RECORD_ID"); 

-- EMAIL DIGEST CONSTRAINTS
ALTER TABLE HOMEPAGE.EMD_RECIPIENTS
    ADD CONSTRAINT "PK_RECIPIENT_ID" PRIMARY KEY("RECIPIENT_ID");    

ALTER TABLE HOMEPAGE.EMD_JOBS
    ADD CONSTRAINT "PK_JOB_ID" PRIMARY KEY("JOB_ID");

ALTER TABLE HOMEPAGE.EMD_JOBS_STATS
    ADD CONSTRAINT "PK_STAT_ID" PRIMARY KEY("STAT_ID");

ALTER TABLE HOMEPAGE.EMD_RECIPIENTS
    ADD CONSTRAINT "FK_REC_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");
	
ALTER TABLE HOMEPAGE.EMD_JOBS_STATS
    ADD CONSTRAINT "FK_JOB_ID" FOREIGN KEY ("JOB_ID")
	REFERENCES HOMEPAGE.EMD_JOBS ("JOB_ID");

ALTER TABLE HOMEPAGE.EMD_JOBS
	ADD CONSTRAINT UNIQUE_JOB_FREQ UNIQUE("JOB_FREQUENCY");

------------------------------------------------------------------
-- END ADDING NEW TABLES FOR NEWS REPOSITORY AND EMAIL DIGIEST
------------------------------------------------------------------

-------------------------------------------------------------------
-- 3) START ADDING INDEXES FOR NEWS REPOSITORY AND EMAIL DIGIEST
-------------------------------------------------------------------

-- NEW REPOSITORY INDEXES
--CREATE INDEX HOMEPAGE.NR_NEWS_RECORDS_READER_IDX
--	ON HOMEPAGE.NR_NEWS_RECORDS(READER_ID);

--CREATE INDEX HOMEPAGE.NR_NEWS_RECORDS_ACTOR_IDX
--	ON HOMEPAGE.NR_NEWS_RECORDS(ACTOR_UUID);

--CREATE INDEX HOMEPAGE.NR_NEWS_RECORDS_SOURCE_IDX
--	ON HOMEPAGE.NR_NEWS_RECORDS(SOURCE);

--CREATE INDEX HOMEPAGE.NR_NEWS_RECORDS_CONTAINER_IDX
--	ON HOMEPAGE.NR_NEWS_RECORDS(CONTAINER_ID);
	
--CREATE INDEX HOMEPAGE.NR_NEWS_RECORDS_DATE_IDX
--	ON HOMEPAGE.NR_NEWS_RECORDS(CREATION_DATE DESC);

--CREATE INDEX HOMEPAGE.NR_NEWS_RECORDS_EVENT_IDX
--	ON HOMEPAGE.NR_NEWS_RECORDS(EVENT_RECORD_UUID);	
	
-- EMAIL DIGEST INDEXES
CREATE INDEX HOMEPAGE.EMD_RECIPIENTS_SENT_UPDATE_IDX
	ON HOMEPAGE.EMD_RECIPIENTS(LAST_SENT_UPDATE DESC);

CREATE INDEX HOMEPAGE.EMD_RECIPIENTS_MAIL_DOMAIN_IDX
	ON HOMEPAGE.EMD_RECIPIENTS(MAIL_DOMAIN DESC);
	
-------------------------------------------------------------------
-- END ADDING INDEXES FOR NEWS REPOSITORY AND EMAIL DIGIEST
-------------------------------------------------------------------

-------------------------------------------------------------------
-- 4) START ADDING SCHEDULER TABLES
-------------------------------------------------------------------

CREATE TABLE HOMEPAGE.NR_SCHEDULER_TASK (
	TASKID BIGINT NOT NULL,
	VERSION VARCHAR(5) NOT NULL,
	ROW_VERSION INTEGER NOT NULL,
	TASKTYPE INTEGER NOT NULL,
	TASKSUSPENDED SMALLINT NOT NULL,
	CANCELLED SMALLINT NOT NULL,
	NEXTFIRETIME BIGINT NOT NULL,
	STARTBYINTERVAL VARCHAR(254),
	STARTBYTIME BIGINT,
	VALIDFROMTIME BIGINT,
	VALIDTOTIME BIGINT,
	REPEATINTERVAL VARCHAR(254),
	MAXREPEATS INTEGER NOT NULL,
	REPEATSLEFT INTEGER NOT NULL,
	TASKINFO BLOB(102400) LOGGED NOT COMPACT,
	NAME VARCHAR(254) NOT NULL,
	AUTOPURGE INTEGER NOT NULL,
	FAILUREACTION INTEGER,
	MAXATTEMPTS INTEGER,
	QOS INTEGER,
	PARTITIONID INTEGER,
	OWNERTOKEN VARCHAR(200) NOT NULL,
	CREATETIME BIGINT NOT NULL
) 
IN NEWSTABSPACE;

ALTER TABLE HOMEPAGE.NR_SCHEDULER_TASK 
	ADD PRIMARY KEY (TASKID);

CREATE INDEX HOMEPAGE.NR_SCHEDULER_TASK_IDX1 
	ON HOMEPAGE.NR_SCHEDULER_TASK (TASKID, OWNERTOKEN);

CREATE INDEX HOMEPAGE.NR_SCHEDULER_TASK_IDX2 
	ON HOMEPAGE.NR_SCHEDULER_TASK (NEXTFIRETIME ASC, REPEATSLEFT, PARTITIONID) CLUSTER;

CREATE TABLE HOMEPAGE.NR_SCHEDULER_TREG (
	REGKEY VARCHAR(254) NOT NULL,
	REGVALUE VARCHAR(254) 
) 
IN NEWSTABSPACE;

ALTER TABLE HOMEPAGE.NR_SCHEDULER_TREG 
	ADD PRIMARY KEY (REGKEY);

CREATE TABLE HOMEPAGE.NR_SCHEDULER_LMGR (
	LEASENAME VARCHAR(254) NOT NULL,
	LEASEOWNER VARCHAR(254) NOT NULL,
	LEASE_EXPIRE_TIME  BIGINT,
	DISABLED VARCHAR(5)
)
IN NEWSTABSPACE;

ALTER TABLE HOMEPAGE.NR_SCHEDULER_LMGR 
	ADD PRIMARY KEY (LEASENAME);

CREATE TABLE HOMEPAGE.NR_SCHEDULER_LMPR (
	LEASENAME VARCHAR(254) NOT NULL,
	NAME VARCHAR(254) NOT NULL,
	VALUE VARCHAR(254) NOT NULL
)
IN NEWSTABSPACE;

CREATE INDEX HOMEPAGE.NR_SCHEDULER_LMPR_IDX1 
	ON HOMEPAGE.NR_SCHEDULER_LMPR (LEASENAME, NAME);
	
-------------------------------------------------------------------
-- END ADDING SCHEDULER TABLES
-------------------------------------------------------------------

-------------------------------------------------------------------
-- 5) START GRANT THE LCUSER
-------------------------------------------------------------------

-- News Repository
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_EVENT_RECORDS TO USER LCUSER;

-- Email digest
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.EMD_RECIPIENTS TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.EMD_JOBS TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.EMD_JOBS_STATS TO USER LCUSER;

-- Scheduler
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_SCHEDULER_TASK TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_SCHEDULER_TREG TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_SCHEDULER_LMGR TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_SCHEDULER_LMPR TO USER LCUSER;

-------------------------------------------------------------------
-- END GRANT THE LCUSER
-------------------------------------------------------------------


-- Fixing a minor dbComparator issue
ALTER TABLE HOMEPAGE.HOMEPAGE_SCHEMA
ALTER COLUMN RELEASEVER SET DEFAULT '';

-- Updating the schema version from 10 to 11
UPDATE  HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER = 11
WHERE   DBSCHEMAVER = 10;

COMMIT;

--------------------------------------
-- FLUSH
--------------------------------------
FLUSH PACKAGE CACHE DYNAMIC;

--------------------------------------
-- TERMINATE
--------------------------------------
connect reset;
terminate; 
