-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- CONSTRAINTS KEYS
CONNECT TO HOMEPAGE;


-- To remove all the records from a database before to start a db transfer
DELETE FROM HOMEPAGE.HOMEPAGE_SCHEMA;
DELETE FROM HOMEPAGE.LOGINNAME;
DELETE FROM HOMEPAGE.HP_WIDGET_INST;
DELETE FROM HOMEPAGE.HP_TAB_INST;
DELETE FROM HOMEPAGE.HP_WIDGET_TAB; 
DELETE FROM HOMEPAGE.HP_UI;
DELETE FROM HOMEPAGE.HP_TAB;
DELETE FROM HOMEPAGE.PREREQ;
DELETE FROM HOMEPAGE.WIDGET;
DELETE FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT;
DELETE FROM HOMEPAGE.NT_NOTIFICATION;
DELETE FROM HOMEPAGE.NR_NEWS_RECORDS;
DELETE FROM HOMEPAGE.NR_SUBSCRIPTION;
DELETE FROM HOMEPAGE.NR_SOURCE;
DELETE FROM HOMEPAGE.NR_EVENT_RECORDS;
DELETE FROM HOMEPAGE.NR_TEMPLATE;
DELETE FROM HOMEPAGE.EMD_JOBS_STATS;
DELETE FROM HOMEPAGE.EMD_RECIPIENTS;
DELETE FROM HOMEPAGE.EMD_JOBS;
DELETE FROM HOMEPAGE.SR_INDEXINGTASKDEF;
DELETE FROM HOMEPAGE.SR_OPTIMIZETASKDEF;
DELETE FROM HOMEPAGE.SR_TASKDEF;
DELETE FROM HOMEPAGE.SR_FILESCONTENT;
DELETE FROM HOMEPAGE.SR_MIGTASKDEFINFO;
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMGR;
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMPR;
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTASK;
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTREG;
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMGR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMPR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TASK;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TREG;
DELETE FROM HOMEPAGE.PERSON;

-- HOMEPAGE 
ALTER TABLE HOMEPAGE.LOGINNAME DROP FOREIGN KEY "FK_LN_PERSON_ID";

ALTER TABLE HOMEPAGE.HP_UI DROP FOREIGN KEY "FK_UI_PERSON_ID";

ALTER TABLE HOMEPAGE.HP_TAB_INST DROP FOREIGN KEY "FK_UI_ID";

ALTER TABLE HOMEPAGE.HP_TAB_INST DROP FOREIGN KEY "FK_TAB_INST_TAB_ID";

ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP FOREIGN KEY "FK_WIDGET_ID";

ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP FOREIGN KEY "FK_TAB_INST_ID";

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP FOREIGN KEY "FK_WID_TAB_WID_ID";

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP FOREIGN KEY "FK_WID_TAB_TAB_ID";

ALTER TABLE HOMEPAGE.PREREQ DROP FOREIGN KEY "FK_PREREQ_WIDGET";

ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT DROP FOREIGN KEY "FK_RECIP_NOTIF";

ALTER TABLE HOMEPAGE.LOGINNAME DROP UNIQUE "LOGINNAME_UNIQUE";

DROP INDEX  HOMEPAGE.PERSON_EXID;

-- NEWS RECORDS 
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION DROP FOREIGN KEY "FK_PERSON_ID";

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION DROP FOREIGN KEY "FK_SOURCE_ID";

ALTER TABLE HOMEPAGE.EMD_RECIPIENTS DROP FOREIGN KEY "FK_REC_PERSON_ID";

ALTER TABLE HOMEPAGE.EMD_JOBS_STATS DROP FOREIGN KEY "FK_JOB_ID";

DROP INDEX  HOMEPAGE.NR_SUBSCRIPTION_IX_UNIQUE;

DROP INDEX  HOMEPAGE.NR_SOURCE_IX_UNIQUE;

ALTER TABLE HOMEPAGE.EMD_JOBS DROP UNIQUE "UNIQUE_JOB_FREQ";

-- SEARCH TABLES
ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF DROP FOREIGN KEY "FK_INDEX_TASK_ID";

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF DROP FOREIGN KEY "FK_OPT_TASK_ID";

ALTER TABLE HOMEPAGE.SR_TASKDEF DROP UNIQUE "UNIQUE_TASK_NAME";

ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF DROP UNIQUE "UNIQUE_TASK_ID_IND";

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF DROP UNIQUE "UNIQUE_TASK_ID_OPT";

ALTER TABLE HOMEPAGE.SR_FILESCONTENT DROP UNIQUE "UNIQUE_COMP_UUID";

ALTER TABLE HOMEPAGE.SR_TASKDEF DROP CHECK "CHECK_SR_TASKDEF";

COMMIT;
CONNECT RESET;
