-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
USE HOMEPAGE
GO

BEGIN TRANSACTION
GO


------------------------------------------------
-- INCLUDE POSTDBXFER30 FOR SEARCH
------------------------------------------------


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- SEARCH TABLES


----------------------------------------
--  SR_SANDTASKDEF
----------------------------------------


ALTER TABLE HOMEPAGE.SR_SANDTASKDEF
	ADD CONSTRAINT UNIQUE_TASK_ID_ST UNIQUE (TASK_ID);
	
ALTER TABLE HOMEPAGE.SR_SANDTASKDEF
	ADD CONSTRAINT FK_ST_TASK_ID FOREIGN KEY (TASK_ID) 
	REFERENCES  HOMEPAGE.SR_TASKDEF(TASK_ID) ON DELETE CASCADE;

----------------------------------------
--  SR_FILECONTENTTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF
	ADD CONSTRAINT UNIQUE_TASK_ID_FC UNIQUE (TASK_ID);

ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF
	ADD CONSTRAINT FK_FC_TASK_ID FOREIGN KEY (TASK_ID) 
	REFERENCES  HOMEPAGE.SR_TASKDEF(TASK_ID) ON DELETE CASCADE;


----------------------------------------
--  SR_BACKUPTASKDEF
----------------------------------------


ALTER TABLE HOMEPAGE.SR_BACKUPTASKDEF
	ADD CONSTRAINT UNIQUE_TASK_ID_BKP UNIQUE (TASK_ID);

ALTER TABLE HOMEPAGE.SR_BACKUPTASKDEF
	ADD CONSTRAINT FK_BKUP_TASK_ID FOREIGN KEY (TASK_ID) 
	REFERENCES  HOMEPAGE.SR_TASKDEF(TASK_ID) ON DELETE CASCADE;
    
----------------------------------------
--  SR_INDEXTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF
	ADD CONSTRAINT UNIQUE_TASK_ID_IND UNIQUE (TASK_ID);


ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF
	ADD CONSTRAINT FK_INDEX_TASK_ID FOREIGN KEY (TASK_ID) 
	REFERENCES HOMEPAGE.SR_TASKDEF(TASK_ID) ON DELETE CASCADE;

    

----------------------------------------
--  SR_OPTIMIZETASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF
	ADD CONSTRAINT UNIQUE_TASK_ID_OPT UNIQUE (TASK_ID);



ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF
	ADD CONSTRAINT FK_OPT_TASK_ID FOREIGN KEY (TASK_ID) 
	REFERENCES  HOMEPAGE.SR_TASKDEF(TASK_ID) ON DELETE CASCADE;


----------------------------------------
--  SR_TASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_TASKDEF
    ADD CONSTRAINT UNIQUE_TASK_NAME UNIQUE (TASK_NAME);

ALTER TABLE HOMEPAGE.SR_TASKDEF
    ADD CONSTRAINT CHECK_SR_TASKDEF
    CHECK ( (STARTBY IS NOT NULL AND INTERVAL IS NOT NULL) OR (STARTBY IS NULL AND INTERVAL IS NULL) );

----------------------------------------
--  SR_FILESCONTENT
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FILESCONTENT
	ADD CONSTRAINT UNIQUE_COMP_UUID UNIQUE (COMPONENT_UUID,COMPONENT);


CREATE INDEX SR_FILESCONTENT_IS_CURRENT_IDX 
	ON HOMEPAGE.SR_FILESCONTENT(IS_CURRENT);

----------------------------------------
--  SR_RESUME_TOKENS
----------------------------------------


ALTER TABLE HOMEPAGE.SR_RESUME_TOKENS
	ADD CONSTRAINT FK_RT_IDX_MGMT_ID FOREIGN KEY (NODE_ID)
	REFERENCES HOMEPAGE.SR_INDEX_MANAGEMENT(NODE_ID) ON DELETE CASCADE;

----------------------------------------
--  SR_FACET_DOCS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FACET_DOCS
	ADD CONSTRAINT FK_IDX_DOC_ID FOREIGN KEY (DOCUMENT_ID) 
	REFERENCES  HOMEPAGE.SR_INDEX_DOCS(DOCUMENT_ID) ON DELETE CASCADE;

CREATE INDEX SR_FACET_DOCS_PARENT_IDX
	ON HOMEPAGE.SR_FACET_DOCS (DOCUMENT_ID)

----------------------------------------
--  SR_INDEX_DOCS
----------------------------------------

CREATE INDEX SR_INDEX_DOCS_CRAWL_VERSION_IDX
	ON HOMEPAGE.SR_INDEX_DOCS (CRAWLING_VERSION);

----------------------------------------
--  SR_FEEDBACK
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK
	ADD CONSTRAINT FK_SRFB_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID)
GO	

CREATE INDEX SR_FEEDBACK_CLIENT_IDX
		ON HOMEPAGE.SR_FEEDBACK (CLIENT_ID)
GO

----------------------------------------
--  SR_FEEDBACK_CONTEXT
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK_CONTEXT
	ADD CONSTRAINT FK_FBK_CTXT_ID FOREIGN KEY (ID)
	REFERENCES HOMEPAGE.SR_FEEDBACK(ID) ON DELETE CASCADE
GO	

----------------------------------------
--  SR_FEEDBACK_PARAMETERS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK_PARAMETERS
	ADD CONSTRAINT FK_FBK_PARAMS_ID FOREIGN KEY (ID)
	REFERENCES HOMEPAGE.SR_FEEDBACK(ID) ON DELETE CASCADE
GO	

----------------------------------------
--  SR_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_STATS
	ADD CONSTRAINT UNIQUE_STAT_KEY UNIQUE (STAT_KEY)
GO	

----------------------------------------
--  SR_STRING_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_STRING_STATS
	ADD CONSTRAINT FK_STR_STAT_ID FOREIGN KEY (STAT_ID)
	REFERENCES HOMEPAGE.SR_STATS(STAT_ID) ON DELETE CASCADE
GO	
----------------------------------------
--  SR_NUMBER_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_NUMBER_STATS
	ADD CONSTRAINT FK_NUM_STAT_ID FOREIGN KEY (STAT_ID)
	REFERENCES HOMEPAGE.SR_STATS(STAT_ID) ON DELETE CASCADE
GO	
----------------------------------------
--  SR_TIMER_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_TIMER_STATS
	ADD CONSTRAINT FK_TMR_STAT_ID FOREIGN KEY (STAT_ID)
	REFERENCES HOMEPAGE.SR_STATS(STAT_ID) ON DELETE CASCADE
GO	


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


--SPR#COFN8DFMY7


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

-- SEARCH

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTASK;
GO
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTREG;
GO
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMGR;
GO
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMPR;
GO



-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


DELETE FROM HOMEPAGE.SR_FILESCONTENT
GO

DELETE FROM HOMEPAGE.SR_FACET_DOCS
GO

DELETE FROM HOMEPAGE.SR_INDEX_DOCS
GO


DELETE FROM HOMEPAGE.SR_RESUME_TOKENS
GO

DELETE FROM HOMEPAGE.SR_INDEX_MANAGEMENT
GO



------------------------------------------------
-- INCLUDE POSTDBXFER30 FOR NEWS
------------------------------------------------


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- NEWS RECORDS 
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);
	
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT FK_SOURCE_ID FOREIGN KEY (SOURCE_ID)
	REFERENCES HOMEPAGE.NR_SOURCE (SOURCE_ID);

CREATE UNIQUE INDEX NR_SUBSCRIPTION_IX_UNIQUE
	ON HOMEPAGE.NR_SUBSCRIPTION(PERSON_ID ASC, SOURCE_ID ASC);

--CREATE UNIQUE INDEX NR_SOURCE_IX_UNIQUE
--	ON HOMEPAGE.NR_SOURCE(SOURCE ASC, CONTAINER_ID ASC, ENTRY_ID ASC);

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT
  	ADD CONSTRAINT FK_C_COMMENT_ID FOREIGN KEY (NEWS_STATUS_COMMENT_ID)
	REFERENCES HOMEPAGE.NR_NEWS_STATUS_COMMENT(NEWS_STATUS_COMMENT_ID);
	
ALTER TABLE HOMEPAGE.NR_RESOURCE_TYPE 
	ADD CONSTRAINT RES_TYPE_UNIQUE UNIQUE (RESOURCE_TYPE);

ALTER TABLE HOMEPAGE.NR_RESOURCE
    ADD CONSTRAINT FK_RES_RES_TYPE FOREIGN KEY (RESOURCE_TYPE)
	REFERENCES HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE);
	
ALTER TABLE HOMEPAGE.NR_RESOURCE
    ADD CONSTRAINT FK_RES_CAT_TYPE FOREIGN KEY (CATEGORY_TYPE)
	REFERENCES HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE);
	
ALTER TABLE HOMEPAGE.NR_FOLLOWS
    ADD CONSTRAINT FK_FS_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_FOLLOWS
    ADD CONSTRAINT FK_FS_RESOURCE_ID FOREIGN KEY (RESOURCE_ID)
	REFERENCES HOMEPAGE.NR_RESOURCE (RESOURCE_ID);

ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW
    ADD CONSTRAINT FK_COMM_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_ORGPERSON_FOLLOW
    ADD CONSTRAINT FK_ORGP_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

--ALTER TABLE HOMEPAGE.NR_COMM_STORIES
--    ADD CONSTRAINT FK_COMM_STORY_ID FOREIGN KEY (STORY_ID)
--	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_ORGPERSON_STORIES
--    ADD CONSTRAINT FK_ORGP_STORY_ID FOREIGN KEY (STORY_ID)
--	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD CONSTRAINT FK_NTW_PERS_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD CONSTRAINT FK_NTW_COLL_ID FOREIGN KEY (COLLEAGUE_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW
    ADD CONSTRAINT FK_COMM_PER_PER_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

--ALTER TABLE HOMEPAGE.NR_COMM_PERSON_STORIES
--    ADD CONSTRAINT FK_FCP_STORY_ID FOREIGN KEY (STORY_ID)
--	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);	

ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE
	ADD CONSTRAINT FRQ_TYPE_UNIQUE UNIQUE (FREQUENCY_TYPE);
	
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF
    ADD CONSTRAINT FK_RES_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF
    ADD CONSTRAINT FK_RES_FRQ_TYPE FOREIGN KEY (FREQUENCY_TYPE)
	REFERENCES HOMEPAGE.EMD_FREQUENCY_TYPE (FREQUENCY_TYPE);
	
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS
    ADD CONSTRAINT FK_EMD_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
    ADD CONSTRAINT FK_TRANCHE_ID FOREIGN KEY (TRANCHE_ID)
	REFERENCES HOMEPAGE.EMD_TRANCHE (TRANCHE_ID);

--ALTER TABLE HOMEPAGE.NR_RESPONSES_STORIES
--    ADD CONSTRAINT FK_RESP_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_PROFILES_STORIES 
--    ADD CONSTRAINT FK_PROF_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_COMMUNITIES_STORIES
--    ADD CONSTRAINT FK_COM_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_ACTIVITIES_STORIES
--    ADD CONSTRAINT FK_ACT_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_BLOGS_STORIES
--    ADD CONSTRAINT FK_BLOGS_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_BOOKMARKS_STORIES
--    ADD CONSTRAINT FK_BOOKS_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_FILES_STORIES
--    ADD CONSTRAINT FK_FILES_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_FORUMS_STORIES
--    ADD CONSTRAINT FK_FORUMS_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_WIKIS_STORIES
--    ADD CONSTRAINT FK_WIKIS_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

--ALTER TABLE HOMEPAGE.NR_TAGS_STORIES
--    ADD CONSTRAINT FK_TAGS_STORY_ID FOREIGN KEY (STORY_ID)
--    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);	
	
-- Delete content from news scheduler tables
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMPR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMGR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TREG;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TASK;		
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


------------------------------------------------
-- INCLUDE POSTDBXFER30 FOR HP
------------------------------------------------


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- HOMEPAGE 
ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT FK_LN_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);
	
ALTER TABLE HOMEPAGE.HP_UI
    ADD CONSTRAINT FK_UI_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);	
	
ALTER TABLE HOMEPAGE.HP_TAB_INST 
    ADD CONSTRAINT FK_UI_ID FOREIGN KEY (UI_ID)
	REFERENCES HOMEPAGE.HP_UI(UI_ID);

ALTER TABLE HOMEPAGE.HP_TAB_INST
    ADD CONSTRAINT FK_TAB_INST_TAB_ID FOREIGN KEY (TAB_ID)
	REFERENCES HOMEPAGE.HP_TAB(TAB_ID);

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
    ADD CONSTRAINT FK_WIDGET_ID FOREIGN KEY (WIDGET_ID)
	REFERENCES HOMEPAGE.WIDGET (WIDGET_ID);

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
    ADD CONSTRAINT FK_TAB_INST_ID FOREIGN KEY (TAB_INST_ID)
	REFERENCES HOMEPAGE.HP_TAB_INST(TAB_INST_ID);

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB	
    ADD CONSTRAINT FK_WID_TAB_WID_ID FOREIGN KEY (WIDGET_ID)
	REFERENCES HOMEPAGE.WIDGET(WIDGET_ID);

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB	
    ADD CONSTRAINT FK_WID_TAB_TAB_ID FOREIGN KEY (TAB_ID)
	REFERENCES HOMEPAGE.HP_TAB(TAB_ID);	

ALTER TABLE HOMEPAGE.PREREQ 
	ADD CONSTRAINT FK_PREREQ_WIDGET FOREIGN KEY (WIDGET_ID)
	REFERENCES HOMEPAGE.WIDGET (WIDGET_ID)
	ON DELETE CASCADE;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
    ADD CONSTRAINT FK_SENDER_ID FOREIGN KEY (SENDER_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
    ADD CONSTRAINT FK_F_RECIPIENT_ID FOREIGN KEY (FIRST_RECIPIENT_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);
	
ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
	ADD CONSTRAINT FK_RECIP_NOTIF FOREIGN KEY (NOTIFICATION_ID)
	REFERENCES HOMEPAGE.NT_NOTIFICATION (NOTIFICATION_ID)
	ON DELETE CASCADE;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT
    ADD CONSTRAINT FK_RECIPIENT_ID FOREIGN KEY (RECIPIENT_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);		

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT LOGINNAME_UNIQUE UNIQUE(LOGINNAME);

CREATE UNIQUE INDEX PERSON_EXID
	ON HOMEPAGE.PERSON (EXID);
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


COMMIT;
