-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
USE HOMEPAGE;
GO

BEGIN TRANSACTION
GO

-- Preparing NR_STORIES
ALTER TABLE HOMEPAGE.NR_STORIES
  	ADD CONSTRAINT FK_ENTRY_ID FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES (ENTRY_ID);  
GO

CREATE INDEX NR_STORIES_EIDX
    ON HOMEPAGE.NR_STORIES (ENTRY_ID);
GO

CREATE INDEX NR_STORIES_ER_UUID
    ON HOMEPAGE.NR_STORIES (EVENT_RECORD_UUID, STORY_ID);
GO

CREATE INDEX NR_STORIES_DATE
	ON HOMEPAGE.NR_STORIES (CREATION_DATE DESC);
GO

CREATE INDEX STORY_CONTAINED_ID
    ON HOMEPAGE.NR_STORIES (CONTAINER_ID);
GO

CREATE INDEX NR_STORY_CD_IDX 
	ON HOMEPAGE.NR_STORIES (CREATION_DATE ASC, STORY_ID);
GO

CREATE INDEX STORIES_EVENT_ITEM_ACTOR_IDX ON
	HOMEPAGE.NR_STORIES (EVENT_NAME, ITEM_ID, ACTOR_UUID);
GO

DROP INDEX MIG_STORIES_ITEM_CD ON HOMEPAGE.NR_STORIES;
GO

CREATE INDEX STORIES_ITEM_ENTRY_CORR_ID
    ON HOMEPAGE.NR_STORIES (ENTRY_CORRELATION_ID);
GO 

DROP INDEX MIG_RLL_STORY_IDX ON HOMEPAGE.NR_STORIES;
GO
   
--DROP INDEX MIG_STORIES_ITEM_ID ON HOMEPAGE.NR_STORIES;
--GO

-- Preparing NR_ENTRIES and NR_ENTRIES_ARCHIVE
CREATE INDEX NR_ENTRIES_CONT
    ON HOMEPAGE.NR_ENTRIES (CONTAINER_ID);
GO

CREATE INDEX NR_ENTRIES_AR_CONT
    ON HOMEPAGE.NR_ENTRIES_ARCHIVE (CONTAINER_ID);
GO

-- Preparing NR_NOTIFICATION to speed up notification reads:
--DROP INDEX MIG_NOT_EXID_PER_ID ON HOMEPAGE.PERSON;
--GO

DROP INDEX MIG_NOT_READS ON HOMEPAGE.NT_NOTIFICATION;
GO

-------------------------------------------------------------------------------




ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_AGGREGATED_READERS
CREATE INDEX AGGREGATED_READERS_ITM_IX ON HOMEPAGE.NR_AGGREGATED_READERS (ITEM_ID) ;
GO

CREATE INDEX AGGREGATED_READERS_CD_IX ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX AGGREGATED_READERS_SRC_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX AGGREGATED_READERS_RLL_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX AGGREGATED_READERS_DEL_SERV_IX ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX AGGREGATED_READERS_ROLLUP_IX ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX AGGREGATED_READERS_RIR_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO



--  [end indexes] NR_AGGREGATED_READERS



ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT FK_RES_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_RESPONSES_READERS
CREATE INDEX RESPONSES_READERS_ITM_IX ON HOMEPAGE.NR_RESPONSES_READERS (ITEM_ID) ;
GO

CREATE INDEX RESPONSES_READERS_CD_IX ON HOMEPAGE.NR_RESPONSES_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX RESPONSES_READERS_SRC_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX RESPONSES_READERS_RLL_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX RESPONSES_READERS_DEL_SERV_IX ON HOMEPAGE.NR_RESPONSES_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX RESPONSES_READERS_ROLLUP_IX ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX RESPONSES_READERS_RIR_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_RESPONSES_READERS



ALTER TABLE HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT FK_PRF_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_PROFILES_READERS
CREATE INDEX PROFILES_READERS_ITM_IX ON HOMEPAGE.NR_PROFILES_READERS (ITEM_ID) ;
GO

CREATE INDEX PROFILES_READERS_CD_IX ON HOMEPAGE.NR_PROFILES_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX PROFILES_READERS_SRC_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX PROFILES_READERS_RLL_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX PROFILES_READERS_DEL_SERV_IX ON HOMEPAGE.NR_PROFILES_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX PROFILES_READERS_ROLLUP_IX ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX PROFILES_READERS_RIR_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_PROFILES_READERS



ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT FK_COM_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_COMMUNITIES_READERS
CREATE INDEX COMM_READERS_ITM_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (ITEM_ID) ;
GO

CREATE INDEX COMM_READERS_CD_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX COMM_READERS_SRC_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO


CREATE INDEX COMM_READERS_RLL_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX COMM_READERS_DEL_SERV_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (CREATION_DATE DESC, IS_BROADCAST) ;
GO

CREATE INDEX COMM_READERS_ROLLUP_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX COMM_READERS_RIR_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_COMMUNITIES_READERS



ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT FK_ACI_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_ACTIVITIES_READERS
CREATE INDEX ACTIVITIES_READERS_ITM_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (ITEM_ID) ;
GO

CREATE INDEX ACTIVITIES_READERS_CD_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX ACTIVITIES_READERS_SRC_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO


CREATE INDEX ACTIVITIES_READERS_RLL_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX ACTIVITIES_READERS_DEL_SERV_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX ACTIVITIES_READERS_ROLLUP_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX ACTIVITIES_READERS_RIR_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_ACTIVITIES_READERS



ALTER TABLE HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT FK_BLG_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_BLOGS_READERS
CREATE INDEX BLOGS_READERS_ITM_IX ON HOMEPAGE.NR_BLOGS_READERS (ITEM_ID) ;
GO

CREATE INDEX BLOGS_READERS_CD_IX ON HOMEPAGE.NR_BLOGS_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX BLOGS_READERS_SRC_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO


CREATE INDEX BLOGS_READERS_RLL_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX BLOGS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_BLOGS_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX BLOGS_READERS_ROLLUP_IX ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX BLOGS_READERS_RIR_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO
--  [end indexes] NR_BLOGS_READERS



ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT FK_BKM_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_BOOKMARKS_READERS
CREATE INDEX BOOKMARKS_READERS_ITM_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (ITEM_ID) ;
GO

CREATE INDEX BOOKMARKS_READERS_CD_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX BOOKMARKS_READERS_SRC_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX BOOKMARKS_READERS_RLL_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX BOOKMARKS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX BOOKMARKS_READERS_ROLLUP_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX BOOKMARKS_READERS_RIR_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_BOOKMARKS_READERS



ALTER TABLE HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT FK_FIL_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_FILES_READERS
CREATE INDEX FILES_READERS_ITM_IX ON HOMEPAGE.NR_FILES_READERS (ITEM_ID) ;
GO

CREATE INDEX FILES_READERS_CD_IX ON HOMEPAGE.NR_FILES_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX FILES_READERS_SRC_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX FILES_READERS_RLL_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX FILES_READERS_DEL_SERV_IX ON HOMEPAGE.NR_FILES_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX FILES_READERS_ROLLUP_IX ON HOMEPAGE.NR_FILES_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX FILES_READERS_RIR_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO
--  [end indexes] NR_FILES_READERS



ALTER TABLE HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT FK_FRM_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_FORUMS_READERS
CREATE INDEX FORUMS_READERS_ITM_IX ON HOMEPAGE.NR_FORUMS_READERS (ITEM_ID) ;
GO

CREATE INDEX FORUMS_READERS_CD_IX ON HOMEPAGE.NR_FORUMS_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX FORUMS_READERS_SRC_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX FORUMS_READERS_RLL_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX FORUMS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_FORUMS_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX FORUMS_READERS_ROLLUP_IX ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX FORUMS_READERS_RIR_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_FORUMS_READERS



ALTER TABLE HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT FK_WIK_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_WIKIS_READERS
CREATE INDEX WIKIS_READERS_ITM_IX ON HOMEPAGE.NR_WIKIS_READERS (ITEM_ID) ;
GO

CREATE INDEX WIKIS_READERS_CD_IX ON HOMEPAGE.NR_WIKIS_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX WIKIS_READERS_SRC_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX WIKIS_READERS_RLL_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX WIKIS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_WIKIS_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX WIKIS_READERS_ROLLUP_IX ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX WIKIS_READERS_RIR_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_WIKIS_READERS



ALTER TABLE HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT FK_TAG_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_TAGS_READERS
CREATE INDEX TAGS_READERS_ITM_IX ON HOMEPAGE.NR_TAGS_READERS (ITEM_ID) ;
GO

CREATE INDEX TAGS_READERS_CD_IX ON HOMEPAGE.NR_TAGS_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX TAGS_READERS_SRC_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO


CREATE INDEX TAGS_READERS_RLL_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX TAGS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_TAGS_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX TAGS_READERS_ROLLUP_IX ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX TAGS_READERS_RIR_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_TAGS_READERS



ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT FK_STA_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE INDEX STATUS_READERS_ITM_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ITEM_ID) ;
GO

CREATE INDEX STATUS_READERS_CD_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX STATUS_READERS_SRC_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX STATUS_READERS_RLL_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX STATUS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX STATUS_READERS_ROLLUP_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX STATUS_READERS_RIR_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_STATUS_UPDATE_READERS



ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT FK_EXT_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_EXTERNAL_READERS
CREATE INDEX EXTERNAL_READERS_ITM_IX ON HOMEPAGE.NR_EXTERNAL_READERS (ITEM_ID) ;
GO

CREATE INDEX EXTERNAL_READERS_CD_IX ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX EXTERNAL_READERS_SRC_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX EXTERNAL_READERS_RLL_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX EXTERNAL_READERS_DEL_SERV_IX ON HOMEPAGE.NR_EXTERNAL_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX EXTERNAL_READERS_ROLLUP_IX ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX EXTERNAL_READERS_RIR_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_EXTERNAL_READERS



ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT FK_ACT_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_ACTIONABLE_READERS
CREATE INDEX ACTIONABLE_READERS_ITM_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (ITEM_ID) ;
GO

CREATE INDEX ACTIONABLE_READERS_CD_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX ACTIONABLE_READERS_SRC_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX ACTIONABLE_READERS_RLL_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX ACTIONABLE_READERS_DEL_SERV_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX ACTIONABLE_READERS_ROLLUP_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX ACTIONABLE_READERS_RIR_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_ACTIONABLE_READERS



ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW ADD CONSTRAINT FK_DIS_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_DISCOVERY_VIEW
CREATE INDEX DISCOVERY_VIEW_ITM_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (ITEM_ID) ;
GO

CREATE INDEX DISCOVERY_VIEW_CD_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX DISCOVERY_VIEW_SRC_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX DISCOVERY_VIEW_RLL_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX DISCOVERY_VIEW_DEL_SERV_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, IS_BROADCAST) ;
GO

CREATE INDEX DISCOVERY_VIEW_ROLLUP_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_ENTRY_ID) ;
GO

CREATE INDEX DISCOVERY_VIEW_RIR_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

CREATE  INDEX DISCOVERY_VIEW_ACT_CD_VIS_IDX  
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ACTOR_UUID, CREATION_DATE DESC, IS_VISIBLE); 
GO

--  [end indexes] NR_DISCOVERY_VIEW



ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW ADD CONSTRAINT FK_PRO_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_PROFILES_VIEW
CREATE INDEX PROFILES_VIEW_ITM_IX ON HOMEPAGE.NR_PROFILES_VIEW (ITEM_ID) ;
GO

CREATE INDEX PROFILES_VIEW_CD_IX ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX PROFILES_VIEW_SRC_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX PROFILES_VIEW_RLL_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX PROFILES_VIEW_DEL_SERV_IX ON HOMEPAGE.NR_PROFILES_VIEW (CREATION_DATE DESC, IS_BROADCAST) ;
GO

CREATE INDEX PROFILES_VIEW_ROLLUP_IX ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX PROFILES_VIEW_RIR_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_PROFILES_VIEW



ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD CONSTRAINT FK_NOT_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE INDEX NOTIFICA_READERS_ITM_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ITEM_ID) ;
GO

CREATE INDEX NOTIFICA_READERS_CD_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX NOTIFICA_READERS_SRC_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX NOTIFICA_READERS_RLL_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX NOTIFICA_READERS_DEL_SERV_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX NOTIFICA_READERS_ROLLUP_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX NOTIFICA_READERS_RIR_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS



ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD CONSTRAINT FK_REC_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE INDEX NOT_REC_READERS_ITM_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ITEM_ID) ;
GO

CREATE INDEX NOT_REC_READERS_CD_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX NOT_REC_READERS_SRC_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX NOT_REC_READERS_RLL_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX NOT_REC_READERS_DEL_SERV_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX NOT_REC_READERS_ROLLUP_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX NOT_REC_READERS_RIR_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS



ALTER TABLE HOMEPAGE.NR_SAVED_READERS ADD CONSTRAINT FK_SAV_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_SAVED_READERS
CREATE INDEX SAVED_READERS_ITM_IX ON HOMEPAGE.NR_SAVED_READERS (ITEM_ID) ;
GO

CREATE INDEX SAVED_READERS_CD_IX ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX SAVED_READERS_SRC_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX SAVED_READERS_RLL_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX SAVED_READERS_DEL_SERV_IX ON HOMEPAGE.NR_SAVED_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX SAVED_READERS_ROLLUP_IX ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX SAVED_READERS_RIR_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_SAVED_READERS



ALTER TABLE HOMEPAGE.NR_TOPICS_READERS ADD CONSTRAINT FK_TOP_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
GO


--  [start indexes] NR_TOPICS_READERS
CREATE INDEX TOPICS_READERS_ITM_IX ON HOMEPAGE.NR_TOPICS_READERS (ITEM_ID) ;
GO

CREATE INDEX TOPICS_READERS_CD_IX ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, CREATION_DATE DESC) ;
GO

CREATE INDEX TOPICS_READERS_SRC_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE) ;
GO

CREATE INDEX TOPICS_READERS_RLL_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP) ;
GO

CREATE INDEX TOPICS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_TOPICS_READERS (CREATION_DATE DESC) ;
GO

CREATE INDEX TOPICS_READERS_ROLLUP_IX ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID) ;
GO

CREATE INDEX TOPICS_READERS_RIR_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
GO

--  [end indexes] NR_TOPICS_READERS

--------------------------------------------------- DROPPING A SPECIFIC INDEX USED BY MIGRATION ROLLUP ----------------------

--  [start indexes] NR_AGGREGATED_READERS
DROP INDEX AGGREGATED_READERS_MIG_IX ON HOMEPAGE.NR_AGGREGATED_READERS;
GO

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
DROP INDEX RESPONSES_READERS_MIG_IX ON HOMEPAGE.NR_RESPONSES_READERS;
GO

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
DROP INDEX PROFILES_READERS_MIG_IX ON HOMEPAGE.NR_PROFILES_READERS;
GO

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
DROP INDEX COMM_READERS_MIG_IX ON HOMEPAGE.NR_COMMUNITIES_READERS;
GO

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
DROP INDEX ACTIVITIES_READERS_MIG_IX ON HOMEPAGE.NR_ACTIVITIES_READERS;
GO

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
DROP INDEX BLOGS_READERS_MIG_IX ON HOMEPAGE.NR_BLOGS_READERS;
GO

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
DROP INDEX BOOKMARKS_READERS_MIG_IX ON HOMEPAGE.NR_BOOKMARKS_READERS;
GO

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
DROP INDEX FILES_READERS_MIG_IX ON HOMEPAGE.NR_FILES_READERS;
GO

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
DROP INDEX FORUMS_READERS_MIG_IX ON HOMEPAGE.NR_FORUMS_READERS;
GO

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
DROP INDEX WIKIS_READERS_MIG_IX ON HOMEPAGE.NR_WIKIS_READERS;
GO

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
DROP INDEX TAGS_READERS_MIG_IX ON HOMEPAGE.NR_TAGS_READERS;
GO

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP INDEX STATUS_READERS_MIG_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP INDEX EXTERNAL_READERS_MIG_IX ON HOMEPAGE.NR_EXTERNAL_READERS;
GO

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP INDEX ACTIONABLE_READERS_MIG_IX ON HOMEPAGE.NR_ACTIONABLE_READERS;
GO

--  [end indexes] NR_ACTIONABLE_READERS


--  [start indexes] NR_DISCOVERY_VIEW
DROP INDEX DISCOVERY_VIEW_MIG_IX ON HOMEPAGE.NR_DISCOVERY_VIEW;
GO

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
DROP INDEX PROFILES_VIEW_MIG_IX ON HOMEPAGE.NR_PROFILES_VIEW;
GO

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP INDEX NOTIFICA_READERS_MIG_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP INDEX NOT_REC_READERS_MIG_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
DROP INDEX SAVED_READERS_MIG_IX ON HOMEPAGE.NR_SAVED_READERS;
GO

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
DROP INDEX TOPICS_READERS_MIG_IX ON HOMEPAGE.NR_TOPICS_READERS;
GO

--  [end indexes] NR_TOPICS_READERS

GO

--70800: [fixup104] add an index on  RELATED_COMMUNITY_ID
CREATE INDEX NR_STORIES_REL_COMM
	ON HOMEPAGE.NR_STORIES (RELATED_COMMUNITY_ID);
GO

--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

DROP INDEX MIG_STR_CORR ON HOMEPAGE.NR_STORIES;


-----------------------------------------------------------------------------------------------------
-- [START] 70821: [fixup104] After rally we see we can improve of 90% perf. on querying readers table.
-----------------------------------------------------------------------------------------------------

--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX AGGREGATED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX RESPONSES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX PROFILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX COMM_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX ACTIVITIES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX BLOGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX BOOKMARKS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX FILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX FORUMS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX WIKIS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX TAGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX STATUS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX EXTERNAL_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX SAVED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX ACTIONABLE_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX DISCOVERY_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX PROFILES_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX NOTIFICA_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX NOT_REC_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX TOPICS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
GO

--  [end indexes] NR_TOPICS_READERS

-----------------------------------------------------------------------------------------------------
-- [END] 70821: [fixup104] After rally we see we can improve of 90% perf. on querying readers table.
-----------------------------------------------------------------------------------------------------


COMMIT;

