-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2016                                          
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 


-- 5724_S68 
USE HOMEPAGE;
GO
BEGIN TRANSACTION
GO

-- REMOVING RECORDS
DELETE FROM HOMEPAGE.L3T_EXT_BINDS;
GO
DELETE FROM HOMEPAGE.L3T_EXT_POINTS;
GO
DELETE FROM HOMEPAGE.SR_FILECONTENTINDEXINGTASK;
GO
DELETE FROM HOMEPAGE.L3T_USER_PKG_PREFS;
GO
DELETE FROM HOMEPAGE.L3T_USER_ENTITLEMENTS;
GO
DELETE FROM HOMEPAGE.L3T_PACKAGE_LOCATION;
GO
DELETE FROM HOMEPAGE.L3T_PACKAGE_DETAILS;
GO
DELETE FROM HOMEPAGE.L3T_EXT_META2;
GO
DELETE FROM HOMEPAGE.L3T_COMPANY_PKG_PREFS;
GO
DELETE FROM HOMEPAGE.L3T_COMPANY_ENTITLEMENTS;
GO
DELETE FROM HOMEPAGE.L3T_PACKAGES;
GO
DELETE FROM HOMEPAGE.L3T_USERS;
GO
DELETE FROM HOMEPAGE.L3T_COMPANIES;
GO
DELETE FROM HOMEPAGE.L3T_ORGANIZATION;
GO
DELETE FROM HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON;
GO
DELETE FROM HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION;
GO
DELETE FROM HOMEPAGE.NR_READ_STATUS;
GO
DELETE FROM HOMEPAGE.SR_RECOMMEND_CACHE_USERPROFILE;
GO
DELETE FROM HOMEPAGE.NR_CUSTOM_LIST_ITEM;
GO
DELETE FROM HOMEPAGE.NR_CUSTOM_LIST;
GO
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMPR;
GO
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMGR;
GO
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTREG;
GO
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTASK;
GO
DELETE FROM HOMEPAGE.SR_ECM_DOCUMENT_TYPE_PROPS;
GO
DELETE FROM HOMEPAGE.SR_POST_FILTERING_SERVICE;
GO
DELETE FROM HOMEPAGE.SR_ECM_DOCUMENT_TYPE_LABELS;
GO
DELETE FROM HOMEPAGE.SR_GLOBAL_SAND_PROPS;
GO
DELETE FROM HOMEPAGE.SR_TIMER_STATS;
GO
DELETE FROM HOMEPAGE.SR_NUMBER_STATS;
GO
DELETE FROM HOMEPAGE.SR_STRING_STATS;
GO
DELETE FROM HOMEPAGE.SR_STATS;
GO
DELETE FROM HOMEPAGE.SR_FEEDBACK_PARAMETERS;
GO
DELETE FROM HOMEPAGE.SR_FEEDBACK_CONTEXT;
GO
DELETE FROM HOMEPAGE.SR_FEEDBACK;
GO
DELETE FROM HOMEPAGE.SR_INDEX_DOCS;
GO
DELETE FROM HOMEPAGE.SR_RESUME_TOKENS;
GO
DELETE FROM HOMEPAGE.SR_INDEX_MANAGEMENT;
GO
DELETE FROM HOMEPAGE.SR_MIGTASKDEFINFO;
GO
DELETE FROM HOMEPAGE.SR_FILESCONTENT;
GO
DELETE FROM HOMEPAGE.SR_SANDTASKDEF;
GO
DELETE FROM HOMEPAGE.SR_BACKUPTASKDEF;
GO
DELETE FROM HOMEPAGE.SR_FILECONTENTTASKDEF;
GO
DELETE FROM HOMEPAGE.SR_OPTIMIZETASKDEF;
GO
DELETE FROM HOMEPAGE.SR_INDEXINGTASKDEF;
GO
DELETE FROM HOMEPAGE.SR_TASKDEF;
GO
DELETE FROM HOMEPAGE.OEMBED_SCHEDULER_LMPR;
GO
DELETE FROM HOMEPAGE.OEMBED_SCHEDULER_LMGR;
GO
DELETE FROM HOMEPAGE.OEMBED_SCHEDULER_TREG;
GO
DELETE FROM HOMEPAGE.OEMBED_SCHEDULER_TASK;
GO
DELETE FROM HOMEPAGE.NR_AS_COUNTS;
GO
DELETE FROM HOMEPAGE.IMG_CACHE;
GO
DELETE FROM HOMEPAGE.NR_AS_CONTENT_INDEX_STATS;
GO
DELETE FROM HOMEPAGE.NR_AS_CRAWLER_STATUS;
GO
DELETE FROM HOMEPAGE.NR_AS_COLLECTION_CONFIG;
GO
DELETE FROM HOMEPAGE.NR_AS_SEEDLIST;
GO
DELETE FROM HOMEPAGE.NR_COMMUNITIES_VIEW;
GO
DELETE FROM HOMEPAGE.NR_MENTIONS_READERS;
GO
DELETE FROM HOMEPAGE.NR_TOPICS_READERS;
GO
DELETE FROM HOMEPAGE.NR_SAVED_READERS;
GO
DELETE FROM HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
GO
DELETE FROM HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
GO
DELETE FROM HOMEPAGE.NR_PROFILES_VIEW;
GO
DELETE FROM HOMEPAGE.NR_COMM_SETTINGS;
GO
DELETE FROM HOMEPAGE.DELETED_STORIES_QUEUE;
GO
DELETE FROM HOMEPAGE.BOARD_MENTIONS;
GO
DELETE FROM HOMEPAGE.BOARD_CURRENT_STATUS;
GO
DELETE FROM HOMEPAGE.BOARD_RECOMMENDATIONS;
GO
DELETE FROM HOMEPAGE.BOARD_OBJECT_REFERENCE;
GO
DELETE FROM HOMEPAGE.BOARD_COMMENTS;
GO
DELETE FROM HOMEPAGE.BOARD_ENTRIES;
GO
DELETE FROM HOMEPAGE.BOARD;
GO
DELETE FROM HOMEPAGE.NR_ACTIONABLE_READERS;
GO
DELETE FROM HOMEPAGE.NR_EXTERNAL_READERS;
GO
DELETE FROM HOMEPAGE.NR_STATUS_UPDATE_READERS;
GO
DELETE FROM HOMEPAGE.NR_AGGREGATED_READERS;
GO
DELETE FROM HOMEPAGE.NR_ENTRIES_ARCHIVE;
GO
DELETE FROM HOMEPAGE.NR_STORIES;
GO
DELETE FROM HOMEPAGE.NR_ENTRIES;
GO
DELETE FROM HOMEPAGE.NR_COMM_PERSON_FOLLOW;
GO
DELETE FROM HOMEPAGE.EMD_EMAIL_PREFS;
GO
DELETE FROM HOMEPAGE.EMD_TRANCHE_INFO;
GO
DELETE FROM HOMEPAGE.EMD_TRANCHE;
GO
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF;
GO
DELETE FROM HOMEPAGE.NR_NETWORK;
GO
DELETE FROM HOMEPAGE.NR_STORIES_CONTENT;
GO
DELETE FROM HOMEPAGE.NR_COMM_FOLLOW;
GO
DELETE FROM HOMEPAGE.NR_FOLLOWS;
GO
DELETE FROM HOMEPAGE.NR_RESOURCE;
GO
DELETE FROM HOMEPAGE.NR_NEWS_COMMENT_CONTENT;
GO
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_CONTENT;
GO
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_COMMENT;
GO
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_NETWORK;
GO
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMPR;
GO
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMGR;
GO
DELETE FROM HOMEPAGE.NR_SCHEDULER_TREG;
GO
DELETE FROM HOMEPAGE.NR_SCHEDULER_TASK;
GO
DELETE FROM HOMEPAGE.NR_TEMPLATE;
GO
DELETE FROM HOMEPAGE.NR_SOURCE_TYPE;
GO
DELETE FROM HOMEPAGE.NR_SOURCE_TYPE_DEFAULT;
GO
DELETE FROM HOMEPAGE.MT_CFG_FILES;
GO
DELETE FROM HOMEPAGE.MT_CFG_SETTINGS;
GO
DELETE FROM HOMEPAGE.MT_CFG_DEFINITIONS;
GO
DELETE FROM HOMEPAGE.MTCONFIG;
GO
DELETE FROM HOMEPAGE.OH2P_CLIENTCFG;
GO
DELETE FROM HOMEPAGE.OH2P_CACHE;
GO
DELETE FROM HOMEPAGE.OAUTH2_TOKEN;
GO
DELETE FROM HOMEPAGE.OAUTH2_GADGET_BINDING;
GO
DELETE FROM HOMEPAGE.OAUTH2_CLIENT;
GO
DELETE FROM HOMEPAGE.OAUTH2_PROVIDER;
GO
DELETE FROM HOMEPAGE.OAUTH1_CONTEXT;
GO
DELETE FROM HOMEPAGE.OAUTH1_CLIENT;
GO
DELETE FROM HOMEPAGE.OAUTH1_PROVIDER;
GO
DELETE FROM HOMEPAGE.OAUTH1_TOKEN;
GO
DELETE FROM HOMEPAGE.METRIC_STAT;
GO
DELETE FROM HOMEPAGE.NT_REPLYTO_RECIPIENT;
GO
DELETE FROM HOMEPAGE.NT_REPLYTO;
GO
DELETE FROM HOMEPAGE.PREREQ;
GO
DELETE FROM HOMEPAGE.HP_WIDGET_INST;
GO
DELETE FROM HOMEPAGE.HP_WIDGET_TAB;
GO
DELETE FROM HOMEPAGE.WIDGET;
GO
DELETE FROM HOMEPAGE.HP_TAB_INST;
GO
DELETE FROM HOMEPAGE.HP_TAB;
GO
DELETE FROM HOMEPAGE.HP_UI;
GO
DELETE FROM HOMEPAGE.LOGINNAME;
GO
DELETE FROM HOMEPAGE.HP_USER_PREFS;
GO
DELETE FROM HOMEPAGE.PERSON_ROLE;
GO
DELETE FROM HOMEPAGE.PERSON;
GO
DELETE FROM HOMEPAGE.MT_ORGANIZATION;
GO
DELETE FROM HOMEPAGE.HOMEPAGE_SCHEMA;
GO

-- DROPPING CONSTRAINT
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BOARD_ORG_ID;
GO
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_CREATED;
GO
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_LASTUPDATE;
GO
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_OWNER;
GO
ALTER TABLE HOMEPAGE.BOARD_COMMENTS DROP CONSTRAINT FK_BOARD_COMMENTS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_COMMENTS DROP CONSTRAINT FK_BRD_COM_ENTRY;
GO
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP CONSTRAINT FK_BOARD_CURRENT_STATUS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP CONSTRAINT FK_CUR_ST_ACTOR_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP CONSTRAINT FK_CUR_ST_ENTRY_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT FK_BOARD_ENTRIES_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT FK_CONTAINER_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_MENTIONS DROP CONSTRAINT FK_BOARD_MENTIONS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_MENTIONS DROP CONSTRAINT FK_BRD_MEN_PER_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_AUTHOR_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_OBJ_REFERENCE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS DROP CONSTRAINT FK_BRD_RECOMMENDER;
GO
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS DROP CONSTRAINT FK_BRD_RECOMMENDER_D;
GO
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS DROP CONSTRAINT FK_BRD_RECOMM_ORG_ID;
GO
ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE DROP CONSTRAINT FK_DEL_STORIES_QUEUE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS DROP CONSTRAINT FK_EMD_EMAIL_PREFS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS DROP CONSTRAINT FK_EMD_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP CONSTRAINT FK_EMD_RES_PREF_ORG_ID;
GO
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP CONSTRAINT FK_RES_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.EMD_TRANCHE DROP CONSTRAINT FK_EMD_TRANCHE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO DROP CONSTRAINT FK_EMD_TRANCHE_INFO_ORG_ID;
GO
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO DROP CONSTRAINT FK_TRANCHE_ID;
GO
ALTER TABLE HOMEPAGE.HP_TAB DROP CONSTRAINT FK_TAB_ORG_ID;
GO
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP CONSTRAINT FK_TAB_INST_ORG_ID;
GO
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP CONSTRAINT FK_TAB_INST_TAB_ID;
GO
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP CONSTRAINT FK_UI_ID;
GO
ALTER TABLE HOMEPAGE.HP_UI DROP CONSTRAINT FK_UI_ORG_ID;
GO
ALTER TABLE HOMEPAGE.HP_UI DROP CONSTRAINT FK_UI_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.HP_USER_PREFS DROP CONSTRAINT FK_USER_PREFS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.HP_USER_PREFS DROP CONSTRAINT FK_USER_PREFS_PERS_ID;
GO
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP CONSTRAINT FK_TAB_INST_ID;
GO
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP CONSTRAINT FK_WIDGET_ID;
GO
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP CONSTRAINT FK_WIDGET_INST_ORG_ID;
GO
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP CONSTRAINT FK_WIDGET_TAB_ORG_ID;
GO
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP CONSTRAINT FK_WID_TAB_TAB_ID;
GO
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP CONSTRAINT FK_WID_TAB_WID_ID;
GO
ALTER TABLE HOMEPAGE.IMG_CACHE DROP CONSTRAINT FK_IMG_CACHE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_COMPANIES DROP CONSTRAINT FK_COM_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_COMPANY_ENTITLEMENTS DROP CONSTRAINT FK_COM_ENT_COM_ID;
GO
ALTER TABLE HOMEPAGE.L3T_COMPANY_ENTITLEMENTS DROP CONSTRAINT FK_COM_ENT_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_COMPANY_ENTITLEMENTS DROP CONSTRAINT FK_COM_ENT_PKG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_COMPANY_PKG_PREFS DROP CONSTRAINT FK_COM_PKG_PREF_COM_ID;
GO
ALTER TABLE HOMEPAGE.L3T_COMPANY_PKG_PREFS DROP CONSTRAINT FK_COM_PKG_PREF_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_COMPANY_PKG_PREFS DROP CONSTRAINT FK_COM_PKG_PREF_PKG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_EXT_META2 DROP CONSTRAINT FK_EXT_META2_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_PACKAGES DROP CONSTRAINT FK_PACKAGES_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_PACKAGES DROP CONSTRAINT FK_PACKAGES_OWNER_ID;
GO
ALTER TABLE HOMEPAGE.L3T_PACKAGE_DETAILS DROP CONSTRAINT FK_PKG_DET_PKG_IDFOREIGN;
GO
ALTER TABLE HOMEPAGE.L3T_PACKAGE_DETAILS DROP CONSTRAINT FK_PKG_DET_PKG_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_PACKAGE_LOCATION DROP CONSTRAINT FK_PACKAGE_LOCATION_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_USERS DROP CONSTRAINT FK_USERS_COMPANY_ID;
GO
ALTER TABLE HOMEPAGE.L3T_USERS DROP CONSTRAINT FK_USERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_USER_ENTITLEMENTS DROP CONSTRAINT FK_USR_ENT_PGK_ID;
GO
ALTER TABLE HOMEPAGE.L3T_USER_PKG_PREFS DROP CONSTRAINT FK_USR_PKG_PRF_ORG_ID;
GO
ALTER TABLE HOMEPAGE.L3T_USER_PKG_PREFS DROP CONSTRAINT FK_USR_PKG_PRF_PKG_ID;
GO
ALTER TABLE HOMEPAGE.LOGINNAME DROP CONSTRAINT FK_LN_ORG_ID;
GO
ALTER TABLE HOMEPAGE.LOGINNAME DROP CONSTRAINT FK_LN_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.METRIC_STAT DROP CONSTRAINT FK_METRIC_ORG_ID;
GO
ALTER TABLE HOMEPAGE.MT_CFG_FILES DROP CONSTRAINT FK_CFG_FILE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.MT_CFG_FILES DROP CONSTRAINT FK_SETTING_ID;
GO
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS DROP CONSTRAINT FK_CFG_SET_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT FK_ACT_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT FK_ACT_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS DROP CONSTRAINT FK_AS_CNT_INDEX_STATS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_AS_COUNTS DROP CONSTRAINT FK_AS_COUNT_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_AS_COUNTS DROP CONSTRAINT FK_AS_COUNT_PER_ID;
GO
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST DROP CONSTRAINT FK_AS_SEEDLIST_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW DROP CONSTRAINT FK_CV_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW DROP CONSTRAINT FK_CV_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW DROP CONSTRAINT FK_COMM_FOLLOW_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW DROP CONSTRAINT FK_COMM_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW DROP CONSTRAINT FK_COMM_PERSON_FOLLOW_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW DROP CONSTRAINT FK_COMM_PER_PER_ID;
GO
ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS DROP CONSTRAINT FK_COMM_SETTINGS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST DROP CONSTRAINT FK_CUST_L_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST DROP CONSTRAINT FK_CUST_L_PER_D_ID;
GO
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST DROP CONSTRAINT FK_CUST_L_PER_ID;
GO
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM DROP CONSTRAINT FK_CUSTOM_LIST_ID;
GO
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM DROP CONSTRAINT FK_CUST_L_I_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM DROP CONSTRAINT FK_CUST_L_I_PER_D_ID;
GO
ALTER TABLE HOMEPAGE.NR_ENTRIES DROP CONSTRAINT FK_ENTRIES_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE DROP CONSTRAINT FK_ENTRIES_ARCHIVE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION DROP CONSTRAINT FK_ORGANIZATION_ID;
GO
ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION DROP CONSTRAINT FK_ROLLUP_AUTHOR_ID;
GO
ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON DROP CONSTRAINT FK_ENTRY_ROLLUP_ACTION_ID;
GO
ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON DROP CONSTRAINT FK_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT FK_EXT_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT FK_EXT_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP CONSTRAINT FK_FOLLOWS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP CONSTRAINT FK_FS_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP CONSTRAINT FK_FS_RESOURCE_ID;
GO
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS DROP CONSTRAINT FK_MENT_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS DROP CONSTRAINT FK_MEN_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_NETWORK DROP CONSTRAINT FK_NETWORK_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_NETWORK DROP CONSTRAINT FK_NTW_COLL_ID;
GO
ALTER TABLE HOMEPAGE.NR_NETWORK DROP CONSTRAINT FK_NTW_PERS_ID;
GO
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP CONSTRAINT FK_C_COMMENT_ID;
GO
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP CONSTRAINT FK_NEWS_COMMENT_CONTENT_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT DROP CONSTRAINT FK_STATUS_COMMENT_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT DROP CONSTRAINT FK_STATUS_CONTENT_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK DROP CONSTRAINT FK_NEWS_STATUS_NETWORK_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS DROP CONSTRAINT FK_NOT_REC_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS DROP CONSTRAINT FK_REC_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS DROP CONSTRAINT FK_NOT_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS DROP CONSTRAINT FK_NOT_SENT_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW DROP CONSTRAINT FK_PRF_VIEW_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW DROP CONSTRAINT FK_PRO_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_READ_STATUS DROP CONSTRAINT FK_READ_STATUS_ORG;
GO
ALTER TABLE HOMEPAGE.NR_READ_STATUS DROP CONSTRAINT FK_READ_STATUS_PER;
GO
ALTER TABLE HOMEPAGE.NR_READ_STATUS DROP CONSTRAINT FK_READ_STATUS_STR;
GO
ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT FK_RESOURCE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_SAVED_READERS DROP CONSTRAINT FK_SAVED_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_SAVED_READERS DROP CONSTRAINT FK_SAV_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE DROP CONSTRAINT FK_SOURCE_TYPE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT FK_STA_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT FK_SU_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_STORIES DROP CONSTRAINT FK_ENTRY_ID;
GO
ALTER TABLE HOMEPAGE.NR_STORIES DROP CONSTRAINT FK_STORIES_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT DROP CONSTRAINT FK_STORIES_CONTENT_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS DROP CONSTRAINT FK_TOPICS_READERS_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS DROP CONSTRAINT FK_TOP_READERS_STR;
GO
ALTER TABLE HOMEPAGE.NT_REPLYTO DROP CONSTRAINT FK_REPLYTO_ORG_ID;
GO
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT DROP CONSTRAINT FK_REPLYTO_NOT_ID;
GO
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT DROP CONSTRAINT FK_REPLYTO_PER_ID;
GO
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT DROP CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID;
GO
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT DROP CONSTRAINT CLNT_FK;
GO
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT DROP CONSTRAINT CLNT_TOKEN_FK;
GO
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT DROP CONSTRAINT FK_OA1CL_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT AUTH_TOKEN_FK;
GO
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT CONTEXT_CLNT_FK;
GO
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT FK_OA1C_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.OAUTH2_CLIENT DROP CONSTRAINT FK_CLIENT_PRO_NAME;
GO
ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING DROP CONSTRAINT FK_BINDING_CLIENT;
GO
ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING DROP CONSTRAINT FK_BINDING_WIDGET;
GO
ALTER TABLE HOMEPAGE.OAUTH2_TOKEN DROP CONSTRAINT FK_OA2T_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.PERSON DROP CONSTRAINT FK_PERSON_ORG_ID;
GO
ALTER TABLE HOMEPAGE.PERSON_ROLE DROP CONSTRAINT FK_PERSON_ROLE_ORG_ID;
GO
ALTER TABLE HOMEPAGE.PERSON_ROLE DROP CONSTRAINT FK_PERSON_ROLE_PER_ID;
GO
ALTER TABLE HOMEPAGE.PREREQ DROP CONSTRAINT FK_PREREQ_ORG_ID;
GO
ALTER TABLE HOMEPAGE.PREREQ DROP CONSTRAINT FK_PREREQ_WIDGET;
GO
ALTER TABLE HOMEPAGE.SR_BACKUPTASKDEF DROP CONSTRAINT FK_BKUP_TASK_ID;
GO
ALTER TABLE HOMEPAGE.SR_FEEDBACK DROP CONSTRAINT FK_SRFB_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.SR_FEEDBACK_CONTEXT DROP CONSTRAINT FK_FBK_CTXT_ID;
GO
ALTER TABLE HOMEPAGE.SR_FEEDBACK_PARAMETERS DROP CONSTRAINT FK_FBK_PARAMS_ID;
GO
ALTER TABLE HOMEPAGE.SR_FILECONTENTINDEXINGTASK DROP CONSTRAINT FK_FCI_TASK_ID;
GO
ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF DROP CONSTRAINT FK_FC_TASK_ID;
GO
ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF DROP CONSTRAINT FK_INDEX_TASK_ID;
GO
ALTER TABLE HOMEPAGE.SR_NUMBER_STATS DROP CONSTRAINT FK_NUM_STAT_ID;
GO
ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF DROP CONSTRAINT FK_OPT_TASK_ID;
GO
ALTER TABLE HOMEPAGE.SR_RECOMMEND_CACHE_USERPROFILE DROP CONSTRAINT FK_RCUP_PERSON_ID;
GO
ALTER TABLE HOMEPAGE.SR_RESUME_TOKENS DROP CONSTRAINT FK_RT_IDX_MGMT_ID;
GO
ALTER TABLE HOMEPAGE.SR_SANDTASKDEF DROP CONSTRAINT FK_ST_TASK_ID;
GO
ALTER TABLE HOMEPAGE.SR_STRING_STATS DROP CONSTRAINT FK_STR_STAT_ID;
GO
ALTER TABLE HOMEPAGE.SR_TIMER_STATS DROP CONSTRAINT FK_TMR_STAT_ID;
GO
ALTER TABLE HOMEPAGE.WIDGET DROP CONSTRAINT FK_WIDGET_ORG_ID;
GO

COMMIT;
