-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------------------
-- HOMEPAGE.NR_CUSTOM_LIST
---------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_CUSTOM_LIST (
	CUSTOM_LIST_ID VARCHAR(36) CCSID 1208 NOT NULL,
	CUSTOM_LIST_NAME VARCHAR(1024) CCSID 1208 NOT NULL,
	CREATION_TIME TIMESTAMP NOT NULL,
	UPDATE_TIME TIMESTAMP NOT NULL,
	CUSTOM_LIST_SUMMARY VARCHAR(2048) CCSID 1208 ,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 NOT NULL,
	PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,
	STATE SMALLINT NOT NULL,
	PERSON_DISPLAY VARCHAR(36) CCSID 1208 
);

ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST 
  	ADD CONSTRAINT PK_CUSTOM_LIST_ID PRIMARY KEY(CUSTOM_LIST_ID);  

ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST
  	ADD CONSTRAINT FK_CUST_L_PER_ID FOREIGN KEY(PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST
  	ADD CONSTRAINT FK_CUST_L_PER_D_ID FOREIGN KEY(PERSON_DISPLAY) REFERENCES HOMEPAGE.PERSON (PERSON_ID);  	
  	
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST
  	ADD CONSTRAINT FK_CUST_L_ORG_ID FOREIGN KEY(ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
  	
CREATE INDEX HOMEPAGE.NR_CUSTOM_LIST_PER_ORG_IDX
	ON HOMEPAGE.NR_CUSTOM_LIST (PERSON_ID, ORGANIZATION_ID); 

CREATE INDEX HOMEPAGE.NR_CUSTOM_LIST_PER_D_IDX
	ON HOMEPAGE.NR_CUSTOM_LIST (PERSON_DISPLAY); 	

---------------------------------------------------------------
-- HOMEPAGE.NR_CUSTOM_LIST_ITEM
---------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM (
	CUSTOM_LIST_ITEM_ID VARCHAR(36) CCSID 1208 NOT NULL,
	CUSTOM_LIST_ID VARCHAR(36) CCSID 1208 NOT NULL,
	ITEM_ID VARCHAR(256) CCSID 1208 NOT NULL,
	CUSTOM_LIST_ITEM_NAME VARCHAR(1024) CCSID 1208 NOT NULL,
	CREATION_TIME TIMESTAMP NOT NULL,
	UPDATE_TIME TIMESTAMP NOT NULL,
	TYPE VARCHAR(256) CCSID 1208 NOT NULL,
	CUSTOM_LIST_ITEM_SUMMARY VARCHAR(2048) CCSID 1208 ,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 NOT NULL,
	STATE SMALLINT NOT NULL,
	PERSON_DISPLAY VARCHAR(36) CCSID 1208 
);

ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM 
  	ADD CONSTRAINT PK_CUSTOM_LIST_ITEM_ID PRIMARY KEY(CUSTOM_LIST_ITEM_ID);
  	
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM 
  	ADD CONSTRAINT FK_CUSTOM_LIST_ID FOREIGN KEY(CUSTOM_LIST_ID) REFERENCES HOMEPAGE.NR_CUSTOM_LIST (CUSTOM_LIST_ID);
  	
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM 
  	ADD CONSTRAINT FK_CUST_L_I_ORG_ID FOREIGN KEY(ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
  	
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM
  	ADD CONSTRAINT FK_CUST_L_I_PER_D_ID FOREIGN KEY(PERSON_DISPLAY) REFERENCES HOMEPAGE.PERSON (PERSON_ID);   	
  	
CREATE INDEX HOMEPAGE.NR_CUSTOM_LIST_ID_ORG_IDX
	ON HOMEPAGE.NR_CUSTOM_LIST_ITEM (CUSTOM_LIST_ID, ORGANIZATION_ID);
	
CREATE UNIQUE INDEX HOMEPAGE.NR_CUSTOM_LIST_ITEM_IDX_UNQ
	ON HOMEPAGE.NR_CUSTOM_LIST_ITEM (ITEM_ID, CUSTOM_LIST_ID);	
	
CREATE INDEX HOMEPAGE.NR_CUSTOM_LIST_ITEM_PER_D_IDX
	ON HOMEPAGE.NR_CUSTOM_LIST_ITEM (PERSON_DISPLAY);	
	
COMMIT;	

--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
-- 129719: Mentions or Update  page keep flashing on D32 exit build - IC10.0_Connections_20140716-1441


--ok
CREATE INDEX HOMEPAGE.TMP_PER_ORG_IDX ON HOMEPAGE.PERSON (ORGANIZATION_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TMP_2_IDX ON HOMEPAGE.LOGINNAME (PERSON_ID);
DELETE FROM HOMEPAGE.LOGINNAME WHERE PERSON_ID IN ( SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
DROP INDEX HOMEPAGE.TMP_2_IDX;
COMMIT;

-- warning
DELETE FROM HOMEPAGE.NR_NETWORK WHERE PERSON_ID IN ( SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

-- warning
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE PERSON_ID IN ( SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

-- warning
DELETE FROM HOMEPAGE.EMD_EMAIL_PREFS WHERE PERSON_ID IN ( SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

-- warnig
CREATE INDEX HOMEPAGE.TMP_UI_IDX ON HOMEPAGE.HP_UI (PERSON_ID);
COMMIT;

DELETE FROM HOMEPAGE.HP_TAB_INST WHERE UI_ID IN (SELECT UI_ID FROM HOMEPAGE.HP_UI WHERE PERSON_ID IN (SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a'));
COMMIT;

DELETE FROM HOMEPAGE.HP_WIDGET_INST WHERE TAB_INST_ID IN (
SELECT TAB_INST_ID FROM HOMEPAGE.HP_TAB_INST WHERE UI_ID IN (SELECT UI_ID FROM HOMEPAGE.HP_UI WHERE PERSON_ID IN (SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a'))
);
COMMIT;

DELETE FROM HOMEPAGE.HP_TAB_INST WHERE UI_ID IN (SELECT UI_ID FROM HOMEPAGE.HP_UI WHERE PERSON_ID IN (SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a'));
COMMIT;

DELETE FROM HOMEPAGE.HP_UI WHERE PERSON_ID IN (SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

DROP INDEX HOMEPAGE.TMP_UI_IDX;
COMMIT;

-- warnig
DELETE FROM HOMEPAGE.NR_COMM_FOLLOW WHERE PERSON_ID IN (SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

-- warnig
DELETE FROM HOMEPAGE.NR_COMM_PERSON_FOLLOW WHERE PERSON_ID IN (SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

-- warnig
DELETE FROM HOMEPAGE.BOARD_CURRENT_STATUS WHERE ACTOR_UUID IN ( SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

-- warnig
CREATE INDEX HOMEPAGE.TMP_BRD_OWNER_ASSOC_IDX ON HOMEPAGE.BOARD (BOARD_OWNER_ASSOC_ID);
COMMIT;

DELETE FROM HOMEPAGE.BOARD_ENTRIES WHERE CONTAINER_ID IN ( SELECT BOARD_CONTAINER_ID FROM HOMEPAGE.BOARD WHERE BOARD_OWNER_ASSOC_ID IN (SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a'));
COMMIT;

-- warnig
DELETE FROM HOMEPAGE.BOARD WHERE BOARD_OWNER_ASSOC_ID IN (SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

DROP INDEX HOMEPAGE.TMP_BRD_OWNER_ASSOC_IDX;
COMMIT;

-- ok
DELETE FROM HOMEPAGE.NR_AS_COUNTS WHERE PERSON_ID IN ( SELECT PERSON_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a');
COMMIT;

--ok
DELETE FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a'; 
COMMIT;

--ok
DELETE FROM HOMEPAGE.NR_SOURCE_TYPE WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a';
COMMIT;

--ok
DELETE FROM HOMEPAGE.MT_CFG_SETTINGS WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a';
COMMIT;

--ok
DELETE FROM HOMEPAGE.MT_ORGANIZATION WHERE ORGANIZATION_ID = '00000000-0000-0000-0000-040508202233' OR ORGANIZATION_ID = 'a';
COMMIT;

DROP INDEX HOMEPAGE.TMP_PER_ORG_IDX;
COMMIT;
