-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}



---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 460 -----------------------------------
---------------------------------------------------------------------------------

-----------------------------------------------------------
-- [START] 98254: fixup460 remove MAX_UPDATE_FOR_READER	
-----------------------------------------------------------

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_TAGS_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_SAVED_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_FILES_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS DROP COLUMN MAX_UPDATE_FOR_READER;
COMMIT;

--REORG TABLE HOMEPAGE.NR_WIKIS_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_TOPICS_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_TAGS_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_SAVED_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_RESPONSES_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_PROFILES_VIEW;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_PROFILES_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_MENTIONS_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_FORUMS_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_FILES_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_EXTERNAL_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_DISCOVERY_VIEW;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_COMMUNITIES_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_BOOKMARKS_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_BLOGS_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_AGGREGATED_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_ACTIVITIES_READERS;
--COMMIT;

--REORG TABLE HOMEPAGE.NR_ACTIONABLE_READERS;
--COMMIT;

-----------------------------------------------------------
-- [END] 98254: fixup460 remove MAX_UPDATE_FOR_READER	
-----------------------------------------------------------

-----------------------------------------------------------
-- [START] 98252:  [fixup460] create the new table NR_AS_COUNTS
-----------------------------------------------------------


-----------------------------------------------------------
-- HOMEPAGE.NR_AS_COUNTS
-----------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_AS_COUNTS (
	AS_COUNT_ID VARCHAR(36) CCSID 1208 NOT NULL,
	PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,	
	UI_VIEW SMALLINT,
	COUNT INTEGER,
	ORGANIZATION_ID VARCHAR (36) CCSID 1208 NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'
)	
;

ALTER TABLE HOMEPAGE.NR_AS_COUNTS 
  	ADD CONSTRAINT PK_AS_COUNT_ID PRIMARY KEY (AS_COUNT_ID);
  	
ALTER TABLE HOMEPAGE.NR_AS_COUNTS
    ADD CONSTRAINT FK_AS_COUNT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
    
ALTER TABLE HOMEPAGE.NR_AS_COUNTS
    ADD CONSTRAINT FK_AS_COUNT_PER_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID);    

CREATE UNIQUE INDEX HOMEPAGE.NR_COUNT_PER_VIEW_UNQ 
	ON HOMEPAGE.NR_AS_COUNTS (PERSON_ID, UI_VIEW);
	
CREATE INDEX HOMEPAGE.NR_AS_COUNT_PER_IDX
	ON HOMEPAGE.NR_AS_COUNTS (PERSON_ID);
	
CREATE INDEX HOMEPAGE.NR_AS_COUNT_ORG_IDX
	ON HOMEPAGE.NR_AS_COUNTS (ORGANIZATION_ID);	
	
COMMIT;

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_AS_COUNTS TO LCUSER;
COMMIT;

--runstats on table HOMEPAGE.NR_AS_COUNTS with distribution and detailed indexes all allow write access;



-----------------------------------------------------------
-- [END] 98252:  [fixup460] create the new table NR_AS_COUNTS
-----------------------------------------------------------

--98630: [fixup460] IMG_CACHE  table Create a new field to store HASH values for the URL. That field need to be indexed. 
DELETE FROM HOMEPAGE.IMG_CACHE;
COMMIT;

ALTER TABLE HOMEPAGE.IMG_CACHE ADD ORIGINAL_URL_MD5 char(32) CCSID 1208 DEFAULT '' NOT NULL;
COMMIT;


ALTER TABLE  HOMEPAGE.IMG_CACHE ALTER ORIGINAL_URL_MD5 DROP DEFAULT;
COMMIT;

CREATE INDEX HOMEPAGE.IMG_CACHE_URL_IDX
	ON HOMEPAGE.IMG_CACHE (ORIGINAL_URL_MD5, ORGANIZATION_ID);
COMMIT;

--REORG TABLE HOMEPAGE.IMG_CACHE;
--COMMIT;
	


---------------------------------------------------------------------------------
------------------------ END   NEWS FIXUP 460 -------------------------------------
---------------------------------------------------------------------------------
