-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 451 -----------------------------------
---------------------------------------------------------------------------------

-- 89208: Remove DEFAULT constraints from BOARD tables: BOARD,  BOARD_COMMENTS, BOARD_CURRENT_STATUS 
-- BOARD_ENTRIES, BOARD_MENTIONS, BOARD_OBJECT_REFERENCE, BOARD_RECOMMENDATIONS 
ALTER TABLE HOMEPAGE.BOARD ALTER COLUMN ORGANIZATION_ID DROP DEFAULT;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_COMMENTS ALTER COLUMN ORGANIZATION_ID DROP DEFAULT;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS ALTER COLUMN ORGANIZATION_ID DROP DEFAULT;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_ENTRIES ALTER COLUMN ORGANIZATION_ID DROP DEFAULT;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_MENTIONS ALTER COLUMN ORGANIZATION_ID DROP DEFAULT;
COMMIT;

CREATE TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE_TEMP (
	OBJECT_ID VARCHAR(47) CCSID 1208 NOT NULL,
	ITEM_ID VARCHAR(47) CCSID 1208 NOT NULL,
	DISPLAY_NAME VARCHAR(2048) CCSID 1208,
	IMAGE_NAME   VARCHAR(2048) CCSID 1208,
	NAME VARCHAR(512) CCSID 1208, 
	URL VARCHAR(1024) CCSID 1208, 
	CONTENT VARCHAR(4000) CCSID 1208,
	IMAGE_URL VARCHAR(1024) CCSID 1208,
	SOURCE  VARCHAR(36) CCSID 1208,
	SOURCE_TYPE  SMALLINT,
	CREATION_DATE TIMESTAMP,
	MIME_TYPE VARCHAR(36) CCSID 1208,
	AUTHOR_ID VARCHAR(36) CCSID 1208,
	AUTHOR_DISPLAY_NAME VARCHAR(256) CCSID 1208,
	OBJECT_META_DATA VARCHAR(4000) CCSID 1208,
	OBJECT_META_DATA_2 VARCHAR(4000) CCSID 1208,
	FULL_OBJECT_META_DATA CLOB CCSID 1208,
	OBJECT_EXTERNAL_ID VARCHAR(256) CCSID 1208,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
);
COMMIT;

-- Copy data
INSERT INTO HOMEPAGE.BOARD_OBJECT_REFERENCE_TEMP(OBJECT_ID, ITEM_ID, DISPLAY_NAME, IMAGE_NAME, NAME, URL, CONTENT, IMAGE_URL, SOURCE, SOURCE_TYPE, CREATION_DATE, MIME_TYPE, AUTHOR_ID, AUTHOR_DISPLAY_NAME, OBJECT_META_DATA, OBJECT_META_DATA_2, FULL_OBJECT_META_DATA, OBJECT_EXTERNAL_ID, ORGANIZATION_ID) 
	SELECT OBJECT_ID, ITEM_ID, DISPLAY_NAME, IMAGE_NAME, NAME, URL, CONTENT, IMAGE_URL, SOURCE, SOURCE_TYPE, CREATION_DATE, MIME_TYPE, AUTHOR_ID, AUTHOR_DISPLAY_NAME, OBJECT_META_DATA, OBJECT_META_DATA_2, FULL_OBJECT_META_DATA, OBJECT_EXTERNAL_ID, ORGANIZATION_ID  
	FROM HOMEPAGE.BOARD_OBJECT_REFERENCE;
COMMIT;

-- Drop constraints
--ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP FOREIGN KEY "HOMEPAGE".FK_BRD_OBJ_ENTRY;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP FOREIGN KEY "HOMEPAGE".FK_BRD_AUTHOR_ID;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP FOREIGN KEY "HOMEPAGE".FK_BRD_OBJ_REFERENCE_ORG_ID;

DROP INDEX HOMEPAGE.BRD_ENTRY_IDX;

DROP INDEX HOMEPAGE.BRD_AUTHOR_IDX;
COMMIT;

-- Drop old table	
DROP TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE;
COMMIT;

-- Rename new table name to old name
RENAME TABLE BOARD_OBJECT_REFERENCE_TEMP TO BOARD_OBJECT_REFERENCE;
COMMIT;

-- Recreate constraints
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE 
    ADD CONSTRAINT "HOMEPAGE".PK_BRD_OBJ_ID PRIMARY KEY(OBJECT_ID);

/*
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT "HOMEPAGE".FK_BRD_OBJ_ENTRY FOREIGN KEY (ITEM_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);
*/
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT "HOMEPAGE".FK_BRD_AUTHOR_ID FOREIGN KEY (AUTHOR_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE 
	ADD CONSTRAINT HOMEPAGE.FK_BRD_OBJ_REFERENCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) 
	REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BRD_AUTHOR_IDX
    ON HOMEPAGE.BOARD_OBJECT_REFERENCE (AUTHOR_ID);   
COMMIT;

CREATE INDEX HOMEPAGE.BRD_ENTRY_IDX
    ON HOMEPAGE.BOARD_OBJECT_REFERENCE (ITEM_ID);
COMMIT;

--Grant access to LCUSER on newly created table
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.BOARD_OBJECT_REFERENCE TO LCUSER;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE ALTER COLUMN ORGANIZATION_ID DROP DEFAULT;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS ALTER COLUMN ORGANIZATION_ID DROP DEFAULT;
COMMIT;


-- 89815: Query vs DISCOVERY and PROFILE_VIEW - need to review the access plan and study indexes to use ORGANIZATION_ID
-- NEW DISCOVERY_VIEW index for SC to support public reads
CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_ORG_IDX 
   	ON HOMEPAGE.NR_DISCOVERY_VIEW (ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, CREATION_DATE, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;

-- NEW PROFILES_VIEW index for SC to support public reads
CREATE INDEX HOMEPAGE.PROFILES_VIEW_ORG_IDX 
   	ON HOMEPAGE.NR_PROFILES_VIEW (ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, CREATION_DATE, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;   	
   	

---------------------------------------------------------------------------------
------------------------ END   NEWS FIXUP 451 -------------------------------------
---------------------------------------------------------------------------------

 

  
  
  
