-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2015                                   
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}


-------------------------------------------------------
-- Add ORGANIZATION_ID to STR_RDR indexes
-------------------------------------------------------
DROP INDEX HOMEPAGE.AGGREGATED_READERS_STR_RDR;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.AGGREGATED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, READER_ID, CONTAINER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT; 

DROP INDEX HOMEPAGE.STATUS_READERS_STR_RDR;
COMMIT;

CREATE UNIQUE  INDEX HOMEPAGE.STATUS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT; 

DROP INDEX HOMEPAGE.EXTERNAL_READERS_STR_RDR;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.EXTERNAL_READERS_STR_RDR 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT;

DROP INDEX HOMEPAGE.ACTIONABLE_READERS_STR_RDR;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.ACTIONABLE_READERS_STR_RDR 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT; 

DROP INDEX HOMEPAGE.PROFILES_VIEW_STR_RDR;
COMMIT;

CREATE UNIQUE  INDEX HOMEPAGE.PROFILES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT; 

DROP INDEX HOMEPAGE.NOTIFICA_READERS_STR_RDR;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NOTIFICA_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT;  

DROP INDEX HOMEPAGE.NOT_REC_READERS_STR_RDR;
COMMIT;

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT; 

DROP INDEX HOMEPAGE.SAVED_READERS_STR_RDR;
COMMIT;

CREATE UNIQUE  INDEX HOMEPAGE.SAVED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT;  

DROP INDEX HOMEPAGE.TOPICS_READERS_STR_RDR;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.TOPICS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT;

DROP INDEX HOMEPAGE.MENTIONS_READERS_STR_RDR;
COMMIT;

CREATE UNIQUE  INDEX HOMEPAGE.MENTIONS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_MENTIONS_READERS (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT;

DROP INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_RDR;
COMMIT;

CREATE UNIQUE  INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, READER_ID, CATEGORY_TYPE, ORGANIZATION_ID); 
COMMIT; 


-------------------------------------------------
-- SCEE: Add new table HOMEPAGE.L3T_EXT_POINTS
-------------------------------------------------
CREATE TABLE HOMEPAGE.L3T_EXT_POINTS (
		EXT_POINT_ID VARCHAR(36) CCSID 1208 NOT NULL,
		NAME VARCHAR(256) CCSID 1208 NOT NULL,
		SERVICE VARCHAR(128) CCSID 1208 NOT NULL,
		EXT_TYPE VARCHAR(128) CCSID 1208 NOT NULL,
		DESCRIPTION VARCHAR(512) CCSID 1208 
);

ALTER TABLE HOMEPAGE.L3T_EXT_POINTS ADD CONSTRAINT HOMEPAGE.PK_EXT_POINT_ID PRIMARY KEY (EXT_POINT_ID);
