-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-----------------------------------------------------------------------
-- ADDING new HOMEPAGE.MT_ORGANIZATION table
-----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.MT_ORGANIZATION (
    ORGANIZATION_ID VARCHAR (36) CCSID 1208 NOT NULL,
    ORGANIZATION_EXID VARCHAR (36) CCSID 1208
);

ALTER TABLE HOMEPAGE.MT_ORGANIZATION
    ADD CONSTRAINT HOMEPAGE.PK_ORGANIZATION_ID PRIMARY KEY(ORGANIZATION_ID);

CREATE UNIQUE INDEX HOMEPAGE.UNQ_ORG_EXID
	ON HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_EXID);	

------------------------------------------------
-- PERSON
------------------------------------------------
CREATE TABLE HOMEPAGE.PERSON  (
		  PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,
		  DISPLAYNAME VARCHAR(256) CCSID 1208 NOT NULL,
		  EXID VARCHAR(256) CCSID 1208 NOT NULL,
		  USER_MAIL VARCHAR(256) CCSID 1208,
		  USER_MAIL_LOWER VARCHAR(256) CCSID 1208,
		  DISPLAYNAME_LOWER VARCHAR(256) CCSID 1208,
		  STATE SMALLINT DEFAULT 0 NOT NULL,
		  LAST_UPDATE TIMESTAMP,
		  SAND_OPT SMALLINT DEFAULT 1,
		  SAND_LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
		  PROF_TYPE VARCHAR(128) CCSID 1208,
		  CREATION_DATE TIMESTAMP,
		  THEME_ID VARCHAR(36) CCSID 1208,
		  COMM_VISIBILITY SMALLINT,
		  MEMBER_TYPE SMALLINT DEFAULT 0 NOT NULL,
		  ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000',
		  COMMUNITY_INTERNAL_ONLY SMALLINT DEFAULT 1,
		  LAST_CONN_VISIT TIMESTAMP,
		  PREF_LANG VARCHAR(5) CCSID 1208,
		  IS_EXTERNAL SMALLINT DEFAULT 0 NOT NULL,
		  HOME_ORG_ID VARCHAR(36) CCSID 1208
);

ALTER TABLE HOMEPAGE.PERSON 
    ADD CONSTRAINT "HOMEPAGE"."PK_PERSON_ID" PRIMARY KEY("PERSON_ID");

ALTER TABLE HOMEPAGE.PERSON ADD CONSTRAINT HOMEPAGE.FK_PERSON_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE UNIQUE INDEX HOMEPAGE.PERSON_EXID_ORG
    ON HOMEPAGE.PERSON (EXID, ORGANIZATION_ID);

CREATE INDEX HOMEPAGE.PERSON_EMD_CHECK 
	ON HOMEPAGE.PERSON (MEMBER_TYPE, CREATION_DATE ASC, STATE, USER_MAIL_LOWER, PERSON_ID, ORGANIZATION_ID);

CREATE INDEX HOMEPAGE.PERSON_USER_MAIL_LWR
    ON HOMEPAGE.PERSON(USER_MAIL_LOWER ASC);

CREATE INDEX HOMEPAGE.PERSON_DISPLAYNAME_LWR
    ON HOMEPAGE.PERSON(DISPLAYNAME_LOWER ASC);

CREATE INDEX HOMEPAGE.PERSON_LAST_UPDATE
    ON HOMEPAGE.PERSON(LAST_UPDATE DESC);    

CREATE INDEX HOMEPAGE.PERSON_SAND_LAST_UPDATE
    ON HOMEPAGE.PERSON(SAND_LAST_UPDATE ASC);

CREATE UNIQUE INDEX HOMEPAGE.PERSON_IDX   
	ON HOMEPAGE.PERSON (PERSON_ID, USER_MAIL, DISPLAYNAME);
	
CREATE INDEX HOMEPAGE.DISPLAYNAME_LOWER_MEM
	ON HOMEPAGE.PERSON (DISPLAYNAME_LOWER, MEMBER_TYPE);	

CREATE INDEX HOMEPAGE.PERSON_EXID_PER_ID_IX
	ON HOMEPAGE.PERSON  (EXID, PERSON_ID);

CREATE INDEX HOMEPAGE.PERSON_STATE_MEM_LU_IX
	ON HOMEPAGE.PERSON  (STATE, MEMBER_TYPE,LAST_UPDATE);

CREATE INDEX HOMEPAGE.PERSON_MEM_STATE_IX
	ON HOMEPAGE.PERSON  (MEMBER_TYPE,STATE);

CREATE INDEX HOMEPAGE.PERSON_MEM_SAND_IX
	ON HOMEPAGE.PERSON  (MEMBER_TYPE,SAND_OPT);
	
CREATE INDEX HOMEPAGE.PERSON_SND_SR 
	ON HOMEPAGE.PERSON (MEMBER_TYPE, SAND_OPT, SAND_LAST_UPDATE ASC);
	
CREATE INDEX HOMEPAGE.PERSON_SAND_OPT_IDX
    ON HOMEPAGE.PERSON(SAND_OPT, SAND_LAST_UPDATE ASC);
    

CREATE INDEX HOMEPAGE.PERSON_STATE_IDX
  ON HOMEPAGE.PERSON(MEMBER_TYPE, LAST_UPDATE ASC, STATE, PERSON_ID); 
	
CREATE INDEX HOMEPAGE.PERSON_LAST_CONN_VISIT
    ON HOMEPAGE.PERSON(LAST_CONN_VISIT DESC);

--RUNSTATS ON TABLE "HOMEPAGE"."PERSON" FOR INDEXES ALL;

----------------------------
-- PERSON_ROLE
----------------------------

CREATE TABLE HOMEPAGE.PERSON_ROLE  (
	PERSON_ROLE_ID VARCHAR(36) CCSID 1208 NOT NULL,
	ROLE VARCHAR(256) CCSID 1208 NOT NULL,
	PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.PERSON_ROLE 
    ADD CONSTRAINT HOMEPAGE.PK_PERSON_ROLE_ID PRIMARY KEY("PERSON_ROLE_ID");
    
ALTER TABLE HOMEPAGE.PERSON_ROLE ADD CONSTRAINT HOMEPAGE.FK_PERSON_ROLE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

ALTER TABLE HOMEPAGE.PERSON_ROLE ADD CONSTRAINT HOMEPAGE.FK_PERSON_ROLE_PER_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID);

CREATE INDEX HOMEPAGE.PERSON_ROLE_PER_IDX
    ON HOMEPAGE.PERSON_ROLE (PERSON_ID);
    
CREATE INDEX HOMEPAGE.PERSON_ROLE_PER_R_IDX
    ON HOMEPAGE.PERSON_ROLE (PERSON_ID, PERSON_ROLE_ID);
    
CREATE UNIQUE INDEX HOMEPAGE.PERSON_ROLE_ROLE_IDX
    ON HOMEPAGE.PERSON_ROLE (PERSON_ID, ROLE);

-- LL requirement
------------------------------------------------
-- SNCORE_PERSON
------------------------------------------------
CREATE VIEW HOMEPAGE.SNCORE_PERSON (SNC_INTERNAL_ID, SNC_IDKEY, SNC_EMAIL_LOWER, SNC_DISPLAY_NAME) 
    AS SELECT PERSON_ID, EXID, USER_MAIL_LOWER, DISPLAYNAME FROM HOMEPAGE.PERSON;

-----------------------------------------
-- HOMEPAGE.USER_PREFS
-----------------------------------------
CREATE TABLE HOMEPAGE.HP_USER_PREFS (
	USER_PREFS_ID VARCHAR(36) CCSID 1208 NOT NULL,
	PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,
	PREF_NAME VARCHAR(400) CCSID 1208,
	PREF_VALUE VARCHAR(1536) CCSID 1208,
	LAST_UPDATE TIMESTAMP,
	CREATE_DATE TIMESTAMP,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
);

ALTER TABLE HOMEPAGE.HP_USER_PREFS
    ADD CONSTRAINT HOMEPAGE.PK_USER_PREFS_ID PRIMARY KEY(USER_PREFS_ID);

ALTER TABLE HOMEPAGE.HP_USER_PREFS 
	ADD CONSTRAINT HOMEPAGE.FK_USER_PREFS_PERS_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID);
	
ALTER TABLE HOMEPAGE.HP_USER_PREFS 
	ADD CONSTRAINT HOMEPAGE.FK_USER_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE INDEX HOMEPAGE.USER_PREF_NAME_IDX
	ON HOMEPAGE.HP_USER_PREFS (PREF_NAME);

CREATE INDEX HOMEPAGE.USER_PREF_PER_IDX
	ON  HOMEPAGE.HP_USER_PREFS (PERSON_ID);

CREATE UNIQUE INDEX HOMEPAGE.USER_PREF_PER_NAME_UNQ
	ON  HOMEPAGE.HP_USER_PREFS (PERSON_ID, PREF_NAME);
	
COMMIT;
	
------------------------------------------------
-- LOGINAME
------------------------------------------------
CREATE TABLE HOMEPAGE.LOGINNAME (
	PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,
	LOGINNAME VARCHAR(256) CCSID 1208 NOT NULL,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT "HOMEPAGE"."PK_LOGINNAME_ID" PRIMARY KEY ("PERSON_ID","LOGINNAME");

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT "HOMEPAGE"."FK_LN_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON("PERSON_ID");

ALTER TABLE HOMEPAGE.LOGINNAME ADD CONSTRAINT HOMEPAGE.FK_LN_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);	

CREATE UNIQUE INDEX HOMEPAGE.LOGINNAME_UNIQUE
    ON HOMEPAGE.LOGINNAME (LOGINNAME, ORGANIZATION_ID);

--RUNSTATS ON TABLE "HOMEPAGE"."LOGINNAME" FOR INDEXES ALL;

------------------------------------------------
-- HP_UI
------------------------------------------------
CREATE TABLE HOMEPAGE.HP_UI  (
	UI_ID VARCHAR(36) CCSID 1208 NOT NULL,
	PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,
	PERSON_LANG VARCHAR(5) CCSID 1208 NOT NULL,
	LAST_VISIT TIMESTAMP NOT NULL,
	WELCOME_MODE SMALLINT DEFAULT 1 NOT NULL,
	SHOW_DISABLED_WIDGETS SMALLINT DEFAULT 0 NOT NULL,
	LAST_NOTIFY_VISIT TIMESTAMP,
	LAST_ACTIONABLE_VISIT TIMESTAMP,
	WELCOME_NOTE SMALLINT DEFAULT 1,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.HP_UI
   ADD CONSTRAINT "HOMEPAGE"."PK_HP_UI" PRIMARY KEY("UI_ID");
       
ALTER TABLE HOMEPAGE.HP_UI
	ADD CONSTRAINT "HOMEPAGE"."FK_UI_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON("PERSON_ID");	

ALTER TABLE HOMEPAGE.HP_UI ADD CONSTRAINT HOMEPAGE.FK_UI_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE UNIQUE INDEX HOMEPAGE.HP_UI_PERSONID
   ON HOMEPAGE.HP_UI (PERSON_ID, PERSON_LANG);
	
CREATE INDEX HOMEPAGE.HP_UI_R
	ON HOMEPAGE.HP_UI (LAST_VISIT);	
	
	
--RUNSTATS ON TABLE "HOMEPAGE"."HP_UI" FOR INDEXES ALL;

------------------------------------------------
-- HP_TAB
------------------------------------------------	
CREATE TABLE HOMEPAGE.HP_TAB  (
	TAB_ID VARCHAR(36) CCSID 1208 NOT NULL,
	DEFAULT_NAME VARCHAR(36) CCSID 1208 NOT NULL,
	DEFAULT_N_COLUMNS SMALLINT,
	IS_NAME_CHANGEABLE SMALLINT,
	ENABLED SMALLINT DEFAULT 1,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.HP_TAB
    ADD CONSTRAINT "HOMEPAGE"."PK_HP_TAB" PRIMARY KEY("TAB_ID");

ALTER TABLE HOMEPAGE.HP_TAB ADD CONSTRAINT HOMEPAGE.FK_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

--RUNSTATS ON TABLE "HOMEPAGE"."HP_TAB" FOR INDEXES ALL;

------------------------------------------------
-- HP_TAB_INST
------------------------------------------------
CREATE TABLE HOMEPAGE.HP_TAB_INST  (
	TAB_INST_ID VARCHAR(36) CCSID 1208 NOT NULL,
	TAB_ID VARCHAR(36) CCSID 1208 NOT NULL,
	UI_ID VARCHAR(36) CCSID 1208 NOT NULL,
	TAB_NAME VARCHAR(36) CCSID 1208,
	N_COLUMNS SMALLINT,
	LAST_MODIFIED TIMESTAMP NOT NULL,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.HP_TAB_INST
	ADD CONSTRAINT "HOMEPAGE"."PK_HP_TAB_INST" PRIMARY KEY("TAB_INST_ID");
    
ALTER TABLE HOMEPAGE.HP_TAB_INST
	ADD CONSTRAINT "HOMEPAGE"."FK_UI_ID" FOREIGN KEY ("UI_ID")
	REFERENCES HOMEPAGE.HP_UI("UI_ID");
	
ALTER TABLE HOMEPAGE.HP_TAB_INST
    ADD CONSTRAINT "HOMEPAGE"."FK_TAB_INST_TAB_ID" FOREIGN KEY ("TAB_ID")
	REFERENCES HOMEPAGE.HP_TAB("TAB_ID");

ALTER TABLE HOMEPAGE.HP_TAB_INST ADD CONSTRAINT HOMEPAGE.FK_TAB_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE INDEX HOMEPAGE.TAB_INST_UI_ID_IDX 
	ON HOMEPAGE.HP_TAB_INST(UI_ID);
	
CREATE INDEX HOMEPAGE.TAB_INST_TAB_ID 
	ON HOMEPAGE.HP_TAB_INST (TAB_ID);	

CREATE UNIQUE INDEX HOMEPAGE.HP_TAB_INST_UNQ 
	ON HOMEPAGE.HP_TAB_INST (TAB_ID, UI_ID);	

--RUNSTATS ON TABLE "HOMEPAGE"."HP_TAB_INST" FOR INDEXES ALL;			

------------------------------------------------
-- WIDGET
------------------------------------------------
CREATE TABLE HOMEPAGE.WIDGET (
		WIDGET_ID VARCHAR(36) CCSID 1208 NOT NULL,
		WIDGET_TITLE VARCHAR(256) CCSID 1208 NOT NULL,
		WIDGET_TEXT VARCHAR(256) CCSID 1208,
		WIDGET_URL VARCHAR(256) CCSID 1208 NOT NULL,
		WIDGET_ICON VARCHAR(256) CCSID 1208,
		WIDGET_ENABLED SMALLINT DEFAULT 0 NOT NULL,
		WIDGET_SYSTEM SMALLINT DEFAULT 0 NOT NULL,
		WIDGET_HOMEPAGE_SPECIFIC SMALLINT DEFAULT 0 NOT NULL,
		WIDGET_PREVIEW_IMAGE VARCHAR(256) CCSID 1208,
		WIDGET_CATEGORY VARCHAR(36) CCSID 1208 DEFAULT ' ' NOT NULL,
		WIDGET_IS_DEFAULT_OPENED SMALLINT DEFAULT 0 NOT NULL,
		WIDGET_MULTIPLE_INSTANCES SMALLINT DEFAULT 0 NOT NULL,		
		WIDGET_MARKED_CACHABLE SMALLINT DEFAULT 0 NOT NULL,
		WIDGET_SECURE_URL VARCHAR(256) CCSID 1208 DEFAULT '',
		WIDGET_SECURE_ICON VARCHAR(256) CCSID 1208 DEFAULT '',
		IS_GADGET SMALLINT DEFAULT 0,
		WIDGET_POLICY_FLAGS INTEGER DEFAULT 1 NOT NULL,
		WIDGET_EXT_PROPERTIES VARCHAR(2048) CCSID 1208, 
		PROXY_POLICY VARCHAR(64) CCSID 1208 DEFAULT 'custom' NOT NULL,
		SHARE_ORDER INTEGER DEFAULT -1 NOT NULL,
		SERVER_ACCESS CLOB CCSID 1208,
		ADDITIONAL_FEATURES CLOB CCSID 1208,
		ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.WIDGET 
	ADD CONSTRAINT "HOMEPAGE"."PK_WIDGET" PRIMARY KEY ("WIDGET_ID");

ALTER TABLE HOMEPAGE.WIDGET ADD CONSTRAINT HOMEPAGE.FK_WIDGET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);	

--RUNSTATS ON TABLE "HOMEPAGE"."WIDGET" FOR INDEXES ALL;

------------------------------------------------
-- HP_WIDGET_TAB
------------------------------------------------
CREATE TABLE HOMEPAGE.HP_WIDGET_TAB (
	WIDGET_TAB_ID VARCHAR(36) CCSID 1208 NOT NULL,
	WIDGET_ID VARCHAR(36) CCSID 1208 NOT NULL,
	TAB_ID VARCHAR(36) CCSID 1208 NOT NULL,
	TYPE VARCHAR(36) CCSID 1208 NOT NULL,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)	
;

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB 
	ADD CONSTRAINT "HOMEPAGE"."PK_WIDGET_TAB" PRIMARY KEY ("WIDGET_TAB_ID");

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB	
    ADD CONSTRAINT "HOMEPAGE"."FK_WID_TAB_WID_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES HOMEPAGE.WIDGET("WIDGET_ID");

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB	
    ADD CONSTRAINT "HOMEPAGE"."FK_WID_TAB_TAB_ID" FOREIGN KEY ("TAB_ID")
	REFERENCES HOMEPAGE.HP_TAB("TAB_ID");	

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ADD CONSTRAINT HOMEPAGE.FK_WIDGET_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

--RUNSTATS ON TABLE "HOMEPAGE"."HP_WIDGET_TAB" FOR INDEXES ALL;

------------------------------------------------
-- HP_WIDGET_INST
------------------------------------------------	
CREATE TABLE HOMEPAGE.HP_WIDGET_INST  (
	WIDGET_INST_ID VARCHAR(36) CCSID 1208 NOT NULL,
	WIDGET_ID VARCHAR(36) CCSID 1208 NOT NULL,
	TAB_INST_ID VARCHAR(36) CCSID 1208 NOT NULL,
	WIDGET_SETTING VARCHAR(2048) CCSID 1208,
	CONTAINER VARCHAR(36) CCSID 1208,
	ORDER_SEQUENCE SMALLINT,
	IS_FIXED SMALLINT,
	IS_TOGGLED SMALLINT,
	LAST_MODIFIED TIMESTAMP NOT NULL,
	LAST_UPDATED TIMESTAMP,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
	ADD CONSTRAINT "HOMEPAGE"."PK_HP_WIDGET_INST" PRIMARY KEY ("WIDGET_INST_ID");

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
    ADD CONSTRAINT "HOMEPAGE"."FK_WIDGET_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES HOMEPAGE.WIDGET ("WIDGET_ID");
	
ALTER TABLE HOMEPAGE.HP_WIDGET_INST
    ADD CONSTRAINT "HOMEPAGE"."FK_TAB_INST_ID" FOREIGN KEY ("TAB_INST_ID")
	REFERENCES HOMEPAGE.HP_TAB_INST("TAB_INST_ID");

ALTER TABLE HOMEPAGE.HP_WIDGET_INST ADD CONSTRAINT HOMEPAGE.FK_WIDGET_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

CREATE INDEX HOMEPAGE.WIDGET_INST
	ON HOMEPAGE.HP_WIDGET_INST(TAB_INST_ID ASC, WIDGET_ID ASC);	

CREATE INDEX HOMEPAGE.HP_WIDGET_INST_TAB_INST_ID_IDX
	ON HOMEPAGE.HP_WIDGET_INST(TAB_INST_ID);
	
CREATE INDEX HOMEPAGE.HP_WIDGET_IDX 
	ON HOMEPAGE.HP_WIDGET_INST (WIDGET_ID);	

--RUNSTATS ON TABLE "HOMEPAGE"."HP_WIDGET_INST" FOR INDEXES ALL;					

------------------------------------------------
-- PREREQ
------------------------------------------------
CREATE TABLE HOMEPAGE.PREREQ (
		PREREQ_ID VARCHAR(36) CCSID 1208 NOT NULL,
		APP_ID VARCHAR(36) CCSID 1208 NOT NULL,
		WIDGET_ID VARCHAR(36) CCSID 1208 NOT NULL,
		ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.PREREQ 
	ADD CONSTRAINT "HOMEPAGE"."PK_PREREQ" PRIMARY KEY ("PREREQ_ID");

ALTER TABLE HOMEPAGE.PREREQ 
	ADD CONSTRAINT "HOMEPAGE"."FK_PREREQ_WIDGET" FOREIGN KEY ("WIDGET_ID")
	REFERENCES HOMEPAGE.WIDGET ("WIDGET_ID")
	ON DELETE CASCADE;	

ALTER TABLE HOMEPAGE.PREREQ ADD CONSTRAINT HOMEPAGE.FK_PREREQ_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

--RUNSTATS ON TABLE "HOMEPAGE"."PREREQ" FOR INDEXES ALL;
	
----------------------------------------------------------------------
-- HOMEPAGE.NT_REPLYTO
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NT_REPLYTO (
	REPLYTO_NOTIFICATION_ID VARCHAR(36) CCSID 1208 NOT NULL,
	SOURCE VARCHAR(36) CCSID 1208,
	EVENT_NAME VARCHAR(256) CCSID 1208 NOT NULL,
	CONTAINER_ID VARCHAR(256) CCSID 1208,	
	ITEM_ID VARCHAR(36) CCSID 1208,
	ITEM_CORRELATION_ID VARCHAR(256) CCSID 1208,	
	CREATION_DATE TIMESTAMP NOT NULL,
	ACTOR_UUID VARCHAR(36) CCSID 1208,
	EVENT_RECORD_UUID VARCHAR(36) CCSID 1208 NOT NULL,
	CATEGORY_TYPE SMALLINT,
	SOURCE_TYPE SMALLINT,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.NT_REPLYTO
    	ADD CONSTRAINT "HOMEPAGE".PK_REPLYTO PRIMARY KEY(REPLYTO_NOTIFICATION_ID);

ALTER TABLE HOMEPAGE.NT_REPLYTO ADD CONSTRAINT HOMEPAGE.FK_REPLYTO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

----------------------------------------------------------------------
-- HOMEPAGE.NT_REPLYTO_RECIPIENT
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT (
	REPLYTO_RECIPIENT_ID VARCHAR(36) CCSID 1208 NOT NULL,
	REPLYTO_NOTIFICATION_ID VARCHAR(36) CCSID 1208 NOT NULL,
	PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,	
	REPLYTO_ID VARCHAR(36) CCSID 1208 NOT NULL,
	LAST_UPDATE TIMESTAMP,
	ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD CONSTRAINT "HOMEPAGE".REPLYTO_RECIP_ID PRIMARY KEY(REPLYTO_RECIPIENT_ID);

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD CONSTRAINT "HOMEPAGE".FK_REPLYTO_NOT_ID FOREIGN KEY (REPLYTO_NOTIFICATION_ID)
	REFERENCES HOMEPAGE.NT_REPLYTO (REPLYTO_NOTIFICATION_ID);

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD CONSTRAINT "HOMEPAGE".FK_REPLYTO_PER_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ADD CONSTRAINT HOMEPAGE.FK_REPLYTO_RECIPIENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);	

CREATE UNIQUE INDEX HOMEPAGE.REPLYTO_IDX
    ON HOMEPAGE.NT_REPLYTO_RECIPIENT (REPLYTO_ID);


----------------------------------------------------------------------
-- HOMEPAGE.MT_METRICS 
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.METRIC_STAT  (
      METRIC_STAT_ID VARCHAR(36) CCSID 1208 NOT NULL,
      RECORDED_ON TIMESTAMP NOT NULL,
      METRIC_TYPE SMALLINT NOT NULL,
      METRIC_DESC VARCHAR(36) CCSID 1208 NOT NULL,
      RES_BUNDLE_KEY VARCHAR(144) CCSID 1208 NOT NULL,
      COUNT_LAST_24_H BIGINT,
      COUNT_LAST_7_D BIGINT,
      COUNT_LAST_1_M BIGINT,
      TOP_STATS VARCHAR(512) CCSID 1208,
      TOT_STAT BIGINT,
      AVG_TOT_STAT BIGINT,
      ORGANIZATION_ID VARCHAR(36) CCSID 1208 DEFAULT '00000000-0000-0000-0000-000000000000'
)
;

ALTER TABLE HOMEPAGE.METRIC_STAT 
    ADD CONSTRAINT "HOMEPAGE".PK_METRIC_STAT_ID PRIMARY KEY(METRIC_STAT_ID);


CREATE INDEX HOMEPAGE.METRIC_IDX
    ON HOMEPAGE.METRIC_STAT (RECORDED_ON ASC, METRIC_TYPE);
ALTER TABLE HOMEPAGE.METRIC_STAT 
	ADD CONSTRAINT HOMEPAGE.FK_METRIC_ORG_ID FOREIGN KEY (ORGANIZATION_ID) 
	REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
    
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: OAuth Consumer Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
--
-- Replace							Example
--  HOMEPAGE					HOMEPAGE
--	 		HOMEPAGE.
-- 	IN USERSPACE8K INDEX IN USERSPACE8K
--  LCUSER
--  STMT == End statement
--
-- Types - You will need to substitue these tokens
--  VARCHAR
--  TIMESTAMP



-------------------------------------------
-- HOMEPAGE.OAUTH1_TOKEN
-------------------------------------------	 
CREATE TABLE HOMEPAGE.OAUTH1_TOKEN (
	ID VARCHAR(256) CCSID 1208 NOT NULL PRIMARY KEY,
	TOKEN VARCHAR(1024) CCSID 1208 NOT NULL,
	SECRET VARCHAR(1024) CCSID 1208 NOT NULL,
	EXPIRATION TIMESTAMP,
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL
)
;




-------------------------------------------
-- HOMEPAGE.OAUTH1_PROVIDER
-------------------------------------------	 
CREATE TABLE HOMEPAGE.OAUTH1_PROVIDER (
	ID VARCHAR(256) CCSID 1208 NOT NULL PRIMARY KEY,
	NAME VARCHAR(254) CCSID 1208 NOT NULL,
	DESCRIPTION VARCHAR(1024) CCSID 1208,
	REQUESTTOKENURL VARCHAR(512) CCSID 1208 NOT NULL,
	AUTHORIZEURL VARCHAR(512) CCSID 1208 NOT NULL,
	ACCESSTOKENURL VARCHAR(512) CCSID 1208 NOT NULL,
	BASEURL VARCHAR(512) CCSID 1208,
	MANAGEURL VARCHAR(512) CCSID 1208,
	REGISTERURL VARCHAR(512) CCSID 1208,
	SIGNMETHOD VARCHAR(32) CCSID 1208,
	VERSION VARCHAR(8) CCSID 1208,
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	CONSTRAINT HOMEPAGE.PRVD_NAME_UK UNIQUE (NAME)
)
;

-------------------------------------------
-- HOMEPAGE.OAUTH1_CLIENT
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH1_CLIENT (
	ID VARCHAR(256) CCSID 1208 NOT NULL PRIMARY KEY,
	PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,
	NAME VARCHAR(254) CCSID 1208 NOT NULL,
	TOKENID VARCHAR(256) CCSID 1208 NOT NULL,
	PROVIDERID VARCHAR(256) CCSID 1208 NOT NULL,
	DESCRIPTION VARCHAR(1024) CCSID 1208,
	CALLBACKURL VARCHAR(512) CCSID 1208,	
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	CONSTRAINT HOMEPAGE.CLNT_NAME_UK UNIQUE (NAME)
)
;

ALTER TABLE HOMEPAGE.OAUTH1_CLIENT 
	ADD CONSTRAINT "HOMEPAGE".CLNT_FK FOREIGN KEY (PROVIDERID) 
	REFERENCES HOMEPAGE.OAUTH1_PROVIDER(ID);

ALTER TABLE HOMEPAGE.OAUTH1_CLIENT 
	ADD CONSTRAINT "HOMEPAGE".CLNT_TOKEN_FK FOREIGN KEY (TOKENID) 
	REFERENCES HOMEPAGE.OAUTH1_TOKEN(ID);
	
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT
	ADD CONSTRAINT "HOMEPAGE".FK_OA1CL_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);		
	


-------------------------------------------
-- HOMEPAGE.OAUTH1_CONTEXT
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH1_CONTEXT (
	ID VARCHAR(256) CCSID 1208 NOT NULL PRIMARY KEY,
	CLIENTID VARCHAR(256) CCSID 1208 NOT NULL,
	PERSON_ID VARCHAR(36) CCSID 1208,
	TOKENID VARCHAR(256) CCSID 1208 NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	NONCE VARCHAR(256) CCSID 1208,
	EXPIRATION TIMESTAMP,
	AUTHORIZED SMALLINT DEFAULT 0 NOT NULL
)
;

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT "HOMEPAGE".CONTEXT_CLNT_FK FOREIGN KEY (CLIENTID) 
	REFERENCES HOMEPAGE.OAUTH1_CLIENT(ID);

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT "HOMEPAGE".AUTH_TOKEN_FK FOREIGN KEY (TOKENID) 
	REFERENCES HOMEPAGE.OAUTH1_TOKEN(ID);
	
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT "HOMEPAGE".FK_OA1C_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);		


	
-------------------------------------------
-- HOMEPAGE.OAUTH2_PROVIDER
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_PROVIDER (
  NAME VARCHAR(254) CCSID 1208 NOT NULL PRIMARY KEY,
  CLIENT_AUTH VARCHAR(254) CCSID 1208,
  AUTH_HEADER SMALLINT,
  URL_PARAM SMALLINT,
  AUTH_URL VARCHAR(1024) CCSID 1208,
  TOKEN_URL VARCHAR(1024) CCSID 1208
)
;

-------------------------------------------
-- HOMEPAGE.OAUTH2_CLIENT
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_CLIENT (
  NAME VARCHAR(254) CCSID 1208 NOT NULL PRIMARY KEY,
  PROVIDER_NAME VARCHAR(254) CCSID 1208 NOT NULL,
  REDIRECT_URI VARCHAR(1024) CCSID 1208,
  CTYPE VARCHAR(254) CCSID 1208 NOT NULL,
  GRANT_TYPE VARCHAR(254) CCSID 1208 NOT NULL,
  CLIENT_ID VARCHAR(1024) CCSID 1208 NOT NULL,
  CLIENT_SECRET VARCHAR(1024) CCSID 1208 NOT NULL,
  ALLOWED_DOMAINS VARCHAR(1024) CCSID 1208
)
;

ALTER TABLE HOMEPAGE.OAUTH2_CLIENT
  ADD CONSTRAINT "HOMEPAGE".FK_CLIENT_PRO_NAME FOREIGN KEY(PROVIDER_NAME)
  REFERENCES HOMEPAGE.OAUTH2_PROVIDER(NAME);
    
-------------------------------------------
-- HOMEPAGE.OAUTH2_GADGET_BINDING
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_GADGET_BINDING (
  ID VARCHAR(36) CCSID 1208 NOT NULL PRIMARY KEY,
  WIDGET_ID VARCHAR(36) CCSID 1208 NOT NULL,
  URI_SHA1 CHAR(40) CCSID 1208 NOT NULL, 
  SERVICE_NAME VARCHAR(254) CCSID 1208  NOT NULL,
  URI VARCHAR(1024) CCSID 1208 NOT NULL,
  CLIENT_NAME VARCHAR(254) CCSID 1208 NOT NULL,
  OVERRIDES SMALLINT NOT NULL,
  SECURE_URI_SHA1 CHAR(40) CCSID 1208,
  SECURE_URI VARCHAR(1024) CCSID 1208,
  CONSTRAINT HOMEPAGE.WIDGET_GADGET_UK UNIQUE (WIDGET_ID, SERVICE_NAME)
)
;

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING
  ADD CONSTRAINT "HOMEPAGE".FK_BINDING_CLIENT FOREIGN KEY(CLIENT_NAME)
  REFERENCES HOMEPAGE.OAUTH2_CLIENT(NAME);

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING
  ADD CONSTRAINT "HOMEPAGE".FK_BINDING_WIDGET FOREIGN KEY(WIDGET_ID)
  REFERENCES HOMEPAGE.WIDGET(WIDGET_ID);
  
CREATE INDEX HOMEPAGE.OA2T_GBINDING_WID
	ON HOMEPAGE.OAUTH2_GADGET_BINDING (WIDGET_ID);
  



-------------------------------------------
-- HOMEPAGE.OAUTH2_TOKEN
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_TOKEN (
  ID VARCHAR(254) CCSID 1208 NOT NULL PRIMARY KEY,
  URI VARCHAR(1024) CCSID 1208 NOT NULL,
  SERVICE_NAME VARCHAR(254) CCSID 1208 NOT NULL,
  PERSON_ID VARCHAR(36) CCSID 1208 NOT NULL,
  SCOPE VARCHAR(1024) CCSID 1208 NOT NULL,
  TTYPE SMALLINT NOT NULL,
  SECRET VARCHAR(1024) CCSID 1208,
  EXPIRES TIMESTAMP,
  ISSUED TIMESTAMP NOT NULL,
  TOKEN_TYPE VARCHAR(254) CCSID 1208,
  MAC_SECRET VARCHAR(1024) CCSID 1208,
  MAC_ALG VARCHAR(254) CCSID 1208,
  MAC_EXT VARCHAR(254) CCSID 1208,
  PROPS VARCHAR(1024) CCSID 1208,
  TOKEN_SHA1 CHAR(40) CCSID 1208
)
;

ALTER TABLE HOMEPAGE.OAUTH2_TOKEN
	ADD CONSTRAINT "HOMEPAGE".FK_OA2T_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);	

CREATE INDEX HOMEPAGE.OA2T_PERSON_SERVICE
	ON HOMEPAGE.OAUTH2_TOKEN (PERSON_ID, SERVICE_NAME);
	
CREATE UNIQUE INDEX HOMEPAGE.OA2_TOKEN_SHA1_UNQ 
	ON HOMEPAGE.OAUTH2_TOKEN (TOKEN_SHA1);	



CREATE TABLE HOMEPAGE.OH2P_CACHE (
	LOOKUPKEY VARCHAR(256) CCSID 1208 NOT NULL, 
	UNIQUEID VARCHAR(128) CCSID 1208 NOT NULL, 
	COMPONENTID VARCHAR(256) CCSID 1208 NOT NULL, 
	TYPE VARCHAR(64) CCSID 1208 NOT NULL, 
	SUBTYPE VARCHAR(64) CCSID 1208, 
	CREATEDAT BIGINT, 
	LIFETIME INTEGER, 
	EXPIRES BIGINT, 
	TOKENSTRING VARCHAR(2048) CCSID 1208 NOT NULL, 
	CLIENTID VARCHAR(64) CCSID 1208 NOT NULL, 
	USERNAME VARCHAR(256) CCSID 1208 NOT NULL, 
	SCOPE VARCHAR(512) CCSID 1208 NOT NULL, 
	REDIRECTURI VARCHAR(2048) CCSID 1208, 
	STATEID VARCHAR(64) CCSID 1208 NOT NULL
)
;

ALTER TABLE HOMEPAGE.OH2P_CACHE 
	ADD CONSTRAINT "HOMEPAGE".PK_LOOKUPKEY PRIMARY KEY (LOOKUPKEY);

CREATE INDEX HOMEPAGE.OH2P_CACHE_EXPIRES ON HOMEPAGE.OH2P_CACHE (EXPIRES ASC);


CREATE INDEX HOMEPAGE.OH2P_CACHE_CNT 
	ON HOMEPAGE.OH2P_CACHE (USERNAME, CLIENTID, COMPONENTID);


CREATE TABLE HOMEPAGE.OH2P_CLIENTCFG (
	COMPONENTID VARCHAR(128) CCSID 1208 NOT NULL, 
	CLIENTID VARCHAR(256) CCSID 1208 NOT NULL, 
	CLIENTSECRET VARCHAR(256) CCSID 1208, 
	DISPLAYNAME VARCHAR(256) CCSID 1208 NOT NULL, 
	REDIRECTURI VARCHAR(2048) CCSID 1208, 
	ENABLED SMALLINT
)
;

ALTER TABLE HOMEPAGE.OH2P_CLIENTCFG 
	ADD CONSTRAINT "HOMEPAGE".PK_COMPIDCLIENTID PRIMARY KEY (COMPONENTID,CLIENTID);



-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END OAuth Consumer Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    

   
CREATE TABLE HOMEPAGE.MTCONFIG (
	UUID			VARCHAR(36) CCSID 1208 NOT NULL,
	SCOPE 			VARCHAR(36) CCSID 1208 NOT NULL,
	ID 				VARCHAR(128) CCSID 1208 NOT NULL,
	CONFIG_VALUE 	VARCHAR(1024) CCSID 1208,
	SERVICE 		VARCHAR(256) CCSID 1208,
	NAME	 		VARCHAR(64) CCSID 1208,
	DESCRIPTION		VARCHAR(64) CCSID 1208,
	OVERRIDABLE 	SMALLINT NOT NULL DEFAULT 1,
	ISPOLICY		SMALLINT NOT NULL DEFAULT 0,
	ADMIN_VIS		SMALLINT NOT NULL DEFAULT 1
) ;

ALTER TABLE HOMEPAGE.MTCONFIG
	 ADD CONSTRAINT "HOMEPAGE"."PK_ID" PRIMARY KEY ("UUID");
	 
ALTER TABLE HOMEPAGE.MTCONFIG
	ADD CONSTRAINT "HOMEPAGE"."UNIQUE_ID" UNIQUE ("SCOPE","ID");

CREATE INDEX HOMEPAGE.SETTINGS_BY_ID
    ON HOMEPAGE.MTCONFIG(ID);

-----------------------------------------------------
--  HOMEPAGE.MT_CFG_DEFINITIONS
-----------------------------------------------------
CREATE TABLE HOMEPAGE.MT_CFG_DEFINITIONS (
	DEFINITION_ID	VARCHAR(36) CCSID 1208 NOT NULL,
	NAME			VARCHAR(128) CCSID 1208 NOT NULL,
	TITLE			VARCHAR(128) CCSID 1208,
	DESCRIPTION		VARCHAR(256) CCSID 1208,
	TYPE			VARCHAR(256) CCSID 1208,
	EDITOR			VARCHAR(128) CCSID 1208,
	CAN_MODIFY		SMALLINT NOT NULL DEFAULT 0,
	DISPLAY			SMALLINT DEFAULT 0 NOT NULL,
	REQUIRES		VARCHAR(128) CCSID 1208,
	VALIDATOR		VARCHAR(256) CCSID 1208,
	CATEGORY 		VARCHAR(128) CCSID 1208,
	ALLOW_ROLE 		SMALLINT
)
;
    
ALTER TABLE HOMEPAGE.MT_CFG_DEFINITIONS
	ADD CONSTRAINT "HOMEPAGE"."PK_MT_CFG_DEFINITION" PRIMARY KEY (DEFINITION_ID);
	

CREATE UNIQUE INDEX HOMEPAGE.UNQ_NAME
	ON HOMEPAGE.MT_CFG_DEFINITIONS (NAME);
		

-----------------------------------------------------
--  HOMEPAGE.MT_CFG_SETTINGS
-----------------------------------------------------
CREATE TABLE HOMEPAGE.MT_CFG_SETTINGS (
	SETTING_ID		VARCHAR(36) CCSID 1208 NOT NULL,
	ORGANIZATION_ID	VARCHAR(36) CCSID 1208 NOT NULL,
	NAME			VARCHAR(128) CCSID 1208 NOT NULL,
	VALUE			VARCHAR(256) CCSID 1208,
	CAN_MODIFY		SMALLINT NOT NULL DEFAULT 0,
	ROLE 			VARCHAR(36) CCSID 1208
)
;

ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS
	ADD CONSTRAINT "HOMEPAGE"."PK_MT_CFG_SETTINGS" PRIMARY KEY (SETTING_ID);
	
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS 
	ADD CONSTRAINT "HOMEPAGE"."FK_CFG_SET_ORG_ID" FOREIGN KEY (ORGANIZATION_ID) 
	REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID); 
	
CREATE UNIQUE INDEX HOMEPAGE.UNQ_ORG_NAME
	ON HOMEPAGE.MT_CFG_SETTINGS (NAME, ORGANIZATION_ID,ROLE);	

-----------------------------------------------------
--  HOMEPAGE.MT_CFG_FILES
-- 	TYPE: 0: BINARY FILE, 1: TXT FILE, 2: CONFIGURATION FILE
-----------------------------------------------------
CREATE TABLE HOMEPAGE.MT_CFG_FILES (
	FILE_ID			VARCHAR(36) CCSID 1208 NOT NULL,
	SETTING_ID		VARCHAR(36) CCSID 1208 NOT NULL,
	TYPE			SMALLINT NOT NULL, 
	FILENAME		VARCHAR(256) CCSID 1208,		
	CACHE			SMALLINT NOT NULL DEFAULT 0,
	C_CONTENT		CLOB CCSID 1208,
	B_CONTENT		BLOB,
	ORGANIZATION_ID	VARCHAR(36) CCSID 1208 NOT NULL	
)
;

ALTER TABLE HOMEPAGE.MT_CFG_FILES
	ADD CONSTRAINT "HOMEPAGE"."PK_MT_CFG_FILE" PRIMARY KEY (FILE_ID);

ALTER TABLE HOMEPAGE.MT_CFG_FILES 
	ADD CONSTRAINT "HOMEPAGE"."FK_SETTING_ID" FOREIGN KEY (SETTING_ID) REFERENCES HOMEPAGE.MT_CFG_SETTINGS (SETTING_ID);

CREATE UNIQUE INDEX HOMEPAGE.UNQ_SETTING
	ON HOMEPAGE.MT_CFG_FILES (SETTING_ID);
	
ALTER TABLE HOMEPAGE.MT_CFG_FILES 
	ADD CONSTRAINT "HOMEPAGE"."FK_CFG_FILE_ORG_ID" FOREIGN KEY (ORGANIZATION_ID) 
	REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);