-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2008, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 
   
--------------------------------------
-- CREATE THE DATABASE
--------------------------------------
CREATE DATABASE HOMEPAGE ON PRIMARY
	( NAME = 'HOMEPAGE', FILENAME = '$(filepath)\HOMEPAGE.mdf', SIZE = 100MB, FILEGROWTH = 20MB )
	LOG ON
	( NAME = 'HOMEPAGE_log', FILENAME = '$(filepath)\HOMEPAGE_log.ldf', SIZE = 20MB, FILEGROWTH = 2MB ) COLLATE LATIN1_GENERAL_BIN
GO 

USE HOMEPAGE;
GO
ALTER DATABASE HOMEPAGE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE HOMEPAGE SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE HOMEPAGE SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE HOMEPAGE SET MULTI_USER;
GO

--------------------------------------
-- CONNECT TO HOMEPAGE
--------------------------------------
USE HOMEPAGE
GO

--------------------------------------
-- CREATE THE SCHEMA
-- The CREATE SCHEMA command must be the first statement in a query batch, that is, must right after GO command
--------------------------------------
CREATE SCHEMA HOMEPAGE
GO

--------------------------------------
-- CREATE HOMEPAGE USER
--------------------------------------
USE HOMEPAGE
GO
CREATE ROLE HOMEPAGE_ROLE
CREATE LOGIN HOMEPAGEUSER WITH PASSWORD = '$(password)', DEFAULT_DATABASE = HOMEPAGE

CREATE USER HOMEPAGEUSER FOR LOGIN HOMEPAGEUSER WITH DEFAULT_SCHEMA = HOMEPAGE
GO

--------------------------------------
-- CREATE THE TABLES
--------------------------------------
BEGIN TRANSACTION
GO

CREATE TABLE HOMEPAGE.HOMEPAGE_SCHEMA (
	COMPKEY nvarchar(36) NOT NULL,
	DBSCHEMAVER NUMERIC(5,0) NOT NULL,
	RELEASEVER nvarchar(32) NOT NULL
)  ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.PERSON  (
	PERSON_ID nvarchar(36) NOT NULL,
	DISPLAYNAME nvarchar(256) NOT NULL,
	EXID nvarchar(256) NOT NULL,
	USER_MAIL nvarchar(256)	
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.LOGINNAME (
	PERSON_ID nvarchar(36) NOT NULL,
	LOGINNAME nvarchar(256) NOT NULL,
) ON [PRIMARY]

GO

CREATE TABLE HOMEPAGE.HP_UI  (
	UI_ID nvarchar(36) NOT NULL,
	PERSON_ID nvarchar(36) NOT NULL,
	PERSON_LANG nvarchar(5) NOT NULL,
	LAST_VISIT DATETIME NOT NULL,
	WELCOME_MODE NUMERIC(5,0) NOT NULL DEFAULT 1,
	SHOW_DISABLED_WIDGETS NUMERIC(5,0) NOT NULL DEFAULT 0 
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.HP_TAB  (
	TAB_ID nvarchar(36) NOT NULL,
	DEFAULT_NAME nvarchar(36) NOT NULL,
	DEFAULT_N_COLUMNS NUMERIC(5, 0) NOT NULL DEFAULT 0,
	IS_NAME_CHANGEABLE NUMERIC(5,0) NOT NULL DEFAULT 0	
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.HP_TAB_INST  (
	TAB_INST_ID nvarchar(36) NOT NULL,
	TAB_ID nvarchar(36) NOT NULL,
	UI_ID nvarchar(36) NOT NULL,
	TAB_NAME nvarchar(36),
	N_COLUMNS NUMERIC(5, 0) NOT NULL DEFAULT 0,
	LAST_MODIFIED DATETIME NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.HP_WIDGET_INST  (
	WIDGET_INST_ID nvarchar(36) NOT NULL,
	WIDGET_ID nvarchar(36) NOT NULL,
	TAB_INST_ID nvarchar(36) NOT NULL,
	WIDGET_SETTING nvarchar(2048),
	CONTAINER nvarchar(36),
	ORDER_SEQUENCE NUMERIC(5, 0),
	IS_FIXED NUMERIC(5,0),
	IS_TOGGLED NUMERIC(5,0),
	LAST_MODIFIED DATETIME NOT NULL,
	LAST_UPDATED DATETIME
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.WIDGET (
	WIDGET_ID nvarchar(36) NOT NULL,
	WIDGET_TITLE nvarchar(256) NOT NULL,
	WIDGET_TEXT nvarchar(256),
	WIDGET_URL nvarchar(256) NOT NULL,
	WIDGET_ICON nvarchar(256),
	WIDGET_ENABLED NUMERIC(5,0) NOT NULL DEFAULT 0,
	WIDGET_SYSTEM NUMERIC(5,0) NOT NULL DEFAULT 0,
	WIDGET_HOMEPAGE_SPECIFIC nvarchar,
	WIDGET_PREVIEW_IMAGE nvarchar(256),
	WIDGET_CATEGORY nvarchar(36) NOT NULL,
	WIDGET_IS_DEFAULT_OPENED NUMERIC(5,0) NOT NULL DEFAULT 0,
	WIDGET_MULTIPLE_INSTANCES NUMERIC(5,0) NOT NULL DEFAULT 0,
	WIDGET_MARKED_CACHABLE NUMERIC(5,0) NOT NULL DEFAULT 0
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.HP_WIDGET_TAB (
	WIDGET_TAB_ID nvarchar(36) NOT NULL,
	WIDGET_ID nvarchar(36) NOT NULL,
	TAB_ID nvarchar(36) NOT NULL,
	TYPE nvarchar(36) NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.PREREQ (
	PREREQ_ID nvarchar(36) NOT NULL,
	APP_ID nvarchar(36) NOT NULL,
	WIDGET_ID nvarchar(36) NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.NT_NOTIFICATION  (
	  NOTIFICATION_ID nvarchar(36) NOT NULL,
	  NOTIFICATION_SOURCE nvarchar(36) NOT NULL,
	  NOTIFICATION_TYPE nvarchar(256) NOT NULL,
	  DATETIME_STAMP DATETIME NOT NULL,
	  SENDER_EXID nvarchar(36) NOT NULL,
	  SUBJECT nvarchar(256),
	  MESSAGE nvarchar(2048),
	  CONTAINER_NAME nvarchar(256),
	  CONTAINER_URL nvarchar(2048),
	  ITEM_NAME nvarchar(256),
	  ITEM_URL nvarchar(2048)
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT (
		  ID nvarchar(36) NOT NULL,
		  NOTIFICATION_ID nvarchar(36) NOT NULL,
		  RECIPIENT_EXID nvarchar(36) NOT NULL		  
) ON [PRIMARY]
GO

--------------------------------------
-- CREATE THE CONSTRAINTS
--------------------------------------
ALTER TABLE HOMEPAGE.PERSON
   ADD CONSTRAINT PK_PERSON_ID PRIMARY KEY (PERSON_ID)
GO

ALTER TABLE HOMEPAGE.HP_UI
    ADD CONSTRAINT PK_HP_UI PRIMARY KEY (UI_ID)  
GO

ALTER TABLE HOMEPAGE.HP_TAB
    ADD CONSTRAINT PK_HP_TAB PRIMARY KEY (TAB_ID)
GO

ALTER TABLE HOMEPAGE.HP_TAB_INST
    ADD CONSTRAINT PK_HP_TAB_INST PRIMARY KEY (TAB_INST_ID)    
GO

ALTER TABLE HOMEPAGE.WIDGET 
	ADD CONSTRAINT PK_WIDGET PRIMARY KEY (WIDGET_ID)
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB 
	ADD CONSTRAINT PK_WIDGET_TAB PRIMARY KEY (WIDGET_TAB_ID)
GO

ALTER TABLE HOMEPAGE.PREREQ 
	ADD CONSTRAINT PK_PREREQ PRIMARY KEY (PREREQ_ID)
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
	ADD CONSTRAINT PK_HP_WIDGET_INST PRIMARY KEY (WIDGET_INST_ID)
GO

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT PK_LOGINNAME_ID PRIMARY KEY (PERSON_ID,LOGINNAME)
GO

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
	ADD CONSTRAINT PK_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID)
	
ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT
	ADD CONSTRAINT PK_NOTIF_RECIP PRIMARY KEY (ID)
GO

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT FK_LN_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID)
GO

ALTER TABLE HOMEPAGE.HP_UI
    ADD CONSTRAINT FK_UI_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID)	
GO
	
ALTER TABLE HOMEPAGE.HP_TAB_INST
    ADD CONSTRAINT FK_UI_ID FOREIGN KEY (UI_ID)
	REFERENCES HOMEPAGE.HP_UI(UI_ID)
GO

ALTER TABLE HOMEPAGE.HP_TAB_INST
    ADD CONSTRAINT FK_TAB_INST_TAB_ID FOREIGN KEY (TAB_ID)
	REFERENCES HOMEPAGE.HP_TAB(TAB_ID)
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
    ADD CONSTRAINT FK_WIDGET_ID FOREIGN KEY (WIDGET_ID)
	REFERENCES HOMEPAGE.WIDGET (WIDGET_ID)
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_INST
    ADD CONSTRAINT FK_TAB_INST_ID FOREIGN KEY (TAB_INST_ID)
	REFERENCES HOMEPAGE.HP_TAB_INST (TAB_INST_ID)
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB	
    ADD CONSTRAINT FK_WID_TAB_WID_ID FOREIGN KEY (WIDGET_ID)
	REFERENCES HOMEPAGE.WIDGET (WIDGET_ID)
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB	
    ADD CONSTRAINT FK_WID_TAB_TAB_ID FOREIGN KEY (TAB_ID)
	REFERENCES HOMEPAGE.HP_TAB (TAB_ID)
GO	

ALTER TABLE HOMEPAGE.PREREQ 
	ADD CONSTRAINT FK_PREREQ_WIDGET FOREIGN KEY (WIDGET_ID)
	REFERENCES HOMEPAGE.WIDGET (WIDGET_ID)
	ON DELETE CASCADE
GO

ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
	ADD CONSTRAINT FK_RECIP_NOTIF FOREIGN KEY (NOTIFICATION_ID)
	REFERENCES HOMEPAGE.NT_NOTIFICATION (NOTIFICATION_ID)
	ON DELETE CASCADE
GO

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT LOGINNAME_UNIQUE UNIQUE (LOGINNAME)
GO

--------------------------------------
-- CREATE THE INDEXES
--------------------------------------
CREATE INDEX WIDGET_INST
	ON HOMEPAGE.HP_WIDGET_INST (TAB_INST_ID ASC, WIDGET_ID ASC)
GO

CREATE UNIQUE INDEX PERSON_EXID
	ON HOMEPAGE.PERSON (EXID)
GO

CREATE INDEX PERSON_USER_MAIL
    ON HOMEPAGE.PERSON(USER_MAIL)
GO

CREATE INDEX HP_UI_PERSON_ID_INDEX
	ON HOMEPAGE.HP_UI (PERSON_ID)
GO

CREATE INDEX NT_NOTIFICATION_EXID_INDEX
	ON HOMEPAGE.NT_NOTIFICATION(SENDER_EXID)
GO
	
CREATE INDEX NT_NOTIF_RECT_EXID_INDEX
	ON HOMEPAGE.NT_NOTIFICATION_RECIPIENT(RECIPIENT_EXID)
GO	
	
CREATE INDEX NT_NOTIF_RECT_NID_INDEX
	ON HOMEPAGE.NT_NOTIFICATION_RECIPIENT(NOTIFICATION_ID)
GO	
	
--------------------------------------
-- POPULATE THE TABLES
--------------------------------------
INSERT INTO HOMEPAGE.HOMEPAGE_SCHEMA ( COMPKEY, DBSCHEMAVER, RELEASEVER) VALUES ('HOMEPAGE', 8, '2.5.0.0')
GO

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- STARTING OF THE DEFINITION FOR THE NEWS REPOSITORY DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------
-- NEWS REPOSITORY - CREATE THE TABLES
----------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_SOURCE (
	SOURCE_ID nvarchar(36) NOT NULL,
	SOURCE nvarchar(36) NOT NULL,
	CONTAINER_ID nvarchar(36) NOT NULL,
	CONTAINER_NAME nvarchar(256) NOT NULL,
	CONTAINER_URL nvarchar(2048),
	ENTRY_ID  nvarchar(36),
	ENTRY_NAME nvarchar(256),
	ENTRY_URL nvarchar(2048),
	ENTRY_ATOM_URL nvarchar(2048),
	IS_ACL NUMERIC(5,0) NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.NR_SUBSCRIPTION  (
	SUBSCRIPTION_ID nvarchar(36) NOT NULL,
	PERSON_ID nvarchar(36) NOT NULL,
	SOURCE_ID nvarchar(36) NOT NULL,
	IS_EXPLICIT NUMERIC(5,0) NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE HOMEPAGE.NR_NEWS_RECORDS (
	NEWS_RECORDS_ID nvarchar(36) NOT NULL,
	EVENT_NAME nvarchar(256) NOT NULL,
    READER_ID nvarchar(36),
    SOURCE nvarchar(36),
    CONTAINER_ID nvarchar(36),
    CONTAINER_NAME nvarchar(256),
    CONTAINER_URL nvarchar(2048),
    ENTRY_ID nvarchar(36),
    ENTRY_NAME nvarchar(256),
    ENTRY_URL nvarchar(2048),
    ENTRY_ATOM_URL nvarchar(2048),
    CREATION_DATE DATETIME NOT NULL,
    IS_INBOX NUMERIC(5,0) NOT NULL,
    IS_SAVED NUMERIC(5,0) NOT NULL,
    IS_TOP_STORY NUMERIC(5,0) NOT NULL,
    IS_PUBLIC NUMERIC(5,0) NOT NULL,
    IS_MAILED NUMERIC(5,0) NOT NULL,
    TIME_STAMP DATETIME NOT NULL,
    BRIEF_DESC nvarchar(256),
    IS_BRIEF_DESC_RTL NUMERIC(5,0) NOT NULL,
    ACTOR_UUID nvarchar(36),
    EVENT_RECORD_UUID nvarchar(36) NOT NULL,
    RELATED_COMM_UUID nvarchar(36),
    RELATED_COMM_NAME nvarchar(256),
    TAGS nvarchar(max),
    META_TEMPLATE nvarchar(max) NOT NULL
) ON [PRIMARY]
GO


CREATE TABLE HOMEPAGE.NR_TEMPLATE (
	TEMPLATE_ID nvarchar(36) NOT NULL,
 	NAME nvarchar(256) NOT NULL,
 	FORMAT nvarchar(256) NOT NULL,
 	DATA_SOURCE_STRING nvarchar(256) NOT NULL,
 	NO_VALUES NUMERIC(5,0) NOT NULL
) ON [PRIMARY]
GO


----------------------------------------------------------------------------
-- NEWS REPOSITORY -  CREATE THE CONSTRAINTS
----------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_SOURCE
    ADD CONSTRAINT PK_SOURCE_ID PRIMARY KEY(SOURCE_ID)    
GO

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT PK_SUBSCRIPTION_ID PRIMARY KEY(SUBSCRIPTION_ID)
GO

ALTER TABLE HOMEPAGE.NR_NEWS_RECORDS
    ADD CONSTRAINT PK_NR_NEWS_RECORDS PRIMARY KEY(NEWS_RECORDS_ID)
GO

ALTER TABLE HOMEPAGE.NR_TEMPLATE 
    ADD CONSTRAINT PK_TEMPLATE_ID PRIMARY KEY(TEMPLATE_ID)
GO
    
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);
GO

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT FK_SOURCE_ID FOREIGN KEY (SOURCE_ID)
	REFERENCES HOMEPAGE.NR_SOURCE (SOURCE_ID)	
GO

----------------------------------------------------------------------------
-- NEWS REPOSITORY -  CREATE THE INDEXES
----------------------------------------------------------------------------
CREATE UNIQUE INDEX NR_SUBSCRIPTION_IX_UNIQUE
	ON HOMEPAGE.NR_SUBSCRIPTION(PERSON_ID ASC, SOURCE_ID ASC)
GO
	
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- END OF THE DEFINITION FOR THE NEWS REPOSITORY DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- START THE DEFINITION FOR THE SEARCH DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.LOTUSCONNECTIONSTASK ( [TASKID] BIGINT NOT NULL ,
               [VERSION] NVARCHAR(5) NOT NULL ,
               [ROW_VERSION] INT NOT NULL ,
               [TASKTYPE] INT NOT NULL ,
               [TASKSUSPENDED] TINYINT NOT NULL ,
               [CANCELLED] TINYINT NOT NULL ,
               [NEXTFIRETIME] BIGINT NOT NULL ,
               [STARTBYINTERVAL] NVARCHAR(254) NULL ,
               [STARTBYTIME] BIGINT NULL ,
               [VALIDFROMTIME] BIGINT NULL ,
               [VALIDTOTIME] BIGINT NULL ,
               [REPEATINTERVAL] NVARCHAR(254) NULL ,
               [MAXREPEATS] INT NOT NULL ,
               [REPEATSLEFT] INT NOT NULL ,
               [TASKINFO] IMAGE NULL ,
               [NAME] NVARCHAR(254) NOT NULL ,
               [AUTOPURGE] INT NOT NULL ,
               [FAILUREACTION] INT NULL ,
               [MAXATTEMPTS] INT NULL ,
               [QOS] INT NULL ,
               [PARTITIONID] INT NULL ,
               [OWNERTOKEN] NVARCHAR(200) NOT NULL ,
               [CREATETIME] BIGINT NOT NULL ) 
GO

ALTER TABLE HOMEPAGE.LOTUSCONNECTIONSTASK WITH NOCHECK ADD CONSTRAINT LOTUSCONNECTIONSTASK_PK PRIMARY KEY  NONCLUSTERED ( [TASKID] ) 
GO

CREATE INDEX LOTUSCONNECTIONSTASK_IDX1 ON HOMEPAGE.LOTUSCONNECTIONSTASK ( [TASKID],
               [OWNERTOKEN] ) 
GO

CREATE CLUSTERED INDEX LOTUSCONNECTIONSTASK_IDX2 ON HOMEPAGE.LOTUSCONNECTIONSTASK ( [NEXTFIRETIME] ASC,
               [REPEATSLEFT],
               [PARTITIONID] )
GO

CREATE TABLE HOMEPAGE.LOTUSCONNECTIONSTREG ( [REGKEY] NVARCHAR(254) NOT NULL ,
               [REGVALUE] NVARCHAR(254) NULL ,
               PRIMARY KEY ( [REGKEY] ) )
GO

CREATE TABLE HOMEPAGE.LOTUSCONNECTIONSLMGR ( [LEASENAME] NVARCHAR(254) NOT NULL,
               [LEASEOWNER] NVARCHAR(254) NOT NULL,
               [LEASE_EXPIRE_TIME] BIGINT,
               [DISABLED] NVARCHAR(5) )
GO

ALTER TABLE HOMEPAGE.LOTUSCONNECTIONSLMGR WITH NOCHECK ADD CONSTRAINT LOTUSCONNECTIONSLMGR_PK PRIMARY KEY  NONCLUSTERED ( [LEASENAME] ) 
GO

CREATE TABLE HOMEPAGE.LOTUSCONNECTIONSLMPR ( [LEASENAME] NVARCHAR(224) NOT NULL,
               [NAME] NVARCHAR(224) NOT NULL,
               [VALUE] NVARCHAR(254) NOT NULL )
GO

CREATE INDEX LOTUSCONNECTIONSLMPR_IDX1 ON HOMEPAGE.LOTUSCONNECTIONSLMPR ( [LEASENAME],
               [NAME] ) 
GO

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- END THE DEFINITION FOR THE SEARCH DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

	
--------------------------------------
-- GRANT TO HOMEPAGE USER
--------------------------------------
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.HOMEPAGE_SCHEMA TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.PERSON TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.LOGINNAME TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.HP_UI TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.HP_TAB TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.HP_TAB_INST TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.HP_WIDGET_INST TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.WIDGET TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.HP_WIDGET_TAB TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.PREREQ TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NT_NOTIFICATION TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NT_NOTIFICATION_RECIPIENT TO HOMEPAGEUSER
GO
-- NEWS REPOSITORY
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_SOURCE TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_SUBSCRIPTION TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_NEWS_RECORDS TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_TEMPLATE TO HOMEPAGEUSER
GO
-- SEARCH
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.LOTUSCONNECTIONSLMPR TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.LOTUSCONNECTIONSLMGR TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.LOTUSCONNECTIONSTREG TO HOMEPAGEUSER
GO
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.LOTUSCONNECTIONSTASK TO HOMEPAGEUSER
GO


--------------------------------------
-- DISCONNECT
--------------------------------------
COMMIT
