-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2008, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

USE HOMEPAGE;
GO

-- To remove all the records from a database before to start a db transfer
DELETE FROM HOMEPAGE.HOMEPAGE_SCHEMA;
DELETE FROM HOMEPAGE.LOGINNAME;
DELETE FROM HOMEPAGE.HP_WIDGET_INST;
DELETE FROM HOMEPAGE.HP_TAB_INST;
DELETE FROM HOMEPAGE.HP_WIDGET_TAB; 
DELETE FROM HOMEPAGE.HP_UI;
DELETE FROM HOMEPAGE.HP_TAB;
DELETE FROM HOMEPAGE.PREREQ;
DELETE FROM HOMEPAGE.WIDGET;
DELETE FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT;
DELETE FROM HOMEPAGE.NT_NOTIFICATION;
DELETE FROM HOMEPAGE.NR_NEWS_RECORDS;
DELETE FROM HOMEPAGE.NR_SUBSCRIPTION;
DELETE FROM HOMEPAGE.NR_SOURCE;
DELETE FROM HOMEPAGE.NR_EVENT_RECORDS;
DELETE FROM HOMEPAGE.NR_TEMPLATE;
DELETE FROM HOMEPAGE.EMD_JOBS_STATS;
DELETE FROM HOMEPAGE.EMD_RECIPIENTS;
DELETE FROM HOMEPAGE.EMD_JOBS;
DELETE FROM HOMEPAGE.SR_INDEXINGTASKDEF;
DELETE FROM HOMEPAGE.SR_OPTIMIZETASKDEF;
DELETE FROM HOMEPAGE.SR_TASKDEF;
DELETE FROM HOMEPAGE.SR_FILESCONTENT;
DELETE FROM HOMEPAGE.SR_MIGTASKDEFINFO;
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMGR;
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMPR;
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTASK;
DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTREG;
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMGR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMPR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TASK;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TREG;
DELETE FROM HOMEPAGE.PERSON;

-- HOMEPAGE 
ALTER TABLE HOMEPAGE.LOGINNAME DROP CONSTRAINT FK_LN_PERSON_ID;
GO

ALTER TABLE HOMEPAGE.HP_UI DROP CONSTRAINT FK_UI_PERSON_ID;
GO

ALTER TABLE HOMEPAGE.HP_TAB_INST DROP CONSTRAINT FK_UI_ID;
GO

ALTER TABLE HOMEPAGE.HP_TAB_INST DROP CONSTRAINT FK_TAB_INST_TAB_ID;
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP CONSTRAINT FK_WIDGET_ID;
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP CONSTRAINT FK_TAB_INST_ID;
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP CONSTRAINT FK_WID_TAB_WID_ID;
GO

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP CONSTRAINT FK_WID_TAB_TAB_ID;
GO

ALTER TABLE HOMEPAGE.PREREQ DROP CONSTRAINT FK_PREREQ_WIDGET;
GO

ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT DROP CONSTRAINT FK_RECIP_NOTIF;
GO

ALTER TABLE HOMEPAGE.LOGINNAME DROP LOGINNAME_UNIQUE;
GO

DROP INDEX PERSON_EXID ON HOMEPAGE.PERSON;
GO

-- NEWS RECORDS 
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION DROP CONSTRAINT FK_PERSON_ID;
GO

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION DROP CONSTRAINT FK_SOURCE_ID;
GO

ALTER TABLE HOMEPAGE.EMD_RECIPIENTS DROP CONSTRAINT FK_REC_PERSON_ID;
GO

ALTER TABLE HOMEPAGE.EMD_JOBS_STATS DROP CONSTRAINT FK_JOB_ID;
GO

DROP INDEX  NR_SUBSCRIPTION_IX_UNIQUE ON HOMEPAGE.NR_SUBSCRIPTION;
GO

DROP INDEX  NR_SOURCE_IX_UNIQUE ON HOMEPAGE.NR_SOURCE;
GO

ALTER TABLE HOMEPAGE.EMD_JOBS DROP UNIQUE_JOB_FREQ;
GO

-- SEARCH
ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF DROP CONSTRAINT FK_INDEX_TASK_ID;

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF DROP CONSTRAINT FK_OPT_TASK_ID;

ALTER TABLE HOMEPAGE.SR_TASKDEF DROP UNIQUE_TASK_NAME;

ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF DROP UNIQUE_TASK_ID_IND;

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF DROP UNIQUE_TASK_ID_OPT;

ALTER TABLE HOMEPAGE.SR_FILESCONTENT  DROP UNIQUE_COMP_UUID;

ALTER TABLE HOMEPAGE.SR_TASKDEF DROP CONSTRAINT CHECK_SR_TASKDEF;

