-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              

---------------------------------------------------------------------
-- Alter Columns HOMEPAGE.NR_ENTRIES HOMEPAGE.NR_ENTRIES_ARCHIVE
---------------------------------------------------------------------

EXPORT TO data.tmp.ixf OF IXF METHOD N (
        ENTRY_ID, JSON_META_DATA, IS_EXTERNAL
)
 SELECT
       ENTRY_ID, JSON_META_DATA, 0 IS_EXTERNAL
 FROM HOMEPAGE.NR_ENTRIES WITH UR@

COMMIT@ 

ALTER TABLE HOMEPAGE.NR_ENTRIES DROP COLUMN JSON_META_DATA@
COMMIT@

-- Adding Columns
ALTER TABLE HOMEPAGE.NR_ENTRIES 
		ADD PREV_COMMENT_OBJECT_META_DATA CLOB INLINE LENGTH 800
		ADD LAST_COMMENT_OBJECT_META_DATA CLOB INLINE LENGTH 800
		ADD	LAST_COMMENT_TAGS VARCHAR(1024)
		ADD PREV_COMMENT_TAGS VARCHAR(1024)
		ADD JSON_META_DATA CLOB INLINE LENGTH 800
		ADD IS_EXTERNAL SMALLINT DEFAULT 0 NOT NULL@
COMMIT@

REORG TABLE HOMEPAGE.NR_ENTRIES@
COMMIT@

IMPORT FROM data.tmp.ixf OF IXF METHOD N (
        ENTRY_ID, JSON_META_DATA, IS_EXTERNAL
) COMMITCOUNT 1000
	INSERT_UPDATE INTO HOMEPAGE.NR_ENTRIES
	        ( 
	        ENTRY_ID, JSON_META_DATA, IS_EXTERNAL
	        )@ 
COMMIT@

---

EXPORT TO data.tmp.ixf OF IXF METHOD N (
        ENTRY_ID, JSON_META_DATA, IS_EXTERNAL
)
 SELECT
       ENTRY_ID, JSON_META_DATA, 0 IS_EXTERNAL
 FROM HOMEPAGE.NR_ENTRIES_ARCHIVE WITH UR@
COMMIT@

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE DROP COLUMN JSON_META_DATA@
COMMIT@

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
		ADD PREV_COMMENT_OBJECT_META_DATA CLOB INLINE LENGTH 800
		ADD LAST_COMMENT_OBJECT_META_DATA CLOB INLINE LENGTH 800
		ADD	LAST_COMMENT_TAGS VARCHAR(1024)
		ADD PREV_COMMENT_TAGS VARCHAR(1024)
		ADD JSON_META_DATA CLOB INLINE LENGTH 800
		ADD IS_EXTERNAL SMALLINT DEFAULT 0 NOT NULL@
COMMIT@

REORG TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE@
COMMIT@

IMPORT FROM data.tmp.ixf OF IXF METHOD N (
        ENTRY_ID, JSON_META_DATA, IS_EXTERNAL
) COMMITCOUNT 1000
	INSERT_UPDATE INTO HOMEPAGE.NR_ENTRIES_ARCHIVE
	        ( 
	        ENTRY_ID, JSON_META_DATA, IS_EXTERNAL
	        )@ 
COMMIT@


---------------------------------------------------------------------
-- Adding Columns HOMEPAGE.NR_ENTRIES HOMEPAGE.NR_ENTRIES_ARCHIVE
---------------------------------------------------------------------


-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-- 113572: [fixup469] [Performance|DB2] Degradation on queries of  (SELECT READER_ID  FROM HOMEPAGE.<READERS>  WHERE ROLLUP_ENTRY_ID = ?
-- 115518: [fixup469] add a new COMMUNITY_ID column to reader tables


--  [start indexes] NR_AGGREGATED_READERS
DROP  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
DROP  INDEX HOMEPAGE.RESPONSES_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.RESPONSES_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
DROP  INDEX HOMEPAGE.PROFILES_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.PROFILES_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
DROP  INDEX HOMEPAGE.COMM_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.COMM_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
DROP  INDEX HOMEPAGE.BLOGS_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.BLOGS_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
DROP  INDEX HOMEPAGE.FILES_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.FILES_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
DROP  INDEX HOMEPAGE.FORUMS_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.FORUMS_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
DROP  INDEX HOMEPAGE.WIKIS_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.WIKIS_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
DROP  INDEX HOMEPAGE.TAGS_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.TAGS_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.STATUS_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_CONT_IDX@
COMMIT@

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.PROFILES_VIEW_CONT_IDX@
COMMIT@

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP  INDEX HOMEPAGE.NOT_REC_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.NOT_REC_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
DROP  INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.SAVED_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
DROP  INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.TOPICS_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
DROP  INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.MENTIONS_READERS_CONT_IDX@
COMMIT@

--  [end indexes] NR_MENTIONS_READERS


--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX HOMEPAGE.RESPONSES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX HOMEPAGE.PROFILES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_PROFILES_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX HOMEPAGE.COMM_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMM_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX HOMEPAGE.BLOGS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BLOGS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_BLOGS_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX HOMEPAGE.FILES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FILES_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_FILES_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX HOMEPAGE.FORUMS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FORUMS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_FORUMS_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX HOMEPAGE.WIKIS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.WIKIS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_WIKIS_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX HOMEPAGE.TAGS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TAGS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_TAGS_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_ENTRY_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_COMM_IDX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_COMM_IDX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX HOMEPAGE.NOT_REC_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_SAVED_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_TOPICS_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
CREATE  INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_MENTIONS_READERS


----------------------------------------------------
-- 23 HOMEPAGE.NR_COMMUNITIES_VIEW
----------------------------------------------------
CREATE TABLE HOMEPAGE.NR_COMMUNITIES_VIEW (
	CATEGORY_READER_ID VARCHAR(36) DEFAULT ' ' NOT NULL,
	READER_ID VARCHAR(39) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(256),
	ROLLUP_ENTRY_ID VARCHAR(256),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	USE_IN_ROLLUP SMALLINT,
	IS_NETWORK	SMALLINT,
	IS_FOLLOWER	SMALLINT,
	EVENT_TIME 	TIMESTAMP,
	IS_STORY_COMM SMALLINT,
	IS_BROADCAST SMALLINT,
	ORGANIZATION_ID VARCHAR(36) DEFAULT '00000000-0000-0000-0000-000000000000',
	ACTOR_UUID VARCHAR(256),
	IS_VISIBLE SMALLINT DEFAULT 1 NOT NULL,
	ROLLUP_AUTHOR_ID VARCHAR (256),
	COMMUNITY_ID VARCHAR(36),
		CONSTRAINT   	CK_CAT23_TYPE
    			CHECK
    			(CATEGORY_TYPE = 23)
)
IN NEWS4TABSPACE@

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW
    ADD CONSTRAINT PK_CV_READERS PRIMARY KEY(CATEGORY_READER_ID)@

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW 
	ADD CONSTRAINT FK_CV_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@ 
	
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW ADD CONSTRAINT FK_CV_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@

--  [start indexes] NR_COMMUNITIES_VIEW
CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_CD_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_BRD_VVI 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@


CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_COMM_IDX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_COMMUNITIES_VIEW


-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------



------------------------------------------------------------------------------------------------
-- UPDATE SCHEMA VERSION AND RELEASE VERSION to 469
------------------------------------------------------------------------------------------------
UPDATE  HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER = 469, RELEASEVER = '5.0.0.0' 
WHERE   DBSCHEMAVER = 468@

------------------------------------------------------------------------------------------------




COMMIT@