-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              

CONNECT TO HOMEPAGE@


-- ALTER TABLES:
ALTER TABLE HOMEPAGE.HOMEPAGE_SCHEMA COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.MT_ORGANIZATION COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.PERSON COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.PERSON_ROLE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.HP_USER_PREFS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.LOGINNAME COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.HP_UI COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.HP_TAB COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.HP_TAB_INST COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.WIDGET COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.HP_WIDGET_INST COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.PREREQ COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NT_REPLYTO COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.METRIC_STAT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_TOKEN COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_PROVIDER COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH2_PROVIDER COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH2_CLIENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH2_TOKEN COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OH2P_CACHE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OH2P_CLIENTCFG COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.MTCONFIG COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.MT_CFG_DEFINITIONS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.MT_CFG_FILES COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE_DEFAULT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_TEMPLATE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SCHEDULER_TASK COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SCHEDULER_TREG COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SCHEDULER_LMGR COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SCHEDULER_LMPR COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_RESOURCE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_FOLLOWS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NETWORK COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_TRANCHE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ENTRIES COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_STORIES COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_ENTRIES COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_COMMENTS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_MENTIONS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SAVED_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_COLLECTION_CONFIG COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_CRAWLER_STATUS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.IMG_CACHE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_COUNTS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OEMBED_SCHEDULER_TASK COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OEMBED_SCHEDULER_TREG COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OEMBED_SCHEDULER_LMGR COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.OEMBED_SCHEDULER_LMPR COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_TASKDEF COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_BACKUPTASKDEF COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_SANDTASKDEF COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FILESCONTENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_MIGTASKDEFINFO COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_INDEX_MANAGEMENT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_RESUME_TOKENS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_INDEX_DOCS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FEEDBACK COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FEEDBACK_CONTEXT COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FEEDBACK_PARAMETERS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_STATS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_STRING_STATS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_NUMBER_STATS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_TIMER_STATS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_GLOBAL_SAND_PROPS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_ECM_DOCUMENT_TYPE_LABELS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_POST_FILTERING_SERVICE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_ECM_DOCUMENT_TYPE_PROPS COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.LOTUSCONNECTIONSTASK COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.LOTUSCONNECTIONSTREG COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.LOTUSCONNECTIONSLMGR COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.LOTUSCONNECTIONSLMPR COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_CUSTOM_LIST_ITEM COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.SR_RECOMMEND_CACHE_USERPROFILE COMPRESS NO@
COMMIT@
ALTER TABLE HOMEPAGE.NR_READ_STATUS COMPRESS NO@
COMMIT@





-- REORG TABLES:
reorg table HOMEPAGE.HOMEPAGE_SCHEMA@
COMMIT@
reorg table HOMEPAGE.MT_ORGANIZATION@
COMMIT@
reorg table HOMEPAGE.PERSON@
COMMIT@
reorg table HOMEPAGE.PERSON_ROLE@
COMMIT@
reorg table HOMEPAGE.HP_USER_PREFS@
COMMIT@
reorg table HOMEPAGE.LOGINNAME@
COMMIT@
reorg table HOMEPAGE.HP_UI@
COMMIT@
reorg table HOMEPAGE.HP_TAB@
COMMIT@
reorg table HOMEPAGE.HP_TAB_INST@
COMMIT@
reorg table HOMEPAGE.WIDGET@
COMMIT@
reorg table HOMEPAGE.HP_WIDGET_TAB@
COMMIT@
reorg table HOMEPAGE.HP_WIDGET_INST@
COMMIT@
reorg table HOMEPAGE.PREREQ@
COMMIT@
reorg table HOMEPAGE.NT_REPLYTO@
COMMIT@
reorg table HOMEPAGE.NT_REPLYTO_RECIPIENT@
COMMIT@
reorg table HOMEPAGE.METRIC_STAT@
COMMIT@
reorg table HOMEPAGE.OAUTH1_TOKEN@
COMMIT@
reorg table HOMEPAGE.OAUTH1_PROVIDER@
COMMIT@
reorg table HOMEPAGE.OAUTH1_CLIENT@
COMMIT@
reorg table HOMEPAGE.OAUTH1_CONTEXT@
COMMIT@
reorg table HOMEPAGE.OAUTH2_PROVIDER@
COMMIT@
reorg table HOMEPAGE.OAUTH2_CLIENT@
COMMIT@
reorg table HOMEPAGE.OAUTH2_GADGET_BINDING@
COMMIT@
reorg table HOMEPAGE.OAUTH2_TOKEN@
COMMIT@
reorg table HOMEPAGE.OH2P_CACHE@
COMMIT@
reorg table HOMEPAGE.OH2P_CLIENTCFG@
COMMIT@
reorg table HOMEPAGE.MTCONFIG@
COMMIT@
reorg table HOMEPAGE.MT_CFG_DEFINITIONS@
COMMIT@
reorg table HOMEPAGE.MT_CFG_SETTINGS@
COMMIT@
reorg table HOMEPAGE.MT_CFG_FILES@
COMMIT@
reorg table HOMEPAGE.NR_SOURCE_TYPE_DEFAULT@
COMMIT@
reorg table HOMEPAGE.NR_SOURCE_TYPE@
COMMIT@
reorg table HOMEPAGE.NR_TEMPLATE@
COMMIT@
reorg table HOMEPAGE.NR_SCHEDULER_TASK@
COMMIT@
reorg table HOMEPAGE.NR_SCHEDULER_TREG@
COMMIT@
reorg table HOMEPAGE.NR_SCHEDULER_LMGR@
COMMIT@
reorg table HOMEPAGE.NR_SCHEDULER_LMPR@
COMMIT@
reorg table HOMEPAGE.NR_NEWS_STATUS_NETWORK@
COMMIT@
reorg table HOMEPAGE.NR_NEWS_STATUS_COMMENT@
COMMIT@
reorg table HOMEPAGE.NR_NEWS_STATUS_CONTENT@
COMMIT@
reorg table HOMEPAGE.NR_NEWS_COMMENT_CONTENT@
COMMIT@
reorg table HOMEPAGE.NR_RESOURCE@
COMMIT@
reorg table HOMEPAGE.NR_FOLLOWS@
COMMIT@
reorg table HOMEPAGE.NR_COMM_FOLLOW@
COMMIT@
reorg table HOMEPAGE.NR_STORIES_CONTENT@
COMMIT@
reorg table HOMEPAGE.NR_NETWORK@
COMMIT@
reorg table HOMEPAGE.EMD_RESOURCE_PREF@
COMMIT@
reorg table HOMEPAGE.EMD_TRANCHE@
COMMIT@
reorg table HOMEPAGE.EMD_TRANCHE_INFO@
COMMIT@
reorg table HOMEPAGE.EMD_EMAIL_PREFS@
COMMIT@
reorg table HOMEPAGE.NR_COMM_PERSON_FOLLOW@
COMMIT@
reorg table HOMEPAGE.NR_ENTRIES@
COMMIT@
reorg table HOMEPAGE.NR_STORIES@
COMMIT@
reorg table HOMEPAGE.NR_ENTRIES_ARCHIVE@
COMMIT@
reorg table HOMEPAGE.NR_AGGREGATED_READERS@
COMMIT@
reorg table HOMEPAGE.NR_STATUS_UPDATE_READERS@
COMMIT@
reorg table HOMEPAGE.NR_EXTERNAL_READERS@
COMMIT@
reorg table HOMEPAGE.NR_ACTIONABLE_READERS@
COMMIT@
reorg table HOMEPAGE.BOARD@
COMMIT@
reorg table HOMEPAGE.BOARD_ENTRIES@
COMMIT@
reorg table HOMEPAGE.BOARD_COMMENTS@
COMMIT@
reorg table HOMEPAGE.BOARD_OBJECT_REFERENCE@
COMMIT@
reorg table HOMEPAGE.BOARD_RECOMMENDATIONS@
COMMIT@
reorg table HOMEPAGE.BOARD_CURRENT_STATUS@
COMMIT@
reorg table HOMEPAGE.BOARD_MENTIONS@
COMMIT@
reorg table HOMEPAGE.DELETED_STORIES_QUEUE@
COMMIT@
reorg table HOMEPAGE.NR_COMM_SETTINGS@
COMMIT@
reorg table HOMEPAGE.NR_PROFILES_VIEW@
COMMIT@
reorg table HOMEPAGE.NR_NOTIFICATION_SENT_READERS@
COMMIT@
reorg table HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS@
COMMIT@
reorg table HOMEPAGE.NR_SAVED_READERS@
COMMIT@
reorg table HOMEPAGE.NR_TOPICS_READERS@
COMMIT@
reorg table HOMEPAGE.NR_MENTIONS_READERS@
COMMIT@
reorg table HOMEPAGE.NR_COMMUNITIES_VIEW@
COMMIT@
reorg table HOMEPAGE.NR_AS_SEEDLIST@
COMMIT@
reorg table HOMEPAGE.NR_AS_COLLECTION_CONFIG@
COMMIT@
reorg table HOMEPAGE.NR_AS_CRAWLER_STATUS@
COMMIT@
reorg table HOMEPAGE.NR_AS_CONTENT_INDEX_STATS@
COMMIT@
reorg table HOMEPAGE.IMG_CACHE@
COMMIT@
reorg table HOMEPAGE.NR_AS_COUNTS@
COMMIT@
reorg table HOMEPAGE.OEMBED_SCHEDULER_TASK@
COMMIT@
reorg table HOMEPAGE.OEMBED_SCHEDULER_TREG@
COMMIT@
reorg table HOMEPAGE.OEMBED_SCHEDULER_LMGR@
COMMIT@
reorg table HOMEPAGE.OEMBED_SCHEDULER_LMPR@
COMMIT@
reorg table HOMEPAGE.SR_TASKDEF@
COMMIT@
reorg table HOMEPAGE.SR_INDEXINGTASKDEF@
COMMIT@
reorg table HOMEPAGE.SR_OPTIMIZETASKDEF@
COMMIT@
reorg table HOMEPAGE.SR_FILECONTENTTASKDEF@
COMMIT@
reorg table HOMEPAGE.SR_BACKUPTASKDEF@
COMMIT@
reorg table HOMEPAGE.SR_SANDTASKDEF@
COMMIT@
reorg table HOMEPAGE.SR_FILESCONTENT@
COMMIT@
reorg table HOMEPAGE.SR_MIGTASKDEFINFO@
COMMIT@
reorg table HOMEPAGE.SR_INDEX_MANAGEMENT@
COMMIT@
reorg table HOMEPAGE.SR_RESUME_TOKENS@
COMMIT@
reorg table HOMEPAGE.SR_INDEX_DOCS@
COMMIT@
reorg table HOMEPAGE.SR_FEEDBACK@
COMMIT@
reorg table HOMEPAGE.SR_FEEDBACK_CONTEXT@
COMMIT@
reorg table HOMEPAGE.SR_FEEDBACK_PARAMETERS@
COMMIT@
reorg table HOMEPAGE.SR_STATS@
COMMIT@
reorg table HOMEPAGE.SR_STRING_STATS@
COMMIT@
reorg table HOMEPAGE.SR_NUMBER_STATS@
COMMIT@
reorg table HOMEPAGE.SR_TIMER_STATS@
COMMIT@
reorg table HOMEPAGE.SR_GLOBAL_SAND_PROPS@
COMMIT@
reorg table HOMEPAGE.SR_ECM_DOCUMENT_TYPE_LABELS@
COMMIT@
reorg table HOMEPAGE.SR_POST_FILTERING_SERVICE@
COMMIT@
reorg table HOMEPAGE.SR_ECM_DOCUMENT_TYPE_PROPS@
COMMIT@
reorg table HOMEPAGE.LOTUSCONNECTIONSTASK@
COMMIT@
reorg table HOMEPAGE.LOTUSCONNECTIONSTREG@
COMMIT@
reorg table HOMEPAGE.LOTUSCONNECTIONSLMGR@
COMMIT@
reorg table HOMEPAGE.LOTUSCONNECTIONSLMPR@
COMMIT@
reorg table HOMEPAGE.NR_CUSTOM_LIST@
COMMIT@
reorg table HOMEPAGE.NR_CUSTOM_LIST_ITEM@
COMMIT@
reorg table HOMEPAGE.SR_RECOMMEND_CACHE_USERPROFILE@
COMMIT@
reorg table HOMEPAGE.NR_READ_STATUS@
COMMIT@


------------------------------------------------------------------------------------------------
-- UPDATE SCHEMA VERSION AND RELEASE VERSION to 516
------------------------------------------------------------------------------------------------
UPDATE  HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER = 516, RELEASEVER = '6.0.0.0' 
WHERE   DBSCHEMAVER = 515@

------------------------------------------------------------------------------------------------




COMMIT@

--------------------------------------
-- FLUSH
--------------------------------------
FLUSH PACKAGE CACHE DYNAMIC@

--------------------------------------
-- TERMINATE
--------------------------------------
connect reset@
terminate@