-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2013, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 


--CREATE TABLE HOMEPAGE.TMP  (
--	TABLE_NAME VARCHAR(256) NOT NULL PRIMARY KEY
--);
--
--
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('BOARD');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('BOARD_COMMENTS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('BOARD_CURRENT_STATUS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('BOARD_ENTRIES');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('BOARD_RECOMMENDATIONS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('HP_TAB_INST');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('HP_UI');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('LOGINNAME');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('MT_METRIC_STAT');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('PERSON');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('SR_INDEX_DOCS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NT_NOTIFICATION');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NT_NOTIFICATION_RECIPIENT');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('OAUTH2_TOKEN');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('OH2P_CACHE');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_ACTIONABLE_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_AS_SEEDLIST');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_ENTRIES');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_ENTRIES_ARCHIVE');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_STORIES');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_STORIES_CONTENT');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('EMD_EMAIL_PREFS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('EMD_RESOURCE_PREF');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_ACTIVITIES_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_AGGREGATED_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_BLOGS_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_BOOKMARKS_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_COMMUNITIES_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_COMM_FOLLOW');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_COMM_PERSON_FOLLOW');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_COMM_SETTINGS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_DISCOVERY_VIEW');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_FILES_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_FOLLOWS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_FORUMS_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_NETWORK');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_NEWS_COMMENT_CONTENT');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_NEWS_STATUS_CONTENT');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_NOTIFICATION_SENT_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_PROFILES_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_PROFILES_VIEW');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_RESOURCE');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_RESPONSES_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_STATUS_UPDATE_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_TAGS_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_WIKIS_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_NEWS_STATUS_COMMENT');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_NEWS_STATUS_NETWORK');
---- added
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_EXTERNAL_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_SAVED_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_NOTIFICATION_RECEIV_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_TOPIC_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('NR_MENTIONS_READERS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('HP_USER_PREFS');
--INSERT INTO HOMEPAGE.TMP (TABLE_NAME) VALUES ('BOARD_OBJECT_REFERENCE');
--
--
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
--
---- i) alter table HOMEPAGE.BOARD_CURRENT_STATUS compress yes;
--select 'ALTER TABLE HOMEPAGE.' || NAME || ' COMPRESS YES; COMMIT;'
--from sysibm.systables
--where CREATOR = 'HOMEPAGE' and type = 'T' AND NAME IN (SELECT TMP.TABLE_NAME FROM HOMEPAGE.TMP TMP)
--ORDER BY NAME;
--
---- ii) alter index HOMEPAGE.ACTOR_ENTRY compress yes;
--select 'ALTER INDEX HOMEPAGE.' || INDEX_NAME || ' COMPRESS YES; COMMIT;' 
--from SYSIBM.SQLSTATISTICS
--where INDEX_NAME is not null and index_qualifier = 'HOMEPAGE' AND INDEX_NAME not in (SELECT CONSTNAME FROM syscat.tabconst  WHERE type = 'P' ) and TABLE_NAME IN (
--	select  NAME
--	from sysibm.systables
--	where CREATOR = 'HOMEPAGE' and type = 'T' AND NAME IN (SELECT TMP.TABLE_NAME FROM HOMEPAGE.TMP TMP)
--	ORDER by NAME
--)
--ORDER by TABLE_NAME;
--
--
---- iii) reorg table HOMEPAGE.BOARD_CURRENT_STATUS RESETDICTIONARY;
--select 'REORG TABLE HOMEPAGE.' || NAME || ' RESETDICTIONARY; COMMIT;'
--from sysibm.systables
--where CREATOR = 'HOMEPAGE' and type = 'T' AND NAME IN (SELECT TMP.TABLE_NAME FROM HOMEPAGE.TMP TMP)
--ORDER BY NAME;
--
---- iv) reorg indexes all for table HOMEPAGE.BOARD_CURRENT_STATUS;
--select 'REORG INDEXES ALL FOR TABLE HOMEPAGE.' || NAME || '; COMMIT;'
--from sysibm.systables
--where CREATOR = 'HOMEPAGE' and type = 'T' AND NAME IN (SELECT TMP.TABLE_NAME FROM HOMEPAGE.TMP TMP)
--ORDER BY NAME;
--
---- v) runstats on table HOMEPAGE.BOARD_CURRENT_STATUS with distribution and detailed indexes all allow read access;
--select 'RUNSTATS ON TABLE HOMEPAGE.' || NAME || ' WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; COMMIT;'
--from sysibm.systables
--where CREATOR = 'HOMEPAGE' and type = 'T'  AND NAME IN (SELECT TMP.TABLE_NAME FROM HOMEPAGE.TMP TMP)
--ORDER BY NAME;
--
--
--DROP TABLE HOMEPAGE.TMP;




connect to HOMEPAGE;


-- i) alter table HOMEPAGE.TABLE_NAME compress yes;
ALTER TABLE HOMEPAGE.BOARD COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_COMMENTS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_ENTRIES COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB_INST COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.HP_UI COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.HP_USER_PREFS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.LOGINNAME COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_FILES_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_FOLLOWS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_NETWORK COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESOURCE COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_SAVED_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_TAGS_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.OAUTH2_TOKEN COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.OH2P_CACHE COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.PERSON COMPRESS YES; 
COMMIT;
ALTER TABLE HOMEPAGE.SR_INDEX_DOCS COMPRESS YES; 
COMMIT;


-- ii) alter index HOMEPAGE.TABLE_NAME compress yes;
ALTER INDEX HOMEPAGE.CONTAINER_ID_UNQ COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BOARD_OWNER_ASSOC_UIDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BOARD_OWNER_ASSOC_UIDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CREATION_DATE_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CREATION_DATE_ITEM_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ITEM_CORR_CREATION_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_COMM_ITEM_COR_PUB COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ITEM_CORR_CREATION_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.NEWS_BRD_ITEM_CORR_ID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ITEM_ITEM_CORR_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ITEM_ITEM_CORR_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.NEWS_BRD_ITEM_ID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CREATION_DATE_ITEM_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_COMM_ITEM_COR_PUB COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTOR_ENTRY COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CURRENT_STATUS_INDEX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CURRENT_STATUS_INDEX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CURRENT_STATUS_INDEX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_CURRENT_STATUS COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CURRENT_STATUS_INDEX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_E_CONTAINER_ID_UIDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.SEEDLIST_BRD_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_ENTRIES_ITEM COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ITEM_ID_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_ENTRIES_ITEM COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_SL_UPDATED_DEL COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_SL_UPDATED_DEL COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.NEWS_BRD_SL_UPDATE COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.SEEDLIST_BRD_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CREATION_ITEM_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.CREATION_ITEM_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ITEM_ID_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_AUTHOR_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_ENTRY_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_REC_ITEM_ID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_REC_RECOM_ITEM_ID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_RECOMMENDER_ID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.BRD_REC_RECOM_ITEM_ID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.EMD_EMAIL_PREFS_PER COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.EMD_EMAIL_PREFS_TR COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.EMD_RESOURCE_PREF_UNQ COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.EMD_RES_PREF_PER_ID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.EMD_RESOURCE_PREF_UNQ COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.HP_TAB_INST_UNQ COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.TAB_INST_TAB_ID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.TAB_INST_UI_ID_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.HP_TAB_INST_UNQ COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.HP_UI COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.HP_UI_PERSONID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.HP_UI_PERSONID COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.USER_PREF_PER_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.USER_PREF_PER_NAME_UNQ COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.USER_PREF_NAME_IDX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.USER_PREF_PER_NAME_UNQ COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.LOGINNAME_UNIQUE COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.LOGINNAME_UNIQUE COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_BRD_VIS COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RIR_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_BRD_VIS COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_ITM_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RDR_STR COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RIR_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_BRD_VIS COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_CD_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_STR_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RDR_STR COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_BRD_VIS COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_DEL_SERV_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_CD_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RIR_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIONABLE_READERS_RIR_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_BRD_VIS COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_RIR_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_BRD_VIS COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_ITM_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_RDR_STR COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_RIR_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_BRD_VIS COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX COMPRESS YES; 
COMMIT;
ALTER INDEX HOMEPAGE.ACTIVITIES_READERS_CD_IX COMPRESS YES; 
COMMIT;



-- iii) reorg table HOMEPAGE.TABLE_NAME RESETDICTIONARY;
REORG TABLE HOMEPAGE.BOARD RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.BOARD_COMMENTS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.BOARD_CURRENT_STATUS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.BOARD_ENTRIES RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.BOARD_RECOMMENDATIONS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.EMD_EMAIL_PREFS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.EMD_RESOURCE_PREF RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.HP_TAB_INST RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.HP_UI RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.HP_USER_PREFS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.LOGINNAME RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_ACTIONABLE_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_ACTIVITIES_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_AGGREGATED_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_AS_SEEDLIST RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_BLOGS_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_BOOKMARKS_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_COMMUNITIES_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_COMM_FOLLOW RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_COMM_SETTINGS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_DISCOVERY_VIEW RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_ENTRIES RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_EXTERNAL_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_FILES_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_FOLLOWS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_FORUMS_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_MENTIONS_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_NETWORK RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_PROFILES_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_PROFILES_VIEW RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_RESOURCE RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_RESPONSES_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_SAVED_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_STORIES RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_STORIES_CONTENT RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_TAGS_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.NR_WIKIS_READERS RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.OAUTH2_TOKEN RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.OH2P_CACHE RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.PERSON RESETDICTIONARY; 
COMMIT;
REORG TABLE HOMEPAGE.SR_INDEX_DOCS RESETDICTIONARY; 
COMMIT;



--iv)  reorg indexes all for table HOMEPAGE.TABLE_NAME;
REORG INDEXES ALL FOR TABLE HOMEPAGE.BOARD;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.BOARD_COMMENTS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.BOARD_CURRENT_STATUS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.BOARD_ENTRIES;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.BOARD_RECOMMENDATIONS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.EMD_EMAIL_PREFS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.EMD_RESOURCE_PREF;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.HP_TAB_INST;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.HP_UI;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.HP_USER_PREFS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.LOGINNAME;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_ACTIONABLE_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_ACTIVITIES_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_AGGREGATED_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_AS_SEEDLIST;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_BLOGS_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_BOOKMARKS_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_COMMUNITIES_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_COMM_FOLLOW;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_COMM_SETTINGS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_DISCOVERY_VIEW;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_ENTRIES;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_EXTERNAL_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_FILES_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_FOLLOWS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_FORUMS_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_MENTIONS_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_NETWORK;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_PROFILES_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_PROFILES_VIEW;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_RESOURCE;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_RESPONSES_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_SAVED_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_STORIES;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_STORIES_CONTENT;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_TAGS_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.NR_WIKIS_READERS;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.OAUTH2_TOKEN;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.OH2P_CACHE;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.PERSON;
COMMIT;
REORG INDEXES ALL FOR TABLE HOMEPAGE.SR_INDEX_DOCS;
COMMIT;




-- v) runstats on table HOMEPAGE.TABLE_NAME with distribution and detailed indexes all allow read access;
RUNSTATS ON TABLE HOMEPAGE.BOARD_COMMENTS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.BOARD_CURRENT_STATUS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.BOARD_ENTRIES WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.BOARD_RECOMMENDATIONS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.BOARD WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.EMD_EMAIL_PREFS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.EMD_RESOURCE_PREF WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.HP_TAB_INST WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.HP_UI WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.HP_USER_PREFS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.LOGINNAME WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_ACTIONABLE_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_ACTIVITIES_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_AGGREGATED_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_AS_SEEDLIST WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_BLOGS_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_BOOKMARKS_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_COMM_FOLLOW WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_COMM_SETTINGS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_COMMUNITIES_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_DISCOVERY_VIEW WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_ENTRIES WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_EXTERNAL_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_FILES_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_FOLLOWS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_FORUMS_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_MENTIONS_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_NETWORK WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_PROFILES_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_PROFILES_VIEW WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_RESOURCE WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_RESPONSES_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_SAVED_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_STORIES_CONTENT WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_STORIES WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_TAGS_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.NR_WIKIS_READERS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.OAUTH2_TOKEN WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.OH2P_CACHE WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.PERSON WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;
RUNSTATS ON TABLE HOMEPAGE.SR_INDEX_DOCS WITH DISTRIBUTION AND DETAILED INDEXES ALL ALLOW READ ACCESS; 
COMMIT;



------------------------------------------------------------------------------------------------
-- UPDATE SCHEMA VERSION AND RELEASE VERSION to 454
------------------------------------------------------------------------------------------------
UPDATE  HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER = 454, RELEASEVER = '5.0.0.0 SC' 
WHERE   DBSCHEMAVER = 453; 

------------------------------------------------------------------------------------------------

COMMIT;

--------------------------------------
-- FLUSH
--------------------------------------
FLUSH PACKAGE CACHE DYNAMIC;

--------------------------------------
-- TERMINATE
--------------------------------------
connect reset;
terminate;












