-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

----------------------------------------------------------------------
-- HOMEPAGE.NT_REPLYTO
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NT_REPLYTO (
	REPLYTO_ID VARCHAR2(36) NOT NULL,
	SOURCE VARCHAR2(36),
	EVENT_NAME VARCHAR2(256) NOT NULL,
	CONTAINER_ID VARCHAR2(256),	
	ITEM_ID VARCHAR2(36),
	ITEM_CORRELATION_ID VARCHAR2(36),	
	CREATION_DATE TIMESTAMP NOT NULL,
	ACTOR_UUID VARCHAR2(36),
	EVENT_RECORD_UUID VARCHAR2(36) NOT NULL,
	CATEGORY_TYPE NUMBER(5,0)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.NT_REPLYTO
    ADD (CONSTRAINT PK_REPLYTO PRIMARY KEY(REPLYTO_ID) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

COMMIT;

----------------------------------------------------------------------
-- HOMEPAGE.NT_REPLYTO_RECIPIENT
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT (
	REPLYTO_RECIPIENT_ID VARCHAR2(36) NOT NULL,
	REPLYTO_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,	
	REPLYTO_ADDRESS_ID VARCHAR2(36) NOT NULL,
	LAST_UPDATE TIMESTAMP
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD (CONSTRAINT REPLYTO_RECIP_ID PRIMARY KEY(REPLYTO_RECIPIENT_ID) USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD CONSTRAINT FK_REPLYTO_ID FOREIGN KEY (REPLYTO_ID)
	REFERENCES HOMEPAGE.NT_REPLYTO (REPLYTO_ID);

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT
    ADD CONSTRAINT FK_REPLYTO_PER_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

CREATE UNIQUE INDEX HOMEPAGE.REPLYTO_ADDRESS_IDX
    ON HOMEPAGE.NT_REPLYTO_RECIPIENT (REPLYTO_ADDRESS_ID) TABLESPACE "HPNTINDEXTABSPACE";



COMMIT;

--------------------------------------------
-- ADDING SOURCE_TYPE - NT_NOTIFICATION
--------------------------------------------
ALTER TABLE HOMEPAGE.NT_NOTIFICATION
	ADD NOTIFICATION_SOURCE_TYPE NUMBER(5,0);
COMMIT;	

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 1 WHERE NOTIFICATION_SOURCE = 'activities';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 2 WHERE NOTIFICATION_SOURCE = 'blogs';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 3 WHERE NOTIFICATION_SOURCE = 'communities';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 4 WHERE NOTIFICATION_SOURCE = 'wikis';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 5 WHERE NOTIFICATION_SOURCE = 'profiles';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 6 WHERE NOTIFICATION_SOURCE = 'homepage';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 7 WHERE NOTIFICATION_SOURCE = 'dogear';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 7 WHERE NOTIFICATION_SOURCE = 'bookmarks';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 8 WHERE NOTIFICATION_SOURCE = 'files';
COMMIT;

UPDATE HOMEPAGE.NT_NOTIFICATION
	SET NOTIFICATION_SOURCE_TYPE = 9 WHERE NOTIFICATION_SOURCE = 'forums';
COMMIT;	

--------------------------------------------
-- ADDING SOURCE_TYPE - NT_REPLYTO
--------------------------------------------
ALTER TABLE HOMEPAGE.NT_REPLYTO
	ADD SOURCE_TYPE NUMBER(5,0);
COMMIT;	

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 1 WHERE SOURCE = 'activities';
COMMIT;

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 2 WHERE SOURCE = 'blogs';
COMMIT;

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 3 WHERE SOURCE = 'communities';
COMMIT;

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 4 WHERE SOURCE = 'wikis';
COMMIT;

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 5 WHERE SOURCE = 'profiles';
COMMIT;

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 6 WHERE SOURCE = 'homepage';
COMMIT;

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 7 WHERE SOURCE = 'dogear';
COMMIT;

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 8 WHERE SOURCE = 'files';
COMMIT;

UPDATE HOMEPAGE.NT_REPLYTO
	SET SOURCE_TYPE = 9 WHERE SOURCE = 'forums';
COMMIT;    

 