-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

DROP TABLE HOMEPAGE.OAUTH2_TOKEN;
DROP TABLE HOMEPAGE.OAUTH2_GADGET_BINDING;
DROP TABLE HOMEPAGE.OAUTH1_CONTEXT;
DROP TABLE HOMEPAGE.OAUTH1_CLIENT;
DROP TABLE HOMEPAGE.OAUTH1_PROVIDER;
DROP TABLE HOMEPAGE.OAUTH1_TOKEN;

-------------------------------------------
-- HOMEPAGE.OAUTH1_TOKEN
-------------------------------------------	 
CREATE TABLE HOMEPAGE.OAUTH1_TOKEN (
	ID VARCHAR2(256) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
	TOKEN VARCHAR2(1024) NOT NULL,
	SECRET VARCHAR2(1024) NOT NULL,
	EXPIRATION TIMESTAMP,
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH1_TOKEN ENABLE ROW MOVEMENT;

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH2_TOKEN
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_TOKEN (
  ID VARCHAR2(254) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
  URI VARCHAR2(1024) NOT NULL,
  SERVICE_NAME VARCHAR2(254) NOT NULL,
  PERSON_ID VARCHAR2(36) NOT NULL,
  SCOPE VARCHAR2(1024) NOT NULL,
  TTYPE NUMBER(5,0) NOT NULL,
  SECRET VARCHAR2(1024),
  EXPIRES TIMESTAMP,
  ISSUED TIMESTAMP NOT NULL,
  TOKEN_TYPE VARCHAR2(254),
  MAC_SECRET VARCHAR2(1024),
  MAC_ALG VARCHAR2(254),
  MAC_EXT VARCHAR2(254),
  PROPS VARCHAR2(1024)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH2_TOKEN
	ADD CONSTRAINT FK_OA2T_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);	

CREATE INDEX HOMEPAGE.OA2T_PERSON_SERVICE
	ON HOMEPAGE.OAUTH2_TOKEN (PERSON_ID, SERVICE_NAME) TABLESPACE "NEWSINDEXTABSPACE";
	
ALTER TABLE HOMEPAGE.OAUTH2_TOKEN ENABLE ROW MOVEMENT;

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH2_GADGET_BINDING
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH2_GADGET_BINDING (
  ID VARCHAR2(36) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
  URI_SHA1 CHAR(40) NOT NULL, 
  SERVICE_NAME VARCHAR2(254)  NOT NULL,
  URI VARCHAR2(1024) NOT NULL,
  CLIENT_NAME VARCHAR2(254) NOT NULL,
  OVERRIDES NUMBER(5,0) NOT NULL,
  CONSTRAINT PK_GADGET_PK UNIQUE (URI_SHA1, SERVICE_NAME) USING INDEX  TABLESPACE "NEWSINDEXTABSPACE"
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING
  ADD CONSTRAINT FK_BINDING_CLIENT FOREIGN KEY(CLIENT_NAME)
  REFERENCES HOMEPAGE.OAUTH2_CLIENT(NAME) ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING ENABLE ROW MOVEMENT;

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH1_PROVIDER
-------------------------------------------	 
CREATE TABLE HOMEPAGE.OAUTH1_PROVIDER (
	ID VARCHAR2(256) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
	NAME VARCHAR2(254) NOT NULL,
	DESCRIPTION VARCHAR2(1024),
	REQUESTTOKENURL VARCHAR2(512) NOT NULL,
	AUTHORIZEURL VARCHAR2(512) NOT NULL,
	ACCESSTOKENURL VARCHAR2(512) NOT NULL,
	BASEURL VARCHAR2(512),
	MANAGEURL VARCHAR2(512),
	REGISTERURL VARCHAR2(512),
	SIGNMETHOD VARCHAR2(32),
	VERSION VARCHAR2(8),
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	CONSTRAINT PRVD_NAME_UK UNIQUE (NAME) USING INDEX  TABLESPACE "NEWSINDEXTABSPACE"
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH1_PROVIDER ENABLE ROW MOVEMENT; 

COMMIT;

-------------------------------------------
-- HOMEPAGE.OAUTH1_CLIENT
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH1_CLIENT (
	ID VARCHAR2(256) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
	PERSON_ID VARCHAR2(36) NOT NULL,
	NAME VARCHAR2(254) NOT NULL,
	TOKENID VARCHAR2(256) NOT NULL,
	PROVIDERID VARCHAR2(256) NOT NULL,
	DESCRIPTION VARCHAR2(1024),
	CALLBACKURL VARCHAR2(512),
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	CONSTRAINT CLNT_NAME_UK UNIQUE (NAME) USING INDEX  TABLESPACE "NEWSINDEXTABSPACE"
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH1_CLIENT 
	ADD CONSTRAINT CLNT_FK FOREIGN KEY (PROVIDERID) 
	REFERENCES HOMEPAGE.OAUTH1_PROVIDER(ID) ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE HOMEPAGE.OAUTH1_CLIENT 
	ADD CONSTRAINT CLNT_TOKEN_FK FOREIGN KEY (TOKENID) 
	REFERENCES HOMEPAGE.OAUTH1_TOKEN(ID) ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;
	
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT
	ADD CONSTRAINT FK_OA1CL_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);		
	
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT ENABLE ROW MOVEMENT; 

COMMIT;

------------------------------------------
-- HOMEPAGE.OAUTH1_CONTEXT
-------------------------------------------
CREATE TABLE HOMEPAGE.OAUTH1_CONTEXT (
	ID VARCHAR2(256) NOT NULL PRIMARY KEY USING INDEX  TABLESPACE "NEWSINDEXTABSPACE",
	CLIENTID VARCHAR2(256) NOT NULL,
	PERSON_ID VARCHAR2(36),
	TOKENID VARCHAR2(256) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	MODIFIED TIMESTAMP NOT NULL,
	NONCE VARCHAR2(256),
	EXPIRATION TIMESTAMP,
	AUTHORIZED NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT CONTEXT_CLNT_FK FOREIGN KEY (CLIENTID) 
	REFERENCES HOMEPAGE.OAUTH1_CLIENT(ID) ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT AUTH_TOKEN_FK FOREIGN KEY (TOKENID) 
	REFERENCES HOMEPAGE.OAUTH1_TOKEN(ID) ON DELETE CASCADE INITIALLY DEFERRED DEFERRABLE;
	
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT
	ADD CONSTRAINT FK_OA1C_PERSON_ID FOREIGN KEY (PERSON_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);		

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT ENABLE ROW MOVEMENT;

COMMIT;
