-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}
 
 ----------------------------------------------------------------------
-- HOMEPAGE.MT_METRICS 
----------------------------------------------------------------------

CREATE TABLE HOMEPAGE.MT_METRIC_STAT  (
      METRIC_STAT_ID VARCHAR2(36) NOT NULL,
      RECORDED_ON TIMESTAMP NOT NULL,
      METRIC_TYPE NUMBER(5,0) NOT NULL,
      METRIC_DESC VARCHAR2(36) NOT NULL,
      RES_BUNDLE_KEY VARCHAR2(144) NOT NULL,
      COUNT_LAST_24_H NUMBER(19 ,0),
      COUNT_LAST_7_D NUMBER(19 ,0),
      COUNT_LAST_1_M NUMBER(19 ,0),
      TOP_STATS VARCHAR2(512),
      TOT_STAT NUMBER(19 ,0),
      AVG_TOT_STAT NUMBER(19 ,0)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.MT_METRIC_STAT 
    ADD (CONSTRAINT PK_METRIC_STAT_ID PRIMARY KEY(METRIC_STAT_ID) USING INDEX TABLESPACE "HPNTINDEXTABSPACE");

CREATE INDEX HOMEPAGE.MT_METRICS_IDX
    ON HOMEPAGE.MT_METRIC_STAT (RECORDED_ON ASC, METRIC_TYPE) TABLESPACE "HPNTINDEXTABSPACE";
    
ALTER TABLE HOMEPAGE.MT_METRIC_STAT ENABLE ROW MOVEMENT;     
{ORA_GRANT_START} HOMEPAGE.MT_METRIC_STAT {ORA_GRANT_STOP}


-------------------------------------------------
-- FIXING NT_NOTIFICATION TABLE
-------------------------------------------------

-- 1 NT_NOTIFICATION_RECIPIENT WHERE RECIPIENT_ID
------------------------------------------------------------------------------------------------------------
-- DELETE FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT WHERE RECIPIENT_ID IS NULL;
------------------------------------------------------------------------------------------------------------
DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (RAWTONHEX(SUBSTR(ID,1,1))) <= '30' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (RAWTONHEX(SUBSTR(ID,1,1))) > '30' AND (RAWTONHEX(SUBSTR(ID,1,1))) <= '34' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (RAWTONHEX(SUBSTR(ID,1,1))) > '34' AND (RAWTONHEX(SUBSTR(ID,1,1))) <= '39' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (RAWTONHEX(SUBSTR(ID,1,1))) > '39' AND (RAWTONHEX(SUBSTR(ID,1,1))) <= '61' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (RAWTONHEX(SUBSTR(ID,1,1))) > '61' AND (RAWTONHEX(SUBSTR(ID,1,1))) <= '64' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (RAWTONHEX(SUBSTR(ID,1,1))) > '64' AND (RAWTONHEX(SUBSTR(ID,1,1))) <= '66' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (RAWTONHEX(SUBSTR(ID,1,1))) > '66' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE 
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT
WHERE RECIPIENT_ID IS NULL;

COMMIT;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT
	MODIFY RECIPIENT_ID NOT NULL;

COMMIT;

-- 2 NT_NOTIFICATION WHERE FIRST_RECIPIENT_ID
-----------------------------------------------------------------------------------
-- DELETE FROM HOMEPAGE.NT_NOTIFICATION WHERE FIRST_RECIPIENT_ID IS NULL;
----------------------------------------------------------------------------------- 
DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '30' AND NOTIFICATION_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '30' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '34' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '34' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '39' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '39' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '61' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '61' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '64' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '64' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '66' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '66' AND NOTIFICATION_ID IS NULL;

COMMIT;

DELETE 
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE FIRST_RECIPIENT_ID IS NULL;

COMMIT;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
	MODIFY FIRST_RECIPIENT_ID NOT NULL;
	
-- 3 NT_NOTIFICATION WHERE SENDER_ID
-----------------------------------------------------------------------------------
-- DELETE FROM HOMEPAGE.NT_NOTIFICATION WHERE SENDER_ID IS NULL;
-----------------------------------------------------------------------------------
DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '30' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '30' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '34' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '34' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '39' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '39' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '61' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '61' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '64' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '64' AND (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '66' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (RAWTONHEX(SUBSTR(NOTIFICATION_ID,1,1))) > '66' AND NOTIFICATION_ID IS NULL;

COMMIT;

DELETE 
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE SENDER_ID IS NULL;

COMMIT;
	
ALTER TABLE HOMEPAGE.NT_NOTIFICATION
	MODIFY SENDER_ID NOT NULL;

COMMIT;	
