-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

--------------------------------------------------------------------------------------
-- START: EMD FIX: changing the DOMAIN_AFFINITY VARCHAR2 TO BE CLOB 
--------------------------------------------------------------------------------------

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
ADD TMP_DOMAIN_AFFINITY CLOB;

COMMIT;

--reorg table HOMEPAGE.EMD_TRANCHE_INFO use NEWS4TMPTABSPACE;

UPDATE HOMEPAGE.EMD_TRANCHE_INFO SET TMP_DOMAIN_AFFINITY = DOMAIN_AFFINITY;

COMMIT;

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
DROP COLUMN DOMAIN_AFFINITY;

COMMIT;

--reorg table HOMEPAGE.EMD_TRANCHE_INFO use NEWS4TMPTABSPACE;

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
ADD DOMAIN_AFFINITY CLOB;

COMMIT;

--reorg table HOMEPAGE.EMD_TRANCHE_INFO use NEWS4TMPTABSPACE;

UPDATE HOMEPAGE.EMD_TRANCHE_INFO SET DOMAIN_AFFINITY = TMP_DOMAIN_AFFINITY;

COMMIT;

--reorg table HOMEPAGE.EMD_TRANCHE_INFO use NEWS4TMPTABSPACE;

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
DROP COLUMN TMP_DOMAIN_AFFINITY;

COMMIT;

--reorg table HOMEPAGE.EMD_TRANCHE_INFO use NEWS4TMPTABSPACE;

COMMIT;

--------------------------------------------------------------------------------------
-- END: EMD FIX: changing the DOMAIN_AFFINITY VARCHAR2 TO BE CLOB 
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
-- START: ADDING ENTRY_ID
--------------------------------------------------------------------------------------

-- 1
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT
	ADD ENTRY_ID VARCHAR2(36);

CREATE INDEX HOMEPAGE.NR_SRC_STORIES_ACT_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_ACT (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE"; 

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT
  	ADD CONSTRAINT FK_ENTRY_ID_ACT FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_ACT (ENTRY_ID); 
	
COMMIT;

-- 2
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG
	ADD ENTRY_ID VARCHAR2(36);
	
CREATE INDEX HOMEPAGE.NR_SRC_STORIES_BLG_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_BLG (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE";      

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG
  	ADD CONSTRAINT FK_ENTRY_ID_BLG FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_BLG (ENTRY_ID); 
	
COMMIT;

-- 3
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM
	ADD ENTRY_ID VARCHAR2(36);
	
CREATE INDEX HOMEPAGE.NR_SRC_STORIES_COM_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_COM (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE"; 

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM
  	ADD CONSTRAINT FK_ENTRY_ID_COM FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_COM (ENTRY_ID);  
	
COMMIT;

-- 4
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK
	ADD ENTRY_ID VARCHAR2(36);
	
CREATE INDEX HOMEPAGE.NR_SRC_STORIES_WIK_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_WIK (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE";

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK
  	ADD CONSTRAINT FK_ENTRY_ID_WIK FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_WIK (ENTRY_ID);
	
COMMIT;

-- 5
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF
	ADD ENTRY_ID VARCHAR2(36);
	
CREATE INDEX HOMEPAGE.NR_SRC_STORIES_PRF_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_PRF (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE";  

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF
  	ADD CONSTRAINT FK_ENTRY_ID_PRF FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_PRF (ENTRY_ID);
	
COMMIT;

-- 6
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP
	ADD ENTRY_ID VARCHAR2(36);
	
CREATE INDEX HOMEPAGE.NR_SRC_STORIES_HP_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_HP (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE";   

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP
  	ADD CONSTRAINT FK_ENTRY_ID_HP FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_HP (ENTRY_ID); 
	
COMMIT;

-- 7
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR
	ADD ENTRY_ID VARCHAR2(36);
	
CREATE INDEX HOMEPAGE.NR_SRC_STORIES_DGR_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_DGR (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE"; 

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR
  	ADD CONSTRAINT FK_ENTRY_ID_DGR FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_DGR (ENTRY_ID);
	
COMMIT;
    
-- 8
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE
	ADD ENTRY_ID VARCHAR2(36);
	
CREATE INDEX HOMEPAGE.NR_SRC_STORIES_FILE_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_FILE (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE";

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE
  	ADD CONSTRAINT FK_ENTRY_ID_FILE FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_FILE (ENTRY_ID); 
	
COMMIT;

-- 9
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM
	ADD ENTRY_ID VARCHAR2(36);
	
CREATE INDEX HOMEPAGE.NR_SRC_STORIES_FRM_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_FRM (ENTRY_ID) TABLESPACE "NEWSINDEXTABSPACE";

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM
  	ADD CONSTRAINT FK_ENTRY_ID_FRM FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_FRM (ENTRY_ID); 
	
COMMIT;

--------------------------------------------------------------------------------------
-- FIXING BOARD TABLES
-------------------------------------------------------------------------------------
DROP TABLE HOMEPAGE.BOARD_RECOMMENDATIONS;

DROP TABLE HOMEPAGE.BOARD_ATTACHMENTS;

DROP TABLE HOMEPAGE.BOARD_COMMENTS;

DROP TABLE HOMEPAGE.BOARD_READERS;

DROP TABLE HOMEPAGE.BOARD_ENTRIES;

COMMIT;

--------------------------------------
-- HOMEPAGE.BOARD_READERS to store the relationship between a reader and a status update
--------------------------------------
CREATE TABLE HOMEPAGE.BOARD_ENTRIES  (
	ENTRY_ID VARCHAR2(47) NOT NULL, -- the format will include in the pk also the creation time
	ENTRY_TYPE NUMBER(5,0),
	CATEGORY_TYPE NUMBER(5,0),
	SOURCE VARCHAR2(36),
	SOURCE_TYPE NUMBER(5,0),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_URL VARCHAR(2048) NOT NULL,
	CONTAINER_ID VARCHAR2(256),
	CONTAINER_NAME VARCHAR2(256),
	CREATION_DATE TIMESTAMP NOT NULL, -- used also by the seedlist, when something is created the update is equal to is created
	UPDATE_DATE TIMESTAMP NOT NULL, -- this field is used and queried from the the seedlist for initial and incremental index
	ACTOR_UUID VARCHAR2(36),
	N_COMMENTS NUMBER(5,0) DEFAULT 0 NOT NULL,
	N_RECOMMANDATIONS NUMBER(5,0) DEFAULT 0 NOT NULL ,
	IS_COMMUNITY_STORY NUMBER(5,0) DEFAULT 0,
	HAS_ATTACHMENT NUMBER(5,0) DEFAULT 0,
	TARGET_SUBJECT_ID VARCHAR2(256),
	TAGS VARCHAR2(1024),
	SL_IS_UPDATED NUMBER(5,0) DEFAULT 0 NOT NULL, -- this field is used by the seedlist
	SL_IS_DELETED NUMBER(5,0) DEFAULT 0 NOT NULL, -- this field is used by the seedlist
	SL_UPDATE_DATE TIMESTAMP NOT NULL, -- this field is used by the seedlist
	CONTENT BLOB NOT NULL
)
LOB (CONTENT) STORE AS (TABLESPACE BOARDLOBTABSPACE 
STORAGE (INITIAL 1M)
CHUNK 4000
NOCACHE NOLOGGING)
TABLESPACE "BOARDREGTABSPACE";

ALTER TABLE HOMEPAGE.BOARD_ENTRIES 
    ADD (CONSTRAINT PK_BRD_ENTRIES PRIMARY KEY(ENTRY_ID) USING INDEX TABLESPACE "BOARDINDEXTABSPACE");

CREATE INDEX HOMEPAGE.NEWS_BRD_UPDATE
    ON HOMEPAGE.BOARD_ENTRIES (UPDATE_DATE ASC) TABLESPACE "BOARDINDEXTABSPACE";
  
CREATE INDEX HOMEPAGE.NEWS_BRD_SL_UPDATE
    ON HOMEPAGE.BOARD_ENTRIES (SL_UPDATE_DATE ASC) TABLESPACE "BOARDINDEXTABSPACE";

CREATE UNIQUE INDEX HOMEPAGE.NEWS_BRD_ITEM
    ON HOMEPAGE.BOARD_ENTRIES (ITEM_ID) TABLESPACE "BOARDINDEXTABSPACE";    

COMMIT;

ALTER TABLE HOMEPAGE.BOARD_ENTRIES ENABLE ROW MOVEMENT;

--------------------------------------
-- HOMEPAGE.BOARD_READERS to store the relationship between a reader and a status update
--------------------------------------
CREATE TABLE HOMEPAGE.BOARD_READERS  (
	READER_ENTRY_ID VARCHAR2(47) NOT NULL, -- the format will include in the pk also the creation time
	READER_ID VARCHAR2(36) NOT NULL,
	IS_READER_COMM NUMBER(5,0) DEFAULT 0 NOT NULL,
	ENTRY_ID VARCHAR2(47) NOT NULL,
	IS_NETWORK_NEWS NUMBER(5,0) DEFAULT 0 NOT NULL,
	IS_FOLLOW_NEWS NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "BOARDREGTABSPACE";

ALTER TABLE HOMEPAGE.BOARD_READERS 
    ADD (CONSTRAINT PK_BRD_READERS PRIMARY KEY(READER_ENTRY_ID) USING INDEX TABLESPACE "BOARDINDEXTABSPACE");

ALTER TABLE HOMEPAGE.BOARD_READERS
	ADD CONSTRAINT FK_BRD_PERSON_ID FOREIGN KEY (READER_ID)
	REFERENCES HOMEPAGE.PERSON(PERSON_ID);

ALTER TABLE HOMEPAGE.BOARD_READERS
	ADD CONSTRAINT FK_BRD_ENTRY_ID FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);	    

CREATE INDEX HOMEPAGE.NEWS_BRD_READER_ID
    ON HOMEPAGE.BOARD_READERS  (READER_ID) TABLESPACE "BOARDINDEXTABSPACE";

CREATE INDEX HOMEPAGE.NEWS_BRD_ENTRY_ID
    ON HOMEPAGE.BOARD_READERS  (ENTRY_ID) TABLESPACE "BOARDINDEXTABSPACE";

ALTER TABLE HOMEPAGE.BOARD_READERS
	ADD CONSTRAINT NEWS_BRD_UNIQUE UNIQUE(READER_ID, ENTRY_ID);

COMMIT;

ALTER TABLE HOMEPAGE.BOARD_READERS ENABLE ROW MOVEMENT;

--------------------------------------
-- HOMEPAGE.BOARD_ATTACHMENTS to store the comments
--------------------------------------
CREATE TABLE HOMEPAGE.BOARD_COMMENTS  (
	COMMENT_ID VARCHAR2(47) NOT NULL, -- the format will include in the pk also the creation time
	ACTOR_UUID VARCHAR2(36),
	CREATION_DATE TIMESTAMP NOT NULL,
	ITEM_ID VARCHAR2(47),
	ITEM_CORRELATION_ID VARCHAR2(47),
	ITEM_URL VARCHAR2(2048),	
	CONTENT BLOB
)
LOB (CONTENT) STORE AS (TABLESPACE BOARDLOBTABSPACE 
STORAGE (INITIAL 1M)
CHUNK 4000
NOCACHE NOLOGGING)
TABLESPACE "BOARDREGTABSPACE";

ALTER TABLE HOMEPAGE.BOARD_COMMENTS 
    ADD (CONSTRAINT PK_BRD_COMMENT_ID PRIMARY KEY(COMMENT_ID) USING INDEX TABLESPACE "BOARDINDEXTABSPACE");

ALTER TABLE HOMEPAGE.BOARD_COMMENTS
	ADD CONSTRAINT FK_BRD_ITEM_COR_ID FOREIGN KEY (ITEM_CORRELATION_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);

CREATE INDEX HOMEPAGE.NEWS_BRD_ITEM_ID
    ON HOMEPAGE.BOARD_COMMENTS  (ITEM_ID) TABLESPACE "BOARDINDEXTABSPACE";

CREATE INDEX HOMEPAGE.NEWS_BRD_ITEM_CORR_ID
    ON HOMEPAGE.BOARD_COMMENTS  (ITEM_CORRELATION_ID) TABLESPACE "BOARDINDEXTABSPACE";

COMMIT;

ALTER TABLE HOMEPAGE.BOARD_COMMENTS ENABLE ROW MOVEMENT;

----------------------------------------------------------------
-- ADDING NR_STATUS_ATTACHMENT
----------------------------------------------------------------
CREATE TABLE HOMEPAGE.BOARD_ATTACHMENTS (
	ATTACHMENT_ID VARCHAR2(47) NOT NULL,
	ENTRY_ID VARCHAR2(47) NOT NULL, -- 47
	SOURCE_TYPE NUMBER(5,0) NOT NULL,
	ATTACHMENT_TYPE NUMBER(5,0),
	CREATION_DATE TIMESTAMP,
	NAME VARCHAR2(2048),
	DESCRIPTION VARCHAR2(4000),	
	TARGET_ID  VARCHAR2(256),
	TARGET_URL VARCHAR2(2048),
	META_DATA VARCHAR2(4000)
)
TABLESPACE "BOARDREGTABSPACE";

ALTER TABLE HOMEPAGE.BOARD_ATTACHMENTS 
    ADD (CONSTRAINT PK_BRD_ATTACH_ID PRIMARY KEY(ATTACHMENT_ID) USING INDEX TABLESPACE "BOARDINDEXTABSPACE");

ALTER TABLE HOMEPAGE.BOARD_ATTACHMENTS
	ADD CONSTRAINT FK_BRD_AT_ENTRY_ID FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);

CREATE INDEX HOMEPAGE.NEWS_BRD_ENTRY_IDX
    ON HOMEPAGE.BOARD_ATTACHMENTS (ENTRY_ID) TABLESPACE "BOARDINDEXTABSPACE";
	
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_ATTACHMENTS ENABLE ROW MOVEMENT;

--------------------------------------
-- HOMEPAGE.BOARD_RECOMMANDATIONS to store the relationship between a board entries and something which has been recommended
---------------------------------------
CREATE TABLE HOMEPAGE.BOARD_RECOMMENDATIONS  (
	RECOMMENDATION_ID VARCHAR2(47) NOT NULL, --primary key
	RECOMMENDER_ID VARCHAR2(36) NOT NULL, -- PERSON_ID of the recommender, FK to PERSON table
	ENTRY_ID VARCHAR2(47) NOT NULL,
	SOURCE_TYPE NUMBER(5,0) NOT NULL, 
	CREATION_DATE TIMESTAMP
)
TABLESPACE "BOARDREGTABSPACE";

ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS 
    ADD (CONSTRAINT PK_BRD_RECOMM_ID PRIMARY KEY(RECOMMENDATION_ID) USING INDEX TABLESPACE "BOARDINDEXTABSPACE");

CREATE INDEX HOMEPAGE.BRD_REC_STORY_ID
    ON HOMEPAGE.BOARD_RECOMMENDATIONS (ENTRY_ID) TABLESPACE "BOARDINDEXTABSPACE";
    
CREATE UNIQUE INDEX HOMEPAGE.BRD_RECOM_ENTRY_ID
    ON HOMEPAGE.BOARD_RECOMMENDATIONS (RECOMMENDER_ID, ENTRY_ID) TABLESPACE "BOARDINDEXTABSPACE";

COMMIT;

ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS ENABLE ROW MOVEMENT;



------------------------------------------------------
-- CREATE VIEW NR_ENTRIES
------------------------------------------------------
CREATE VIEW HOMEPAGE.NR_ENTRIES AS (
    SELECT * FROM HOMEPAGE.NR_ENTRIES_ACT
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ENTRIES_BLG
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ENTRIES_COM
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ENTRIES_WIK
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ENTRIES_PRF
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ENTRIES_HP
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ENTRIES_DGR
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ENTRIES_FILE
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ENTRIES_FRM
);

