-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

ALTER TABLE HOMEPAGE.NR_NEWS_RECORDS
    MODIFY CONTAINER_ID 
    VARCHAR2(256);

ALTER TABLE HOMEPAGE.NR_STORIES
    MODIFY R_META_TEMPLATE
    VARCHAR2(4000) DEFAULT '' NOT NULL;

-- NEWS REPOSITORY
{ORA_GRANT_START} HOMEPAGE.NR_SOURCE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SUBSCRIPTION {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_RECORDS {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_TEMPLATE {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMGR {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMPR {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SCHEDULER_TASK {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_SCHEDULER_TREG {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_CATEGORY_TYPE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_SAVED {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_DISCOVERY {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_NETWORK {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_COMMENT {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_CONTENT {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NEWS_COMMENT_CONTENT {ORA_GRANT_STOP}

{ORA_GRANT_START} HOMEPAGE.NR_RESOURCE_TYPE  {ORA_GRANT_STOP}	
{ORA_GRANT_START} HOMEPAGE.NR_RESOURCE  {ORA_GRANT_STOP}  
{ORA_GRANT_START} HOMEPAGE.NR_FOLLOWS  {ORA_GRANT_STOP}	
{ORA_GRANT_START} HOMEPAGE.NR_COMM_FOLLOW  {ORA_GRANT_STOP}	  
{ORA_GRANT_START} HOMEPAGE.NR_ORGPERSON_FOLLOW  {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_STORIES  {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_FOLLOWED_STORIES  {ORA_GRANT_STOP}    
{ORA_GRANT_START} HOMEPAGE.NR_COMM_STORIES  {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_ORGPERSON_STORIES  {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_STORIES_CONTENT  {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.NR_NETWORK  {ORA_GRANT_STOP}	

{ORA_GRANT_START} HOMEPAGE.EMD_FREQUENCY_TYPE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.EMD_RESOURCE_PREF {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.EMD_TRANCHE {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.EMD_TRANCHE_INFO {ORA_GRANT_STOP}
{ORA_GRANT_START} HOMEPAGE.EMD_EMAIL_PREFS {ORA_GRANT_STOP}    
