-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-----------------------------------------------
-- UPDATING SOURCE_TYPE TABLE
-----------------------------------------------
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE
	ADD IS_ENABLE NUMBER(5,0);

COMMIT;
	
UPDATE HOMEPAGE.NR_SOURCE_TYPE SET IS_ENABLE = 1;

COMMIT;

----------------------------------------------------------------------
-- [START] INDEX CLEANUP
----------------------------------------------------------------------

-----------------------------------------------
-- FIXING INDEXES ON COMM_STORIES TABLE
-----------------------------------------------
DROP INDEX  HOMEPAGE.NR_COMM_STORIES_COM_ID;

CREATE INDEX HOMEPAGE.NR_COMM_STORIES_CDATE
    ON HOMEPAGE.NR_COMM_STORIES (COMMUNITY_ID, CREATION_DATE ASC) TABLESPACE NEWSINDEXTABSPACE; 

CREATE INDEX HOMEPAGE.NR_COM_STORY_ID			ON	HOMEPAGE.NR_COMM_STORIES (COMMUNITY_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;

COMMIT;

-- DROPPING UNUSED INDEXES FOR READERS TABLES
DROP INDEX  HOMEPAGE.RESPONSES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.PROFILES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.COMMUNITIES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.ACTIVITIES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.BLOGS_STORIES_CIDX;
DROP INDEX  HOMEPAGE.BOOKMARKS_STORIES_CIDX;
DROP INDEX  HOMEPAGE.FILES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.FORUMS_STORIES_CIDX;
DROP INDEX  HOMEPAGE.WIKIS_STORIES_CIDX;
DROP INDEX  HOMEPAGE.TAGS_STORIES_CIDX;

-- ADDING INDEXES used to retrieve the evidence and delete records
CREATE INDEX HOMEPAGE.NR_RESP_READER_STORY 		ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_PRO_READER_STORY 		ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_COM_READER_STORY 		ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_ACT_READER_STORY 		ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_BLG_READER_STORY 		ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_BOOK_READER_STORY 		ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_FILES_READER_STORY 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_FORUMS_READER_STORY 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_WIKIS_READER_STORY 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;
CREATE INDEX HOMEPAGE.NR_TAGS_READER_STORY 		ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;



COMMIT;

-- DROPPING UNUSED INDEXES FOR ENTRIES TABLES
DROP INDEX  HOMEPAGE.NR_ENTRIES_ACT_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_BLG_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_COM_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_WIK_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_PRF_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_HP_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_DGR_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_FILE_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_FRM_SRC;

-- DROPPING UNUSED INDEXES FOR STORIES TABLES
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_ACT_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_BLG_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_COM_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_WIK_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_PRF_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_HP_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_DGR_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_FILE_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_FRM_SIDX;




----------------------------------------------------------------------
-- [END] INDEX CLEANUP
----------------------------------------------------------------------

---------------------------------------------------------
-- [START] EMD INIT DATA
---------------------------------------------------------
UPDATE HOMEPAGE.EMD_TRANCHE	SET 	
		IS_LOCKED = 0,
		IS_LOCKED_DAILY = 0,
		IS_LOCKED_WEEKLY = 0;
---------------------------------------------------------
-- [END] EMD INIT DATA
---------------------------------------------------------

--------------------------------------------------------
-- [START] UPDATING NR_STORIES TABLES 
--------------------------------------------------------
-- Adding to story table:
-- i) MESSAGE
-- ii) EVENT_TIME
--- iii) VERB
--------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);

COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM
	ADD MESSAGE VARCHAR2(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR2 (128);
	

COMMIT;	
--------------------------------------------------------
-- [END] UPDATING NR_STORIES TABLES
--------------------------------------------------------

--------------------------------------------------------
-- [START] UPDATING NR_ENTRIES TABLES ADDING
--------------------------------------------------------
--  FIRST: we need to move it do a bigger table space
-- i) Adding preview URL
-- ii) Adding status update column
-- iii) Adding JSON_META_DATA column
-- iv) Event time
--------------------------------------------------------
------------------------------------------------------------------------------------
-- CREATING NEW TABLES (Those new tables will also have the new required fields)
-- Which are: MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA
--	MESSAGE VARCHAR2(4000),
--	PREVIEW_IMAGE_URL VARCHAR2(2048),
--	JSON_META_DATA VARCHAR2(4000),
--	EVENT_TIME TIMESTAMP,
------------------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_ENTRIES_ACT
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_BLG
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_COM
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_WIK
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_PRF
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_HP
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_DGR
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_FILE
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_FRM
	ADD MESSAGE VARCHAR2(4000)
	ADD PREVIEW_IMAGE_URL VARCHAR2(2048)
	ADD JSON_META_DATA VARCHAR2 (4000)
	ADD EVENT_TIME TIMESTAMP;

COMMIT;

--------------------------------------------------------
-- [END] UPDATING NR_ENTRIES TABLES
--------------------------------------------------------


---------------------------------------------
-- Adding VERB and USE_IN_ROLLUP columns to the readers tables
---------------------------------------------
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_STORIES
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;
	

COMMIT;

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;
	
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;	

COMMIT;

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ADD  		USE_IN_ROLLUP 		NUMBER(5,0)
	ADD			IS_NETWORK			NUMBER(5,0)
	ADD			IS_FOLLOWER			NUMBER(5,0)
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

-----------------------------------------------------------
-- ADDING A NR_STATUS_UPDATE_READER
-----------------------------------------------------------
-- Adding four new categories for ui rendering of actianable stories (we don't need to add source here as they already exist)
INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('status_update_x8b0bx51af2ddef2cd', 11, '%status_update', 'status_update');

--------------------------------------------------------------------------
-- 11) HOMEPAGE.NR_STATUS_UPDATE_READERS
--------------------------------------------------------------------------	
CREATE TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS (
	FOLLOWED_STORY_ID VARCHAR2(36) NOT NULL,
	READER_ID VARCHAR2(36) NOT NULL,
	CATEGORY_TYPE NUMBER(5,0) NOT NULL,
	SOURCE VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(256),
	ITEM_ID VARCHAR2(36),
	RESOURCE_TYPE NUMBER(5,0) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR2(36) NOT NULL,
	SOURCE_TYPE NUMBER(5,0),
	USE_IN_ROLLUP NUMBER(5,0),
	IS_NETWORK	NUMBER(5,0),
	IS_FOLLOWER	NUMBER(5,0),
	EVENT_TIME TIMESTAMP,
   	CONSTRAINT  CK_CAT11_TYPE
    			CHECK
    			(CATEGORY_TYPE = 11)
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS 
    ADD (CONSTRAINT PK_SU_READERS PRIMARY KEY(FOLLOWED_STORY_ID) USING INDEX TABLESPACE "NEWSINDEXTABSPACE");
    
CREATE INDEX HOMEPAGE.SU_STORIES_IDX
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, CREATION_DATE ASC) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.SU_STORIES_SIDX
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.SU_STORIES_ITEM_ID
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ITEM_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.SU_STORIES_READER_STORY
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;	

COMMIT;


ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS  		ENABLE ROW MOVEMENT;

---------------------------------------------------------
-- [START] THIRD PARTY EVENTS HANDLING CHANGES
---------------------------------------------------------
----------------------------------------------------------
-- Adding ACTIVITY_META_DATA to NR_STORIES_CONTENT table
----------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT
	ADD ACTIVITY_META_DATA CLOB
	LOB (ACTIVITY_META_DATA) STORE AS (TABLESPACE NEWSLOBTABSPACE 
	STORAGE (INITIAL 1M)
	CHUNK 4000
	NOCACHE NOLOGGING);
	

COMMIT;
----------------------------------------------------------

---------------------------------------------------------------------------------
-- INSERTING THIRD PARTY CATEGORIES AND SOURCES
---------------------------------------------------------------------------------
-- Adding a new category (used from UI rendering) and source (used a source of stories from component)
INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('ext_9cax4cc4x8b0bx51af2ddef2cd', 12, '%external', 'external');

INSERT INTO HOMEPAGE.NR_SOURCE_TYPE (SOURCE_TYPE_ID, SOURCE_TYPE, SOURCE_TYPE_NAME, SOURCE_TYPE_DESC, IS_ENABLE)
VALUES ('ext_____fdfdc9cax80bx51af2', 100, '%external', 'external', 0);

---------------------------------------------------------
-- 12) ADDING A NR_EXTERNAL_READERS READER TABLE
---------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_EXTERNAL_READERS (
	FOLLOWED_STORY_ID VARCHAR2(36) NOT NULL,
	READER_ID VARCHAR2(36) NOT NULL,
	CATEGORY_TYPE NUMBER(5,0) NOT NULL,
	SOURCE VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(256),
	ITEM_ID VARCHAR2(36),
	RESOURCE_TYPE NUMBER(5,0) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR2(36) NOT NULL,
	SOURCE_TYPE NUMBER(5,0),
	USE_IN_ROLLUP NUMBER(5,0),
	IS_NETWORK	NUMBER(5,0),
	IS_FOLLOWER	NUMBER(5,0),
	EVENT_TIME TIMESTAMP,
   	CONSTRAINT  CK_CAT12_TYPE
    			CHECK
    			(CATEGORY_TYPE = 12)
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS 
    ADD (CONSTRAINT PK_EXT_STORIES PRIMARY KEY(FOLLOWED_STORY_ID)  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");
    
CREATE INDEX HOMEPAGE.EXT_STORIES_IDX
    ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, CREATION_DATE ASC) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.EXT_STORIES_SIDX
    ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.EXT_STORIES_ITEM_ID
    ON HOMEPAGE.NR_EXTERNAL_READERS (ITEM_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.EXT_STORIES_READER_STORY
    ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;    


ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS  ENABLE ROW MOVEMENT;

--------------------------------------------------------------
-- ADDING A NR_ENTRIES_EXTERNAL TABLE
--------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ENTRIES_EXTERNAL  (
	ENTRY_ID VARCHAR2(36) NOT NULL,
	SOURCE VARCHAR2(36) NOT NULL,
	SOURCE_TYPE NUMBER(5,0),
	CONTAINER_ID VARCHAR2(256),
	CONTAINER_NAME VARCHAR2(256),
	CONTAINER_URL VARCHAR2(2048),
	ITEM_ID VARCHAR2(36) NOT NULL,
	ITEM_NAME VARCHAR2(256),
	ITEM_URL VARCHAR2(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR2(1024),
	N_COMMENTS NUMBER(5,0) DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS NUMBER(5,0) DEFAULT 0 NOT NULL,
	N_ATTACHMENTS NUMBER(5,0) DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR2(512),
	LAST_RECOMMENDER_ID VARCHAR2(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR2(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR2(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR2(256),
	LAST_AUTHOR_COMMENT VARCHAR2(36),
	PREV_COMMENT_ID VARCHAR2(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR2(256),
	PREV_AUTHOR_COMMENT VARCHAR2(36),
	TARGET_SUBJECT_ID VARCHAR2(36),
	ITEM_ATOM_URL VARCHAR2(2048),
	MESSAGE VARCHAR2(4000),
	PREVIEW_IMAGE_URL VARCHAR2(2048),
	JSON_META_DATA VARCHAR2(4000),
	EVENT_TIME TIMESTAMP,
	CONSTRAINT   	CK_ENT_SRC10_TYPE
    				CHECK
    				(SOURCE_TYPE = 10)
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_ENTRIES_EXTERNAL 
    ADD (CONSTRAINT PK_EXT_ENTRY_ID PRIMARY KEY(ENTRY_ID)  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

CREATE INDEX HOMEPAGE.NR_ENTRIES_EXT_CONT
    ON HOMEPAGE.NR_ENTRIES_EXTERNAL (CONTAINER_ID) TABLESPACE NEWSINDEXTABSPACE;
    
COMMIT;


ALTER TABLE HOMEPAGE.NR_ENTRIES_EXTERNAL  ENABLE ROW MOVEMENT;

----------------------------------------------------
-- ADDING A NR_SRC_STORIES_EXTERNAL TABLE
----------------------------------------------------
CREATE TABLE HOMEPAGE.NR_SRC_STORIES_EXTERNAL (
	STORY_ID VARCHAR2(36) NOT NULL,
	EVENT_NAME VARCHAR2(256) NOT NULL,
	SOURCE VARCHAR2(36),
	CONTAINER_ID VARCHAR2(256),	
	CONTAINER_NAME VARCHAR2(256),
	CONTAINER_URL VARCHAR2(2048),
	ITEM_ATOM_URL VARCHAR2(2048),
	ITEM_CORRELATION_ID VARCHAR2(36),
	CREATION_DATE TIMESTAMP NOT NULL,
	BRIEF_DESC VARCHAR2(512),
	ACTOR_UUID VARCHAR2(36),
	EVENT_RECORD_UUID VARCHAR2(36) NOT NULL,
	TAGS VARCHAR2(1024),
	META_TEMPLATE VARCHAR2(4000) DEFAULT '' NOT NULL,
	TEXT_META_TEMPLATE VARCHAR2(1024),
	R_META_TEMPLATE VARCHAR2(4000),
	R_TEXT_META_TEMPLATE VARCHAR2(1024),
	IS_COMMUNITY_STORY NUMBER(5,0) DEFAULT 0,
	ITEM_CORRELATION_NAME VARCHAR2(256),
	HAS_ATTACHMENT NUMBER(5,0) DEFAULT 0,
	SOURCE_TYPE NUMBER(5,0),
	ENTRY_ID VARCHAR2(36),
	MESSAGE VARCHAR2(4000),
	EVENT_TIME TIMESTAMP,
	VERB VARCHAR2 (128),	
	CONSTRAINT   	CK_SRC100_TYPE
    				CHECK
    				(SOURCE_TYPE >= 10)
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_EXTERNAL
    ADD (CONSTRAINT PK_EXT_STORY_ID PRIMARY KEY(STORY_ID)  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_EXTERNAL
  	ADD CONSTRAINT FK_ENTRY_ID_EXT FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_EXTERNAL (ENTRY_ID);    

CREATE INDEX HOMEPAGE.SRC_STORIES_EXT_DATE
	ON HOMEPAGE.NR_ENTRIES_EXTERNAL (CREATION_DATE DESC) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.SRC_EXT_CONTAINER_ID
    ON HOMEPAGE.NR_SRC_STORIES_EXTERNAL (CONTAINER_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.SRC_EXT_ITEM_CORR_ID
    ON HOMEPAGE.NR_SRC_STORIES_EXTERNAL (ITEM_CORRELATION_ID) TABLESPACE NEWSINDEXTABSPACE;
    
CREATE INDEX HOMEPAGE.SRC_STORIES_EXT_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_EXTERNAL (ENTRY_ID) TABLESPACE NEWSINDEXTABSPACE;  


ALTER TABLE HOMEPAGE.NR_SRC_STORIES_EXTERNAL  ENABLE ROW MOVEMENT;

---------------------------------------------------------
-- [END] THIRD PARTY EVENTS HANDLING CHANGES
---------------------------------------------------------


---------------------------------------------------------
-- [START] ACTIONABLE
---------------------------------------------------------
-- Adding four new categories for ui rendering of actianable stories
INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('actionable_saved_stories_4cc4x8b0bx', 13, '%actionable_saved_stories', 'actionable_saved_stories');

INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('actionable_directed_notification_bx', 14, '%actionable_directed_notification', 'actionable_directed_notification');

INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('actionable_todo_______cax4cc4x8b0bx', 15, '%actionable_todo', 'actionable_todo');

INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('actionable_action_required__4x8b0bx', 16, '%actionable_action_required', 'actionable_action_required');

COMMIT;


---------------------------------------------------------
-- ADDING NR_ACTIONABLE_READERS READER TABLE
---------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ACTIONABLE_READERS (
	ACTIONABLE_READER_ID VARCHAR2(36) NOT NULL,
	READER_ID VARCHAR2(36) NOT NULL,
	CATEGORY_TYPE NUMBER(5,0) NOT NULL,
	SOURCE VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(256),
	ITEM_ID VARCHAR2(36),
	RESOURCE_TYPE NUMBER(5,0) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR2(36) NOT NULL,
	SOURCE_TYPE NUMBER(5,0),
	USE_IN_ROLLUP NUMBER(5,0),
	IS_NETWORK	NUMBER(5,0),
	IS_FOLLOWER	NUMBER(5,0),
	EVENT_TIME TIMESTAMP,
	NOTE_TEXT VARCHAR2(4000),
	NOTE_UPDATE_DATE TIMESTAMP,
	CONSTRAINT   	CK_CAT_ACTION_TYPE
    				CHECK
    				(CATEGORY_TYPE >= 13 AND CATEGORY_TYPE <= 16)	
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS 
    ADD (CONSTRAINT PK_ACTION_STORIES PRIMARY KEY (ACTIONABLE_READER_ID)  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");
    
CREATE INDEX HOMEPAGE.ACTION_READER_STORIES_IDX
    ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, CREATION_DATE ASC) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.ACTION_READER_SIDX
    ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.ACTION_READER_ITEM_ID
    ON HOMEPAGE.NR_ACTIONABLE_READERS (ITEM_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE UNIQUE INDEX HOMEPAGE.ACTION_READER_STORY
    ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, STORY_ID) TABLESPACE NEWSINDEXTABSPACE;  

    

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ENABLE ROW MOVEMENT;

COMMIT;

---------------------------------------------------------
-- ADDING NR_ACTIONABLE_STORIES TABLE
---------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ACTIONABLE_STORIES (
	STORY_ID VARCHAR2(36) NOT NULL,
	EVENT_NAME VARCHAR2(256) NOT NULL,
	SOURCE VARCHAR2(36),
	CONTAINER_ID VARCHAR2(256),	
	CONTAINER_NAME VARCHAR2(256),
	CONTAINER_URL VARCHAR2(2048),
	ITEM_ATOM_URL VARCHAR2(2048),
	ITEM_CORRELATION_ID VARCHAR2(36), -- NEW	
	CREATION_DATE TIMESTAMP NOT NULL,
	BRIEF_DESC VARCHAR2(512),
	ACTOR_UUID VARCHAR2(36),
	EVENT_RECORD_UUID VARCHAR2(36) NOT NULL,
	TAGS VARCHAR2(1024),
	META_TEMPLATE VARCHAR2(4000) DEFAULT '' NOT NULL,
	TEXT_META_TEMPLATE VARCHAR2(1024),
	R_META_TEMPLATE VARCHAR2(4000),
	R_TEXT_META_TEMPLATE VARCHAR2(1024),
	IS_COMMUNITY_STORY NUMBER(5,0) DEFAULT 0,
	ITEM_CORRELATION_NAME VARCHAR2(256),
	HAS_ATTACHMENT NUMBER(5,0) DEFAULT 0,
	SOURCE_TYPE NUMBER(5,0),
	ENTRY_ID VARCHAR2(36),
	MESSAGE VARCHAR2(4000),
	EVENT_TIME TIMESTAMP,
	VERB VARCHAR2 (128),
	CONSTRAINT   	CK_SRC_ACTION_TYPE
    				CHECK
    				(SOURCE_TYPE >= 1 AND SOURCE_TYPE <= 10 )
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_STORIES
    ADD (CONSTRAINT PK_ACTION_STORY_ID PRIMARY KEY(STORY_ID)  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

CREATE INDEX HOMEPAGE.ACTION_CONTAINER_ID
    ON HOMEPAGE.NR_ACTIONABLE_STORIES (CONTAINER_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.ACTION_ITEM_CORR_ID
    ON HOMEPAGE.NR_ACTIONABLE_STORIES (ITEM_CORRELATION_ID) TABLESPACE NEWSINDEXTABSPACE;

CREATE INDEX HOMEPAGE.ACTION_ACT_ENTRYID
    ON HOMEPAGE.NR_ACTIONABLE_STORIES (ENTRY_ID) TABLESPACE NEWSINDEXTABSPACE;    



ALTER TABLE HOMEPAGE.NR_ACTIONABLE_STORIES ENABLE ROW MOVEMENT;

COMMIT;
	
---------------------------------------------------------
-- [END] ACTIONABLE
---------------------------------------------------------

DROP VIEW HOMEPAGE.NR_CATEGORIES_READERS;
    
--------------------------------------------------------------------------------------------------------------
-- CREATE THE VIEW FOR ALL THE STORIES
--------------------------------------------------------------------------------------------------------------
CREATE VIEW HOMEPAGE.NR_CATEGORIES_READERS AS (
    SELECT * FROM HOMEPAGE.NR_RESPONSES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_PROFILES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_COMMUNITIES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ACTIVITIES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_BLOGS_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_BOOKMARKS_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_FILES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_FORUMS_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_WIKIS_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_TAGS_READERS
    	UNION ALL
    SELECT * FROM HOMEPAGE.NR_STATUS_UPDATE_READERS
    	UNION ALL
	SELECT * FROM HOMEPAGE.NR_EXTERNAL_READERS    	
);


