-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

----------------------------------------------------------------------
-- 1) ADDING RESOURCE TYPE
----------------------------------------------------------------------

------------
--- START INSERT NR_RESOURCE_TYPE
------------

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('responses_0fdf1xc9cax4cc4x8b0bx51af2', 1, '%responses', 'responses');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('activity_c9cax4cc4x8b0bx51af2ddef2cd', 2, '%activity', 'activity');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('blog________0f1xc9cax4cc4x8b0bx51af2', 3, '%blog', 'blog');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('community____f1xc9cax4cc4x8b0bx51af2', 4, '%community', 'community');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('file_change_ds1xc9cax4cc4x8b0bx51af2', 5, '%file_change', 'file_change');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('file_comment_df1xc9cax4cc4x8b0bx5af2', 6, '%file_comment', 'file_comment');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('file_collection_fdfca4cc4x8b0bx51af2', 7, '%file_collection', 'file_collection');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('forum_topic_fdfdxc9cax4cc4xb0bx51af2', 8, '%forum_topic', 'forum_topic');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('forum_0fdsfdsf1xc9cax4cc4xb0bxd51af2', 9, '%forum', 'forum');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('person_0f1xc9cax4cc4xb0bx51af2def2cd', 10, '%person', 'person');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('wiki_page_change_fdfdc9cax8b0bx51af2', 11, '%wiki_page_change', 'wiki_page_change');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('wiki_page_comment_0cax4c4x8b0bx51af2', 12, '%wiki_page_comment', 'wiki_page_comment');

INSERT INTO HOMEPAGE.NR_RESOURCE_TYPE (RESOURCE_TYPE_ID, RESOURCE_TYPE, RESOURCE_TYPE_NAME, RESOURCE_TYPE_DESC)
VALUES ('tag_0f1xc9cax4cc4x8cdb0bx51f2ddef2cd', 13, '%tag', 'tag');

------------
--- END INSERT NR_RESOURCE_TYPE
------------

----------------------------------------------------------------------
-- 2) CHANGE FROM THE USE OF RESOURCE_TYPE_ID to USE RESOURCE_TYPE AND ADDING ITEM_ID TO NR_COMM_STORIES
----------------------------------------------------------------------

-- a) NR_FOLLOWED_STORIES
DROP TABLE HOMEPAGE.NR_FOLLOWED_STORIES;
----------------------------------------------------------------------
-- HOMEPAGE.NR_FOLLOWED_STORIES
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_FOLLOWED_STORIES (
	FOLLOWED_STORY_ID VARCHAR2(36) NOT NULL,
	READER_ID VARCHAR2(36) NOT NULL,
	CATEGORY_TYPE NUMBER(5,0) NOT NULL,
	SOURCE VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(36),
	ITEM_ID VARCHAR2(36), -- I don't think we need SOURCE_ID here, this should be in the SOURCE table?
	RESOURCE_TYPE NUMBER(5,0) NOT NULL, -- ???? what is this ??
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR2(36) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_FOLLOWED_STORIES
    ADD (CONSTRAINT "PK_F_STORY_ID" PRIMARY KEY("FOLLOWED_STORY_ID")  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_FOLLOWED_STORIES
    ADD CONSTRAINT "FK_F_STORY_ID" FOREIGN KEY ("STORY_ID")
	REFERENCES HOMEPAGE.NR_STORIES ("STORY_ID");

ALTER TABLE HOMEPAGE.NR_FOLLOWED_STORIES ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.NR_FOLLOWED_STORIES  {ORA_GRANT_STOP}  

-- b) NR_COMM_STORIES
DROP TABLE HOMEPAGE.NR_COMM_STORIES;
----------------------------------------------------------------------
-- HOMEPAGE.NR_COMM_STORIES
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_COMM_STORIES (
	COMM_STORY_ID VARCHAR2(36) NOT NULL,
	COMMUNITY_ID VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(36),
	ITEM_ID VARCHAR2(36),
	RESOURCE_TYPE NUMBER(5,0) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR2(36) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_COMM_STORIES
    ADD (CONSTRAINT "PK_F_CSTORY_ID" PRIMARY KEY("COMM_STORY_ID")  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_COMM_STORIES
    ADD CONSTRAINT "FK_COMM_STORY_ID" FOREIGN KEY ("STORY_ID")
	REFERENCES HOMEPAGE.NR_STORIES ("STORY_ID");

ALTER TABLE HOMEPAGE.NR_COMM_STORIES ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.NR_COMM_STORIES  {ORA_GRANT_STOP}

-- c) NR_ORGPERSON_STORIES
DROP TABLE HOMEPAGE.NR_ORGPERSON_STORIES;
----------------------------------------------------------------------
-- HOMEPAGE.NR_ORGPERSON_STORIES
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ORGPERSON_STORIES (
	ORGPERSON_STORY_ID VARCHAR2(36) NOT NULL,
	ORGANIZATION_ID VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(36),
	ITEM_ID VARCHAR2(36),
	RESOURCE_TYPE NUMBER(5,0) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR2(36) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_ORGPERSON_STORIES
    ADD (CONSTRAINT "PK_ORGP_STORY_ID" PRIMARY KEY("ORGPERSON_STORY_ID")  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_ORGPERSON_STORIES
    ADD CONSTRAINT "FK_ORGP_STORY_ID" FOREIGN KEY ("STORY_ID")
	REFERENCES HOMEPAGE.NR_STORIES ("STORY_ID");

ALTER TABLE HOMEPAGE.NR_ORGPERSON_STORIES ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.NR_ORGPERSON_STORIES  {ORA_GRANT_STOP}

------------------------------------------------------
-- 3) REMOVING THE IS_ACTIVE FLAG and REDO the VIEW
------------------------------------------------------
--ALTER TABLE HOMEPAGE.PERSON DROP COLUMN IS_ACTIVE;

------------------------------------------------------
-- 4) ADDING FK TO THE NR_RESOURCE for CATEGORY_TYPE AND - RESOURCE TYPE
------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_RESOURCE
    ADD CONSTRAINT "FK_RES_RES_TYPE" FOREIGN KEY ("RESOURCE_TYPE")
	REFERENCES HOMEPAGE.NR_RESOURCE_TYPE ("RESOURCE_TYPE");
	
ALTER TABLE HOMEPAGE.NR_RESOURCE
    ADD CONSTRAINT "FK_RES_CAT_TYPE" FOREIGN KEY ("CATEGORY_TYPE")
	REFERENCES HOMEPAGE.NR_CATEGORY_TYPE ("CATEGORY_TYPE");
	
------------------------------------------------------
-- 5) ADDING NR_NETWORK TABLE TO MANAGE PEOPLE IN YOUR NETWORK
------------------------------------------------------

----------------------------------------------------------------------
-- HOMEPAGE.NR_NETWORK
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_NETWORK (
	NETWORK_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	COLLEAGUE_ID VARCHAR2(36) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD (CONSTRAINT "PK_NETWORK_ID" PRIMARY KEY("NETWORK_ID")  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD CONSTRAINT "FK_NTW_PERS_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");

ALTER TABLE HOMEPAGE.NR_NETWORK
    ADD CONSTRAINT "FK_NTW_COLL_ID" FOREIGN KEY ("COLLEAGUE_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");

ALTER TABLE HOMEPAGE.NR_NETWORK ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.NR_NETWORK  {ORA_GRANT_STOP}	
	
------------------------------------------------------
-- 6) REMOVING OLD EMAIL DIGEST TABLES
------------------------------------------------------
DROP TABLE HOMEPAGE.EMD_JOBS_STATS;
DROP TABLE HOMEPAGE.EMD_JOBS;
DROP TABLE HOMEPAGE.EMD_RECIPIENTS;

------------------------------------------------------
-- 7) ADDING NEW EMAIL DIGEST TABLES
------------------------------------------------------

-----------------------------------------
-- HOMEPAGE.EMD_FREQUENCY_TYPE
-----------------------------------------
CREATE TABLE HOMEPAGE.EMD_FREQUENCY_TYPE (
	FREQUENCY_TYPE_ID VARCHAR2(36) NOT NULL,
	FREQUENCY_TYPE_NAME VARCHAR2(36) NOT NULL, -- this is externalized
	FREQUENCY_TYPE NUMBER(5,0) NOT NULL,
	FREQUENCY_TYPE_DESC VARCHAR2(256) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE 
  	ADD (CONSTRAINT "PK_FRQ_TYPE_ID" PRIMARY KEY("FREQUENCY_TYPE_ID")  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE
	ADD CONSTRAINT FRQ_TYPE_UNIQUE UNIQUE (FREQUENCY_TYPE);

ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.EMD_FREQUENCY_TYPE  {ORA_GRANT_STOP} 	

-----------------------------------------
-- HOMEPAGE.EMD_RESOURCE_PREF
-----------------------------------------
CREATE TABLE HOMEPAGE.EMD_RESOURCE_PREF (
	RESOURCE_PREF_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	RESOURCE_TYPE NUMBER(5,0) NOT NULL,
	FREQUENCY_TYPE NUMBER(5,0) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF 
  	ADD (CONSTRAINT "PK_RES_PREF_ID" PRIMARY KEY("RESOURCE_PREF_ID")  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF
    ADD CONSTRAINT "FK_RES_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF
    ADD CONSTRAINT "FK_RES_FRQ_TYPE" FOREIGN KEY ("FREQUENCY_TYPE")
	REFERENCES HOMEPAGE.EMD_FREQUENCY_TYPE ("FREQUENCY_TYPE");

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.EMD_RESOURCE_PREF  {ORA_GRANT_STOP}  	 	

-----------------------------------------
-- HOMEPAGE.EMD_TRANCHE
-----------------------------------------
CREATE TABLE HOMEPAGE.EMD_TRANCHE (
	TRANCHE_ID VARCHAR2(36) NOT NULL,
	SEQ_NUMBER SMALLINT NOT NULL,
	LAST_PROCESSED_DAILY TIMESTAMP,
	LAST_PROCESSED_WEEKLY TIMESTAMP,
	IS_LOCKED NUMBER(5,0) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.EMD_TRANCHE 
  	ADD (CONSTRAINT "PK_TRANCHE_ID" PRIMARY KEY("TRANCHE_ID")  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.EMD_TRANCHE 
	ADD CONSTRAINT SEQ_NUMBER_UNIQUE UNIQUE (SEQ_NUMBER);  	

ALTER TABLE HOMEPAGE.EMD_TRANCHE ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.EMD_TRANCHE  {ORA_GRANT_STOP}

-----------------------------------------
-- HOMEPAGE.EMD_TRANCHE_INFO
-----------------------------------------
CREATE TABLE HOMEPAGE.EMD_TRANCHE_INFO (
	TRANCHE_INFO_ID VARCHAR2(36) NOT NULL,
	TRANCHE_ID VARCHAR2(36) NOT NULL,
	COUNT_PROCESSED_DAILY NUMBER(5,0),
	COUNT_PROCESSED_WEEKLY NUMBER(5,0),
	AVG_EXEC_TIME_DAILY_MIN NUMBER(5,0),
	AVG_EXEC_TIME_WEEKLY_MIN NUMBER(5,0),
	DOMAIN_AFFINITY VARCHAR2(2048) NOT NULL,
	N_USERS NUMBER(5,0)
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
  	ADD CONSTRAINT "PK_TRC_INFO_ID" PRIMARY KEY("TRANCHE_INFO_ID");

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO
    ADD CONSTRAINT "FK_TRANCHE_ID" FOREIGN KEY ("TRANCHE_ID")
	REFERENCES HOMEPAGE.EMD_TRANCHE ("TRANCHE_ID");	 	

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.EMD_TRANCHE_INFO  {ORA_GRANT_STOP}

-----------------------------------------
-- HOMEPAGE.EMD_EMAIL_PREFS
-----------------------------------------
CREATE TABLE HOMEPAGE.EMD_EMAIL_PREFS (
	EMAIL_PREFS_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	SEND_DIRECTED NUMBER(5,0) NOT NULL,
	TRANCHE_ID VARCHAR2(36) NOT NULL,
	EMAIL_ADDRESS VARCHAR2(256) NOT NULL,
	LANG VARCHAR2(36) NOT NULL,
	USE_TEXT_EMAIL NUMBER(5,0) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS 
  	ADD (CONSTRAINT "PK_EMAIL_PREFS_ID" PRIMARY KEY("EMAIL_PREFS_ID")  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS
    ADD CONSTRAINT "FK_EMD_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");

ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS ENABLE ROW MOVEMENT;
{ORA_GRANT_START} HOMEPAGE.EMD_EMAIL_PREFS  {ORA_GRANT_STOP}	
	
--------------------------------------
-- 8) INIT EMD_FREQUENCY_TYPE
--------------------------------------

-----------------------------------
-- START EMD_FREQUENCY_TYPE
-----------------------------------	
INSERT INTO HOMEPAGE.EMD_FREQUENCY_TYPE (FREQUENCY_TYPE_ID, FREQUENCY_TYPE, FREQUENCY_TYPE_NAME, FREQUENCY_TYPE_DESC)
VALUES ('never_____0fdf1xc9cax4cc4x8b0bx51af2', 1, '%never', 'never');

INSERT INTO HOMEPAGE.EMD_FREQUENCY_TYPE (FREQUENCY_TYPE_ID, FREQUENCY_TYPE, FREQUENCY_TYPE_NAME, FREQUENCY_TYPE_DESC)
VALUES ('immediete_9cax4cc4x8b0bx51af2ddef2cd', 2, '%immediete', 'immediete');

INSERT INTO HOMEPAGE.EMD_FREQUENCY_TYPE (FREQUENCY_TYPE_ID, FREQUENCY_TYPE, FREQUENCY_TYPE_NAME, FREQUENCY_TYPE_DESC)
VALUES ('daily_______0f1xc9cax4cc4x8b0bx51af2', 3, '%daily', 'daily');

INSERT INTO HOMEPAGE.EMD_FREQUENCY_TYPE (FREQUENCY_TYPE_ID, FREQUENCY_TYPE, FREQUENCY_TYPE_NAME, FREQUENCY_TYPE_DESC)
VALUES ('weekly_______f1xc9cax4cc4x8b0bx51af2', 4, '%weekly', 'weekly');  	
-----------------------------------
-- END EMD_FREQUENCY_TYPE
-----------------------------------




