-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- 114306: Add IS_EXTERNAL flag to identify content that can be viewed by external users
-- NR_ENTRIES
ALTER TABLE HOMEPAGE.NR_ENTRIES ADD IS_EXTERNAL NUMBER(5,0) DEFAULT 0 NOT NULL;
COMMIT;

DECLARE CURSOR cur IS SELECT ENTRY_ID FROM HOMEPAGE.NR_ENTRIES FOR UPDATE;


                BEGIN
                        FOR rec IN cur LOOP
                                UPDATE HOMEPAGE.NR_ENTRIES SET IS_EXTERNAL = '0' WHERE CURRENT OF cur;
                        END LOOP;
                                                COMMIT;
                END;
 /
COMMIT;

-- NR_ENTRIES_ARCHIVE
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE ADD IS_EXTERNAL NUMBER(5,0) DEFAULT 0 NOT NULL;
COMMIT;

DECLARE CURSOR cur IS SELECT ENTRY_ID FROM HOMEPAGE.NR_ENTRIES_ARCHIVE FOR UPDATE;


                BEGIN
                        FOR rec IN cur LOOP
                                UPDATE HOMEPAGE.NR_ENTRIES_ARCHIVE SET IS_EXTERNAL = '0' WHERE CURRENT OF cur;
                        END LOOP;
                                                COMMIT;
                END;
 /
COMMIT;

-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-- 113572: [fixup469] [Performance|DB2] Degradation on queries of  (SELECT READER_ID  FROM HOMEPAGE.<READERS>  WHERE ROLLUP_ENTRY_ID = ?
-- 115518: [fixup469] add a new COMMUNITY_ID column to reader tables


--  [start indexes] NR_AGGREGATED_READERS
DROP  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
DROP  INDEX HOMEPAGE.RESPONSES_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
DROP  INDEX HOMEPAGE.PROFILES_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
DROP  INDEX HOMEPAGE.COMM_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
DROP  INDEX HOMEPAGE.BLOGS_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
DROP  INDEX HOMEPAGE.FILES_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
DROP  INDEX HOMEPAGE.FORUMS_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
DROP  INDEX HOMEPAGE.WIKIS_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
DROP  INDEX HOMEPAGE.TAGS_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_CONT_IDX;
COMMIT;

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_CONT_IDX;
COMMIT;

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP  INDEX HOMEPAGE.NOT_REC_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
DROP  INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
DROP  INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
DROP  INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_CONT_IDX;
COMMIT;

--  [end indexes] NR_MENTIONS_READERS



--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX HOMEPAGE.RESPONSES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX HOMEPAGE.PROFILES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.PROFILES_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_PROFILES_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX HOMEPAGE.COMM_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.COMM_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX HOMEPAGE.BLOGS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.BLOGS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_BLOGS_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX HOMEPAGE.FILES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.FILES_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_FILES_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX HOMEPAGE.FORUMS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.FORUMS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_FORUMS_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX HOMEPAGE.WIKIS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.WIKIS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_WIKIS_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX HOMEPAGE.TAGS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.TAGS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_TAGS_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.STATUS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_ENTRY_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_COMM_IDX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_COMM_IDX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX HOMEPAGE.NOT_REC_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.SAVED_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_SAVED_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.TOPICS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_TOPICS_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
CREATE  INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_MENTIONS_READERS

----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------

----------------------------------------------------
-- 23 HOMEPAGE.NR_COMMUNITIES_VIEW
----------------------------------------------------
CREATE TABLE HOMEPAGE.NR_COMMUNITIES_VIEW (
	CATEGORY_READER_ID VARCHAR2(36)  DEFAULT ' ' NOT NULL,
	READER_ID VARCHAR2(39) NOT NULL,
	CATEGORY_TYPE NUMBER(5 ,0) NOT NULL,
	SOURCE VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(256),
	ITEM_ID VARCHAR2(256),
	ROLLUP_ENTRY_ID VARCHAR2(256),
	RESOURCE_TYPE NUMBER(5 ,0) NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR2(36) NOT NULL,
	SOURCE_TYPE NUMBER(5 ,0),
	USE_IN_ROLLUP NUMBER(5 ,0),
	IS_NETWORK	NUMBER(5 ,0),
	IS_FOLLOWER	NUMBER(5 ,0),
	EVENT_TIME 	TIMESTAMP,
	IS_STORY_COMM NUMBER(5 ,0),
	IS_BROADCAST NUMBER(5,0),
	ORGANIZATION_ID VARCHAR2(36) DEFAULT '00000000-0000-0000-0000-000000000000',
	ACTOR_UUID VARCHAR2(256),
	ROLLUP_AUTHOR_ID VARCHAR2 (256),
	IS_VISIBLE NUMBER(5 ,0) DEFAULT 1 NOT NULL,
	COMMUNITY_ID VARCHAR2(36),
		CONSTRAINT   	CK_CAT23_TYPE
    			CHECK
    			(CATEGORY_TYPE = 23)
)
TABLESPACE "NEWSREGTABSPACE";

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW
    ADD (CONSTRAINT PK_CV_READERS PRIMARY KEY(CATEGORY_READER_ID)  USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW 
	ADD CONSTRAINT FK_CV_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
	
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW ADD CONSTRAINT FK_CV_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);

--  [start indexes] NR_COMMUNITIES_VIEW
CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ITEM_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_CD_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, READER_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_BRD_VVI 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;


CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_COMM_IDX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (COMMUNITY_ID) TABLESPACE  NEWSINDEXTABSPACE; 
COMMIT;

--  [end indexes] NR_COMMUNITIES_VIEW

ALTER TABLE "HOMEPAGE"."NR_COMMUNITIES_VIEW" ENABLE ROW MOVEMENT;

