-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2012, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

CREATE TABLE HOMEPAGE.SR_FILECONTENTINDEXINGTASK (
	FILE_CONTENT_INDEXING_TASK_ID VARCHAR2(36) NOT NULL,
	TASK_ID VARCHAR2(36) NOT NULL,
	FILE_CONT_INDX_TASK_SERVICES VARCHAR2(256) NOT NULL,
	FILE_CONT_INDX_TASK_DURATION NUMBER(19,0) NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

ALTER TABLE HOMEPAGE.SR_FILECONTENTINDEXINGTASK
	ADD CONSTRAINT "PK_FCI_TASK_ID" PRIMARY KEY ("FILE_CONTENT_INDEXING_TASK_ID");	

CREATE UNIQUE INDEX HOMEPAGE.TASK_ID_UN_IDX
    ON HOMEPAGE.SR_FILECONTENTINDEXINGTASK("TASK_ID");

ALTER TABLE HOMEPAGE.SR_FILECONTENTINDEXINGTASK
	ADD CONSTRAINT "FK_FCI_TASK_ID" FOREIGN KEY ("TASK_ID") 
	REFERENCES  HOMEPAGE.SR_TASKDEF("TASK_ID");

DROP VIEW HOMEPAGE.SR_ALLTASKSDEF;

CREATE VIEW HOMEPAGE.SR_ALLTASKSDEF AS
(
	SELECT 	T1.TASK_ID  		AS	PARENT_TASK_ID,
	T1.TASK_NAME 				AS	PARENT_TASK_NAME,
	T1.INTERVAL 				AS	PARENT_TASK_INTERVAL,
	T1.STARTBY	 				AS	PARENT_TASK_STARTBY,
	T1.TASK_TYPE 				AS	PARENT_TASK_TYPE,
	T1.ENABLED					AS  PARENT_TASK_ENABLED,
	T2.INDEXING_TASK_SERVICES	AS	INDEXING_TASK_SERVICES,
	T2.INDEXING_TASK_OPTIMIZE	AS	INDEXING_TASK_OPTIMIZE,
	T2.INDEXING_TASK_ID			AS	INDEXING_TASK_ID,
	''							AS	OPTIMIZE_TASK_ID,
	'' 							AS 	FILECONTENT_TASK_ID,
	''							AS	FILE_CONTENT_TASK_SERVICES,
	0							AS 	CONTENT_FAILURES_ONLY,
        ''                  	AS  SAND_TASK_ID,
	''							AS	SAND_TASK_SERVICES,
	'' 							AS 	BACKUP_TASK_ID,
	''							AS	BACKUP_TASK_TYPE,
	''							AS	BACKUP_TASK_SCRIPT,
	''							AS	FILE_CONTENT_INDEXING_TASK_ID,
	''							AS	FILE_CONT_INDX_TASK_SERVICES,
	0							AS	FILE_CONT_INDX_TASK_DURATION,
	T2.INDEXING_TASK_ID			AS	CHILDTASK_PK	
	FROM    HOMEPAGE.SR_TASKDEF T1,HOMEPAGE.SR_INDEXINGTASKDEF T2 
	WHERE T1.TASK_ID=T2.TASK_ID
) 
UNION 
(
	SELECT T3.TASK_ID		AS 	PARENT_TASK_ID,
	T3.TASK_NAME 			AS 	PARENT_TASK_NAME,
	T3.INTERVAL				AS 	PARENT_TASK_INTERVAL,
	T3.STARTBY 				AS	PARENT_TASK_STARTBY,
	T3.TASK_TYPE 			AS 	PARENT_TASK_TYPE,
 	T3.ENABLED 				AS 	PARENT_TASK_ENABLED,
	''						AS 	INDEXING_TASK_SERVICES,
	0						AS	INDEXING_TASK_OPTIMIZE,
	''						AS	INDEXING_TASK_ID,
	T4.OPTIMIZE_TASK_ID 	AS	OPTIMIZE_TASK_ID,
	'' 						AS 	FILECONTENT_TASK_ID,
	''						AS	FILE_CONTENT_TASK_SERVICES,
	0						AS	CONTENT_FAILURES_ONLY,
        ''                 	AS  SAND_TASK_ID,
	''                      AS  SAND_TASK_SERVICES,
	'' 						AS 	BACKUP_TASK_ID,
	''						AS	BACKUP_TASK_TYPE,
	''						AS	BACKUP_TASK_SCRIPT,
	''						AS	FILE_CONTENT_INDEXING_TASK_ID,
	''						AS	FILE_CONT_INDX_TASK_SERVICES,
	0						AS	FILE_CONT_INDX_TASK_DURATION,
	T4.OPTIMIZE_TASK_ID		AS	CHILDTASK_PK
	FROM   HOMEPAGE.SR_TASKDEF T3,HOMEPAGE.SR_OPTIMIZETASKDEF T4
	WHERE  T3.TASK_ID=T4.TASK_ID
)
UNION 
(
	SELECT T5.TASK_ID				AS	PARENT_TASK_ID,
	T5.TASK_NAME 					AS	PARENT_TASK_NAME,
	T5.INTERVAL						AS	PARENT_TASK_INTERVAL,
	T5.STARTBY 						AS	PARENT_TASK_STARTBY,
	T5.TASK_TYPE 					AS	PARENT_TASK_TYPE,
 	T5.ENABLED 						AS	PARENT_TASK_ENABLED,
	''								AS	INDEXING_TASK_SERVICES,
	0								AS	INDEXING_TASK_OPTIMIZE,
	''								AS	INDEXING_TASK_ID,
	''								AS	OPTIMIZE_TASK_ID,
	T6.FILECONTENT_TASK_ID 			AS	FILECONTENT_TASK_ID,
	T6.FILE_CONTENT_TASK_SERVICES	AS	FILE_CONTENT_TASK_SERVICES,
	T6.CONTENT_FAILURES_ONLY		AS	CONTENT_FAILURES_ONLY,
        ''                  		AS  SAND_TASK_ID,
	''                      		AS  SAND_TASK_SERVICES,
	'' 								AS  BACKUP_TASK_ID,
	''								AS	BACKUP_TASK_TYPE,
	''								AS	BACKUP_TASK_SCRIPT,
	''								AS	FILE_CONTENT_INDEXING_TASK_ID,
	''								AS	FILE_CONT_INDX_TASK_SERVICES,
	0								AS	FILE_CONT_INDX_TASK_DURATION,
	T6.FILECONTENT_TASK_ID			AS	CHILDTASK_PK
	FROM   HOMEPAGE.SR_TASKDEF T5,HOMEPAGE.SR_FILECONTENTTASKDEF T6
	WHERE  T5.TASK_ID=T6.TASK_ID
)
UNION 
(
	SELECT T7.TASK_ID		AS 	PARENT_TASK_ID,
	T7.TASK_NAME 			AS 	PARENT_TASK_NAME,
	T7.INTERVAL				AS 	PARENT_TASK_INTERVAL,
	T7.STARTBY 				AS	PARENT_TASK_STARTBY,
	T7.TASK_TYPE 			AS 	PARENT_TASK_TYPE,
 	T7.ENABLED 				AS	PARENT_TASK_ENABLED,
	''						AS 	INDEXING_TASK_SERVICES,
	0						AS	INDEXING_TASK_OPTIMIZE,
	''						AS	INDEXING_TASK_ID,
	''						AS	OPTIMIZE_TASK_ID,
	''		 				AS 	FILECONTENT_TASK_ID,
	''						AS	FILE_CONTENT_TASK_SERVICES,
	0						AS	CONTENT_FAILURES_ONLY,
	''                  	AS  SAND_TASK_ID,
	''                      AS  SAND_TASK_SERVICES,
	T8.BACKUP_TASK_ID		AS 	BACKUP_TASK_ID,
	T8.TYPE					AS	BACKUP_TASK_TYPE,
	T8.SCRIPT				AS	BACKUP_TASK_SCRIPT,
	''						AS	FILE_CONTENT_INDEXING_TASK_ID,
	''						AS	FILE_CONT_INDX_TASK_SERVICES,
	0						AS	FILE_CONT_INDX_TASK_DURATION,
	T8.BACKUP_TASK_ID		AS	CHILDTASK_PK
	FROM   HOMEPAGE.SR_TASKDEF T7,HOMEPAGE.SR_BACKUPTASKDEF T8
	WHERE  T7.TASK_ID=T8.TASK_ID
)
UNION
(
        SELECT T9.TASK_ID              AS   PARENT_TASK_ID,
        T9.TASK_NAME                   AS   PARENT_TASK_NAME,
        T9.INTERVAL                    AS   PARENT_TASK_INTERVAL,
        T9.STARTBY                     AS   PARENT_TASK_STARTBY,
        T9.TASK_TYPE                   AS   PARENT_TASK_TYPE,
        T9.ENABLED                     AS   PARENT_TASK_ENABLED,
        ''                             AS   INDEXING_TASK_SERVICES,
        0                              AS   INDEXING_TASK_OPTIMIZE,
        ''                             AS   INDEXING_TASK_ID,
        ''                             AS   OPTIMIZE_TASK_ID,
        ''                             AS   FILECONTENT_TASK_ID,
        ''                             AS   FILE_CONTENT_TASK_SERVICES,
        0                              AS   CONTENT_FAILURES_ONLY,
        T10.SAND_TASK_ID               AS   SAND_TASK_ID,
	T10.SAND_TASK_SERVICES		   AS	SAND_TASK_SERVICES,
        ''                             AS   BACKUP_TASK_ID,
        ''                             AS   BACKUP_TASK_TYPE,
        ''                             AS   BACKUP_TASK_SCRIPT,
        ''							   AS	FILE_CONTENT_INDEXING_TASK_ID,
	''							   	   AS	FILE_CONT_INDX_TASK_SERVICES,
	0							       AS	FILE_CONT_INDX_TASK_DURATION,
        T10.SAND_TASK_ID               AS   CHILDTASK_PK
        FROM   HOMEPAGE.SR_TASKDEF T9,HOMEPAGE.SR_SANDTASKDEF T10
        WHERE  T9.TASK_ID=T10.TASK_ID
)
UNION
(
        SELECT T11.TASK_ID              		AS	PARENT_TASK_ID,
        T11.TASK_NAME                   		AS	PARENT_TASK_NAME,
        T11.INTERVAL                    		AS	PARENT_TASK_INTERVAL,
        T11.STARTBY                     		AS	PARENT_TASK_STARTBY,
        T11.TASK_TYPE                   		AS	PARENT_TASK_TYPE,
        T11.ENABLED                    			AS	PARENT_TASK_ENABLED,
        ''                             			AS	INDEXING_TASK_SERVICES,
        0                              			AS	INDEXING_TASK_OPTIMIZE,
        ''                             			AS	INDEXING_TASK_ID,
        ''                             			AS	OPTIMIZE_TASK_ID,
        ''                             			AS	FILECONTENT_TASK_ID,
        ''                             			AS	FILE_CONTENT_TASK_SERVICES,
        0                              			AS	CONTENT_FAILURES_ONLY,
        ''       				       	AS  	SAND_TASK_ID,
	''						AS	SAND_TASK_SERVICES,
        ''                             			AS  	BACKUP_TASK_ID,
        ''                             			AS  	BACKUP_TASK_TYPE,
        ''                             			AS  	BACKUP_TASK_SCRIPT,
        T12.FILE_CONTENT_INDEXING_TASK_ID		AS	FILE_CONTENT_INDEXING_TASK_ID,
	T12.FILE_CONT_INDX_TASK_SERVICES			AS	FILE_CONT_INDX_TASK_SERVICES,
	T12.FILE_CONT_INDX_TASK_DURATION			AS	FILE_CONT_INDX_TASK_DURATION,
        T12.FILE_CONTENT_INDEXING_TASK_ID		AS	CHILDTASK_PK
        FROM   HOMEPAGE.SR_TASKDEF T11,HOMEPAGE.SR_FILECONTENTINDEXINGTASK T12
        WHERE  T11.TASK_ID=T12.TASK_ID
);