-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- *********************************i******************************* 

-- CONSTRAINTS KEYS
 
-- HOMEPAGE 
ALTER TABLE "HOMEPAGE"."LOGINNAME" DROP CONSTRAINT "FK_LN_PERSON_ID";

ALTER TABLE "HOMEPAGE"."HP_UI" DROP CONSTRAINT "FK_UI_PERSON_ID";

ALTER TABLE "HOMEPAGE"."HP_TAB_INST" DROP CONSTRAINT "FK_UI_ID"; 

ALTER TABLE "HOMEPAGE"."HP_TAB_INST" DROP CONSTRAINT "FK_TAB_INST_TAB_ID";

ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST" DROP CONSTRAINT "FK_WIDGET_ID";

ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST" DROP CONSTRAINT "FK_TAB_INST_ID";

ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB" DROP CONSTRAINT "FK_WID_TAB_WID_ID";

ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB" DROP CONSTRAINT "FK_WID_TAB_TAB_ID";

ALTER TABLE "HOMEPAGE"."PREREQ" DROP CONSTRAINT "FK_PREREQ_WIDGET";

ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT" DROP CONSTRAINT "FK_RECIP_NOTIF";

ALTER TABLE "HOMEPAGE"."LOGINNAME" DROP CONSTRAINT "LOGINNAME_UNIQUE";

DROP INDEX  "HOMEPAGE"."PERSON_EXID";

-- NEWS RECORDS 
ALTER TABLE "HOMEPAGE"."NR_SUBSCRIPTION" DROP CONSTRAINT "FK_PERSON_ID";

ALTER TABLE "HOMEPAGE"."NR_SUBSCRIPTION" DROP CONSTRAINT "FK_SOURCE_ID";

ALTER TABLE "HOMEPAGE"."EMD_RECIPIENTS" DROP CONSTRAINT "FK_REC_PERSON_ID";

ALTER TABLE "HOMEPAGE"."EMD_JOBS_STATS" DROP CONSTRAINT "FK_JOB_ID";

DROP INDEX  "HOMEPAGE"."NR_SUBSCRIPTION_IX_UNIQUE";

DROP INDEX  "HOMEPAGE"."NR_SOURCE_IX_UNIQUE";

ALTER TABLE "HOMEPAGE"."EMD_JOBS" DROP CONSTRAINT "UNIQUE_JOB_FREQ";

-- SEARCH TABLES
ALTER TABLE "HOMEPAGE"."SR_INDEXINGTASKDEF" DROP CONSTRAINT "FK_INDEX_TASK_ID";

ALTER TABLE "HOMEPAGE"."SR_OPTIMIZETASKDEF" DROP CONSTRAINT "FK_OPT_TASK_ID";

ALTER TABLE "HOMEPAGE"."SR_TASKDEF" DROP CONSTRAINT "UNIQUE_TASK_NAME";

ALTER TABLE "HOMEPAGE"."SR_INDEXINGTASKDEF" DROP CONSTRAINT "UNIQUE_TASK_ID_IND";

ALTER TABLE "HOMEPAGE"."SR_OPTIMIZETASKDEF" DROP CONSTRAINT "UNIQUE_TASK_ID_OPT";

COMMIT;

QUIT;
