-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2016, 2017                              
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
-- CREATE THE DATABASE
-------------------------------------- 
 
CREATE DATABASE HOMEPAGE USING CODESET UTF-8 TERRITORY US@

CONNECT TO HOMEPAGE@  


CREATE BUFFERPOOL HOMEPAGE4KBP IMMEDIATE SIZE 4000 AUTOMATIC PAGESIZE 4K@

--CREATE BUFFERPOOL NT8KBP IMMEDIATE SIZE 8000 AUTOMATIC PAGESIZE 8K@
CREATE BUFFERPOOL NT16KBP IMMEDIATE SIZE 16000 AUTOMATIC PAGESIZE 16K@

CREATE BUFFERPOOL NEWS4KBP IMMEDIATE SIZE 16000 AUTOMATIC PAGESIZE 4K@
--CREATE BUFFERPOOL NEWS8KBP IMMEDIATE SIZE 16000 AUTOMATIC PAGESIZE 8K@
CREATE BUFFERPOOL NEWS16KBP IMMEDIATE SIZE 16000 AUTOMATIC PAGESIZE 16K@
CREATE BUFFERPOOL NEWS32KBP IMMEDIATE SIZE 16000 AUTOMATIC PAGESIZE 32K@
--CREATE BUFFERPOOL NEWSCONTBFP IMMEDIATE SIZE 1000 AUTOMATIC PAGESIZE 4K@


-- Disable the run stats. Increase the logs
UPDATE DATABASE CONFIGURATION USING AUTO_RUNSTATS OFF IMMEDIATE@
UPDATE DATABASE CONFIGURATION USING LOGPRIMARY 26@
UPDATE DATABASE CONFIGURATION USING LOGSECOND 52@
UPDATE DBM CFG USING NUMDB 15@

-- HOMEPAGE TABLESPACE
CREATE LARGE TABLESPACE HOMEPAGETABSPACE  
	PAGESIZE 4K MANAGED BY DATABASE
	USING (FILE 'HOMEPAGETABSPACE' 20000) 
	EXTENTSIZE 4
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL HOMEPAGE4KBP
	AUTORESIZE YES
	INCREASESIZE 20 M
	MAXSIZE NONE@
 
-- HOMEPAGE NOTIFICATION TABLETABLESPACE
--CREATE SYSTEM TEMPORARY TABLESPACE HPNTTMPTABSPACE
--	PAGESIZE 8K MANAGED BY SYSTEM 
--	USING ( 'HPNTTMPTABSPACE' ) 
--	EXTENTSIZE 8 PREFETCHSIZE AUTOMATIC
--	BUFFERPOOL NT8KBP
--	FILE SYSTEM CACHING@
              
--CREATE LARGE TABLESPACE HPNTTABSPACE 
--	PAGESIZE 8K MANAGED BY DATABASE
--	USING (FILE 'HPNTTABSPACE' 12800)
--	EXTENTSIZE 8
--	PREFETCHSIZE AUTOMATIC
--	BUFFERPOOL NT8KBP
--	AUTORESIZE YES
--	INCREASESIZE 20 M
--	MAXSIZE NONE@

-- NOTIFICATION HPNT16TABSPACE
CREATE SYSTEM TEMPORARY TABLESPACE HPNT16TMPTABSPACE
	PAGESIZE 16K MANAGED BY SYSTEM 
	USING ( 'HPNT16TMPTABSPACE' ) 
	EXTENTSIZE 8 PREFETCHSIZE AUTOMATIC
	BUFFERPOOL NT16KBP
	FILE SYSTEM CACHING@

CREATE LARGE TABLESPACE HPNT16TABSPACE 
	PAGESIZE 16K MANAGED BY DATABASE
	USING (FILE 'HPNT16TABSPACE' 12800)
	EXTENTSIZE 8
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL NT16KBP
	AUTORESIZE YES
	INCREASESIZE 20 M
	MAXSIZE NONE@	

-- NEWS 4K TABLESPACE 
CREATE SYSTEM TEMPORARY TABLESPACE NEWS4TMPTABSPACE
	PAGESIZE 4K MANAGED BY SYSTEM 
	USING ( 'NEWS4TMPTABSPACE' ) 
	EXTENTSIZE 16 PREFETCHSIZE AUTOMATIC
	BUFFERPOOL NEWS4KBP
	FILE SYSTEM CACHING@
              
CREATE LARGE TABLESPACE NEWS4TABSPACE 
	PAGESIZE 4K MANAGED BY DATABASE
	USING (FILE 'NEWS4TABSPACE' 12800)
	EXTENTSIZE 16
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL NEWS4KBP
	AUTORESIZE YES
	INCREASESIZE 40 M
	MAXSIZE NONE@ 
        
-- NEWS 8K TABLESPACE 
--CREATE SYSTEM TEMPORARY TABLESPACE NEWS8TMPTABSPACE
--	PAGESIZE 8K MANAGED BY SYSTEM 
--	USING ( 'NEWS8TMPTABSPACE' ) 
--	EXTENTSIZE 16 PREFETCHSIZE AUTOMATIC
--	BUFFERPOOL NEWS8KBP
--	FILE SYSTEM CACHING@
              
--CREATE LARGE TABLESPACE NEWS8TABSPACE 
-- 	PAGESIZE 8K MANAGED BY DATABASE
--	USING (FILE 'NEWS8TABSPACE' 12800)
--	EXTENTSIZE 16
--	PREFETCHSIZE AUTOMATIC
--	BUFFERPOOL NEWS8KBP
--	AUTORESIZE YES
--	INCREASESIZE 40 M
--	MAXSIZE NONE@

-- NEWS 16K TABLESPACE
CREATE SYSTEM TEMPORARY TABLESPACE NEWSTMPTABSPACE
	PAGESIZE 16K MANAGED BY SYSTEM 
	USING ( 'NEWSTMPTABSPACE' ) 
	EXTENTSIZE 16 PREFETCHSIZE AUTOMATIC
	BUFFERPOOL NEWS16KBP
	FILE SYSTEM CACHING@
	      
CREATE LARGE TABLESPACE NEWSTABSPACE 
	PAGESIZE 16K MANAGED BY DATABASE
	USING (FILE 'NEWSTABSPACE' 12800)
	EXTENTSIZE 16
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL NEWS16KBP
	AUTORESIZE YES
	INCREASESIZE 40 M
	MAXSIZE NONE@   

-- NEWS 32K TABLESPACE
CREATE SYSTEM TEMPORARY TABLESPACE NEWS32TMPTABSPACE
	PAGESIZE 32K MANAGED BY SYSTEM 
	USING ( 'NEWS32TMPTABSPACE' ) 
	EXTENTSIZE 16 PREFETCHSIZE AUTOMATIC
	BUFFERPOOL NEWS32KBP
	FILE SYSTEM CACHING@
              
CREATE LARGE TABLESPACE NEWS32TABSPACE 
	PAGESIZE 32K MANAGED BY DATABASE
	USING (FILE 'NEWS32TABSPACE' 12800)
	EXTENTSIZE 16
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL NEWS32KBP
	AUTORESIZE YES
	INCREASESIZE 40 M
	MAXSIZE NONE@
   
-- NEWS 4K CONTENT TABLESPACE
--CREATE LARGE TABLESPACE NEWSCONT4KTABSPACE 
--	PAGESIZE 4K  MANAGED BY DATABASE
--	USING (FILE 'NEWSCONT_TABSPACE' 12800) 
--	EXTENTSIZE 8 
--	PREFETCHSIZE 8 
--	BUFFERPOOL NEWSCONTBFP@

--------------------------------
-- LCNEXT new tabspace for BOARD use case
--------------------------------
CREATE BUFFERPOOL BOARD16KBP IMMEDIATE SIZE 32000 AUTOMATIC PAGESIZE 16K@

CREATE SYSTEM TEMPORARY TABLESPACE BOARDTMPTABSPACE
	PAGESIZE 16K MANAGED BY SYSTEM 
	USING ( 'BOARDTMPTABSPACE' ) 
	EXTENTSIZE 16 PREFETCHSIZE AUTOMATIC
	BUFFERPOOL BOARD16KBP
	FILE SYSTEM CACHING@
	      
CREATE LARGE TABLESPACE BOARD16TABSPACE 
	PAGESIZE 16K MANAGED BY DATABASE
	USING (FILE 'BOARD16TABSPACE' 12800)
	EXTENTSIZE 16
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL BOARD16KBP
	AUTORESIZE YES
	INCREASESIZE 40 M
	MAXSIZE NONE@	
    
	
------------------------------------
-- DDL Statements for TABLESPACES -- 
------------------------------------
CREATE BUFFERPOOL BRD32KBP IMMEDIATE SIZE 32000 AUTOMATIC PAGESIZE 32K@

-- BRD 32K TABLESPACE
CREATE SYSTEM TEMPORARY TABLESPACE BRD32TMPTABSPACE
	PAGESIZE 32K MANAGED BY SYSTEM 
	USING ( 'BRDS32TMPTABSPACE' ) 
	EXTENTSIZE 16 PREFETCHSIZE AUTOMATIC
	BUFFERPOOL BRD32KBP
	FILE SYSTEM CACHING@
              
CREATE LARGE TABLESPACE BRD32TABSPACE 
	PAGESIZE 32K MANAGED BY DATABASE
	USING (FILE 'BRD32TABSPACE' 12800)
	EXTENTSIZE 16
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL BRD32KBP
	AUTORESIZE YES
	INCREASESIZE 40 M
	MAXSIZE NONE@
	 
COMMIT@


--------------------------------------
-- CREATE THE SCHEMA
--------------------------------------    
        
CREATE SCHEMA HOMEPAGE@

--------------------------------------
-- CREATE THE SCHEMA TABLE
--------------------------------------

CREATE TABLE HOMEPAGE.HOMEPAGE_SCHEMA (
	COMPKEY VARCHAR(36) NOT NULL,
	DBSCHEMAVER INTEGER NOT NULL,
	PRESCHEMAVER VARCHAR(10) DEFAULT '0' NOT NULL,
	POSTSCHEMAVER VARCHAR(10) DEFAULT '0' NOT NULL,
	RELEASEVER VARCHAR(32) NOT NULL DEFAULT ''
) 
IN HOMEPAGETABSPACE@

RUNSTATS ON TABLE "HOMEPAGE"."HOMEPAGE_SCHEMA"@
RUNSTATS ON TABLE "HOMEPAGE"."HOMEPAGE_SCHEMA" FOR INDEXES ALL@

--------------------------------------
-- STARTING HOMEPAGE TABLES DEFINITIONS
--------------------------------------
{include.hp-createDb.sql}
--------------------------------------
-- END HOMEPAGE TABLES DEFINITIONS
--------------------------------------

--------------------------------------
-- STARTING NEWS TABLES DEFINITIONS
--------------------------------------
{include.news-createDb.sql}
--------------------------------------
-- END NEWS TABLES DEFINITIONS
--------------------------------------

--------------------------------------
-- STARTING SEARCH TABLES DEFINITIONS
--------------------------------------
{include.search-createDb.sql}
--------------------------------------
-- END SEARCH TABLES DEFINITIONS
--------------------------------------

--------------------------------------
-- INSERT THE SCHEMA VERSION
--------------------------------------
INSERT INTO HOMEPAGE.HOMEPAGE_SCHEMA (COMPKEY, DBSCHEMAVER, POSTSCHEMAVER, RELEASEVER)
VALUES ('HOMEPAGE', 710, '710.9', '7.0.0.0')@


COMMIT@
	
--------------------------------------
-- FLUSH
--------------------------------------
FLUSH PACKAGE CACHE DYNAMIC@

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- END THE DEFINITION FOR THE SEARCH DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

--------------------------------------
-- TERMINATE
--------------------------------------
connect reset@
terminate@
