-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 


-- 5724_S68 
CONNECT TO HOMEPAGE@


-- CREATING FKs
ALTER TABLE HOMEPAGE.BOARD ADD CONSTRAINT FK_BOARD_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD ADD CONSTRAINT FK_BRD_CREATED FOREIGN KEY (CREATED_BY) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD ADD CONSTRAINT FK_BRD_LASTUPDATE FOREIGN KEY (LASTUPDATE_BY) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD ADD CONSTRAINT FK_BRD_OWNER FOREIGN KEY (BOARD_OWNER_ASSOC_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_COMMENTS ADD CONSTRAINT FK_BOARD_COMMENTS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_COMMENTS ADD CONSTRAINT FK_BRD_COM_ENTRY FOREIGN KEY (ENTRY_ID) REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS ADD CONSTRAINT FK_BOARD_CURRENT_STATUS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS ADD CONSTRAINT FK_CUR_ST_ACTOR_ID FOREIGN KEY (ACTOR_UUID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS ADD CONSTRAINT FK_CUR_ST_ENTRY_ID FOREIGN KEY (ENTRY_ID) REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_ENTRIES ADD CONSTRAINT FK_BOARD_ENTRIES_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_ENTRIES ADD CONSTRAINT FK_CONTAINER_ID FOREIGN KEY (CONTAINER_ID) REFERENCES HOMEPAGE.BOARD (BOARD_CONTAINER_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_MENTIONS ADD CONSTRAINT FK_BOARD_MENTIONS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_MENTIONS ADD CONSTRAINT FK_BRD_MEN_PER_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE ADD CONSTRAINT FK_BRD_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE ADD CONSTRAINT FK_BRD_OBJ_REFERENCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS ADD CONSTRAINT FK_BRD_RECOMMENDER FOREIGN KEY (RECOMMENDER_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS ADD CONSTRAINT FK_BRD_RECOMM_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE ADD CONSTRAINT FK_DEL_STORIES_QUEUE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS ADD CONSTRAINT FK_EMD_EMAIL_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS ADD CONSTRAINT FK_EMD_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF ADD CONSTRAINT FK_EMD_RES_PREF_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF ADD CONSTRAINT FK_RES_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_TRANCHE ADD CONSTRAINT FK_EMD_TRANCHE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO ADD CONSTRAINT FK_EMD_TRANCHE_INFO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO ADD CONSTRAINT FK_TRANCHE_ID FOREIGN KEY (TRANCHE_ID) REFERENCES HOMEPAGE.EMD_TRANCHE (TRANCHE_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_TAB ADD CONSTRAINT FK_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_TAB_INST ADD CONSTRAINT FK_TAB_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_TAB_INST ADD CONSTRAINT FK_TAB_INST_TAB_ID FOREIGN KEY (TAB_ID) REFERENCES HOMEPAGE.HP_TAB (TAB_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_TAB_INST ADD CONSTRAINT FK_UI_ID FOREIGN KEY (UI_ID) REFERENCES HOMEPAGE.HP_UI (UI_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_UI ADD CONSTRAINT FK_UI_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_UI ADD CONSTRAINT FK_UI_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_USER_PREFS ADD CONSTRAINT FK_USER_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_USER_PREFS ADD CONSTRAINT FK_USER_PREFS_PERS_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_WIDGET_INST ADD CONSTRAINT FK_TAB_INST_ID FOREIGN KEY (TAB_INST_ID) REFERENCES HOMEPAGE.HP_TAB_INST (TAB_INST_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_WIDGET_INST ADD CONSTRAINT FK_WIDGET_ID FOREIGN KEY (WIDGET_ID) REFERENCES HOMEPAGE.WIDGET (WIDGET_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_WIDGET_INST ADD CONSTRAINT FK_WIDGET_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ADD CONSTRAINT FK_WIDGET_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ADD CONSTRAINT FK_WID_TAB_TAB_ID FOREIGN KEY (TAB_ID) REFERENCES HOMEPAGE.HP_TAB (TAB_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ADD CONSTRAINT FK_WID_TAB_WID_ID FOREIGN KEY (WIDGET_ID) REFERENCES HOMEPAGE.WIDGET (WIDGET_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.IMG_CACHE ADD CONSTRAINT FK_IMG_CACHE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.LOGINNAME ADD CONSTRAINT FK_LN_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.LOGINNAME ADD CONSTRAINT FK_LN_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.METRIC_STAT ADD CONSTRAINT FK_METRIC_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.MT_CFG_FILES ADD CONSTRAINT FK_CFG_FILE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.MT_CFG_FILES ADD CONSTRAINT FK_SETTING_ID FOREIGN KEY (SETTING_ID) REFERENCES HOMEPAGE.MT_CFG_SETTINGS (SETTING_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS ADD CONSTRAINT FK_CFG_SET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT FK_ACT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT FK_ACT_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT FK_ACI_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT FK_ACTIVITIES_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS ADD CONSTRAINT FK_AS_CNT_INDEX_STATS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_COUNTS ADD CONSTRAINT FK_AS_COUNT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_COUNTS ADD CONSTRAINT FK_AS_COUNT_PER_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST ADD CONSTRAINT FK_AS_SEEDLIST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT FK_BLG_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT FK_BLOGS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT FK_BKM_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT FK_BOOK_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT FK_COMM_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT FK_COM_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW ADD CONSTRAINT FK_CV_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_VIEW ADD CONSTRAINT FK_CV_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW ADD CONSTRAINT FK_COMM_FOLLOW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW ADD CONSTRAINT FK_COMM_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW ADD CONSTRAINT FK_COMM_PERSON_FOLLOW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW ADD CONSTRAINT FK_COMM_PER_PER_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS ADD CONSTRAINT FK_COMM_SETTINGS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW ADD CONSTRAINT FK_DISCOVERY_VIEW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW ADD CONSTRAINT FK_DIS_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ENTRIES ADD CONSTRAINT FK_ENTRIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE ADD CONSTRAINT FK_ENTRIES_ARCHIVE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT FK_EXT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT FK_EXT_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT FK_FILES_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT FK_FIL_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_FOLLOWS ADD CONSTRAINT FK_FOLLOWS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_FOLLOWS ADD CONSTRAINT FK_FS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_FOLLOWS ADD CONSTRAINT FK_FS_RESOURCE_ID FOREIGN KEY (RESOURCE_ID) REFERENCES HOMEPAGE.NR_RESOURCE (RESOURCE_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT FK_FORUMS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT FK_FRM_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS ADD CONSTRAINT FK_MENT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS ADD CONSTRAINT FK_MEN_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NETWORK ADD CONSTRAINT FK_NETWORK_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NETWORK ADD CONSTRAINT FK_NTW_COLL_ID FOREIGN KEY (COLLEAGUE_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NETWORK ADD CONSTRAINT FK_NTW_PERS_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT ADD CONSTRAINT FK_C_COMMENT_ID FOREIGN KEY (NEWS_STATUS_COMMENT_ID) REFERENCES HOMEPAGE.NR_NEWS_STATUS_COMMENT (NEWS_STATUS_COMMENT_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT ADD CONSTRAINT FK_NEWS_COMMENT_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT ADD CONSTRAINT FK_STATUS_COMMENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT ADD CONSTRAINT FK_STATUS_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK ADD CONSTRAINT FK_NEWS_STATUS_NETWORK_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD CONSTRAINT FK_NOT_REC_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD CONSTRAINT FK_REC_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD CONSTRAINT FK_NOT_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD CONSTRAINT FK_NOT_SENT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT FK_PRF_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT FK_PROF_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW ADD CONSTRAINT FK_PRF_VIEW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW ADD CONSTRAINT FK_PRO_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_RESOURCE ADD CONSTRAINT FK_RESOURCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT FK_RESP_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT FK_RES_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SAVED_READERS ADD CONSTRAINT FK_SAVED_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SAVED_READERS ADD CONSTRAINT FK_SAV_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE ADD CONSTRAINT FK_SOURCE_TYPE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT FK_STA_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT FK_SU_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_STORIES ADD CONSTRAINT FK_ENTRY_ID FOREIGN KEY (ENTRY_ID) REFERENCES HOMEPAGE.NR_ENTRIES (ENTRY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_STORIES ADD CONSTRAINT FK_STORIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT ADD CONSTRAINT FK_STORIES_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT FK_TAGS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT FK_TAG_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS ADD CONSTRAINT FK_TOPICS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS ADD CONSTRAINT FK_TOP_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT FK_WIKIS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT FK_WIK_READERS_STR FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NT_REPLYTO ADD CONSTRAINT FK_REPLYTO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ADD CONSTRAINT FK_REPLYTO_NOT_ID FOREIGN KEY (REPLYTO_NOTIFICATION_ID) REFERENCES HOMEPAGE.NT_REPLYTO (REPLYTO_NOTIFICATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ADD CONSTRAINT FK_REPLYTO_PER_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ADD CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT ADD CONSTRAINT CLNT_FK FOREIGN KEY (PROVIDERID) REFERENCES HOMEPAGE.OAUTH1_PROVIDER (ID)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT ADD CONSTRAINT CLNT_TOKEN_FK FOREIGN KEY (TOKENID) REFERENCES HOMEPAGE.OAUTH1_TOKEN (ID)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT ADD CONSTRAINT FK_OA1CL_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT ADD CONSTRAINT AUTH_TOKEN_FK FOREIGN KEY (TOKENID) REFERENCES HOMEPAGE.OAUTH1_TOKEN (ID)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT ADD CONSTRAINT CONTEXT_CLNT_FK FOREIGN KEY (CLIENTID) REFERENCES HOMEPAGE.OAUTH1_CLIENT (ID)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT ADD CONSTRAINT FK_OA1C_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH2_CLIENT ADD CONSTRAINT FK_CLIENT_PRO_NAME FOREIGN KEY (PROVIDER_NAME) REFERENCES HOMEPAGE.OAUTH2_PROVIDER (NAME)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING ADD CONSTRAINT FK_BINDING_CLIENT FOREIGN KEY (CLIENT_NAME) REFERENCES HOMEPAGE.OAUTH2_CLIENT (NAME)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING ADD CONSTRAINT FK_BINDING_WIDGET FOREIGN KEY (WIDGET_ID) REFERENCES HOMEPAGE.WIDGET (WIDGET_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.OAUTH2_TOKEN ADD CONSTRAINT FK_OA2T_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.PERSON ADD CONSTRAINT FK_PERSON_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.PERSON_ROLE ADD CONSTRAINT FK_PERSON_ROLE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.PERSON_ROLE ADD CONSTRAINT FK_PERSON_ROLE_PER_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.PREREQ ADD CONSTRAINT FK_PREREQ_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.PREREQ ADD CONSTRAINT FK_PREREQ_WIDGET FOREIGN KEY (WIDGET_ID) REFERENCES HOMEPAGE.WIDGET (WIDGET_ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_BACKUPTASKDEF ADD CONSTRAINT FK_BKUP_TASK_ID FOREIGN KEY (TASK_ID) REFERENCES HOMEPAGE.SR_TASKDEF (TASK_ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FEEDBACK ADD CONSTRAINT FK_SRFB_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON (PERSON_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FEEDBACK_CONTEXT ADD CONSTRAINT FK_FBK_CTXT_ID FOREIGN KEY (ID) REFERENCES HOMEPAGE.SR_FEEDBACK (ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FEEDBACK_PARAMETERS ADD CONSTRAINT FK_FBK_PARAMS_ID FOREIGN KEY (ID) REFERENCES HOMEPAGE.SR_FEEDBACK (ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF ADD CONSTRAINT FK_FC_TASK_ID FOREIGN KEY (TASK_ID) REFERENCES HOMEPAGE.SR_TASKDEF (TASK_ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF ADD CONSTRAINT FK_INDEX_TASK_ID FOREIGN KEY (TASK_ID) REFERENCES HOMEPAGE.SR_TASKDEF (TASK_ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_NUMBER_STATS ADD CONSTRAINT FK_NUM_STAT_ID FOREIGN KEY (STAT_ID) REFERENCES HOMEPAGE.SR_STATS (STAT_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF ADD CONSTRAINT FK_OPT_TASK_ID FOREIGN KEY (TASK_ID) REFERENCES HOMEPAGE.SR_TASKDEF (TASK_ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_RESUME_TOKENS ADD CONSTRAINT FK_RT_IDX_MGMT_ID FOREIGN KEY (NODE_ID) REFERENCES HOMEPAGE.SR_INDEX_MANAGEMENT (NODE_ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_SANDTASKDEF ADD CONSTRAINT FK_ST_TASK_ID FOREIGN KEY (TASK_ID) REFERENCES HOMEPAGE.SR_TASKDEF (TASK_ID) ON DELETE CASCADE@
COMMIT@
ALTER TABLE HOMEPAGE.SR_STRING_STATS ADD CONSTRAINT FK_STR_STAT_ID FOREIGN KEY (STAT_ID) REFERENCES HOMEPAGE.SR_STATS (STAT_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.SR_TIMER_STATS ADD CONSTRAINT FK_TMR_STAT_ID FOREIGN KEY (STAT_ID) REFERENCES HOMEPAGE.SR_STATS (STAT_ID)@
COMMIT@
ALTER TABLE HOMEPAGE.WIDGET ADD CONSTRAINT FK_WIDGET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
COMMIT@



--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_STR_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_ITM_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_CD_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_BRD_VVI 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX HOMEPAGE.RESPONSES_READERS_STR_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_CD_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_STR_RDR 
 	ON HOMEPAGE.NR_RESPONSES_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX HOMEPAGE.PROFILES_READERS_STR_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_READERS_CD_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_READERS_STR_RDR 
 	ON HOMEPAGE.NR_PROFILES_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_PROFILES_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX HOMEPAGE.COMM_READERS_STR_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMM_READERS_ITM_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMM_READERS_CD_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMM_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMM_READERS_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMM_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (CREATION_DATE DESC, IS_BROADCAST)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMM_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMM_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_STR_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_CD_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_STR_RDR 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_BRD_VVI 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX HOMEPAGE.BLOGS_READERS_STR_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BLOGS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BLOGS_READERS_CD_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BLOGS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BLOGS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_BLOGS_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BLOGS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_BLOGS_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BLOGS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BLOGS_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_STR_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_CD_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX HOMEPAGE.FILES_READERS_STR_IX 
 	ON HOMEPAGE.NR_FILES_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FILES_READERS_ITM_IX 
 	ON HOMEPAGE.NR_FILES_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FILES_READERS_CD_IX 
 	ON HOMEPAGE.NR_FILES_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FILES_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FILES_READERS_STR_RDR 
 	ON HOMEPAGE.NR_FILES_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FILES_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_FILES_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FILES_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FILES_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX HOMEPAGE.FORUMS_READERS_STR_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FORUMS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FORUMS_READERS_CD_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FORUMS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FORUMS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_FORUMS_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FORUMS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_FORUMS_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FORUMS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.FORUMS_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX HOMEPAGE.WIKIS_READERS_STR_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.WIKIS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.WIKIS_READERS_CD_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.WIKIS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.WIKIS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_WIKIS_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.WIKIS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_WIKIS_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.WIKIS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.WIKIS_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX HOMEPAGE.TAGS_READERS_STR_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TAGS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TAGS_READERS_CD_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TAGS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TAGS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_TAGS_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TAGS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_TAGS_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TAGS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TAGS_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX HOMEPAGE.STATUS_READERS_STR_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_CD_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_STR_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_ITM_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_CD_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_STR_RDR 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_STR_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_ITM_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_CD_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_STR_RDR 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_BRD_VVI 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_STR_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_CD_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (USE_IN_ROLLUP, ORGANIZATION_ID, IS_VISIBLE, CREATION_DATE DESC,  IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID)@ 
COMMIT@


CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, IS_BROADCAST)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_ENTRY_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@

--NEW ORG_ID NR_DISCOVERY_VIEW 
CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_ORG_IIDX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ORGANIZATION_ID, IS_VISIBLE, IS_BROADCAST, ROLLUP_ENTRY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_COM 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_STORY_COMM, ORGANIZATION_ID, IS_VISIBLE, USE_IN_ROLLUP, CREATION_DATE DESC, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_ACT_CD_VIS_IDX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ACTOR_UUID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_COMM_IDX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX HOMEPAGE.PROFILES_VIEW_STR_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_CD_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (CREATION_DATE DESC, IS_BROADCAST)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@

--NEW ORG_ID NR_PROFILES_VIEW 
CREATE  INDEX HOMEPAGE.PROFILES_VIEW_ORG_IIDX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ORGANIZATION_ID, IS_VISIBLE, IS_BROADCAST, ROLLUP_ENTRY_ID, CREATION_DATE DESC)@ 
COMMIT@


COMMIT@

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_STR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_ITM_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_CD_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX HOMEPAGE.NOT_REC_READERS_STR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_ITM_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_CD_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX HOMEPAGE.SAVED_READERS_STR_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_ITM_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_CD_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_SAVED_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX HOMEPAGE.TOPICS_READERS_STR_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_CD_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_TOPICS_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
CREATE  INDEX HOMEPAGE.MENTIONS_READERS_STR_IX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_ITM_IX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_CD_IX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_MENTIONS_READERS (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_MENTIONS_READERS

--  [start indexes] NR_COMMUNITIES_VIEW
CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_ITM_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_CD_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, READER_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_DEL_SERV_IX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_BRD_VVIS 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@



COMMIT@

--  [end indexes] NR_COMMUNITIES_VIEW


COMMIT@
FLUSH PACKAGE CACHE DYNAMIC@
connect reset@
terminate@
