-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
CONNECT TO HOMEPAGE;  

-- Preparing NR_STORIES
ALTER TABLE HOMEPAGE.NR_STORIES
  	ADD CONSTRAINT FK_ENTRY_ID FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES (ENTRY_ID); 
COMMIT;

CREATE INDEX HOMEPAGE.NR_STORIES_EIDX
    ON HOMEPAGE.NR_STORIES (ENTRY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NR_STORIES_ER_UUID
    ON HOMEPAGE.NR_STORIES (EVENT_RECORD_UUID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NR_STORIES_DATE
	ON HOMEPAGE.NR_STORIES (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.STORY_CONTAINED_ID
    ON HOMEPAGE.NR_STORIES (CONTAINER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NR_STORY_CD_IDX 
	ON HOMEPAGE.NR_STORIES (CREATION_DATE ASC, STORY_ID); 
COMMIT;

CREATE INDEX HOMEPAGE.STORIES_EVENT_ITEM_ACTOR_IDX ON
	HOMEPAGE.NR_STORIES (EVENT_NAME, ITEM_ID, ACTOR_UUID);
COMMIT;

DROP INDEX HOMEPAGE.MIG_STORIES_ITEM_CD;
COMMIT;

CREATE INDEX HOMEPAGE.STORIES_ITEM_ENTRY_CORR_ID
    ON HOMEPAGE.NR_STORIES (ENTRY_CORRELATION_ID); 
COMMIT;    

DROP INDEX HOMEPAGE.MIG_RLL_STORY_IDX;
COMMIT;

--DROP INDEX HOMEPAGE.MIG_STORIES_ITEM_ID;
--COMMIT;

-- Preparing NR_ENTRIES and NR_ENTRIES_ARCHIVE
CREATE INDEX HOMEPAGE.NR_ENTRIES_CONT
    ON HOMEPAGE.NR_ENTRIES (CONTAINER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NR_ENTRIES_AR_CONT
    ON HOMEPAGE.NR_ENTRIES_ARCHIVE (CONTAINER_ID);
COMMIT;

-- Preparing NR_NOTIFICATION to speed up notification reads:
--DROP INDEX HOMEPAGE.MIG_NOT_EXID_PER_ID;
--COMMIT;

DROP INDEX HOMEPAGE.MIG_NOT_READS;
COMMIT;

-- add fk for table: NR_AGGREGATED_READERS
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_AGGREGATED_READERS
--CREATE INDEX HOMEPAGE.AGGREGATED_READERS_STR_IX ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_ITM_IX ON HOMEPAGE.NR_AGGREGATED_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_CD_IX ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_SRC_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_RDR_STR ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_DEL_SERV_IX ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IX ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_RIR_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_AGGREGATED_READERS



-- add fk for table: NR_RESPONSES_READERS
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT FK_RES_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_RESPONSES_READERS
--CREATE INDEX HOMEPAGE.RESPONSES_READERS_STR_IX ON HOMEPAGE.NR_RESPONSES_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.RESPONSES_READERS_ITM_IX ON HOMEPAGE.NR_RESPONSES_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.RESPONSES_READERS_CD_IX ON HOMEPAGE.NR_RESPONSES_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.RESPONSES_READERS_SRC_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.RESPONSES_READERS_RLL_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.RESPONSES_READERS_RDR_STR ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.RESPONSES_READERS_DEL_SERV_IX ON HOMEPAGE.NR_RESPONSES_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.RESPONSES_READERS_ROLLUP_IX ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.RESPONSES_READERS_RIR_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_RESPONSES_READERS



-- add fk for table: NR_PROFILES_READERS
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT FK_PRF_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_PROFILES_READERS
--CREATE INDEX HOMEPAGE.PROFILES_READERS_STR_IX ON HOMEPAGE.NR_PROFILES_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_READERS_ITM_IX ON HOMEPAGE.NR_PROFILES_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_READERS_CD_IX ON HOMEPAGE.NR_PROFILES_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_READERS_SRC_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_READERS_RLL_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_READERS_RDR_STR ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_READERS_DEL_SERV_IX ON HOMEPAGE.NR_PROFILES_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_READERS_ROLLUP_IX ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_READERS_RIR_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_PROFILES_READERS



-- add fk for table: NR_COMMUNITIES_READERS
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT FK_COM_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_COMMUNITIES_READERS
--CREATE INDEX HOMEPAGE.COMM_READERS_STR_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.COMM_READERS_ITM_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.COMM_READERS_CD_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.COMM_READERS_SRC_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.COMM_READERS_RLL_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.COMM_READERS_RDR_STR ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.COMM_READERS_DEL_SERV_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (CREATION_DATE DESC, IS_BROADCAST);
COMMIT;

CREATE INDEX HOMEPAGE.COMM_READERS_ROLLUP_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.COMM_READERS_RIR_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_COMMUNITIES_READERS



-- add fk for table: NR_ACTIVITIES_READERS
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT FK_ACI_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_ACTIVITIES_READERS
--CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_STR_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_ITM_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_CD_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_RDR_STR ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_DEL_SERV_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_RIR_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_ACTIVITIES_READERS



-- add fk for table: NR_BLOGS_READERS
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT FK_BLG_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_BLOGS_READERS
--CREATE INDEX HOMEPAGE.BLOGS_READERS_STR_IX ON HOMEPAGE.NR_BLOGS_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BLOGS_READERS_ITM_IX ON HOMEPAGE.NR_BLOGS_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BLOGS_READERS_CD_IX ON HOMEPAGE.NR_BLOGS_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.BLOGS_READERS_SRC_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.BLOGS_READERS_RLL_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.BLOGS_READERS_RDR_STR ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BLOGS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_BLOGS_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.BLOGS_READERS_ROLLUP_IX ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BLOGS_READERS_RIR_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_BLOGS_READERS



-- add fk for table: NR_BOOKMARKS_READERS
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT FK_BKM_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_BOOKMARKS_READERS
--CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_STR_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_ITM_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_CD_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_SRC_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_RDR_STR ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_ROLLUP_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_RIR_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_BOOKMARKS_READERS



-- add fk for table: NR_FILES_READERS
ALTER TABLE HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT FK_FIL_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_FILES_READERS
--CREATE INDEX HOMEPAGE.FILES_READERS_STR_IX ON HOMEPAGE.NR_FILES_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.FILES_READERS_ITM_IX ON HOMEPAGE.NR_FILES_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.FILES_READERS_CD_IX ON HOMEPAGE.NR_FILES_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.FILES_READERS_SRC_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;


CREATE INDEX HOMEPAGE.FILES_READERS_RLL_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.FILES_READERS_RDR_STR ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.FILES_READERS_DEL_SERV_IX ON HOMEPAGE.NR_FILES_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.FILES_READERS_ROLLUP_IX ON HOMEPAGE.NR_FILES_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.FILES_READERS_RIR_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_FILES_READERS



-- add fk for table: NR_FORUMS_READERS
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT FK_FRM_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_FORUMS_READERS
--CREATE INDEX HOMEPAGE.FORUMS_READERS_STR_IX ON HOMEPAGE.NR_FORUMS_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.FORUMS_READERS_ITM_IX ON HOMEPAGE.NR_FORUMS_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.FORUMS_READERS_CD_IX ON HOMEPAGE.NR_FORUMS_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.FORUMS_READERS_SRC_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.FORUMS_READERS_RLL_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.FORUMS_READERS_RDR_STR ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.FORUMS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_FORUMS_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.FORUMS_READERS_ROLLUP_IX ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.FORUMS_READERS_RIR_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_FORUMS_READERS



-- add fk for table: NR_WIKIS_READERS
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT FK_WIK_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_WIKIS_READERS
--CREATE INDEX HOMEPAGE.WIKIS_READERS_STR_IX ON HOMEPAGE.NR_WIKIS_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.WIKIS_READERS_ITM_IX ON HOMEPAGE.NR_WIKIS_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.WIKIS_READERS_CD_IX ON HOMEPAGE.NR_WIKIS_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.WIKIS_READERS_SRC_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.WIKIS_READERS_RLL_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.WIKIS_READERS_RDR_STR ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.WIKIS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_WIKIS_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.WIKIS_READERS_ROLLUP_IX ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.WIKIS_READERS_RIR_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_WIKIS_READERS



-- add fk for table: NR_TAGS_READERS
ALTER TABLE HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT FK_TAG_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_TAGS_READERS
--CREATE INDEX HOMEPAGE.TAGS_READERS_STR_IX ON HOMEPAGE.NR_TAGS_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TAGS_READERS_ITM_IX ON HOMEPAGE.NR_TAGS_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TAGS_READERS_CD_IX ON HOMEPAGE.NR_TAGS_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.TAGS_READERS_SRC_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.TAGS_READERS_RLL_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.TAGS_READERS_RDR_STR ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TAGS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_TAGS_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.TAGS_READERS_ROLLUP_IX ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TAGS_READERS_RIR_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_TAGS_READERS



-- add fk for table: NR_STATUS_UPDATE_READERS
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT FK_STA_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_STATUS_UPDATE_READERS
--CREATE INDEX HOMEPAGE.STATUS_READERS_STR_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.STATUS_READERS_ITM_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.STATUS_READERS_CD_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.STATUS_READERS_SRC_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.STATUS_READERS_RLL_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.STATUS_READERS_RDR_STR ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.STATUS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.STATUS_READERS_RIR_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_STATUS_UPDATE_READERS



-- add fk for table: NR_EXTERNAL_READERS
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT FK_EXT_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_EXTERNAL_READERS
--CREATE INDEX HOMEPAGE.EXTERNAL_READERS_STR_IX ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_ITM_IX ON HOMEPAGE.NR_EXTERNAL_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_CD_IX ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_SRC_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_RDR_STR ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_DEL_SERV_IX ON HOMEPAGE.NR_EXTERNAL_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IX ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_RIR_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_EXTERNAL_READERS



-- add fk for table: NR_ACTIONABLE_READERS
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT FK_ACT_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_ACTIONABLE_READERS
--CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_STR_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_ITM_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_CD_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_RDR_STR ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_DEL_SERV_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_RIR_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_ACTIONABLE_READERS



-- add fk for table: NR_DISCOVERY_VIEW
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW ADD CONSTRAINT FK_DIS_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_DISCOVERY_VIEW
--CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_STR_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_ITM_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_CD_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_SRC_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

-- removed in 107
--CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_RDR_STR ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, STORY_ID);
--COMMIT;

CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_DEL_SERV_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE DESC, IS_BROADCAST);
COMMIT;

CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_ROLLUP_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_ENTRY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_RIR_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_ACT_CD_VIS_IDX  
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ACTOR_UUID, CREATION_DATE DESC, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_DISCOVERY_VIEW



-- add fk for table: NR_PROFILES_VIEW
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW ADD CONSTRAINT FK_PRO_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_PROFILES_VIEW
--CREATE INDEX HOMEPAGE.PROFILES_VIEW_STR_IX ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_VIEW_ITM_IX ON HOMEPAGE.NR_PROFILES_VIEW (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_VIEW_CD_IX ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_VIEW_SRC_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_VIEW_RLL_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_VIEW_RDR_STR ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_VIEW_DEL_SERV_IX ON HOMEPAGE.NR_PROFILES_VIEW (CREATION_DATE DESC, IS_BROADCAST);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IX ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.PROFILES_VIEW_RIR_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_PROFILES_VIEW



-- add fk for table: NR_NOTIFICATION_SENT_READERS
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD CONSTRAINT FK_NOT_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_NOTIFICATION_SENT_READERS
--CREATE INDEX HOMEPAGE.NOTIFICA_READERS_STR_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_ITM_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_CD_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_SRC_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_RDR_STR ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_DEL_SERV_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_RIR_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_NOTIFICATION_SENT_READERS



-- add fk for table: NR_NOTIFICATION_RECEIV_READERS
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD CONSTRAINT FK_REC_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
--CREATE INDEX HOMEPAGE.NOT_REC_READERS_STR_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NOT_REC_READERS_ITM_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NOT_REC_READERS_CD_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.NOT_REC_READERS_SRC_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;


CREATE INDEX HOMEPAGE.NOT_REC_READERS_RLL_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.NOT_REC_READERS_RDR_STR ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NOT_REC_READERS_DEL_SERV_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.NOT_REC_READERS_ROLLUP_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.NOT_REC_READERS_RIR_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS



-- add fk for table: NR_SAVED_READERS
ALTER TABLE HOMEPAGE.NR_SAVED_READERS ADD CONSTRAINT FK_SAV_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_SAVED_READERS
--CREATE INDEX HOMEPAGE.SAVED_READERS_STR_IX ON HOMEPAGE.NR_SAVED_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.SAVED_READERS_ITM_IX ON HOMEPAGE.NR_SAVED_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.SAVED_READERS_CD_IX ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.SAVED_READERS_SRC_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;


CREATE INDEX HOMEPAGE.SAVED_READERS_RLL_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.SAVED_READERS_RDR_STR ON HOMEPAGE.NR_SAVED_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.SAVED_READERS_DEL_SERV_IX ON HOMEPAGE.NR_SAVED_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IX ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.SAVED_READERS_RIR_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_SAVED_READERS



-- add fk for table: NR_TOPICS_READERS
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS ADD CONSTRAINT FK_TOP_READERS_STR  FOREIGN KEY (STORY_ID) REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;


--  [start indexes] NR_TOPICS_READERS
--CREATE INDEX HOMEPAGE.TOPICS_READERS_STR_IX ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TOPICS_READERS_ITM_IX ON HOMEPAGE.NR_TOPICS_READERS (ITEM_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TOPICS_READERS_CD_IX ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.TOPICS_READERS_SRC_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, IS_VISIBLE);
COMMIT;


CREATE INDEX HOMEPAGE.TOPICS_READERS_RLL_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

CREATE INDEX HOMEPAGE.TOPICS_READERS_RDR_STR ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, STORY_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TOPICS_READERS_DEL_SERV_IX ON HOMEPAGE.NR_TOPICS_READERS (CREATION_DATE DESC);
COMMIT;

CREATE INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IX ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID);
COMMIT;

CREATE INDEX HOMEPAGE.TOPICS_READERS_RIR_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

--  [end indexes] NR_TOPICS_READERS

--------------------------------------------------- DROPPING  SPECIFIC INDEX USED BY MIGRATION ROLLUP ----------------------

--  [start indexes] NR_AGGREGATED_READERS
DROP INDEX HOMEPAGE.AGGREGATED_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
DROP INDEX HOMEPAGE.RESPONSES_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
DROP INDEX HOMEPAGE.PROFILES_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
DROP INDEX HOMEPAGE.COMM_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
DROP INDEX HOMEPAGE.ACTIVITIES_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
DROP INDEX HOMEPAGE.BLOGS_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
DROP INDEX HOMEPAGE.BOOKMARKS_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
DROP INDEX HOMEPAGE.FILES_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
DROP INDEX HOMEPAGE.FORUMS_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
DROP INDEX HOMEPAGE.WIKIS_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
DROP INDEX HOMEPAGE.TAGS_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP INDEX HOMEPAGE.STATUS_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP INDEX HOMEPAGE.EXTERNAL_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP INDEX HOMEPAGE.ACTIONABLE_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_ACTIONABLE_READERS


--  [start indexes] NR_DISCOVERY_VIEW
DROP INDEX HOMEPAGE.DISCOVERY_VIEW_MIG_IX;
COMMIT;

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
DROP INDEX HOMEPAGE.PROFILES_VIEW_MIG_IX;
COMMIT;

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP INDEX HOMEPAGE.NOTIFICA_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP INDEX HOMEPAGE.NOT_REC_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
DROP INDEX HOMEPAGE.SAVED_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
DROP INDEX HOMEPAGE.TOPICS_READERS_MIG_IX;
COMMIT;

--  [end indexes] NR_TOPICS_READERS


--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------

DROP INDEX HOMEPAGE.MIG_STR_CORR;
COMMIT;

--70800: [fixup104] add an index on  RELATED_COMMUNITY_ID
CREATE INDEX HOMEPAGE.NR_STORIES_REL_COMM
	ON HOMEPAGE.NR_STORIES (RELATED_COMMUNITY_ID);
COMMIT;	


-----------------------------------------------------------------------------------------------------
-- [START] 70821: [fixup104] After rally we see we can improve of 90% perf. on querying readers table.
-----------------------------------------------------------------------------------------------------

--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX HOMEPAGE.RESPONSES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_RESPONSES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX HOMEPAGE.PROFILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX HOMEPAGE.COMM_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX HOMEPAGE.BLOGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BLOGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX HOMEPAGE.FILES_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FILES_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX HOMEPAGE.FORUMS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_FORUMS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX HOMEPAGE.WIKIS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_WIKIS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX HOMEPAGE.TAGS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TAGS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX HOMEPAGE.STATUS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX HOMEPAGE.SAVED_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX HOMEPAGE.PROFILES_VIEW_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX HOMEPAGE.NOT_REC_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX HOMEPAGE.TOPICS_READERS_RLL_BRD_VIS 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, USE_IN_ROLLUP, IS_VISIBLE); 
COMMIT;

--  [end indexes] NR_TOPICS_READERS

-----------------------------------------------------------------------------------------------------
-- [END] 70821: [fixup104] After rally we see we can improve of 90% perf. on querying readers table.
-----------------------------------------------------------------------------------------------------

CONNECT RESET;





