-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
CONNECT TO HOMEPAGE;


---------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS DROP CONSTRAINT FK_NOT_SENT_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_TAGS_READERS DROP CONSTRAINT FK_TAGS_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS DROP CONSTRAINT FK_BLOGS_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS DROP CONSTRAINT FK_RESP_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS DROP CONSTRAINT FK_NOT_REC_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT FK_SU_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_FILES_READERS DROP CONSTRAINT FK_FILES_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW DROP CONSTRAINT FK_DISCOVERY_VIEW_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS DROP CONSTRAINT FK_TOPICS_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS DROP CONSTRAINT FK_BOOK_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS DROP CONSTRAINT FK_MENT_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS DROP CONSTRAINT FK_PROF_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT FK_EXT_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS DROP CONSTRAINT FK_ACTIVITIES_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS DROP CONSTRAINT FK_WIKIS_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT FK_ACT_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_SAVED_READERS DROP CONSTRAINT FK_SAVED_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS DROP CONSTRAINT FK_COMM_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS DROP CONSTRAINT FK_FORUMS_READERS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW DROP CONSTRAINT FK_PRF_VIEW_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST DROP CONSTRAINT FK_AS_SEEDLIST_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS DROP CONSTRAINT FK_BRD_RECOMM_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW DROP CONSTRAINT FK_COMM_PERSON_FOLLOW_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_OBJ_REFERENCE_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.WIDGET DROP CONSTRAINT FK_WIDGET_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BOARD_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT DROP CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP CONSTRAINT FK_FOLLOWS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP CONSTRAINT FK_NEWS_COMMENT_CONTENT_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW DROP CONSTRAINT FK_COMM_FOLLOW_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NT_REPLYTO DROP CONSTRAINT FK_REPLYTO_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP CONSTRAINT FK_WIDGET_TAB_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP CONSTRAINT FK_EMD_RES_PREF_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.EMD_TRANCHE DROP CONSTRAINT FK_EMD_TRANCHE_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT DROP CONSTRAINT FK_STORIES_CONTENT_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_NETWORK DROP CONSTRAINT FK_NETWORK_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.LOGINNAME DROP CONSTRAINT FK_LN_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.PERSON DROP CONSTRAINT FK_PERSON_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE DROP CONSTRAINT FK_ENTRIES_ARCHIVE_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS DROP CONSTRAINT FK_AS_CNT_INDEX_STATS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.PREREQ DROP CONSTRAINT FK_PREREQ_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE DROP CONSTRAINT FK_DEL_STORIES_QUEUE_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_MENTIONS DROP CONSTRAINT FK_BOARD_MENTIONS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE DROP CONSTRAINT FK_SOURCE_TYPE_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT DROP CONSTRAINT FK_STATUS_COMMENT_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.HP_TAB_INST DROP CONSTRAINT FK_TAB_INST_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT FK_RESOURCE_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS DROP CONSTRAINT FK_EMD_EMAIL_PREFS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP CONSTRAINT FK_WIDGET_INST_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.MT_METRIC_STAT DROP CONSTRAINT FK_METRIC_STAT_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.HP_UI DROP CONSTRAINT FK_UI_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP CONSTRAINT FK_BOARD_CURRENT_STATUS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK DROP CONSTRAINT FK_NEWS_STATUS_NETWORK_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_COMMENTS  DROP CONSTRAINT FK_BOARD_COMMENTS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES DROP CONSTRAINT FK_ENTRIES_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_SOURCE DROP CONSTRAINT FK_SOURCE_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT FK_BOARD_ENTRIES_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_STORIES DROP CONSTRAINT FK_STORIES_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS DROP CONSTRAINT FK_COMM_SETTINGS_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO DROP CONSTRAINT FK_EMD_TRANCHE_INFO_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT DROP CONSTRAINT FK_STATUS_CONTENT_ORG_ID;
COMMIT;

ALTER TABLE HOMEPAGE.HP_TAB DROP CONSTRAINT FK_TAB_ORG_ID;
COMMIT;


---------------------------------------------------------------------------


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- SEARCH TABLES


----------------------------------------
--  SR_SANDTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_SANDTASKDEF DROP FOREIGN KEY "FK_ST_TASK_ID";

----------------------------------------
--  SR_FILECONTENTTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF DROP FOREIGN KEY "FK_FC_TASK_ID";

----------------------------------------
--  SR_BACKUPTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_BACKUPTASKDEF DROP FOREIGN KEY "FK_BKUP_TASK_ID";

----------------------------------------
--  SR_INDEXTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF DROP FOREIGN KEY "FK_INDEX_TASK_ID";

----------------------------------------
--  SR_OPTIMIZETASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF DROP FOREIGN KEY "FK_OPT_TASK_ID";

----------------------------------------
--  SR_RESUME_TOKENS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_RESUME_TOKENS DROP FOREIGN KEY "FK_RT_IDX_MGMT_ID";

----------------------------------------
--  SR_FEEDBACK
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK DROP FOREIGN KEY "FK_SRFB_PERSON_ID";

----------------------------------------
--  SR_FEEDBACK_CONTEXT
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK_CONTEXT DROP FOREIGN KEY "FK_FBK_CTXT_ID";

----------------------------------------
--  SR_FEEDBACK_PARAMETERS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK_PARAMETERS DROP FOREIGN KEY "FK_FBK_PARAMS_ID";

----------------------------------------
--  SR_STRING_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_STRING_STATS DROP FOREIGN KEY "FK_STR_STAT_ID";

----------------------------------------
--  SR_NUMBER_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_NUMBER_STATS DROP FOREIGN KEY "FK_NUM_STAT_ID";

----------------------------------------
--  SR_TIMER_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_TIMER_STATS DROP FOREIGN KEY "FK_TMR_STAT_ID";


--NO FKS YET FOR 4.5



-- SEARCH deletion

-- REMOVING RECORDS -----------------

DELETE FROM HOMEPAGE.SR_FILECONTENTTASKDEF;

DELETE FROM HOMEPAGE.SR_SANDTASKDEF;

DELETE FROM HOMEPAGE.SR_BACKUPTASKDEF;

DELETE FROM HOMEPAGE.SR_INDEXINGTASKDEF;

DELETE FROM HOMEPAGE.SR_OPTIMIZETASKDEF;

DELETE FROM HOMEPAGE.SR_TASKDEF;

DELETE FROM HOMEPAGE.SR_FILESCONTENT;

DELETE FROM HOMEPAGE.SR_MIGTASKDEFINFO;

DELETE FROM HOMEPAGE.SR_INDEX_DOCS;

DELETE FROM HOMEPAGE.SR_RESUME_TOKENS;

DELETE FROM HOMEPAGE.SR_INDEX_MANAGEMENT;

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMGR;

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMPR;

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTASK;

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTREG;

DELETE FROM HOMEPAGE.SR_FEEDBACK;

DELETE FROM HOMEPAGE.SR_FEEDBACK_CONTEXT;

DELETE FROM HOMEPAGE.SR_FEEDBACK_PARAMETERS;

DELETE FROM HOMEPAGE.SR_STATS;

DELETE FROM HOMEPAGE.SR_STRING_STATS;

DELETE FROM HOMEPAGE.SR_NUMBER_STATS;

DELETE FROM HOMEPAGE.SR_TIMER_STATS;

DELETE FROM HOMEPAGE.SR_GLOBAL_SAND_PROPS; 

DELETE FROM HOMEPAGE.SR_ECM_DOCUMENT_TYPE_PROPS;

DELETE FROM HOMEPAGE.SR_ECM_DOCUMENT_TYPE_LABELS;

DELETE FROM HOMEPAGE.SR_POST_FILTERING_SERVICE;


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- NEWS RECORDS 

--DROP INDEX  HOMEPAGE.NR_SOURCE_IX_UNIQUE;

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP FOREIGN KEY "FK_C_COMMENT_ID";

ALTER TABLE HOMEPAGE.NR_RESOURCE DROP FOREIGN KEY "FK_RES_RES_TYPE";
ALTER TABLE HOMEPAGE.NR_RESOURCE DROP FOREIGN KEY "FK_RES_CAT_TYPE";
ALTER TABLE HOMEPAGE.NR_RESOURCE_TYPE DROP UNIQUE "RES_TYPE_UNIQUE";
ALTER TABLE HOMEPAGE.NR_FOLLOWS  DROP FOREIGN KEY "FK_FS_PERSON_ID";
ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP FOREIGN KEY "FK_FS_RESOURCE_ID";
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW DROP FOREIGN KEY "FK_COMM_PERSON_ID";

ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW DROP FOREIGN KEY "FK_COMM_PER_PER_ID";

ALTER TABLE HOMEPAGE.NR_NETWORK DROP FOREIGN KEY "FK_NTW_PERS_ID";
ALTER TABLE HOMEPAGE.NR_NETWORK DROP FOREIGN KEY  "FK_NTW_COLL_ID";

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP FOREIGN KEY "FK_RES_PERSON_ID"; 
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP FOREIGN KEY "FK_RES_FRQ_TYPE";
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS DROP FOREIGN KEY "FK_EMD_PERSON_ID";
ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE DROP UNIQUE "FRQ_TYPE_UNIQUE";
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO DROP FOREIGN KEY "FK_TRANCHE_ID";

-- BOARD
ALTER TABLE HOMEPAGE.BOARD_COMMENTS DROP CONSTRAINT FK_BRD_COM_ENTRY;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_OBJ_ENTRY;
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_AUTHOR_ID;

ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP FOREIGN KEY FK_CUR_ST_ACTOR_ID;
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP FOREIGN KEY FK_CUR_ST_ENTRY_ID;

ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_OWNER;
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_CREATED;
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BRD_LASTUPDATE;

ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT FK_CONTAINER_ID;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS 	DROP CONSTRAINT FK_BRD_RECOMMENDER;

COMMIT;

ALTER TABLE HOMEPAGE.BOARD_MENTIONS 	DROP CONSTRAINT FK_BRD_MEN_PER_ID;
COMMIT;

ALTER TABLE HOMEPAGE.NR_STORIES DROP CONSTRAINT FK_ENTRY_ID;
COMMIT;

-----------------------------------------------------------------------------------
-- [START] FK KEY FROM READERS TO STORIES TABLE
-----------------------------------------------------------------------------------
-- DROPing the fk
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS DROP CONSTRAINT FK_RES_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS DROP CONSTRAINT FK_PRF_READERS_STR;
COMMIT;		
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS DROP CONSTRAINT FK_COM_READERS_STR;
COMMIT;	 
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS DROP CONSTRAINT FK_ACI_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS DROP CONSTRAINT FK_BLG_READERS_STR;
COMMIT;	 
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS DROP CONSTRAINT FK_BKM_READERS_STR;
COMMIT;	 
ALTER TABLE HOMEPAGE.NR_FILES_READERS DROP CONSTRAINT FK_FIL_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS DROP CONSTRAINT FK_FRM_READERS_STR;
COMMIT;	 
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS DROP CONSTRAINT FK_WIK_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_TAGS_READERS DROP CONSTRAINT FK_TAG_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT FK_STA_READERS_STR;
COMMIT;	 
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT FK_EXT_READERS_STR;
COMMIT;	
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT FK_ACT_READERS_STR;
COMMIT;		
ALTER TABLE HOMEPAGE.NR_SAVED_READERS DROP CONSTRAINT FK_SAV_READERS_STR;
COMMIT;	 
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW DROP CONSTRAINT FK_DIS_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW DROP CONSTRAINT FK_PRO_READERS_STR;
COMMIT;	 
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS DROP CONSTRAINT FK_NOT_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS DROP CONSTRAINT FK_REC_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS DROP CONSTRAINT  FK_TOP_READERS_STR;
COMMIT;
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS DROP CONSTRAINT  FK_MEN_READERS_STR;
COMMIT;

ALTER TABLE HOMEPAGE.OAUTH2_CLIENT DROP CONSTRAINT FK_CLIENT_PRO_NAME;
ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING DROP CONSTRAINT FK_BINDING_CLIENT;
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT  DROP CONSTRAINT CLNT_FK;
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT DROP CONSTRAINT CLNT_TOKEN_FK;
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT CONTEXT_CLNT_FK;
ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT AUTH_TOKEN_FK;

ALTER TABLE HOMEPAGE.OAUTH1_CONTEXT DROP CONSTRAINT FK_OA1C_PERSON_ID;
ALTER TABLE HOMEPAGE.OAUTH2_TOKEN DROP CONSTRAINT FK_OA2T_PERSON_ID;

ALTER TABLE HOMEPAGE.OAUTH2_GADGET_BINDING DROP CONSTRAINT FK_BINDING_WIDGET;
ALTER TABLE HOMEPAGE.OAUTH1_CLIENT DROP CONSTRAINT FK_OA1CL_PERSON_ID;


COMMIT;

-----------------------------------------------------------------------------------
-- [END] FK KEY FROM READERS TO STORIES TABLE
-----------------------------------------------------------------------------------

DELETE FROM HOMEPAGE.NR_STORIES;
DELETE FROM HOMEPAGE.NR_ENTRIES;
DELETE FROM HOMEPAGE.NR_ENTRIES_ARCHIVE;

DELETE FROM HOMEPAGE.NR_COMM_SETTINGS;

DELETE FROM HOMEPAGE.DELETED_STORIES_QUEUE;

-- News delete board tables
DELETE FROM HOMEPAGE.BOARD_CURRENT_STATUS;
DELETE FROM HOMEPAGE.BOARD_RECOMMENDATIONS;
DELETE FROM HOMEPAGE.BOARD_OBJECT_REFERENCE;
DELETE FROM HOMEPAGE.BOARD_COMMENTS;
DELETE FROM HOMEPAGE.BOARD_ENTRIES;
DELETE FROM HOMEPAGE.BOARD;

-- New delete categories stories
DELETE FROM HOMEPAGE.NR_DISCOVERY_VIEW;
DELETE FROM HOMEPAGE.NR_RESPONSES_READERS;
DELETE FROM HOMEPAGE.NR_PROFILES_READERS;
DELETE FROM HOMEPAGE.NR_COMMUNITIES_READERS;
DELETE FROM HOMEPAGE.NR_ACTIVITIES_READERS;
DELETE FROM HOMEPAGE.NR_BLOGS_READERS;
DELETE FROM HOMEPAGE.NR_BOOKMARKS_READERS;
DELETE FROM HOMEPAGE.NR_FILES_READERS;
DELETE FROM HOMEPAGE.NR_FORUMS_READERS;
DELETE FROM HOMEPAGE.NR_WIKIS_READERS;
DELETE FROM HOMEPAGE.NR_TAGS_READERS;
DELETE FROM HOMEPAGE.NR_STATUS_UPDATE_READERS;
DELETE FROM HOMEPAGE.NR_DISCOVERY_VIEW;
DELETE FROM HOMEPAGE.NR_PROFILES_VIEW;
DELETE FROM HOMEPAGE.NR_NOTIFICATION_SENT_READERS;
DELETE FROM HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
DELETE FROM HOMEPAGE.NR_TOPICS_READERS;
 
DELETE FROM HOMEPAGE.NR_AS_SEEDLIST; 
DELETE FROM HOMEPAGE.NR_AS_COLLECTION_CONFIG; 
DELETE FROM HOMEPAGE.NR_AS_CRAWLER_STATUS; 

COMMIT;

-- NEWS deletion


DELETE FROM HOMEPAGE.NR_SOURCE;
DELETE FROM HOMEPAGE.NR_TEMPLATE;

DELETE FROM HOMEPAGE.NR_CATEGORY_TYPE;

DELETE FROM HOMEPAGE.NR_NEWS_COMMENT_CONTENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_CONTENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_COMMENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_NETWORK;

DELETE FROM HOMEPAGE.NR_AGGREGATED_READERS;
DELETE FROM HOMEPAGE.NR_COMM_PERSON_FOLLOW;
DELETE FROM HOMEPAGE.NR_NETWORK;
DELETE FROM HOMEPAGE.NR_STORIES_CONTENT;

DELETE FROM HOMEPAGE.NR_COMM_FOLLOW;
DELETE FROM HOMEPAGE.NR_FOLLOWS;	
DELETE FROM HOMEPAGE.NR_RESOURCE;
DELETE FROM HOMEPAGE.NR_RESOURCE_TYPE;

-- EMail Digest deletion
DELETE FROM HOMEPAGE.EMD_EMAIL_PREFS;
DELETE FROM HOMEPAGE.EMD_TRANCHE_INFO;
DELETE FROM HOMEPAGE.EMD_TRANCHE;
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF;
DELETE FROM HOMEPAGE.EMD_FREQUENCY_TYPE;


DELETE FROM HOMEPAGE.NR_SOURCE_TYPE; 

-- Delete actionable stories
DELETE FROM HOMEPAGE.NR_ACTIONABLE_READERS;
DELETE FROM HOMEPAGE.NR_SAVED_READERS;
DELETE FROM HOMEPAGE.NR_DISCOVERY_VIEW;

DELETE FROM HOMEPAGE.OAUTH2_TOKEN;
DELETE FROM HOMEPAGE.OAUTH2_GADGET_BINDING;
DELETE FROM HOMEPAGE.OAUTH2_CLIENT;
DELETE FROM HOMEPAGE.OAUTH2_PROVIDER;
DELETE FROM HOMEPAGE.OAUTH1_CONTEXT;
DELETE FROM HOMEPAGE.OAUTH1_CLIENT;
DELETE FROM HOMEPAGE.OAUTH1_PROVIDER;
DELETE FROM HOMEPAGE.OAUTH1_TOKEN;

DELETE FROM HOMEPAGE.NR_AS_CONTENT_INDEX_STATS;



----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
-- REMOVE indexes
 ---------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------


--  [start indexes] NR_AGGREGATED_READERS
DROP  INDEX HOMEPAGE.AGGREGATED_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
DROP  INDEX HOMEPAGE.RESPONSES_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
DROP  INDEX HOMEPAGE.PROFILES_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
DROP  INDEX HOMEPAGE.COMM_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
DROP  INDEX HOMEPAGE.BLOGS_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
DROP  INDEX HOMEPAGE.FILES_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
DROP  INDEX HOMEPAGE.FORUMS_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
DROP  INDEX HOMEPAGE.WIKIS_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
DROP  INDEX HOMEPAGE.TAGS_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX HOMEPAGE.STATUS_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX HOMEPAGE.EXTERNAL_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_SAVED_READERS
DROP  INDEX HOMEPAGE.SAVED_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_RLL_BRD_VIS;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_SR_IX;
COMMIT;


--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_IX;
COMMIT;


DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_BRD_VIS;
COMMIT;


DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_ACT_CD_VIS_IDX ;
COMMIT;

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX HOMEPAGE.PROFILES_VIEW_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX HOMEPAGE.NOTIFICA_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP  INDEX HOMEPAGE.NOT_REC_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_TOPICS_READERS
DROP  INDEX HOMEPAGE.TOPICS_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_RLL_BRD_VIS;
COMMIT;



--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
DROP  INDEX HOMEPAGE.MENTIONS_READERS_STR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_ITM_IX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_CD_IX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_SRC_IX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_RLL_IX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_RDR_STR;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_DEL_SERV_IX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_RIR_IX;
COMMIT;

DROP  INDEX HOMEPAGE.MENTIONS_READERS_RLL_BRD_VIS;
COMMIT;


--  [end indexes] NR_MENTIONS_READERS

----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
-- REMOVE indexes
 ---------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------



-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

-- HOMEPAGE 
ALTER TABLE HOMEPAGE.LOGINNAME DROP FOREIGN KEY "FK_LN_PERSON_ID";
ALTER TABLE HOMEPAGE.HP_UI DROP FOREIGN KEY "FK_UI_PERSON_ID";
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP FOREIGN KEY "FK_UI_ID";
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP FOREIGN KEY "FK_TAB_INST_TAB_ID";
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP FOREIGN KEY "FK_WIDGET_ID";
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP FOREIGN KEY "FK_TAB_INST_ID";
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP FOREIGN KEY "FK_WID_TAB_WID_ID";
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP FOREIGN KEY "FK_WID_TAB_TAB_ID";
ALTER TABLE HOMEPAGE.PREREQ DROP FOREIGN KEY "FK_PREREQ_WIDGET";



DROP INDEX  HOMEPAGE.PERSON_EXID;


-- HOMEPAGE deletion
DELETE FROM HOMEPAGE.HOMEPAGE_SCHEMA;
DELETE FROM HOMEPAGE.LOGINNAME;
DELETE FROM HOMEPAGE.HP_WIDGET_INST;
DELETE FROM HOMEPAGE.HP_TAB_INST;
DELETE FROM HOMEPAGE.HP_WIDGET_TAB; 
DELETE FROM HOMEPAGE.HP_UI;
DELETE FROM HOMEPAGE.HP_TAB;
DELETE FROM HOMEPAGE.PREREQ;
DELETE FROM HOMEPAGE.WIDGET;



DELETE FROM HOMEPAGE.PERSON;
DELETE FROM HOMEPAGE.MT_METRIC_STAT;

-- NEW SECTION FOR 3.5

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT DROP FOREIGN KEY "FK_REPLYTO_NOT_ID";
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT DROP FOREIGN KEY "FK_REPLYTO_PER_ID";

DELETE FROM HOMEPAGE.NT_REPLYTO_RECIPIENT;
DELETE FROM HOMEPAGE.NT_REPLYTO;

DELETE FROM HOMEPAGE.MT_ORGANIZATION;

-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



COMMIT;
CONNECT RESET;
