-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
CONNECT TO HOMEPAGE;

------------------------------------------------
-- INCLUDE PREDBXFER30 FOR SEARCH
------------------------------------------------


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- SEARCH TABLES


----------------------------------------
--  SR_SANDTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_SANDTASKDEF DROP UNIQUE "UNIQUE_TASK_ID_ST";

ALTER TABLE HOMEPAGE.SR_SANDTASKDEF DROP FOREIGN KEY "FK_ST_TASK_ID";

----------------------------------------
--  SR_FILECONTENTTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF DROP UNIQUE  "UNIQUE_TASK_ID_FC";

ALTER TABLE HOMEPAGE.SR_FILECONTENTTASKDEF DROP FOREIGN KEY "FK_FC_TASK_ID";

----------------------------------------
--  SR_BACKUPTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_BACKUPTASKDEF DROP UNIQUE "UNIQUE_TASK_ID_BKP";

ALTER TABLE HOMEPAGE.SR_BACKUPTASKDEF DROP FOREIGN KEY "FK_BKUP_TASK_ID";

----------------------------------------
--  SR_INDEXTASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF DROP FOREIGN KEY "FK_INDEX_TASK_ID";

ALTER TABLE HOMEPAGE.SR_INDEXINGTASKDEF DROP UNIQUE "UNIQUE_TASK_ID_IND";

----------------------------------------
--  SR_OPTIMIZETASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF DROP UNIQUE "UNIQUE_TASK_ID_OPT";

ALTER TABLE HOMEPAGE.SR_OPTIMIZETASKDEF DROP FOREIGN KEY "FK_OPT_TASK_ID";

----------------------------------------
--  SR_TASKDEF
----------------------------------------

ALTER TABLE HOMEPAGE.SR_TASKDEF DROP UNIQUE "UNIQUE_TASK_NAME";

ALTER TABLE HOMEPAGE.SR_TASKDEF DROP CHECK "CHECK_SR_TASKDEF";

----------------------------------------
--  SR_FILESCONTENT
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FILESCONTENT DROP UNIQUE "UNIQUE_COMP_UUID";

DROP INDEX  HOMEPAGE.SR_FILESCONTENT_IS_CURRENT_IDX;


----------------------------------------
--  SR_RESUME_TOKENS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_RESUME_TOKENS DROP FOREIGN KEY "FK_RT_IDX_MGMT_ID";


----------------------------------------
--  SR_FACET_DOCS
----------------------------------------


ALTER TABLE HOMEPAGE.SR_FACET_DOCS    DROP FOREIGN KEY  "FK_IDX_DOC_ID"; 

DROP INDEX HOMEPAGE.SR_FACET_DOCS_PARENT_IDX;

----------------------------------------
--  SR_INDEX_DOCS
----------------------------------------

DROP INDEX  HOMEPAGE.SR_INDEX_CRAWL_VERSION_IDX;

----------------------------------------
--  SR_FEEDBACK
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK DROP FOREIGN KEY "FK_SRFB_PERSON_ID";

DROP INDEX HOMEPAGE.SR_FEEDBACK_CLIENT_IDX;

----------------------------------------
--  SR_FEEDBACK_CONTEXT
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK_CONTEXT DROP FOREIGN KEY "FK_FBK_CTXT_ID";

----------------------------------------
--  SR_FEEDBACK_PARAMETERS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_FEEDBACK_PARAMETERS DROP FOREIGN KEY "FK_FBK_PARAMS_ID";

----------------------------------------
--  SR_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_STATS DROP  UNIQUE "UNIQUE_STAT_KEY";

----------------------------------------
--  SR_STRING_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_STRING_STATS DROP FOREIGN KEY "FK_STR_STAT_ID";

----------------------------------------
--  SR_NUMBER_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_NUMBER_STATS DROP FOREIGN KEY "FK_NUM_STAT_ID";

----------------------------------------
--  SR_TIMER_STATS
----------------------------------------

ALTER TABLE HOMEPAGE.SR_TIMER_STATS DROP FOREIGN KEY "FK_TMR_STAT_ID";


-- SEARCH deletion

-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


-- REMOVING RECORDS -----------------

DELETE FROM HOMEPAGE.SR_FILECONTENTTASKDEF;

DELETE FROM HOMEPAGE.SR_SANDTASKDEF;

DELETE FROM HOMEPAGE.SR_BACKUPTASKDEF;

DELETE FROM HOMEPAGE.SR_INDEXINGTASKDEF;

DELETE FROM HOMEPAGE.SR_OPTIMIZETASKDEF;

DELETE FROM HOMEPAGE.SR_TASKDEF;

DELETE FROM HOMEPAGE.SR_FILESCONTENT;

DELETE FROM HOMEPAGE.SR_MIGTASKDEFINFO;

DELETE FROM HOMEPAGE.SR_INDEX_DOCS;

DELETE FROM HOMEPAGE.SR_FACET_DOCS;

DELETE FROM HOMEPAGE.SR_RESUME_TOKENS;

DELETE FROM HOMEPAGE.SR_INDEX_MANAGEMENT;

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMGR;

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSLMPR;

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTASK;

DELETE FROM HOMEPAGE.LOTUSCONNECTIONSTREG;

DELETE FROM HOMEPAGE.SR_FEEDBACK;

DELETE FROM HOMEPAGE.SR_FEEDBACK_CONTEXT;

DELETE FROM HOMEPAGE.SR_FEEDBACK_PARAMETERS;

DELETE FROM HOMEPAGE.SR_STATS;

DELETE FROM HOMEPAGE.SR_STRING_STATS;

DELETE FROM HOMEPAGE.SR_NUMBER_STATS;

DELETE FROM HOMEPAGE.SR_TIMER_STATS;





-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END Search Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


------------------------------------------------
-- INCLUDE PREDBXFER30 FOR NEWS
------------------------------------------------


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- NEWS RECORDS 
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION DROP FOREIGN KEY "FK_PERSON_ID";
ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION DROP FOREIGN KEY "FK_SOURCE_ID";
DROP INDEX  HOMEPAGE.NR_SUBSCRIPTION_IX_UNIQUE;
--DROP INDEX  HOMEPAGE.NR_SOURCE_IX_UNIQUE;

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP FOREIGN KEY "FK_C_COMMENT_ID";

ALTER TABLE HOMEPAGE.NR_RESOURCE DROP FOREIGN KEY "FK_RES_RES_TYPE";
ALTER TABLE HOMEPAGE.NR_RESOURCE DROP FOREIGN KEY "FK_RES_CAT_TYPE";
ALTER TABLE HOMEPAGE.NR_RESOURCE_TYPE DROP UNIQUE "RES_TYPE_UNIQUE";
ALTER TABLE HOMEPAGE.NR_FOLLOWS  DROP FOREIGN KEY "FK_FS_PERSON_ID";
ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP FOREIGN KEY "FK_FS_RESOURCE_ID";
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW DROP FOREIGN KEY "FK_COMM_PERSON_ID";
ALTER TABLE HOMEPAGE.NR_ORGPERSON_FOLLOW DROP FOREIGN KEY "FK_ORGP_PERSON_ID";

--ALTER TABLE HOMEPAGE.NR_COMM_STORIES DROP FOREIGN KEY "FK_COMM_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_ORGPERSON_STORIES  DROP FOREIGN KEY "FK_ORGP_STORY_ID";
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW DROP FOREIGN KEY "FK_COMM_PER_PER_ID";
--ALTER TABLE HOMEPAGE.NR_COMM_PERSON_STORIES DROP FOREIGN KEY "FK_FCP_STORY_ID";

ALTER TABLE HOMEPAGE.NR_NETWORK DROP FOREIGN KEY "FK_NTW_PERS_ID";
ALTER TABLE HOMEPAGE.NR_NETWORK DROP FOREIGN KEY  "FK_NTW_COLL_ID";

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP FOREIGN KEY "FK_RES_PERSON_ID"; 
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP FOREIGN KEY "FK_RES_FRQ_TYPE";
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS DROP FOREIGN KEY "FK_EMD_PERSON_ID";
ALTER TABLE HOMEPAGE.EMD_FREQUENCY_TYPE DROP UNIQUE "FRQ_TYPE_UNIQUE";
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO DROP FOREIGN KEY "FK_TRANCHE_ID";

--ALTER TABLE HOMEPAGE.NR_RESPONSES_STORIES DROP FOREIGN KEY "FK_RESP_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_PROFILES_STORIES DROP FOREIGN KEY "FK_PROF_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_COMMUNITIES_STORIES DROP FOREIGN KEY "FK_COM_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_ACTIVITIES_STORIES DROP FOREIGN KEY "FK_ACT_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_BLOGS_STORIES DROP FOREIGN KEY "FK_BLOGS_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_BOOKMARKS_STORIES DROP FOREIGN KEY "FK_BOOKS_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_FILES_STORIES DROP FOREIGN KEY "FK_FILES_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_FORUMS_STORIES DROP FOREIGN KEY "FK_FORUMS_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_WIKIS_STORIES DROP FOREIGN KEY "FK_WIKIS_STORY_ID";
--ALTER TABLE HOMEPAGE.NR_TAGS_STORIES DROP FOREIGN KEY "FK_TAGS_STORY_ID";

-- New delete categories stories
DELETE FROM HOMEPAGE.NR_RESPONSES_STORIES;
DELETE FROM HOMEPAGE.NR_PROFILES_STORIES;
DELETE FROM HOMEPAGE.NR_COMMUNITIES_STORIES;
DELETE FROM HOMEPAGE.NR_ACTIVITIES_STORIES;
DELETE FROM HOMEPAGE.NR_BLOGS_STORIES;
DELETE FROM HOMEPAGE.NR_BOOKMARKS_STORIES;
DELETE FROM HOMEPAGE.NR_FILES_STORIES;
DELETE FROM HOMEPAGE.NR_FORUMS_STORIES;
DELETE FROM HOMEPAGE.NR_WIKIS_STORIES;
DELETE FROM HOMEPAGE.NR_TAGS_STORIES;

-- NEWS deletion
DELETE FROM HOMEPAGE.NR_NEWS_RECORDS;
DELETE FROM HOMEPAGE.NR_SUBSCRIPTION;
DELETE FROM HOMEPAGE.NR_SOURCE;
DELETE FROM HOMEPAGE.NR_TEMPLATE;

DELETE FROM HOMEPAGE.NR_CATEGORY_TYPE;
DELETE FROM HOMEPAGE.NR_NEWS_SAVED;
DELETE FROM HOMEPAGE.NR_NEWS_DISCOVERY;

DELETE FROM HOMEPAGE.NR_NEWS_COMMENT_CONTENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_CONTENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_COMMENT;
DELETE FROM HOMEPAGE.NR_NEWS_STATUS_NETWORK;

DELETE FROM HOMEPAGE.NR_COMM_PERSON_STORIES;
DELETE FROM HOMEPAGE.NR_COMM_PERSON_FOLLOW;
DELETE FROM HOMEPAGE.NR_NETWORK;
DELETE FROM HOMEPAGE.NR_STORIES_CONTENT;
DELETE FROM HOMEPAGE.NR_ORGPERSON_STORIES;
DELETE FROM HOMEPAGE.NR_COMM_STORIES;

DELETE FROM HOMEPAGE.NR_ORGPERSON_FOLLOW;
DELETE FROM HOMEPAGE.NR_COMM_FOLLOW;
DELETE FROM HOMEPAGE.NR_FOLLOWS;	
DELETE FROM HOMEPAGE.NR_RESOURCE;
DELETE FROM HOMEPAGE.NR_RESOURCE_TYPE;
DELETE FROM HOMEPAGE.NR_STORIES;

-- EMail Digest deletion
DELETE FROM HOMEPAGE.EMD_EMAIL_PREFS;
DELETE FROM HOMEPAGE.EMD_TRANCHE_INFO;
DELETE FROM HOMEPAGE.EMD_TRANCHE;
DELETE FROM HOMEPAGE.EMD_RESOURCE_PREF;
DELETE FROM HOMEPAGE.EMD_FREQUENCY_TYPE;

-- Delete notifications NT_NOTIFICATIONs
DELETE FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT;
DELETE FROM HOMEPAGE.NT_NOTIFICATION;

-- Delete content from news scheduler tables
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMPR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_LMGR;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TREG;
DELETE FROM HOMEPAGE.NR_SCHEDULER_TASK;

--Delete content from the recommendatins and attachments tables
DELETE FROM HOMEPAGE.NR_RECOMMENDATION;
DELETE FROM HOMEPAGE.NR_ATTACHMENT;    

-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


------------------------------------------------
-- INCLUDE PREDBXFER30 FOR HP
------------------------------------------------


-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- START: NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- HOMEPAGE 
ALTER TABLE HOMEPAGE.LOGINNAME DROP FOREIGN KEY "FK_LN_PERSON_ID";
ALTER TABLE HOMEPAGE.HP_UI DROP FOREIGN KEY "FK_UI_PERSON_ID";
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP FOREIGN KEY "FK_UI_ID";
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP FOREIGN KEY "FK_TAB_INST_TAB_ID";
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP FOREIGN KEY "FK_WIDGET_ID";
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP FOREIGN KEY "FK_TAB_INST_ID";
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP FOREIGN KEY "FK_WID_TAB_WID_ID";
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP FOREIGN KEY "FK_WID_TAB_TAB_ID";
ALTER TABLE HOMEPAGE.PREREQ DROP FOREIGN KEY "FK_PREREQ_WIDGET";

ALTER TABLE HOMEPAGE.NT_NOTIFICATION DROP FOREIGN KEY "FK_SENDER_ID";
ALTER TABLE HOMEPAGE.NT_NOTIFICATION DROP FOREIGN KEY "FK_F_RECIPIENT_ID";
ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT DROP FOREIGN KEY "FK_RECIP_NOTIF";
ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT DROP FOREIGN KEY "FK_RECIPIENT_ID";

ALTER TABLE HOMEPAGE.LOGINNAME DROP UNIQUE "LOGINNAME_UNIQUE";
DROP INDEX  HOMEPAGE.PERSON_EXID;

-- HOMEPAGE deletion
DELETE FROM HOMEPAGE.HOMEPAGE_SCHEMA;
DELETE FROM HOMEPAGE.LOGINNAME;
DELETE FROM HOMEPAGE.HP_WIDGET_INST;
DELETE FROM HOMEPAGE.HP_TAB_INST;
DELETE FROM HOMEPAGE.HP_WIDGET_TAB; 
DELETE FROM HOMEPAGE.HP_UI;
DELETE FROM HOMEPAGE.HP_TAB;
DELETE FROM HOMEPAGE.PREREQ;
DELETE FROM HOMEPAGE.WIDGET;

-- Delete notifications NT_NOTIFICATIONs
DELETE FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT;
DELETE FROM HOMEPAGE.NT_NOTIFICATION;

DELETE FROM HOMEPAGE.PERSON;
DELETE FROM HOMEPAGE.MT_METRIC_STAT;

-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
-- END NewsHp Schema
-- %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


DELETE FROM HOMEPAGE.NR_RECOMMENDATION;
DELETE FROM HOMEPAGE.NR_ATTACHMENT;


COMMIT;
CONNECT RESET;
