-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
connect to HOMEPAGE;

REORGCHK;
commit;

-- 117915: AC deployment manager installation failed in minidev (D6) env
ALTER TABLE HOMEPAGE.NR_STORIES ADD CONSTRAINT FK_STORIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

--92652: Add fixup210 to ﻿upgrade-45-50-sc.sql
{include.news-fixup210.sql}

------------------------------------------------
-- Include purge AS tables: 90357: Purge activity stream tables (just SC)
------------------------------------------------
{include.sc-45-50-purge-as-tables.sql}


-- ************************************************************************* --
-- ************************************************************************* --
-- ************************************************************************* --
--[Work Item 113963] Delivery of con_home DB schema updates [s]
-- including c&p post-java-migration.sql
------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST ADD CONSTRAINT FK_AS_SEEDLIST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS ADD CONSTRAINT FK_BRD_RECOMM_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW ADD CONSTRAINT FK_COMM_PERSON_FOLLOW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE ADD CONSTRAINT FK_BRD_OBJ_REFERENCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.WIDGET ADD CONSTRAINT FK_WIDGET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.BOARD ADD CONSTRAINT FK_BOARD_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ADD CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_FOLLOWS ADD CONSTRAINT FK_FOLLOWS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT ADD CONSTRAINT FK_NEWS_COMMENT_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW ADD CONSTRAINT FK_COMM_FOLLOW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NT_REPLYTO ADD CONSTRAINT FK_REPLYTO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ADD CONSTRAINT FK_WIDGET_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF ADD CONSTRAINT FK_EMD_RES_PREF_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.EMD_TRANCHE ADD CONSTRAINT FK_EMD_TRANCHE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT ADD CONSTRAINT FK_STORIES_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_NETWORK ADD CONSTRAINT FK_NETWORK_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.LOGINNAME ADD CONSTRAINT FK_LN_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.PERSON ADD CONSTRAINT FK_PERSON_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE ADD CONSTRAINT FK_ENTRIES_ARCHIVE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS ADD CONSTRAINT FK_AS_CNT_INDEX_STATS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.PREREQ ADD CONSTRAINT FK_PREREQ_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE ADD CONSTRAINT FK_DEL_STORIES_QUEUE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_MENTIONS ADD CONSTRAINT FK_BOARD_MENTIONS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE ADD CONSTRAINT FK_SOURCE_TYPE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT ADD CONSTRAINT FK_STATUS_COMMENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.HP_TAB_INST ADD CONSTRAINT FK_TAB_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;


ALTER TABLE HOMEPAGE.NR_RESOURCE ADD CONSTRAINT FK_RESOURCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS ADD CONSTRAINT FK_EMD_EMAIL_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.HP_WIDGET_INST ADD CONSTRAINT FK_WIDGET_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.MT_METRIC_STAT ADD CONSTRAINT FK_METRIC_STAT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.HP_UI ADD CONSTRAINT FK_UI_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS ADD CONSTRAINT FK_BOARD_CURRENT_STATUS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK ADD CONSTRAINT FK_NEWS_STATUS_NETWORK_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_COMMENTS  ADD CONSTRAINT FK_BOARD_COMMENTS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES ADD CONSTRAINT FK_ENTRIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_SOURCE ADD CONSTRAINT FK_SOURCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_ENTRIES ADD CONSTRAINT FK_BOARD_ENTRIES_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

-- 117915: AC deployment manager installation failed in minidev (D6) env
--ALTER TABLE HOMEPAGE.NR_STORIES ADD CONSTRAINT FK_STORIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
--COMMIT;

ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS ADD CONSTRAINT FK_COMM_SETTINGS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO ADD CONSTRAINT FK_EMD_TRANCHE_INFO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT ADD CONSTRAINT FK_STATUS_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.HP_TAB ADD CONSTRAINT FK_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD CONSTRAINT FK_NOT_SENT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT FK_TAGS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT FK_BLOGS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT FK_RESP_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD CONSTRAINT FK_NOT_REC_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT FK_SU_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT FK_FILES_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW ADD CONSTRAINT FK_DISCOVERY_VIEW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS ADD CONSTRAINT FK_TOPICS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT FK_BOOK_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS ADD CONSTRAINT FK_MENT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT FK_PROF_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT FK_EXT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT FK_ACTIVITIES_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT FK_WIKIS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT FK_ACT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_SAVED_READERS ADD CONSTRAINT FK_SAVED_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT FK_COMM_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT FK_FORUMS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW ADD CONSTRAINT FK_PRF_VIEW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

-- ************************************************************************* --
-- ************************************************************************* --
-- ************************************************************************* --
-- ************************************************************************* --


------------------------------------------------
-- INCLUDE FIXUP 451 FOR HP
------------------------------------------------

{include.hp-fixup451.sql}

------------------------------------------------
-- INCLUDE FIXUP 451 FOR NEWS
------------------------------------------------

{include.news-fixup451.sql}


-- 92644: On SC release MT_ORGANIZATION is expected to be empty. For this reason we need to set to NULL all the FK. 
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------
-- Before to set NULL orgId we need to make sure that there are no records with the same EXID
-- In that case we invalidate them
-----------------------------------------------------------------------------------------------------------------------

CREATE VIEW HOMEPAGE.DUPS AS (
	SELECT P1.PERSON_ID, P1.EXID, P1.DISPLAYNAME, P1.USER_MAIL, P1.USER_MAIL_LOWER, P1.ORGANIZATION_ID
	FROM HOMEPAGE.PERSON P1,
		(
		SELECT EXID
		FROM HOMEPAGE.PERSON
		GROUP BY EXID
		HAVING COUNT(*) > 1
		)	P2
	WHERE P1.EXID = P2.EXID
);
COMMIT;

-- Invalidate
UPDATE HOMEPAGE.PERSON T1 
SET (T1.PERSON_ID, T1.EXID, T1.USER_MAIL, T1.USER_MAIL_LOWER) = 
	(
	SELECT 	T2.PERSON_ID, 'INVALID_' || SUBSTR(T2.PERSON_ID,1, 6) || SUBSTR(T2.EXID,7,20), 'INVALID_' || T2.USER_MAIL, 'INVALID_' || T2.USER_MAIL_LOWER 
	FROM 	HOMEPAGE.DUPS AS T2
	WHERE 	T1.PERSON_ID = T2.PERSON_ID AND T1.ORGANIZATION_ID IS NULL
	) 
WHERE EXISTS (
	SELECT 1 
	FROM HOMEPAGE.DUPS AS T2
	WHERE T1.PERSON_ID = T2.PERSON_ID AND T1.ORGANIZATION_ID IS NULL
);
COMMIT;

DROP VIEW HOMEPAGE.DUPS;
COMMIT;

UPDATE HOMEPAGE.PERSON SET ORGANIZATION_ID = NULL;
COMMIT;

-----------------------------------------------------------------------------------------------------------------------
-- During migration we truncate those tables. So it is a redundant part.
-----------------------------------------------------------------------------------------------------------------------

UPDATE HOMEPAGE.NR_ENTRIES SET ORGANIZATION_ID = NULL;
COMMIT;

UPDATE HOMEPAGE.NR_STORIES SET ORGANIZATION_ID = NULL;
COMMIT;

UPDATE HOMEPAGE.NR_AGGREGATED_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_RESPONSES_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_PROFILES_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_COMMUNITIES_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_ACTIVITIES_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_BLOGS_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_BOOKMARKS_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_FILES_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_FORUMS_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_WIKIS_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_TAGS_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_STATUS_UPDATE_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_EXTERNAL_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_DISCOVERY_VIEW SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_PROFILES_VIEW SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_ACTIONABLE_READERS SET ORGANIZATION_ID = NULL;
COMMIT;

UPDATE HOMEPAGE.NR_NOTIFICATION_SENT_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_TOPICS_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_MENTIONS_READERS SET ORGANIZATION_ID = NULL;
COMMIT;


UPDATE HOMEPAGE.BOARD_CURRENT_STATUS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.BOARD_OBJECT_REFERENCE SET ORGANIZATION_ID = NULL;   
COMMIT;
UPDATE HOMEPAGE.BOARD_RECOMMENDATIONS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.BOARD_COMMENTS SET ORGANIZATION_ID = NULL;   
COMMIT;
UPDATE HOMEPAGE.BOARD_ENTRIES SET ORGANIZATION_ID = NULL;
COMMIT;

UPDATE HOMEPAGE.NR_NEWS_COMMENT_CONTENT SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_NEWS_STATUS_CONTENT SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_NEWS_STATUS_COMMENT SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_NEWS_STATUS_NETWORK SET ORGANIZATION_ID = NULL;
COMMIT;

-------

-- 92644: On SC release MT_ORGANIZATION is expected to be empty. For this reason we need to set to NULL all the FK. 
UPDATE HOMEPAGE.HP_TAB SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.WIDGET SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.HP_WIDGET_TAB SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.PREREQ SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_SOURCE_TYPE SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.EMD_TRANCHE SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.EMD_TRANCHE_INFO SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_AS_SEEDLIST SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_COMM_PERSON_FOLLOW SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.BOARD SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_FOLLOWS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_COMM_FOLLOW SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.EMD_RESOURCE_PREF SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_STORIES_CONTENT SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES_ARCHIVE SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.DELETED_STORIES_QUEUE SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.HP_TAB_INST SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_RESOURCE SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.EMD_EMAIL_PREFS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.HP_UI SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.HP_WIDGET_INST SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.METRIC_STAT SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.BOARD_MENTIONS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_NEWS_STATUS_NETWORK SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_COMM_SETTINGS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_NEWS_STATUS_CONTENT SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_AGGREGATED_READERS SET ORGANIZATION_ID = NULL;
COMMIT;
UPDATE HOMEPAGE.NR_SOURCE SET ORGANIZATION_ID = NULL;
COMMIT;

TRUNCATE HOMEPAGE.LOGINNAME IMMEDIATE;
COMMIT;


DELETE FROM HOMEPAGE.MT_ORGANIZATION;



UPDATE  HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER = 451 , RELEASEVER = '5.0.0.0 SC Aug'
WHERE   DBSCHEMAVER = 209;

--------------------------------------
-- COMMIT
--------------------------------------

COMMIT;
--------------------------------------
-- FLUSH
--------------------------------------
FLUSH PACKAGE CACHE DYNAMIC;

--------------------------------------
-- TERMINATE
--------------------------------------
connect reset;
terminate;