-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- SEARCH
{SQL_GRANT_START} HOMEPAGE.SR_TASKDEF {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_OPTIMIZETASKDEF {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_INDEXINGTASKDEF {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_FILESCONTENT {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_ALLTASKSDEF {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_MIGTASKDEFINFO {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_FILECONTENTTASKDEF {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_INDEX_DOCS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_RESUME_TOKENS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_BACKUPTASKDEF {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_INDEX_MANAGEMENT {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_SANDTASKDEF {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_FEEDBACK {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_FEEDBACK_CONTEXT {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_FEEDBACK_PARAMETERS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_STATS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_STRING_STATS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_NUMBER_STATS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_TIMER_STATS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_GLOBAL_SAND_PROPS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_ECM_DOCUMENT_TYPE_LABELS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_ECM_DOCUMENT_TYPE_PROPS {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.SR_POST_FILTERING_SERVICE {SQL_GRANT_STOP}
GO

{SQL_GRANT_START} HOMEPAGE.LOTUSCONNECTIONSLMGR {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.LOTUSCONNECTIONSLMPR {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.LOTUSCONNECTIONSTASK {SQL_GRANT_STOP}
GO
{SQL_GRANT_START} HOMEPAGE.LOTUSCONNECTIONSTREG {SQL_GRANT_STOP}
GO


