-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              

SET CURRENT SCHEMA HOMEPAGE;

-- +++++++++++++++++++++++++++++++++++++++++++++
-- +++++++++++++++++++++++++++++++++++++++++++++
--					start	FIXUP 460
-- +++++++++++++++++++++++++++++++++++++++++++++
-- +++++++++++++++++++++++++++++++++++++++++++++

------------------------------------------------
-- INCLUDE FIX UP 460 FOR HOMEPAGE
------------------------------------------------

{include.hp-fixup460.sql}

------------------------------------------------
-- INCLUDE FIX UP 460 FOR NEWS
------------------------------------------------

{include.news-fixup460.sql}



-- DROPPING FK
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST DROP CONSTRAINT FK_AS_SEEDLIST_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.METRIC_STAT DROP CONSTRAINT FK_METRIC_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_OBJ_REFERENCE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.MT_CFG_FILES DROP CONSTRAINT FK_CFG_FILE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP CONSTRAINT FK_NEWS_COMMENT_CONTENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP CONSTRAINT FK_WIDGET_TAB_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NETWORK DROP CONSTRAINT FK_NETWORK_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS DROP CONSTRAINT FK_MENT_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT FK_EXT_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS DROP CONSTRAINT FK_WIKIS_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS DROP CONSTRAINT FK_AS_CNT_INDEX_STATS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.PREREQ DROP CONSTRAINT FK_PREREQ_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT FK_ACT_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW DROP CONSTRAINT FK_PRF_VIEW_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE DROP CONSTRAINT FK_DEL_STORIES_QUEUE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_MENTIONS DROP CONSTRAINT FK_BOARD_MENTIONS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP CONSTRAINT FK_TAB_INST_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS DROP CONSTRAINT FK_RESP_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT FK_RESOURCE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP CONSTRAINT FK_WIDGET_INST_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_UI DROP CONSTRAINT FK_UI_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT FK_SU_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS DROP CONSTRAINT FK_TOPICS_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP CONSTRAINT FK_BOARD_CURRENT_STATUS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK DROP CONSTRAINT FK_NEWS_STATUS_NETWORK_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_USER_PREFS DROP CONSTRAINT FK_USER_PREFS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_COUNTS DROP CONSTRAINT FK_AS_COUNT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS DROP CONSTRAINT FK_PROF_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES DROP CONSTRAINT FK_STORIES_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS DROP CONSTRAINT FK_COMM_SETTINGS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB DROP CONSTRAINT FK_TAB_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS DROP CONSTRAINT FK_BRD_RECOMM_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW DROP CONSTRAINT FK_COMM_PERSON_FOLLOW_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.WIDGET DROP CONSTRAINT FK_WIDGET_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.IMG_CACHE DROP CONSTRAINT FK_IMG_CACHE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT DROP CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BOARD_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP CONSTRAINT FK_FOLLOWS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW DROP CONSTRAINT FK_COMM_FOLLOW_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS DROP CONSTRAINT FK_NOT_REC_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NT_REPLYTO DROP CONSTRAINT FK_REPLYTO_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_COMMENTS DROP CONSTRAINT FK_BOARD_COMMENTS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_FILES_READERS DROP CONSTRAINT FK_FILES_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW DROP CONSTRAINT FK_DISCOVERY_VIEW_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP CONSTRAINT FK_EMD_RES_PREF_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT DROP CONSTRAINT FK_STORIES_CONTENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.EMD_TRANCHE DROP CONSTRAINT FK_EMD_TRANCHE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS DROP CONSTRAINT FK_BOOK_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.LOGINNAME DROP CONSTRAINT FK_LN_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.PERSON DROP CONSTRAINT FK_PERSON_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS DROP CONSTRAINT FK_CFG_SET_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE DROP CONSTRAINT FK_ENTRIES_ARCHIVE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_SAVED_READERS DROP CONSTRAINT FK_SAVED_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS DROP CONSTRAINT FK_COMM_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS DROP CONSTRAINT FK_NOT_SENT_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT DROP CONSTRAINT FK_STATUS_COMMENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE DROP CONSTRAINT FK_SOURCE_TYPE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_TAGS_READERS DROP CONSTRAINT FK_TAGS_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS DROP CONSTRAINT FK_BLOGS_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS DROP CONSTRAINT FK_EMD_EMAIL_PREFS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES DROP CONSTRAINT FK_ENTRIES_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_SOURCE DROP CONSTRAINT FK_SOURCE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT FK_BOARD_ENTRIES_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS DROP CONSTRAINT FK_ACTIVITIES_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO DROP CONSTRAINT FK_EMD_TRANCHE_INFO_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT DROP CONSTRAINT FK_STATUS_CONTENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS DROP CONSTRAINT FK_FORUMS_READERS_ORG_ID;
COMMIT;

-- DROPPING INDEXES
DROP INDEX HOMEPAGE.UNQ_ORG_EXID;
COMMIT;
DROP INDEX HOMEPAGE.PERSON_EXID;
COMMIT;
DROP INDEX HOMEPAGE.LOGINNAME_UNIQUE;
COMMIT;
DROP INDEX HOMEPAGE.UNQ_ORG_NAME;
COMMIT;
DROP INDEX HOMEPAGE.NR_SRC_TYPE_ORG_UIDX;
COMMIT;
DROP INDEX HOMEPAGE.SEQ_NUMBER_UNIQUE;
COMMIT;
DROP INDEX HOMEPAGE.AGGREGATED_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.RESPONSES_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.PROFILES_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.COMM_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.BLOGS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.BOOKMARKS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.FILES_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.FORUMS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.WIKIS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.TAGS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.STATUS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.EXTERNAL_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.DISCOVERY_VIEW_ORG_IDX;
COMMIT;
DROP INDEX HOMEPAGE.PROFILES_VIEW_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.PROFILES_VIEW_ORG_IDX;
COMMIT;
DROP INDEX HOMEPAGE.NOTIFICA_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.NOT_REC_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.SAVED_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.TOPICS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.MENTIONS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.IMG_CACHE_URL_IDX;
COMMIT;
DROP INDEX HOMEPAGE.NR_AS_COUNT_ORG_IDX;
COMMIT;

-- UPDATE NOT NULL ORGANIZATION_ID

 --REORG TABLE HOMEPAGE.MT_ORGANIZATION ALLOW NO ACCESS;
 --COMMIT;

 /*
	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        ORGANIZATION_ID, ORGANIZATION_ID
	        ) 
 
	SELECT ORGANIZATION_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.MT_ORGANIZATION WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        ORGANIZATION_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.MT_ORGANIZATION 
	        ( 
	        ORGANIZATION_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.PERSON ALLOW NO ACCESS;
 --COMMIT;

 CREATE INDEX HOMEPAGE.PERSON_TMP_ORG_IDX  ON HOMEPAGE.PERSON (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.PERSON FOR SAMPLED DETAILED INDEX HOMEPAGE.PERSON_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        PERSON_ID, ORGANIZATION_ID
	        ) 
 
	SELECT PERSON_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.PERSON_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        PERSON_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.PERSON 
	        ( 
	        PERSON_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.HP_USER_PREFS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.HP_USER_PREFS_TMP_ORG_IDX  ON HOMEPAGE.HP_USER_PREFS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.HP_USER_PREFS FOR SAMPLED DETAILED INDEX HOMEPAGE.HP_USER_PREFS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        USER_PREFS_ID, ORGANIZATION_ID
	        ) 
 
	SELECT USER_PREFS_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.HP_USER_PREFS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.HP_USER_PREFS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        USER_PREFS_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.HP_USER_PREFS 
	        ( 
	        USER_PREFS_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.LOGINNAME ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.LOGINNAME_TMP_ORG_IDX  ON HOMEPAGE.LOGINNAME (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.LOGINNAME FOR SAMPLED DETAILED INDEX HOMEPAGE.LOGINNAME_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        PERSON_ID, ORGANIZATION_ID
	        ) 
 
	SELECT PERSON_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.LOGINNAME WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.LOGINNAME_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        PERSON_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.LOGINNAME 
	        ( 
	        PERSON_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.HP_UI ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.HP_UI_TMP_ORG_IDX  ON HOMEPAGE.HP_UI (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.HP_UI FOR SAMPLED DETAILED INDEX HOMEPAGE.HP_UI_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        UI_ID, ORGANIZATION_ID
	        ) 
 
	SELECT UI_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.HP_UI WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.HP_UI_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        UI_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.HP_UI 
	        ( 
	        UI_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.HP_TAB ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.HP_TAB_TMP_ORG_IDX  ON HOMEPAGE.HP_TAB (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.HP_TAB FOR SAMPLED DETAILED INDEX HOMEPAGE.HP_TAB_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        TAB_ID, ORGANIZATION_ID
	        ) 
 
	SELECT TAB_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.HP_TAB WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.HP_TAB_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        TAB_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.HP_TAB 
	        ( 
	        TAB_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.HP_TAB_INST ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.HP_TAB_INST_TMP_ORG_IDX  ON HOMEPAGE.HP_TAB_INST (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.HP_TAB_INST FOR SAMPLED DETAILED INDEX HOMEPAGE.HP_TAB_INST_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        TAB_INST_ID, ORGANIZATION_ID
	        ) 
 
	SELECT TAB_INST_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.HP_TAB_INST WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.HP_TAB_INST_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        TAB_INST_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.HP_TAB_INST 
	        ( 
	        TAB_INST_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.WIDGET ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.WIDGET_TMP_ORG_IDX  ON HOMEPAGE.WIDGET (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.WIDGET FOR SAMPLED DETAILED INDEX HOMEPAGE.WIDGET_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        WIDGET_ID, ORGANIZATION_ID
	        ) 
 
	SELECT WIDGET_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.WIDGET WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.WIDGET_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        WIDGET_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.WIDGET 
	        ( 
	        WIDGET_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.HP_WIDGET_TAB ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.HP_WIDGET_TAB_TMP_ORG_IDX  ON HOMEPAGE.HP_WIDGET_TAB (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.HP_WIDGET_TAB FOR SAMPLED DETAILED INDEX HOMEPAGE.HP_WIDGET_TAB_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        WIDGET_TAB_ID, ORGANIZATION_ID
	        ) 
 
	SELECT WIDGET_TAB_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.HP_WIDGET_TAB WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.HP_WIDGET_TAB_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        WIDGET_TAB_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.HP_WIDGET_TAB 
	        ( 
	        WIDGET_TAB_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.HP_WIDGET_INST ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.HP_WIDGET_INST_TMP_ORG_IDX  ON HOMEPAGE.HP_WIDGET_INST (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.HP_WIDGET_INST FOR SAMPLED DETAILED INDEX HOMEPAGE.HP_WIDGET_INST_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        WIDGET_INST_ID, ORGANIZATION_ID
	        ) 
 
	SELECT WIDGET_INST_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.HP_WIDGET_INST WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.HP_WIDGET_INST_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        WIDGET_INST_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.HP_WIDGET_INST 
	        ( 
	        WIDGET_INST_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.PREREQ ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.PREREQ_TMP_ORG_IDX  ON HOMEPAGE.PREREQ (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.PREREQ FOR SAMPLED DETAILED INDEX HOMEPAGE.PREREQ_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        PREREQ_ID, ORGANIZATION_ID
	        ) 
 
	SELECT PREREQ_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.PREREQ WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.PREREQ_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        PREREQ_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.PREREQ 
	        ( 
	        PREREQ_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NT_REPLYTO ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NT_REPLYTO_TMP_ORG_IDX  ON HOMEPAGE.NT_REPLYTO (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NT_REPLYTO FOR SAMPLED DETAILED INDEX HOMEPAGE.NT_REPLYTO_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        REPLYTO_NOTIFICATION_ID, ORGANIZATION_ID
	        ) 
 
	SELECT REPLYTO_NOTIFICATION_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NT_REPLYTO WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NT_REPLYTO_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        REPLYTO_NOTIFICATION_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NT_REPLYTO 
	        ( 
	        REPLYTO_NOTIFICATION_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NT_REPLYTO_RECIPIENT_TMP_ORG_IDX  ON HOMEPAGE.NT_REPLYTO_RECIPIENT (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT FOR SAMPLED DETAILED INDEX HOMEPAGE.NT_REPLYTO_RECIPIENT_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        REPLYTO_RECIPIENT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT REPLYTO_RECIPIENT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NT_REPLYTO_RECIPIENT WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NT_REPLYTO_RECIPIENT_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        REPLYTO_RECIPIENT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NT_REPLYTO_RECIPIENT 
	        ( 
	        REPLYTO_RECIPIENT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.METRIC_STAT ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.METRIC_STAT_TMP_ORG_IDX  ON HOMEPAGE.METRIC_STAT (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.METRIC_STAT FOR SAMPLED DETAILED INDEX HOMEPAGE.METRIC_STAT_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        METRIC_STAT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT METRIC_STAT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.METRIC_STAT WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.METRIC_STAT_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        METRIC_STAT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.METRIC_STAT 
	        ( 
	        METRIC_STAT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.MT_CFG_SETTINGS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.MT_CFG_SETTINGS_TMP_ORG_IDX  ON HOMEPAGE.MT_CFG_SETTINGS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.MT_CFG_SETTINGS FOR SAMPLED DETAILED INDEX HOMEPAGE.MT_CFG_SETTINGS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SETTING_ID, ORGANIZATION_ID
	        ) 
 
	SELECT SETTING_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.MT_CFG_SETTINGS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.MT_CFG_SETTINGS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SETTING_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.MT_CFG_SETTINGS 
	        ( 
	        SETTING_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.MT_CFG_FILES ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.MT_CFG_FILES_TMP_ORG_IDX  ON HOMEPAGE.MT_CFG_FILES (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.MT_CFG_FILES FOR SAMPLED DETAILED INDEX HOMEPAGE.MT_CFG_FILES_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        FILE_ID, ORGANIZATION_ID
	        ) 
 
	SELECT FILE_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.MT_CFG_FILES WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.MT_CFG_FILES_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        FILE_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.MT_CFG_FILES 
	        ( 
	        FILE_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_SOURCE_TYPE_DEFAULT ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_SOURCE_TYPE_DEFAULT_TMP_ORG_IDX  ON HOMEPAGE.NR_SOURCE_TYPE_DEFAULT (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_SOURCE_TYPE_DEFAULT FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_SOURCE_TYPE_DEFAULT_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SOURCE_TYPE_ID, ORGANIZATION_ID
	        ) 
 
	SELECT SOURCE_TYPE_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_SOURCE_TYPE_DEFAULT WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_SOURCE_TYPE_DEFAULT_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SOURCE_TYPE_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_SOURCE_TYPE_DEFAULT 
	        ( 
	        SOURCE_TYPE_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_SOURCE_TYPE ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_SOURCE_TYPE_TMP_ORG_IDX  ON HOMEPAGE.NR_SOURCE_TYPE (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_SOURCE_TYPE FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_SOURCE_TYPE_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SOURCE_TYPE_ID, ORGANIZATION_ID
	        ) 
 
	SELECT SOURCE_TYPE_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_SOURCE_TYPE WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_SOURCE_TYPE_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SOURCE_TYPE_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_SOURCE_TYPE 
	        ( 
	        SOURCE_TYPE_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_SOURCE ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_SOURCE_TMP_ORG_IDX  ON HOMEPAGE.NR_SOURCE (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_SOURCE FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_SOURCE_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SOURCE_ID, ORGANIZATION_ID
	        ) 
 
	SELECT SOURCE_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_SOURCE WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_SOURCE_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SOURCE_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_SOURCE 
	        ( 
	        SOURCE_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_NEWS_STATUS_NETWORK_TMP_ORG_IDX  ON HOMEPAGE.NR_NEWS_STATUS_NETWORK (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_NEWS_STATUS_NETWORK_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NEWS_STATUS_NETWORK_ID, ORGANIZATION_ID
	        ) 
 
	SELECT NEWS_STATUS_NETWORK_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_NEWS_STATUS_NETWORK WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_NEWS_STATUS_NETWORK_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NEWS_STATUS_NETWORK_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_NEWS_STATUS_NETWORK 
	        ( 
	        NEWS_STATUS_NETWORK_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_NEWS_STATUS_COMMENT_TMP_ORG_IDX  ON HOMEPAGE.NR_NEWS_STATUS_COMMENT (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_NEWS_STATUS_COMMENT_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NEWS_STATUS_COMMENT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT NEWS_STATUS_COMMENT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_NEWS_STATUS_COMMENT WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_NEWS_STATUS_COMMENT_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NEWS_STATUS_COMMENT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_NEWS_STATUS_COMMENT 
	        ( 
	        NEWS_STATUS_COMMENT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_NEWS_STATUS_CONTENT_TMP_ORG_IDX  ON HOMEPAGE.NR_NEWS_STATUS_CONTENT (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_NEWS_STATUS_CONTENT_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NEWS_STATUS_CONTENT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT NEWS_STATUS_CONTENT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_NEWS_STATUS_CONTENT WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_NEWS_STATUS_CONTENT_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NEWS_STATUS_CONTENT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_NEWS_STATUS_CONTENT 
	        ( 
	        NEWS_STATUS_CONTENT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_NEWS_COMMENT_CONTENT_TMP_ORG_IDX  ON HOMEPAGE.NR_NEWS_COMMENT_CONTENT (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_NEWS_COMMENT_CONTENT_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NEWS_COMMENT_CONTENT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT NEWS_COMMENT_CONTENT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_NEWS_COMMENT_CONTENT WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_NEWS_COMMENT_CONTENT_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NEWS_COMMENT_CONTENT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_NEWS_COMMENT_CONTENT 
	        ( 
	        NEWS_COMMENT_CONTENT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_RESOURCE ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_RESOURCE_TMP_ORG_IDX  ON HOMEPAGE.NR_RESOURCE (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_RESOURCE FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_RESOURCE_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        RESOURCE_ID, ORGANIZATION_ID
	        ) 
 
	SELECT RESOURCE_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_RESOURCE WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_RESOURCE_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        RESOURCE_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_RESOURCE 
	        ( 
	        RESOURCE_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_FOLLOWS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_FOLLOWS_TMP_ORG_IDX  ON HOMEPAGE.NR_FOLLOWS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_FOLLOWS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_FOLLOWS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        FOLLOW_ID, ORGANIZATION_ID
	        ) 
 
	SELECT FOLLOW_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_FOLLOWS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_FOLLOWS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        FOLLOW_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_FOLLOWS 
	        ( 
	        FOLLOW_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_COMM_FOLLOW ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_COMM_FOLLOW_TMP_ORG_IDX  ON HOMEPAGE.NR_COMM_FOLLOW (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_COMM_FOLLOW FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_COMM_FOLLOW_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        COMM_FOLLOW_ID, ORGANIZATION_ID
	        ) 
 
	SELECT COMM_FOLLOW_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_COMM_FOLLOW WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_COMM_FOLLOW_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        COMM_FOLLOW_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_COMM_FOLLOW 
	        ( 
	        COMM_FOLLOW_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_STORIES_CONTENT ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_STORIES_CONTENT_TMP_ORG_IDX  ON HOMEPAGE.NR_STORIES_CONTENT (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_STORIES_CONTENT FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_STORIES_CONTENT_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        STORY_CONTENT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT STORY_CONTENT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_STORIES_CONTENT WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_STORIES_CONTENT_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        STORY_CONTENT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_STORIES_CONTENT 
	        ( 
	        STORY_CONTENT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_NETWORK ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_NETWORK_TMP_ORG_IDX  ON HOMEPAGE.NR_NETWORK (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_NETWORK FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_NETWORK_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NETWORK_ID, ORGANIZATION_ID
	        ) 
 
	SELECT NETWORK_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_NETWORK WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_NETWORK_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        NETWORK_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_NETWORK 
	        ( 
	        NETWORK_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.EMD_RESOURCE_PREF ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.EMD_RESOURCE_PREF_TMP_ORG_IDX  ON HOMEPAGE.EMD_RESOURCE_PREF (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.EMD_RESOURCE_PREF FOR SAMPLED DETAILED INDEX HOMEPAGE.EMD_RESOURCE_PREF_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        RESOURCE_PREF_ID, ORGANIZATION_ID
	        ) 
 
	SELECT RESOURCE_PREF_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.EMD_RESOURCE_PREF_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        RESOURCE_PREF_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.EMD_RESOURCE_PREF 
	        ( 
	        RESOURCE_PREF_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.EMD_TRANCHE ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.EMD_TRANCHE_TMP_ORG_IDX  ON HOMEPAGE.EMD_TRANCHE (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.EMD_TRANCHE FOR SAMPLED DETAILED INDEX HOMEPAGE.EMD_TRANCHE_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        TRANCHE_ID, ORGANIZATION_ID
	        ) 
 
	SELECT TRANCHE_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.EMD_TRANCHE WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.EMD_TRANCHE_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        TRANCHE_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.EMD_TRANCHE 
	        ( 
	        TRANCHE_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.EMD_TRANCHE_INFO ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.EMD_TRANCHE_INFO_TMP_ORG_IDX  ON HOMEPAGE.EMD_TRANCHE_INFO (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.EMD_TRANCHE_INFO FOR SAMPLED DETAILED INDEX HOMEPAGE.EMD_TRANCHE_INFO_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        TRANCHE_INFO_ID, ORGANIZATION_ID
	        ) 
 
	SELECT TRANCHE_INFO_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.EMD_TRANCHE_INFO WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.EMD_TRANCHE_INFO_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        TRANCHE_INFO_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.EMD_TRANCHE_INFO 
	        ( 
	        TRANCHE_INFO_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.EMD_EMAIL_PREFS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.EMD_EMAIL_PREFS_TMP_ORG_IDX  ON HOMEPAGE.EMD_EMAIL_PREFS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.EMD_EMAIL_PREFS FOR SAMPLED DETAILED INDEX HOMEPAGE.EMD_EMAIL_PREFS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        EMAIL_PREFS_ID, ORGANIZATION_ID
	        ) 
 
	SELECT EMAIL_PREFS_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.EMD_EMAIL_PREFS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.EMD_EMAIL_PREFS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        EMAIL_PREFS_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.EMD_EMAIL_PREFS 
	        ( 
	        EMAIL_PREFS_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_COMM_PERSON_FOLLOW_TMP_ORG_IDX  ON HOMEPAGE.NR_COMM_PERSON_FOLLOW (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_COMM_PERSON_FOLLOW_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        COMM_PERSON_FOLLOW_ID, ORGANIZATION_ID
	        ) 
 
	SELECT COMM_PERSON_FOLLOW_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_COMM_PERSON_FOLLOW WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_COMM_PERSON_FOLLOW_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        COMM_PERSON_FOLLOW_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_COMM_PERSON_FOLLOW 
	        ( 
	        COMM_PERSON_FOLLOW_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_ENTRIES ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_ENTRIES_TMP_ORG_IDX  ON HOMEPAGE.NR_ENTRIES (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_ENTRIES FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_ENTRIES_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID
	        ) 
 
	SELECT ENTRY_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_ENTRIES WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_ENTRIES_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_ENTRIES 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_STORIES ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_STORIES_TMP_ORG_IDX  ON HOMEPAGE.NR_STORIES (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_STORIES FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_STORIES_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        STORY_ID, ORGANIZATION_ID
	        ) 
 
	SELECT STORY_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_STORIES WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_STORIES_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        STORY_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_STORIES 
	        ( 
	        STORY_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_ENTRIES_ARCHIVE_TMP_ORG_IDX  ON HOMEPAGE.NR_ENTRIES_ARCHIVE (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_ENTRIES_ARCHIVE_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID
	        ) 
 
	SELECT ENTRY_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_ENTRIES_ARCHIVE WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_ENTRIES_ARCHIVE_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_ENTRIES_ARCHIVE 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_AGGREGATED_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_AGGREGATED_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_AGGREGATED_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_AGGREGATED_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_AGGREGATED_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_AGGREGATED_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_AGGREGATED_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_AGGREGATED_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_RESPONSES_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_RESPONSES_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_RESPONSES_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_RESPONSES_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_RESPONSES_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_RESPONSES_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_RESPONSES_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_RESPONSES_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_PROFILES_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_PROFILES_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_PROFILES_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_PROFILES_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_PROFILES_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_PROFILES_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_PROFILES_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_PROFILES_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_COMMUNITIES_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_COMMUNITIES_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_COMMUNITIES_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_COMMUNITIES_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_COMMUNITIES_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_COMMUNITIES_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_COMMUNITIES_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_COMMUNITIES_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_WIKIS_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_WIKIS_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_WIKIS_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_WIKIS_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_WIKIS_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_WIKIS_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_WIKIS_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_WIKIS_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.IMG_CACHE ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.IMG_CACHE_TMP_ORG_IDX  ON HOMEPAGE.IMG_CACHE (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.IMG_CACHE FOR SAMPLED DETAILED INDEX HOMEPAGE.IMG_CACHE_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        IMG_CACHE_ID, ORGANIZATION_ID
	        ) 
 
	SELECT IMG_CACHE_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.IMG_CACHE WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.IMG_CACHE_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        IMG_CACHE_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.IMG_CACHE 
	        ( 
	        IMG_CACHE_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_ACTIVITIES_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_ACTIVITIES_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_ACTIVITIES_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_ACTIVITIES_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_ACTIVITIES_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_ACTIVITIES_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_ACTIVITIES_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_ACTIVITIES_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_BLOGS_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_BLOGS_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_BLOGS_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_BLOGS_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_BLOGS_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_BLOGS_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_BLOGS_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_BLOGS_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_BOOKMARKS_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_BOOKMARKS_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_BOOKMARKS_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_BOOKMARKS_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_BOOKMARKS_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_BOOKMARKS_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_BOOKMARKS_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_BOOKMARKS_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_FILES_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_FILES_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_FILES_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_FILES_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_FILES_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_FILES_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_FILES_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_FILES_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_FORUMS_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_FORUMS_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_FORUMS_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_FORUMS_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_FORUMS_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_FORUMS_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_FORUMS_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_FORUMS_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_TAGS_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_TAGS_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_TAGS_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_TAGS_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_TAGS_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_TAGS_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_TAGS_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_TAGS_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_STATUS_UPDATE_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_STATUS_UPDATE_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_STATUS_UPDATE_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_STATUS_UPDATE_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_STATUS_UPDATE_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_EXTERNAL_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_EXTERNAL_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_EXTERNAL_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_EXTERNAL_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_EXTERNAL_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_EXTERNAL_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_EXTERNAL_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_EXTERNAL_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_ACTIONABLE_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_ACTIONABLE_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_ACTIONABLE_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_ACTIONABLE_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_ACTIONABLE_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_ACTIONABLE_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_ACTIONABLE_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_ACTIONABLE_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.BOARD ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.BOARD_TMP_ORG_IDX  ON HOMEPAGE.BOARD (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.BOARD FOR SAMPLED DETAILED INDEX HOMEPAGE.BOARD_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        BOARD_ID, ORGANIZATION_ID
	        ) 
 
	SELECT BOARD_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.BOARD WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.BOARD_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        BOARD_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.BOARD 
	        ( 
	        BOARD_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_AS_COUNTS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_AS_COUNTS_TMP_ORG_IDX  ON HOMEPAGE.NR_AS_COUNTS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_AS_COUNTS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_AS_COUNTS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        AS_COUNT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT AS_COUNT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_AS_COUNTS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_AS_COUNTS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        AS_COUNT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_AS_COUNTS 
	        ( 
	        AS_COUNT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.BOARD_ENTRIES ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.BOARD_ENTRIES_TMP_ORG_IDX  ON HOMEPAGE.BOARD_ENTRIES (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.BOARD_ENTRIES FOR SAMPLED DETAILED INDEX HOMEPAGE.BOARD_ENTRIES_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID
	        ) 
 
	SELECT ENTRY_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.BOARD_ENTRIES WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.BOARD_ENTRIES_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.BOARD_ENTRIES 
	        ( 
	        ENTRY_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.BOARD_COMMENTS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.BOARD_COMMENTS_TMP_ORG_IDX  ON HOMEPAGE.BOARD_COMMENTS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.BOARD_COMMENTS FOR SAMPLED DETAILED INDEX HOMEPAGE.BOARD_COMMENTS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        COMMENT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT COMMENT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.BOARD_COMMENTS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.BOARD_COMMENTS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        COMMENT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.BOARD_COMMENTS 
	        ( 
	        COMMENT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.BOARD_OBJECT_REFERENCE_TMP_ORG_IDX  ON HOMEPAGE.BOARD_OBJECT_REFERENCE (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE FOR SAMPLED DETAILED INDEX HOMEPAGE.BOARD_OBJECT_REFERENCE_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        OBJECT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT OBJECT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.BOARD_OBJECT_REFERENCE WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.BOARD_OBJECT_REFERENCE_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        OBJECT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.BOARD_OBJECT_REFERENCE 
	        ( 
	        OBJECT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.BOARD_RECOMMENDATIONS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.BOARD_RECOMMENDATIONS_TMP_ORG_IDX  ON HOMEPAGE.BOARD_RECOMMENDATIONS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.BOARD_RECOMMENDATIONS FOR SAMPLED DETAILED INDEX HOMEPAGE.BOARD_RECOMMENDATIONS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        RECOMMENDATION_ID, ORGANIZATION_ID
	        ) 
 
	SELECT RECOMMENDATION_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.BOARD_RECOMMENDATIONS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.BOARD_RECOMMENDATIONS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        RECOMMENDATION_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.BOARD_RECOMMENDATIONS 
	        ( 
	        RECOMMENDATION_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.BOARD_CURRENT_STATUS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.BOARD_CURRENT_STATUS_TMP_ORG_IDX  ON HOMEPAGE.BOARD_CURRENT_STATUS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.BOARD_CURRENT_STATUS FOR SAMPLED DETAILED INDEX HOMEPAGE.BOARD_CURRENT_STATUS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CURRENT_STATUS_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CURRENT_STATUS_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.BOARD_CURRENT_STATUS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.BOARD_CURRENT_STATUS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CURRENT_STATUS_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.BOARD_CURRENT_STATUS 
	        ( 
	        CURRENT_STATUS_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.BOARD_MENTIONS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.BOARD_MENTIONS_TMP_ORG_IDX  ON HOMEPAGE.BOARD_MENTIONS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.BOARD_MENTIONS FOR SAMPLED DETAILED INDEX HOMEPAGE.BOARD_MENTIONS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        BOARD_MENTIONS_ID, ORGANIZATION_ID
	        ) 
 
	SELECT BOARD_MENTIONS_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.BOARD_MENTIONS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.BOARD_MENTIONS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        BOARD_MENTIONS_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.BOARD_MENTIONS 
	        ( 
	        BOARD_MENTIONS_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.DELETED_STORIES_QUEUE ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.DELETED_STORIES_QUEUE_TMP_ORG_IDX  ON HOMEPAGE.DELETED_STORIES_QUEUE (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.DELETED_STORIES_QUEUE FOR SAMPLED DETAILED INDEX HOMEPAGE.DELETED_STORIES_QUEUE_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        QUEUE_ID, ORGANIZATION_ID
	        ) 
 
	SELECT QUEUE_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.DELETED_STORIES_QUEUE WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.DELETED_STORIES_QUEUE_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        QUEUE_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.DELETED_STORIES_QUEUE 
	        ( 
	        QUEUE_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_COMM_SETTINGS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_COMM_SETTINGS_TMP_ORG_IDX  ON HOMEPAGE.NR_COMM_SETTINGS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_COMM_SETTINGS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_COMM_SETTINGS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        COMM_ID, ORGANIZATION_ID
	        ) 
 
	SELECT COMM_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_COMM_SETTINGS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_COMM_SETTINGS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        COMM_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_COMM_SETTINGS 
	        ( 
	        COMM_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_DISCOVERY_VIEW ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_DISCOVERY_VIEW_TMP_ORG_IDX  ON HOMEPAGE.NR_DISCOVERY_VIEW (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_DISCOVERY_VIEW FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_DISCOVERY_VIEW_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_DISCOVERY_VIEW WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_DISCOVERY_VIEW_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_DISCOVERY_VIEW 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_PROFILES_VIEW ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_PROFILES_VIEW_TMP_ORG_IDX  ON HOMEPAGE.NR_PROFILES_VIEW (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_PROFILES_VIEW FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_PROFILES_VIEW_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_PROFILES_VIEW WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_PROFILES_VIEW_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_PROFILES_VIEW 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_NOTIFICATION_SENT_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_NOTIFICATION_SENT_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_NOTIFICATION_SENT_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_NOTIFICATION_SENT_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_NOTIFICATION_SENT_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_SAVED_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_SAVED_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_SAVED_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_SAVED_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_SAVED_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_SAVED_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_SAVED_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_SAVED_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_TOPICS_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_TOPICS_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_TOPICS_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_TOPICS_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_TOPICS_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_TOPICS_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_TOPICS_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_TOPICS_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_MENTIONS_READERS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_MENTIONS_READERS_TMP_ORG_IDX  ON HOMEPAGE.NR_MENTIONS_READERS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_MENTIONS_READERS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_MENTIONS_READERS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID
	        ) 
 
	SELECT CATEGORY_READER_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_MENTIONS_READERS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_MENTIONS_READERS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_MENTIONS_READERS 
	        ( 
	        CATEGORY_READER_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_AS_SEEDLIST ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_AS_SEEDLIST_TMP_ORG_IDX  ON HOMEPAGE.NR_AS_SEEDLIST (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_AS_SEEDLIST FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_AS_SEEDLIST_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SEEDLIST_ID, ORGANIZATION_ID
	        ) 
 
	SELECT SEEDLIST_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_AS_SEEDLIST WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_AS_SEEDLIST_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        SEEDLIST_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_AS_SEEDLIST 
	        ( 
	        SEEDLIST_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
 
COMMIT;

 --REORG TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS ALLOW NO ACCESS;
 COMMIT;

 CREATE INDEX HOMEPAGE.NR_AS_CONTENT_INDEX_STATS_TMP_ORG_IDX  ON HOMEPAGE.NR_AS_CONTENT_INDEX_STATS (ORGANIZATION_ID);
 COMMIT;

 RUNSTATS ON TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS FOR SAMPLED DETAILED INDEX HOMEPAGE.NR_AS_CONTENT_INDEX_STATS_TMP_ORG_IDX;
 COMMIT;

	EXPORT TO data.tmp.ixf OF IXF METHOD N 
	        ( 
	        STAT_ID, ORGANIZATION_ID
	        ) 
 
	SELECT STAT_ID, '00000000-0000-0000-0000-000000000000' ORGANIZATION_ID FROM HOMEPAGE.NR_AS_CONTENT_INDEX_STATS WHERE ORGANIZATION_ID IS NULL WITH UR; 
	COMMIT; 
 
 DROP INDEX HOMEPAGE.NR_AS_CONTENT_INDEX_STATS_TMP_ORG_IDX;
 COMMIT;

	IMPORT FROM data.tmp.ixf OF IXF METHOD N 
	        ( 
	        STAT_ID, ORGANIZATION_ID 
	        ) 
	ALLOW NO ACCESS COMMITCOUNT 2000 
	INSERT_UPDATE INTO HOMEPAGE.NR_AS_CONTENT_INDEX_STATS 
	        ( 
	        STAT_ID, ORGANIZATION_ID 
	        ); 
	COMMIT; 
*/
COMMIT;

-- RESTORING FK
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST ADD CONSTRAINT FK_AS_SEEDLIST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.METRIC_STAT ADD CONSTRAINT FK_METRIC_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE ADD CONSTRAINT FK_BRD_OBJ_REFERENCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.MT_CFG_FILES ADD CONSTRAINT FK_CFG_FILE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT ADD CONSTRAINT FK_NEWS_COMMENT_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ADD CONSTRAINT FK_WIDGET_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NETWORK ADD CONSTRAINT FK_NETWORK_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS ADD CONSTRAINT FK_MENT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT FK_EXT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT FK_WIKIS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS ADD CONSTRAINT FK_AS_CNT_INDEX_STATS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.PREREQ ADD CONSTRAINT FK_PREREQ_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT FK_ACT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW ADD CONSTRAINT FK_PRF_VIEW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE ADD CONSTRAINT FK_DEL_STORIES_QUEUE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_MENTIONS ADD CONSTRAINT FK_BOARD_MENTIONS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB_INST ADD CONSTRAINT FK_TAB_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT FK_RESP_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESOURCE ADD CONSTRAINT FK_RESOURCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_WIDGET_INST ADD CONSTRAINT FK_WIDGET_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_UI ADD CONSTRAINT FK_UI_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT FK_SU_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS ADD CONSTRAINT FK_TOPICS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS ADD CONSTRAINT FK_BOARD_CURRENT_STATUS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK ADD CONSTRAINT FK_NEWS_STATUS_NETWORK_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_USER_PREFS ADD CONSTRAINT FK_USER_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_COUNTS ADD CONSTRAINT FK_AS_COUNT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT FK_PROF_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES ADD CONSTRAINT FK_STORIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS ADD CONSTRAINT FK_COMM_SETTINGS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB ADD CONSTRAINT FK_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS ADD CONSTRAINT FK_BRD_RECOMM_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW ADD CONSTRAINT FK_COMM_PERSON_FOLLOW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.WIDGET ADD CONSTRAINT FK_WIDGET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.IMG_CACHE ADD CONSTRAINT FK_IMG_CACHE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ADD CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD ADD CONSTRAINT FK_BOARD_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_FOLLOWS ADD CONSTRAINT FK_FOLLOWS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW ADD CONSTRAINT FK_COMM_FOLLOW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD CONSTRAINT FK_NOT_REC_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NT_REPLYTO ADD CONSTRAINT FK_REPLYTO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_COMMENTS ADD CONSTRAINT FK_BOARD_COMMENTS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT FK_FILES_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW ADD CONSTRAINT FK_DISCOVERY_VIEW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF ADD CONSTRAINT FK_EMD_RES_PREF_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT ADD CONSTRAINT FK_STORIES_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.EMD_TRANCHE ADD CONSTRAINT FK_EMD_TRANCHE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT FK_BOOK_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.LOGINNAME ADD CONSTRAINT FK_LN_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.PERSON ADD CONSTRAINT FK_PERSON_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS ADD CONSTRAINT FK_CFG_SET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE ADD CONSTRAINT FK_ENTRIES_ARCHIVE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_SAVED_READERS ADD CONSTRAINT FK_SAVED_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT FK_COMM_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD CONSTRAINT FK_NOT_SENT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT ADD CONSTRAINT FK_STATUS_COMMENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE ADD CONSTRAINT FK_SOURCE_TYPE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT FK_TAGS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT FK_BLOGS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS ADD CONSTRAINT FK_EMD_EMAIL_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES ADD CONSTRAINT FK_ENTRIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_SOURCE ADD CONSTRAINT FK_SOURCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_ENTRIES ADD CONSTRAINT FK_BOARD_ENTRIES_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT FK_ACTIVITIES_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO ADD CONSTRAINT FK_EMD_TRANCHE_INFO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT ADD CONSTRAINT FK_STATUS_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT FK_FORUMS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

-- RESTORING INDEXES
CREATE INDEX HOMEPAGE.UNQ_ORG_EXID ON HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_EXID);
COMMIT;
CREATE INDEX HOMEPAGE.PERSON_EXID ON HOMEPAGE.PERSON (EXID, ORGANIZATION_ID);
COMMIT;
CREATE INDEX HOMEPAGE.LOGINNAME_UNIQUE ON HOMEPAGE.LOGINNAME (LOGINNAME, ORGANIZATION_ID);
COMMIT;
CREATE INDEX HOMEPAGE.UNQ_ORG_NAME ON HOMEPAGE.MT_CFG_SETTINGS (NAME, ORGANIZATION_ID);
COMMIT;
CREATE INDEX HOMEPAGE.NR_SRC_TYPE_ORG_UIDX ON HOMEPAGE.NR_SOURCE_TYPE (SOURCE_TYPE, ORGANIZATION_ID);
COMMIT;
CREATE INDEX HOMEPAGE.SEQ_NUMBER_UNIQUE ON HOMEPAGE.EMD_TRANCHE (SEQ_NUMBER, ORGANIZATION_ID);
COMMIT;
CREATE INDEX HOMEPAGE.AGGREGATED_READERS_SRC_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.RESPONSES_READERS_SRC_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.PROFILES_READERS_SRC_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.COMM_READERS_SRC_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.BLOGS_READERS_SRC_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_SRC_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.FILES_READERS_SRC_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.FORUMS_READERS_SRC_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.WIKIS_READERS_SRC_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.TAGS_READERS_SRC_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.STATUS_READERS_SRC_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.EXTERNAL_READERS_SRC_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_ORG_IDX ON HOMEPAGE.NR_DISCOVERY_VIEW (ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, CREATION_DATE DESC, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.PROFILES_VIEW_SRC_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.PROFILES_VIEW_ORG_IDX ON HOMEPAGE.NR_PROFILES_VIEW (ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, CREATION_DATE DESC, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.NOTIFICA_READERS_SRC_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.NOT_REC_READERS_SRC_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.SAVED_READERS_SRC_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.TOPICS_READERS_SRC_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.MENTIONS_READERS_SRC_IX ON HOMEPAGE.NR_MENTIONS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID);
COMMIT;
CREATE INDEX HOMEPAGE.IMG_CACHE_URL_IDX ON HOMEPAGE.IMG_CACHE (ORIGINAL_URL_MD5, ORGANIZATION_ID);
COMMIT;
CREATE INDEX HOMEPAGE.NR_AS_COUNT_ORG_IDX ON HOMEPAGE.NR_AS_COUNTS (ORGANIZATION_ID);
COMMIT;

------------------------------------------------------------------------------------------------
-- UPDATE SCHEMA VERSION AND RELEASE VERSION to 460
------------------------------------------------------------------------------------------------
UPDATE  HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER = 460, RELEASEVER = '4.6.0.0' 
WHERE   DBSCHEMAVER = 459; 

------------------------------------------------------------------------------------------------

COMMIT;

-- +++++++++++++++++++++++++++++++++++++++++++++
-- +++++++++++++++++++++++++++++++++++++++++++++
--					end	FIXUP 460
-- +++++++++++++++++++++++++++++++++++++++++++++
-- +++++++++++++++++++++++++++++++++++++++++++++

