-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2008, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

connect to HOMEPAGE;

RUNSTATS ON TABLE HOMEPAGE.HOMEPAGE_SCHEMA;
RUNSTATS ON TABLE HOMEPAGE.PERSON;
RUNSTATS ON TABLE HOMEPAGE.LOGINNAME;
RUNSTATS ON TABLE HOMEPAGE.PREREQ;
RUNSTATS ON TABLE HOMEPAGE.WIDGET;

RUNSTATS ON TABLE HOMEPAGE.HP_UI;
RUNSTATS ON TABLE HOMEPAGE.HP_TAB;
RUNSTATS ON TABLE HOMEPAGE.HP_TAB_INST;
RUNSTATS ON TABLE HOMEPAGE.HP_WIDGET_INST;
RUNSTATS ON TABLE HOMEPAGE.HP_WIDGET_TAB;

RUNSTATS ON TABLE HOMEPAGE.NT_NOTIFICATION;
RUNSTATS ON TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT;

RUNSTATS ON TABLE HOMEPAGE.NR_SOURCE;
RUNSTATS ON TABLE HOMEPAGE.NR_SUBSCRIPTION;
RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_RECORDS;
RUNSTATS ON TABLE HOMEPAGE.NR_TEMPLATE;
RUNSTATS ON TABLE HOMEPAGE.NR_EVENT_RECORDS;

RUNSTATS ON TABLE HOMEPAGE.EMD_JOBS;
RUNSTATS ON TABLE HOMEPAGE.EMD_JOBS_STATS;
RUNSTATS ON TABLE HOMEPAGE.EMD_RECIPIENTS;

RUNSTATS ON TABLE HOMEPAGE.NR_SCHEDULER_LMGR;
RUNSTATS ON TABLE HOMEPAGE.NR_SCHEDULER_LMPR;
RUNSTATS ON TABLE HOMEPAGE.NR_SCHEDULER_TASK;
RUNSTATS ON TABLE HOMEPAGE.NR_SCHEDULER_TREG;

RUNSTATS ON TABLE HOMEPAGE.SR_INDEXINGTASKDEF;
RUNSTATS ON TABLE HOMEPAGE.SR_OPTIMIZETASKDEF;
RUNSTATS ON TABLE HOMEPAGE.SR_TASKDEF;

RUNSTATS ON TABLE HOMEPAGE.LOTUSCONNECTIONSLMGR;
RUNSTATS ON TABLE HOMEPAGE.LOTUSCONNECTIONSLMPR;
RUNSTATS ON TABLE HOMEPAGE.LOTUSCONNECTIONSTASK;

--------------------------------------------------------------------

RUNSTATS ON TABLE HOMEPAGE.HOMEPAGE_SCHEMA 	FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.PERSON			FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.LOGINNAME		FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.PREREQ			FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.WIDGET			FOR INDEXES ALL;

RUNSTATS ON TABLE HOMEPAGE.HP_UI			FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.HP_TAB			FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.HP_TAB_INST 		FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.HP_WIDGET_INST	FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.HP_WIDGET_TAB	FOR INDEXES ALL;

RUNSTATS ON TABLE HOMEPAGE.NT_NOTIFICATION	FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT	FOR INDEXES ALL;

RUNSTATS ON TABLE HOMEPAGE.NR_SOURCE		FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.NR_SUBSCRIPTION	FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.NR_NEWS_RECORDS	FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.NR_TEMPLATE		FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.NR_EVENT_RECORDS	FOR INDEXES ALL;

RUNSTATS ON TABLE HOMEPAGE.EMD_JOBS			FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.EMD_JOBS_STATS	FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.EMD_RECIPIENTS	FOR INDEXES ALL;

RUNSTATS ON TABLE HOMEPAGE.NR_SCHEDULER_LMGR FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.NR_SCHEDULER_LMPR FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.NR_SCHEDULER_TASK FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.NR_SCHEDULER_TREG FOR INDEXES ALL;

RUNSTATS ON TABLE HOMEPAGE.SR_INDEXINGTASKDEF 	FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.SR_OPTIMIZETASKDEF	FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.SR_TASKDEF			FOR INDEXES ALL;

RUNSTATS ON TABLE HOMEPAGE.LOTUSCONNECTIONSLMGR FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.LOTUSCONNECTIONSLMPR FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.LOTUSCONNECTIONSTASK FOR INDEXES ALL;
RUNSTATS ON TABLE HOMEPAGE.LOTUSCONNECTIONSTREG FOR INDEXES ALL;

COMMIT;
	
--------------------------------------
-- FLUSH
--------------------------------------
FLUSH PACKAGE CACHE DYNAMIC;

--------------------------------------
-- TERMINATE
--------------------------------------
connect reset;
terminate; 
