-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- 1) Update HOMEPAGE.PERSON  
ALTER TABLE HOMEPAGE.PERSON
ADD STATE SMALLINT DEFAULT 0 NOT NULL;

-- 2) CHANGE HOMEPAGE.NT_NOTIFICATION to be with this size: 16K

-- b) backup the NOTIFICATION table 
------------------------------------------------
-- BK into TMP_NOTIFICATION
------------------------------------------------
CREATE TABLE HOMEPAGE.TMP_NOTIFICATION  (
	  NOTIFICATION_ID VARCHAR(36) NOT NULL,
	  NOTIFICATION_SOURCE VARCHAR(36) NOT NULL,
	  NOTIFICATION_TYPE VARCHAR(256) NOT NULL,
	  DATETIME_STAMP TIMESTAMP NOT NULL,
	  SENDER_EXID VARCHAR(36) NOT NULL,
	  SUBJECT VARCHAR(256),
	  MESSAGE VARCHAR(2048),
	  CONTAINER_NAME VARCHAR(256),
	  CONTAINER_URL VARCHAR(2048),
	  ITEM_NAME VARCHAR(256),
	  ITEM_URL VARCHAR(2048) 
)
IN HPNT16TABSPACE;

INSERT INTO HOMEPAGE.TMP_NOTIFICATION (     NOTIFICATION_ID, NOTIFICATION_SOURCE, NOTIFICATION_TYPE, DATETIME_STAMP, SENDER_EXID, SUBJECT, MESSAGE, 
                                            CONTAINER_NAME, CONTAINER_URL, ITEM_NAME, ITEM_URL)    
SELECT  NOTIFICATION_ID, NOTIFICATION_SOURCE, NOTIFICATION_TYPE, DATETIME_STAMP, SENDER_EXID, SUBJECT, MESSAGE, 
        CONTAINER_NAME, CONTAINER_URL, ITEM_NAME, ITEM_URL
FROM HOMEPAGE.NT_NOTIFICATION;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT DROP FOREIGN KEY "FK_RECIP_NOTIF";

DROP TABLE HOMEPAGE.NT_NOTIFICATION;

CREATE TABLE HOMEPAGE.NT_NOTIFICATION  (
	  NOTIFICATION_ID VARCHAR(36) NOT NULL,
	  NOTIFICATION_SOURCE VARCHAR(36) NOT NULL,
	  NOTIFICATION_TYPE VARCHAR(256) NOT NULL,
	  DATETIME_STAMP TIMESTAMP NOT NULL,
	  SENDER_EXID VARCHAR(36) NOT NULL,
	  SUBJECT VARCHAR(256),
	  MESSAGE VARCHAR(2048),
	  CONTAINER_NAME VARCHAR(256),
	  CONTAINER_URL VARCHAR(2048),
	  ITEM_NAME VARCHAR(256),
	  ITEM_URL VARCHAR(2048) 
)
IN HPNT16TABSPACE;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
	ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NOTIFICATION_ID");

CREATE INDEX HOMEPAGE.NT_NOTIFICATION_EXID_INDEX
	ON HOMEPAGE.NT_NOTIFICATION(SENDER_EXID);	

RUNSTATS ON TABLE "HOMEPAGE"."NT_NOTIFICATION" FOR INDEXES ALL;
REORG TABLE	HOMEPAGE.NT_NOTIFICATION;

INSERT INTO HOMEPAGE.NT_NOTIFICATION (     NOTIFICATION_ID, NOTIFICATION_SOURCE, NOTIFICATION_TYPE, DATETIME_STAMP, SENDER_EXID, SUBJECT, MESSAGE, 
                                            CONTAINER_NAME, CONTAINER_URL, ITEM_NAME, ITEM_URL)    
SELECT  NOTIFICATION_ID, NOTIFICATION_SOURCE, NOTIFICATION_TYPE, DATETIME_STAMP, SENDER_EXID, SUBJECT, MESSAGE, 
        CONTAINER_NAME, CONTAINER_URL, ITEM_NAME, ITEM_URL
FROM HOMEPAGE.TMP_NOTIFICATION;

RUNSTATS ON TABLE "HOMEPAGE"."NT_NOTIFICATION" FOR INDEXES ALL;
REORG TABLE	HOMEPAGE.NT_NOTIFICATION;

DROP TABLE HOMEPAGE.TMP_NOTIFICATION;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
	ADD CONSTRAINT "FK_RECIP_NOTIF" FOREIGN KEY ("NOTIFICATION_ID")
	REFERENCES HOMEPAGE.NT_NOTIFICATION ("NOTIFICATION_ID")
	ON DELETE CASCADE;
	

-- b) update the NT_NOTIFICATION table
ALTER TABLE HOMEPAGE.NT_NOTIFICATION
ADD FIRST_RECIPIENT_EXID VARCHAR(36);

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
ADD NUM_RECIPIENTS SMALLINT;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
ADD IS_DELETED SMALLINT;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
ADD PRIMARY_ACTION_URL VARCHAR(2048);

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
ADD SECONDARY_ACTION_URL VARCHAR(2048);

--c) update NT_RECIPIENTS table
ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT
ADD IS_DELETED SMALLINT;

RUNSTATS ON TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT" FOR INDEXES ALL;
REORG TABLE	HOMEPAGE.NT_NOTIFICATION_RECIPIENT;
