-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}
 
----------------------------------------------------------------------
-- HOMEPAGE.MT_METRICS 
----------------------------------------------------------------------

CREATE TABLE HOMEPAGE.MT_METRIC_STAT  (
      METRIC_STAT_ID VARCHAR(36) NOT NULL,
      RECORDED_ON TIMESTAMP NOT NULL,
      METRIC_TYPE SMALLINT NOT NULL,
      METRIC_DESC VARCHAR(36) NOT NULL,
      RES_BUNDLE_KEY VARCHAR(144) NOT NULL,
      COUNT_LAST_24_H BIGINT,
      COUNT_LAST_7_D BIGINT,
      COUNT_LAST_1_M BIGINT,
      TOP_STATS VARCHAR(512),
      TOT_STAT BIGINT,
      AVG_TOT_STAT BIGINT
)
IN HOMEPAGETABSPACE;

ALTER TABLE HOMEPAGE.MT_METRIC_STAT 
    ADD CONSTRAINT PK_METRIC_STAT_ID PRIMARY KEY(METRIC_STAT_ID);

CREATE INDEX HOMEPAGE.MT_METRICS_IDX
    ON HOMEPAGE.MT_METRIC_STAT (RECORDED_ON ASC, METRIC_TYPE);
    
{DB2_GRANT_START} HOMEPAGE.MT_METRIC_STAT {DB2_GRANT_STOP}


-------------------------------------------------
-- FIXING NT_NOTIFICATION TABLE
-------------------------------------------------

-- 1 NT_NOTIFICATION_RECIPIENT WHERE RECIPIENT_ID
------------------------------------------------------------------------------------------------------------
-- DELETE FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT WHERE RECIPIENT_ID IS NULL;
------------------------------------------------------------------------------------------------------------
DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (HEX(SUBSTR(ID,1,1))) <= '30' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (HEX(SUBSTR(ID,1,1))) > '30' AND (HEX(SUBSTR(ID,1,1))) <= '34' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (HEX(SUBSTR(ID,1,1))) > '34' AND (HEX(SUBSTR(ID,1,1))) <= '39' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (HEX(SUBSTR(ID,1,1))) > '39' AND (HEX(SUBSTR(ID,1,1))) <= '61' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (HEX(SUBSTR(ID,1,1))) > '61' AND (HEX(SUBSTR(ID,1,1))) <= '64' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (HEX(SUBSTR(ID,1,1))) > '64' AND (HEX(SUBSTR(ID,1,1))) <= '66' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT 
WHERE (HEX(SUBSTR(ID,1,1))) > '66' AND RECIPIENT_ID IS NULL;

COMMIT;

DELETE 
FROM HOMEPAGE.NT_NOTIFICATION_RECIPIENT
WHERE RECIPIENT_ID IS NULL;

COMMIT;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION_RECIPIENT
	ALTER COLUMN RECIPIENT_ID SET NOT NULL;

reorg table HOMEPAGE.NT_NOTIFICATION_RECIPIENT use HPNT16TMPTABSPACE;

COMMIT;

-- 2 NT_NOTIFICATION WHERE FIRST_RECIPIENT_ID
-----------------------------------------------------------------------------------
-- DELETE FROM HOMEPAGE.NT_NOTIFICATION WHERE FIRST_RECIPIENT_ID IS NULL;
----------------------------------------------------------------------------------- 
DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '30' AND NOTIFICATION_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '30' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '34' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '34' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '39' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '39' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '61' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '61' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '64' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '64' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '66' AND FIRST_RECIPIENT_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '66' AND NOTIFICATION_ID IS NULL;

COMMIT;

DELETE 
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE FIRST_RECIPIENT_ID IS NULL;

COMMIT;

ALTER TABLE HOMEPAGE.NT_NOTIFICATION
	ALTER COLUMN FIRST_RECIPIENT_ID SET NOT NULL;

reorg table HOMEPAGE.NT_NOTIFICATION use HPNT16TMPTABSPACE;
	
-- 3 NT_NOTIFICATION WHERE SENDER_ID
-----------------------------------------------------------------------------------
-- DELETE FROM HOMEPAGE.NT_NOTIFICATION WHERE SENDER_ID IS NULL;
-----------------------------------------------------------------------------------
DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '30' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '30' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '34' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '34' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '39' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '39' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '61' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '61' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '64' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '64' AND (HEX(SUBSTR(NOTIFICATION_ID,1,1))) <= '66' AND SENDER_ID IS NULL;

COMMIT;

DELETE
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE (HEX(SUBSTR(NOTIFICATION_ID,1,1))) > '66' AND NOTIFICATION_ID IS NULL;

COMMIT;

DELETE 
FROM HOMEPAGE.NT_NOTIFICATION 
WHERE SENDER_ID IS NULL;

COMMIT;
	
ALTER TABLE HOMEPAGE.NT_NOTIFICATION
	ALTER COLUMN SENDER_ID SET NOT NULL;

reorg table HOMEPAGE.NT_NOTIFICATION use HPNT16TMPTABSPACE;

COMMIT;	




