-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 103 -----------------------------------
---------------------------------------------------------------------------------

-- TODO
-- 68544: Adding to AS table an unique column where the timestamp is auto generated 
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST ALTER COLUMN UPDATE_DATE SET  DEFAULT CURRENT TIMESTAMP;
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST ALTER COLUMN UPDATE_DATE SET NOT NULL;
COMMIT;

--68754: expensive comments query, tablescan on BOARD_COMMENTS
CREATE INDEX HOMEPAGE.SEEDLIST_BRD_IDX 
	ON HOMEPAGE.BOARD_ENTRIES (SL_UPDATE_DATE ASC, ENTRY_ID);
COMMIT;	

REORG TABLE HOMEPAGE.NR_AS_SEEDLIST ALLOW NO ACCESS;
COMMIT;

-- 67826
DROP INDEX HOMEPAGE.NR_STORIES_ER_UUID;
COMMIT;

CREATE INDEX  HOMEPAGE.NR_STORIES_ER_UUID 
	ON HOMEPAGE.NR_STORIES (EVENT_RECORD_UUID, STORY_ID);
COMMIT;

-- 68050: Discovery view for communities is very slow. Index needed
CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_COM 
	ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_STORY_COMM, USE_IN_ROLLUP);
COMMIT;

--68097: Remove WIDGET_ID column from BOARD table in next fixup
ALTER TABLE HOMEPAGE.BOARD DROP COLUMN WIDGET_ID;
COMMIT;

reorg table HOMEPAGE.BOARD ALLOW NO ACCESS;
COMMIT;

--59735: Exception in the logs on News startup in SourceTypeSyncServiceImpl
UPDATE HOMEPAGE.NR_SOURCE_TYPE 	SET  	IMAGE_URL = '${connections}/resources/web/com.ibm.lconn.core.styles/images/iconCommunities16.png',
										IMAGE_URL_SSL = '${connections}/resources/web/com.ibm.lconn.core.styles/images/iconCommunities16.png'
								WHERE 	SOURCE = 'communities';
COMMIT;			

--68088: [fixup 103] Add 2 columns in BOARD_ENTRIES and BOARD_COMMENTS
--57636: Issue with hashtags keeping the capitals characters when added
--TAGS_LOWER columns in BOARD_ENTRIES and BOARD_COMMENTS
ALTER TABLE HOMEPAGE.BOARD_ENTRIES ADD HTML_CONTENT CLOB;
COMMIT;

ALTER TABLE HOMEPAGE.BOARD_COMMENTS ADD HTML_CONTENT CLOB;
COMMIT;

reorg table HOMEPAGE.BOARD_ENTRIES ALLOW NO ACCESS;
COMMIT;
reorg table HOMEPAGE.BOARD_COMMENTS ALLOW NO ACCESS;
COMMIT;


-------------------------------------------------------------------------------------------------------------
-- Drop 2 indexes: AUT_IX, RLL_IX; Create a new index
-------------------------------------------------------------------------------------------------------------

--  [start indexes] NR_AGGREGATED_READERS
DROP  INDEX HOMEPAGE.AGGREGATED_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_AGGREGATED_READERS



COMMIT;


--  [start indexes] NR_RESPONSES_READERS
DROP  INDEX HOMEPAGE.RESPONSES_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.RESPONSES_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_RESPONSES_READERS



COMMIT;


--  [start indexes] NR_PROFILES_READERS
DROP  INDEX HOMEPAGE.PROFILES_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_PROFILES_READERS



COMMIT;


--  [start indexes] NR_COMMUNITIES_READERS
DROP  INDEX HOMEPAGE.COMM_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.COMM_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_COMMUNITIES_READERS



COMMIT;


--  [start indexes] NR_ACTIVITIES_READERS
DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_ACTIVITIES_READERS



COMMIT;


--  [start indexes] NR_BLOGS_READERS
DROP  INDEX HOMEPAGE.BLOGS_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BLOGS_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_BLOGS_READERS



COMMIT;


--  [start indexes] NR_BOOKMARKS_READERS
DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_BOOKMARKS_READERS



COMMIT;


--  [start indexes] NR_FILES_READERS
DROP  INDEX HOMEPAGE.FILES_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FILES_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_FILES_READERS



COMMIT;


--  [start indexes] NR_FORUMS_READERS
DROP  INDEX HOMEPAGE.FORUMS_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.FORUMS_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_FORUMS_READERS



COMMIT;


--  [start indexes] NR_WIKIS_READERS
DROP  INDEX HOMEPAGE.WIKIS_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.WIKIS_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_WIKIS_READERS



COMMIT;


--  [start indexes] NR_TAGS_READERS
DROP  INDEX HOMEPAGE.TAGS_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TAGS_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_TAGS_READERS



COMMIT;


--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX HOMEPAGE.STATUS_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.STATUS_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_STATUS_UPDATE_READERS



COMMIT;


--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX HOMEPAGE.EXTERNAL_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_EXTERNAL_READERS



COMMIT;


--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_ACTIONABLE_READERS



COMMIT;


--  [start indexes] NR_DISCOVERY_VIEW
DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_IX;
COMMIT;

--  [end indexes] NR_DISCOVERY_VIEW



COMMIT;


--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX HOMEPAGE.PROFILES_VIEW_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.PROFILES_VIEW_RLL_IX;
COMMIT;

--  [end indexes] NR_PROFILES_VIEW



COMMIT;


--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX HOMEPAGE.NOTIFICA_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_NOTIFICATION_SENT_READERS



COMMIT;


--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP  INDEX HOMEPAGE.NOT_REC_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.NOT_REC_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS



COMMIT;


--  [start indexes] NR_SAVED_READERS
DROP  INDEX HOMEPAGE.SAVED_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.SAVED_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_SAVED_READERS



COMMIT;


--  [start indexes] NR_TOPICS_READERS
DROP  INDEX HOMEPAGE.TOPICS_READERS_AUT_IX;
COMMIT;

DROP  INDEX HOMEPAGE.TOPICS_READERS_RLL_IX;
COMMIT;

--  [end indexes] NR_TOPICS_READERS






--  [start indexes] NR_AGGREGATED_READERS
CREATE INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_AGGREGATED_READERS





--  [start indexes] NR_RESPONSES_READERS
CREATE INDEX HOMEPAGE.RESPONSES_READERS_RLL_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_RESPONSES_READERS





--  [start indexes] NR_PROFILES_READERS
CREATE INDEX HOMEPAGE.PROFILES_READERS_RLL_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_PROFILES_READERS





--  [start indexes] NR_COMMUNITIES_READERS
CREATE INDEX HOMEPAGE.COMM_READERS_RLL_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_COMMUNITIES_READERS





--  [start indexes] NR_ACTIVITIES_READERS
CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_ACTIVITIES_READERS





--  [start indexes] NR_BLOGS_READERS
CREATE INDEX HOMEPAGE.BLOGS_READERS_RLL_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_BLOGS_READERS





--  [start indexes] NR_BOOKMARKS_READERS
CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_BOOKMARKS_READERS





--  [start indexes] NR_FILES_READERS
CREATE INDEX HOMEPAGE.FILES_READERS_RLL_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_FILES_READERS





--  [start indexes] NR_FORUMS_READERS
CREATE INDEX HOMEPAGE.FORUMS_READERS_RLL_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_FORUMS_READERS





--  [start indexes] NR_WIKIS_READERS
CREATE INDEX HOMEPAGE.WIKIS_READERS_RLL_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_WIKIS_READERS





--  [start indexes] NR_TAGS_READERS
CREATE INDEX HOMEPAGE.TAGS_READERS_RLL_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_TAGS_READERS





--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE INDEX HOMEPAGE.STATUS_READERS_RLL_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_STATUS_UPDATE_READERS





--  [start indexes] NR_EXTERNAL_READERS
CREATE INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_EXTERNAL_READERS





--  [start indexes] NR_ACTIONABLE_READERS
CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_ACTIONABLE_READERS





--  [start indexes] NR_DISCOVERY_VIEW
CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_IX ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_DISCOVERY_VIEW





--  [start indexes] NR_PROFILES_VIEW
CREATE INDEX HOMEPAGE.PROFILES_VIEW_RLL_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_PROFILES_VIEW





--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_NOTIFICATION_SENT_READERS





--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE INDEX HOMEPAGE.NOT_REC_READERS_RLL_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS





--  [start indexes] NR_SAVED_READERS
CREATE INDEX HOMEPAGE.SAVED_READERS_RLL_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_SAVED_READERS





--  [start indexes] NR_TOPICS_READERS
CREATE INDEX HOMEPAGE.TOPICS_READERS_RLL_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, USE_IN_ROLLUP);
COMMIT;

--  [end indexes] NR_TOPICS_READERS


---------------------------------------------------------------------------------
------------------------ END NEWS FIXUP 103 -------------------------------------
---------------------------------------------------------------------------------
 

  
  
  
