-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2015                                   
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- 141809: Rollup is by object + action

-------------------------------------------------------
-- NR_ENTRIES_ROLLUP_ACTION
-------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION  (
        ENTRY_ROLLUP_ACTION_ID VARCHAR(36) NOT NULL,
        ROLLUP_ENTRY_ID VARCHAR(256) NOT NULL,
        ROLLUP_AUTHOR_ID VARCHAR(36),
        TEMPLATE_NAME VARCHAR(256) NOT NULL,
        ACTION VARCHAR(50) NOT NULL,   			
        ACTION_COUNT INTEGER DEFAULT 0, 
		META_TEMPLATE VARCHAR(3328) NOT NULL,
		TEXT_META_TEMPLATE VARCHAR(1024) NOT NULL,
		CREATION_DATE TIMESTAMP NOT NULL,
        UPDATE_DATE TIMESTAMP NOT NULL,
		ORGANIZATION_ID VARCHAR(36) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL 		  
)
IN NEWSTABSPACE@

ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION
	ADD CONSTRAINT PK_ENTRIES_ROLLUP_ACTION_ID PRIMARY KEY (ENTRY_ROLLUP_ACTION_ID)@

ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION
	ADD CONSTRAINT FK_ROLLUP_AUTHOR_ID FOREIGN KEY (ROLLUP_AUTHOR_ID) REFERENCES HOMEPAGE.PERSON(PERSON_ID)@

ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION 
	ADD CONSTRAINT FK_ORGANIZATION_ID FOREIGN KEY (ORGANIZATION_ID)  REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@
	
CREATE INDEX HOMEPAGE.ENTR_ROLLUP_ACT_CDATE_IDX 
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION (CREATION_DATE DESC)@
	
CREATE INDEX HOMEPAGE.ENTR_ROLLUP_ACT_UDATE_IDX 
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION (UPDATE_DATE DESC)@

CREATE UNIQUE INDEX HOMEPAGE.ENTR_ROLLUP_ACT_UNQ_IDX
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION (ROLLUP_ENTRY_ID, ACTION, ROLLUP_AUTHOR_ID, ORGANIZATION_ID)@
	
CREATE INDEX HOMEPAGE.ENTR_ROLLUP_ACT_AUT_ID_IDX
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION (ROLLUP_AUTHOR_ID, ORGANIZATION_ID)@	

CREATE INDEX HOMEPAGE.ENTRIES_ROLLUP_ACT_AUT_IDX 
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION (ROLLUP_AUTHOR_ID)@


---------------------------------------------------------------
-- NR_ENTRIES_ROLLUP_PERSON
---------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON  (
        ENTRY_ROLLUP_PERSON_ID VARCHAR(36) NOT NULL,
        ENTRY_ROLLUP_ACTION_ID VARCHAR(36) NOT NULL,			
        PERSON_ID VARCHAR(36) NOT NULL,			
        ACTION_COUNT INTEGER DEFAULT 0,
		CREATION_DATE TIMESTAMP NOT NULL,
        UPDATE_DATE TIMESTAMP NOT NULL,
		ORGANIZATION_ID VARCHAR(36) DEFAULT '00000000-0000-0000-0000-000000000000' NOT NULL 	  		  
)
IN NEWSTABSPACE@

ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON
	ADD CONSTRAINT PK_ENTRY_ROLLUP_PERSON_ID PRIMARY KEY (ENTRY_ROLLUP_PERSON_ID)@

ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON
	ADD CONSTRAINT FK_ENTRY_ROLLUP_ACTION_ID FOREIGN KEY (ENTRY_ROLLUP_ACTION_ID) REFERENCES HOMEPAGE.NR_ENTRIES_ROLLUP_ACTION (ENTRY_ROLLUP_ACTION_ID)@

ALTER TABLE HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON 
	ADD CONSTRAINT FK_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES HOMEPAGE.PERSON(PERSON_ID)@

CREATE INDEX HOMEPAGE.ENTR_ROLLUP_PER_CDATE_IDX 
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON (CREATION_DATE DESC)@

CREATE INDEX HOMEPAGE.ENTR_ROLLUP_PER_UDATE_IDX 
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON (UPDATE_DATE DESC)@

CREATE INDEX HOMEPAGE.ENTR_ROLLUP_PER_PER_ID_IDX 
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON (PERSON_ID, ORGANIZATION_ID)@

CREATE UNIQUE INDEX HOMEPAGE.ENTR_ROLLUP_PER_ROL_ACTI_IDX 
	ON HOMEPAGE.NR_ENTRIES_ROLLUP_PERSON (ENTRY_ROLLUP_ACTION_ID, PERSON_ID, ORGANIZATION_ID)@

-----------------------------------------------------------------------------------------	
	
INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('lastActor','lastActor', 'lastActor', 'profilePhoto', 1)@

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('previousActor','previousActor', 'previousActor', 'profilePhoto', 1)@

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('actionCount','actionCount', 'actionCount', 'plain', 1)@