-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

DROP INDEX HOMEPAGE.DISCOVERY_VIEW_COM@


CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_COM 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (IS_STORY_COMM, ORGANIZATION_ID, IS_VISIBLE, USE_IN_ROLLUP, CREATION_DATE DESC, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID)@ 
COMMIT@

--  [start indexes] NR_AGGREGATED_READERS
DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
DROP  INDEX HOMEPAGE.RESPONSES_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
DROP  INDEX HOMEPAGE.PROFILES_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
DROP  INDEX HOMEPAGE.COMM_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
DROP  INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
DROP  INDEX HOMEPAGE.BLOGS_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
DROP  INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
DROP  INDEX HOMEPAGE.FILES_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
DROP  INDEX HOMEPAGE.FORUMS_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
DROP  INDEX HOMEPAGE.WIKIS_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
DROP  INDEX HOMEPAGE.TAGS_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX HOMEPAGE.STATUS_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
DROP  INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_IIX@
COMMIT@

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX HOMEPAGE.PROFILES_VIEW_RLL_IIX@
COMMIT@

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
DROP  INDEX HOMEPAGE.NOT_REC_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
DROP  INDEX HOMEPAGE.SAVED_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
DROP  INDEX HOMEPAGE.TOPICS_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
DROP  INDEX HOMEPAGE.MENTIONS_READERS_RLL_IIX@
COMMIT@

--  [end indexes] NR_MENTIONS_READERS

--  [start indexes] NR_COMMUNITIES_VIEW
DROP  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_IIX@
COMMIT@

--  [end indexes] NR_COMMUNITIES_VIEW


--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_RESPONSES_READERS
CREATE  INDEX HOMEPAGE.RESPONSES_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_RESPONSES_READERS

--  [start indexes] NR_PROFILES_READERS
CREATE  INDEX HOMEPAGE.PROFILES_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_PROFILES_READERS

--  [start indexes] NR_COMMUNITIES_READERS
CREATE  INDEX HOMEPAGE.COMM_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_COMMUNITIES_READERS

--  [start indexes] NR_ACTIVITIES_READERS
CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_ACTIVITIES_READERS

--  [start indexes] NR_BLOGS_READERS
CREATE  INDEX HOMEPAGE.BLOGS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_BLOGS_READERS

--  [start indexes] NR_BOOKMARKS_READERS
CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_BOOKMARKS_READERS

--  [start indexes] NR_FILES_READERS
CREATE  INDEX HOMEPAGE.FILES_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_FILES_READERS

--  [start indexes] NR_FORUMS_READERS
CREATE  INDEX HOMEPAGE.FORUMS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_FORUMS_READERS

--  [start indexes] NR_WIKIS_READERS
CREATE  INDEX HOMEPAGE.WIKIS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_WIKIS_READERS

--  [start indexes] NR_TAGS_READERS
CREATE  INDEX HOMEPAGE.TAGS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_TAGS_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX HOMEPAGE.STATUS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_DISCOVERY_VIEW
CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (USE_IN_ROLLUP, ORGANIZATION_ID, IS_VISIBLE, CREATION_DATE DESC,  IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID)@ 
COMMIT@

--  [end indexes] NR_DISCOVERY_VIEW

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX HOMEPAGE.PROFILES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_NOTIFICATION_RECEIV_READERS
CREATE  INDEX HOMEPAGE.NOT_REC_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_NOTIFICATION_RECEIV_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX HOMEPAGE.SAVED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX HOMEPAGE.TOPICS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
CREATE  INDEX HOMEPAGE.MENTIONS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_MENTIONS_READERS

--  [start indexes] NR_COMMUNITIES_VIEW
CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_COMMUNITIES_VIEW
