-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------------------------------------------------------
-- 135559: Homepage_Check-SC-DB-Fixup IC10.0_Homepage_20140922-1157 - UNIQUE INDEX issues
---------------------------------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.TMP (
	CATEGORY_READER_ID VARCHAR(36) NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL
)@
COMMIT@

ALTER TABLE HOMEPAGE.TMP
    ADD CONSTRAINT PK_TMP PRIMARY KEY (CATEGORY_READER_ID)@
COMMIT@

-- 148073: Homepage database fixup510 hangs
CREATE INDEX HOMEPAGE.IDX1 ON HOMEPAGE.TMP (STORY_ID, READER_ID)@
COMMIT@

--------------------------------------------------------------------------------------------------------
-- FIX NR_AGGREGATED_READERS TABLE
--------------------------------------------------------------------------------------------------------
-- I) SEARCH FOR DUPS
INSERT INTO HOMEPAGE.TMP (CATEGORY_READER_ID, STORY_ID, READER_ID, CATEGORY_TYPE) (
	SELECT READERS.CATEGORY_READER_ID, READERS.STORY_ID, READERS.READER_ID, READERS.CATEGORY_TYPE
	FROM
		(
		SELECT 	STORY_ID, READER_ID, CATEGORY_TYPE 
		FROM 	HOMEPAGE.NR_AGGREGATED_READERS    
		GROUP 	BY STORY_ID, READER_ID, CATEGORY_TYPE HAVING COUNT(*) > 1
		) TMP,
		HOMEPAGE.NR_AGGREGATED_READERS    READERS
	WHERE  	TMP.STORY_ID = READERS.STORY_ID AND 
			TMP.READER_ID = READERS.READER_ID AND
			TMP.CATEGORY_TYPE = READERS.CATEGORY_TYPE
)@
COMMIT@

RUNSTATS ON TABLE HOMEPAGE.TMP@

-- DELETE DUPS
DELETE FROM HOMEPAGE.NR_AGGREGATED_READERS R WHERE CATEGORY_READER_ID IN (
	SELECT CATEGORY_READER_ID FROM HOMEPAGE.TMP WHERE CATEGORY_READER_ID < ( 
		SELECT 	MAX(CATEGORY_READER_ID) 
		FROM 	HOMEPAGE.TMP TMP
		WHERE 	TMP.STORY_ID = R.STORY_ID AND TMP.READER_ID = R.READER_ID AND TMP.CATEGORY_TYPE = R.CATEGORY_TYPE
		GROUP BY STORY_ID, READER_ID, CATEGORY_TYPE)
)@
COMMIT@

-- CLEAN TMP TABLE
TRUNCATE  HOMEPAGE.TMP IMMEDIATE@
COMMIT@
--------------------------------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------
-- FIX NR_STATUS_UPDATE_READERS TABLE
--------------------------------------------------------------------------------------------------------
-- I) SEARCH FOR DUPS
INSERT INTO HOMEPAGE.TMP (CATEGORY_READER_ID, STORY_ID, READER_ID, CATEGORY_TYPE) (
	SELECT READERS.CATEGORY_READER_ID, READERS.STORY_ID, READERS.READER_ID, READERS.CATEGORY_TYPE
	FROM
		(
		SELECT 	STORY_ID, READER_ID, CATEGORY_TYPE 
		FROM 	HOMEPAGE.NR_STATUS_UPDATE_READERS    
		GROUP 	BY STORY_ID, READER_ID, CATEGORY_TYPE HAVING COUNT(*) > 1
		) TMP,
		HOMEPAGE.NR_STATUS_UPDATE_READERS    READERS
	WHERE  	TMP.STORY_ID = READERS.STORY_ID AND 
			TMP.READER_ID = READERS.READER_ID AND
			TMP.CATEGORY_TYPE = READERS.CATEGORY_TYPE
)@
COMMIT@

RUNSTATS ON TABLE HOMEPAGE.TMP@

-- DELETE DUPS
DELETE FROM HOMEPAGE.NR_STATUS_UPDATE_READERS R WHERE CATEGORY_READER_ID IN (
	SELECT CATEGORY_READER_ID FROM HOMEPAGE.TMP WHERE CATEGORY_READER_ID < ( 
		SELECT 	MAX(CATEGORY_READER_ID) 
		FROM 	HOMEPAGE.TMP TMP
		WHERE 	TMP.STORY_ID = R.STORY_ID AND TMP.READER_ID = R.READER_ID AND TMP.CATEGORY_TYPE = R.CATEGORY_TYPE
		GROUP BY STORY_ID, READER_ID, CATEGORY_TYPE)
)@
COMMIT@


-- CLEAN TMP TABLE
TRUNCATE  HOMEPAGE.TMP IMMEDIATE@
COMMIT@

--------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
-- FIX NR_SAVED_READERS TABLE
--------------------------------------------------------------------------------------------------------
-- I) SEARCH FOR DUPS
INSERT INTO HOMEPAGE.TMP (CATEGORY_READER_ID, STORY_ID, READER_ID, CATEGORY_TYPE) (
	SELECT READERS.CATEGORY_READER_ID, READERS.STORY_ID, READERS.READER_ID, READERS.CATEGORY_TYPE
	FROM
		(
		SELECT 	STORY_ID, READER_ID, CATEGORY_TYPE 
		FROM 	HOMEPAGE.NR_SAVED_READERS    
		GROUP 	BY STORY_ID, READER_ID, CATEGORY_TYPE HAVING COUNT(*) > 1
		) TMP,
		HOMEPAGE.NR_SAVED_READERS    READERS
	WHERE  	TMP.STORY_ID = READERS.STORY_ID AND 
			TMP.READER_ID = READERS.READER_ID AND
			TMP.CATEGORY_TYPE = READERS.CATEGORY_TYPE
)@
COMMIT@

RUNSTATS ON TABLE HOMEPAGE.TMP@

-- DELETE DUPS
DELETE FROM HOMEPAGE.NR_SAVED_READERS R WHERE CATEGORY_READER_ID IN (
	SELECT CATEGORY_READER_ID FROM HOMEPAGE.TMP WHERE CATEGORY_READER_ID < ( 
		SELECT 	MAX(CATEGORY_READER_ID) 
		FROM 	HOMEPAGE.TMP TMP
		WHERE 	TMP.STORY_ID = R.STORY_ID AND TMP.READER_ID = R.READER_ID AND TMP.CATEGORY_TYPE = R.CATEGORY_TYPE
		GROUP BY STORY_ID, READER_ID, CATEGORY_TYPE)
)@
COMMIT@

-- CLEAN TMP TABLE
TRUNCATE  HOMEPAGE.TMP IMMEDIATE@
COMMIT@
--------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
-- FIX NR_COMMUNITIES_VIEW TABLE
--------------------------------------------------------------------------------------------------------
-- I) SEARCH FOR DUPS
INSERT INTO HOMEPAGE.TMP (CATEGORY_READER_ID, STORY_ID, READER_ID, CATEGORY_TYPE) (
	SELECT READERS.CATEGORY_READER_ID, READERS.STORY_ID, READERS.READER_ID, READERS.CATEGORY_TYPE
	FROM
		(
		SELECT 	STORY_ID, READER_ID, CATEGORY_TYPE 
		FROM 	HOMEPAGE.NR_COMMUNITIES_VIEW    
		GROUP 	BY STORY_ID, READER_ID, CATEGORY_TYPE HAVING COUNT(*) > 1
		) TMP,
		HOMEPAGE.NR_COMMUNITIES_VIEW    READERS
	WHERE  	TMP.STORY_ID = READERS.STORY_ID AND 
			TMP.READER_ID = READERS.READER_ID AND
			TMP.CATEGORY_TYPE = READERS.CATEGORY_TYPE
)@
COMMIT@

RUNSTATS ON TABLE HOMEPAGE.TMP@

-- DELETE DUPS
DELETE FROM HOMEPAGE.NR_COMMUNITIES_VIEW R WHERE CATEGORY_READER_ID IN (
	SELECT CATEGORY_READER_ID FROM HOMEPAGE.TMP WHERE CATEGORY_READER_ID < ( 
		SELECT 	MAX(CATEGORY_READER_ID) 
		FROM 	HOMEPAGE.TMP TMP
		WHERE 	TMP.STORY_ID = R.STORY_ID AND TMP.READER_ID = R.READER_ID AND TMP.CATEGORY_TYPE = R.CATEGORY_TYPE
		GROUP BY STORY_ID, READER_ID, CATEGORY_TYPE)
)@
COMMIT@

-- CLEAN TMP TABLE
TRUNCATE  HOMEPAGE.TMP IMMEDIATE@
COMMIT@

--------------------------------------------------------------------------------------------------------------------------------

DROP TABLE HOMEPAGE.TMP@
COMMIT@

----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------




-- 134379: [fixup505] Unique BOARD_RECOMMENDATIONS index needs to be changed

DROP INDEX HOMEPAGE.BRD_REC_RECOM_ITEM_ID@
COMMIT@

-- 153582: BHT6: Error:  Failed to update AC DB server RPMs.  AC DB Server upgrade failed
EXPORT TO data.tmp.ixf OF IXF METHOD N (
        RECOMMENDATION_ID, RECOMMENDER_ID,  CREATION_DATE
)
 SELECT
       RECOMMENDATION_ID, RECOMMENDER_ID,  CREATION_DATE
 FROM HOMEPAGE.BOARD_RECOMMENDATIONS WHERE RECOMMENDER_ID_DISPLAY IS NULL @

COMMIT@

IMPORT FROM data.tmp.ixf OF IXF METHOD N (
        RECOMMENDATION_ID, RECOMMENDER_ID,  CREATION_DATE
) COMMITCOUNT 2000
        INSERT_UPDATE INTO HOMEPAGE.BOARD_RECOMMENDATIONS
                (
                RECOMMENDATION_ID, RECOMMENDER_ID_DISPLAY, CREATION_DATE_DISPLAY
                )@
COMMIT@
    
CREATE UNIQUE INDEX HOMEPAGE.BRD_REC_RECOM_D_ITEM_ID
	ON HOMEPAGE.BOARD_RECOMMENDATIONS (RECOMMENDER_ID_DISPLAY, ITEM_ID)@	
COMMIT@	


-------------------------------------------------------------------------------------------------
--- Removing un-used tables
-------------------------------------------------------------------------------------------------

-- To speedup the merging process we remove indexes and FK from NR_AGGREGATED_READERS
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT PK_AGG_READERS@
COMMIT@

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_STR@
COMMIT@
	
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_ORG_ID@
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_STR_IX@ 
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_ITM_IX@ 
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_CD_IX@ 
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_DEL_SERV_IX@ 
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX@ 
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_BRD_VVI@ 
COMMIT@

DROP  INDEX HOMEPAGE.AGGREGATED_READERS_COMM_IDX@ 
COMMIT@


-----------------------------------------------------------------------------------------------------
-- Merging just NR_DISCOVERY_VIEW
-----------------------------------------------------------------------------------------------------
-- Merging HOMEPAGE.NR_DISCOVERY_VIEW 
		EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
			CATEGORY_READER_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID, 
			ROLLUP_ENTRY_ID, RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM, 
			IS_BROADCAST, ORGANIZATION_ID, ACTOR_UUID, IS_VISIBLE, ROLLUP_AUTHOR_ID, COMMUNITY_ID 
		) 
		SELECT 
			CATEGORY_READER_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID, 
			ROLLUP_ENTRY_ID, RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM, 
			IS_BROADCAST, ORGANIZATION_ID, ACTOR_UUID, IS_VISIBLE, ROLLUP_AUTHOR_ID, COMMUNITY_ID 
		FROM HOMEPAGE.NR_DISCOVERY_VIEW@ 
		COMMIT@ 
 
		IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
			CATEGORY_READER_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID, 
			ROLLUP_ENTRY_ID, RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM, 
			IS_BROADCAST, ORGANIZATION_ID, ACTOR_UUID, IS_VISIBLE, ROLLUP_AUTHOR_ID, COMMUNITY_ID 
		) COMMITCOUNT 2000 
		INSERT INTO HOMEPAGE.NR_AGGREGATED_READERS ( 
			CATEGORY_READER_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID, 
			ROLLUP_ENTRY_ID, RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM, 
			IS_BROADCAST, ORGANIZATION_ID, ACTOR_UUID, IS_VISIBLE, ROLLUP_AUTHOR_ID, COMMUNITY_ID 
		)@ 
		COMMIT@ 

-------------------------------------------------------------------------------------------------------------------------		
-- DROPPING TABLES (this will be done in a new fixup for debug purpose and in case something fail. This is to prevent data lost
-------------------------------------------------------------------------------------------------------------------------
--DROP TABLE HOMEPAGE.NR_RESPONSES_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_PROFILES_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_COMMUNITIES_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_ACTIVITIES_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_BLOGS_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_BOOKMARKS_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_FILES_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_FORUMS_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_WIKIS_READERS;
--COMMIT;

--DROP TABLE HOMEPAGE.NR_TAGS_READERS;
--COMMIT;												
		
--DROP TABLE HOMEPAGE.NR_DISCOVERY_VIEW; 
--COMMIT;

--DROP TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS;
--COMMIT;

-------------------------------------------------------------------------------------------------------------------------


-- We restore the constraints
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
    ADD CONSTRAINT PK_AGG_READERS PRIMARY KEY(CATEGORY_READER_ID)@

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS 
	ADD CONSTRAINT FK_AGG_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID)@ 
	
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID)@

--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_STR_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_ITM_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ITEM_ID)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_CD_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, CREATION_DATE DESC)@ 
COMMIT@

--CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IIX 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
--COMMIT@

--CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_STR_RDR 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, READER_ID)@ 
--COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_DEL_SERV_IX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE DESC)@ 
COMMIT@

--CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX 
-- 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, IS_VISIBLE, CREATION_DATE DESC)@ 
--COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_BRD_VVI 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_AUTHOR_ID, IS_BROADCAST, IS_VISIBLE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_COMM_IDX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (COMMUNITY_ID)@ 
COMMIT@

--  [end indexes] NR_AGGREGATED_READERS

---------------------------------------------------------------------------------------------------------------
-- Dropping index
---------------------------------------------------------------------------------------------------------------

--  [start indexes] NR_AGGREGATED_READERS
--DROP  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IIX@
--COMMIT@

--DROP  INDEX HOMEPAGE.AGGREGATED_READERS_STR_RDR@
--COMMIT@

--DROP  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX@
--COMMIT@

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
DROP  INDEX HOMEPAGE.STATUS_READERS_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.STATUS_READERS_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
DROP  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_PROFILES_VIEW
DROP  INDEX HOMEPAGE.PROFILES_VIEW_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.PROFILES_VIEW_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
DROP  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_SAVED_READERS
DROP  INDEX HOMEPAGE.SAVED_READERS_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.SAVED_READERS_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
DROP  INDEX HOMEPAGE.TOPICS_READERS_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.TOPICS_READERS_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
DROP  INDEX HOMEPAGE.MENTIONS_READERS_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.MENTIONS_READERS_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_MENTIONS_READERS

--  [start indexes] NR_COMMUNITIES_VIEW
DROP  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_IIX@
COMMIT@

DROP  INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_RDR@
COMMIT@

DROP  INDEX HOMEPAGE.COMMUNITIES_VIEW_ROLLUP_IIIX@
COMMIT@

--  [end indexes] NR_COMMUNITIES_VIEW

-- CREATING INDEX


--  [start indexes] NR_AGGREGATED_READERS
CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.AGGREGATED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID, READER_ID, CONTAINER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_AGGREGATED_READERS

--  [start indexes] NR_STATUS_UPDATE_READERS
CREATE  INDEX HOMEPAGE.STATUS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.STATUS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_STATUS_UPDATE_READERS

--  [start indexes] NR_EXTERNAL_READERS
CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.EXTERNAL_READERS_STR_RDR 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_EXTERNAL_READERS

--  [start indexes] NR_ACTIONABLE_READERS
CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.ACTIONABLE_READERS_STR_RDR 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_ACTIONABLE_READERS

--  [start indexes] NR_PROFILES_VIEW
CREATE  INDEX HOMEPAGE.PROFILES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.PROFILES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_PROFILES_VIEW (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_PROFILES_VIEW

--  [start indexes] NR_NOTIFICATION_SENT_READERS
CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.NOTIFICA_READERS_STR_RDR 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_NOTIFICATION_SENT_READERS

--  [start indexes] NR_SAVED_READERS
CREATE  INDEX HOMEPAGE.SAVED_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.SAVED_READERS_STR_RDR 
 	ON HOMEPAGE.NR_SAVED_READERS (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_SAVED_READERS

--  [start indexes] NR_TOPICS_READERS
CREATE  INDEX HOMEPAGE.TOPICS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.TOPICS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_TOPICS_READERS (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_TOPICS_READERS

--  [start indexes] NR_MENTIONS_READERS
CREATE  INDEX HOMEPAGE.MENTIONS_READERS_RLL_IIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.MENTIONS_READERS_STR_RDR 
 	ON HOMEPAGE.NR_MENTIONS_READERS (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_MENTIONS_READERS

--  [start indexes] NR_COMMUNITIES_VIEW
CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_RLL_IIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (READER_ID, CATEGORY_TYPE, IS_VISIBLE, ORGANIZATION_ID, CREATION_DATE DESC)@ 
COMMIT@

CREATE UNIQUE INDEX HOMEPAGE.COMMUNITIES_VIEW_STR_RDR 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (STORY_ID, READER_ID, CATEGORY_TYPE)@ 
COMMIT@

CREATE  INDEX HOMEPAGE.COMMUNITIES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE, CREATION_DATE DESC)@ 
COMMIT@

--  [end indexes] NR_COMMUNITIES_VIEW


