-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2015, 2016                             
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- -----------------------------------------------------------------
-- Visitor model event tracking table
-- -----------------------------------------------------------------

CREATE TABLE HOMEPAGE.VM_EVENT_TRACKER(
	SUBSCRIBER_ID VARCHAR(36) NOT NULL,
	VISITING_ORG_ID VARCHAR(36),
	HOME_ORG_ID VARCHAR(36),
	LAST_MODIFIED TIMESTAMP NOT NULL,
	MIGRATED SMALLINT DEFAULT 0,
	EVENT_NAME VARCHAR(36) NOT NULL
)
IN NEWS4TABSPACE@

ALTER TABLE HOMEPAGE.VM_EVENT_TRACKER ADD CONSTRAINT PK_VM_SUBSCRIBER_ID PRIMARY KEY (SUBSCRIBER_ID)@
CREATE INDEX HOMEPAGE.VM_VISITING_ORG_IDX ON HOMEPAGE.VM_EVENT_TRACKER (VISITING_ORG_ID)@
CREATE INDEX HOMEPAGE.VM_HOME_ORG_IDX ON HOMEPAGE.VM_EVENT_TRACKER (HOME_ORG_ID)@

COMMIT@

RUNSTATS ON TABLE HOMEPAGE.VM_EVENT_TRACKER@

-- -----------------------------------------------------------------
-- IC Task 173439
-- -----------------------------------------------------------------

DROP INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.AGGREGATED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_AGGREGATED_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.STATUS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.EXTERNAL_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_EXTERNAL_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.PROFILES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_PROFILES_VIEW (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.NOTIFICA_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.SAVED_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_SAVED_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.TOPICS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_TOPICS_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.MENTIONS_READERS_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_MENTIONS_READERS (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

DROP INDEX HOMEPAGE.COMMUNITIES_VIEW_ROLLUP_IIIX@
COMMIT@

CREATE INDEX HOMEPAGE.COMMUNITIES_VIEW_ROLLUP_IIIX 
 	ON HOMEPAGE.NR_COMMUNITIES_VIEW (ROLLUP_ENTRY_ID, READER_ID, CATEGORY_TYPE, IS_VISIBLE)@ 
COMMIT@

