-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-----------------------------------------------
-- UPDATING SOURCE_TYPE TABLE
-----------------------------------------------
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE
	ADD IS_ENABLE SMALLINT;

COMMIT;
	
UPDATE HOMEPAGE.NR_SOURCE_TYPE SET IS_ENABLE = 1;

COMMIT;

----------------------------------------------------------------------
-- [START] INDEX CLEANUP
----------------------------------------------------------------------

-----------------------------------------------
-- FIXING INDEXES ON COMM_STORIES TABLE
-----------------------------------------------
DROP INDEX  HOMEPAGE.NR_COMM_STORIES_COM_ID;

CREATE INDEX HOMEPAGE.NR_COMM_STORIES_CDATE
    ON HOMEPAGE.NR_COMM_STORIES (COMMUNITY_ID, CREATION_DATE ASC); 

CREATE INDEX HOMEPAGE.NR_COM_STORY_ID			ON	HOMEPAGE.NR_COMM_STORIES (COMMUNITY_ID, STORY_ID);

COMMIT;

-- DROPPING UNUSED INDEXES FOR READERS TABLES
DROP INDEX  HOMEPAGE.RESPONSES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.PROFILES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.COMMUNITIES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.ACTIVITIES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.BLOGS_STORIES_CIDX;
DROP INDEX  HOMEPAGE.BOOKMARKS_STORIES_CIDX;
DROP INDEX  HOMEPAGE.FILES_STORIES_CIDX;
DROP INDEX  HOMEPAGE.FORUMS_STORIES_CIDX;
DROP INDEX  HOMEPAGE.WIKIS_STORIES_CIDX;
DROP INDEX  HOMEPAGE.TAGS_STORIES_CIDX;

-- ADDING INDEXES used to retrieve the evidence and delete records
CREATE INDEX HOMEPAGE.NR_RESP_READER_STORY 		ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID); 
CREATE INDEX HOMEPAGE.NR_PRO_READER_STORY 		ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID);
CREATE INDEX HOMEPAGE.NR_COM_READER_STORY 		ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID);
CREATE INDEX HOMEPAGE.NR_ACT_READER_STORY 		ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID);
CREATE INDEX HOMEPAGE.NR_BLG_READER_STORY 		ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID);
CREATE INDEX HOMEPAGE.NR_BOOK_READER_STORY 		ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID);
CREATE INDEX HOMEPAGE.NR_FILES_READER_STORY 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID);
CREATE INDEX HOMEPAGE.NR_FORUMS_READER_STORY 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID);
CREATE INDEX HOMEPAGE.NR_WIKIS_READER_STORY 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID);
CREATE INDEX HOMEPAGE.NR_TAGS_READER_STORY 		ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID);



COMMIT;

-- DROPPING UNUSED INDEXES FOR ENTRIES TABLES
DROP INDEX  HOMEPAGE.NR_ENTRIES_ACT_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_BLG_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_COM_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_WIK_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_PRF_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_HP_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_DGR_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_FILE_SRC;
DROP INDEX  HOMEPAGE.NR_ENTRIES_FRM_SRC;

-- DROPPING UNUSED INDEXES FOR STORIES TABLES
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_ACT_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_BLG_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_COM_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_WIK_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_PRF_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_HP_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_DGR_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_FILE_SIDX;
DROP INDEX  HOMEPAGE.NR_SRC_STORIES_FRM_SIDX;




----------------------------------------------------------------------
-- [END] INDEX CLEANUP
----------------------------------------------------------------------

---------------------------------------------------------
-- [START] EMD INIT DATA
---------------------------------------------------------
UPDATE HOMEPAGE.EMD_TRANCHE	SET 	
		IS_LOCKED = 0,
		IS_LOCKED_DAILY = 0,
		IS_LOCKED_WEEKLY = 0;
---------------------------------------------------------
-- [END] EMD INIT DATA
---------------------------------------------------------

--------------------------------------------------------
-- [START] UPDATING NR_STORIES TABLES 
--------------------------------------------------------
-- Adding to story table:
-- i) MESSAGE
-- ii) EVENT_TIME
--- iii) VERB
--------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);

COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);


COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM
	ADD MESSAGE VARCHAR(4000)
	ADD EVENT_TIME TIMESTAMP
	ADD VERB VARCHAR (128);
	

COMMIT;	
--------------------------------------------------------
-- [END] UPDATING NR_STORIES TABLES
--------------------------------------------------------

--------------------------------------------------------
-- [START] UPDATING NR_ENTRIES TABLES ADDING
--------------------------------------------------------
--  FIRST: we need to move it do a bigger table space
-- i) Adding preview URL
-- ii) Adding status update column
-- iii) Adding JSON_META_DATA column
-- iv) Event time
--------------------------------------------------------

--------------------------------------------------
-- Before to perform this operation we need to move all the existing table NR_ENTRIES_XXX 
-- to a different tabspace
--------------------------------------------------

-- DROPPING FK TO RENAME TABLE
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT DROP CONSTRAINT FK_ENTRY_ID_ACT;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG DROP CONSTRAINT FK_ENTRY_ID_BLG;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM DROP CONSTRAINT FK_ENTRY_ID_COM;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK DROP CONSTRAINT FK_ENTRY_ID_WIK;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF DROP CONSTRAINT FK_ENTRY_ID_PRF;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP 	DROP CONSTRAINT FK_ENTRY_ID_HP;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR DROP CONSTRAINT FK_ENTRY_ID_DGR;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE DROP CONSTRAINT FK_ENTRY_ID_FILE;
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM DROP CONSTRAINT FK_ENTRY_ID_FRM;

ALTER TABLE HOMEPAGE.NR_NEWS_PRF_COMMENT DROP CONSTRAINT FK_ENTRY_ID;
COMMIT;

-- DROPPING CHECK CONSTRAINTS TO RENAME TABLE
ALTER TABLE HOMEPAGE.NR_ENTRIES_ACT DROP CONSTRAINT CK_ENT_SRC1_TYPE;
ALTER TABLE HOMEPAGE.NR_ENTRIES_BLG DROP CONSTRAINT CK_ENT_SRC2_TYPE;
ALTER TABLE HOMEPAGE.NR_ENTRIES_COM DROP CONSTRAINT CK_ENT_SRC3_TYPE;
ALTER TABLE HOMEPAGE.NR_ENTRIES_WIK DROP CONSTRAINT CK_ENT_SRC4_TYPE;
ALTER TABLE HOMEPAGE.NR_ENTRIES_PRF DROP CONSTRAINT CK_ENT_SRC5_TYPE;
ALTER TABLE HOMEPAGE.NR_ENTRIES_HP DROP CONSTRAINT CK_ENT_SRC6_TYPE;
ALTER TABLE HOMEPAGE.NR_ENTRIES_DGR DROP CONSTRAINT CK_ENT_SRC7_TYPE;
ALTER TABLE HOMEPAGE.NR_ENTRIES_FILE DROP CONSTRAINT CK_ENT_SRC8_TYPE;
ALTER TABLE HOMEPAGE.NR_ENTRIES_FRM DROP CONSTRAINT CK_ENT_SRC9_TYPE;


------------------------------------------------------------------------------------
-- CREATING NEW TABLES (Those new tables will also have the new required fields)
-- Which are: MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA
------------------------------------------------------------------------------------
--------------------------------
-- RENEAMING THE PREV TABLES:
--------------------------------

RENAME TABLE HOMEPAGE.NR_ENTRIES_ACT 		TO ACT;
RENAME TABLE HOMEPAGE.NR_ENTRIES_BLG 		TO BLG;
RENAME TABLE HOMEPAGE.NR_ENTRIES_COM 		TO COM;
RENAME TABLE HOMEPAGE.NR_ENTRIES_WIK 		TO WIK;
RENAME TABLE HOMEPAGE.NR_ENTRIES_PRF 		TO PRF;
RENAME TABLE HOMEPAGE.NR_ENTRIES_HP 		TO HP;
RENAME TABLE HOMEPAGE.NR_ENTRIES_DGR 		TO DGR;
RENAME TABLE HOMEPAGE.NR_ENTRIES_FILE 		TO FILE;
RENAME TABLE HOMEPAGE.NR_ENTRIES_FRM 		TO FRM;

COMMIT;

----------------------------------------------------------------------
-- 1) HOMEPAGE.NR_ENTRIES_ACT
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ENTRIES_ACT (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,
	CONSTRAINT   	CK_ENT_SRC1_TYPE
    				CHECK
    				(SOURCE_TYPE = 1)
)
IN NEWS32TABSPACE;

COMMIT;

----------------------------------------------------------------------
-- 2) HOMEPAGE.NR_ENTRIES_BLG
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ENTRIES_BLG (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,	
	CONSTRAINT   	CK_ENT_SRC2_TYPE
    				CHECK
    				(SOURCE_TYPE = 2)
)
IN NEWS32TABSPACE;

COMMIT;

----------------------------------------------------------------------
-- 3) HOMEPAGE.NR_ENTRIES_COM
----------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ENTRIES_COM (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,	
	CONSTRAINT   	CK_ENT_SRC3_TYPE
    				CHECK
    				(SOURCE_TYPE = 3)
)
IN NEWS32TABSPACE;

COMMIT;

----------------------------------------------------------------------
-- 4) HOMEPAGE.NR_ENTRIES_WIK
----------------------------------------------------------------------    
CREATE TABLE HOMEPAGE.NR_ENTRIES_WIK (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,	
	CONSTRAINT   	CK_ENT_SRC4_TYPE
    				CHECK
    				(SOURCE_TYPE = 4)
)
IN NEWS32TABSPACE;

COMMIT;

----------------------------------------------------------------------
-- 5) HOMEPAGE.NR_ENTRIES_PRF
----------------------------------------------------------------------    
CREATE TABLE HOMEPAGE.NR_ENTRIES_PRF (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,	
	CONSTRAINT   	CK_ENT_SRC5_TYPE
    				CHECK
    				(SOURCE_TYPE = 5)
)
IN NEWS32TABSPACE;

COMMIT;

----------------------------------------------------------------------
-- 6) HOMEPAGE.NR_ENTRIES_HP
----------------------------------------------------------------------    
CREATE TABLE HOMEPAGE.NR_ENTRIES_HP (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,	
	CONSTRAINT   	CK_ENT_SRC6_TYPE
    				CHECK
    				(SOURCE_TYPE = 6)
)
IN NEWS32TABSPACE;

COMMIT;

----------------------------------------------------------------------
-- 7) HOMEPAGE.NR_ENTRIES_DGR
----------------------------------------------------------------------      
CREATE TABLE HOMEPAGE.NR_ENTRIES_DGR (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,	
	CONSTRAINT   	CK_ENT_SRC7_TYPE
    				CHECK
    				(SOURCE_TYPE = 7)
)
IN NEWS32TABSPACE;

COMMIT;

----------------------------------------------------------------------
-- 8) HOMEPAGE.NR_ENTRIES_FILE
----------------------------------------------------------------------      
CREATE TABLE HOMEPAGE.NR_ENTRIES_FILE (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,	
	CONSTRAINT   	CK_ENT_SRC8_TYPE
    				CHECK
    				(SOURCE_TYPE = 8)
)
IN NEWS32TABSPACE;

COMMIT;

----------------------------------------------------------------------
-- 9) HOMEPAGE.NR_ENTRIES_FRM
----------------------------------------------------------------------      
CREATE TABLE HOMEPAGE.NR_ENTRIES_FRM (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,
	CONSTRAINT   	CK_ENT_SRC9_TYPE
    				CHECK
    				(SOURCE_TYPE = 9)
)
IN NEWS32TABSPACE;

COMMIT;

--------------------------------------------------------------
-- MIGRATE DATA
--------------------------------------------------------------
-- [START]  Working on HOMEPAGE.NR_ENTRIES_ACT
reorg table HOMEPAGE.NR_ENTRIES_ACT;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME	

  FROM HOMEPAGE.ACT ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_ACT ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_ACT;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_ACT

-- [START]  Working on HOMEPAGE.NR_ENTRIES_BLG
reorg table HOMEPAGE.NR_ENTRIES_BLG;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME	

  FROM HOMEPAGE.BLG ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_BLG ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_BLG;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_BLG


-- [START]  Working on HOMEPAGE.NR_ENTRIES_COM
reorg table HOMEPAGE.NR_ENTRIES_COM;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME	

  FROM HOMEPAGE.COM ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_COM ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_COM;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_COM


-- [START]  Working on HOMEPAGE.NR_ENTRIES_WIK
reorg table HOMEPAGE.NR_ENTRIES_WIK;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME	

  FROM HOMEPAGE.WIK ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_WIK ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_WIK;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_WIK


-- [START]  Working on HOMEPAGE.NR_ENTRIES_PRF
reorg table HOMEPAGE.NR_ENTRIES_PRF;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME	

  FROM HOMEPAGE.PRF ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_PRF ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_PRF;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_PRF


-- [START]  Working on HOMEPAGE.NR_ENTRIES_HP
reorg table HOMEPAGE.NR_ENTRIES_HP;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME	

  FROM HOMEPAGE.HP ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_HP ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_HP;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_HP


-- [START]  Working on HOMEPAGE.NR_ENTRIES_DGR
reorg table HOMEPAGE.NR_ENTRIES_DGR;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME	

  FROM HOMEPAGE.DGR ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_DGR ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_DGR;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_DGR


-- [START]  Working on HOMEPAGE.NR_ENTRIES_FILE
reorg table HOMEPAGE.NR_ENTRIES_FILE;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME	

  FROM HOMEPAGE.FILE ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_FILE ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_FILE;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_FILE


-- [START]  Working on HOMEPAGE.NR_ENTRIES_FRM
reorg table HOMEPAGE.NR_ENTRIES_FRM;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
)
 SELECT 
  	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, ' ' MESSAGE, ' ' PREVIEW_IMAGE_URL, '  ' JSON_META_DATA, CREATION_DATE EVENT_TIME

  FROM HOMEPAGE.FRM ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_ENTRIES_FRM ( 
 	 ENTRY_ID, SOURCE, SOURCE_TYPE, CONTAINER_ID, CONTAINER_NAME, CONTAINER_URL, ITEM_ID, 
 	 ITEM_NAME, ITEM_URL, CREATION_DATE, UPDATE_DATE, TAGS, N_COMMENTS, N_RECCOMANDATIONS, 
 	 N_ATTACHMENTS, BRIEF_DESC, LAST_RECOMMENDER_ID, LAST_DATE_RECOMMENDER_ID, PREV_RECOMMENDER_ID, 
 	 PREV_DATE_RECOMMENDER_ID, LAST_COMMENT_ID, LAST_DATE_COMMENT, LAST_DESC_COMMENT, LAST_AUTHOR_COMMENT, 
 	 PREV_COMMENT_ID, PREV_DATE_COMMENT, PREV_DESC_COMMENT, PREV_AUTHOR_COMMENT, TARGET_SUBJECT_ID, 
 	 ITEM_ATOM_URL, MESSAGE, PREVIEW_IMAGE_URL, JSON_META_DATA, EVENT_TIME	
 
); 
commit; 

reorg table HOMEPAGE.NR_ENTRIES_FRM;
commit; 

-- [END]  Working on HOMEPAGE.NR_ENTRIES_FRM


--set integrity for HOMEPAGE.NR_ENTRIES_ACT all immediate unchecked;
--set integrity for HOMEPAGE.NR_ENTRIES_BLG all immediate unchecked;
--set integrity for HOMEPAGE.NR_ENTRIES_COM all immediate unchecked;
--set integrity for HOMEPAGE.NR_ENTRIES_WIK all immediate unchecked;
--set integrity for HOMEPAGE.NR_ENTRIES_PRF all immediate unchecked;
--set integrity for HOMEPAGE.NR_ENTRIES_HP all immediate unchecked;
--set integrity for HOMEPAGE.NR_ENTRIES_DGR all immediate unchecked;
--set integrity for HOMEPAGE.NR_ENTRIES_FILE all immediate unchecked;
--set integrity for HOMEPAGE.NR_ENTRIES_FRM all immediate unchecked;


commit;

DROP TABLE HOMEPAGE.ACT;
commit;

DROP TABLE HOMEPAGE.BLG;
commit;

DROP TABLE HOMEPAGE.COM;
commit;

DROP TABLE HOMEPAGE.WIK;
commit;

DROP TABLE HOMEPAGE.PRF;
commit;

DROP TABLE HOMEPAGE.HP;
commit;

DROP TABLE HOMEPAGE.DGR;
commit;

DROP TABLE HOMEPAGE.FILE;
commit;

DROP TABLE HOMEPAGE.FRM;
commit;
---------------------------------------------------------------
-- ADDING BACK THE CONSTRAINTS
---------------------------------------------------------------
-- HOMEPAGE.NR_ENTRIES_ACT
ALTER TABLE HOMEPAGE.NR_ENTRIES_ACT
    ADD CONSTRAINT PK_ACT_ENTRY_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_ACT_CONT
    ON HOMEPAGE.NR_ENTRIES_ACT (CONTAINER_ID);
    
COMMIT;

-- HOMEPAGE.NR_ENTRIES_BLG
ALTER TABLE HOMEPAGE.NR_ENTRIES_BLG
    ADD CONSTRAINT PK_BLG_ENTRY_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_BLG_CONT
    ON HOMEPAGE.NR_ENTRIES_BLG (CONTAINER_ID);
	
COMMIT;

-- HOMEPAGE.NR_ENTRIES_COM
ALTER TABLE HOMEPAGE.NR_ENTRIES_COM
    ADD CONSTRAINT PK_COM_ENTRY_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_COM_CONT
    ON HOMEPAGE.NR_ENTRIES_COM (CONTAINER_ID);
    
COMMIT;

-- HOMEPAGE.NR_ENTRIES_WIK
ALTER TABLE HOMEPAGE.NR_ENTRIES_WIK
    ADD CONSTRAINT PK_WIK_ENTRY_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_WIK_CONT
    ON HOMEPAGE.NR_ENTRIES_WIK (CONTAINER_ID);
    
COMMIT;

-- HOMEPAGE.NR_ENTRIES_PRF
ALTER TABLE HOMEPAGE.NR_ENTRIES_PRF
    ADD CONSTRAINT PK_PRF_ENTRY_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_PRF_CONT
    ON HOMEPAGE.NR_ENTRIES_PRF (CONTAINER_ID);
    
COMMIT;

-- HOMEPAGE.NR_ENTRIES_HP
ALTER TABLE HOMEPAGE.NR_ENTRIES_HP
    ADD CONSTRAINT PK_HP_ENTRY_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_HP_CONT
    ON HOMEPAGE.NR_ENTRIES_HP (CONTAINER_ID);
    
COMMIT;

-- HOMEPAGE.NR_ENTRIES_DGR
ALTER TABLE HOMEPAGE.NR_ENTRIES_DGR
    ADD CONSTRAINT PK_DGR_ENTRY_ID PRIMARY KEY(ENTRY_ID);
   
CREATE INDEX HOMEPAGE.NR_ENTRIES_DGR_CONT
    ON HOMEPAGE.NR_ENTRIES_DGR (CONTAINER_ID);

COMMIT;

-- HOMEPAGE.NR_ENTRIES_FILE
ALTER TABLE HOMEPAGE.NR_ENTRIES_FILE
    ADD CONSTRAINT PK_FILE_ENTRY_ID PRIMARY KEY(ENTRY_ID);
   
CREATE INDEX HOMEPAGE.NR_ENTRIES_FILE_CONT
    ON HOMEPAGE.NR_ENTRIES_FILE (CONTAINER_ID);
    
COMMIT;

-- HOMEPAGE.NR_ENTRIES_FRM
ALTER TABLE HOMEPAGE.NR_ENTRIES_FRM
    ADD CONSTRAINT PK_FRM_ENTRY_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_FRM_CONT
    ON HOMEPAGE.NR_ENTRIES_FRM (CONTAINER_ID);
	
COMMIT;

--------------------------------------------------------
-- ADDING BACK FK RELETIONSHIP FROM SOURCE TABLE TO ENTRY TABLES
--------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_SRC_STORIES_ACT
  	ADD CONSTRAINT FK_ENTRY_ID_ACT FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_ACT (ENTRY_ID);   

COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_BLG
  	ADD CONSTRAINT FK_ENTRY_ID_BLG FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_BLG (ENTRY_ID);          

COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_COM
  	ADD CONSTRAINT FK_ENTRY_ID_COM FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_COM (ENTRY_ID);   
	
COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_WIK
  	ADD CONSTRAINT FK_ENTRY_ID_WIK FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_WIK (ENTRY_ID);      

COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_PRF
  	ADD CONSTRAINT FK_ENTRY_ID_PRF FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_PRF (ENTRY_ID);         

COMMIT;


ALTER TABLE HOMEPAGE.NR_SRC_STORIES_HP
  	ADD CONSTRAINT FK_ENTRY_ID_HP FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_HP (ENTRY_ID);          

COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_DGR
  	ADD CONSTRAINT FK_ENTRY_ID_DGR FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_DGR (ENTRY_ID);  
	
COMMIT;    

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FILE
  	ADD CONSTRAINT FK_ENTRY_ID_FILE FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_FILE (ENTRY_ID);        

COMMIT;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_FRM
  	ADD CONSTRAINT FK_ENTRY_ID_FRM FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_FRM (ENTRY_ID);      

COMMIT;	

ALTER TABLE HOMEPAGE.NR_NEWS_PRF_COMMENT
  	ADD CONSTRAINT FK_ENTRY_ID FOREIGN KEY (ITEM_CORRELATION_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_PRF (ENTRY_ID);

COMMIT;	
	
--------------------------------------------------------
-- [END] UPDATING NR_ENTRIES TABLES
--------------------------------------------------------


---------------------------------------------
-- Adding VERB and USE_IN_ROLLUP columns to the readers tables
---------------------------------------------
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_STORIES
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;
	

COMMIT;

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;
	
COMMIT;

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;	

COMMIT;

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ADD  		USE_IN_ROLLUP 		SMALLINT
	ADD			IS_NETWORK			SMALLINT
	ADD			IS_FOLLOWER			SMALLINT
	ADD			EVENT_TIME 			TIMESTAMP;

COMMIT;

-----------------------------------------------------------
-- ADDING A NR_STATUS_UPDATE_READER
-----------------------------------------------------------
-- Adding four new categories for ui rendering of actianable stories (we don't need to add source here as they already exist)
INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('status_update_x8b0bx51af2ddef2cd', 11, '%status_update', 'status_update');

--------------------------------------------------------------------------
-- 11) HOMEPAGE.NR_STATUS_UPDATE_READERS
--------------------------------------------------------------------------	
CREATE TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	USE_IN_ROLLUP SMALLINT,
	IS_NETWORK	SMALLINT,
	IS_FOLLOWER	SMALLINT,
	EVENT_TIME TIMESTAMP,
   	CONSTRAINT  CK_CAT11_TYPE
    			CHECK
    			(CATEGORY_TYPE = 11)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS 
    ADD CONSTRAINT PK_SU_READERS PRIMARY KEY(FOLLOWED_STORY_ID);

CREATE INDEX HOMEPAGE.SU_STORIES_IDX
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.SU_STORIES_SIDX
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (STORY_ID);

CREATE INDEX HOMEPAGE.SU_STORIES_ITEM_ID
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ITEM_ID);

CREATE INDEX HOMEPAGE.SU_STORIES_READER_STORY
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID);	

COMMIT;



---------------------------------------------------------
-- [START] THIRD PARTY EVENTS HANDLING CHANGES
---------------------------------------------------------
----------------------------------------------------------
-- Adding ACTIVITY_META_DATA to NR_STORIES_CONTENT table
----------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT
	ADD ACTIVITY_META_DATA CLOB;

COMMIT;
----------------------------------------------------------

---------------------------------------------------------------------------------
-- INSERTING THIRD PARTY CATEGORIES AND SOURCES
---------------------------------------------------------------------------------
-- Adding a new category (used from UI rendering) and source (used a source of stories from component)
INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('ext_9cax4cc4x8b0bx51af2ddef2cd', 12, '%external', 'external');

INSERT INTO HOMEPAGE.NR_SOURCE_TYPE (SOURCE_TYPE_ID, SOURCE_TYPE, SOURCE_TYPE_NAME, SOURCE_TYPE_DESC, IS_ENABLE)
VALUES ('ext_____fdfdc9cax80bx51af2', 100, '%external', 'external', 0);

---------------------------------------------------------
-- 12) ADDING A NR_EXTERNAL_READERS READER TABLE
---------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_EXTERNAL_READERS (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	USE_IN_ROLLUP SMALLINT,
	IS_NETWORK	SMALLINT,
	IS_FOLLOWER	SMALLINT,
	EVENT_TIME TIMESTAMP,
   	CONSTRAINT  CK_CAT12_TYPE
    			CHECK
    			(CATEGORY_TYPE = 12)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS 
    ADD CONSTRAINT PK_EXT_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);
    
CREATE INDEX HOMEPAGE.EXT_STORIES_IDX
    ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.EXT_STORIES_SIDX
    ON HOMEPAGE.NR_EXTERNAL_READERS (STORY_ID);

CREATE INDEX HOMEPAGE.EXT_STORIES_ITEM_ID
    ON HOMEPAGE.NR_EXTERNAL_READERS (ITEM_ID);

CREATE INDEX HOMEPAGE.EXT_STORIES_READER_STORY
    ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID);    



--------------------------------------------------------------
-- ADDING A NR_ENTRIES_EXTERNAL TABLE
--------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ENTRIES_EXTERNAL  (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36) NOT NULL,
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	CREATION_DATE TIMESTAMP NOT NULL,
	UPDATE_DATE TIMESTAMP NOT NULL,
	TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT 0 NOT NULL,
	N_RECCOMANDATIONS SMALLINT DEFAULT 0 NOT NULL,
	N_ATTACHMENTS SMALLINT DEFAULT 0 NOT NULL,
	BRIEF_DESC VARCHAR(512),
	LAST_RECOMMENDER_ID VARCHAR(36),
	LAST_DATE_RECOMMENDER_ID TIMESTAMP,
	PREV_RECOMMENDER_ID VARCHAR(36),
	PREV_DATE_RECOMMENDER_ID TIMESTAMP,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_DESC_COMMENT VARCHAR(256),
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_DESC_COMMENT VARCHAR(256),
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	MESSAGE VARCHAR(4000),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	EVENT_TIME TIMESTAMP,
	CONSTRAINT   	CK_ENT_SRC10_TYPE
    				CHECK
    				(SOURCE_TYPE = 10)
)
IN NEWS32TABSPACE;

ALTER TABLE HOMEPAGE.NR_ENTRIES_EXTERNAL 
    ADD CONSTRAINT PK_EXT_ENTRY_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_EXT_CONT
    ON HOMEPAGE.NR_ENTRIES_EXTERNAL (CONTAINER_ID);
    
COMMIT;



----------------------------------------------------
-- ADDING A NR_SRC_STORIES_EXTERNAL TABLE
----------------------------------------------------
CREATE TABLE HOMEPAGE.NR_SRC_STORIES_EXTERNAL (
	STORY_ID VARCHAR(36) NOT NULL,
	EVENT_NAME VARCHAR(256) NOT NULL,
	SOURCE VARCHAR(36),
	CONTAINER_ID VARCHAR(256),	
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ATOM_URL VARCHAR(2048),
	ITEM_CORRELATION_ID VARCHAR(36),
	CREATION_DATE TIMESTAMP NOT NULL,
	BRIEF_DESC VARCHAR(512),
	ACTOR_UUID VARCHAR(36),
	EVENT_RECORD_UUID VARCHAR(36) NOT NULL,
	TAGS VARCHAR(1024),
	META_TEMPLATE VARCHAR(4096) DEFAULT '' NOT NULL,
	TEXT_META_TEMPLATE VARCHAR(1024),
	R_META_TEMPLATE VARCHAR(4096),
	R_TEXT_META_TEMPLATE VARCHAR(1024),
	IS_COMMUNITY_STORY SMALLINT DEFAULT 0,
	ITEM_CORRELATION_NAME VARCHAR(256),
	HAS_ATTACHMENT SMALLINT DEFAULT 0,
	SOURCE_TYPE SMALLINT,
	ENTRY_ID VARCHAR(36),
	MESSAGE VARCHAR(4000),
	EVENT_TIME TIMESTAMP,
	VERB VARCHAR (128),	
	CONSTRAINT   	CK_SRC100_TYPE
    				CHECK
    				(SOURCE_TYPE >= 100)
)
IN NEWS32TABSPACE;

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_EXTERNAL
    ADD CONSTRAINT PK_EXT_STORY_ID PRIMARY KEY(STORY_ID);

ALTER TABLE HOMEPAGE.NR_SRC_STORIES_EXTERNAL
  	ADD CONSTRAINT FK_ENTRY_ID_EXT FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.NR_ENTRIES_EXTERNAL (ENTRY_ID);    

CREATE INDEX HOMEPAGE.SRC_STORIES_EXT_DATE
	ON HOMEPAGE.NR_ENTRIES_EXTERNAL (CREATION_DATE DESC);

CREATE INDEX HOMEPAGE.SRC_EXT_CONTAINER_ID
    ON HOMEPAGE.NR_SRC_STORIES_EXTERNAL (CONTAINER_ID);

CREATE INDEX HOMEPAGE.SRC_EXT_ITEM_CORR_ID
    ON HOMEPAGE.NR_SRC_STORIES_EXTERNAL (ITEM_CORRELATION_ID);
    
CREATE INDEX HOMEPAGE.SRC_STORIES_EXT_EIDX
    ON HOMEPAGE.NR_SRC_STORIES_EXTERNAL (ENTRY_ID);  



---------------------------------------------------------
-- [END] THIRD PARTY EVENTS HANDLING CHANGES
---------------------------------------------------------


---------------------------------------------------------
-- [START] ACTIONABLE
---------------------------------------------------------
-- Adding four new categories for ui rendering of actianable stories
INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('actionable_saved_stories_4cc4x8b0bx', 13, '%actionable_saved_stories', 'actionable_saved_stories');

INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('actionable_directed_notification_bx', 14, '%actionable_directed_notification', 'actionable_directed_notification');

INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('actionable_todo_______cax4cc4x8b0bx', 15, '%actionable_todo', 'actionable_todo');

INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('actionable_action_required__4x8b0bx', 16, '%actionable_action_required', 'actionable_action_required');

COMMIT;


---------------------------------------------------------
-- ADDING NR_ACTIONABLE_READERS READER TABLE
---------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ACTIONABLE_READERS (
	ACTIONABLE_READER_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	USE_IN_ROLLUP SMALLINT,
	IS_NETWORK	SMALLINT,
	IS_FOLLOWER	SMALLINT,
	EVENT_TIME TIMESTAMP,
	NOTE_TEXT VARCHAR(4000),
	NOTE_UPDATE_DATE TIMESTAMP,
	CONSTRAINT   	CK_CAT_ACTION_TYPE
    				CHECK
    				(CATEGORY_TYPE >= 13 AND CATEGORY_TYPE <= 16)	
)
IN NEWS32TABSPACE;

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS 
    ADD CONSTRAINT PK_ACTION_STORIES PRIMARY KEY (ACTIONABLE_READER_ID);
    
CREATE INDEX HOMEPAGE.ACTION_READER_STORIES_IDX
    ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.ACTION_READER_SIDX
    ON HOMEPAGE.NR_ACTIONABLE_READERS (STORY_ID);

CREATE INDEX HOMEPAGE.ACTION_READER_ITEM_ID
    ON HOMEPAGE.NR_ACTIONABLE_READERS (ITEM_ID);

CREATE UNIQUE INDEX HOMEPAGE.ACTION_READER_STORY
    ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, STORY_ID);    

    
    


COMMIT;

---------------------------------------------------------
-- ADDING NR_ACTIONABLE_STORIES TABLE
---------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ACTIONABLE_STORIES (
	STORY_ID VARCHAR(36) NOT NULL,
	EVENT_NAME VARCHAR(256) NOT NULL,
	SOURCE VARCHAR(36),
	CONTAINER_ID VARCHAR(256),	
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ATOM_URL VARCHAR(2048),
	ITEM_CORRELATION_ID VARCHAR(36), -- NEW	
	CREATION_DATE TIMESTAMP NOT NULL,
	BRIEF_DESC VARCHAR(512),
	ACTOR_UUID VARCHAR(36),
	EVENT_RECORD_UUID VARCHAR(36) NOT NULL,
	TAGS VARCHAR(1024),
	META_TEMPLATE VARCHAR(4096) DEFAULT '' NOT NULL,
	TEXT_META_TEMPLATE VARCHAR(1024),
	R_META_TEMPLATE VARCHAR(4096),
	R_TEXT_META_TEMPLATE VARCHAR(1024),
	IS_COMMUNITY_STORY SMALLINT DEFAULT 0,
	ITEM_CORRELATION_NAME VARCHAR(256),
	HAS_ATTACHMENT SMALLINT DEFAULT 0,
	SOURCE_TYPE SMALLINT,
	ENTRY_ID VARCHAR(36),
	MESSAGE VARCHAR(4000),
	EVENT_TIME TIMESTAMP,
	VERB VARCHAR (128),
	CONSTRAINT   	CK_SRC_ACTION_TYPE
    				CHECK
    				(SOURCE_TYPE >= 1 AND SOURCE_TYPE <= 10 )
)
IN NEWS32TABSPACE;

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_STORIES
    ADD CONSTRAINT PK_ACTION_STORY_ID PRIMARY KEY(STORY_ID);

CREATE INDEX HOMEPAGE.ACTION_CONTAINER_ID
    ON HOMEPAGE.NR_ACTIONABLE_STORIES (CONTAINER_ID);

CREATE INDEX HOMEPAGE.ACTION_ITEM_CORR_ID
    ON HOMEPAGE.NR_ACTIONABLE_STORIES (ITEM_CORRELATION_ID);

CREATE INDEX HOMEPAGE.ACTION_ACT_ENTRYID
    ON HOMEPAGE.NR_ACTIONABLE_STORIES (ENTRY_ID);    




COMMIT;
	
---------------------------------------------------------
-- [END] ACTIONABLE
---------------------------------------------------------

DROP VIEW HOMEPAGE.NR_CATEGORIES_READERS;
    
--------------------------------------------------------------------------------------------------------------
-- CREATE THE VIEW FOR ALL THE STORIES
--------------------------------------------------------------------------------------------------------------
CREATE VIEW HOMEPAGE.NR_CATEGORIES_READERS AS (
    SELECT * FROM HOMEPAGE.NR_RESPONSES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_PROFILES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_COMMUNITIES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ACTIVITIES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_BLOGS_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_BOOKMARKS_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_FILES_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_FORUMS_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_WIKIS_READERS
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_TAGS_READERS
    	UNION ALL
    SELECT * FROM HOMEPAGE.NR_STATUS_UPDATE_READERS
    	UNION ALL
	SELECT * FROM HOMEPAGE.NR_EXTERNAL_READERS    	
);

