-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

--------------------------------------------------
-- ADDING COLUMN ITEM_CORRELATION_NAME TO NR_STORIES
--------------------------------------------------
ALTER TABLE HOMEPAGE.NR_STORIES
    ADD COLUMN ITEM_CORRELATION_NAME VARCHAR(256);
    
--------------------------------------------------------------------------
-- 1 NR_RESPONSES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_RESPONSES_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   	CK_CAT1_TYPE
    				CHECK
    				(CATEGORY_TYPE = 1)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_RESPONSES_STORIES 
    ADD CONSTRAINT PK_RESP_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_RESPONSES_STORIES
    ADD CONSTRAINT FK_RESP_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.RESPONSES_STORIES_IDX
    ON HOMEPAGE.NR_RESPONSES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.RESPONSES_STORIES_CIDX
    ON HOMEPAGE.NR_RESPONSES_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.RESPONSES_STORIES_SIDX
    ON HOMEPAGE.NR_RESPONSES_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_RESPONSES_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 2 NR_PROFILES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_PROFILES_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   	CK_CAT2_TYPE
    				CHECK
    				(CATEGORY_TYPE = 2)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_PROFILES_STORIES 
    ADD CONSTRAINT PK_PROF_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_PROFILES_STORIES
    ADD CONSTRAINT FK_PROF_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.PROFILES_STORIES_IDX
    ON HOMEPAGE.NR_PROFILES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.PROFILES_STORIES_CIDX
    ON HOMEPAGE.NR_PROFILES_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.PROFILES_STORIES_SIDX
    ON HOMEPAGE.NR_PROFILES_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_PROFILES_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 3 NR_COMMUNITIES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_COMMUNITIES_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   	CK_CAT3_TYPE
    				CHECK
    				(CATEGORY_TYPE = 3)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_STORIES 
    ADD CONSTRAINT PK_COMM_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_STORIES
    ADD CONSTRAINT FK_COM_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.COMMUNITIES_STORIES_IDX
    ON HOMEPAGE.NR_COMMUNITIES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.COMMUNITIES_STORIES_CIDX
    ON HOMEPAGE.NR_COMMUNITIES_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.COMMUNITIES_STORIES_SIDX
    ON HOMEPAGE.NR_COMMUNITIES_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_COMMUNITIES_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 4 NR_ACTIVITIES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ACTIVITIES_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   		CK_CAT4_TYPE
    					CHECK
    					(CATEGORY_TYPE = 4)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_STORIES 
    ADD CONSTRAINT PK_ACT_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_STORIES
    ADD CONSTRAINT FK_ACT_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.ACTIVITIES_STORIES_IDX
    ON HOMEPAGE.NR_ACTIVITIES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.ACTIVITIES_STORIES_CIDX
    ON HOMEPAGE.NR_ACTIVITIES_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.ACTIVITIES_STORIES_SIDX
    ON HOMEPAGE.NR_ACTIVITIES_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_ACTIVITIES_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 5 NR_BLOGS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_BLOGS_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   		CK_CAT5_TYPE
    					CHECK
    					(CATEGORY_TYPE = 5)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_BLOGS_STORIES 
    ADD CONSTRAINT PK_BLOGS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_BLOGS_STORIES
    ADD CONSTRAINT FK_BLOGS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.BLOGS_STORIES_IDX
    ON HOMEPAGE.NR_BLOGS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.BLOGS_STORIES_CIDX
    ON HOMEPAGE.NR_BLOGS_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.BLOGS_STORIES_SIDX
    ON HOMEPAGE.NR_BLOGS_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_BLOGS_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 6 NR_BOOKMARKS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_BOOKMARKS_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   	CK_CAT6_TYPE
    				CHECK
    				(CATEGORY_TYPE = 6)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_STORIES 
    ADD CONSTRAINT PK_BOOKS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_STORIES
    ADD CONSTRAINT FK_BOOKS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.BOOKMARKS_STORIES_IDX
    ON HOMEPAGE.NR_BOOKMARKS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.BOOKMARKS_STORIES_CIDX
    ON HOMEPAGE.NR_BOOKMARKS_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.BOOKMARKS_STORIES_SIDX
    ON HOMEPAGE.NR_BOOKMARKS_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_BOOKMARKS_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 7 NR_FILES_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_FILES_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   		CK_CAT7_TYPE
    					CHECK
    					(CATEGORY_TYPE = 7)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_FILES_STORIES 
    ADD CONSTRAINT PK_FILES_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_FILES_STORIES
    ADD CONSTRAINT FK_FILES_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.FILES_STORIES_IDX
    ON HOMEPAGE.NR_FILES_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.FILES_STORIES_CIDX
    ON HOMEPAGE.NR_FILES_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.FILES_STORIES_SIDX
    ON HOMEPAGE.NR_FILES_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_FILES_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 8 NR_FORUMS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_FORUMS_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   	CK_CAT8_TYPE
    				CHECK
    				(CATEGORY_TYPE = 8)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_FORUMS_STORIES 
    ADD CONSTRAINT PK_FORUMS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_FORUMS_STORIES
    ADD CONSTRAINT FK_FORUMS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.FORUMS_STORIES_IDX
    ON HOMEPAGE.NR_FORUMS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.FORUMS_STORIES_CIDX
    ON HOMEPAGE.NR_FORUMS_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.FORUMS_STORIES_SIDX
    ON HOMEPAGE.NR_FORUMS_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_FORUMS_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 9 NR_WIKIS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_WIKIS_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   	CK_CAT9_TYPE
    				CHECK
    				(CATEGORY_TYPE = 9)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_WIKIS_STORIES 
    ADD CONSTRAINT PK_WIKIS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_WIKIS_STORIES
    ADD CONSTRAINT FK_WIKIS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.WIKIS_STORIES_IDX
    ON HOMEPAGE.NR_WIKIS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.WIKIS_STORIES_CIDX
    ON HOMEPAGE.NR_WIKIS_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.WIKIS_STORIES_SIDX
    ON HOMEPAGE.NR_WIKIS_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_WIKIS_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------
-- 10 NR_WIKIS_STORIES
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_TAGS_STORIES (
	FOLLOWED_STORY_ID VARCHAR(36) NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	CONSTRAINT   	CK_CAT10_TYPE
    				CHECK
    				(CATEGORY_TYPE = 10)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_TAGS_STORIES 
    ADD CONSTRAINT PK_TAGS_STORIES PRIMARY KEY(FOLLOWED_STORY_ID);

ALTER TABLE HOMEPAGE.NR_TAGS_STORIES
    ADD CONSTRAINT FK_TAGS_STORY_ID FOREIGN KEY (STORY_ID)
    REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);

CREATE INDEX HOMEPAGE.TAGS_STORIES_IDX
    ON HOMEPAGE.NR_TAGS_STORIES (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.TAGS_STORIES_CIDX
    ON HOMEPAGE.NR_TAGS_STORIES (CATEGORY_TYPE);

CREATE INDEX HOMEPAGE.TAGS_STORIES_SIDX
    ON HOMEPAGE.NR_TAGS_STORIES (STORY_ID);

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_TAGS_STORIES TO USER LCUSER;

COMMIT;

--------------------------------------------------------------------------------------------------------------
-- RENAME THE ORIGINAL TABLE SO WE CAN USE THE VIEW NAME TO REFERENCE FROM THE CODE THE NEW SET OF TABLES
--------------------------------------------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_FOLLOWED_STORIES DROP FOREIGN KEY FK_F_STORY_ID;

RENAME TABLE HOMEPAGE.NR_FOLLOWED_STORIES TO FOLLOWED_STORIES_ORIGINAL;

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.FOLLOWED_STORIES_ORIGINAL TO USER LCUSER;

--------------------------------------------------------------------------------------------------------------
-- CREATE THE VIEW FOR ALL THE STORIES
--------------------------------------------------------------------------------------------------------------
CREATE VIEW HOMEPAGE.NR_FOLLOWED_STORIES AS (
    SELECT * FROM HOMEPAGE.NR_RESPONSES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_PROFILES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_COMMUNITIES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_ACTIVITIES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_BLOGS_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_BOOKMARKS_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_FILES_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_FORUMS_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_WIKIS_STORIES
        UNION ALL
    SELECT * FROM HOMEPAGE.NR_TAGS_STORIES
);

--ALTER VIEW HOMEPAGE.NR_FOLLOWED_STORIES ENABLE QUERY OPTIMIZATION;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.NR_FOLLOWED_STORIES TO USER LCUSER;

COMMIT;

------------------------------------------------------------------------------------------------------
-- MOVING BACK DATA
------------------------------------------------------------------------------------------------------

----------------------------
-- 1 NR_RESPONSES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 1;

COMMIT;

INSERT INTO HOMEPAGE.NR_RESPONSES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 1;

COMMIT;

----------------------------
-- 2 NR_PROFILES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 2;

COMMIT;

INSERT INTO HOMEPAGE.NR_PROFILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 2;

COMMIT;

----------------------------
-- 3 NR_COMMUNITIES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 3;

COMMIT;

INSERT INTO HOMEPAGE.NR_COMMUNITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 3;

COMMIT;

----------------------------
-- 4 NR_ACTIVITIES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 4;

COMMIT;

INSERT INTO HOMEPAGE.NR_ACTIVITIES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 4;

COMMIT;

----------------------------
-- 5 NR_BLOGS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 5;

COMMIT;

INSERT INTO HOMEPAGE.NR_BLOGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 5;

COMMIT;

----------------------------
-- 6 NR_BOOKMARKS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 6;

COMMIT;

INSERT INTO HOMEPAGE.NR_BOOKMARKS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 6;

COMMIT;

----------------------------
-- 7 NR_FILES_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 7;

COMMIT;

INSERT INTO HOMEPAGE.NR_FILES_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 7;

COMMIT;

----------------------------
-- 8 NR_FORUMS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 8;

COMMIT;

INSERT INTO HOMEPAGE.NR_FORUMS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 8;

COMMIT;

----------------------------
-- 9 NR_WIKIS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 9;

COMMIT;

INSERT INTO HOMEPAGE.NR_WIKIS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 9;

COMMIT;

----------------------------
-- 10 NR_TAGS_STORIES
----------------------------
INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '0%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '1%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '2%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '3%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '4%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '5%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '6%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '7%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '8%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE '9%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'a%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'b%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'c%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'd%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'e%' AND CATEGORY_TYPE = 10;

COMMIT;

INSERT INTO HOMEPAGE.NR_TAGS_STORIES SELECT * FROM HOMEPAGE.FOLLOWED_STORIES_ORIGINAL WHERE FOLLOWED_STORY_ID LIKE 'f%' AND CATEGORY_TYPE = 10;

COMMIT;

------------------------------------
-- DROP TEMP TABLE
------------------------------------
DROP TABLE HOMEPAGE.FOLLOWED_STORIES_ORIGINAL;

COMMIT;

--------------------------------------------------------------------------------------------------------
-- REORG AND RUNSTATS
--------------------------------------------------------------------------------------------------------
reorg table HOMEPAGE.NR_RESPONSES_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_RESPONSES_STORIES;
runstats on table HOMEPAGE.NR_RESPONSES_STORIES;
runstats on table HOMEPAGE.NR_RESPONSES_STORIES with distribution and detailed indexes all allow write access;

reorg table HOMEPAGE.NR_PROFILES_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_PROFILES_STORIES;
runstats on table HOMEPAGE.NR_PROFILES_STORIES;
runstats on table HOMEPAGE.NR_PROFILES_STORIES with distribution and detailed indexes all allow write access;

reorg table HOMEPAGE.NR_COMMUNITIES_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_COMMUNITIES_STORIES;
runstats on table HOMEPAGE.NR_COMMUNITIES_STORIES;
runstats on table HOMEPAGE.NR_COMMUNITIES_STORIES with distribution and detailed indexes all allow write access;

reorg table HOMEPAGE.NR_ACTIVITIES_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_ACTIVITIES_STORIES;
runstats on table HOMEPAGE.NR_ACTIVITIES_STORIES;
runstats on table HOMEPAGE.NR_ACTIVITIES_STORIES with distribution and detailed indexes all allow write access;

reorg table HOMEPAGE.NR_BLOGS_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_BLOGS_STORIES;
runstats on table HOMEPAGE.NR_BLOGS_STORIES;
runstats on table HOMEPAGE.NR_BLOGS_STORIES with distribution and detailed indexes all allow write access;

reorg table HOMEPAGE.NR_BOOKMARKS_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_BOOKMARKS_STORIES;
runstats on table HOMEPAGE.NR_BOOKMARKS_STORIES;
runstats on table HOMEPAGE.NR_BOOKMARKS_STORIES with distribution and detailed indexes all allow write access;

reorg table HOMEPAGE.NR_FILES_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_FILES_STORIES;
runstats on table HOMEPAGE.NR_FILES_STORIES;
runstats on table HOMEPAGE.NR_FILES_STORIES with distribution and detailed indexes all allow write access;

reorg table HOMEPAGE.NR_FORUMS_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_FORUMS_STORIES;
runstats on table HOMEPAGE.NR_FORUMS_STORIES;
runstats on table HOMEPAGE.NR_FORUMS_STORIES with distribution and detailed indexes all allow write access;

reorg table HOMEPAGE.NR_WIKIS_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_WIKIS_STORIES;
runstats on table HOMEPAGE.NR_WIKIS_STORIES;
runstats on table HOMEPAGE.NR_WIKIS_STORIES with distribution and detailed indexes all allow write access;


reorg table HOMEPAGE.NR_TAGS_STORIES use NEWS4TMPTABSPACE;
reorg indexes all for table HOMEPAGE.NR_TAGS_STORIES;
runstats on table HOMEPAGE.NR_TAGS_STORIES;
runstats on table HOMEPAGE.NR_TAGS_STORIES with distribution and detailed indexes all allow write access;
