-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-----------------------------------------------------------------------------------
-- Remove NR_NEWS_PRF_COMMENT
-----------------------------------------------------------------------------------
DROP TABLE HOMEPAGE.NR_NEWS_PRF_COMMENT;

COMMIT;


-----------------------------------------------------------------------------------
-- Rename all the PK in the reader tables to be CATEGORY_READER_ID;
-----------------------------------------------------------------------------------
-- 1
ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;


--  [start] HOMEPAGE.NR_RESPONSES_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_RESPONSES_READERS ;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_RESPONSES_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_RESPONSES_READERS


ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS DROP CONSTRAINT PK_RESP_STORIES;
COMMIT;


ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT PK_RESP_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_RESPONSES_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_RESP_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_RESPONSES_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_RESP_READER_STORY 		
	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID);
COMMIT;

-- 2
ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--fix
--  [start] HOMEPAGE.NR_PROFILES_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_PROFILES_READERS ;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_PROFILES_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_PROFILES_READERS

ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS DROP CONSTRAINT PK_PROF_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT PK_PROF_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_PROFILES_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_PRO_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_PROFILES_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_PRO_READER_STORY 		
	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID);  
COMMIT;

-- 3
ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--  [start] HOMEPAGE.NR_COMMUNITIES_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_COMMUNITIES_READERS ;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_COMMUNITIES_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_COMMUNITIES_READERS

ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS DROP CONSTRAINT PK_COMM_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT PK_COMM_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_COMMUNITIES_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_COM_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_COMMUNITIES_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_COM_READER_STORY 		
	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID);
COMMIT;

-- 4
ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--  [start] HOMEPAGE.NR_ACTIVITIES_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_ACTIVITIES_READERS ;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_ACTIVITIES_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_ACTIVITIES_READERS

ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS DROP CONSTRAINT PK_ACT_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT PK_ACT_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_ACTIVITIES_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_ACT_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_ACTIVITIES_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_ACT_READER_STORY 		
	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID);
COMMIT;

-- 5
ALTER TABLE 	HOMEPAGE.NR_BLOGS_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--  [start] HOMEPAGE.NR_BLOGS_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_BLOGS_READERS;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_BLOGS_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_BLOGS_READERS

ALTER TABLE		HOMEPAGE.NR_BLOGS_READERS DROP CONSTRAINT PK_BLOGS_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT PK_BLOGS_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_BLOGS_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_BLOGS_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_BLG_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_BLOGS_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_BLG_READER_STORY 		
	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID);
COMMIT;

-- 6
ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--  [start] HOMEPAGE.NR_BOOKMARKS_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_BOOKMARKS_READERS;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_BOOKMARKS_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_BOOKMARKS_READERS

ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS  DROP CONSTRAINT PK_BOOKS_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT PK_BOOKS_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_BOOKMARKS_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_BOOK_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_BOOKMARKS_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_BOOK_READER_STORY 		
	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID);
COMMIT;

-- 7
ALTER TABLE 	HOMEPAGE.NR_FILES_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--  [start] HOMEPAGE.NR_FILES_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_FILES_READERS;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_FILES_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_FILES_READERS

ALTER TABLE 	HOMEPAGE.NR_FILES_READERS DROP CONSTRAINT PK_FILES_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT PK_FILES_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_FILES_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_FILES_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_FILES_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_FILES_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_FILES_READER_STORY 		
	ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID);
	
COMMIT;

-- 8
ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--  [start] HOMEPAGE.NR_FORUMS_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_FORUMS_READERS;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_FORUMS_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_FORUMS_READERS

ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS DROP CONSTRAINT PK_FORUMS_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT PK_FORUMS_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_FORUMS_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_FORUMS_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_FORUMS_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_FORUMS_READER_STORY 	
	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID);
COMMIT;

-- 9
ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--  [start] HOMEPAGE.NR_WIKIS_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_WIKIS_READERS ;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_WIKIS_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_WIKIS_READERS

ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS DROP CONSTRAINT PK_WIKIS_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT PK_WIKIS_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_WIKIS_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.NR_WIKIS_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_WIKIS_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.NR_WIKIS_READER_STORY 		
	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID);
COMMIT;

-- 10
ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--fix
--  [start] HOMEPAGE.NR_TAGS_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_TAGS_READERS;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_TAGS_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_TAGS_READERS

ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS DROP CONSTRAINT PK_TAGS_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT PK_TAGS_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_TAGS_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

--DROP INDEX HOMEPAGE.NR_TAGS_READER_STORY;
--COMMIT;

reorg table HOMEPAGE.NR_TAGS_READERS use NEWS4TMPTABSPACE;
COMMIT;

--CREATE UNIQUE INDEX HOMEPAGE.NR_TAGS_READER_STORY 		
--	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID);
--COMMIT;

-- 11 NR_STATUS_UPDATE_READERS
ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--  [start] HOMEPAGE.NR_STATUS_UPDATE_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_STATUS_UPDATE_READERS;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_STATUS_UPDATE_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_STATUS_UPDATE_READERS

ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT PK_SU_READERS;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT PK_SU_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_STATUS_UPDATE_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.SU_STORIES_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_STATUS_UPDATE_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.SU_STORIES_READER_STORY
    ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID);
COMMIT;

-- 12 NR_EXTERNAL_READERS
ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;
--fix

--  [start] HOMEPAGE.NR_EXTERNAL_READERS
EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID
 
)
 SELECT 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, FOLLOWED_STORY_ID CATEGORY_READER_ID 

  FROM HOMEPAGE.NR_EXTERNAL_READERS ;

IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 

) COMMITCOUNT 1000 
INSERT_UPDATE INTO HOMEPAGE.NR_EXTERNAL_READERS ( 
	FOLLOWED_STORY_ID, READER_ID, CATEGORY_TYPE, SOURCE, CONTAINER_ID, ITEM_ID,
	RESOURCE_TYPE, CREATION_DATE, STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER,
	EVENT_TIME, ROLLUP_ENTRY_ID, CATEGORY_READER_ID 
); 
commit; 
--  [end] HOMEPAGE.NR_EXTERNAL_READERS


ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT PK_EXT_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT PK_EXT_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS DROP COLUMN FOLLOWED_STORY_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_EXTERNAL_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

DROP INDEX HOMEPAGE.EXT_STORIES_READER_STORY;
COMMIT;

reorg table HOMEPAGE.NR_EXTERNAL_READERS use NEWS4TMPTABSPACE;
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.EXT_STORIES_READER_STORY
    ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID);
COMMIT;

-- 13-16 ACTIONABLE TABLES
ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT PK_ACTION_STORIES;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS ADD CATEGORY_READER_ID VARCHAR(36) NOT NULL DEFAULT ' ';
COMMIT;

--fix
UPDATE 			HOMEPAGE.NR_ACTIONABLE_READERS SET CATEGORY_READER_ID = ACTIONABLE_READER_ID;
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT PK_ACTION_READERS PRIMARY KEY(CATEGORY_READER_ID);
COMMIT;

ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS DROP COLUMN ACTIONABLE_READER_ID;
COMMIT;
ALTER TABLE 	HOMEPAGE.NR_ACTIONABLE_READERS ADD IS_STORY_COMM SMALLINT;
COMMIT;

reorg table HOMEPAGE.NR_ACTIONABLE_READERS;
COMMIT;

-------------------------------------------------------------------
-- Remove NR_ACTIONABLE_STORIES
-------------------------------------------------------------------
DROP TABLE HOMEPAGE.NR_ACTIONABLE_STORIES; 
COMMIT;



-------------------------------------------------------------------
-- TODO: Remove the 4 categories type, leave just one category (16)
-------------------------------------------------------------------

-- Add a category type: aggregated_readers
CREATE TABLE HOMEPAGE.NR_AGGREGATED_READERS (
	CATEGORY_READER_ID VARCHAR(36) DEFAULT ' ' NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	ROLLUP_ENTRY_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	USE_IN_ROLLUP SMALLINT,
	IS_NETWORK	SMALLINT,
	IS_FOLLOWER	SMALLINT,
	EVENT_TIME 	TIMESTAMP,
	IS_STORY_COMM SMALLINT
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
    ADD CONSTRAINT PK_AGG_READERS PRIMARY KEY(CATEGORY_READER_ID);

CREATE INDEX HOMEPAGE.NR_AGGREGATED_READERS_IDX
    ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE ASC, READER_ID);

CREATE INDEX HOMEPAGE.NR_AGGREGATED_READERS_STORY_ID
    ON HOMEPAGE.NR_AGGREGATED_READERS (STORY_ID);

CREATE INDEX HOMEPAGE.NR_AGGREGATED_READERS_ITEM_ID
    ON HOMEPAGE.NR_AGGREGATED_READERS (ITEM_ID);

CREATE INDEX HOMEPAGE.NR_AGGREGATED_READERS_DATE
    ON HOMEPAGE.NR_AGGREGATED_READERS (CREATION_DATE ASC);

CREATE UNIQUE INDEX HOMEPAGE.NR_AGG_READERS_UNQ
     ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, STORY_ID);    

   

-------------------------------------------------------------------    
-- MIGRATION FROM: NR_COMM_PERSON_STORIES -> NR_AGGREGATED_READERS
-------------------------------------------------------------------    
-- [START]  Working on HOMEPAGE.NR_AGGREGATED_READERS
reorg table HOMEPAGE.NR_AGGREGATED_READERS;
commit; 

EXPORT TO data.tmp.ixf OF IXF METHOD N ( 
 	 CATEGORY_READER_ID, READER_ID, CATEGORY_TYPE, SOURCE, 
  	 CONTAINER_ID, ITEM_ID, ROLLUP_ENTRY_ID, RESOURCE_TYPE, CREATION_DATE,  
  	 STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM 
 
)
 SELECT 
  	 COMM_PER_STORY_ID, COMM_PER_READER_ID, CATEGORY_TYPE, SOURCE, 
  	 CONTAINER_ID, ITEM_ID, ' ' ROLLUP_ENTRY_ID, RESOURCE_TYPE, CREATION_DATE,  
  	 STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM 

  FROM HOMEPAGE.NR_COMM_PERSON_STORIES ;



IMPORT FROM data.tmp.ixf OF IXF METHOD N ( 
 	 CATEGORY_READER_ID, READER_ID, CATEGORY_TYPE, SOURCE, 
  	 CONTAINER_ID, ITEM_ID, ROLLUP_ENTRY_ID, RESOURCE_TYPE, CREATION_DATE,  
  	 STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM 

) COMMITCOUNT 1000 
INSERT INTO HOMEPAGE.NR_AGGREGATED_READERS ( 
 	 CATEGORY_READER_ID, READER_ID, CATEGORY_TYPE, SOURCE, 
  	 CONTAINER_ID, ITEM_ID, ROLLUP_ENTRY_ID, RESOURCE_TYPE, CREATION_DATE,  
  	 STORY_ID, SOURCE_TYPE, USE_IN_ROLLUP, IS_NETWORK, IS_FOLLOWER, EVENT_TIME, IS_STORY_COMM 
 
); 
commit; 

reorg table HOMEPAGE.NR_AGGREGATED_READERS;
commit; 

-- [END]  Working on HOMEPAGE.NR_AGGREGATED_READERS


-- DROPPING PREV. TABLE
DROP TABLE HOMEPAGE.NR_COMM_PERSON_STORIES;

-------------------------------------------------------------------
-- Remove N_COMMENTS and N_RECOMMANDATIONS from BOARD_ENTRIES
-------------------------------------------------------------------
ALTER TABLE 	HOMEPAGE.BOARD_ENTRIES DROP COLUMN N_COMMENTS;
COMMIT;
ALTER TABLE 	HOMEPAGE.BOARD_ENTRIES DROP COLUMN N_RECOMMANDATIONS;
COMMIT;


reorg table HOMEPAGE.BOARD_ENTRIES;
COMMIT;

-------------------------------------------------------------------
-- BOARD_OBJECT_REFERENCE 
-------------------------------------------------------------------
DROP TABLE HOMEPAGE.BOARD_ATTACHMENTS;

CREATE TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE (
	OBJECT_ID VARCHAR(47) NOT NULL,
	ENTRY_ID VARCHAR(47) NOT NULL,
	DISPLAY_NAME VARCHAR(2048),
	IMAGE_NAME   VARCHAR(2048),
	NAME VARCHAR(1024),
	URL VARCHAR(2048),
	CONTENT VARCHAR(4000),
	IMAGE_URL VARCHAR(2048),
	SOURCE  VARCHAR(36),
	SOURCE_TYPE  SMALLINT,
	CREATION_DATE TIMESTAMP,
	MIME_TYPE VARCHAR(36),
	AUTHOR_ID VARCHAR(36),
	AUTHOR_DISPLAY_NAME VARCHAR(256)	
)
IN BOARD16TABSPACE;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE 
    ADD CONSTRAINT PK_BRD_OBJ_ID PRIMARY KEY(OBJECT_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT FK_BRD_OBJ_ENTRY FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT FK_BRD_AUTHOR_ID FOREIGN KEY (AUTHOR_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

CREATE INDEX HOMEPAGE.BRD_ENTRY_IDX
    ON HOMEPAGE.BOARD_OBJECT_REFERENCE (ENTRY_ID);

CREATE INDEX HOMEPAGE.BRD_AUTHOR_IDX
    ON HOMEPAGE.BOARD_OBJECT_REFERENCE (AUTHOR_ID);



COMMIT;


-----------------------------------------------
-- HOMEPAGE.NR_COMM_SETTINGS
-----------------------------------------------

CREATE TABLE HOMEPAGE.NR_COMM_SETTINGS (
	COMM_ID VARCHAR(36) NOT NULL,
	MICROBLOGGING_ENABLED SMALLINT,
	FLAGS VARCHAR(36)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS
    ADD CONSTRAINT PK_COMM_ID PRIMARY KEY(COMM_ID);
    
  

--------------------------------------------------------------------------
-- 17 HOMEPAGE.NR_DISCOVERY_VIEW
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_DISCOVERY_VIEW (
	CATEGORY_READER_ID VARCHAR(36)  DEFAULT ' ' NOT NULL,
	READER_ID VARCHAR(36),
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	ROLLUP_ENTRY_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	USE_IN_ROLLUP SMALLINT,
	IS_NETWORK	SMALLINT,
	IS_FOLLOWER	SMALLINT,
	EVENT_TIME 	TIMESTAMP,
	IS_STORY_COMM SMALLINT,
	CONSTRAINT   	CK_CAT17_TYPE
    			CHECK
    			(CATEGORY_TYPE = 17)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW 
    ADD CONSTRAINT PK_DISCOVERY_VIEW PRIMARY KEY(CATEGORY_READER_ID);

CREATE INDEX HOMEPAGE.DISCOVERY_STORIES_IDX
    ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, CREATION_DATE ASC);

CREATE INDEX HOMEPAGE.DISCOVERY_SIDX
    ON HOMEPAGE.NR_DISCOVERY_VIEW (STORY_ID);

CREATE INDEX HOMEPAGE.DISCOVERY_ITEM
    ON HOMEPAGE.NR_DISCOVERY_VIEW (ITEM_ID);

CREATE INDEX HOMEPAGE.DISCOVERY_STORIES_DATE
    ON HOMEPAGE.NR_DISCOVERY_VIEW (CREATION_DATE ASC);

CREATE UNIQUE INDEX HOMEPAGE.DISCOVERY_READER_STORY 		
	ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, STORY_ID);   



INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('discovery-view', 17, '%discovery', 'discovery');

COMMIT;
