-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

ALTER TABLE HOMEPAGE.NR_NEWS_RECORDS
    ALTER COLUMN CONTAINER_ID 
    SET DATA TYPE VARCHAR(256);

reorg table HOMEPAGE.NR_NEWS_RECORDS use NEWSTMPTABSPACE;

-- NEWS REPOSITORY
{DB2_GRANT_START} HOMEPAGE.NR_SOURCE {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_SUBSCRIPTION {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_NEWS_RECORDS {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_TEMPLATE {DB2_GRANT_STOP}

{DB2_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMGR {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_SCHEDULER_LMPR {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_SCHEDULER_TASK {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_SCHEDULER_TREG {DB2_GRANT_STOP}

{DB2_GRANT_START} HOMEPAGE.NR_CATEGORY_TYPE {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_NEWS_SAVED {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_NEWS_DISCOVERY {DB2_GRANT_STOP}

{DB2_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_NETWORK {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_COMMENT {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_NEWS_STATUS_CONTENT {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_NEWS_COMMENT_CONTENT {DB2_GRANT_STOP}

{DB2_GRANT_START} HOMEPAGE.NR_RESOURCE_TYPE  {DB2_GRANT_STOP}	
{DB2_GRANT_START} HOMEPAGE.NR_RESOURCE  {DB2_GRANT_STOP}  
{DB2_GRANT_START} HOMEPAGE.NR_FOLLOWS  {DB2_GRANT_STOP}	
{DB2_GRANT_START} HOMEPAGE.NR_COMM_FOLLOW  {DB2_GRANT_STOP}	  
{DB2_GRANT_START} HOMEPAGE.NR_ORGPERSON_FOLLOW  {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_STORIES  {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_FOLLOWED_STORIES  {DB2_GRANT_STOP}    
{DB2_GRANT_START} HOMEPAGE.NR_COMM_STORIES  {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_ORGPERSON_STORIES  {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_STORIES_CONTENT  {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.NR_NETWORK  {DB2_GRANT_STOP}	

{DB2_GRANT_START} HOMEPAGE.EMD_FREQUENCY_TYPE {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.EMD_RESOURCE_PREF {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.EMD_TRANCHE {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.EMD_TRANCHE_INFO {DB2_GRANT_STOP}
{DB2_GRANT_START} HOMEPAGE.EMD_EMAIL_PREFS {DB2_GRANT_STOP}
	    


