-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

---------------------------------------------------------------------------------
------------------------ START NEWS FIXUP 101 -----------------------------------
---------------------------------------------------------------------------------

ALTER TABLE HOMEPAGE.BOARD_COMMENTS
	ADD COLUMN TAGS VARCHAR(1024);
COMMIT; 

reorg table HOMEPAGE.BOARD_COMMENTS;

COMMIT;


ALTER TABLE HOMEPAGE.BOARD_ENTRIES
	DROP COLUMN CONTAINER_NAME;
COMMIT; 

reorg table HOMEPAGE.BOARD_ENTRIES;

COMMIT;


ALTER TABLE HOMEPAGE.NR_ENTRIES
	ADD COLUMN LAST_UPDATE_RECORD TIMESTAMP 
	DROP COLUMN TARGET_SUBJECT_ID;
COMMIT; 

reorg table HOMEPAGE.NR_ENTRIES;

COMMIT;


ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ADD COLUMN LAST_UPDATE_RECORD TIMESTAMP 
	DROP COLUMN TARGET_SUBJECT_ID;
COMMIT; 

reorg table HOMEPAGE.NR_ENTRIES_ARCHIVE;

COMMIT;


ALTER TABLE HOMEPAGE.NR_STORIES
	ADD COLUMN CONTAINER_ATOM_URL VARCHAR(2048);
COMMIT; 

reorg table HOMEPAGE.NR_STORIES;

COMMIT;


ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS 
	ADD COLUMN STAT_UPDATE_DATE TIMESTAMP;
COMMIT; 

reorg table HOMEPAGE.NR_AS_CONTENT_INDEX_STATS;

COMMIT;


ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST 
	DROP COLUMN EVENT_RECORD_UUID;
COMMIT; 

reorg table HOMEPAGE.NR_AS_SEEDLIST;

COMMIT;

-------------------------------------------------------------------------
-- Insert repost author templates
-------------------------------------------------------------------------

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('itemAuthor-wPldKwZTaR7aAiPFw4L08CyRW','Author', 'asItemAuthor','profilePhoto', 1);

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('itemauthor-wPldKwZTaR7aAiPFw4L08CyRW','author', 'asItemAuthor','profilePhoto',  1);

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('itemCorrAuthorkla9034jl89vasgf3k5Wfd','correlationItemAuthor', 'correlationItemAuthor','profilePhoto',  1);

COMMIT;


-------------------------------------------------------------------------
-- Fix SOURCE TYPE data
-------------------------------------------------------------------------

UPDATE HOMEPAGE.NR_SOURCE_TYPE SET IMAGE_URL_SSL = IMAGE_URL;

COMMIT;

---------------------------------------------------------------------------------
-- 36 -> 256
---------------------------------------------------------------------------------


ALTER TABLE HOMEPAGE.NR_ENTRIES
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_CORRELATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN LAST_COMMENT_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN PREV_COMMENT_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_AUTHOR_UUID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_CORRELATION_AUTHOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_CORRELATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN LAST_COMMENT_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN PREV_COMMENT_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_AUTHOR_UUID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_CORRELATION_AUTHOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_STORIES
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_CORRELATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_AUTHOR_UUID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ITEM_CORRELATION_AUTHOR_UUID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;


ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;


ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_SAVED_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

ALTER TABLE HOMEPAGE.NR_TOPICS_READERS
	ALTER COLUMN ITEM_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_ENTRY_ID SET DATA TYPE VARCHAR(256) 
	ALTER COLUMN ORGANIZATION_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ROLLUP_AUTHOR_ID SET DATA TYPE VARCHAR(256)
	ALTER COLUMN ACTOR_UUID SET DATA TYPE VARCHAR(256);

COMMIT;

---------------------------------------------------------------------------------
-- READER TABLES: MAKE INDEX ON READER_ID,STORY_ID CLUSTER
---------------------------------------------------------------------------------

DROP INDEX HOMEPAGE.AGGREGATED_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.AGGREGATED_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RDR_STR
ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_CL_RDR_IX
ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.RESPONSES_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.RESPONSES_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_RDR_STR
ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_CL_RDR_IX
ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.PROFILES_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.PROFILES_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.PROFILES_READERS_RDR_STR
ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.PROFILES_READERS_CL_RDR_IX
ON HOMEPAGE.NR_PROFILES_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.COMM_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.COMM_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.COMM_READERS_RDR_STR
ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.COMM_READERS_CL_RDR_IX
ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.ACTIVITIES_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.ACTIVITIES_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_RDR_STR
ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_CL_RDR_IX
ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.BLOGS_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.BLOGS_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.BLOGS_READERS_RDR_STR
ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.BLOGS_READERS_CL_RDR_IX
ON HOMEPAGE.NR_BLOGS_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.BOOKMARKS_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.BOOKMARKS_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_RDR_STR
ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_CL_RDR_IX
ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.FILES_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.FILES_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.FILES_READERS_RDR_STR
ON HOMEPAGE.NR_FILES_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.FILES_READERS_CL_RDR_IX
ON HOMEPAGE.NR_FILES_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.FORUMS_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.FORUMS_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.FORUMS_READERS_RDR_STR
ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.FORUMS_READERS_CL_RDR_IX
ON HOMEPAGE.NR_FORUMS_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.WIKIS_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.WIKIS_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.WIKIS_READERS_RDR_STR
ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.WIKIS_READERS_CL_RDR_IX
ON HOMEPAGE.NR_WIKIS_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.TAGS_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.TAGS_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.TAGS_READERS_RDR_STR
ON HOMEPAGE.NR_TAGS_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.TAGS_READERS_CL_RDR_IX
ON HOMEPAGE.NR_TAGS_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.STATUS_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.STATUS_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.STATUS_READERS_RDR_STR
ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.STATUS_READERS_CL_RDR_IX
ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.EXTERNAL_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.EXTERNAL_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_RDR_STR
ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_CL_RDR_IX
ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.ACTIONABLE_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.ACTIONABLE_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_RDR_STR
ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_CL_RDR_IX
ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.DISCOVERY_VIEW_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.DISCOVERY_VIEW_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_RDR_STR
ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_CL_RDR_IX
ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.PROFILES_VIEW_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.PROFILES_VIEW_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_RDR_STR
ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_CL_RDR_IX
ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.NOTIFICA_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.NOTIFICA_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_RDR_STR
ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_CL_RDR_IX
ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.NOT_REC_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.NOT_REC_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_RDR_STR
ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_CL_RDR_IX
ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.SAVED_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.SAVED_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.SAVED_READERS_RDR_STR
ON HOMEPAGE.NR_SAVED_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.SAVED_READERS_CL_RDR_IX
ON HOMEPAGE.NR_SAVED_READERS (READER_ID);
COMMIT;


DROP INDEX HOMEPAGE.TOPICS_READERS_RDR_STR;
COMMIT;

DROP INDEX HOMEPAGE.TOPICS_READERS_CL_RDR_IX;
COMMIT;

CREATE  INDEX HOMEPAGE.TOPICS_READERS_RDR_STR
ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, STORY_ID) CLUSTER;
COMMIT;

CREATE  INDEX HOMEPAGE.TOPICS_READERS_CL_RDR_IX
ON HOMEPAGE.NR_TOPICS_READERS (READER_ID);
COMMIT;

----------------------------------------------------------------------------
--  Add new index to READER tables
----------------------------------------------------------------------------

CREATE  INDEX HOMEPAGE.AGGREGATED_READERS_RIR_IX
 	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.RESPONSES_READERS_RIR_IX
 	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.PROFILES_READERS_RIR_IX
 	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.COMM_READERS_RIR_IX
 	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.ACTIVITIES_READERS_RIR_IX
 	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.BLOGS_READERS_RIR_IX
 	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.BOOKMARKS_READERS_RIR_IX
 	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.FILES_READERS_RIR_IX
 	ON HOMEPAGE.NR_FILES_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.FORUMS_READERS_RIR_IX
 	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.WIKIS_READERS_RIR_IX
 	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.TAGS_READERS_RIR_IX
 	ON HOMEPAGE.NR_TAGS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.STATUS_READERS_RIR_IX
 	ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.EXTERNAL_READERS_RIR_IX
 	ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.ACTIONABLE_READERS_RIR_IX
 	ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.DISCOVERY_VIEW_RIR_IX
 	ON HOMEPAGE.NR_DISCOVERY_VIEW (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.PROFILES_VIEW_RIR_IX
 	ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.NOTIFICA_READERS_RIR_IX
 	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.NOT_REC_READERS_RIR_IX
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.SAVED_READERS_RIR_IX
 	ON HOMEPAGE.NR_SAVED_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;

CREATE  INDEX HOMEPAGE.TOPICS_READERS_RIR_IX
 	ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, IS_VISIBLE, ROLLUP_ENTRY_ID DESC, CREATION_DATE DESC);
COMMIT;



---------------------------------------------------------------------------------
--Community Event Widget
---------------------------------------------------------------------------------

INSERT INTO HOMEPAGE.WIDGET
            (WIDGET_ID, WIDGET_TITLE, WIDGET_TEXT, WIDGET_URL, WIDGET_ICON, WIDGET_ENABLED, WIDGET_SYSTEM, WIDGET_HOMEPAGE_SPECIFIC, WIDGET_PREVIEW_IMAGE, WIDGET_CATEGORY, WIDGET_IS_DEFAULT_OPENED, WIDGET_MULTIPLE_INSTANCES, WIDGET_SECURE_URL, WIDGET_SECURE_ICON, IS_GADGET)
VALUES      ('commuevtxe7c4x4e08xab54x80e7a4eb8933', '%widget.communities.event.name', '%widget.communities.event.desc', '${COMMON_CONTEXT_ROOT}/web/lconn.calendar/CalendarGadget.xml', '${COMMON_CONTEXT_ROOT}/web/com.ibm.lconn.core.styles/images/iconCommunities16.png', 1, 1, 1, '${HOMEPAGE_CONTEXT_ROOT}/web/jsp/palette/images/profiles_my_colleagues.jpg', 'COMMUNITIES', 1,  0, '${COMMON_CONTEXT_ROOT}/web/lconn.calendar/CalendarGadget.xml', '${COMMON_CONTEXT_ROOT}/web/com.ibm.lconn.core.styles/images/iconCommunities16.png',1);

INSERT INTO HOMEPAGE.PREREQ
            (PREREQ_ID, APP_ID, WIDGET_ID)
VALUES      ('73de6654x9317x4195x90c0x696c1b6da4ff', 'communities', 'commuevtxe7c4x4e08xab54x80e7a4eb8933');

INSERT INTO HOMEPAGE.HP_WIDGET_TAB
        (WIDGET_TAB_ID, WIDGET_ID, TAB_ID, TYPE)
VALUES  ('UPDATES_communityevent-sidebar', 'commuevtxe7c4x4e08xab54x80e7a4eb8933', '_panel.updatex4a43x82aaxb00187218631', 'primary');

COMMIT;


-------------------------- fixing issue with is_prev is_last comment ------------------------

--  [start] NR_ENTRIES
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID < '0..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID < '0..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '0..f' AND ENTRY_ID < '1..f'  ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '0..f' AND ENTRY_ID < '1..f'  ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '1..f' AND ENTRY_ID < '2..f'  ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '1..f' AND ENTRY_ID < '2..f'  ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '2..f' AND ENTRY_ID < '3..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '2..f' AND ENTRY_ID < '3..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '3..f' AND ENTRY_ID < '4..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '3..f' AND ENTRY_ID < '4..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '4..f' AND ENTRY_ID < '5..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '4..f' AND ENTRY_ID < '5..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '5..f' AND ENTRY_ID < '6..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '5..f' AND ENTRY_ID < '6..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '6..f' AND ENTRY_ID < '7..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '6..f' AND ENTRY_ID < '7..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '7..f' AND ENTRY_ID < '8..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '7..f' AND ENTRY_ID < '8..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '8..f' AND ENTRY_ID < '9..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '8..f' AND ENTRY_ID < '9..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '9..f' AND ENTRY_ID < 'a..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= '9..f' AND ENTRY_ID < 'a..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'a..f' AND ENTRY_ID < 'b..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'a..f' AND ENTRY_ID < 'b..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'b..f' AND ENTRY_ID < 'c..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'b..f' AND ENTRY_ID < 'c..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'c..f' AND ENTRY_ID < 'd..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'c..f' AND ENTRY_ID < 'd..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'd..f' AND ENTRY_ID < 'e..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'd..f' AND ENTRY_ID < 'e..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'e..f' AND ENTRY_ID < 'f..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'e..f' AND ENTRY_ID < 'f..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_PREV_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_PREV_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'f..f' ;
COMMIT;
UPDATE HOMEPAGE.NR_ENTRIES  
 	SET IS_LAST_COMMENT_VISIBLE = 1 	WHERE NOT ( IS_LAST_COMMENT_VISIBLE = 1 ) AND  ENTRY_ID >= 'f..f' ;
COMMIT;
--  [end] NR_ENTRIES

---------------------------------------------------------------------------------
------------------------ END NEWS FIXUP 101 -------------------------------------
---------------------------------------------------------------------------------
 

  
  
  