-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-----------------------------------------------------------------
-- [START] Adding to NR_STORIES_CONTENT:
-----------------------------------------------------------------
--ITEM_CONTENT - CLOB (can be null)
--ITEM_CORRELATION_CONTENT - CLOB (can be null)

--CONTENT_FORMAT - INTEGER (can be null)
--ITEM_CONTENT_FORMAT -  INTEGER (can be null)
--ITEM_CORRELATION_FORMAT -  INTEGER (can be null)
-----------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT
	ADD	ITEM_CONTENT CLOB
	ADD	ITEM_CORRELATION_CONTENT CLOB
	ADD ITEM_CONTENT_FORMAT SMALLINT
	ADD ITEM_CORRELATION_FORMAT SMALLINT
	ADD CONTENT_FORMAT SMALLINT;
COMMIT;

REORG TABLE HOMEPAGE.NR_STORIES_CONTENT;

COMMIT;
-----------------------------------------------------------------
-- [END] Adding to NR_STORIES_CONTENT:
-----------------------------------------------------------------

-----------------------------------------------------------------
-- [START] Add OBJECT_META_DATA and OBJECT_META_DATA_2 in BOARD_OBJECT_REFERENCE table
-----------------------------------------------------------------

------------------------------------
-- DDL Statements for BUFFERPOOLS --
------------------------------------ 
CREATE BUFFERPOOL BPOOL8K SIZE AUTOMATIC PAGESIZE 8192;

------------------------------------
-- DDL Statements for TABLESPACES -- 
------------------------------------
CREATE BUFFERPOOL BRD32KBP IMMEDIATE SIZE 16000 AUTOMATIC PAGESIZE 32K;

-- BRD 32K TABLESPACE
CREATE SYSTEM TEMPORARY TABLESPACE BRD32TMPTABSPACE
	PAGESIZE 32K MANAGED BY SYSTEM 
	USING ( 'BRDS32TMPTABSPACE' ) 
	EXTENTSIZE 16 PREFETCHSIZE AUTOMATIC
	BUFFERPOOL BRD32KBP
	FILE SYSTEM CACHING;
              
CREATE LARGE TABLESPACE BRD32TABSPACE 
	PAGESIZE 32K MANAGED BY DATABASE
	USING (FILE 'BRD32TABSPACE' 12800)
	EXTENTSIZE 16
	PREFETCHSIZE AUTOMATIC
	BUFFERPOOL BRD32KBP
	AUTORESIZE YES
	INCREASESIZE 40 M
	MAXSIZE NONE;
	 
COMMIT;

DROP TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE;

----------------------------------------------------------------
-- ADDING BOARD_OBJECT_REFERENCE
----------------------------------------------------------------
CREATE TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE (
	OBJECT_ID VARCHAR(47) NOT NULL,
	ENTRY_ID VARCHAR(47) NOT NULL,
	DISPLAY_NAME VARCHAR(2048),
	IMAGE_NAME   VARCHAR(2048),
	NAME VARCHAR(512), 
	URL VARCHAR(1024), 
	CONTENT VARCHAR(4000),
	IMAGE_URL VARCHAR(1024),
	SOURCE  VARCHAR(36),
	SOURCE_TYPE  SMALLINT,
	CREATION_DATE TIMESTAMP,
	MIME_TYPE VARCHAR(36),
	AUTHOR_ID VARCHAR(36),
	AUTHOR_DISPLAY_NAME VARCHAR(256),
	OBJECT_META_DATA VARCHAR(4000),
	OBJECT_META_DATA_2 VARCHAR(4000),
	FULL_OBJECT_META_DATA CLOB
)
IN BRD32TABSPACE;

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE 
    ADD CONSTRAINT PK_BRD_OBJ_ID PRIMARY KEY(OBJECT_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT FK_BRD_OBJ_ENTRY FOREIGN KEY (ENTRY_ID)
	REFERENCES HOMEPAGE.BOARD_ENTRIES (ENTRY_ID);

ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE
	ADD CONSTRAINT FK_BRD_AUTHOR_ID FOREIGN KEY (AUTHOR_ID)
	REFERENCES HOMEPAGE.PERSON (PERSON_ID);

CREATE INDEX HOMEPAGE.BRD_ENTRY_IDX
    ON HOMEPAGE.BOARD_OBJECT_REFERENCE (ENTRY_ID);

CREATE INDEX HOMEPAGE.BRD_AUTHOR_IDX
    ON HOMEPAGE.BOARD_OBJECT_REFERENCE (AUTHOR_ID);

COMMIT;
-----------------------------------------------------------------
-- [END] Add OBJECT_META_DATA and OBJECT_META_DATA_2 in BOARD_OBJECT_REFERENCE table
-----------------------------------------------------------------

-----------------------------------------------------------------
-- [START] Adding two columns to NR_ENTRIES tables: ITEM_CORRELATION_BRIEF_DESC
-----------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_ENTRIES
	ADD	ITEM_CORRELATION_BRIEF_DESC VARCHAR(4000);
COMMIT;

REORG TABLE HOMEPAGE.NR_ENTRIES;

COMMIT;
-----------------------------------------------------------------
-- [END] Adding two columns to NR_ENTRIES tables: ITEM_CORRELATION_BRIEF_DESC
-----------------------------------------------------------------

-----------------------------------------------------------------
-- [START] adding back a fk from READERS table to STORIES table
-----------------------------------------------------------------

-- cleanup possible wrong records (we have seen this issue on tapstage)
--1)
DELETE FROM HOMEPAGE.NR_AGGREGATED_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--2)
DELETE FROM HOMEPAGE.NR_RESPONSES_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

DELETE FROM HOMEPAGE.NR_PROFILES_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--3)
DELETE FROM HOMEPAGE.NR_COMMUNITIES_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--4)
DELETE FROM HOMEPAGE.NR_ACTIVITIES_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--5)
DELETE FROM HOMEPAGE.NR_BLOGS_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--6)
DELETE FROM HOMEPAGE.NR_BOOKMARKS_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--7)
DELETE FROM HOMEPAGE.NR_FILES_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--8)
DELETE FROM HOMEPAGE.NR_FORUMS_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--9)
DELETE FROM HOMEPAGE.NR_WIKIS_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--10)
DELETE FROM HOMEPAGE.NR_TAGS_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;


--11)
DELETE FROM HOMEPAGE.NR_STATUS_UPDATE_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--12)
DELETE FROM HOMEPAGE.NR_EXTERNAL_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--13)
DELETE FROM HOMEPAGE.NR_ACTIONABLE_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--14)
DELETE FROM HOMEPAGE.NR_SAVED_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--15)
DELETE FROM HOMEPAGE.NR_DISCOVERY_VIEW READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

--16)
DELETE FROM HOMEPAGE.NR_PROFILES_VIEW READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;


--17)
DELETE FROM HOMEPAGE.NR_NOTIFICATION_SENT_READERS READERS
WHERE 	NOT EXISTS (	
					SELECT 	1 
					FROM 	HOMEPAGE.NR_STORIES  STORIES
					WHERE 	STORIES.STORY_ID = READERS.STORY_ID
				);
commit;

-- adding the fk
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS 
	ADD CONSTRAINT FK_AGG_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS 
	ADD CONSTRAINT FK_RES_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_READERS 
	ADD CONSTRAINT FK_PRF_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;	
	
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS
	ADD CONSTRAINT FK_COM_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;
	 
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS
	ADD CONSTRAINT FK_ACI_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;
	 
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS
	ADD CONSTRAINT FK_BLG_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;
	 
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS
	ADD CONSTRAINT FK_BKM_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;
	 
ALTER TABLE HOMEPAGE.NR_FILES_READERS
	ADD CONSTRAINT FK_FIL_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_FORUMS_READERS
	ADD CONSTRAINT FK_FRM_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;
	 
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS
	ADD CONSTRAINT FK_WIK_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_TAGS_READERS
	ADD CONSTRAINT FK_TAG_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS
	ADD CONSTRAINT FK_STA_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;	
	 
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS
	ADD CONSTRAINT FK_EXT_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;	
	
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS
	ADD CONSTRAINT FK_ACT_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;	
	
ALTER TABLE HOMEPAGE.NR_SAVED_READERS
	ADD CONSTRAINT FK_SAV_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;
	 
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW
	ADD CONSTRAINT FK_DIS_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;

ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW
	ADD CONSTRAINT FK_PRO_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;
	 
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS
	ADD CONSTRAINT FK_NOT_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);
COMMIT;		



-----------------------------------------------------------------
-- [END] adding back a fk from READERS table to STORIES table
-----------------------------------------------------------------

-----------------------------------------------------------------
-- [START] adding cluster index on the READERS table
-----------------------------------------------------------------
CREATE INDEX HOMEPAGE.CL_AGGREGATED_READERS_IDX
	ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID) CLUSTER; 
COMMIT;

CREATE INDEX HOMEPAGE.CL_RESPONSES_READERS_IDX
	ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID) CLUSTER;
COMMIT;	

CREATE INDEX HOMEPAGE.CL_PROFILES_READERS_IDX
	ON HOMEPAGE.NR_PROFILES_READERS (READER_ID) CLUSTER;
COMMIT;

CREATE INDEX HOMEPAGE.CL_COMM_READERS_IDX
	ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID) CLUSTER;
COMMIT;
	 
CREATE INDEX HOMEPAGE.CL_ACTIVITIES_READERS_IDX
	ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID) CLUSTER;
COMMIT;
	 
CREATE INDEX HOMEPAGE.CL_BLOGS_READERS_IDX
	ON HOMEPAGE.NR_BLOGS_READERS (READER_ID) CLUSTER;
COMMIT;
	 
CREATE INDEX HOMEPAGE.CL_BOOKMARKS_READERS_IDX
	ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID) CLUSTER;
COMMIT;
	 
CREATE INDEX HOMEPAGE.CL_FILES_READERS_IDX
	ON HOMEPAGE.NR_FILES_READERS (READER_ID) CLUSTER;
COMMIT;

CREATE INDEX HOMEPAGE.CL_FORUMS_READERS_IDX
	ON HOMEPAGE.NR_FORUMS_READERS (READER_ID) CLUSTER;
COMMIT;
	 
CREATE INDEX HOMEPAGE.CL_WIKIS_READERS_IDX
	ON HOMEPAGE.NR_WIKIS_READERS (READER_ID) CLUSTER;
COMMIT;

CREATE INDEX HOMEPAGE.CL_TAGS_READERS_IDX
	ON HOMEPAGE.NR_TAGS_READERS (READER_ID) CLUSTER;
COMMIT;

CREATE INDEX HOMEPAGE.CL_STATUS_READERS_IDX
	ON HOMEPAGE.NR_STATUS_UPDATE_READERS  (READER_ID) CLUSTER;
COMMIT;	
	 
CREATE INDEX HOMEPAGE.CL_EXTERNAL_READERS_IDX
	ON HOMEPAGE.NR_EXTERNAL_READERS  (READER_ID) CLUSTER;
COMMIT;	
	
CREATE INDEX HOMEPAGE.CL_ACTIONABLE_READERS_IDX
	ON HOMEPAGE.NR_ACTIONABLE_READERS  (READER_ID) CLUSTER;
COMMIT;	
	
CREATE INDEX HOMEPAGE.CL_SAVED_READERS_IDX
	ON HOMEPAGE.NR_SAVED_READERS  (READER_ID) CLUSTER;
COMMIT;
	 
CREATE INDEX HOMEPAGE.CL_DISCOVERY_READERS_IDX
	ON HOMEPAGE.NR_DISCOVERY_VIEW  (READER_ID) CLUSTER;
COMMIT;

CREATE INDEX HOMEPAGE.CL_PROFILESV_READERS_IDX
	ON HOMEPAGE.NR_PROFILES_VIEW  (READER_ID) CLUSTER;
COMMIT;
	 
CREATE INDEX HOMEPAGE.CL_NOTIFICA_READERS_IDX
	ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS  (READER_ID) CLUSTER;
COMMIT;

-----------------------------------------------------------------
-- [STOP] adding cluster index on the READERS table
-----------------------------------------------------------------

-----------------------------------------------------------------
-- [START] N_COMMENTS AND N_RECOMMENDATIONS need to be nullable
-----------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_ENTRIES ALTER COLUMN N_COMMENTS DROP NOT NULL;
commit;
ALTER TABLE HOMEPAGE.NR_ENTRIES ALTER COLUMN N_COMMENTS SET DEFAULT NULL;
commit;

ALTER TABLE HOMEPAGE.NR_ENTRIES ALTER COLUMN N_RECOMMANDATIONS DROP NOT NULL;
commit;
ALTER TABLE HOMEPAGE.NR_ENTRIES ALTER COLUMN N_RECOMMANDATIONS SET DEFAULT NULL;
commit;

reorg table HOMEPAGE.NR_ENTRIES;
commit;

--- Adding EVENT_SCOPE
ALTER TABLE HOMEPAGE.NR_STORIES
	ADD COLUMN EVENT_SCOPE SMALLINT;
	
reorg table HOMEPAGE.NR_STORIES;
commit;


-----------------------------------------------------------------
-- [END] N_COMMENTS AND N_RECOMMENDATIONS need to be nullable
-----------------------------------------------------------------
UPDATE HOMEPAGE.NR_ENTRIES SET N_COMMENTS = NULL WHERE N_COMMENTS = -1;
COMMIT;

UPDATE HOMEPAGE.NR_ENTRIES SET N_RECOMMANDATIONS = NULL WHERE N_RECOMMANDATIONS = -1;
COMMIT;

	
	
------------------------------------------------------------------
-- [START] Adding calendar templates
------------------------------------------------------------------
INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('general-containerffasfh3452yst42465','container','containerName;containerHtmlPath', 'link', 1);

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('general-item-slkmg9015bxBNKbkHkdf65','item','itemName;itemHtmlPath', 'link', 1);

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('general-correllation-asdfbe898Bjr95','correlationitem','correlationName;correlationHtmlPath', 'link', 1);

------------------------------------------------------------------
-- [END] Adding calendar templates
------------------------------------------------------------------

------------------------------------------------------------------
-- Adding NR_ENTRIES_ARCHIVE table
------------------------------------------------------------------
----------------------------------------------------------------
-- HOMEPAGE.NR_ENTRIES_ARCHIVE
----------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE (
	ENTRY_ID VARCHAR(36) NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	CONTAINER_ID VARCHAR(256),
	CONTAINER_NAME VARCHAR(256),
	CONTAINER_URL VARCHAR(2048),
	ITEM_ID VARCHAR(36),
	ITEM_NAME VARCHAR(256),
	ITEM_URL VARCHAR(2048),
	ITEM_CREATION_DATE TIMESTAMP,
	ITEM_UPDATE_DATE TIMESTAMP,
	ITEM_TAGS VARCHAR(1024),
	N_COMMENTS SMALLINT DEFAULT NULL,
	N_RECOMMANDATIONS SMALLINT DEFAULT NULL,
	LAST_COMMENT_ID VARCHAR(36),
	LAST_DATE_COMMENT TIMESTAMP,
	LAST_AUTHOR_COMMENT VARCHAR(36),
	PREV_COMMENT_ID VARCHAR(36),
	PREV_DATE_COMMENT TIMESTAMP,
	PREV_AUTHOR_COMMENT VARCHAR(36),
	TARGET_SUBJECT_ID VARCHAR(36),
	ITEM_ATOM_URL VARCHAR(2048),
	PREVIEW_IMAGE_URL VARCHAR(2048),
	JSON_META_DATA VARCHAR(4000),
	ITEM_SCOPE SMALLINT,
	IS_LAST_COMMENT_PUBLIC SMALLINT,
	IS_PREV_COMMENT_PUBLIC SMALLINT,
	ITEM_CORRELATION_ID VARCHAR(36),
	ITEM_CORRELATION_NAME VARCHAR(256),
	LAST_DESC_COMMENT VARCHAR(4000),
	PREV_DESC_COMMENT VARCHAR(4000),
	LAST_UPDATE_DATE_COMMENT TIMESTAMP,
	PREV_UPDATE_DATE_COMMENT TIMESTAMP,
	ITEM_AUTHOR_UUID VARCHAR (36),
	ITEM_AUTHOR_DISPLAYNAME VARCHAR (256),
	ITEM_CORRELATION_AUTHOR_UUID VARCHAR (36),
	ITEM_CORRELATION_AUTHOR_NAME VARCHAR (256),
	BRIEF_DESC VARCHAR (4000),
	ITEM_CORRELATION_BRIEF_DESC VARCHAR(4000)
)
IN NEWS32TABSPACE;

ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE
    ADD CONSTRAINT PK_ENTRY_AR_ID PRIMARY KEY(ENTRY_ID);

CREATE INDEX HOMEPAGE.NR_ENTRIES_AR_CONT
    ON HOMEPAGE.NR_ENTRIES_ARCHIVE (CONTAINER_ID);

CREATE UNIQUE INDEX HOMEPAGE.NR_ENTRIES_AR_ITEM
    ON HOMEPAGE.NR_ENTRIES_ARCHIVE (ITEM_ID);

COMMIT;


--------------------------------------------------------------------------
-- 20 HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
--------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (
	CATEGORY_READER_ID VARCHAR(36)  DEFAULT ' ' NOT NULL,
	READER_ID VARCHAR(36) NOT NULL,
	CATEGORY_TYPE SMALLINT NOT NULL,
	SOURCE VARCHAR(36) NOT NULL,
	CONTAINER_ID VARCHAR(256),
	ITEM_ID VARCHAR(36),
	ROLLUP_ENTRY_ID VARCHAR(36),
	RESOURCE_TYPE SMALLINT NOT NULL,
	CREATION_DATE TIMESTAMP NOT NULL,
	STORY_ID VARCHAR(36) NOT NULL,
	SOURCE_TYPE SMALLINT,
	USE_IN_ROLLUP SMALLINT,
	IS_NETWORK	SMALLINT,
	IS_FOLLOWER	SMALLINT,
	EVENT_TIME 	TIMESTAMP,
	IS_STORY_COMM SMALLINT,
	IS_BROADCAST SMALLINT,
	ORGANIZATION_ID VARCHAR(36),
	ACTOR_UUID VARCHAR(36),
        CONSTRAINT   	CK_CAT20_TYPE
    			CHECK
    			(CATEGORY_TYPE = 20)
)
IN NEWS4TABSPACE;

ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS 
    ADD CONSTRAINT PK_REC_NOT_READ PRIMARY KEY(CATEGORY_READER_ID);
    
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS
	ADD CONSTRAINT FK_REC_READERS_STR FOREIGN KEY (STORY_ID)
	REFERENCES HOMEPAGE.NR_STORIES (STORY_ID);    

CREATE  INDEX HOMEPAGE.REC_READERS_STR_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID); 
COMMIT;

CREATE  INDEX HOMEPAGE.REC_READERS_ITM_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ITEM_ID); 
COMMIT;

CREATE  INDEX HOMEPAGE.REC_READERS_CD_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (STORY_ID, CREATION_DATE DESC); 
COMMIT;

CREATE  INDEX HOMEPAGE.REC_READERS_SRC_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE); 
COMMIT;

CREATE  INDEX HOMEPAGE.REC_READERS_ACT_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, CREATION_DATE DESC, ACTOR_UUID, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE); 
COMMIT;

CREATE  INDEX HOMEPAGE.REC_READERS_RLL_IX 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (USE_IN_ROLLUP, READER_ID, CREATION_DATE DESC, STORY_ID, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE); 
COMMIT;

CREATE UNIQUE INDEX HOMEPAGE.REC_READERS_UNQ_RDR_STR 
 	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, STORY_ID); 
COMMIT;

CREATE INDEX HOMEPAGE.CL_REC_READERS_IDX
	ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS  (READER_ID) CLUSTER;
COMMIT;

------------------------------------
-- Adding the category type for: notification-received
------------------------------------
INSERT INTO HOMEPAGE.NR_CATEGORY_TYPE (CATEGORY_TYPE_ID, CATEGORY_TYPE, CATEGORY_TYPE_NAME, CATEGORY_TYPE_DESC)
VALUES ('notification-received', 20, '%notification-received', 'notification-received');

------------------------------------------------------------------
-- [START] Adding GENERAL templates (for EXTERNAL events)
------------------------------------------------------------------
INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('Actor-3913FB2B6B5D4323BFD4DAAC189B8','Actor', 'actorInternalId', 'profilePhoto', 1); 

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('Object-CEDEBA0964F2442EB3E5155493C0','Object', 'asObjectType;asObjectInternalId;asObjectName;asObjectHtmlPath', 'activityObject', 1);

INSERT INTO HOMEPAGE.NR_TEMPLATE
		(TEMPLATE_ID, NAME, DATA_SOURCE_STRING, FORMAT, NO_VALUES)
VALUES	('Target-5EF5EDF61F9F47F692ED1CDFDF86','Target', 'asTargetType;asTargetInternalId;asTargetName;asTargetHtmlPath', 'activityObject', 1);

------------------------------------------------------------------
-- [END] Adding GENERAL templates (for EXTERNAL events)
------------------------------------------------------------------
