-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2007, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- {COPYRIGHT}

-- SEARCH
{AS400_GRANT_START} HOMEPAGE.SR_TASKDEF {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_OPTIMIZETASKDEF {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_INDEXINGTASKDEF {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_FILESCONTENT {AS400_GRANT_STOP}

--view needn't to be granted except for the select authority
GRANT SELECT ON HOMEPAGE.SR_ALLTASKSDEF {AS400_GRANT_STOP}

{AS400_GRANT_START} HOMEPAGE.SR_MIGTASKDEFINFO {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_FILECONTENTTASKDEF {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_INDEX_DOCS {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_RESUME_TOKENS {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_BACKUPTASKDEF {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_INDEX_MANAGEMENT {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_SANDTASKDEF {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_FEEDBACK {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_FEEDBACK_CONTEXT {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_FEEDBACK_PARAMETERS {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_STATS {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_STRING_STATS {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_NUMBER_STATS {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_TIMER_STATS {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_GLOBAL_SAND_PROPS {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_ECM_DOCUMENT_TYPE_LABELS  {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.SR_ECM_DOCUMENT_TYPE_PROPS {AS400_GRANT_STOP} 
{AS400_GRANT_START} HOMEPAGE.SR_POST_FILTERING_SERVICE {AS400_GRANT_STOP}

{AS400_GRANT_START} HOMEPAGE.LOTUSCONNECTIONSLMGR {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.LOTUSCONNECTIONSLMPR {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.LOTUSCONNECTIONSTASK {AS400_GRANT_STOP}
{AS400_GRANT_START} HOMEPAGE.LOTUSCONNECTIONSTREG {AS400_GRANT_STOP}

