-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2009, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

connect to HOMEPAGE;

--------------------------------------
-- DROP THE INDEXES
--------------------------------------
DROP INDEX HOMEPAGE.USERID_WIDGET_UNIQUE;

--------------------------------------
-- DROP THE CONSTRAINTS
--------------------------------------
ALTER TABLE HOMEPAGE.PREREQ DROP FOREIGN KEY FK_PREREQ_WIDGET;

ALTER TABLE HOMEPAGE.USER_WIDGET_PREF DROP FOREIGN KEY FK_WIDGET_ID;


-----------------------------------------------------------------------------------------------------
-- WORKING ON HOMEPAGE.PERSON
-----------------------------------------------------------------------------------------------------
-- adding PERSON_ID column
ALTER TABLE HOMEPAGE.PERSON ADD PERSON_ID VARCHAR(36) NOT NULL DEFAULT '';

-- adding DISPLAYNAME column
ALTER TABLE HOMEPAGE.PERSON ADD DISPLAYNAME VARCHAR(256) NOT NULL DEFAULT '';

-- adding SHOW_DISABLED_WIDGETS column
ALTER TABLE HOMEPAGE.PERSON ADD SHOW_DISABLED_WIDGETS SMALLINT DEFAULT 0 NOT NULL;

-- USER_MAIL can now be even NULL
ALTER TABLE HOMEPAGE.PERSON ALTER COLUMN USER_MAIL DROP NOT NULL;

REORG TABLE HOMEPAGE.PERSON USE TEMPSPACE1;

-- copy USER_ID in PERSON_ID
UPDATE HOMEPAGE.PERSON  	
SET HOMEPAGE.PERSON.PERSON_ID = 	( SELECT PERSON_A.USER_ID
FROM HOMEPAGE.PERSON AS PERSON_A
WHERE PERSON_A.USER_ID = HOMEPAGE.PERSON.USER_ID)
WHERE EXISTS
  ( SELECT PERSON_B.USER_ID
    FROM HOMEPAGE.PERSON AS PERSON_B
    WHERE PERSON_B.USER_ID = HOMEPAGE.PERSON.USER_ID);

-- copy USER_MAIL in DISPLAYNAME
UPDATE HOMEPAGE.PERSON  	
SET HOMEPAGE.PERSON.DISPLAYNAME = 	( SELECT PERSON_A.USER_MAIL
FROM HOMEPAGE.PERSON AS PERSON_A
WHERE PERSON_A.USER_ID = HOMEPAGE.PERSON.USER_ID)
WHERE EXISTS
  ( SELECT PERSON_B.USER_MAIL
    FROM HOMEPAGE.PERSON AS PERSON_B
    WHERE PERSON_B.USER_ID = HOMEPAGE.PERSON.USER_ID);

-- copy SHOW_DISABLED_WIDGETS 
UPDATE HOMEPAGE.PERSON  	
SET HOMEPAGE.PERSON.SHOW_DISABLED_WIDGETS = ( 	SELECT DISTINCT (HOMEPAGE.USER_WIDGET_PREF.SHOW_DISABLED_WIDGETS)
												FROM HOMEPAGE.USER_WIDGET_PREF
												WHERE 	HOMEPAGE.USER_WIDGET_PREF.USER_ID = HOMEPAGE.PERSON.USER_ID AND 
														HOMEPAGE.USER_WIDGET_PREF.SHOW_DISABLED_WIDGETS <> 0)
WHERE EXISTS
  ( SELECT DISTINCT (HOMEPAGE.USER_WIDGET_PREF.USER_ID)
    FROM HOMEPAGE.USER_WIDGET_PREF
    WHERE HOMEPAGE.USER_WIDGET_PREF.USER_ID = HOMEPAGE.PERSON.USER_ID AND 
    HOMEPAGE.USER_WIDGET_PREF.SHOW_DISABLED_WIDGETS <> 0);


-- renaming USER_ID to PERSON_ID, remove the old USER_ID which now is called PERSON_ID
-- remove the primary key on USER_ID and set it on PERSON_ID
-- Note: the drop for FK_USER_ID could fail
ALTER TABLE HOMEPAGE.PERSON DROP PRIMARY KEY;
ALTER TABLE HOMEPAGE.PERSON ADD CONSTRAINT "PK_PERSON_ID" PRIMARY KEY("PERSON_ID");
ALTER TABLE HOMEPAGE.PERSON DROP COLUMN USER_ID;

-----------------------------------------------------------------------------------------------------
-- WORKING ON HOMEPAGE.LOGINNAME
-----------------------------------------------------------------------------------------------------
-- Adding the new table LOGINAME
CREATE TABLE HOMEPAGE.LOGINNAME (
	PERSON_ID VARCHAR(36) NOT NULL,
	LOGINNAME VARCHAR(256) NOT NULL
)
IN HOMEPAGETABSPACE;

-- Populate the new table LOGINAME
INSERT INTO HOMEPAGE.LOGINNAME (PERSON_ID, LOGINNAME) SELECT PERSON_ID, USER_MAIL FROM HOMEPAGE.PERSON;

------------------------------------------------------------------------------------------------------
-- WORKING ON HOMEPAGE.USER_WIDGET_PREF
------------------------------------------------------------------------------------------------------
-- change USER_ID VARCHAR(256) to USER_ID VARCHAR(36), need to use a temp column TEMP_USER_ID
ALTER TABLE HOMEPAGE.USER_WIDGET_PREF ADD COLUMN TEMP_USER_ID VARCHAR(36);

UPDATE HOMEPAGE.USER_WIDGET_PREF  	
SET HOMEPAGE.USER_WIDGET_PREF.TEMP_USER_ID = 	( SELECT USER_WIDGET_PREF_A.USER_ID
FROM HOMEPAGE.USER_WIDGET_PREF AS USER_WIDGET_PREF_A
WHERE USER_WIDGET_PREF_A.USER_WIDGET_PREF_ID = HOMEPAGE.USER_WIDGET_PREF.USER_WIDGET_PREF_ID)
WHERE EXISTS
  ( SELECT USER_WIDGET_PREF_B.USER_WIDGET_PREF_ID
    FROM HOMEPAGE.USER_WIDGET_PREF AS USER_WIDGET_PREF_B
    WHERE USER_WIDGET_PREF_B.USER_WIDGET_PREF_ID = HOMEPAGE.USER_WIDGET_PREF.USER_WIDGET_PREF_ID);

ALTER TABLE HOMEPAGE.USER_WIDGET_PREF DROP COLUMN USER_ID;

ALTER TABLE HOMEPAGE.USER_WIDGET_PREF ADD USER_ID VARCHAR(36) NOT NULL DEFAULT '';

-- need to perform a REORG at this stage (just db2)
REORG TABLE HOMEPAGE.USER_WIDGET_PREF use TEMPSPACE1;

UPDATE HOMEPAGE.USER_WIDGET_PREF  	
SET HOMEPAGE.USER_WIDGET_PREF.USER_ID = 	( SELECT USER_WIDGET_PREF_A.TEMP_USER_ID
FROM HOMEPAGE.USER_WIDGET_PREF AS USER_WIDGET_PREF_A
WHERE USER_WIDGET_PREF_A.USER_WIDGET_PREF_ID = HOMEPAGE.USER_WIDGET_PREF.USER_WIDGET_PREF_ID)
WHERE EXISTS
  ( SELECT USER_WIDGET_PREF_B.TEMP_USER_ID
    FROM HOMEPAGE.USER_WIDGET_PREF AS USER_WIDGET_PREF_B
    WHERE USER_WIDGET_PREF_B.USER_WIDGET_PREF_ID = HOMEPAGE.USER_WIDGET_PREF.USER_WIDGET_PREF_ID);

-- remove TEMP_USER_ID
ALTER TABLE HOMEPAGE.USER_WIDGET_PREF DROP COLUMN TEMP_USER_ID;

-- remove SHOW_DISABLED_WIDGETS
ALTER TABLE HOMEPAGE.USER_WIDGET_PREF DROP COLUMN SHOW_DISABLED_WIDGETS;

-- UPDATE THE WIDGET_ICON using HOMEPAGE_CONTEXT_ROOT in HOMEPAGE.WIDGET
UPDATE HOMEPAGE.WIDGET 
	SET HOMEPAGE.WIDGET.WIDGET_ICON = '${HOMEPAGE_CONTEXT_ROOT}' || SUBSTR(HOMEPAGE.WIDGET.WIDGET_ICON,10)
	WHERE HOMEPAGE.WIDGET.WIDGET_ICON like '/homepage/%';


------------------------------------------------------------------------------------------------------
-- WORKING ON HOMEPAGE.USER_WIDGET_PREF
------------------------------------------------------------------------------------------------------
UPDATE HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER =  6;


--------------------------------------
-- CREATE THE CONSTRAINTS
--------------------------------------
ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT "PK_LOGINNAME_ID" PRIMARY KEY ("PERSON_ID","LOGINNAME");	

REORG TABLE HOMEPAGE.PERSON USE TEMPSPACE1;

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT "FK_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON("PERSON_ID");
	
ALTER TABLE HOMEPAGE.USER_WIDGET_PREF
    ADD CONSTRAINT "FK_USER_ID" FOREIGN KEY ("USER_ID")
	REFERENCES HOMEPAGE.PERSON("PERSON_ID");

ALTER TABLE HOMEPAGE.USER_WIDGET_PREF
    ADD CONSTRAINT "FK_WIDGET_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES HOMEPAGE.WIDGET ("WIDGET_ID");

ALTER TABLE HOMEPAGE.PREREQ 
	ADD CONSTRAINT "FK_PREREQ_WIDGET" FOREIGN KEY ("WIDGET_ID")
	REFERENCES HOMEPAGE.WIDGET ("WIDGET_ID")
	ON DELETE CASCADE;

ALTER TABLE HOMEPAGE.LOGINNAME
	ADD CONSTRAINT LOGINNAME_UNIQUE UNIQUE(LOGINNAME);

--------------------------------------
-- CREATE THE INDEXES
--------------------------------------
REORG TABLE HOMEPAGE.USER_WIDGET_PREF USE TEMPSPACE1;

CREATE UNIQUE INDEX HOMEPAGE.USERID_WIDGET_UNIQUE
	ON HOMEPAGE.USER_WIDGET_PREF(USER_ID ASC, WIDGET_ID ASC);
	
CREATE UNIQUE INDEX HOMEPAGE.PERSON_EXID
    ON HOMEPAGE.PERSON(EXID);

CREATE INDEX HOMEPAGE.PERSON_USER_MAIL
    ON HOMEPAGE.PERSON(USER_MAIL);

-- grant connect

GRANT CONNECT ON DATABASE TO USER LCUSER;

-- grants for homepage tables

GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.HOMEPAGE_SCHEMA TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.PERSON TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.LOGINNAME TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.USER_WIDGET_PREF  TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.WIDGET  TO USER LCUSER;
GRANT DELETE,INSERT,SELECT,UPDATE ON HOMEPAGE.PREREQ TO USER LCUSER;

connect reset;
terminate;
