-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2008, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- DB2   	ORACLE
-- CHAR 	-> CHAR 
-- VARCHAR	-> VARCHAR2
-- SMALLINT	-> NUMBER(5,0)
-- INTEGER	-> NUMBER(10 ,0)
-- BIGINT	-> NUMBER(19 ,0)
-- CLOB(max)	-> CLOB
-- BLOB(max)	-> BLOB
-- TIMESTAMP	-> TIMESTAMP   
  
--------------------------------------
-- CREATE THE TABLESPACE  
-------------------------------------- 

-- HOMEPAGE TABLESPACE
CREATE SMALLFILE TABLESPACE "HOMEPAGEREGTABSPACE" 
	DATAFILE 'HOMEPAGEREGTABSPACE' 
	SIZE 400M REUSE AUTOEXTEND ON 
	NEXT 20M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;
	
CREATE SMALLFILE TABLESPACE "HOMEPAGEINDEXTABSPACE" 
	DATAFILE 'HOMEPAGEINDEXTABSPACE' 
	SIZE 400M REUSE AUTOEXTEND ON 
	NEXT 20M MAXSIZE UNLIMITED 
	LOGGING EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;

-- HOMEPAGE NOTIFICATION TABLETABLESPACE
CREATE TEMPORARY TABLESPACE "HPNTTMPTABSPACE"
	TEMPFILE 'HPNTTMPTABSPACE'
	SIZE 800M REUSE AUTOEXTEND ON;
	
CREATE SMALLFILE TABLESPACE "HPNTREGTABSPACE"
	DATAFILE 'HPNTREGTABSPACE'
	SIZE 800M REUSE AUTOEXTEND ON 
	NEXT 20M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "HPNTINDEXTABSPACE"
	DATAFILE 'HPNTINDEXTABSPACE'
	SIZE 800M REUSE AUTOEXTEND ON 
	NEXT 40M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;

-- HOMEPAGE NEWS TABLETABLESPACE
CREATE TEMPORARY TABLESPACE "NEWSTMPTABSPACE"
	TEMPFILE 'NEWSTMPTABSPACE'
	SIZE 1600M REUSE AUTOEXTEND ON;
	
CREATE SMALLFILE TABLESPACE "NEWSREGTABSPACE"
	DATAFILE 'NEWSREGTABSPACE'
	SIZE 1600M REUSE AUTOEXTEND ON 
	NEXT 40M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;
	
CREATE SMALLFILE TABLESPACE "NEWSINDEXTABSPACE"
	DATAFILE 'NEWSINDEXTABSPACE'
	SIZE 1600M REUSE AUTOEXTEND ON 
	NEXT 40M MAXSIZE UNLIMITED LOGGING 
	EXTENT MANAGEMENT LOCAL 
	SEGMENT SPACE MANAGEMENT AUTO;	

--------------------------------------
-- CREATE THE USER\SCHEMA
--------------------------------------
CREATE USER "HOMEPAGE" PROFILE "DEFAULT" IDENTIFIED BY "&1" DEFAULT TABLESPACE "HOMEPAGEREGTABSPACE" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
COMMIT;

-------------------------------------
-- ALTER HOMEPAGE USER, assumes already created
-------------------------------------
GRANT "CONNECT" TO "HOMEPAGE";
ALTER USER "HOMEPAGE" DEFAULT ROLE ALL;
GRANT ALTER TABLESPACE TO "HOMEPAGE";
GRANT UNLIMITED TABLESPACE TO "HOMEPAGE";

--------------------------------------
-- CREATE THE TABLES
--------------------------------------
CREATE TABLE "HOMEPAGE"."HOMEPAGE_SCHEMA" ( 
	COMPKEY VARCHAR2(36) NOT NULL,
	DBSCHEMAVER NUMBER(5, 0) NOT NULL,
	RELEASEVER VARCHAR2(32) NOT NULL
) 
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."PERSON"  (
	PERSON_ID VARCHAR2(36) NOT NULL,
	DISPLAYNAME VARCHAR2(256) NOT NULL,
	EXID VARCHAR2(256) NOT NULL,
	USER_MAIL VARCHAR2(256)
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."LOGINNAME" (
	PERSON_ID VARCHAR2(36) NOT NULL,
	LOGINNAME VARCHAR2(256) NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";  

CREATE TABLE "HOMEPAGE"."HP_UI"  (
	UI_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	PERSON_LANG VARCHAR2(5) NOT NULL,
	LAST_VISIT TIMESTAMP NOT NULL,
	WELCOME_MODE NUMBER(5,0) DEFAULT 1 NOT NULL,
	SHOW_DISABLED_WIDGETS NUMBER(5,0) DEFAULT 0 NOT NULL		
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."HP_TAB"  (
	TAB_ID VARCHAR2(36) NOT NULL,
	DEFAULT_NAME VARCHAR2(36) NOT NULL,
	DEFAULT_N_COLUMNS NUMBER(5,0),
	IS_NAME_CHANGEABLE NUMBER(5,0)	
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."HP_TAB_INST"  (
	TAB_INST_ID VARCHAR2(36) NOT NULL,
	TAB_ID VARCHAR2(36) NOT NULL,
	UI_ID VARCHAR2(36) NOT NULL,
	TAB_NAME VARCHAR2(36),
	N_COLUMNS NUMBER(5,0),
	LAST_MODIFIED TIMESTAMP NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."HP_WIDGET_INST"  (
	WIDGET_INST_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL,
	TAB_INST_ID VARCHAR2(36) NOT NULL,
	WIDGET_SETTING VARCHAR2(2048),
	CONTAINER VARCHAR2(36),
	ORDER_SEQUENCE NUMBER(5,0),
	IS_FIXED NUMBER(5,0),
	IS_TOGGLED NUMBER(5,0),
	LAST_MODIFIED TIMESTAMP NOT NULL,
	LAST_UPDATED TIMESTAMP
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."WIDGET" (
	WIDGET_ID VARCHAR2(36) NOT NULL,
	WIDGET_TITLE VARCHAR2(256) NOT NULL,
	WIDGET_TEXT VARCHAR2(256),
	WIDGET_URL VARCHAR2(256) NOT NULL,
	WIDGET_ICON VARCHAR2(256),
	WIDGET_ENABLED NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_SYSTEM NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_HOMEPAGE_SPECIFIC NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_PREVIEW_IMAGE VARCHAR2(256),
	WIDGET_CATEGORY VARCHAR2(36) NOT NULL,
	WIDGET_IS_DEFAULT_OPENED NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_MULTIPLE_INSTANCES NUMBER(5,0) DEFAULT 0 NOT NULL,
	WIDGET_MARKED_CACHABLE NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."HP_WIDGET_TAB" (
	WIDGET_TAB_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL,
	TAB_ID VARCHAR2(36) NOT NULL,
	TYPE VARCHAR2(36) NOT NULL
)	
TABLESPACE "HOMEPAGEREGTABSPACE";

CREATE TABLE "HOMEPAGE"."PREREQ" (
	PREREQ_ID VARCHAR2(36) NOT NULL,
	APP_ID VARCHAR2(36) NOT NULL,
	WIDGET_ID VARCHAR2(36) NOT NULL
)
TABLESPACE "HOMEPAGEREGTABSPACE";	

CREATE TABLE "HOMEPAGE"."NT_NOTIFICATION"  (
	  NOTIFICATION_ID VARCHAR2(36) NOT NULL,
	  NOTIFICATION_SOURCE VARCHAR2(36) NOT NULL,
	  NOTIFICATION_TYPE VARCHAR2(256) NOT NULL,
	  DATETIME_STAMP TIMESTAMP NOT NULL,
	  SENDER_EXID VARCHAR2(36) NOT NULL,
	  SUBJECT VARCHAR2(256),
	  MESSAGE VARCHAR2(2048),
	  CONTAINER_NAME VARCHAR2(256),
	  CONTAINER_URL VARCHAR2(2048),
	  ITEM_NAME VARCHAR2(256),
	  ITEM_URL VARCHAR2(2048)
)
TABLESPACE "HPNTREGTABSPACE";

CREATE TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT" (
		  ID VARCHAR2(36) NOT NULL,
		  NOTIFICATION_ID VARCHAR2(36) NOT NULL,
		  RECIPIENT_EXID VARCHAR2(36) NOT NULL		  
)
TABLESPACE "HPNTREGTABSPACE";
--------------------------------------
-- CREATE THE CONSTRAINTS
--------------------------------------

ALTER TABLE "HOMEPAGE"."PERSON" 
    ADD (CONSTRAINT "PK_PERSON_ID" PRIMARY KEY ("PERSON_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."HP_UI"
    ADD (CONSTRAINT "PK_HP_UI" PRIMARY KEY ("UI_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");   

ALTER TABLE "HOMEPAGE"."HP_TAB"
    ADD (CONSTRAINT "PK_HP_TAB" PRIMARY KEY("TAB_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."HP_TAB_INST"
    ADD (CONSTRAINT "PK_HP_TAB_INST" PRIMARY KEY("TAB_INST_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
        
ALTER TABLE "HOMEPAGE"."WIDGET"
	ADD (CONSTRAINT "PK_WIDGET" PRIMARY KEY ("WIDGET_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB"
	ADD (CONSTRAINT "PK_WIDGET_TAB" PRIMARY KEY ("WIDGET_TAB_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."PREREQ" 
	ADD (CONSTRAINT "PK_PREREQ" PRIMARY KEY ("PREREQ_ID")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST"
	ADD (CONSTRAINT "PK_HP_WIDGET_INST" PRIMARY KEY ("WIDGET_INST_ID")
	USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");

ALTER TABLE "HOMEPAGE"."LOGINNAME"
	ADD (CONSTRAINT "PK_LOGINNAME_ID" PRIMARY KEY ("PERSON_ID","LOGINNAME")
    USING INDEX TABLESPACE "HOMEPAGEINDEXTABSPACE");
    
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION"
	ADD (CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NOTIFICATION_ID")
	USING INDEX TABLESPACE "HPNTINDEXTABSPACE");
	
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT"
	ADD (CONSTRAINT "PK_NOTIF_RECIP" PRIMARY KEY ("ID")
	USING INDEX TABLESPACE "HPNTINDEXTABSPACE");

ALTER TABLE "HOMEPAGE"."LOGINNAME"
	ADD CONSTRAINT "FK_LN_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES "HOMEPAGE"."PERSON" ("PERSON_ID");

ALTER TABLE "HOMEPAGE"."HP_UI"
    ADD CONSTRAINT "FK_UI_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES "HOMEPAGE"."PERSON" ("PERSON_ID");
		
ALTER TABLE "HOMEPAGE"."HP_TAB_INST"
    ADD CONSTRAINT "FK_UI_ID" FOREIGN KEY ("UI_ID")
	REFERENCES "HOMEPAGE"."HP_UI" ("UI_ID");

ALTER TABLE "HOMEPAGE"."HP_TAB_INST"
    ADD CONSTRAINT "FK_TAB_INST_TAB_ID" FOREIGN KEY ("TAB_ID")
	REFERENCES "HOMEPAGE"."HP_TAB" ("TAB_ID");
	
ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST"
    ADD CONSTRAINT "FK_WIDGET_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID");
		
ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST"
    ADD CONSTRAINT "FK_TAB_INST_ID" FOREIGN KEY ("TAB_INST_ID")
	REFERENCES "HOMEPAGE"."HP_TAB_INST" ("TAB_INST_ID");
	
ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB"	
    ADD CONSTRAINT "FK_WID_TAB_WID_ID" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID");
	
ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB"	
    ADD CONSTRAINT "FK_WID_TAB_TAB_ID" FOREIGN KEY ("TAB_ID")
	REFERENCES "HOMEPAGE"."HP_TAB" ("TAB_ID");
	
ALTER TABLE "HOMEPAGE"."PREREQ"
	ADD CONSTRAINT "FK_PREREQ_WIDGET" FOREIGN KEY ("WIDGET_ID")
	REFERENCES "HOMEPAGE"."WIDGET" ("WIDGET_ID")
	ON DELETE CASCADE;
	
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT"
	ADD CONSTRAINT "FK_RECIP_NOTIF" FOREIGN KEY ("NOTIFICATION_ID")
	REFERENCES "HOMEPAGE"."NT_NOTIFICATION" ("NOTIFICATION_ID")
	ON DELETE CASCADE;
	
ALTER TABLE "HOMEPAGE"."LOGINNAME"
	ADD CONSTRAINT LOGINNAME_UNIQUE UNIQUE(LOGINNAME);
	
--------------------------------------
-- CREATE THE INDEXES
--------------------------------------

CREATE INDEX "HOMEPAGE"."WIDGET_INST"
	ON "HOMEPAGE"."HP_WIDGET_INST"("TAB_INST_ID" ASC, "WIDGET_ID" ASC) TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE UNIQUE INDEX "HOMEPAGE"."PERSON_EXID"
    ON "HOMEPAGE"."PERSON"("EXID") TABLESPACE "HPNTINDEXTABSPACE";
    
CREATE INDEX "HOMEPAGE"."PERSON_USER_MAIL"
	ON "HOMEPAGE"."PERSON"("USER_MAIL") TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE INDEX "HOMEPAGE"."HP_UI_PERSON_ID_INDEX"
	ON "HOMEPAGE"."HP_UI"("PERSON_ID") TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NT_NOTIFICATION_EXID_INDEX"
	ON "HOMEPAGE"."NT_NOTIFICATION"("SENDER_EXID") TABLESPACE "HPNTINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NT_NOTIF_RECT_EXID_INDEX"
	ON "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT" ("RECIPIENT_EXID") TABLESPACE "HPNTINDEXTABSPACE";
	
CREATE INDEX "HOMEPAGE"."NT_NOTIF_RECT_NID_INDEX"
	ON "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT"("NOTIFICATION_ID") TABLESPACE "HPNTINDEXTABSPACE";

	
--------------------------------------
-- CREATE THE VIEWS
--------------------------------------

-- TBD

--------------------------------------
-- POPULATE THE TABLES
--------------------------------------

INSERT INTO "HOMEPAGE"."HOMEPAGE_SCHEMA"
	( "COMPKEY", "DBSCHEMAVER", "RELEASEVER") 
VALUES 
	( 'HOMEPAGE', 7, '2.5.0.0');


--------------------------------------
-- ENABLE ROW MOVEMENT (for backup, epxort/import)
--------------------------------------
ALTER TABLE "HOMEPAGE"."HOMEPAGE_SCHEMA" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."PERSON" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."LOGINNAME" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_UI" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_TAB" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_TAB_INST" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_WIDGET_INST" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."WIDGET" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."HP_WIDGET_TAB" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."PREREQ" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NT_NOTIFICATION_RECIPIENT" ENABLE ROW MOVEMENT;

COMMIT;

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- STARTING OF THE DEFINITION FOR THE NEWS REPOSITORY DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------
-- NEWS REPOSITORY - CREATE THE TABLES
----------------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_SOURCE (
	SOURCE_ID VARCHAR2(36) NOT NULL,
	SOURCE VARCHAR2(36) NOT NULL,
	CONTAINER_ID VARCHAR2(36) NOT NULL,
	CONTAINER_NAME VARCHAR2(256),
	CONTAINER_URL VARCHAR2(2048),
	ENTRY_ID  VARCHAR2(36),
	ENTRY_NAME VARCHAR2(256),
	ENTRY_URL VARCHAR2(2048),
	ENTRY_ATOM_URL VARCHAR2(2048),
	IS_ACL NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";


CREATE TABLE HOMEPAGE.NR_SUBSCRIPTION  (
	SUBSCRIPTION_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	SOURCE_ID VARCHAR2(36) NOT NULL,
	IS_EXPLICIT NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";


CREATE TABLE HOMEPAGE.NR_NEWS_RECORDS (
	NEWS_RECORDS_ID VARCHAR2(36) NOT NULL,
	EVENT_NAME VARCHAR2(256) NOT NULL,
    READER_ID VARCHAR2(36),
    SOURCE VARCHAR2(36),
    CONTAINER_ID VARCHAR2(36),
    CONTAINER_NAME VARCHAR2(256),
    CONTAINER_URL VARCHAR2(2048),
    ENTRY_ID VARCHAR2(36),
    ENTRY_NAME VARCHAR2(256),
    ENTRY_URL VARCHAR2(2048),
    ENTRY_ATOM_URL VARCHAR2(2048),
    CREATION_DATE TIMESTAMP NOT NULL,
    IS_INBOX NUMBER(5,0) DEFAULT 0 NOT NULL,
    IS_SAVED NUMBER(5,0) DEFAULT 0 NOT NULL,
    IS_TOP_STORY NUMBER(5,0) DEFAULT 0 NOT NULL,
    IS_PUBLIC NUMBER(5,0) NOT NULL,
    IS_MAILED NUMBER(5,0) NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL,
    BRIEF_DESC VARCHAR2(256),
    IS_BRIEF_DESC_RTL NUMBER(5,0) DEFAULT 0 NOT NULL,
    ACTOR_UUID VARCHAR2(36),
    EVENT_RECORD_UUID VARCHAR2(36) NOT NULL,
    RELATED_COMM_UUID VARCHAR2(36),
    RELATED_COMM_NAME VARCHAR2(256),
    TAGS CLOB,
    META_TEMPLATE CLOB NOT NULL
) 
TABLESPACE "NEWSREGTABSPACE";



CREATE TABLE HOMEPAGE.NR_TEMPLATE (
	TEMPLATE_ID VARCHAR2(36) NOT NULL,
 	NAME VARCHAR2(256) NOT NULL,
 	FORMAT VARCHAR2(256) NOT NULL,
 	DATA_SOURCE_STRING VARCHAR2(256) NOT NULL,
 	NO_VALUES NUMBER(5,0) DEFAULT 0 NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";



----------------------------------------------------------------------------
-- NEWS REPOSITORY -  CREATE THE CONSTRAINTS
----------------------------------------------------------------------------
ALTER TABLE HOMEPAGE.NR_SOURCE
    ADD (CONSTRAINT "PK_SOURCE_ID" PRIMARY KEY ("SOURCE_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");    

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD (CONSTRAINT "PK_SUBSCRIPTION_ID" PRIMARY KEY ("SUBSCRIPTION_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_NEWS_RECORDS
    ADD (CONSTRAINT "PK_NR_NEWS_RECORDS" PRIMARY KEY ("NEWS_RECORDS_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE HOMEPAGE.NR_TEMPLATE 
    ADD (CONSTRAINT "PK_TEMPLATE_ID" PRIMARY KEY ("TEMPLATE_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");    

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT "FK_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");

ALTER TABLE HOMEPAGE.NR_SUBSCRIPTION
    ADD CONSTRAINT "FK_SOURCE_ID" FOREIGN KEY ("SOURCE_ID")
	REFERENCES HOMEPAGE.NR_SOURCE ("SOURCE_ID");	

----------------------------------------------------------------------------
-- NEWS REPOSITORY -  CREATE THE INDEXES
----------------------------------------------------------------------------
CREATE UNIQUE INDEX HOMEPAGE.NR_SUBSCRIPTION_IX_UNIQUE
	ON HOMEPAGE.NR_SUBSCRIPTION("PERSON_ID" ASC, "SOURCE_ID" ASC) TABLESPACE "NEWSINDEXTABSPACE";

--------------------------------------
-- ENABLE ROW MOVEMENT (for backup, epxort/import)
--------------------------------------
ALTER TABLE "HOMEPAGE"."NR_SOURCE" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_SUBSCRIPTION" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_NEWS_RECORDS" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_TEMPLATE" ENABLE ROW MOVEMENT;
	
-----------------------------------------------------------------------------
-- NEWS REPOSITORY -  RUN STATS
-----------------------------------------------------------------------------
-- TODO


COMMIT;
	


------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
-- END OF THE DEFINITION FOR THE NEWS REPOSITORY DATABASE
------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

--------------------------------------
-- DISCONNECT
--------------------------------------
DISCONNECT ALL;

QUIT;
