-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
-- 1) START ADDING INDEXES FOR HOMEPAGE TABLES
----------------------------------------------------
--CREATE INDEX "HOMEPAGE"."TAB_INST_UI_ID_IDX" 
--	ON "HOMEPAGE"."HP_TAB_INST"("UI_ID") TABLESPACE "HPNTINDEXTABSPACE";	


--CREATE INDEX "HOMEPAGE"."HP_WIDGET_INST_TAB_INST_ID_IDX"
--	ON "HOMEPAGE"."HP_WIDGET_INST"("TAB_INST_ID") TABLESPACE "HPNTINDEXTABSPACE";

----------------------------------------------------
-- END ADDING INDEXES FOR HOMEPAGE TABLES
----------------------------------------------------



-------------------------------------------------------------------
-- 2) START ADDING NEW TABLES FOR NEWS REPOSITORY AND EMAIL DIGEST
-------------------------------------------------------------------

-- NEW REPOSITORY
CREATE TABLE HOMEPAGE.NR_EVENT_RECORDS  (
	EVENT_RECORD_ID VARCHAR2(36) NOT NULL,
	EVENT_RECORD_CONTENT BLOB,
	IS_ACL NUMBER(5,0) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

-- EMAIL DIGEST
CREATE TABLE HOMEPAGE.EMD_RECIPIENTS (
	RECIPIENT_ID VARCHAR2(36) NOT NULL,
	PERSON_ID VARCHAR2(36) NOT NULL,
	FREQUENCY_UPDATE NUMBER(5,0) NOT NULL,
	LAST_SENT_UPDATE TIMESTAMP NOT NULL,
	MAIL_DOMAIN VARCHAR2(256) NOT NULL,
	MAIL_ADDRESS  VARCHAR2(256) NOT NULL
)
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.EMD_JOBS  (
	JOB_ID VARCHAR2(36) NOT NULL,
	JOB_FREQUENCY NUMBER(5,0) NOT NULL,
	NEXT_EXEC_TIME TIMESTAMP NOT NULL,
	DUE_DATE_EXEC_TIME TIMESTAMP,
	START_JOB TIMESTAMP,
	END_JOB TIMESTAMP,
	STATUS VARCHAR2(36),
	N_PERSONS_TO_UPDATE NUMBER(10,0),
	AVG_EXEC_JOB NUMBER(10,0)
)
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.EMD_JOBS_STATS (
	STAT_ID VARCHAR2(36) NOT NULL,
	JOB_ID VARCHAR2(36) NOT NULL,
	START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    EXEC_TIME NUMBER(10,0),
    N_PERSONS_UPDATED NUMBER(10,0)
)
TABLESPACE "NEWSREGTABSPACE";


-- NEWS REPOSITORY CONSTRAINTS
ALTER TABLE "HOMEPAGE"."NR_EVENT_RECORDS"
    ADD (CONSTRAINT "PK_EVENT_RECORD_ID" PRIMARY KEY("EVENT_RECORD_ID")
	USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

-- EMAIL DIGEST CONSTRAINTS
ALTER TABLE "HOMEPAGE"."EMD_RECIPIENTS"
    ADD (CONSTRAINT "PK_RECIPIENT_ID" PRIMARY KEY("RECIPIENT_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");   

ALTER TABLE "HOMEPAGE"."EMD_JOBS"
    ADD (CONSTRAINT "PK_JOB_ID" PRIMARY KEY("JOB_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE "HOMEPAGE"."EMD_JOBS_STATS"
    ADD (CONSTRAINT "PK_STAT_ID" PRIMARY KEY("STAT_ID")
    USING INDEX TABLESPACE "NEWSINDEXTABSPACE");

ALTER TABLE "HOMEPAGE"."EMD_RECIPIENTS"
    ADD CONSTRAINT "FK_REC_PERSON_ID" FOREIGN KEY ("PERSON_ID")
	REFERENCES HOMEPAGE.PERSON ("PERSON_ID");
	
ALTER TABLE "HOMEPAGE"."EMD_JOBS_STATS"
    ADD CONSTRAINT "FK_JOB_ID" FOREIGN KEY ("JOB_ID")
	REFERENCES HOMEPAGE.EMD_JOBS ("JOB_ID");

ALTER TABLE "HOMEPAGE"."EMD_JOBS"
	ADD CONSTRAINT UNIQUE_JOB_FREQ UNIQUE("JOB_FREQUENCY");

------------------------------------------------------------------
-- END ADDING NEW TABLES FOR NEWS REPOSITORY AND EMAIL DIGIEST
------------------------------------------------------------------

-------------------------------------------------------------------
-- 3) START ADDING INDEXES FOR NEWS REPOSITORY AND EMAIL DIGIEST
-------------------------------------------------------------------

-- NEW REPOSITORY INDEXES
--CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_READER_IDX"
--	ON HOMEPAGE.NR_NEWS_RECORDS("READER_ID") TABLESPACE "NEWSINDEXTABSPACE";

--CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_ACTOR_IDX"
--	ON HOMEPAGE.NR_NEWS_RECORDS("ACTOR_UUID") TABLESPACE "NEWSINDEXTABSPACE";

--CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_SOURCE_IDX"
--	ON HOMEPAGE.NR_NEWS_RECORDS("SOURCE") TABLESPACE "NEWSINDEXTABSPACE";

--CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_CONTAINER_IDX"
--	ON HOMEPAGE.NR_NEWS_RECORDS("CONTAINER_ID") TABLESPACE "NEWSINDEXTABSPACE";
	
--CREATE INDEX "HOMEPAGE"."NR_NEWS_RECORDS_DATE_IDX"
--	ON HOMEPAGE.NR_NEWS_RECORDS("CREATION_DATE" DESC) TABLESPACE "NEWSINDEXTABSPACE";

--CREATE INDEX HOMEPAGE.NR_NEWS_RECORDS_EVENT_IDX
--	ON HOMEPAGE.NR_NEWS_RECORDS("EVENT_RECORD_UUID") TABLESPACE "NEWSINDEXTABSPACE";	
	
-- EMAIL DIGEST INDEXES
CREATE INDEX "HOMEPAGE"."EMD_RECIPIENTS_SENT_UPDATE_IDX"
	ON HOMEPAGE.EMD_RECIPIENTS("LAST_SENT_UPDATE" DESC) TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."EMD_RECIPIENTS_MAIL_DOMAIN_IDX"
	ON HOMEPAGE.EMD_RECIPIENTS("MAIL_DOMAIN" DESC) TABLESPACE "NEWSINDEXTABSPACE";
	
-------------------------------------------------------------------
-- END ADDING INDEXES FOR NEWS REPOSITORY AND EMAIL DIGIEST
-------------------------------------------------------------------

-------------------------------------------------------------------
-- 4) START ADDING SCHEDULER TABLES
-------------------------------------------------------------------
CREATE TABLE HOMEPAGE.NR_SCHEDULER_TASK (
	TASKID NUMBER(19) NOT NULL,
	VERSION VARCHAR2(5) NOT NULL,
   	ROW_VERSION NUMBER(10) NOT NULL,
   	TASKTYPE NUMBER(10) NOT NULL,
   	TASKSUSPENDED NUMBER(1) NOT NULL,
   	CANCELLED NUMBER(1) NOT NULL,
   	NEXTFIRETIME NUMBER(19) NOT NULL,
   	STARTBYINTERVAL VARCHAR2(254),
   	STARTBYTIME NUMBER(19),
   	VALIDFROMTIME NUMBER(19),
   	VALIDTOTIME NUMBER(19),
   	REPEATINTERVAL VARCHAR2(254),
   	MAXREPEATS NUMBER(10) NOT NULL,
   	REPEATSLEFT NUMBER(10) NOT NULL,
   	TASKINFO BLOB,
   	NAME VARCHAR2(254),
   	AUTOPURGE NUMBER(10) NOT NULL,
   	FAILUREACTION NUMBER(10),
   	MAXATTEMPTS NUMBER(10),
   	QOS NUMBER(10),
   	PARTITIONID NUMBER(10),
   	OWNERTOKEN VARCHAR2(200) NOT NULL,
   	CREATETIME NUMBER(19) NOT NULL,
   	PRIMARY KEY (TASKID)
)
TABLESPACE "NEWSREGTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_SCHEDULER_TASK_IDX1 "
	ON "HOMEPAGE"."NR_SCHEDULER_TASK" ("TASKID", "OWNERTOKEN") TABLESPACE "NEWSINDEXTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_SCHEDULER_TASK_IDX2" 
	ON "HOMEPAGE"."NR_SCHEDULER_TASK" ("NEXTFIRETIME" ASC, "REPEATSLEFT", "PARTITIONID") TABLESPACE "NEWSINDEXTABSPACE";

CREATE TABLE HOMEPAGE.NR_SCHEDULER_TREG (
	REGKEY VARCHAR2(254) NOT NULL,
	REGVALUE VARCHAR2(254),
	PRIMARY KEY (REGKEY)
) 
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.NR_SCHEDULER_LMGR (
	LEASENAME VARCHAR2(254) NOT NULL,
	LEASEOWNER VARCHAR2(254),
	LEASE_EXPIRE_TIME NUMBER(19),
	DISABLED VARCHAR2(254),
	PRIMARY KEY (LEASENAME)
)
TABLESPACE "NEWSREGTABSPACE";

CREATE TABLE HOMEPAGE.NR_SCHEDULER_LMPR (
	LEASENAME VARCHAR2(254) NOT NULL,
	NAME VARCHAR2(254) NOT NULL,
	VALUE VARCHAR2(254) NOT NULL 
)
TABLESPACE "NEWSREGTABSPACE";

CREATE INDEX "HOMEPAGE"."NR_SCHEDULER_LMPR_IDX1"
	ON "HOMEPAGE"."NR_SCHEDULER_LMPR" ("LEASENAME", "NAME") TABLESPACE "NEWSINDEXTABSPACE";


	
-------------------------------------------------------------------
-- END ADDING SCHEDULER TABLES
-------------------------------------------------------------------

-------------------------------------------------------------------
-- 5) START ENABLE ROW MOVEMENT
-------------------------------------------------------------------

-- News Repository
ALTER TABLE "HOMEPAGE"."NR_EVENT_RECORDS" ENABLE ROW MOVEMENT;

-- Email digest
ALTER TABLE "HOMEPAGE"."EMD_RECIPIENTS" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."EMD_JOBS" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."EMD_JOBS_STATS" ENABLE ROW MOVEMENT;

-- Scheduler
ALTER TABLE "HOMEPAGE"."NR_SCHEDULER_TASK" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_SCHEDULER_TREG" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_SCHEDULER_LMGR" ENABLE ROW MOVEMENT;
ALTER TABLE "HOMEPAGE"."NR_SCHEDULER_LMPR" ENABLE ROW MOVEMENT;	

-------------------------------------------------------------------
-- END START ENABLE ROW MOVEMENT
-------------------------------------------------------------------



-- Updating the schema version from 10 to 11
UPDATE  HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER = 11
WHERE   DBSCHEMAVER = 10;

COMMIT;

--------------------------------------
-- DISCONNECT
--------------------------------------
DISCONNECT ALL;

QUIT;