-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2001, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

-- 5724_S68                                              
--					start	FIXUP 460
-- +++++++++++++++++++++++++++++++++++++++++++++
-- +++++++++++++++++++++++++++++++++++++++++++++

------------------------------------------------
-- INCLUDE FIX UP 460 FOR HOMEPAGE
------------------------------------------------

{include.hp-fixup460.sql}

------------------------------------------------
-- INCLUDE FIX UP 460 FOR NEWS
------------------------------------------------

{include.news-fixup460.sql}



-- DROPPING FK
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST DROP CONSTRAINT FK_AS_SEEDLIST_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.METRIC_STAT DROP CONSTRAINT FK_METRIC_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE DROP CONSTRAINT FK_BRD_OBJ_REFERENCE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.MT_CFG_FILES DROP CONSTRAINT FK_CFG_FILE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT DROP CONSTRAINT FK_NEWS_COMMENT_CONTENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB DROP CONSTRAINT FK_WIDGET_TAB_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS DROP CONSTRAINT FK_AGG_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NETWORK DROP CONSTRAINT FK_NETWORK_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS DROP CONSTRAINT FK_MENT_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS DROP CONSTRAINT FK_EXT_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS DROP CONSTRAINT FK_WIKIS_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS DROP CONSTRAINT FK_AS_CNT_INDEX_STATS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.PREREQ DROP CONSTRAINT FK_PREREQ_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS DROP CONSTRAINT FK_ACT_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW DROP CONSTRAINT FK_PRF_VIEW_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE DROP CONSTRAINT FK_DEL_STORIES_QUEUE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_MENTIONS DROP CONSTRAINT FK_BOARD_MENTIONS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB_INST DROP CONSTRAINT FK_TAB_INST_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS DROP CONSTRAINT FK_RESP_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESOURCE DROP CONSTRAINT FK_RESOURCE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_WIDGET_INST DROP CONSTRAINT FK_WIDGET_INST_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_UI DROP CONSTRAINT FK_UI_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS DROP CONSTRAINT FK_SU_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS DROP CONSTRAINT FK_TOPICS_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS DROP CONSTRAINT FK_BOARD_CURRENT_STATUS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK DROP CONSTRAINT FK_NEWS_STATUS_NETWORK_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_USER_PREFS DROP CONSTRAINT FK_USER_PREFS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_COUNTS DROP CONSTRAINT FK_AS_COUNT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS DROP CONSTRAINT FK_PROF_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES DROP CONSTRAINT FK_STORIES_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS DROP CONSTRAINT FK_COMM_SETTINGS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB DROP CONSTRAINT FK_TAB_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS DROP CONSTRAINT FK_BRD_RECOMM_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW DROP CONSTRAINT FK_COMM_PERSON_FOLLOW_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.WIDGET DROP CONSTRAINT FK_WIDGET_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.IMG_CACHE DROP CONSTRAINT FK_IMG_CACHE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT DROP CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD DROP CONSTRAINT FK_BOARD_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_FOLLOWS DROP CONSTRAINT FK_FOLLOWS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW DROP CONSTRAINT FK_COMM_FOLLOW_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS DROP CONSTRAINT FK_NOT_REC_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NT_REPLYTO DROP CONSTRAINT FK_REPLYTO_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_COMMENTS DROP CONSTRAINT FK_BOARD_COMMENTS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_FILES_READERS DROP CONSTRAINT FK_FILES_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW DROP CONSTRAINT FK_DISCOVERY_VIEW_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF DROP CONSTRAINT FK_EMD_RES_PREF_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT DROP CONSTRAINT FK_STORIES_CONTENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.EMD_TRANCHE DROP CONSTRAINT FK_EMD_TRANCHE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS DROP CONSTRAINT FK_BOOK_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.LOGINNAME DROP CONSTRAINT FK_LN_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.PERSON DROP CONSTRAINT FK_PERSON_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS DROP CONSTRAINT FK_CFG_SET_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE DROP CONSTRAINT FK_ENTRIES_ARCHIVE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_SAVED_READERS DROP CONSTRAINT FK_SAVED_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS DROP CONSTRAINT FK_COMM_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS DROP CONSTRAINT FK_NOT_SENT_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT DROP CONSTRAINT FK_STATUS_COMMENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE DROP CONSTRAINT FK_SOURCE_TYPE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_TAGS_READERS DROP CONSTRAINT FK_TAGS_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS DROP CONSTRAINT FK_BLOGS_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS DROP CONSTRAINT FK_EMD_EMAIL_PREFS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES DROP CONSTRAINT FK_ENTRIES_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_SOURCE DROP CONSTRAINT FK_SOURCE_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_ENTRIES DROP CONSTRAINT FK_BOARD_ENTRIES_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS DROP CONSTRAINT FK_ACTIVITIES_READERS_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO DROP CONSTRAINT FK_EMD_TRANCHE_INFO_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT DROP CONSTRAINT FK_STATUS_CONTENT_ORG_ID;
COMMIT;
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS DROP CONSTRAINT FK_FORUMS_READERS_ORG_ID;
COMMIT;

-- DROPPING INDEXES
DROP INDEX HOMEPAGE.UNQ_ORG_EXID;
COMMIT;
DROP INDEX HOMEPAGE.PERSON_EXID;
COMMIT;
DROP INDEX HOMEPAGE.LOGINNAME_UNIQUE;
COMMIT;
DROP INDEX HOMEPAGE.UNQ_ORG_NAME;
COMMIT;
DROP INDEX HOMEPAGE.NR_SRC_TYPE_ORG_UIDX;
COMMIT;
DROP INDEX HOMEPAGE.SEQ_NUMBER_UNIQUE;
COMMIT;
DROP INDEX HOMEPAGE.AGGREGATED_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.RESPONSES_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.PROFILES_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.COMM_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.BLOGS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.BOOKMARKS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.FILES_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.FORUMS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.WIKIS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.TAGS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.STATUS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.EXTERNAL_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.DISCOVERY_VIEW_ORG_IDX;
COMMIT;
DROP INDEX HOMEPAGE.PROFILES_VIEW_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.PROFILES_VIEW_ORG_IDX;
COMMIT;
DROP INDEX HOMEPAGE.NOTIFICA_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.NOT_REC_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.SAVED_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.TOPICS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.MENTIONS_READERS_SRC_IX;
COMMIT;
DROP INDEX HOMEPAGE.IMG_CACHE_URL_IDX;
COMMIT;
DROP INDEX HOMEPAGE.NR_AS_COUNT_ORG_IDX;
COMMIT;

-- UPDATE NOT NULL ORGANIZATION_ID

 DECLARE CURSOR cur IS SELECT ORGANIZATION_ID PK FROM HOMEPAGE.MT_ORGANIZATION WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.MT_ORGANIZATION SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
COMMIT;

 CREATE INDEX HOMEPAGE.PERS_TMP_ORG_IDX  ON HOMEPAGE.PERSON (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT PERSON_ID PK FROM HOMEPAGE.PERSON WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.PERSON SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.PERS_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.HP_U_TMP_ORG_IDX  ON HOMEPAGE.HP_USER_PREFS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT USER_PREFS_ID PK FROM HOMEPAGE.HP_USER_PREFS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.HP_USER_PREFS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.HP_U_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.LOGI_TMP_ORG_IDX  ON HOMEPAGE.LOGINNAME (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT PERSON_ID PK FROM HOMEPAGE.LOGINNAME WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.LOGINNAME SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.LOGI_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.HP_U_TMP_ORG_IDX  ON HOMEPAGE.HP_UI (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT UI_ID PK FROM HOMEPAGE.HP_UI WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.HP_UI SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.HP_U_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.HP_T_TMP_ORG_IDX  ON HOMEPAGE.HP_TAB (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT TAB_ID PK FROM HOMEPAGE.HP_TAB WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.HP_TAB SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.HP_T_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.HP_T_TMP_ORG_IDX  ON HOMEPAGE.HP_TAB_INST (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT TAB_INST_ID PK FROM HOMEPAGE.HP_TAB_INST WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.HP_TAB_INST SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.HP_T_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.WIDG_TMP_ORG_IDX  ON HOMEPAGE.WIDGET (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT WIDGET_ID PK FROM HOMEPAGE.WIDGET WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.WIDGET SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.WIDG_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.HP_W_TMP_ORG_IDX  ON HOMEPAGE.HP_WIDGET_TAB (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT WIDGET_TAB_ID PK FROM HOMEPAGE.HP_WIDGET_TAB WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.HP_WIDGET_TAB SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.HP_W_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.HP_W_TMP_ORG_IDX  ON HOMEPAGE.HP_WIDGET_INST (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT WIDGET_INST_ID PK FROM HOMEPAGE.HP_WIDGET_INST WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.HP_WIDGET_INST SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.HP_W_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.PRER_TMP_ORG_IDX  ON HOMEPAGE.PREREQ (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT PREREQ_ID PK FROM HOMEPAGE.PREREQ WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.PREREQ SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.PRER_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NT_R_TMP_ORG_IDX  ON HOMEPAGE.NT_REPLYTO (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT REPLYTO_NOTIFICATION_ID PK FROM HOMEPAGE.NT_REPLYTO WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NT_REPLYTO SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NT_R_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NT_R_TMP_ORG_IDX  ON HOMEPAGE.NT_REPLYTO_RECIPIENT (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT REPLYTO_RECIPIENT_ID PK FROM HOMEPAGE.NT_REPLYTO_RECIPIENT WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NT_REPLYTO_RECIPIENT SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NT_R_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.METR_TMP_ORG_IDX  ON HOMEPAGE.METRIC_STAT (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT METRIC_STAT_ID PK FROM HOMEPAGE.METRIC_STAT WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.METRIC_STAT SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.METR_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.MT_C_TMP_ORG_IDX  ON HOMEPAGE.MT_CFG_SETTINGS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT SETTING_ID PK FROM HOMEPAGE.MT_CFG_SETTINGS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.MT_CFG_SETTINGS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.MT_C_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.MT_C_TMP_ORG_IDX  ON HOMEPAGE.MT_CFG_FILES (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT FILE_ID PK FROM HOMEPAGE.MT_CFG_FILES WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.MT_CFG_FILES SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.MT_C_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_S_TMP_ORG_IDX  ON HOMEPAGE.NR_SOURCE_TYPE_DEFAULT (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT SOURCE_TYPE_ID PK FROM HOMEPAGE.NR_SOURCE_TYPE_DEFAULT WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_SOURCE_TYPE_DEFAULT SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_S_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_S_TMP_ORG_IDX  ON HOMEPAGE.NR_SOURCE_TYPE (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT SOURCE_TYPE_ID PK FROM HOMEPAGE.NR_SOURCE_TYPE WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_SOURCE_TYPE SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_S_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_S_TMP_ORG_IDX  ON HOMEPAGE.NR_SOURCE (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT SOURCE_ID PK FROM HOMEPAGE.NR_SOURCE WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_SOURCE SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_S_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_N_TMP_ORG_IDX  ON HOMEPAGE.NR_NEWS_STATUS_NETWORK (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT NEWS_STATUS_NETWORK_ID PK FROM HOMEPAGE.NR_NEWS_STATUS_NETWORK WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_NEWS_STATUS_NETWORK SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_N_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_N_TMP_ORG_IDX  ON HOMEPAGE.NR_NEWS_STATUS_COMMENT (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT NEWS_STATUS_COMMENT_ID PK FROM HOMEPAGE.NR_NEWS_STATUS_COMMENT WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_NEWS_STATUS_COMMENT SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_N_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_N_TMP_ORG_IDX  ON HOMEPAGE.NR_NEWS_STATUS_CONTENT (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT NEWS_STATUS_CONTENT_ID PK FROM HOMEPAGE.NR_NEWS_STATUS_CONTENT WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_NEWS_STATUS_CONTENT SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_N_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_N_TMP_ORG_IDX  ON HOMEPAGE.NR_NEWS_COMMENT_CONTENT (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT NEWS_COMMENT_CONTENT_ID PK FROM HOMEPAGE.NR_NEWS_COMMENT_CONTENT WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_NEWS_COMMENT_CONTENT SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_N_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_R_TMP_ORG_IDX  ON HOMEPAGE.NR_RESOURCE (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT RESOURCE_ID PK FROM HOMEPAGE.NR_RESOURCE WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_RESOURCE SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_R_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_F_TMP_ORG_IDX  ON HOMEPAGE.NR_FOLLOWS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT FOLLOW_ID PK FROM HOMEPAGE.NR_FOLLOWS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_FOLLOWS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_F_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_C_TMP_ORG_IDX  ON HOMEPAGE.NR_COMM_FOLLOW (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT COMM_FOLLOW_ID PK FROM HOMEPAGE.NR_COMM_FOLLOW WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_COMM_FOLLOW SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_C_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_S_TMP_ORG_IDX  ON HOMEPAGE.NR_STORIES_CONTENT (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT STORY_CONTENT_ID PK FROM HOMEPAGE.NR_STORIES_CONTENT WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_STORIES_CONTENT SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_S_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_N_TMP_ORG_IDX  ON HOMEPAGE.NR_NETWORK (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT NETWORK_ID PK FROM HOMEPAGE.NR_NETWORK WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_NETWORK SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_N_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.EMD__TMP_ORG_IDX  ON HOMEPAGE.EMD_RESOURCE_PREF (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT RESOURCE_PREF_ID PK FROM HOMEPAGE.EMD_RESOURCE_PREF WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.EMD_RESOURCE_PREF SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.EMD__TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.EMD__TMP_ORG_IDX  ON HOMEPAGE.EMD_TRANCHE (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT TRANCHE_ID PK FROM HOMEPAGE.EMD_TRANCHE WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.EMD_TRANCHE SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.EMD__TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.EMD__TMP_ORG_IDX  ON HOMEPAGE.EMD_TRANCHE_INFO (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT TRANCHE_INFO_ID PK FROM HOMEPAGE.EMD_TRANCHE_INFO WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.EMD_TRANCHE_INFO SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.EMD__TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.EMD__TMP_ORG_IDX  ON HOMEPAGE.EMD_EMAIL_PREFS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT EMAIL_PREFS_ID PK FROM HOMEPAGE.EMD_EMAIL_PREFS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.EMD_EMAIL_PREFS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.EMD__TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_C_TMP_ORG_IDX  ON HOMEPAGE.NR_COMM_PERSON_FOLLOW (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT COMM_PERSON_FOLLOW_ID PK FROM HOMEPAGE.NR_COMM_PERSON_FOLLOW WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_COMM_PERSON_FOLLOW SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_C_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_E_TMP_ORG_IDX  ON HOMEPAGE.NR_ENTRIES (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT ENTRY_ID PK FROM HOMEPAGE.NR_ENTRIES WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_ENTRIES SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_E_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_S_TMP_ORG_IDX  ON HOMEPAGE.NR_STORIES (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT STORY_ID PK FROM HOMEPAGE.NR_STORIES WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_STORIES SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_S_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_E_TMP_ORG_IDX  ON HOMEPAGE.NR_ENTRIES_ARCHIVE (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT ENTRY_ID PK FROM HOMEPAGE.NR_ENTRIES_ARCHIVE WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_ENTRIES_ARCHIVE SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_E_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_A_TMP_ORG_IDX  ON HOMEPAGE.NR_AGGREGATED_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_AGGREGATED_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_AGGREGATED_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_A_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_R_TMP_ORG_IDX  ON HOMEPAGE.NR_RESPONSES_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_RESPONSES_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_RESPONSES_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_R_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_P_TMP_ORG_IDX  ON HOMEPAGE.NR_PROFILES_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_PROFILES_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_PROFILES_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_P_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_C_TMP_ORG_IDX  ON HOMEPAGE.NR_COMMUNITIES_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_COMMUNITIES_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_COMMUNITIES_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_C_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_W_TMP_ORG_IDX  ON HOMEPAGE.NR_WIKIS_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_WIKIS_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_WIKIS_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_W_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.IMG__TMP_ORG_IDX  ON HOMEPAGE.IMG_CACHE (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT IMG_CACHE_ID PK FROM HOMEPAGE.IMG_CACHE WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.IMG_CACHE SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.IMG__TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_A_TMP_ORG_IDX  ON HOMEPAGE.NR_ACTIVITIES_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_ACTIVITIES_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_ACTIVITIES_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_A_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_B_TMP_ORG_IDX  ON HOMEPAGE.NR_BLOGS_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_BLOGS_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_BLOGS_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_B_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_B_TMP_ORG_IDX  ON HOMEPAGE.NR_BOOKMARKS_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_BOOKMARKS_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_BOOKMARKS_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_B_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_F_TMP_ORG_IDX  ON HOMEPAGE.NR_FILES_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_FILES_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_FILES_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_F_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_F_TMP_ORG_IDX  ON HOMEPAGE.NR_FORUMS_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_FORUMS_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_FORUMS_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_F_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_T_TMP_ORG_IDX  ON HOMEPAGE.NR_TAGS_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_TAGS_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_TAGS_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_T_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_S_TMP_ORG_IDX  ON HOMEPAGE.NR_STATUS_UPDATE_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_STATUS_UPDATE_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_STATUS_UPDATE_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_S_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_E_TMP_ORG_IDX  ON HOMEPAGE.NR_EXTERNAL_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_EXTERNAL_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_EXTERNAL_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_E_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_A_TMP_ORG_IDX  ON HOMEPAGE.NR_ACTIONABLE_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_ACTIONABLE_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_ACTIONABLE_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_A_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.BOAR_TMP_ORG_IDX  ON HOMEPAGE.BOARD (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT BOARD_ID PK FROM HOMEPAGE.BOARD WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.BOARD SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.BOAR_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_A_TMP_ORG_IDX  ON HOMEPAGE.NR_AS_COUNTS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT AS_COUNT_ID PK FROM HOMEPAGE.NR_AS_COUNTS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_AS_COUNTS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_A_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.BOAR_TMP_ORG_IDX  ON HOMEPAGE.BOARD_ENTRIES (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT ENTRY_ID PK FROM HOMEPAGE.BOARD_ENTRIES WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.BOARD_ENTRIES SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.BOAR_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.BOAR_TMP_ORG_IDX  ON HOMEPAGE.BOARD_COMMENTS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT COMMENT_ID PK FROM HOMEPAGE.BOARD_COMMENTS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.BOARD_COMMENTS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.BOAR_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.BOAR_TMP_ORG_IDX  ON HOMEPAGE.BOARD_OBJECT_REFERENCE (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT OBJECT_ID PK FROM HOMEPAGE.BOARD_OBJECT_REFERENCE WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.BOARD_OBJECT_REFERENCE SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.BOAR_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.BOAR_TMP_ORG_IDX  ON HOMEPAGE.BOARD_RECOMMENDATIONS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT RECOMMENDATION_ID PK FROM HOMEPAGE.BOARD_RECOMMENDATIONS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.BOARD_RECOMMENDATIONS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.BOAR_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.BOAR_TMP_ORG_IDX  ON HOMEPAGE.BOARD_CURRENT_STATUS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CURRENT_STATUS_ID PK FROM HOMEPAGE.BOARD_CURRENT_STATUS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.BOARD_CURRENT_STATUS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.BOAR_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.BOAR_TMP_ORG_IDX  ON HOMEPAGE.BOARD_MENTIONS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT BOARD_MENTIONS_ID PK FROM HOMEPAGE.BOARD_MENTIONS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.BOARD_MENTIONS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.BOAR_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.DELE_TMP_ORG_IDX  ON HOMEPAGE.DELETED_STORIES_QUEUE (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT QUEUE_ID PK FROM HOMEPAGE.DELETED_STORIES_QUEUE WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.DELETED_STORIES_QUEUE SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.DELE_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_C_TMP_ORG_IDX  ON HOMEPAGE.NR_COMM_SETTINGS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT COMM_ID PK FROM HOMEPAGE.NR_COMM_SETTINGS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_COMM_SETTINGS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_C_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_D_TMP_ORG_IDX  ON HOMEPAGE.NR_DISCOVERY_VIEW (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_DISCOVERY_VIEW WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_DISCOVERY_VIEW SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_D_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_P_TMP_ORG_IDX  ON HOMEPAGE.NR_PROFILES_VIEW (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_PROFILES_VIEW WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_PROFILES_VIEW SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_P_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_N_TMP_ORG_IDX  ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_NOTIFICATION_SENT_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_NOTIFICATION_SENT_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_N_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_N_TMP_ORG_IDX  ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_N_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_S_TMP_ORG_IDX  ON HOMEPAGE.NR_SAVED_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_SAVED_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_SAVED_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_S_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_T_TMP_ORG_IDX  ON HOMEPAGE.NR_TOPICS_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_TOPICS_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_TOPICS_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_T_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_M_TMP_ORG_IDX  ON HOMEPAGE.NR_MENTIONS_READERS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT CATEGORY_READER_ID PK FROM HOMEPAGE.NR_MENTIONS_READERS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_MENTIONS_READERS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_M_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_A_TMP_ORG_IDX  ON HOMEPAGE.NR_AS_SEEDLIST (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT SEEDLIST_ID PK FROM HOMEPAGE.NR_AS_SEEDLIST WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_AS_SEEDLIST SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_A_TMP_ORG_IDX;
 COMMIT;

COMMIT;

 CREATE INDEX HOMEPAGE.NR_A_TMP_ORG_IDX  ON HOMEPAGE.NR_AS_CONTENT_INDEX_STATS (ORGANIZATION_ID) TABLESPACE NEWSINDEXTABSPACE;
 COMMIT;

 DECLARE CURSOR cur IS SELECT STAT_ID PK FROM HOMEPAGE.NR_AS_CONTENT_INDEX_STATS WHERE ORGANIZATION_ID IS NULL FOR UPDATE; 
 
 
                BEGIN 
                        FOR rec IN cur LOOP 
                        	UPDATE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS SET ORGANIZATION_ID = '00000000-0000-0000-0000-000000000000' WHERE CURRENT OF cur; 
                        END LOOP; 
                        COMMIT; 
                END; 
 / 
 DROP INDEX HOMEPAGE.NR_A_TMP_ORG_IDX;
 COMMIT;

COMMIT;

-- RESTORING FK
ALTER TABLE HOMEPAGE.NR_AS_SEEDLIST ADD CONSTRAINT FK_AS_SEEDLIST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.METRIC_STAT ADD CONSTRAINT FK_METRIC_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_OBJECT_REFERENCE ADD CONSTRAINT FK_BRD_OBJ_REFERENCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.MT_CFG_FILES ADD CONSTRAINT FK_CFG_FILE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_COMMENT_CONTENT ADD CONSTRAINT FK_NEWS_COMMENT_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_WIDGET_TAB ADD CONSTRAINT FK_WIDGET_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_AGGREGATED_READERS ADD CONSTRAINT FK_AGG_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NETWORK ADD CONSTRAINT FK_NETWORK_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_MENTIONS_READERS ADD CONSTRAINT FK_MENT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_EXTERNAL_READERS ADD CONSTRAINT FK_EXT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_WIKIS_READERS ADD CONSTRAINT FK_WIKIS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_CONTENT_INDEX_STATS ADD CONSTRAINT FK_AS_CNT_INDEX_STATS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.PREREQ ADD CONSTRAINT FK_PREREQ_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIONABLE_READERS ADD CONSTRAINT FK_ACT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_VIEW ADD CONSTRAINT FK_PRF_VIEW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.DELETED_STORIES_QUEUE ADD CONSTRAINT FK_DEL_STORIES_QUEUE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_MENTIONS ADD CONSTRAINT FK_BOARD_MENTIONS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB_INST ADD CONSTRAINT FK_TAB_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESPONSES_READERS ADD CONSTRAINT FK_RESP_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_RESOURCE ADD CONSTRAINT FK_RESOURCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_WIDGET_INST ADD CONSTRAINT FK_WIDGET_INST_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_UI ADD CONSTRAINT FK_UI_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_STATUS_UPDATE_READERS ADD CONSTRAINT FK_SU_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_TOPICS_READERS ADD CONSTRAINT FK_TOPICS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_CURRENT_STATUS ADD CONSTRAINT FK_BOARD_CURRENT_STATUS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_NETWORK ADD CONSTRAINT FK_NEWS_STATUS_NETWORK_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_USER_PREFS ADD CONSTRAINT FK_USER_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_AS_COUNTS ADD CONSTRAINT FK_AS_COUNT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_PROFILES_READERS ADD CONSTRAINT FK_PROF_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES ADD CONSTRAINT FK_STORIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_SETTINGS ADD CONSTRAINT FK_COMM_SETTINGS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.HP_TAB ADD CONSTRAINT FK_TAB_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_RECOMMENDATIONS ADD CONSTRAINT FK_BRD_RECOMM_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_PERSON_FOLLOW ADD CONSTRAINT FK_COMM_PERSON_FOLLOW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.WIDGET ADD CONSTRAINT FK_WIDGET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.IMG_CACHE ADD CONSTRAINT FK_IMG_CACHE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NT_REPLYTO_RECIPIENT ADD CONSTRAINT FK_REPLYTO_RECIPIENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD ADD CONSTRAINT FK_BOARD_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_FOLLOWS ADD CONSTRAINT FK_FOLLOWS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMM_FOLLOW ADD CONSTRAINT FK_COMM_FOLLOW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS ADD CONSTRAINT FK_NOT_REC_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NT_REPLYTO ADD CONSTRAINT FK_REPLYTO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_COMMENTS ADD CONSTRAINT FK_BOARD_COMMENTS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_FILES_READERS ADD CONSTRAINT FK_FILES_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_DISCOVERY_VIEW ADD CONSTRAINT FK_DISCOVERY_VIEW_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.EMD_RESOURCE_PREF ADD CONSTRAINT FK_EMD_RES_PREF_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_STORIES_CONTENT ADD CONSTRAINT FK_STORIES_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.EMD_TRANCHE ADD CONSTRAINT FK_EMD_TRANCHE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_BOOKMARKS_READERS ADD CONSTRAINT FK_BOOK_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.LOGINNAME ADD CONSTRAINT FK_LN_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.PERSON ADD CONSTRAINT FK_PERSON_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.MT_CFG_SETTINGS ADD CONSTRAINT FK_CFG_SET_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES_ARCHIVE ADD CONSTRAINT FK_ENTRIES_ARCHIVE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_SAVED_READERS ADD CONSTRAINT FK_SAVED_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_COMMUNITIES_READERS ADD CONSTRAINT FK_COMM_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NOTIFICATION_SENT_READERS ADD CONSTRAINT FK_NOT_SENT_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_COMMENT ADD CONSTRAINT FK_STATUS_COMMENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_SOURCE_TYPE ADD CONSTRAINT FK_SOURCE_TYPE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_TAGS_READERS ADD CONSTRAINT FK_TAGS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_BLOGS_READERS ADD CONSTRAINT FK_BLOGS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.EMD_EMAIL_PREFS ADD CONSTRAINT FK_EMD_EMAIL_PREFS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_ENTRIES ADD CONSTRAINT FK_ENTRIES_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_SOURCE ADD CONSTRAINT FK_SOURCE_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.BOARD_ENTRIES ADD CONSTRAINT FK_BOARD_ENTRIES_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_ACTIVITIES_READERS ADD CONSTRAINT FK_ACTIVITIES_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.EMD_TRANCHE_INFO ADD CONSTRAINT FK_EMD_TRANCHE_INFO_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_NEWS_STATUS_CONTENT ADD CONSTRAINT FK_STATUS_CONTENT_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;
ALTER TABLE HOMEPAGE.NR_FORUMS_READERS ADD CONSTRAINT FK_FORUMS_READERS_ORG_ID FOREIGN KEY (ORGANIZATION_ID) REFERENCES HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_ID);
COMMIT;

-- RESTORING INDEXES
CREATE INDEX HOMEPAGE.UNQ_ORG_EXID ON HOMEPAGE.MT_ORGANIZATION (ORGANIZATION_EXID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.PERSON_EXID ON HOMEPAGE.PERSON (EXID, ORGANIZATION_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.LOGINNAME_UNIQUE ON HOMEPAGE.LOGINNAME (LOGINNAME, ORGANIZATION_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.UNQ_ORG_NAME ON HOMEPAGE.MT_CFG_SETTINGS (NAME, ORGANIZATION_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.NR_SRC_TYPE_ORG_UIDX ON HOMEPAGE.NR_SOURCE_TYPE (SOURCE_TYPE, ORGANIZATION_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.SEQ_NUMBER_UNIQUE ON HOMEPAGE.EMD_TRANCHE (SEQ_NUMBER, ORGANIZATION_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.AGGREGATED_READERS_SRC_IX ON HOMEPAGE.NR_AGGREGATED_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.RESPONSES_READERS_SRC_IX ON HOMEPAGE.NR_RESPONSES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.PROFILES_READERS_SRC_IX ON HOMEPAGE.NR_PROFILES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.COMM_READERS_SRC_IX ON HOMEPAGE.NR_COMMUNITIES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.ACTIVITIES_READERS_SRC_IX ON HOMEPAGE.NR_ACTIVITIES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.BLOGS_READERS_SRC_IX ON HOMEPAGE.NR_BLOGS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.BOOKMARKS_READERS_SRC_IX ON HOMEPAGE.NR_BOOKMARKS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.FILES_READERS_SRC_IX ON HOMEPAGE.NR_FILES_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.FORUMS_READERS_SRC_IX ON HOMEPAGE.NR_FORUMS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.WIKIS_READERS_SRC_IX ON HOMEPAGE.NR_WIKIS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.TAGS_READERS_SRC_IX ON HOMEPAGE.NR_TAGS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.STATUS_READERS_SRC_IX ON HOMEPAGE.NR_STATUS_UPDATE_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.EXTERNAL_READERS_SRC_IX ON HOMEPAGE.NR_EXTERNAL_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.ACTIONABLE_READERS_SRC_IX ON HOMEPAGE.NR_ACTIONABLE_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.DISCOVERY_VIEW_ORG_IDX ON HOMEPAGE.NR_DISCOVERY_VIEW (ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, CREATION_DATE DESC, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.PROFILES_VIEW_SRC_IX ON HOMEPAGE.NR_PROFILES_VIEW (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.PROFILES_VIEW_ORG_IDX ON HOMEPAGE.NR_PROFILES_VIEW (ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, CREATION_DATE DESC, IS_BROADCAST, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.NOTIFICA_READERS_SRC_IX ON HOMEPAGE.NR_NOTIFICATION_SENT_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.NOT_REC_READERS_SRC_IX ON HOMEPAGE.NR_NOTIFICATION_RECEIV_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.SAVED_READERS_SRC_IX ON HOMEPAGE.NR_SAVED_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.TOPICS_READERS_SRC_IX ON HOMEPAGE.NR_TOPICS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.MENTIONS_READERS_SRC_IX ON HOMEPAGE.NR_MENTIONS_READERS (READER_ID, ORGANIZATION_ID, USE_IN_ROLLUP, IS_VISIBLE, IS_BROADCAST, CREATION_DATE DESC, ROLLUP_ENTRY_ID, SOURCE_TYPE, STORY_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.IMG_CACHE_URL_IDX ON HOMEPAGE.IMG_CACHE (ORIGINAL_URL_MD5, ORGANIZATION_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;
CREATE INDEX HOMEPAGE.NR_AS_COUNT_ORG_IDX ON HOMEPAGE.NR_AS_COUNTS (ORGANIZATION_ID) TABLESPACE  NEWSINDEXTABSPACE;
COMMIT;

------------------------------------------------------------------------------------------------
-- UPDATE SCHEMA VERSION AND RELEASE VERSION to 460
------------------------------------------------------------------------------------------------
UPDATE  HOMEPAGE.HOMEPAGE_SCHEMA SET DBSCHEMAVER = 460, RELEASEVER = '4.6.0.0' 
WHERE   DBSCHEMAVER = 459; 

------------------------------------------------------------------------------------------------

COMMIT;

-- +++++++++++++++++++++++++++++++++++++++++++++
-- +++++++++++++++++++++++++++++++++++++++++++++
--					end	FIXUP 460
-- +++++++++++++++++++++++++++++++++++++++++++++
-- +++++++++++++++++++++++++++++++++++++++++++++


--------------------------------------
-- DISCONNECT
--------------------------------------
DISCONNECT ALL;

QUIT;