-- ***************************************************************** 
--                                                                   
-- IBM Confidential                                                  
--                                                                   
-- OCO Source Materials                                              
--                                                                   
-- Copyright IBM Corp. 2008, 2015                                    
--                                                                   
-- The source code for this program is not published or otherwise    
-- divested of its trade secrets, irrespective of what has been      
-- deposited with the U.S. Copyright Office.                         
--                                                                   
-- ***************************************************************** 

USE HOMEPAGE;
GO


UPDATE STATISTICS HOMEPAGE.HOMEPAGE_SCHEMA;
GO

UPDATE STATISTICS HOMEPAGE.PERSON;
GO

UPDATE STATISTICS HOMEPAGE.LOGINNAME;
GO

UPDATE STATISTICS HOMEPAGE.PREREQ;
GO

UPDATE STATISTICS HOMEPAGE.WIDGET;
GO

UPDATE STATISTICS HOMEPAGE.HP_UI;
GO

UPDATE STATISTICS HOMEPAGE.HP_TAB;
GO

UPDATE STATISTICS HOMEPAGE.HP_TAB_INST;
GO

UPDATE STATISTICS HOMEPAGE.HP_WIDGET_INST;
GO

UPDATE STATISTICS HOMEPAGE.HP_WIDGET_TAB;
GO

UPDATE STATISTICS HOMEPAGE.NT_NOTIFICATION;
GO

UPDATE STATISTICS HOMEPAGE.NT_NOTIFICATION_RECIPIENT;
GO

UPDATE STATISTICS HOMEPAGE.NR_SOURCE;
GO

UPDATE STATISTICS HOMEPAGE.NR_SUBSCRIPTION;
GO

UPDATE STATISTICS HOMEPAGE.NR_NEWS_RECORDS;
GO

UPDATE STATISTICS HOMEPAGE.NR_TEMPLATE;
GO

UPDATE STATISTICS HOMEPAGE.NR_EVENT_RECORDS;
GO

UPDATE STATISTICS HOMEPAGE.EMD_JOBS;
GO

UPDATE STATISTICS HOMEPAGE.EMD_JOBS_STATS;
GO

UPDATE STATISTICS HOMEPAGE.EMD_RECIPIENTS;
GO

UPDATE STATISTICS  HOMEPAGE.NR_SCHEDULER_LMGR;
GO

UPDATE STATISTICS  HOMEPAGE.NR_SCHEDULER_LMPR;
GO

UPDATE STATISTICS  HOMEPAGE.NR_SCHEDULER_TASK;
GO

UPDATE STATISTICS  HOMEPAGE.NR_SCHEDULER_TREG;
GO

UPDATE STATISTICS  HOMEPAGE.SR_INDEXINGTASKDEF;
GO

UPDATE STATISTICS  HOMEPAGE.SR_OPTIMIZETASKDEF;
GO

UPDATE STATISTICS  HOMEPAGE.SR_TASKDEF;
GO

UPDATE STATISTICS  HOMEPAGE.LOTUSCONNECTIONSLMGR;
GO

UPDATE STATISTICS  HOMEPAGE.LOTUSCONNECTIONSLMPR;
GO

UPDATE STATISTICS  HOMEPAGE.LOTUSCONNECTIONSTASK;
GO
